### ISSUE TITLE
langchain.vectorstores.MatchingEngine.from_components() throws InvalidArgument exception

### ISSUE THREAD

**Issue by sgalij** [langchain-ai/langchain#10050]
### System Info

langchain==0.0.249
Windows
Python 3.11.4

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

The official example described here:
https://python.langchain.com/docs/integrations/vectorstores/matchingengine#create-vectorstore-from-texts

Does not work.

My code throws beloe exception:
from langchain.vectorstores import MatchingEngine

texts = [
  "The cat sat on",
  "the mat.",
  "I like to",
  "eat pizza for",
  "dinner.",
  "The sun sets",
  "in the west.",
]

vector_store = MatchingEngine.from_components(
  project_id="",
  region="",
  gcs_bucket_name="",
  index_id="",
  endpoint_id="",
)

### Expected behavior

Traceback (most recent call last):
  File "C:\GitHub\onecloud-chatbot\onecloud-chatbot\Lib\site-packages\google\api_core\grpc_helpers.py", line 72, in error_remapped_callable
    return callable_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GitHub\onecloud-chatbot\onecloud-chatbot\Lib\site-packages\grpc\_channel.py", line 1030, in __call__
    return _end_unary_response_blocking(state, call, False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GitHub\onecloud-chatbot\onecloud-chatbot\Lib\site-packages\grpc\_channel.py", line 910, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
        details = "Request contains an invalid argument."
        debug_error_string = "UNKNOWN:Error received from peer ipv4:172.217.16.42:443 {created_time:"2023-08-31T14:00:16.506362524+00:00", grpc_status:3, grpc_message:"Request contains an invalid argument."}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\GitHub\onecloud-chatbot\matching_engine_insert.py", line 13, in <module>
    vector_store = MatchingEngine.from_components(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GitHub\onecloud-chatbot\onecloud-chatbot\Lib\site-packages\langchain\vectorstores\matching_engine.py", line 280, in from_components
    endpoint = cls._create_endpoint_by_id(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GitHub\onecloud-chatbot\onecloud-chatbot\Lib\site-packages\langchain\vectorstores\matching_engine.py", line 386, in _create_endpoint_by_id
    return aiplatform.MatchingEngineIndexEndpoint(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GitHub\onecloud-chatbot\onecloud-chatbot\Lib\site-packages\google\cloud\aiplatform\matching_engine\matching_engine_index_endpoint.py", line 130, in __init__
    self._gca_resource = self._get_gca_resource(resource_name=index_endpoint_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GitHub\onecloud-chatbot\onecloud-chatbot\Lib\site-packages\google\cloud\aiplatform\base.py", line 648, in _get_gca_resource
    return getattr(self.api_client, self._getter_method)(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GitHub\onecloud-chatbot\onecloud-chatbot\Lib\site-packages\google\cloud\aiplatform_v1\services\index_endpoint_service\client.py", line 707, in get_index_endpoint
    response = rpc(
               ^^^^
  File "C:\GitHub\onecloud-chatbot\onecloud-chatbot\Lib\site-packages\google\api_core\gapic_v1\method.py", line 113, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GitHub\onecloud-chatbot\onecloud-chatbot\Lib\site-packages\google\api_core\retry.py", line 349, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "C:\GitHub\onecloud-chatbot\onecloud-chatbot\Lib\site-packages\google\api_core\retry.py", line 191, in retry_target
    return target()
           ^^^^^^^^
  File "C:\GitHub\onecloud-chatbot\onecloud-chatbot\Lib\site-packages\google\api_core\grpc_helpers.py", line 74, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.InvalidArgument: 400 Request contains an invalid argument.

**Comment by sgalij** [comment]
I removed values of parameters on purpose.
I think the issue was that "endpoint_id" had incorrect value (deployedIndexId instead of indexEndpoint).

Now I'm struggling with passing optional embedding parameter.
I would like to pass the vertexai.preview.language_models.TextEmbeddingModel to from_components() method but I've got an error: 
AttributeError: '_PreviewTextEmbeddingModel' object has no attribute 'embed_documents'

**Comment by thisjustinh** [comment]
Hi @sgalij I am guessing you figured out the issue with the AttributeError but just in case, if you use the `VertexAIEmbeddings` from `langchain.embeddings` that should work since it has the `embed_documents` function. Ran into this issue today; your comment about the endpoint ID helped a lot thanks!
