### ISSUE TITLE
Multiple bases have instance lay-out conflict

### ISSUE THREAD

**Issue by alpha-21** [langchain-ai/langchain#10179]
### System Info

torch = "2.0.1"
transformers = "4.31.0"
langchain= "0.0.251"
kor= "0.13.0"
openai= "0.27.8"
pydantic= "1.10.8"
python_version = "3.9"

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from db.tools import DbTools
from langchain.chat_models import ChatOpenAI
from kor.nodes import Object, Text, Number
from kor import create_extraction_chain, Object, Text 

llm = ChatOpenAI(
    model_name="gpt-3.5-turbo",
    temperature=0,
    max_tokens=2000,
    frequency_penalty=0,
    presence_penalty=0,
    openai_api_key = "" ,
    top_p=1.0,
)

### Expected behavior

Hello I encountered the following error when trying to import the langchain.schema module:
Traceback (most recent call last):
  File "/home/alpha/platform/shared/libpython/computation/fine_instruction_GPT.py", line 2, in <module>
    from langchain.chat_models import ChatOpenAI
  File "/home/alpha/.local/share/virtualenvs/platform-_bj8LfuO/lib/python3.9/site-packages/langchain/__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "/home/alpha/.local/share/virtualenvs/platform-_bj8LfuO/lib/python3.9/site-packages/langchain/agents/__init__.py", line 31, in <module>
    from langchain.agents.agent import (
  File "/home/alpha/.local/share/virtualenvs/platform-_bj8LfuO/lib/python3.9/site-packages/langchain/agents/agent.py", line 15, in <module>
    from langchain.agents.agent_iterator import AgentExecutorIterator
  File "/home/alpha/.local/share/virtualenvs/platform-_bj8LfuO/lib/python3.9/site-packages/langchain/agents/agent_iterator.py", line 21, in <module>
    from langchain.callbacks.manager import (
  File "/home/alpha/.local/share/virtualenvs/platform-_bj8LfuO/lib/python3.9/site-packages/langchain/callbacks/__init__.py", line 10, in <module>
    from langchain.callbacks.aim_callback import AimCallbackHandler
  File "/home/alpha/.local/share/virtualenvs/platform-_bj8LfuO/lib/python3.9/site-packages/langchain/callbacks/aim_callback.py", line 5, in <module>
    from langchain.schema import AgentAction, AgentFinish, LLMResult
  File "/home/alpha/.local/share/virtualenvs/platform-_bj8LfuO/lib/python3.9/site-packages/langchain/schema/__init__.py", line 4, in <module>
    from langchain.schema.memory import BaseChatMessageHistory, BaseMemory
  File "/home/alpha/.local/share/virtualenvs/platform-_bj8LfuO/lib/python3.9/site-packages/langchain/schema/memory.py", line 7, in <module>
    from langchain.schema.messages import AIMessage, BaseMessage, HumanMessage
  File "/home/alpha/.local/share/virtualenvs/platform-_bj8LfuO/lib/python3.9/site-packages/langchain/schema/messages.py", line 147, in <module>
    class HumanMessageChunk(HumanMessage, BaseMessageChunk):
  File "pydantic/main.py", line 367, in pydantic.main.ModelMetaclass.__new__
  File "/usr/lib/python3.9/abc.py", line 85, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
TypeError: multiple bases have instance lay-out conflict

**Comment by alpha-21** [comment]
Thank but i have the same issues

**Comment by Veghit** [comment]
I have the same issue. Updating Pydantic to 1.10.12 solved it, but if conflicts with other requirements in my project.

**Comment by khanhphan1311** [comment]
> I have the same issue. Updating Pydantic to 1.10.12 solved it, but if conflicts with other requirements in my project.

This works for me like magic. Many thanks.

**Comment by shuish0071** [comment]
> I have the same issue. Updating Pydantic to 1.10.12 solved it, but if conflicts with other requirements in my project.

Thank you so muck, it works !

**Comment by HissaanAli** [comment]
> I have the same issue. Updating Pydantic to 1.10.12 solved it, but if conflicts with other requirements in my project.

Same, worked for me as well.

**Comment by haiwang-joe** [comment]
> I have the same issue. Updating Pydantic to 1.10.12 solved it, but if conflicts with other requirements in my project.

I works for me, thanks.
