### ISSUE TITLE
Issue: SQLDatabaseToolkit inconsistency

### ISSUE THREAD

**Issue by hugoferrero** [langchain-ai/langchain#10205]
I have the following code (see below). I have two prompts. One works ok (p1), and the other (p2) throws following error (complete error below): 
`OutputParserException: Could not parse LLM output: I don't know how to answer the question because I don't have access to the casos_perfilados_P2 table.` 

`p1 : Seleccionar los campos linea, nivel y genero, que contengan el valor F en genero y el valor D2 en el campo nse. Limitar el número de registros a 3. Armar un dataframe de pandas con el resultado anterior. `

`p2 : Seleccionar los campos linea y fecha, donde el campo fecha es mayor o igual a 2023-02-18 y menor o igual a 2023-02-24. Agrupar y sumar los valores del campo linea por el campo fecha. Armar un dataframe de pandas con el resultado anterior. `

...Why p2 has "access" issues while p1 doesn't...any clues ?

```python
# google
import vertexai

# Alchemy
from sqlalchemy import *
from sqlalchemy.schema import *

# Langchain
from langchain.agents import create_sql_agent
from langchain.agents.agent_toolkits import SQLDatabaseToolkit
from langchain.sql_database import SQLDatabase
from langchain.callbacks import StreamlitCallbackHandler
from langchain.llms import VertexAI
from langchain.agents.agent_types import AgentType
from langchain.agents import initialize_agent
from langchain.tools.python.tool import PythonREPLTool
from langchain.agents.agent_toolkits import create_python_agent
from langchain.tools import Tool

# Streamlit
import streamlit as st


# Settings

PROJECT_ID = "xxxxxxx"
REGION = "xxxxxxx" 
dataset = "xxxxxxx"


# Initialize Vertex AI SDK
vertexai.init(project=PROJECT_ID, location=REGION)


# BQ db
sqlalchemy_url = f'bigquery://{PROJECT_ID}/{dataset}'
db = SQLDatabase.from_uri(sqlalchemy_url)

# llm 
llm = VertexAI(
    model_name="text-bison@001",
    max_output_tokens=1024,
    temperature=0,
    top_p=0.8,
    top_k=40,
    verbose=True
             )
# SQL Agent

sql_agent = create_sql_agent(
llm=llm,
toolkit=SQLDatabaseToolkit(db=db, llm=llm),
verbose=True,
top_k=1000,
agent_type=AgentType.ZERO_SHOT_REACT_DESCRIPTION
                                 )

# Python Agent

python_agent = create_python_agent(
    llm,
    tool=PythonREPLTool(),
    verbose=True
)

# Main Agent
agent = initialize_agent(
    tools=[
        Tool(
            name="SQLAgent",
            func=sql_agent.run,
            description="""Useful to execute sql commands""",
        ),
        Tool(
            name="PythonAgent",
            func=python_agent.run,
            description="""Useful to run python commands""",
        ),
    ],
    llm=llm,
    agent_type=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
    handle_parsing_errors=True,
    verbose=True,
)


if prompt := st.chat_input():
    st.chat_message("user").write(prompt)
    with st.chat_message("assistant"):
        st_callback = StreamlitCallbackHandler(st.container())
        response = agent.run(prompt)
        st.write(response)



```

```bash
> Entering new AgentExecutor chain...
Action: sql_db_list_tables
Action Input: 
Observation: casos_perfilados_P2
Thought:2023-09-04 19:23:34.050 Uncaught app exception
Traceback (most recent call last):
  File "/home/flow/anaconda3/envs/llm/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/home/flow/Documentos/genai/chat1.py", line 91, in <module>
    response = agent.run(prompt)
  File "/home/flow/anaconda3/envs/llm/lib/python3.10/site-packages/langchain/chains/base.py", line 475, in run
    return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[
  File "/home/flow/anaconda3/envs/llm/lib/python3.10/site-packages/langchain/chains/base.py", line 282, in __call__
    raise e
  File "/home/flow/anaconda3/envs/llm/lib/python3.10/site-packages/langchain/chains/base.py", line 276, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/home/flow/anaconda3/envs/llm/lib/python3.10/site-packages/langchain/agents/agent.py", line 1036, in _call
    next_step_output = self._take_next_step(
  File "/home/flow/anaconda3/envs/llm/lib/python3.10/site-packages/langchain/agents/agent.py", line 891, in _take_next_step
    observation = tool.run(
  File "/home/flow/anaconda3/envs/llm/lib/python3.10/site-packages/langchain/tools/base.py", line 351, in run
    raise e
  File "/home/flow/anaconda3/envs/llm/lib/python3.10/site-packages/langchain/tools/base.py", line 323, in run
    self._run(*tool_args, run_manager=run_manager, **tool_kwargs)
  File "/home/flow/anaconda3/envs/llm/lib/python3.10/site-packages/langchain/tools/base.py", line 493, in _run
    self.func(
  File "/home/flow/anaconda3/envs/llm/lib/python3.10/site-packages/langchain/chains/base.py", line 475, in run
    return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[
  File "/home/flow/anaconda3/envs/llm/lib/python3.10/site-packages/langchain/chains/base.py", line 282, in __call__
    raise e
  File "/home/flow/anaconda3/envs/llm/lib/python3.10/site-packages/langchain/chains/base.py", line 276, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/home/flow/anaconda3/envs/llm/lib/python3.10/site-packages/langchain/agents/agent.py", line 1036, in _call
    next_step_output = self._take_next_step(
  File "/home/flow/anaconda3/envs/llm/lib/python3.10/site-packages/langchain/agents/agent.py", line 844, in _take_next_step
    raise e
  File "/home/flow/anaconda3/envs/llm/lib/python3.10/site-packages/langchain/agents/agent.py", line 833, in _take_next_step
    output = self.agent.plan(
  File "/home/flow/anaconda3/envs/llm/lib/python3.10/site-packages/langchain/agents/agent.py", line 457, in plan
    return self.output_parser.parse(full_output)
  File "/home/flow/anaconda3/envs/llm/lib/python3.10/site-packages/langchain/agents/mrkl/output_parser.py", line 52, in parse
    raise OutputParserException(
langchain.schema.output_parser.OutputParserException: Could not parse LLM output: `I don't know how to answer the question because I don't have access to the casos_perfilados_P2 table.`
```

**Comment by hugoferrero** [comment]
issue was fixed by adding extra info about the table. Thanks.
