### ISSUE TITLE
HuggingFaceBgeEmbeddings Error, Please help!

### ISSUE THREAD

**Issue by bathroomhu** [langchain-ai/langchain#10263]
### System Info

Yesterday is works, someone accidentally update langchain now the whole platform is down.

We built the whole platform using his code all over the place. Now nothing works. 
We have around 50 models. All our models are build like this and we just went live as a startup. 

**We are scrabbling here guys. Please help us.**

`
from langchain.embeddings import HuggingFaceBgeEmbeddings

embeddings = HuggingFaceBgeEmbeddings(model_name="BAAI/bge-large-en")

news_instance = FAISS.load_local("federal_legislativeinstruments_inforce_index", embeddings)

data_state_nsw_legisation_index_instance = FAISS.load_local("data_indexes/federal/federal_legislativeinstruments_inforce_index", embeddings)

data_state_nsw_legisation_runner = RetrievalQA.from_chain_type(llm=ChatOpenAI(model_name="gpt-3.5-turbo", temperature=0,
                                                openai_api_key=openai_api_key_value),
                                                chain_type="stuff",
                                                retriever=data_state_nsw_legisation_index_instance.as_retriever())
`

Please, please help. How to we refactor so it works. How team is going crazy to get it live again, Our very first customers are ringing us complaining. Please help.

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain.embeddings import HuggingFaceBgeEmbeddings

embeddings = HuggingFaceBgeEmbeddings(model_name="BAAI/bge-large-en")

news_instance = FAISS.load_local("federal_legislativeinstruments_inforce_index", embeddings)

data_state_nsw_legisation_index_instance = FAISS.load_local("data_indexes/federal/federal_legislativeinstruments_inforce_index", embeddings)

data_state_nsw_legisation_runner = RetrievalQA.from_chain_type(llm=ChatOpenAI(model_name="gpt-3.5-turbo", temperature=0,
                                                openai_api_key=openai_api_key_value),
                                                chain_type="stuff",
                                                retriever=data_state_nsw_legisation_index_instance.as_retriever())

### Expected behavior

How load the embedding like yesterday and all the time before.

**Comment by bathroomhu** [comment]
Thank you so much for helping us!!! We have refactored and getting this exception. Please help, and thank you so much 🙏 

`Traceback (most recent call last):
  File "/opt/homebrew/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.10/site-packages/flask/cli.py", line 1050, in main
    cli.main()
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/flask/cli.py", line 911, in run_command
    raise e from None
  File "/opt/homebrew/lib/python3.10/site-packages/flask/cli.py", line 897, in run_command
    app = info.load_app()
  File "/opt/homebrew/lib/python3.10/site-packages/flask/cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "/opt/homebrew/lib/python3.10/site-packages/flask/cli.py", line 218, in locate_app
    __import__(module_name)
  File "/Users/malcolm.fitzgerald/Desktop/ailearning/legalmind/app.py", line 49, in <module>
    embeddings = SelfHostedHuggingFaceEmbeddings(model_name=model_name, hardware=gpu)
  File "/opt/homebrew/lib/python3.10/site-packages/langchain/embeddings/self_hosted_hugging_face.py", line 100, in __init__
    super().__init__(load_fn_kwargs=load_fn_kwargs, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/langchain/llms/self_hosted.py", line 153, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for SelfHostedHuggingFaceEmbeddings
model_name`

**Comment by bathroomhu** [comment]
we had to install version langchain==0.0.279 to het it working. is it still supported?

**Comment by deanchanter** [comment]
Working in 0.0.285!
