### ISSUE TITLE
Errors about ErnieBotChat

### ISSUE THREAD

**Issue by liye199033** [langchain-ai/langchain#10309]
### Issue you'd like to raise.

my test code
```
import unittest
from langchain.chat_models import ErnieBotChat
from langchain.schema import (
    HumanMessage
)


class TestErnieBotCase(unittest.TestCase):
    def test_ernie_bot(self):
        chat_llm = ErnieBotChat(
            ernie_client_id="xxx",
            ernie_client_secret="xxx"
        )
        result = chat_llm.generate(messages=[HumanMessage(content="请列出清朝的所有皇帝的姓名和年号")])
        print(result)


if __name__ == '__main__':
    unittest.main()
```
it's return error：
```
Error
Traceback (most recent call last):
  File "/Users/keigo/Workspace/study/langchain/tests/test_erniebot.py", line 14, in test_ernie_bot
    result = chat_llm.generate(messages=[HumanMessage(content="请列出清朝的所有皇帝的姓名和年号")])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/keigo/Workspace/study/langchain/venv/lib/python3.11/site-packages/langchain/chat_models/base.py", line 309, in generate
    raise e
  File "/Users/keigo/Workspace/study/langchain/venv/lib/python3.11/site-packages/langchain/chat_models/base.py", line 299, in generate
    self._generate_with_cache(
  File "/Users/keigo/Workspace/study/langchain/venv/lib/python3.11/site-packages/langchain/chat_models/base.py", line 446, in _generate_with_cache
    return self._generate(
           ^^^^^^^^^^^^^^^
  File "/Users/keigo/Workspace/study/langchain/venv/lib/python3.11/site-packages/langchain/chat_models/ernie.py", line 157, in _generate
    "messages": [_convert_message_to_dict(m) for m in messages],
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/keigo/Workspace/study/langchain/venv/lib/python3.11/site-packages/langchain/chat_models/ernie.py", line 157, in <listcomp>
    "messages": [_convert_message_to_dict(m) for m in messages],
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/keigo/Workspace/study/langchain/venv/lib/python3.11/site-packages/langchain/chat_models/ernie.py", line 31, in _convert_message_to_dict
    raise ValueError(f"Got unknown type {message}")
ValueError: Got unknown type ('content', '请列出清朝的所有皇帝的姓名和年号')
```

in ernie.py file function _convert_message_to_dict,the variable message is of type tuple。

**Comment by liye199033** [comment]
Thank you. See what the problem is
