### ISSUE TITLE
Langchain Quickstart is not working for me

### ISSUE THREAD

**Issue by FilipMasar** [langchain-ai/langchain#10314]
### System Info

Apple Macbook M1 Pro
python: 3.11.2
langchain: 0.0.283
pydantic: 2.3.0

### Who can help?

@hwchase17 @agola11 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. pip3.11 install langchain
2. run python3.11 in terminal
3. execute `from langchain.llms import OpenAI` which produce following error for me

```
Python 3.11.2 (main, Feb 16 2023, 02:55:59) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from langchain.llms import OpenAI
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/agents/__init__.py", line 31, in <module>
    from langchain.agents.agent import (
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/agents/agent.py", line 14, in <module>
    from langchain.agents.agent_iterator import AgentExecutorIterator
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/agents/agent_iterator.py", line 30, in <module>
    from langchain.tools import BaseTool
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/tools/__init__.py", line 25, in <module>
    from langchain.tools.arxiv.tool import ArxivQueryRun
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/tools/arxiv/tool.py", line 8, in <module>
    from langchain.utilities.arxiv import ArxivAPIWrapper
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/utilities/__init__.py", line 7, in <module>
    from langchain.utilities.apify import ApifyWrapper
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/utilities/apify.py", line 3, in <module>
    from langchain.document_loaders import ApifyDatasetLoader
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/document_loaders/__init__.py", line 76, in <module>
    from langchain.document_loaders.embaas import EmbaasBlobLoader, EmbaasLoader
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/document_loaders/embaas.py", line 54, in <module>
    class BaseEmbaasLoader(BaseModel):
  File "/opt/homebrew/lib/python3.11/site-packages/pydantic/main.py", line 204, in __new__
    fields[ann_name] = ModelField.infer(
                       ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pydantic/fields.py", line 488, in infer
    return cls(
           ^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pydantic/fields.py", line 419, in __init__
    self.prepare()
  File "/opt/homebrew/lib/python3.11/site-packages/pydantic/fields.py", line 539, in prepare
    self.populate_validators()
  File "/opt/homebrew/lib/python3.11/site-packages/pydantic/fields.py", line 801, in populate_validators
    *(get_validators() if get_validators else list(find_validators(self.type_, self.model_config))),
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pydantic/validators.py", line 696, in find_validators
    yield make_typeddict_validator(type_, config)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pydantic/validators.py", line 585, in make_typeddict_validator
    TypedDictModel = create_model_from_typeddict(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pydantic/annotated_types.py", line 35, in create_model_from_typeddict
    return create_model(typeddict_cls.__name__, **kwargs, **field_definitions)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pydantic/main.py", line 972, in create_model
    return type(__model_name, __base__, namespace)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pydantic/main.py", line 204, in __new__
    fields[ann_name] = ModelField.infer(
                       ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pydantic/fields.py", line 488, in infer
    return cls(
           ^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pydantic/fields.py", line 419, in __init__
    self.prepare()
  File "/opt/homebrew/lib/python3.11/site-packages/pydantic/fields.py", line 534, in prepare
    self._type_analysis()
  File "/opt/homebrew/lib/python3.11/site-packages/pydantic/fields.py", line 638, in _type_analysis
    elif issubclass(origin, Tuple):  # type: ignore
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/typing.py", line 1551, in __subclasscheck__
    return issubclass(cls, self.__origin__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
```

### Expected behavior

To be able to use langchain

**Comment by FilipMasar** [comment]
It was indeed issue with versions. Python 3.10 works
