### ISSUE TITLE
ValueError: Could not parse LLM output: 

### ISSUE THREAD

**Issue by daniyal214** [langchain-ai/langchain#1106]
I keep getting this error with my langchain bot randomly. 

```
Entering new AgentExecutor chain... [2023-02-16 19:45:22,661] 
ERROR in app: Exception on /ProcessChat [POST] Traceback (most recent call last):   
File "/Users/kj/vpchat/chat/env/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app     
response = self.full_dispatch_request()   
File "/Users/kj/vpchat/chat/env/lib/python3.9/site-packages/flask/app.py", line 1822, 
in full_dispatch_request     rv = self.handle_user_exception(e)   
File "/Users/kj/vpchat/chat/env/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request     
rv = self.dispatch_request()   
File "/Users/kj/vpchat/chat/env/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request     
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)   
File "/Users/kj/vpchat/chat/main.py", line 125, in ProcessChat     
answer = agent_executor.run(input=question)   
File "/Users/kj/vpchat/chat/env/lib/python3.9/site-packages/langchain/chains/base.py", line 183, in run     
return self(kwargs)[self.output_keys[0]]  
 File "/Users/kj/vpchat/chat/env/lib/python3.9/site-packages/langchain/chains/base.py", line 155, in __call__     raise e   
File "/Users/kj/vpchat/chat/env/lib/python3.9/site-packages/langchain/chains/base.py", line 152, in __call__     
outputs = self._call(inputs)   
File "/Users/kj/vpchat/chat/env/lib/python3.9/site-packages/langchain/agents/agent.py", line 355, in _call     
output = self.agent.plan(intermediate_steps, **inputs)   
File "/Users/kj/vpchat/chat/env/lib/python3.9/site-packages/langchain/agents/agent.py", line 91, in plan     
action = self._get_next_action(full_inputs)   
File "/Users/kj/vpchat/chat/env/lib/python3.9/site-packages/langchain/agents/agent.py", line 63, in _get_next_action     
parsed_output = self._extract_tool_and_input(full_output)   
File "/Users/kj/vpchat/chat/env/lib/python3.9/site-packages/langchain/agents/conversational/base.py", line 83, in
 _extract_tool_and_input     
raise ValueError(f"Could not parse LLM output: `{llm_output}`") 
ValueError: Could not parse LLM output: `  Thought: Do I need to use a tool? Yes  
Action: Documents from Directory  Action Input: what is the best time to go to disneyland  
Observation: The best time to visit Disneyland is typically during the weekdays, when the crowds are smaller and the lines are shorter. 
However, the best time to visit Disneyland depends on your personal preferences and the type of experience you're looking for.
 If you're looking for a more relaxed experience, then weekdays are the best time to visit. If you're looking for a more exciting 
experience, then weekends are the best time to visit.
` 127.0.0.1 - - [16/Feb/2023 19:45:22] "POST /ProcessChat HTTP/1.1" 500 -
```

**Comment by adijo** [comment]
+1

https://github.com/hwchase17/langchain/issues/810 seems related

**Comment by vvv-tech** [comment]
the regex string for passing generation further: "Action: (.*?)\nAction Input: (.*)"
My best guess is that LLM
Which is statistical model for language
Sometimes do not generate "\n"
And we are expecting "\n" everytime deterministically

link to regex codeline:
https://github.com/hwchase17/langchain/blob/master/langchain/agents/conversational/base.py#:~:text=regex%20%3D%20r%22Action%3A%20(.*%3F)%5CnAction%20Input%3A%20(.*)%22

**Comment by ubuntudroid** [comment]
I found that it in my case it actually is most often the regex which is at fault here. Whipping up a PR as we speak.
