### ISSUE TITLE
Issue: Fixed unicode decode byte error

### ISSUE THREAD

**Issue by hackedpassword** [langchain-ai/langchain#11359]
### Issue you'd like to raise.

Trying to submit a code update. This would be a first. Help a non software eng out. :)

Here's a manual diff of the intended change:
```
langchain\libs\langchain\langchain\document_loaders\text.py
<<[41]             with open(self.file_path, encoding=self.encoding) as f:
>>[41]            with open(self.file_path, encoding=self.encoding, errors='replace') as f:
```

The COMMIT_EDITMSG file:
"""
Solves unicode [codec can't decode byte] traceback error:

Traceback (most recent call last):
  File "C:\Program Files\Python3\Lib\site-packages\langchain\document_loaders\text.py", line 41, in load
    text = f.read()
           ^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa7 in position 549: invalid start byte
"""

The general flow used:
PS C:\dev\github\langchain\libs\langchain\langchain\document_loaders> notepad .\text.py
PS C:\dev\github\langchain\libs\langchain\langchain\document_loaders> git add text.py
PS C:\dev\github\langchain\libs\langchain\langchain\document_loaders> git checkout -b unicode_replace_fix
Switched to a new branch 'unicode_replace_fix'
PS C:\dev\github\langchain\libs\langchain\langchain\document_loaders> git commit -m "Solves unicode [codec can't decode byte] traceback error."
... // had to update user.name/email
PS C:\dev\github\langchain\libs\langchain\langchain\document_loaders> git commit --amend --reset-author
hint: Waiting for your editor to close the file... unix2dos: converting file C:/Dev/Github/langchain/.git/COMMIT_EDITMSG to DOS format...
dos2unix: converting file C:/Dev/Github/langchain/.git/COMMIT_EDITMSG to Unix format...
[unicode_replace_fix 09c9cb77e] Solves unicode [codec can't decode byte] traceback error:
 1 file changed, 1 insertion(+), 1 deletion(-)

// below, I got a github auth popup, went through, succeeded - then denied?
PS C:\dev\github\langchain\libs\langchain\langchain\document_loaders> git push origin unicode_replace_fix
info: please complete authentication in your browser...
remote: Permission to langchain-ai/langchain.git denied to hackedpassword.
fatal: unable to access 'https://github.com/langchain-ai/langchain/': The requested URL returned error: 403

// denied but no diff?
PS C:\dev\github\langchain> git diff HEAD
PS C:\dev\github\langchain> git status
On branch unicode_replace_fix
nothing to commit, working tree clean
PS C:\dev\github\langchain> git diff
PS C:\dev\github\langchain>

Maybe I'm up against a repo push permission issue?

**Comment by hackedpassword** [comment]
Heh, helpful bot. Love em.

I tried 2 things:

1. Created a general token on github, added GITHUB_TOKEN to my env vars.
2. Installed github desktop app, cloned and forked langchain, new branch on fork

Via github desktop, I've created:

https://github.com/langchain-ai/langchain/pull/11361

The bot is right and I suspected there may be use case considerations. From here, I really have no idea how the project handles subjective inclusions. I'm just happy to have made it this far. =)
