### ISSUE TITLE
Release 3.0.4 breaks compatibility with ddtrace.

### ISSUE THREAD

**Issue by Siddhartha90** [langchain-ai/langchain#11624]
### System Info

https://github.com/langchain-ai/langchain/releases/tag/v0.0.304

Reverting to 3.0.3 or under fixes it. The error looks something like (truncated confidential parts of the trace)

```
Traceback (most recent call last):
  ...
  File "/Users/sid.gupta/.pyenv/versions/3.11.3/lib/python3.11/site-packages/ddtrace/_monkey.py", line 205, in patch_all
    patch(raise_errors=False, **modules)
  File "/Users/sid.gupta/.pyenv/versions/3.11.3/lib/python3.11/site-packages/ddtrace/_monkey.py", line 245, in patch
    when_imported(module)(
  File "/Users/sid.gupta/.pyenv/versions/3.11.3/lib/python3.11/site-packages/ddtrace/vendor/wrapt/importer.py", line 284, in register
    register_post_import_hook(hook, name)
  File "/Users/sid.gupta/.pyenv/versions/3.11.3/lib/python3.11/site-packages/ddtrace/vendor/wrapt/decorators.py", line 470, in _synchronized
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sid.gupta/.pyenv/versions/3.11.3/lib/python3.11/site-packages/ddtrace/vendor/wrapt/importer.py", line 82, in register_post_import_hook
    hook(module)
  File "/Users/sid.gupta/.pyenv/versions/3.11.3/lib/python3.11/site-packages/ddtrace/_monkey.py", line 168, in on_import
    imported_module.patch()
  File "/Users/sid.gupta/.pyenv/versions/3.11.3/lib/python3.11/site-packages/ddtrace/contrib/langchain/patch.py", line 763, in patch
    if hasattr(langchain.embeddings, text_embedding_model):
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/sid.gupta/.pyenv/versions/3.11.3/lib/python3.11/site-packages/langchain/__init__.py", line 332, in __getattr__
    raise AttributeError(f"Could not find: {name}")
AttributeError: Could not find: embeddings
```

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Be on `ddtrace 1.17.6` and a langchain version >= 3.0.4. Running an webapp on hypercorn and fastAPI.

### Expected behavior

Don't throw this trace and block the application.

**Comment by dariatsenter** [comment]
Experiencing the same behavior when importing
`from langchain.prompts import (
    ChatPromptTemplate,
    HumanMessagePromptTemplate,
    SystemMessagePromptTemplate,
)`


```File "/usr/local/src/guidance_api/.venv/lib/python3.10/site-packages/ddtrace/vendor/wrapt/importer.py", line 177, in _exec_module
20
    notify_module_loaded(module)
19
  File "/usr/local/src/guidance_api/.venv/lib/python3.10/site-packages/ddtrace/vendor/wrapt/decorators.py", line 470, in _synchronized
18
    return wrapped(*args, **kwargs)
17
  File "/usr/local/src/guidance_api/.venv/lib/python3.10/site-packages/ddtrace/vendor/wrapt/importer.py", line 136, in notify_module_loaded
16
    hook(module)
15
  File "/usr/local/src/guidance_api/.venv/lib/python3.10/site-packages/ddtrace/_monkey.py", line 166, in on_import
14
    imported_module.patch()
13
  File "/usr/local/src/guidance_api/.venv/lib/python3.10/site-packages/ddtrace/contrib/langchain/patch.py", line 754, in patch
12
    wrap("langchain", "llms.base.BaseLLM.generate", traced_llm_generate(langchain))
11
  File "/usr/local/src/guidance_api/.venv/lib/python3.10/site-packages/ddtrace/vendor/wrapt/wrappers.py", line 882, in wrap_function_wrapper
10
    return wrap_object(module, name, FunctionWrapper, (wrapper,))
9
  File "/usr/local/src/guidance_api/.venv/lib/python3.10/site-packages/ddtrace/vendor/wrapt/wrappers.py", line 822, in wrap_object
8
    (parent, attribute, original) = resolve_path(module, name)
7
  File "/usr/local/src/guidance_api/.venv/lib/python3.10/site-packages/ddtrace/vendor/wrapt/wrappers.py", line 808, in resolve_path
6
    original = lookup_attribute(parent, attribute)
5
  File "/usr/local/src/guidance_api/.venv/lib/python3.10/site-packages/ddtrace/vendor/wrapt/wrappers.py", line 806, in lookup_attribute
4
    return getattr(parent, attribute)
3
  File "/usr/local/src/guidance_api/.venv/lib/python3.10/site-packages/langchain/__init__.py", line 328, in __getattr__
2
    raise AttributeError(f"Could not find: {name}")
1
AttributeError: Could not find: llms
```
