### ISSUE TITLE
@root_validator error

### ISSUE THREAD

**Issue by brainer3220** [langchain-ai/langchain#11749]
### System Info

```sh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/langchain/__init__.py", line 8, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "/usr/local/lib/python3.8/dist-packages/langchain/agents/__init__.py", line 2, in <module>
    from langchain.agents.agent import Agent
  File "/usr/local/lib/python3.8/dist-packages/langchain/agents/agent.py", line 10, in <module>
    from langchain.chains.base import Chain
  File "/usr/local/lib/python3.8/dist-packages/langchain/chains/__init__.py", line 2, in <module>
    from langchain.chains.conversation.base import ConversationChain
  File "/usr/local/lib/python3.8/dist-packages/langchain/chains/conversation/base.py", line 7, in <module>
    from langchain.chains.conversation.memory import ConversationBufferMemory
  File "/usr/local/lib/python3.8/dist-packages/langchain/chains/conversation/memory.py", line 7, in <module>
    from langchain.chains.conversation.prompt import SUMMARY_PROMPT
  File "/usr/local/lib/python3.8/dist-packages/langchain/chains/conversation/prompt.py", line 2, in <module>
    from langchain.prompts.prompt import PromptTemplate
  File "/usr/local/lib/python3.8/dist-packages/langchain/prompts/__init__.py", line 2, in <module>
    from langchain.prompts.base import BasePromptTemplate
  File "/usr/local/lib/python3.8/dist-packages/langchain/prompts/base.py", line 35, in <module>
    class BasePromptTemplate(BaseModel, ABC):
  File "/usr/local/lib/python3.8/dist-packages/langchain/prompts/base.py", line 41, in BasePromptTemplate
    @root_validator()
  File "/usr/local/lib/python3.8/dist-packages/pydantic/deprecated/class_validators.py", line 228, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.
```

### Who can help?

@agola11 

```python
import langchain
```

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Install langchain latest version on Linux
2. import langchain

### Expected behavior

Nothing.

**Comment by shimilgithub** [comment]
@dosu-bot is there any other solution for this issue instead of downgrading pydantic to v1?

**Comment by devstein** [comment]
@shimilgithub As of now Dosu only responds to the issue author.  Stay tuned for changes on this in the coming weeks. 

Let me know if you have any ideas/feedback on Dosu in the meantime!
