### ISSUE TITLE
DOC: <Please write a comprehensive title after the 'DOC: ' prefix>

### ISSUE THREAD

**Issue by herofolk** [langchain-ai/langchain#11898]
### Issue with current documentation:

I want to load doc type file use UnstructuredFileLoader, andI installed all require library, but I got this mistake:
Traceback (most recent call last):
  File "D:\soft\Anaconda3\lib\site-packages\unstructured\partition\doc.py", line 67, in partition_doc
    convert_office_doc(
  File "D:\soft\Anaconda3\lib\site-packages\unstructured\partition\common.py", line 294, in convert_office_doc
    logger.info(output.decode().strip())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 42: invalid continuation byte.
Then I see the code of function convert_office_doc that can not change encoding type, this mistake is 'utf-8' is not valid encoding type, so I changed this to 'gb2312', it worked.
So, whether a parameter should be added for the encoding type when reading the file?

### Idea or request for content:

So, whether a parameter should be added for the encoding type when reading the file?
For example, UnstructuredFileLoader(file_path, file_name, coding='utf-8').

**Comment by herofolk** [comment]
I solved the problem like this：
```python
import locale
output.decode(locale.getpreferredencoding(False)).strip()
```
Because encode type is unknow.
