### ISSUE TITLE
Issue:The completion operation does not work with the specified model for azure openai api

### ISSUE THREAD

**Issue by ImGoodBai** [langchain-ai/langchain#12019]
### Issue you'd like to raise.

```
import os
from langchain.llms import AzureOpenAI

os.environ["OPENAI_API_TYPE"] = "azure"
os.environ["OPENAI_API_VERSION"] = "2023-07-01-preview"
os.environ["OPENAI_API_BASE"] = "https://myurlid.openai.azure.com/"
os.environ["OPENAI_API_KEY"] = "my key"

llm = AzureOpenAI(
    deployment_name="gpt35",
    openai_api_version="2023-07-01-preview",
)

# Run the LLM
llm("Tell me a joke")
print(llm)
```

this is my demo code, try run it show error info:
```

$ /bin/python /home/good/langchain/cookbook/test/azure_hello.py
Traceback (most recent call last):
  File "/home/good/langchain/cookbook/test/azure_hello.py", line 22, in <module>
    llm("Tell me a joke")
  File "/home/good/.local/lib/python3.9/site-packages/langchain/llms/base.py", line 866, in __call__
    self.generate(
  File "/home/good/.local/lib/python3.9/site-packages/langchain/llms/base.py", line 646, in generate
    output = self._generate_helper(
  File "/home/good/.local/lib/python3.9/site-packages/langchain/llms/base.py", line 534, in _generate_helper
    raise e
  File "/home/good/.local/lib/python3.9/site-packages/langchain/llms/base.py", line 521, in _generate_helper
    self._generate(
  File "/home/good/.local/lib/python3.9/site-packages/langchain/llms/openai.py", line 401, in _generate
    response = completion_with_retry(
  File "/home/good/.local/lib/python3.9/site-packages/langchain/llms/openai.py", line 115, in completion_with_retry
    return _completion_with_retry(**kwargs)
  File "/home/good/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/home/good/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/good/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/good/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/home/good/.local/lib/python3.9/site-packages/langchain/llms/openai.py", line 113, in _completion_with_retry
    return llm.client.create(**kwargs)
  File "/home/good/.local/lib/python3.9/site-packages/openai/api_resources/completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/good/.local/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
  File "/home/good/.local/lib/python3.9/site-packages/openai/api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/good/.local/lib/python3.9/site-packages/openai/api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "/home/good/.local/lib/python3.9/site-packages/openai/api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The completion operation does not work with the specified model, gpt-35-turbo. Please choose different model and try again. You can learn more about which models can be used with each operation here: https://go.microsoft.com/fwlink/?linkid=2197993.
```
$ python -V
Python 3.9.9

I'm sure my Azure key and other information are correct, because they work normally elsewhere.

**Comment by ImGoodBai** [comment]
How should I modify my code? The name 'gpt-35-turbo' does not appear in my code, and I don't know how it was generated. My model deployment name is 'gtp35'

**Comment by ImGoodBai** [comment]
When I added a parameter to specify the model name while initializing llm, the following error occurred during execution:

code：
```
llm = AzureOpenAI(
    deployment_name="gpt35",
+  engine="gpt-3.5-turbo",
)
```

error：
`openai.error.InvalidRequestError: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.`

**Comment by ImGoodBai** [comment]
When I modified model name to “gpt4", terminal show error info:

`openai.error.InvalidRequestError: The completion operation does not work with the specified model, gpt-4. Please choose different model and try again. You can learn more about which models can be used with each operation here: https://go.microsoft.com/fwlink/?linkid=2197993.` 

code:
`llm = AzureOpenAI(
    deployment_name="gpt4",
    engine="gpt-4",
)`

why ，   "gpt-4" in its mapping!

**Comment by ltanme** [comment]
Me too, I encountered this kind of error.

[https://learn.microsoft.com/en-us/answers/questions/1402872/how-to-fix-openai-error-invalidrequesterror-the-co?orderby=helpful#answers
](url)

my code is as follows

`from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.vectorstores import Chroma
from langchain.text_splitter import CharacterTextSplitter
from langchain import OpenAI
from langchain.document_loaders import DirectoryLoader
from langchain.chains import RetrievalQA

import os

os.environ["OPENAI_API_TYPE"] = "azure"
os.environ["OPENAI_API_BASE"] = "https://myname.openai.azure.com/"
os.environ["OPENAI_API_KEY"] = "234230349502348590238423"
os.environ["OPENAI_API_VERSION"] = "2023-03-15-preview" 

 
loader = DirectoryLoader('/data/', glob='**/*.txt') 
documents = loader.load()

 
text_splitter = CharacterTextSplitter(chunk_size=100, chunk_overlap=0)
 
split_docs = text_splitter.split_documents(documents)

 
embeddings = OpenAIEmbeddings(
    deployment="t-ada",
    openai_api_base="https://myname.openai.azure.com/",
    openai_api_type="azure",
    openai_api_key="234230349502348590238423",
    openai_api_version="2023-03-15-preview",
)

docsearch = Chroma.from_documents(split_docs, embeddings)


qa = RetrievalQA.from_chain_type(llm=OpenAI(engine="t-ada"), chain_type="stuff", retriever=docsearch.as_retriever(),
                                 return_source_documents=True)
 
result = qa({"query": "What is this article mainly about?"})
print(result)` 


my error is as follows:

`    raise self.handle_error_response(
openai.error.InvalidRequestError: The embeddings operation does not work with the specified model, gpt-35-turbo-instruct. Please choose different model and try again. You can learn more about which models can be used with each operation here:`

my python env is as follows
python3.10.6
pip install openai==0.27.8
pip install langchain==0.27.8
