### ISSUE TITLE
SQLDatabaseChain Error

### ISSUE THREAD

**Issue by awsgirib** [langchain-ai/langchain#12295]
### System Info

Langchain version == 0.0.323
python == 3.10

```
I have a simple code to query a postgres DB:

from langchain.llms import Bedrock
from langchain_experimental.sql import SQLDatabaseChain

db = SQLDatabase.from_uri(database_uri="postgresql://xxx:yyy:zzzzz")

llm = Bedrock(
    credentials_profile_name="langchain",
    model_id="anthropic.claude-v2"
)
db_chain = SQLDatabaseChain.from_llm(llm, db, verbose=True)
db_chain.run("how many lab reports are there?")
```

Get the following error:
```

 Entering new SQLDatabaseChain chain...
how many lab reports are there?
SQLQuery:Here is the query and response for your question:

Question: how many lab reports are there?
SQLQuery: SELECT COUNT(*) FROM lab_reportsTraceback (most recent call last):
  File "/home/ec2-user/miniconda3/envs/langchain3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/home/ec2-user/miniconda3/envs/langchain3.10/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.SyntaxError: syntax error at or near "Here"
LINE 1: Here is the query and response for your question:
        ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ec2-user/environment/Langchain/langchain-sql.py", line 12, in <module>
    db_chain.run("how many lab reports are there?")
  File "/home/ec2-user/miniconda3/envs/langchain3.10/lib/python3.10/site-packages/langchain/chains/base.py", line 505, in run
    return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[
  File "/home/ec2-user/miniconda3/envs/langchain3.10/lib/python3.10/site-packages/langchain/chains/base.py", line 310, in __call__
    raise e
  File "/home/ec2-user/miniconda3/envs/langchain3.10/lib/python3.10/site-packages/langchain/chains/base.py", line 304, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/home/ec2-user/miniconda3/envs/langchain3.10/lib/python3.10/site-packages/langchain_experimental/sql/base.py", line 198, in _call
    raise exc
  File "/home/ec2-user/miniconda3/envs/langchain3.10/lib/python3.10/site-packages/langchain_experimental/sql/base.py", line 143, in _call
    result = self.database.run(sql_cmd)
  File "/home/ec2-user/miniconda3/envs/langchain3.10/lib/python3.10/site-packages/langchain/utilities/sql_database.py", line 429, in run
    result = self._execute(command, fetch)
  File "/home/ec2-user/miniconda3/envs/langchain3.10/lib/python3.10/site-packages/langchain/utilities/sql_database.py", line 407, in _execute
    cursor = connection.execute(text(command))
  File "/home/ec2-user/miniconda3/envs/langchain3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
  File "/home/ec2-user/miniconda3/envs/langchain3.10/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/ec2-user/miniconda3/envs/langchain3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1639, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/ec2-user/miniconda3/envs/langchain3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1848, in _execute_context
    return self._exec_single_context(
  File "/home/ec2-user/miniconda3/envs/langchain3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1988, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/ec2-user/miniconda3/envs/langchain3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2343, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/ec2-user/miniconda3/envs/langchain3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/home/ec2-user/miniconda3/envs/langchain3.10/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "Here"
LINE 1: Here is the query and response for your question:
        ^

[SQL: Here is the query and response for your question:

Question: how many lab reports are there?
SQLQuery: SELECT COUNT(*) FROM lab_reports]
(Background on this error at: https://sqlalche.me/e/20/f405)
```

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Execute the code with a postgres DB

### Expected behavior

Expect the query to execute and get results.

**Comment by Falydoor** [comment]
I'm also getting the same error with `anthropic.claude-v2`.

It looks like the answer from Claude needs to be parsed because it includes more data than just the SQL query:

```json
{
    "completion": " Here is the solution:\n\nQuestion: EDITED_QUESTION\n\nSQLQuery:\nEDITED_QUERY \n\nSQLResult:\nEDITED_RESULT\n\nAnswer: EDITED_ANSWER",
    "stop_reason": "stop_sequence",
    "stop": "\n\nHuman:"
}
```

I believe this part of the code will have to parse the answer: https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/llms/bedrock.py#L104.

Is there already a class that is capable of extracting a SQL query from a block of text?
