### ISSUE TITLE
`Docx2txtLoader` isn't loading docx files properly

### ISSUE THREAD

**Issue by sidmohanty11** [langchain-ai/langchain#12399]
### System Info

Langchain version: 0.0.323
Platform: MacOS Sonoma
Python version: 3.11

### Who can help?

@eyurtsev

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

`Docx2txtLoader` isn't handling improperly encoded docx files and is throwing errors.

Code:
```python
from langchain.document_loaders import Docx2txtLoader

def main():
    file = 'elon_doc.docx'
    loader = Docx2txtLoader(file)
    text = loader.load()
    print(text)


if __name__ == '__main__':
    main()
```

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/sidharthmohanty/Desktop/oss/test-docs/docx.py", line 11, in <module>
    main()
  File "/Users/sidharthmohanty/Desktop/oss/test-docs/docx.py", line 6, in main
    text = loader.load()
           ^^^^^^^^^^^^^
  File "/Users/sidharthmohanty/Desktop/oss/test-docs/dev_env/lib/python3.11/site-packages/langchain/document_loaders/word_document.py", line 55, in load
    page_content=docx2txt.process(self.file_path),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sidharthmohanty/Desktop/oss/test-docs/dev_env/lib/python3.11/site-packages/docx2txt/docx2txt.py", line 76, in process
    zipf = zipfile.ZipFile(docx)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/zipfile.py", line 1302, in __init__
    self._RealGetContents()
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/zipfile.py", line 1369, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

To reproduce the issue please use this file: https://uploadnow.io/f/Mr0tybt.

### Expected behavior

It should handle it gracefully and extract text if possible. If the file is completely corrupted, it should show an error for a corrupted file.

**Comment by codebynikhil** [comment]
I used in one of my code worked fine for me 
import os
from docx import Document as DocxDocument
from langchain_community.document_loaders import Docx2txtLoader

print("Using Doc2txtloader")

try:
    docx_loader = Docx2txtLoader('data/word_files/Nikhil_Chauhan_resume_2026.docx')
    docs=docx_loader.load()
    print(f"Loaded {len(docs)} documents from word_docs folder")
    print(f"First document content: {docs[0].page_content[:500]}")  # Print first 500 characters of the first document
except Exception as e:
    print(f"Error loading documents: {e}")
