### ISSUE TITLE
Importing openai causes openai.error.InvalidRequestError: Resource not found

### ISSUE THREAD

**Issue by ksaurabh21** [langchain-ai/langchain#12430]
### System Info

langchain==0.0.324
openai==0.28.1
Python 3.9.16
Using gpt-35-turbo-16k model from azure

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Save this code in a .py file and run it to see the error:
```
import os
from dotenv import load_dotenv, find_dotenv
from langchain.chat_models import ChatOpenAI
from langchain.prompts import ChatPromptTemplate
import openai

_ = load_dotenv(find_dotenv())
llm_model_name = os.environ.get('CHAT_MODEL_DEPLOYMENT_NAME')
llm = ChatOpenAI(temperature=0.0, model_kwargs={"engine": llm_model_name})
prompt = ChatPromptTemplate.from_template(
    """tell me a joke about {topic}"""
)
response = llm(prompt.format_messages(topic = "bear"))
print(response.content)
```
Then comment the `import openai` line and run again to get rid of errors.

### Expected behavior

The given code generates expected response from the llm after commenting the `import openai` line:
```
Why don't bears wear shoes?

Because they have bear feet!
```

**Comment by arunsathiya** [comment]
I ran the code on a Jupyter notebook but I cannot reproduce the issue. The imported `openai` package is simply unused.

Not sure what might be causing the behavior at your end, but I am following this issue to learn.

**Comment by ksaurabh21** [comment]
This is what I am getting:
```
Traceback (most recent call last):
  File "C:\workspace\generative_ai\MS-Conversational-AI\notebooks\bug.py", line 13, in <module>
    response = llm(prompt.format_messages(topic = "bear"))
  File "C:\workspace\generative_ai\MS-Conversational-AI\venv\lib\site-packages\langchain\chat_models\base.py", line 600, in __call__
    generation = self.generate(
  File "C:\workspace\generative_ai\MS-Conversational-AI\venv\lib\site-packages\langchain\chat_models\base.py", line 349, in generate
    raise e
  File "C:\workspace\generative_ai\MS-Conversational-AI\venv\lib\site-packages\langchain\chat_models\base.py", line 339, in generate
    self._generate_with_cache(
  File "C:\workspace\generative_ai\MS-Conversational-AI\venv\lib\site-packages\langchain\chat_models\base.py", line 492, in _generate_with_cache
    return self._generate(
  File "C:\workspace\generative_ai\MS-Conversational-AI\venv\lib\site-packages\langchain\chat_models\openai.py", line 360, in _generate
    response = self.completion_with_retry(
  File "C:\workspace\generative_ai\MS-Conversational-AI\venv\lib\site-packages\langchain\chat_models\openai.py", line 299, in completion_with_retry
    return _completion_with_retry(**kwargs)
  File "C:\workspace\generative_ai\MS-Conversational-AI\venv\lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "C:\workspace\generative_ai\MS-Conversational-AI\venv\lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\workspace\generative_ai\MS-Conversational-AI\venv\lib\site-packages\tenacity\__init__.py", line 314, in iter
    return fut.result()
  File "C:\Users\KumarSaurabh\miniconda3\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\KumarSaurabh\miniconda3\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\workspace\generative_ai\MS-Conversational-AI\venv\lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "C:\workspace\generative_ai\MS-Conversational-AI\venv\lib\site-packages\langchain\chat_models\openai.py", line 297, in _completion_with_retry
    return self.client.create(**kwargs)
  File "C:\workspace\generative_ai\MS-Conversational-AI\venv\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\workspace\generative_ai\MS-Conversational-AI\venv\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
  File "C:\workspace\generative_ai\MS-Conversational-AI\venv\lib\site-packages\openai\api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\workspace\generative_ai\MS-Conversational-AI\venv\lib\site-packages\openai\api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "C:\workspace\generative_ai\MS-Conversational-AI\venv\lib\site-packages\openai\api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Resource not found

```

**Comment by ksaurabh21** [comment]
And the package versions that I have:
```
aiohttp==3.8.6
aiosignal==1.3.1
altair==5.1.2
anyio==3.7.1
asttokens==2.4.1
async-timeout==4.0.3
attrs==23.1.0
backcall==0.2.0
bcrypt==4.0.1
blinker==1.6.3
cachetools==5.3.2
certifi==2023.7.22
charset-normalizer==3.3.1
click==8.1.7
colorama==0.4.6
comm==0.1.4
dataclasses-json==0.6.1
debugpy==1.8.0
decorator==5.1.1
docarray==0.39.1
exceptiongroup==1.1.3
executing==2.0.0
extra-streamlit-components==0.1.60
frozenlist==1.4.0
gitdb==4.0.11
GitPython==3.1.40
greenlet==3.0.1
idna==3.4
importlib-metadata==6.8.0
ipykernel==6.26.0
ipython==8.16.1
jedi==0.19.1
Jinja2==3.1.2
jsonpatch==1.33
jsonpointer==2.4
jsonschema==4.19.1
jsonschema-specifications==2023.7.1
jupyter_client==8.5.0
jupyter_core==5.4.0
langchain==0.0.324
langsmith==0.0.52
markdown-it-py==3.0.0
MarkupSafe==2.1.3
marshmallow==3.20.1
matplotlib-inline==0.1.6
mdurl==0.1.2
multidict==6.0.4
mypy-extensions==1.0.0
nest-asyncio==1.5.8
numpy==1.26.1
openai==0.28.1
orjson==3.9.10
packaging==23.2
pandas==2.1.2
parso==0.8.3
pickleshare==0.7.5
Pillow==10.1.0
platformdirs==3.11.0
prompt-toolkit==3.0.39
protobuf==4.24.4
psutil==5.9.6
pure-eval==0.2.2
pyarrow==13.0.0
pydantic==1.10.9
pydeck==0.8.1b0
Pygments==2.16.1
PyJWT==2.8.0
python-dateutil==2.8.2
python-dotenv==1.0.0
pytz==2023.3.post1
pywin32==306
PyYAML==6.0.1
pyzmq==25.1.1
referencing==0.30.2
regex==2023.10.3
requests==2.31.0
rich==13.6.0
rpds-py==0.10.6
six==1.16.0
smmap==5.0.1
sniffio==1.3.0
SQLAlchemy==2.0.22
stack-data==0.6.3
streamlit==1.28.0
streamlit-authenticator==0.2.3
tenacity==8.2.3
tiktoken==0.5.1
toml==0.10.2
toolz==0.12.0
tornado==6.3.3
tqdm==4.66.1
traitlets==5.12.0
types-requests==2.31.0.10
typing-inspect==0.9.0
typing_extensions==4.8.0
tzdata==2023.3
tzlocal==5.2
urllib3==2.0.7
uuid==1.30
validators==0.22.0
watchdog==3.0.0
wcwidth==0.2.8
websockets==12.0
yarl==1.9.2
zipp==3.17.0

```

**Comment by samadkoita** [comment]
@ksaurabh21 The reason for this is that you are using an invalid model_name (gpt-35-turbo-16k). The openai API does not support Azure model names. Please refer to AzureChatOpenAI in azure_openai.py instead
