### ISSUE TITLE
VertexAIEmbeddings is raising timout exception

### ISSUE THREAD

**Issue by tripathyas** [langchain-ai/langchain#12662]
### System Info

`[tool.poetry.dependencies]
python = "=3.8.16"
langchain = "^0.0.327"
google-cloud-aiplatform = "^1.35.0"
`

code:
`embedding = VertexAIEmbeddings()`

error:
`Traceback (most recent call last):                                                                                                                                           File "/Users/astripathy/Library/Caches/pypoetry/virtualenvs/nssauto-test-2ktKcOZb-py3.8/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 75, in error_r
emapped_callable
    return callable_(*args, **kwargs)                                                                                                                                        File "/Users/astripathy/Library/Caches/pypoetry/virtualenvs/nssauto-test-2ktKcOZb-py3.8/lib/python3.8/site-packages/grpc/_channel.py", line 1161, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/astripathy/Library/Caches/pypoetry/virtualenvs/nssauto-test-2ktKcOZb-py3.8/lib/python3.8/site-packages/grpc/_channel.py", line 1004, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:                                                                                                   status = StatusCode.UNAVAILABLE
        details = "DNS resolution failed for us-central1-aiplatform.googleapis.com:443: C-ares status is not ARES_SUCCESS qtype=A name=us-central1-aiplatform.googleapis.co
m is_balancer=0: DNS query cancelled"                                                                                                                                              debug_error_string = "UNKNOWN:DNS resolution failed for us-central1-aiplatform.googleapis.com:443: C-ares status is not ARES_SUCCESS qtype=A name=us-central1-aipla
tform.googleapis.com is_balancer=0: DNS query cancelled {grpc_status:14, created_time:"2023-10-31T22:38:41.657524+05:30"}"`

I don't think there is any connectivity issue as I am able to successfully run below query from the same machine:

`MODEL_ID="textembedding-gecko"
PROJECT_ID=XXXX-XXXX

curl \
-X POST \
-H "Authorization: Bearer $(gcloud auth print-access-token)" \
-H "Content-Type: application/json" \
https://us-central1-aiplatform.googleapis.com/v1/projects/${PROJECT_ID}/locations/us-central1/publishers/google/models/${MODEL_ID}:predict -d \
$'{
  "instances": [
    { "content": "What is life?"}
  ],
}'
{
  "predictions": [
    {
      "embeddings": {
        "values": [
          0.010562753304839134,
          0.049150310456752777,`

### Who can help?

@hwchase17 @agola11 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

`!pip install langchain
!pip install google-cloud-aiplatform
import langchain
from langchain.embeddings import VertexAIEmbeddings
from google.cloud import aiplatform

embedding = VertexAIEmbeddings()`

### Expected behavior

Below code should not throw any exception:
` embedding = VertexAIEmbeddings()`

**Comment by tripathyas** [comment]
It looks like the error is coming because of the antivirus on my laptop. I tried same code with same configuration on cloud VM and it worked.
