### ISSUE TITLE
Missing 'Action:' after 'Thought:

### ISSUE THREAD

**Issue by WalnutStudios** [langchain-ai/langchain#12689]
### System Info

langchain==0.0.326
Python 3.10.8

llm = Bedrock

Note: I tested this with the Bedrock LLM and these 3 models:
anthropic.claude-instant-v1
anthropic.claude-v2
ai21.j2-ultra-v1

The error does NOT occur when using llm=OpenAI

Stack Trace:
```
Thought:Traceback (most recent call last):
  File "...venv\lib\site-packages\langchain\agents\agent.py", line 933, in _take_next_step
    output = self.agent.plan(
  File "...venv\lib\site-packages\langchain\agents\agent.py", line 547, in plan
    return self.output_parser.parse(full_output)
  File "...venv\lib\site-packages\langchain\agents\mrkl\output_parser.py", line 61, in parse
    raise OutputParserException(
langchain.schema.output_parser.OutputParserException: Could not parse LLM output: ` Fumio Kishida is 65 years old. The largest prime number smaller than 65 is 61.`

During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "...langchain\l101.py", line 32, in <module>
    agent.run("Who is the current leader of Japan and how old are they? What is the largest prime number that is smaller than the leader's age?")
  File "...venv\lib\site-packages\langchain\chains\base.py", line 505, in run
    return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[
  File "...venv\lib\site-packages\langchain\chains\base.py", line 310, in __call__
    raise e
  File "...venv\lib\site-packages\langchain\chains\base.py", line 304, in __call__
    self._call(inputs, run_manager=run_manager)
  File "...venv\lib\site-packages\langchain\agents\agent.py", line 1146, in _call
    next_step_output = self._take_next_step(
  File "...venv\lib\site-packages\langchain\agents\agent.py", line 944, in _take_next_step
    raise ValueError(
ValueError: An output parsing error occurred. In order to pass this error back to the agent and have it try again, pass `handle_parsing_errors=True` to the AgentExecutor. This is the error: Could not parse LLM output: ` Fumio Kishida is 65 years old. The largest prime number smaller than 65 is 61.`
```

### Who can help?

@sbusso 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [X] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
llm = Bedrock(
    credentials_profile_name="default",
    model_id="ai21.j2-ultra-v1",
    # streaming=True,
    model_kwargs={"temperature": 0.0}
)

# llm = OpenAI(temperature=0)

tools = load_tools(["serpapi"],llm=llm)
# agent = initialize_agent(tools=tools,llm=llm,agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION,handle_parsing_errors=True,verbose=True)
agent = initialize_agent(tools=tools,llm=llm,agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION,verbose=True)

agent.run("Who is the current leader of Japan and how old are they? What is the largest prime number that is smaller than the leader's age?")

```

### Expected behavior

The text should have been parsed. Based on the stack trace:
Could not parse LLM output: ` Fumio Kishida is 65 years old. The largest prime number smaller than 65 is 61.`

I'm thinking this is probably derived from the boto3 API response, because it works fine with OpenAI.

**Comment by austinmw** [comment]
Custom parsing helps, however I think the ReAct prompt should ideally be tailored and improved for the Claude or Jurassic models. Does anyone have a good working ReAct prompt for these models to share?
