### ISSUE TITLE
Updated to latest langchain version but still getting OpenAI embeddings error

### ISSUE THREAD

**Issue by pelguetat** [langchain-ai/langchain#13056]
### System Info

LangChain version = 0.0.331
Openai version = 1.1.1

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```Error creating LLM: module 'openai' has no attribute 'Embedding'
aai_app            | Error creating LLM: module 'openai' has no attribute 'Embedding'
aai_app            | Traceback (most recent call last):
aai_app            |   File "/code/aai/apps/slack_bot/views.py", line 160, in call_open_ai
aai_app            |     reply = open_ai.execute_query(question)
aai_app            |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aai_app            |   File "/code/aai/apps/affiliateai/services/open_ai/open_ai.py", line 130, in execute_query
aai_app            |     named_entity_recognition = NamedEntityRecognition(
aai_app            |                                ^^^^^^^^^^^^^^^^^^^^^^^
aai_app            |   File "/code/aai/apps/affiliateai/services/open_ai/named_entity_recognition.py", line 41, in __init__
aai_app            |     self.llm_embeddings = self.llm.create_llm(
aai_app            |                           ^^^^^^^^^^^^^^^^^^^^
aai_app            |   File "/code/aai/apps/affiliateai/services/open_ai/llm_manager.py", line 63, in create_llm
aai_app            |     return OpenAIEmbeddings(
aai_app            |            ^^^^^^^^^^^^^^^^^
aai_app            |   File "/usr/local/lib/python3.11/site-packages/pydantic/v1/main.py", line 339, in __init__
aai_app            |     values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
aai_app            |                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aai_app            |   File "/usr/local/lib/python3.11/site-packages/pydantic/v1/main.py", line 1050, in validate_model
aai_app            |     input_data = validator(cls_, input_data)
aai_app            |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
aai_app            |   File "/usr/local/lib/python3.11/site-packages/langchain/embeddings/openai.py", line 284, in validate_environment
aai_app            |     values["client"] = openai.Embedding
aai_app            |                        ^^^^^^^^^^^^^^^^
aai_app            | AttributeError: module 'openai' has no attribute 'Embedding'
aai_app            | 
aai_app            | module 'openai' has no attribute 'Embedding'
aai_app            | Traceback (most recent call last):
aai_app            |   File "/code/aai/apps/slack_bot/views.py", line 160, in call_open_ai
aai_app            |     reply = open_ai.execute_query(question)
aai_app            |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aai_app            |   File "/code/aai/apps/affiliateai/services/open_ai/open_ai.py", line 130, in execute_query
aai_app            |     named_entity_recognition = NamedEntityRecognition(
aai_app            |                                ^^^^^^^^^^^^^^^^^^^^^^^
aai_app            |   File "/code/aai/apps/affiliateai/services/open_ai/named_entity_recognition.py", line 41, in __init__
aai_app            |     self.llm_embeddings = self.llm.create_llm(
aai_app            |                           ^^^^^^^^^^^^^^^^^^^^
aai_app            |   File "/code/aai/apps/affiliateai/services/open_ai/llm_manager.py", line 63, in create_llm
aai_app            |     return OpenAIEmbeddings(
aai_app            |            ^^^^^^^^^^^^^^^^^
aai_app            |   File "/usr/local/lib/python3.11/site-packages/pydantic/v1/main.py", line 339, in __init__
aai_app            |     values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
aai_app            |                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aai_app            |   File "/usr/local/lib/python3.11/site-packages/pydantic/v1/main.py", line 1050, in validate_model
aai_app            |     input_data = validator(cls_, input_data)
aai_app            |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
aai_app            |   File "/usr/local/lib/python3.11/site-packages/langchain/embeddings/openai.py", line 284, in validate_environment
aai_app            |     values["client"] = openai.Embedding
aai_app            |                        ^^^^^^^^^^^^^^^^
aai_app            | AttributeError: module 'openai' has no attribute 'Embedding'```

### Expected behavior

Not to see this error.

**Comment by baskaryan** [comment]
support is still in preview, `langchain>=0.0.331rc2`. Will have a proper release out soon

**Comment by umair313** [comment]
> support is still in preview, `langchain>=0.0.331rc2`. Will have a proper release out soon

can I contribute in that?
