### ISSUE TITLE
NameError: name '_httpx_client' is not defined

### ISSUE THREAD

**Issue by gregbird101** [langchain-ai/langchain#13204]
### System Info

Hello All,

I have just installed the helm chart with some small additions to the basic values.yaml and the "langchain-langsmith-backend" contain keeps breaking with the following error, Has anyone had this before?
INFO: Started server process [1]
--
Fri, Nov 10 2023 2:41:24 pm | INFO: Waiting for application startup.
Fri, Nov 10 2023 2:41:24 pm | INFO: Application startup complete.
Fri, Nov 10 2023 2:41:24 pm | INFO: Uvicorn running on http://0.0.0.0:1984 (Press CTRL+C to quit)
Fri, Nov 10 2023 2:42:18 pm | INFO: Shutting down
Fri, Nov 10 2023 2:42:18 pm | INFO: Waiting for application shutdown.
Fri, Nov 10 2023 2:42:19 pm | ERROR:root:Error closing httpx client for clickhouse name '_httpx_client' is not defined
Fri, Nov 10 2023 2:42:19 pm | Traceback (most recent call last):
Fri, Nov 10 2023 2:42:19 pm | File "/code/smith-backend/app/main.py", line 140, in shutdown_event
Fri, Nov 10 2023 2:42:19 pm | File "/code/lc_database/lc_database/clickhouse.py", line 36, in close_clickhouse_client
Fri, Nov 10 2023 2:42:19 pm | await _httpx_client.aclose()
Fri, Nov 10 2023 2:42:19 pm | ^^^^^^^^^^^^^
Fri, Nov 10 2023 2:42:19 pm | NameError: name '_httpx_client' is not defined
Fri, Nov 10 2023 2:42:19 pm | INFO: Application shutdown complete.
Fri, Nov 10 2023 2:42:19 pm | INFO: Finished server process [1]

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

helm repo add langchain https://langchain-ai.github.io/helm/
helm install langchain/langsmith . --values values.yaml --namespace it-dev-langchain

Running this on an on prem Rancher cluster.

### Expected behavior

The contain runs normally.

**Comment by gregbird101** [comment]
1. helm list - langsmith-0.1.3 0.1.0
NAME            NAMESPACE               REVISION        UPDATED                                 STATUS          CHART           APP VERSION
langchain       it-dev-langchain        1               2023-11-10 14:42:59.4745717 +0000 UTC   deployed        langsmith-0.1.3 0.1.0
2. lines changed in value
`ingress:
  hostname: "langchain-langsmith-frontend.domain.com"
config:
  langsmithLicenseKey: "langsmith_partner_2023"`
3.
