### ISSUE TITLE
Issue: When using Qianfan chat model and enabling streaming, get ValueError

### ISSUE THREAD

**Issue by TheJerryChang** [langchain-ai/langchain#13546]
### Issue you'd like to raise.

Here is my code:

"""For basic init and call"""
import os
import qianfan
from langchain.chat_models import QianfanChatEndpoint
from langchain.chat_models.base import HumanMessage
os.environ["QIANFAN_AK"] = "myak"
os.environ["QIANFAN_SK"] = "mysk"

chat = QianfanChatEndpoint(
    streaming=True,
)
res = chat.stream([HumanMessage(content="给我一篇100字的睡前故事")], streaming=True)
for r in res:
    print("chat resp:", r)

And after it prints two sentences, returns an error. The full error message is:
Traceback (most recent call last):
  File "d:\work\qianfan_test.py", line 13, in <module>
    for r in res:
  File "C:\Users\a1383\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\langchain\chat_models\base.py", line 220, in stream
    raise e
  File "C:\Users\a1383\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\langchain\chat_models\base.py", line 216, in stream
    generation += chunk
  File "C:\Users\a1383\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\langchain\schema\output.py", line 94, in __add__
    message=self.message + other.message,
  File "C:\Users\a1383\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\langchain\schema\messages.py", line 225, in __add__
    additional_kwargs=self._merge_kwargs_dict(
  File "C:\Users\a1383\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\langchain\schema\messages.py", line 138, in _merge_kwargs_dict
    raise ValueError(
ValueError: Additional kwargs key created already exists in this message.

I am only following the official langchain documentation:https://python.langchain.com/docs/integrations/chat/baidu_qianfan_endpoint 
And it is not working. What have I done wrong?

**Comment by danielhjz** [comment]
Hi @TheJerryChang , thanks for report. This issue will be fixed in the incoming future. An #13800 draft has been created.

**Comment by TheJerryChang** [comment]
> Hi @TheJerryChang , thanks for report. This issue will be fixed in the incoming future. An #13800 draft has been created.

Great! Thanks!
