### ISSUE TITLE
Issue: Filling `ConversationSummaryMemory` with existing conversation from an SQLite database 

### ISSUE THREAD

**Issue by Issaminu** [langchain-ai/langchain#13599]
### Issue you'd like to raise.

I'd like to make `ConversationSummaryMemory` is filled with the previous questions and answers for a specific conversation from an SQLite database so I can have my agent already aware of previous conversation with the user.

Here's my current code:
```py
import os
import sys
from langchain.chains import ConversationalRetrievalChain
from langchain.chat_models import ChatOpenAI
from langchain.embeddings import OpenAIEmbeddings
from langchain.indexes import VectorstoreIndexCreator
from langchain.indexes.vectorstore import VectorStoreIndexWrapper
from langchain.vectorstores.chroma import Chroma
from langchain.memory import ConversationSummaryMemory
from langchain.tools import Tool
from langchain.agents.types import AgentType
from langchain.agents import initialize_agent
from dotenv import load_dotenv

load_dotenv()
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

query = " ".join(sys.argv[1:]) if len(sys.argv) > 1 else None

retriever = # retriever stuff here for the `local-docs` tool

llm = ChatOpenAI(temperature=0.7, model="gpt-3.5-turbo-1106")

memory = ConversationSummaryMemory(
    llm=llm,
    memory_key="chat_history",
    return_messages=True,
)


chain = ConversationalRetrievalChain.from_llm(
    llm=llm,
    memory=memory,
    chain_type="stuff",
    retriever=index.vectorstore.as_retriever(search_kwargs={"k": 4}),
    get_chat_history=lambda h: h,
    verbose=False,
)

system_message = (
    "Be helpful to your users".
)
tools = [
    Tool(
        name="local-docs",
        func=chain,
        description="Useful when you need to answer docs-related questions",
    )
]


def ask(input: str) -> str:
    result = ""
    try:
        result = executor({"input": input})
    except Exception as e:
        response = str(e)
        if response.startswith("Could not parse LLM output: `"):
            response = response.removeprefix(
                "Could not parse LLM output: `"
            ).removesuffix("`")
            return response
        else:
            raise Exception(str(e))
    return result


chat_history = []
executor = initialize_agent(
    agent=AgentType.CHAT_CONVERSATIONAL_REACT_DESCRIPTION,
    tools=tools,
    llm=llm,
    memory=memory,
    agent_kwargs={"system_message": system_message},
    verbose=True,
    max_execution_time=30,
    max_iterations=6,
    handle_parsing_errors=True,
    early_stopping_method="generate",
    stop=["\nObservation:"],
)

result = ask(query)
print(result["output"])
```

**Comment by Issaminu** [comment]
@dosu-bot Thanks but `BaseChatMessageHistory` is an abstract class, so we can't use it.
I'm not sure but maybe `SQLChatMessageHistory` would help?

**Comment by Issaminu** [comment]
@dosu-bot I actually used `ConversationSummaryMemory().from_messages()` instead of the `conversation_memory.add_message(message)` you suggested since `ConversationSummaryMemory().add_message()` doesn't exist.

Right now, I'm facing an issue with `SQLChatMessageHistory`, when I do this `messages = chat_history.messages` it throws this error:
```
Traceback (most recent call last):
  File "query.py", line 61, in <module>
    messages = chat_history.messages
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/issam/.local/lib/python3.11/site-packages/langchain/memory/chat_message_histories/sql.py", line 122, in messages
    messages.append(self.converter.from_sql_model(record))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/issam/.local/lib/python3.11/site-packages/langchain/memory/chat_message_histories/sql.py", line 71, in from_sql_model
    return messages_from_dict([json.loads(sql_message.message)])[0]
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Issaminu** [comment]
@dosu-bot Unfortunately it didn't work. I'd like to fetch the records manually.

Suppose I have an list of tuples with (type,message) in each item of the list, how can I turn this list into something usable in `ConversationSummaryMemory`?

**Comment by Issaminu** [comment]
@dosu-bot you didn't show where to use `memory_dict`.

**Comment by Issaminu** [comment]
@dosu-bot sorry but you're tripping a bit. We're creating a list of message objects, then we're turning them into a dictionary, then we're turning them back into a list of message objects?

Also your snippets are using abstract classes like `BaseMessage` and `BaseChatMessageHistory`, please don't use them in your code.

**Comment by Issaminu** [comment]
@dosu-bot I think I got it mostly working now, but it still errors with this:

```
ValueError: A single string input was passed in, but this chain expects multiple inputs ({'question', 'chat_history'}). When a chain expects multiple inputs, please call it by passing in a dictionary, eg `chain({'foo': 1, 'bar': 2})`
```

Here's the full code:

```python
import os
import sys
from langchain.chains import ConversationalRetrievalChain
from langchain.chat_models import ChatOpenAI
from langchain.document_loaders import DirectoryLoader, TextLoader
from langchain.embeddings import OpenAIEmbeddings
from langchain.indexes import VectorstoreIndexCreator
from langchain.indexes.vectorstore import VectorStoreIndexWrapper
from langchain.vectorstores.chroma import Chroma
from langchain.memory.chat_message_histories import SQLChatMessageHistory
from langchain.memory import ConversationBufferMemory, ConversationSummaryMemory
from langchain.chains.conversational_retrieval.prompts import CONDENSE_QUESTION_PROMPT
from langchain.schema import HumanMessage, AIMessage, SystemMessage
from langchain.chains import StuffDocumentsChain, LLMChain, ConversationalRetrievalChain
from langchain.prompts import PromptTemplate
from langchain.tools import Tool
from langchain.agents.types import AgentType
from langchain.agents import initialize_agent
from langchain.chains.question_answering import load_qa_chain
import sqlite3
from dotenv import load_dotenv


load_dotenv()
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
PERSIST = True
query = " ".join(sys.argv[1:]) if len(sys.argv) > 1 else None
if PERSIST and os.path.exists("persist"):
    vectorstore = Chroma(
        persist_directory="persist", embedding_function=OpenAIEmbeddings()
    )
    index = VectorStoreIndexWrapper(vectorstore=vectorstore)
else:
    loader = DirectoryLoader("text/www.enset-media.ac.ma")
    if PERSIST:
        index = VectorstoreIndexCreator(
            vectorstore_kwargs={"persist_directory": "persist"}
        ).from_loaders([loader])
    else:
        index = VectorstoreIndexCreator().from_loaders([loader])
conn = sqlite3.connect("persist/chat_history.db")
cursor = conn.cursor()
cursor.execute("SELECT type, message FROM message_store WHERE session_id = 1")
conversation = [(type, message) for type, message in cursor.fetchall()]
conn.close()
llm = ChatOpenAI(temperature=0.7, model="gpt-3.5-turbo-1106")
template = (
    "Combine the chat history and follow up question into "
    + "a standalone question. Chat History: "
    + str(conversation)
    + ". Follow up question: "
    + query
)
memory = ConversationBufferMemory(
    memory_key="chat_history", input_key="question", return_messages=True
)
prompt = PromptTemplate.from_template(template)
question_generator = LLMChain(
    llm=ChatOpenAI(
        temperature=0,
        streaming=True,
    ),
    prompt=CONDENSE_QUESTION_PROMPT,
)
doc_chain = load_qa_chain(
    llm=ChatOpenAI(
        temperature=0,
        streaming=True,
    ),
    chain_type="stuff",
)
chain = ConversationalRetrievalChain(
    combine_docs_chain=doc_chain,
    question_generator=question_generator,
    retriever=index.vectorstore.as_retriever(),
    verbose=True,
    output_key="output",
)
system_message = (
    "Your name is EnsetAI, a chatbot that knows everything about ENSET Mohammedia."
)
tools = [
    Tool(
        name="qa-enset",
        func=chain.run,
        description="Useful when you need to answer ENSET-related questions",
    )
]
def ask(input: str) -> str:
    result = ""
    try:
        new_message = ("question", input)
        conversation.append(new_message)
        print(conversation)
        result = agent.run({"chat_history": conversation, "input": input})
    except Exception as e:
        response = str(e)
        if response.startswith("Could not parse LLM output: `"):
            response = response.removeprefix(
                "Could not parse LLM output: `"
            ).removesuffix("`")
            return response
        else:
            raise Exception(str(e))
    return result
chat_history = []
agent = initialize_agent(
    agent=AgentType.CHAT_CONVERSATIONAL_REACT_DESCRIPTION,
    tools=tools,
    llm=llm,
    input_key="question",
    agent_kwargs={"system_message": system_message},
    verbose=True,
    max_execution_time=30,
    memory=memory,
    max_iterations=6,
    handle_parsing_errors=True,
    early_stopping_method="generate",
    stop=["\nObservation:"],
)
result = ask(query)
print(result)
```

The problem appears to be because of that `agent.run({"chat_history": conversation, "input": input})`.
I have a couple of questions:
* Is it even logical to use different chains for `question_generator` and `doc_chain`? Can't I just pass a list or a dict with existing messages? that's literally all I need.
* How to solve the error? it may have to do with keys I provided/didn't provide, but I'm not sure exactly where is the issue.

**Comment by Issaminu** [comment]
I ended up solving it at the end. And not gonna lie @dosu-bot was hella useless.
Here's my full code if anyone needs to copy something:
```python
import os
import sys
from langchain.chat_models import ChatOpenAI
from langchain.document_loaders import DirectoryLoader, TextLoader
from langchain.embeddings import OpenAIEmbeddings
from langchain.indexes import VectorstoreIndexCreator
from langchain.indexes.vectorstore import VectorStoreIndexWrapper
from langchain.vectorstores.chroma import Chroma
from langchain.memory import ConversationBufferMemory
from langchain.chains.conversational_retrieval.prompts import CONDENSE_QUESTION_PROMPT
from langchain.chains.retrieval_qa.base import RetrievalQA
from langchain.schema import HumanMessage, AIMessage
from langchain.chains import LLMChain
from langchain.tools import Tool
from langchain.agents.types import AgentType
from langchain.agents import initialize_agent
from langchain.chains.question_answering import load_qa_chain
import sqlite3
from dotenv import load_dotenv

load_dotenv()
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

PERSIST = True

query = " ".join(sys.argv[1:]) if len(sys.argv) > 1 else None

if PERSIST and os.path.exists("persist"):
    vectorstore = Chroma(
        persist_directory="persist", embedding_function=OpenAIEmbeddings()
    )
    retreiver = VectorStoreIndexWrapper(
        vectorstore=vectorstore
    ).vectorstore.as_retriever()
else:
    # loader = TextLoader("combined.txt")
    loader = DirectoryLoader("text/www.enset-media.ac.ma")
    if PERSIST:
        retreiver = (
            VectorstoreIndexCreator(vectorstore_kwargs={"persist_directory": "persist"})
            .from_loaders([loader])
            .vectorstore.as_retriever()
        )
    else:
        retreiver = (
            VectorstoreIndexCreator().from_loaders([loader]).vectorstore.as_retriever()
        )


conn = sqlite3.connect("persist/chat_history.db")
cursor = conn.cursor()

cursor.execute("SELECT type, message FROM message_store WHERE session_id = 1")

conversation = [(type, message) for type, message in cursor.fetchall()]


conn.close()

llm = ChatOpenAI(temperature=0.7, model="gpt-3.5-turbo-1106")
print(conversation)

messages = []
for message in conversation:
    if message[0] == "human":
        messages.append(HumanMessage(content=message[1]))
    else:
        messages.append(AIMessage(content=message[1]))


memory = ConversationBufferMemory(return_messages=True)

question_generator = LLMChain(
    llm=ChatOpenAI(
        temperature=0,
        streaming=True,
    ),
    prompt=CONDENSE_QUESTION_PROMPT,
)
doc_chain = load_qa_chain(
    llm=ChatOpenAI(
        temperature=0,
        streaming=True,
    ),
    chain_type="stuff",
)


chain = RetrievalQA(
    retriever=retreiver,
    combine_documents_chain=doc_chain,
    verbose=True,
    output_key="output",
)
system_message = (
    "Your name is EnsetAI, a chatbot that knows everything about ENSET Mohammedia."
)
tools = [
    Tool(
        name="qa-enset",
        func=chain.run,
        description="Useful when you need to answer ENSET-related questions",
    )
]


def ask(input: str) -> str:
    result = ""
    try:
        result = agent.run({"input": input, "chat_history": messages})
    except Exception as e:
        response = str(e)
        if response.startswith("Could not parse LLM output: `"):
            response = response.removeprefix(
                "Could not parse LLM output: `"
            ).removesuffix("`")
            return response
        else:
            raise Exception(str(e))
    return result


chat_history = []
agent = initialize_agent(
    agent=AgentType.CHAT_CONVERSATIONAL_REACT_DESCRIPTION,
    tools=tools,
    llm=llm,
    agent_kwargs={"system_message": system_message},
    verbose=True,
    max_execution_time=30,
    memory=memory,
    max_iterations=6,
    handle_parsing_errors=True,
    early_stopping_method="generate",
    stop=["\nObservation:"],
)


result = ask(query)
print(result)
```
I also had to comment out some code from the langchain source code. The file is `/home/<user>/.local/lib/python3.11/site-packages/langchain/memory/utils.py`:
```python
# Comment out these two lines
if len(prompt_input_keys) != 1:
        raise ValueError(f"One input key expected got {prompt_input_keys}")
```

The problem is that here, `agent.run()` requires passing `"chat_memory"` as an attribute. But then it proceeds to complain because you did as it asked.

And dayum this library has 4 chatbots that you can ask about the docs, **but none of them can help reduce the pain stemming from how terrible the docs are.**

**Comment by devstein** [comment]
Hey @Issaminu sorry to hear Dosu wasn't useful. Appreciate you posting your solution (Dosu will learn from it for future users)

If you have any feedback or ideas for how to improve Dosu, let me know! Or reach out at hi@dosu.dev
