### ISSUE TITLE
Trouble using OpenAI ChatCompletion (gpt-3.5-turbo model)

### ISSUE THREAD

**Issue by wiseman** [langchain-ai/langchain#1368]
Trying to use the new gpt-3.5-turbo model causes an error:

```
llm = OpenAI(model_name="gpt-3.5-turbo")
# ...
llm.run(...)
InvalidRequestError: Invalid URL (POST /v1/completions)
```

I also tried specifying a client but got the same error.
```
import openai
llm = OpenAI(model_name="gpt-3.5-turbo", client=openai.ChatCompletion)
```

Am I missing the trick or does langchain need to have support added specifically for ChatCompletion?

**Comment by hwchase17** [comment]
https://github.com/hwchase17/langchain/pull/1367

needs own class

**Comment by bentrevett** [comment]
@hwchase17 Is it possible to have the `prefix_message` different for each call to the OpenAIChat model? e.g. `llm_outputs = llm.generate(list_of_prompts, list_of_prefix_messages)`

**Comment by rbjarnason** [comment]
@hwchase17 Thanks so much for the quick turnaround on this. :) But our code is based on the langchain chat demo we get: ERROR:root:Async generation not implemented for this LLM - Any ideas? Something in the chat app code or still issue with langchain?

**Comment by yaodongC** [comment]
Instead of OpenAI(model_name="gpt-3.5-turbo") you need to use OpenAIChat(model_name='gpt-3.5-turbo'). Note this only works with langchain >=0.0.98

**Comment by hwchase17** [comment]
@rbjarnason async will be in tmrws release

**Comment by gcsun** [comment]
OpenAIChat still not work for me , this is my code :
```python
from langchain.prompts import PromptTemplate
from langchain.llms import OpenAIChat
from langchain.chains import LLMChain

llm = OpenAIChat(temperature=0,model_name='gpt-3.5-turbo', openai_api_key="sk-..." )
prompt = PromptTemplate(
    input_variables=["product"],
    template="What is a good name for a company that makes {product}?",
)

chain = LLMChain(llm=llm, prompt=prompt)

print(chain.run("colorful socks"))
```
the error:
```
Traceback (most recent call last):
  File "/Users/sunguanchao/Workspace/baidu/acg-fsu-alg-app/langchain-thought/langchain_thought/utils/langchain_tools/test_back_up/test_chatgpt_prompt.py", line 22, in <module>
    print(chain.run("colorful socks"))
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/langchain/chains/base.py", line 213, in run
    return self(args[0])[self.output_keys[0]]
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/langchain/chains/base.py", line 116, in __call__
    raise e
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/langchain/chains/base.py", line 113, in __call__
    outputs = self._call(inputs)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/langchain/chains/llm.py", line 57, in _call
    return self.apply([inputs])[0]
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/langchain/chains/llm.py", line 118, in apply
    response = self.generate(input_list)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/langchain/chains/llm.py", line 62, in generate
    return self.llm.generate_prompt(prompts, stop)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/langchain/llms/base.py", line 107, in generate_prompt
    return self.generate(prompt_strings, stop=stop)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/langchain/llms/base.py", line 140, in generate
    raise e
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/langchain/llms/base.py", line 137, in generate
    output = self._generate(prompts, stop=stop)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/langchain/llms/openai.py", line 645, in _generate
    full_response = completion_with_retry(self, messages=messages, **params)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/langchain/llms/openai.py", line 98, in completion_with_retry
    return _completion_with_retry(**kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/langchain/llms/openai.py", line 96, in _completion_with_retry
    return llm.client.create(**kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Invalid URL (POST /v1/chat/completions)
```

**Comment by FergusFettes** [comment]
It looks like this issue can be closed. https://github.com/hwchase17/langchain/issues/1368#issuecomment-1465583175 For example is either using an old version of langchain, and old version of openai, or both.

For anyone finding this because they are trying to use turbo/gpt4 with chains, you can apply my patch:

> If you are desperate to get this working, you can cherrypick the commit I made here: https://github.com/hwchase17/langchain/pull/1826

> Then you can use turbo and gpt4 for chains etc.

**Comment by rishibh7** [comment]
+1

**Comment by swamichandra** [comment]
When I specify `langchain>=0.0.98` in requirements.txt, it works locally on my machine. But the same is not working on Streamlit cloud. It is not able to pick up 0.0.98. Any suggestions?

When is 0.0.98 scheduled to be released?

**Comment by geocine** [comment]
I also tried this for the `csv_agent`. It just gets confused . The default  `text-davinci` works in one go.

![image](https://user-images.githubusercontent.com/507464/230288720-3575353e-e2f6-4fde-8faa-a3542edd576c.png)

**Comment by namedgraph** [comment]
What's the difference between `OpenAI` and `OpenAIChat`? 🤔

**Comment by dmyoung9** [comment]
@namedgraph `OpenAI` uses the standard models, while `ChatOpenAI` (since `OpenAIChat` is deprecated) uses the chat models.

I agree with @FergusFettes, this should be closed now.
