### ISSUE TITLE
DOC: how to use load_qa_chain with memory 

### ISSUE THREAD

**Issue by lfoppiano** [langchain-ai/langchain#13696]
### Issue with current documentation:

There is a lack of comprehensive documentation on how to use load_qa_chain with memory. 

I've found this: https://cheatsheet.md/langchain-tutorials/load-qa-chain-langchain.en but does not cover other memories, like for example BufferedWindowMemory. 

I have the following memory: 
```
memory = {ConversationBufferWindowMemory} chat_memory=ChatMessageHistory(messages=[HumanMessage(content='What is the main material? Keept he answer short'), AIMessage(content='The main material is R 2 Fe 14 B.'), HumanMessage(content='What are its properties? '), AIMessage(content='The properties 
 Config = {type} <class 'langchain.schema.memory.BaseMemory.Config'>
 ai_prefix = {str} 'AI'
 buffer = {str} 'Human: What is the main material? Keept he answer short\nAI: The main material is R 2 Fe 14 B.\nHuman: What are its properties? \nAI: The properties of the material being discussed are not explicitly mentioned in the given context. However, some information 
 buffer_as_messages = {list: 4} [content='What is the main material? Keept he answer short', content='The main material is R 2 Fe 14 B.', content='What are its properties? ', content='The properties of the material being discussed are not explicitly mentioned in the given context. Howeve
 buffer_as_str = {str} 'Human: What is the main material? Keept he answer short\nAI: The main material is R 2 Fe 14 B.\nHuman: What are its properties? \nAI: The properties of the material being discussed are not explicitly mentioned in the given context. However, some information 
 chat_memory = {ChatMessageHistory} messages=[HumanMessage(content='What is the main material? Keept he answer short'), AIMessage(content='The main material is R 2 Fe 14 B.'), HumanMessage(content='What are its properties? '), AIMessage(content='The properties of the material being discussed
 human_prefix = {str} 'Human'
 input_key = {NoneType} None
 k = {int} 4
 lc_attributes = {dict: 0} {}
 lc_secrets = {dict: 0} {}
 memory_key = {str} 'history'
 memory_variables = {list: 1} ['history']
 output_key = {NoneType} None
 return_messages = {bool} False
```

And the messages are the following: 
```
0 = {HumanMessage} content='What is the main material? Keept he answer short'
1 = {AIMessage} content='The main material is R 2 Fe 14 B.'
2 = {HumanMessage} content='What are its properties? '
3 = {AIMessage} content='The properties of the material being discussed are not explicitly mentioned in the given context. However, some information about the magnetic properties and microstructure of the material is provided. It is mentioned that the magnetic properties of the specimens were measured using a BH tracer or a vibrating sample magnetometer (VSM). The microstructure and crystal structure were analyzed using various techniques such as focused ion beam-scanning electron microscopy (FIB-SEM), electron probe microanalyses (EPMA), scanning transmission electron microscope-energy dispersive spectroscopy (STEM-EDS), and X-ray diffraction (XRD). The area ratio of each phase and the coverage ratio of the grains by the grain-boundary phase were calculated. Additionally, it is mentioned that the material contains rare-earth elements (Nd, Y, and Ce) and Fe, and that the coercivity can be improved by controlling the grain boundaries using certain phases (R6Fe13Ga and RFe2).'
```

And then I pass it to a load_qa_chain which is instantiated as follow (I'm summarising)

```
self.chain = load_qa_chain(llm, chain_type=qa_chain_type)
[...]
self.chain.run(input_documents=relevant_documents,
                                  question=query,
                                  memory=memory)
```

however, in the prompt, there seems to be no memory information. 

I would like to avoid having to rewrite the prompt with a custom one. Maybe the memory does not follow the required conventions (e.g. how the human / assitant message should be characterized), which are not clear to me, I haven't found any documentation in regard.

**Comment by lfoppiano** [comment]
@dosubot where can I find the template into load_qa_chain?  It seems that openai template and huggingface templates are different

**Comment by lfoppiano** [comment]
I tried to combine the ConversationChain but it does not work, I receive: 

```python 
Traceback (most recent call last):
  File "/Users/lfoppiano/anaconda3/envs/magneto/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 541, in _run_script
    exec(code, module.__dict__)
  File "/Users/lfoppiano/development/projects/grobid-magneto/document-qa/streamlit_app.py", line 322, in <module>
    _, text_response = st.session_state['rqa'][model].query_document(question, st.session_state.doc_id,
  File "/Users/lfoppiano/development/projects/grobid-magneto/document-qa/document_qa/document_qa_engine.py", line 108, in query_document
    response = self._run_query(doc_id, query, context_size=context_size)
  File "/Users/lfoppiano/development/projects/grobid-magneto/document-qa/document_qa/document_qa_engine.py", line 160, in _run_query
    return self.chain.run(input_documents=relevant_documents,
  File "/Users/lfoppiano/anaconda3/envs/magneto/lib/python3.9/site-packages/langchain/chains/base.py", line 510, in run
    return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[
  File "/Users/lfoppiano/anaconda3/envs/magneto/lib/python3.9/site-packages/langchain/chains/base.py", line 310, in __call__
    raise e
  File "/Users/lfoppiano/anaconda3/envs/magneto/lib/python3.9/site-packages/langchain/chains/base.py", line 304, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/Users/lfoppiano/anaconda3/envs/magneto/lib/python3.9/site-packages/langchain/chains/combine_documents/base.py", line 122, in _call
    output, extra_return_dict = self.combine_docs(
  File "/Users/lfoppiano/anaconda3/envs/magneto/lib/python3.9/site-packages/langchain/chains/combine_documents/stuff.py", line 171, in combine_docs
    return self.llm_chain.predict(callbacks=callbacks, **inputs), {}
  File "/Users/lfoppiano/anaconda3/envs/magneto/lib/python3.9/site-packages/langchain/chains/llm.py", line 298, in predict
    return self(kwargs, callbacks=callbacks)[self.output_key]
  File "/Users/lfoppiano/anaconda3/envs/magneto/lib/python3.9/site-packages/langchain/chains/base.py", line 310, in __call__
    raise e
  File "/Users/lfoppiano/anaconda3/envs/magneto/lib/python3.9/site-packages/langchain/chains/base.py", line 304, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/Users/lfoppiano/anaconda3/envs/magneto/lib/python3.9/site-packages/langchain/chains/llm.py", line 108, in _call
    response = self.generate([inputs], run_manager=run_manager)
  File "/Users/lfoppiano/anaconda3/envs/magneto/lib/python3.9/site-packages/langchain/chains/llm.py", line 127, in generate
    results = self.llm.bind(stop=stop, **self.llm_kwargs).batch(
  File "/Users/lfoppiano/anaconda3/envs/magneto/lib/python3.9/site-packages/langchain/schema/runnable/base.py", line 2819, in batch
    return self.bound.batch(
  File "/Users/lfoppiano/anaconda3/envs/magneto/lib/python3.9/site-packages/langchain/schema/runnable/base.py", line 439, in batch
    return cast(List[Output], [invoke(inputs[0], configs[0])])
  File "/Users/lfoppiano/anaconda3/envs/magneto/lib/python3.9/site-packages/langchain/schema/runnable/base.py", line 435, in invoke
    return self.invoke(input, config, **kwargs)
  File "/Users/lfoppiano/anaconda3/envs/magneto/lib/python3.9/site-packages/langchain/chains/base.py", line 87, in invoke
    return self(
TypeError: __call__() got an unexpected keyword argument 'stop'
```

**Comment by lfoppiano** [comment]
I fixed my problem by re-implementing the retrieval / query approach. As discussed [here](https://github.com/langchain-ai/langchain/issues/8748#issuecomment-1822187801).
