### ISSUE TITLE
ModuleNotFoundError: No module named 'xml.etree'; 'xml' is not a package

### ISSUE THREAD

**Issue by shine10076** [langchain-ai/langchain#13709]
### System Info

Traceback (most recent call last):
  File "/Users/xxx/anaconda3/envs/kaoyan-chat/lib/python3.10/site-packages/langchain/output_parsers/xml.py", line 2, in <module>
    import xml.etree.ElementTree as ET
  File "/Users/xxx/anaconda3/envs/kaoyan-chat/lib/python3.10/site-packages/langchain/output_parsers/xml.py", line 2, in <module>
    import xml.etree.ElementTree as ET
ModuleNotFoundError: No module named 'xml.etree'; 'xml' is not a package

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [X] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

llm = AzureChatOpenAI(model_name="gpt-35-turbo",
                      deployment_name="gpt-35-turbo", temperature=0.3)

tools = load_tools(["serpapi", "llm-math"], llm=llm)

### Expected behavior

i run this code and hope it can run normally, but it throw the exception. xml is not a package , i think this is beacause the python file is named xml.py , it confilct with import xml.etree.ElementTree as ET

**Comment by shine10076** [comment]
how to solve this problem? it must to rename this python file xml.py to xxx_xml.py?  can anyone explain why name these python file like json.py, xml.py and so on in langchain/output_parsers

**Comment by shine10076** [comment]
how to solve this problem? it must to rename this python file xml.py to xxx_xml.py? can anyone explain why name these python file like json.py, xml.py and so on in langchain/output_parsers @dosu-bot.

**Comment by shine10076** [comment]
i want to fix it in [rename xml.py-> xml_parser.py fix #13709](https://github.com/langchain-ai/langchain/pull/13715 )
