### ISSUE TITLE
AttributeError: 'NotImplementedType' object has no attribute 'get_input_schema'

### ISSUE THREAD

**Issue by austinmw** [langchain-ai/langchain#14128]
### System Info

Using latest docker versions for langchain templates

### Who can help?

@hwchase17 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

First, following the quickstart for Templates until it gets to LangSmith deployment:
1. `pip install -U langchain-cli`
2. `langchain app new my-app`
3. `cd my-app`
4. `langchain app add pirate-speak`

Then, since I don't have access to LangServe, follow the template README for docker deployment:
5. `docker build . -t my-langserve-app`
6. `docker run -e OPENAI_API_KEY=$OPENAI_API_KEY -p 8080:8080 my-langserve-app`

Results in error:
```
Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 416, in main
    run(
  File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/code/app/server.py", line 14, in <module>
    add_routes(app, NotImplemented)
  File "/usr/local/lib/python3.11/site-packages/langserve/server.py", line 627, in add_routes
    input_type_ = _resolve_model(runnable.get_input_schema(), "Input", model_namespace)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NotImplementedType' object has no attribute 'get_input_schema'
```

I also tried the `research-assistant` template and got a similar `get_input_schema` error. 

Am I missing a setup step?

### Expected behavior

Deploying the solution locally

**Comment by austinmw** [comment]
Looks like I just needed to modify the `server.py` file. I didn't get a message to do this automatically, which seems to be implied by, "After that, it will ask you if you want to generate route code for this project."

**Comment by Maxch3306** [comment]
same as you, how did you fix this

**Comment by dfackler** [comment]
In the actual server.py code is there is a dummy line for add_routes. It was line 16 for me. You need to change this to specify the path you are looking for. In my case, I am doing the rag-conversation template.  

First I add an import up top 
`from rag_conversation import chain as rag_conversation_chain`

Then I **edit** the existing add_routes line in the file.
```
# Edit this to add the chain you want to add
add_routes(app, rag_conversation_chain, path="/rag-conversation")
```

**Comment by Weltbummler1** [comment]
think the step instructions are a bit unclear, but yep ultimately makes sense and works as intended.

**Comment by NatiSayada** [comment]
I think the doc should be more explicit.
It should be _replace_ the line and not _add_
