### ISSUE TITLE
BUG: csv loader exception, AttributeError: partially initialized module 'importlib.metadata' has no attribute 'version' (most likely due to a circular import)

### ISSUE THREAD

**Issue by bluese** [langchain-ai/langchain#14173]
### System Info

langchain version ： 
  langchain                 0.0.344
  langchain-core            0.0.8

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

code:
  from langchain.document_loaders.csv_loader import CSVLoader    
  loader = CSVLoader(file_path='./test.csv')
  data = loader.load()

### Expected behavior

exception:
Traceback (most recent call last):
  File "/Users/liucong/opt/miniconda3/envs/310-test/lib/python3.10/site-packages/langchain_core/__init__.py", line 4, in <module>
    __version__ = metadata.version(__package__)
AttributeError: partially initialized module 'importlib.metadata' has no attribute 'version' (most likely due to a circular import)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/liucong/opt/miniconda3/envs/310-test/lib/python3.10/site-packages/langchain/__init__.py", line 4, in <module>
    from importlib import metadata
  File "/Users/liucong/opt/miniconda3/envs/310-test/lib/python3.10/importlib/metadata/__init__.py", line 4, in <module>
    import csv
  File "/Users/liucong/PycharmProjects/llm_learn/lang_chain/data_connection/csv.py", line 1, in <module>
    from langchain.document_loaders.csv_loader import CSVLoader
  File "/Users/liucong/opt/miniconda3/envs/310-test/lib/python3.10/site-packages/langchain/document_loaders/__init__.py", line 18, in <module>
    from langchain.document_loaders.acreom import AcreomLoader
  File "/Users/liucong/opt/miniconda3/envs/310-test/lib/python3.10/site-packages/langchain/document_loaders/acreom.py", line 5, in <module>
    from langchain_core.documents import Document
  File "/Users/liucong/opt/miniconda3/envs/310-test/lib/python3.10/site-packages/langchain_core/__init__.py", line 5, in <module>
    except metadata.PackageNotFoundError:
AttributeError: partially initialized module 'importlib.metadata' has no attribute 'PackageNotFoundError' (most likely due to a circular import)

**Comment by bluese** [comment]
> @bluese There is a `csv.py` file in your project. It conflicts with the name of the [`csv`](https://docs.python.org/3/library/csv.html) module of the standard library. You should change the name.您的项目中有一个 `csv.py` 文件。它与标准库的 `csv` 模块的名称冲突。你应该改个名字。
> 
> > File "/Users/liucong/PycharmProjects/llm_learn/lang_chain/data_connection/csv.py", line 1, in文件“/Users/liucong/PycharmProjects/llm_learn/lang_chain/data_connection/csv.py”，第 1 行，位于
> > from langchain.document_loaders.csv_loader import CSVLoader从 langchain.document_loaders.csv_loader 导入 CSVLoader

thank you.
