### ISSUE TITLE
Using AzureSearch with custom vector field names

### ISSUE THREAD

**Issue by levalencia** [langchain-ai/langchain#14298]
### System Info

azure-search-documents==11.4.0b9
langchain                 0.0.342
langchain-core            0.0.7

### Who can help?

@hwc

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

My local.settings.json has the custom field names for Azure Cognitive Search:

```
{
  "IsEncrypted": false,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "python",
    "AZURESEARCH_FIELDS_ID" :"chunk_id",
    "AZURESEARCH_FIELDS_CONTENT" :"chunk",
    "AZURESEARCH_FIELDS_CONTENT_VECTOR " :"vector",
    "AZURESEARCH_FIELDS_TAG" :"metadata",
    "FIELDS_ID" : "chunk_id",
    "FIELDS_CONTENT" : "chunk",
    "FIELDS_CONTENT_VECTOR" : "vector",
    "FIELDS_METADATA" : "metadata",
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "AzureWebJobsFeatureFlags": "EnableWorkerIndexing"
  }
}
```

I also tried to create a Fields array and pass it into the AzureSearch constructor like this:

 ```
 os.environ["AZURE_OPENAI_API_KEY"] = "xx"
            os.environ["AZURE_OPENAI_ENDPOINT"] = "https://xx.openai.azure.com/"
            embeddings = AzureOpenAIEmbeddings(
                azure_deployment="text-embedding-ada-002",
                openai_api_version="2023-05-15",
            )
           
            fields = [
                SimpleField(
                    name="chunk_id",
                    type=SearchFieldDataType.String,
                    key=True,
                    filterable=True,
                ),
                SearchableField(
                    name="chunk",
                    type=SearchFieldDataType.String,
                    searchable=True,
                ),
                SearchField(
                    name="vector",
                    type=SearchFieldDataType.Collection(SearchFieldDataType.Single),
                    searchable=True,
                    vector_search_dimensions=1536,
                    vector_search_configuration="default",
                )
            ]
            
            FIELDS_ID = get_from_env(
                key="AZURESEARCH_FIELDS_ID", env_key="AZURESEARCH_FIELDS_ID", default="id"
            )
            FIELDS_CONTENT = get_from_env(
                key="AZURESEARCH_FIELDS_CONTENT",
                env_key="AZURESEARCH_FIELDS_CONTENT",
                default="content",
            )
            FIELDS_CONTENT_VECTOR = get_from_env(
                key="AZURESEARCH_FIELDS_CONTENT_VECTOR",
                env_key="AZURESEARCH_FIELDS_CONTENT_VECTOR",
                default="content_vector",
            )
            FIELDS_METADATA = get_from_env(
                key="AZURESEARCH_FIELDS_TAG", env_key="AZURESEARCH_FIELDS_TAG", default="metadata"
            )
                        
            vector_store_address: str = "https://xx.search.windows.net"
            vector_store_password: str = "xx"
            vector_store: AzureSearch = AzureSearch(
                azure_search_endpoint=vector_store_address,
                azure_search_key=vector_store_password,
                index_name="vector-1701341754619",
                fiekds=fields,
                embedding_function=embeddings.embed_query
            )
            llm = AzureChatOpenAI(
                azure_deployment="chat",
                openai_api_version="2023-05-15",
            )  
            chain = RetrievalQA.from_chain_type(llm=llm,
                                                chain_type="stuff",
                                                retriever=Element61Retriever(vectorstore=vector_store),
                                                return_source_documents=True)
            result = chain({"query": 'Whats out of scope?'})
            return result
```

However I am always getting:
```
Executed 'Functions.TestCustomRetriever' (Failed, Id=2f243ed8-24bd-414b-af51-6cf1419633a5, Duration=6900ms)
[2023-12-05T15:08:53.252Z] System.Private.CoreLib: Exception while executing function: Functions.TestCustomRetriever. System.Private.CoreLib: Result: Failure
Exception: HttpResponseError: (InvalidRequestParameter) Unknown field 'content_vector' in vector field list.
Code: InvalidRequestParameter
Message: Unknown field 'content_vector' in vector field list.
Exception Details:      (UnknownField) Unknown field 'content_vector' in vector field list.
        Code: UnknownField
```

Please note this is being executed in an Azure Function locally

### Expected behavior

The custom field names should be taken into account

**Comment by kaito0228** [comment]
I too am facing this problem.
Do you have any plans to resolve it?
I just want to have a reference to the VECTOR FIELDS that we specify.

**Comment by alexmanie** [comment]
Hi @levalencia , 
Are you still having this issue? Are you trying to execute that piece of code inside an Azure Function app?

When you run that piece of code in your solution, what is the value you get for "**FIELDS_CONTENT_VECTOR**" variable?

```python
FIELDS_CONTENT_VECTOR = get_from_env(
               key="AZURESEARCH_FIELDS_CONTENT_VECTOR",
               env_key="AZURESEARCH_FIELDS_CONTENT_VECTOR",
               default="content_vector",
           )
```

**Comment by gurvinder-dhillon** [comment]
Did anyone ever found a solution to this. None of the suggested solution work.

**Comment by levalencia** [comment]
> ```python
> import os
> 
> os.environ["AZURESEARCH_FIELDS_ID"] = "chunk_id"
> os.environ["AZURESEARCH_FIELDS_CONTENT"] = "chunk"
> os.environ["AZURESEARCH_FIELDS_CONTENT_VECTOR"] = "vector"
> os.environ["AZURESEARCH_FIELDS_TAG"] = "metadata"
> 
> from langchain.vectorstores import AzureSearch
> ```

this worked for me

**Comment by Hadi2525** [comment]
I am also getting the same error. It sounds like, the index fields should follow the environment variables set like this:
```
os.environ["AZURESEARCH_FIELDS_ID"] 
os.environ["AZURESEARCH_FIELDS_CONTENT"] 
os.environ["AZURESEARCH_FIELDS_CONTENT_VECTOR"] 
os.environ["AZURESEARCH_FIELDS_TAG"] 
```
and there is no way to apply a custom field name based on my built index on Azure Cognitive Search.

pulling @hwchase17 and @pamelafox and @marlenezw for their insights.

**Comment by marlenezw** [comment]
Thanks for the tag @Hadi2525, let me take a look

**Comment by ANMOL2001A** [comment]
what if we don't want to set enviroment variable can we pass our own feilds instead of default feilds

**Comment by Hadi2525** [comment]
I am still waiting for the relevant contributor to chime in. Maybe @marlenezw if you have any updates on this issue please let us know thank you!

**Comment by rcruzgar** [comment]
Hi! any updates about this error? I am trying to make a multivectorial search and I am having the same issue.  Do you know if it has been fixed in the latest langchain releases?

**Comment by Hadi2525** [comment]
> Hi! any updates about this error? I am trying to make a multivectorial search and I am having the same issue. Do you know if it has been fixed in the latest langchain releases? (I don't think so: https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/vectorstores/azuresearch.py). Setting the environment variable before importing the class works for me, but I need to make the search on few vectors, not just one. AzureSearch should take some parameter like "vector_field_name" to dynamically construct vector stores, instead of restricting it to only one previously set as environment variable.

Hey @rcruzgar  yea I don't see any developers focusing on this issue. I will try to take a stab at it and put a PR out soon. Stay tuned.

**Comment by jo-jstrm** [comment]
I am also facing this issue. My current workaround is not changing the environment variables, but rather directly update the global variables that are instantiated based on the env variables:
```python
import langchain_community.vectorstores.azuresearch as azuresearch

azuresearch.FIELDS_CONTENT_VECTOR='whatever_your_field_is_named'

# Will use 'whatever_your_field_is_named' for retrieval
search = AzureSearch(...)
```
This way, you can easily change the field names during runtime and save the roundtrip via environment vars.

**Comment by gajanandC** [comment]
Hi @Hadi2525 , did you get any resolution to the issue, instead of setting environment variable , can we directly pass the custom vector field name to azuresearch object

**Comment by marlenezw** [comment]
I started taking a look but got caught up in a few other things. @mattgotteiner any thoughts on this? I can probably get around to a PR after next week

**Comment by Hadi2525** [comment]
Hello,

Just as a reference, `AzureAISearchRetriever` used in https://python.langchain.com/docs/integrations/retrievers/azure_ai_search/ sounds to be a solution to calling custom field names. I did not come across the issue with this library.

from langchain_community.retrievers import AzureAISearchRetriever

retriever = AzureAISearchRetriever(
    content_key="content", top_k=1, index_name="langchain-vector-demo"
)

One major issue with `Azure AI Search` is that the POST method does not allow to search against a certain custom field. Unless you manually check/uncheck the `searchable` term for the field inside `Azure Portal`. Another option is to add `filtering` to the `search` method from the `Azure Search Document` library.

I hope it helps.

**Comment by marlenezw** [comment]
Thank you! That does help. I'll tag you in the PR once I have it going

**Comment by Hadi2525** [comment]
@marlenezw Thank you Marlene! I can work on this as well (I have some free time this weekend).

Also, let's remove the `__del__` causing the following error as well:
```
Exception ignored in: <function AzureSearch.__del__ at 0x7f51d9d044a0>
Traceback (most recent call last):
  File "/anaconda/envs/goa-aicoe-tradesecrets/lib/python3.12/site-packages/langchain_community/vectorstores/azuresearch.py", line 422, in __del__
  File "/anaconda/envs/goa-aicoe-tradesecrets/lib/python3.12/asyncio/events.py", line 782, in get_event_loop_policy
  File "/anaconda/envs/goa-aicoe-tradesecrets/lib/python3.12/asyncio/events.py", line 775, in _init_event_loop_policy
ImportError: sys.meta_path is None, Python is likely shutting down

**Comment by freegor** [comment]
hi guys, any update about it?

**Comment by Adamsimsy** [comment]
My workaround for this was to create a new index, using the existing index json and renaming the field 'text_vector' to 'content_vector'. 

If like me you used the 'Import and vectorize data' wizard, you'll need to also need to update the skillset.

Hope that might help someone else.
