### ISSUE TITLE
RunnableWithMessageHistory streaming bug

### ISSUE THREAD

**Issue by ShukriChiu** [langchain-ai/langchain#14511]
### System Info

0.0.348, linux , python 3.11

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [x] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
 chain_with_history = RunnableWithMessageHistory(
        chain,
        lambda session_id: RedisChatMessageHistory(session_id, url=REDIS_URL, ttl=600),
        input_messages_key="inputs",
        history_messages_key="history",
    )
    return chain_with_history

  response = customer_support_invoke().stream(
          {"inputs": userChats.inputs, "profile": userChats.profile},
          config={"configurable": {"session_id": "123"}},
      )
      for s in response:
          print(s.content, end="", flush=True)
```

if I streaming twice , it will raise an error "ValueError: Got unexpected message type: AIMessageChunk
"

### Expected behavior

streaming correctly

**Comment by ShukriChiu** [comment]
@dosu-bot
do you have a simple way to resolve it.

**Comment by ShukriChiu** [comment]
@dosu-bot
error still exist:
Traceback (most recent call last):
  File "/root/shujiancoding/SinocareGPT/customer_support.py", line 191, in <module>
    for c in response:
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 3005, in stream
    yield from self.bound.stream(
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 3005, in stream
    yield from self.bound.stream(
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 1882, in stream
    yield from self.transform(iter([input]), config, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 1872, in transform
    yield from self._transform_stream_with_config(
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 1121, in _transform_stream_with_config
    for chunk in iterator:
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 1836, in _transform
    for output in final_pipeline:
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 3030, in transform
    yield from self.bound.transform(
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 1872, in transform
    yield from self._transform_stream_with_config(
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 1121, in _transform_stream_with_config
    for chunk in iterator:
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 1836, in _transform
    for output in final_pipeline:
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 686, in transform
    for chunk in input:
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 686, in transform
    for chunk in input:
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 2141, in transform
    yield from self._transform_stream_with_config(
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 1121, in _transform_stream_with_config
    for chunk in iterator:
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 2126, in _transform
    chunk = AddableDict({step_name: future.result()})
                                    ^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.6/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.6/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/root/.pyenv/versions/3.11.6/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 686, in transform
    for chunk in input:
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_core/utils/iter.py", line 52, in tee_peer
    item = next(iterator)
           ^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 3030, in transform
    yield from self.bound.transform(
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_core/runnables/passthrough.py", line 466, in transform
    yield from self._transform_stream_with_config(
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 1121, in _transform_stream_with_config
    for chunk in iterator:
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_core/runnables/passthrough.py", line 456, in _transform
    yield cast(Dict[str, Any], first_map_chunk_future.result())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.6/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.6/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/root/.pyenv/versions/3.11.6/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 2141, in transform
    yield from self._transform_stream_with_config(
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 1121, in _transform_stream_with_config
    for chunk in iterator:
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 2126, in _transform
    chunk = AddableDict({step_name: future.result()})
                                    ^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.6/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.6/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/root/.pyenv/versions/3.11.6/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 3030, in transform
    yield from self.bound.transform(
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 696, in transform
    yield from self.stream(final, config, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 491, in stream
    yield self.invoke(input, config, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 2631, in invoke
    return self._call_with_config(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 886, in _call_with_config
    output = call_func_with_variable_args(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_core/runnables/config.py", line 308, in call_func_with_variable_args
    return func(input, **kwargs)  # type: ignore[call-arg]
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 2549, in _invoke
    output = call_func_with_variable_args(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_core/runnables/config.py", line 308, in call_func_with_variable_args
    return func(input, **kwargs)  # type: ignore[call-arg]
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_core/runnables/history.py", line 249, in _enter_history
    return hist.messages.copy()
           ^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_community/chat_message_histories/redis.py", line 54, in messages
    messages = messages_from_dict(items)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_core/messages/__init__.py", line 98, in messages_from_dict
    return [_message_from_dict(m) for m in messages]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_core/messages/__init__.py", line 98, in <listcomp>
    return [_message_from_dict(m) for m in messages]
            ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/sinocaregpt-AEuQH49k-py3.11/lib/python3.11/site-packages/langchain_core/messages/__init__.py", line 86, in _message_from_dict
    raise ValueError(f"Got unexpected message type: {_type}")
ValueError: Got unexpected message type: AIMessageChunk
Error in LangChainTracer.on_chain_error callback: ImportError('sys.meta_path is None, Python is likely shutting down')

**Comment by ShukriChiu** [comment]
@dosu-bot
```
    userChats = UserChats(
        user_id="33b2b7b03ba8467f972877b999dc3af8",
        inputs="oppo 保活",
        profile={
            "用户名": "罗和平",
            "年龄": "70",
            "性别": "男",
            "身高": "163.5cm",
            "体重": "67.15kg",
            "腰围": "94cm",
            "糖尿病类型": "2型",
            "确诊时间": "2003-10-29",
            "最近HbA1c": "11.8 (2023-10-29)",
            "是否佩戴连续血糖监测器": "是",
            "主要症状": "患者10年前发现血糖高，诊断为2型糖尿病，患者现予以二甲双胍 1片 每天一次 及达美康 2片 每天一次治疗，有口干、尿多，有视物模糊、手脚麻木，夜间睡眠可，皮肤瘙痒感，双下肢怕冷，头晕、头痛。",
            "既往病史": "过敏性鼻炎、肾结石",
            "药物过敏史": "无",
            "流行病史": "无",
            "个人史": "抽烟，一天10根",
            "家族史": "无",
        },
    )

    response = customer_support_invoke().stream(
        {"inputs": userChats.inputs, "profile": userChats.profile},
        config={"configurable": {"session_id": "123"}},
    )
    for c in response:
        print(c.content, end="", flush=True)
``` 
above is my code. If I run it twice, it will raise an error.

**Comment by xiechengmude** [comment]
The same bug met  here. I will trace the issue.

**Comment by jamiesun** [comment]
I'm having this problem too, and my temporary solution is Customizing MyRedisChatMessageHistory
It's running fine now.

```python
import json
import logging
from typing import Optional
from typing import List

from langchain_core.messages.ai import AIMessageChunk

from langchain_core.chat_history import BaseChatMessageHistory
from langchain_core.messages import (
    BaseMessage,
    messages_from_dict
)

from langchain_community.utilities.redis import get_client

logger = logging.getLogger(__name__)


def message_to_dict(message: BaseMessage) -> dict:
    if isinstance(message, AIMessageChunk):
        data = message.dict()
        data["type"] = "ai"
        return {"type": "ai", "data": data}
    return {"type": message.type, "data": message.dict()}


class MyRedisChatMessageHistory(BaseChatMessageHistory):
    """Chat message history stored in a Redis database."""

    def __init__(
        self,
        session_id: str,
        url: str = "redis://localhost:6379/0",
        key_prefix: str = "message_store:",
        ttl: Optional[int] = None,
    ):
        try:
            import redis
        except ImportError:
            raise ImportError(
                "Could not import redis python package. "
                "Please install it with `pip install redis`."
            )

        try:
            self.redis_client = get_client(redis_url=url)
        except redis.exceptions.ConnectionError as error:
            logger.error(error)

        self.session_id = session_id
        self.key_prefix = key_prefix
        self.ttl = ttl

    @property
    def key(self) -> str:
        """Construct the record key to use"""
        return self.key_prefix + self.session_id

    @property
    def messages(self) -> List[BaseMessage]:  # type: ignore
        """Retrieve the messages from Redis"""
        _items = self.redis_client.lrange(self.key, 0, -1)
        items = [json.loads(m.decode("utf-8")) for m in _items[::-1]]
        messages = messages_from_dict(items)
        return messages

    def add_message(self, message: BaseMessage) -> None:
        """Append the message to the record in Redis"""
        self.redis_client.lpush(self.key, json.dumps(message_to_dict(message)))
        if self.ttl:
            self.redis_client.expire(self.key, self.ttl)

    def clear(self) -> None:
        """Clear session memory from Redis"""
        self.redis_client.delete(self.key)

```

**Comment by jonnolen** [comment]
this is referenced here and there was a proposed change: https://github.com/gpt-engineer-org/gpt-engineer/issues/804
