### ISSUE TITLE
GithubAPIWrapper throws list index out of range error

### ISSUE THREAD

**Issue by usamasaleem1** [langchain-ai/langchain#14550]
### System Info

Name: langchain
Version: 0.0.348

Name: PyGithub
Version: 2.1.1

### Who can help?
@hwchase17 
@agola11 
``` 
Traceback (most recent call last):
  File "/Users/mac/Dev Projects/Chainlit_qa/test.py", line 12, in <module>
    github = GitHubAPIWrapper(
             ^^^^^^^^^^^^^^^^^
  File "/Users/mac/Dev Projects/Chainlit_qa/myenv/lib/python3.11/site-packages/pydantic/v1/main.py", line 339, in __init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Dev Projects/Chainlit_qa/myenv/lib/python3.11/site-packages/pydantic/v1/main.py", line 1102, in validate_model
    values = validator(cls_, values)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Dev Projects/Chainlit_qa/myenv/lib/python3.11/site-packages/langchain/utilities/github.py", line 69, in validate_environment
    installation = gi.get_installations()[0]
                   ~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/mac/Dev Projects/Chainlit_qa/myenv/lib/python3.11/site-packages/github/PaginatedList.py", line 62, in __getitem__
    return self.__elements[index]
           ~~~~~~~~~~~~~~~^^^^^^^
IndexError: list index out of range
```

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Run basic python file:

```
from langchain.agents.agent_toolkits.github.toolkit import GitHubToolkit
from langchain.utilities.github import GitHubAPIWrapper

github = GitHubAPIWrapper()
toolkit = GitHubToolkit.from_github_api_wrapper(github)
tools = toolkit.get_tools()

```

### Expected behavior

Fetching github repository information

**Comment by usamasaleem1** [comment]
Still same error while logging validate_environment

**Comment by keenborder786** [comment]
Let me see.

**Comment by usamasaleem1** [comment]
> I have created a PR for this but just to clarify , in order to use the wrapper for your repo, you need to make sure that you have installed the app on the repo. Please see `Repository access` in your app configuration and make sure to install the app on the repo.

Thanks, i've done that, and now I get this error:

```
2023-12-12 12:03:41 - 1 validation error for GitHubAPIWrapper
__root__
  An error occurred while validating the environment: name 'GitHubIntegration' is not defined (type=value_error)
Traceback (most recent call last):
  File "/Users/mac/Dev Projects/Chainlit_qa/myenv/lib/python3.11/site-packages/chainlit/utils.py", line 41, in wrapper
    return user_function(**params_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Dev Projects/Chainlit_qa/chainlit_app.py", line 106, in start
    github = GitHubAPIWrapper()
             ^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Dev Projects/Chainlit_qa/myenv/lib/python3.11/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for GitHubAPIWrapper
__root__
  An error occurred while validating the environment: name 'GitHubIntegration' is not defined (type=value_error)

```

**Comment by keenborder786** [comment]
Make sure to install PyGithub:
```bash
pip install PyGithub
```

Can you please more of your code so that I can help you better because this does not seem problem with langchain.

**Comment by usamasaleem1** [comment]
> Make sure to install PyGithub:
> 
> ```shell
> pip install PyGithub
> ```
> 
> Can you please more of your code so that I can help you better because this does not seem problem with langchain.

I found the issue. I just didn't set the permissions for my APi to the full scope lol.

**Comment by triThirty** [comment]
Hi @keenborder786 ,
I got this error
```Bash
Traceback (most recent call last):
  File "/Users/Downloads/archive/ai/main.py", line 28, in <module>
    github = GitHubAPIWrapper()
             ^^^^^^^^^^^^^^^^^^
  File "/Users/Downloads/archive/venv/lib/python3.11/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for GitHubAPIWrapper
__root__
  ('Could not deserialize key data. The data may be in an incorrect format, it may be encrypted with an unsupported algorithm, or it may be an unsupported key type (e.g. EC curves with explicit parameters).', [<OpenSSLError(code=75497580, lib=9, reason=108, reason_text=no start line)>]) (type=value_error)
```
I am not sure `github = GitHubAPIWrapper()` is ok, cause I found `github` and `github_repo_instance` are mandatory.
But I am confused because both values would be set [here](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/utilities/github.py#L107-L108). So could you give me some clue? Thanks
