### ISSUE TITLE
 SQLDatabaseChain with LlamaCpp Llama2 "Chain Run Errored With Error: ArgumentError: <class 'TypeError'>: wrong type" 

### ISSUE THREAD

**Issue by QUAY17** [langchain-ai/langchain#14660]
### System Info

LangChain version 0.0.348
Python version 3.10
Operating System MacOS Monterey version 12.6
SQLAlchemy version 2.0.23

### Who can help?

@hwchase17 
@agola11

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```# Connect to db
# Create an SQLAlchemy engine
engine = create_engine("mysql+mysqlconnector://user:pass@host/database")

# Test the database connection
try:
    # Connect and execute a simple query
    with engine.connect() as connection:
        query = text("SELECT 1")
        result = connection.execute(query)
        for row in result:
            print("Connection successful, got row:", row)
except Exception as e:
    print("Error connecting to database:", e)

# Create an instance of SQLDatabase
db = SQLDatabase(engine)

# using Llama2 
llm = LlamaCpp(
    model_path="/path_to/llama-2-7b.Q4_K_M.gguf", 
    verbose=True, 
    n_ctx=2048)

# using Default and Suffix prompt template
PROMPT = PromptTemplate(
    input_variables=["input", "table_info", "dialect", "top_k"],
    template=_DEFAULT_TEMPLATE + PROMPT_SUFFIX,
)

db_chain = SQLDatabaseChain.from_llm(llm, db, verbose=True, return_sql=True, 
                                     prompt=PROMPT)

langchain.debug = True

response = db_chain.run(formatted_prompt)
print(response


### Expected behavior

Expected Behavior: Expected to generate SQL queries without errors.

Actual Behavior: Received TypeError: wrong type and context window exceedance errors.

File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/llama_cpp/llama.py", line 1325, in _create_completion
    f"Requested tokens ({len(prompt_tokens)}) exceed context window of {llama_cpp.llama_n_ctx(self._ctx)}"
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/llama_cpp/llama_cpp.py", line 612, in llama_n_ctx
    return _lib.llama_n_ctx(ctx)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type```

**Comment by QUAY17** [comment]
[chain/start] [1:chain:SQLDatabaseChain] Entering Chain run with input:
...
[chain/start] [1:chain:SQLDatabaseChain > 2:chain:LLMChain] Entering Chain run with input:
...
[llm/error] [1:chain:SQLDatabaseChain > 2:chain:LLMChain > 3:llm:LlamaCpp] [26ms] LLM run errored with error:
"ArgumentError(\"argument 1: <class 'TypeError'>: wrong type\")"
[chain/error] [1:chain:SQLDatabaseChain > 2:chain:LLMChain] [28ms] Chain run errored with error:
"ArgumentError(\"argument 1: <class 'TypeError'>: wrong type\")"
[chain/error] [1:chain:SQLDatabaseChain] [90ms] Chain run errored with error:
"ArgumentError(\"argument 1: <class 'TypeError'>: wrong type\")"
Traceback (most recent call last):
    response = db_chain.run(formatted_prompt)
.
.
.
File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/llama_cpp/llama.py", line 1325, in _create_completion
    f"Requested tokens ({len(prompt_tokens)}) exceed context window of {llama_cpp.llama_n_ctx(self._ctx)}"
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/llama_cpp/llama_cpp.py", line 612, in llama_n_ctx
    return _lib.llama_n_ctx(ctx)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type

**Comment by QUAY17** [comment]
here is the full error message:


llm/error] [1:chain:SQLDatabaseChain > 2:chain:LLMChain > 3:llm:LlamaCpp] [26ms] LLM run errored with error:
"ArgumentError(\"argument 1: <class 'TypeError'>: wrong type\")"
[chain/error] [1:chain:SQLDatabaseChain > 2:chain:LLMChain] [28ms] Chain run errored with error:
"ArgumentError(\"argument 1: <class 'TypeError'>: wrong type\")"
[chain/error] [1:chain:SQLDatabaseChain] [90ms] Chain run errored with error:
"ArgumentError(\"argument 1: <class 'TypeError'>: wrong type\")"
Traceback (most recent call last):
  File "/Users/quay17/Desktop/GitLocal/NLP/db/langChain.py", line 194, in <module>
    response = db_chain.run(formatted_prompt)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/chains/base.py", line 507, in run
    return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/chains/base.py", line 312, in __call__
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/chains/base.py", line 306, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain_experimental/sql/base.py", line 201, in _call
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain_experimental/sql/base.py", line 132, in _call
    sql_cmd = self.llm_chain.predict(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/chains/llm.py", line 293, in predict
    return self(kwargs, callbacks=callbacks)[self.output_key]
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/chains/base.py", line 312, in __call__
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/chains/base.py", line 306, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/chains/llm.py", line 103, in _call
    response = self.generate([inputs], run_manager=run_manager)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/chains/llm.py", line 115, in generate
    return self.llm.generate_prompt(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 516, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 666, in generate
    output = self._generate_helper(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 553, in _generate_helper
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 540, in _generate_helper
    self._generate(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 1069, in _generate
    self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/llms/llamacpp.py", line 292, in _call
    for chunk in self._stream(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/llms/llamacpp.py", line 345, in _stream
    for part in result:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/llama_cpp/llama.py", line 1325, in _create_completion
    f"Requested tokens ({len(prompt_tokens)}) exceed context window of {llama_cpp.llama_n_ctx(self._ctx)}"
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/llama_cpp/llama_cpp.py", line 612, in llama_n_ctx
    return _lib.llama_n_ctx(ctx)
