### ISSUE TITLE
SerpAPIWrapper doesn't work

### ISSUE THREAD

**Issue by don007git** [langchain-ai/langchain#14855]
### System Info

**Below is my Linux box:**
Linux  5.15.0-1014-azure #17~20.04.1-Ubuntu SMP Thu Jun 23 20:01:51 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Below is libraries within my conda environment:**
google-auth                              2.24.0
google-search-results                    2.4.2
googleapis-common-protos                 1.61.0
langchain                                0.0.349
langchain-cli                            0.0.19
langchain-community                      0.0.1
langchain-core                           0.0.13
langchainhub                             0.1.14
requests                                 2.31.0
requests-oauthlib                        1.3.1
types-requests                           2.31.0.10

### Who can help?

@hwchase17

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [X] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

**Below is source code:**

```
import requests
import json
import os

SERPAPI_API_KEY=os.environ["SERPAPI_API_KEY"]
print(f"{SERPAPI_API_KEY=}")

url = "https://google.serper.dev/search"
payload = json.dumps({
  "q": "apple inc"
})
headers = {
  'X-API-KEY': SERPAPI_API_KEY,
  'Content-Type': 'application/json'
}
response = requests.request("POST", url, headers=headers, data=payload)
print("************ result from request ***************")
print(response.text)


from langchain.utilities import SerpAPIWrapper
search = SerpAPIWrapper(serpapi_api_key=SERPAPI_API_KEY)

res = search.run("apple inc")
print("************ result from langchain ***************")
print(f"{res=}")

```

### Expected behavior

if the KEY works for request API, then SerpAPIWrapper shouldn't fails with invalid KEY error.

**Comment by don007git** [comment]
I didn't use async version, so my code will invoke results, instead of aresults .... so your explanations make no sense here. 
I upgrade my version to v0.0.350: "Successfully installed langchain-0.0.350 langchain-community-0.0.3 langchain-core-0.1.1"
but still get the same error as captured below. ****

Traceback (most recent call last):
    res = search.run("apple inc")
  File "/anaconda/envs/pyautogen/lib/python3.10/site-packages/langchain_community/utilities/serpapi.py", line 84, in run
    return self._process_response(self.results(query))
  File "/anaconda/envs/pyautogen/lib/python3.10/site-packages/langchain_community/utilities/serpapi.py", line 130, in _process_response
    raise ValueError(f"Got error from SerpAPI: {res['error']}")
ValueError: Got error from SerpAPI: Invalid API key. Your API key should be here: https://serpapi.com/manage-api-key
