### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by Vivek-Kawathalkar** [langchain-ai/langchain#15005]
### Issue you'd like to raise.

Traceback (most recent call last):
  File "c:\Users\vivek\OneDrive\Desktop\SOPPOC\version.py", line 57, in <module>
    openAIEmbedd = FAISS.from_documents(texts, embeddings)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vivek\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\langchain_core\vectorstores.py", line 510, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vivek\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\langchain_community\vectorstores\faiss.py", line 914, in from_texts
    embeddings = embedding.embed_documents(texts)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vivek\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\langchain_community\embeddings\openai.py", line 667, in embed_documents
    return self._get_len_safe_embeddings(texts, engine=engine)
 
        ^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
why i am getting this error

**Comment by SighingSnow** [comment]
I think this issuse maybe help to solve this problem. It's not a langchain  #problem.https://github.com/openai/tiktoken/issues/136
