### ISSUE TITLE
Chromadb connection error

### ISSUE THREAD

**Issue by ahron1** [langchain-ai/langchain#15348]
### System Info

Langchain 0.0.353
Python 3.10.12
System Ubuntu 22.04

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I am trying to modify and run the example on [this page](https://python.langchain.com/docs/use_cases/question_answering/). I am modifying it slightly to use a different embedding tool from the Ollama model. 

The last line, which should create the vector store, in the below snippet crashes.

```
import bs4
from langchain import hub
from langchain.chat_models import ChatOpenAI
from langchain.document_loaders import WebBaseLoader
from langchain.embeddings import OllamaEmbeddings
from langchain.schema import StrOutputParser
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.vectorstores import Chroma
from langchain_core.runnables import RunnablePassthrough

embeddings_open = OllamaEmbeddings(model="mistral")

loader = WebBaseLoader(
    web_paths=("https://lilianweng.github.io/posts/2023-06-23-agent/",),
    bs_kwargs=dict(
        parse_only=bs4.SoupStrainer(
            class_=("post-content", "post-title", "post-header")
        )
    ),
)
docs = loader.load()

text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
splits = text_splitter.split_documents(docs)

vectorstore = Chroma.from_documents(documents=splits, embedding=embeddings_open)

```

### Expected behavior

I would expect the code to work, unless I'm missing something important. Instead, I get this error. 

Any clues are most appreciated. I'm sure it is something simple I overlooked.

```
>>> vectorstore = Chroma.from_documents(documents=splits, embedding = embeddings_open)

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
      conn = connection.create_connection(
        File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection
            raise err
              File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
                  sock.connect(sa)
                  ConnectionRefusedError: [Errno 111] Connection refused
                  
                  
                  
                  
                  
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 486, in send
      resp = conn.urlopen(
        File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 756, in urlopen
            retries = retries.increment(
              File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
                  raise MaxRetryError(_pool, url, error or ResponseError(cause))
                  urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8d11256bc0>: Failed to establish a new connection: [Errno 111] Connection refused'))



```

**Comment by itsritiksingh** [comment]
You are receiving a refused connection on port 11434, which is the port used by Ollama. You can start Ollama by running:

```
sudo systemctl start ollama
```

You can confirm whether Ollama is running or not by making the following curl request:

```
curl -X POST http://localhost:11434/api/generate -d '{
    "model": "mistral",
    "prompt": "Why is the sky blue?"
}'
```

**Comment by ahron1** [comment]
Yes, it was indeed a simple thing that I missed. Thanks!
