### ISSUE TITLE
RAG crash: TypeError: Type is not JSON serializable: numpy.ndarray

### ISSUE THREAD

**Issue by allquixotic** [langchain-ai/langchain#15371]
### System Info

- Python 3.12.1
- MacOS 14.2.1
- langchain-cli 0.0.20 from pip OR langchain-* from git master branch (commit-ish [26f84b7](https://github.com/langchain-ai/langchain/commit/26f84b74d0f7dc4d2211a1a62d47eec36cb1d726)) -- can reproduce with latest code: langchain 0.0.353, langchain-cli 0.0.20, langchain-community 0.0.7, langchain-core 0.1.4
- pandas 2.1.4
- lancedb 0.4.3
- numpy 1.26.2

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I started with the rag-chroma-private quickstart, then modified it to my needs. I got rid of Chroma due to errors and now use a persistent LanceDB file.

When I try to enter a prompt on the playground, I get a crash (see the bottom of this message).

server.py:
```
from fastapi import FastAPI
from fastapi.responses import RedirectResponse
from langserve import add_routes
from app.chain import chain as rag_private_chain

app = FastAPI()


@app.get("/")
async def redirect_root_to_docs():
    return RedirectResponse("/docs")


add_routes(app, rag_private_chain, path="/rag-lancedb-private")

if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8000)

```

chain.py:
```
# Load
from typing import List
from langchain.chat_models import ChatOllama
from langchain.document_loaders import UnstructuredMarkdownLoader
from langchain.embeddings import OllamaEmbeddings
from langchain.prompts import ChatPromptTemplate
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_core.output_parsers import StrOutputParser
from langchain_core.pydantic_v1 import BaseModel
from langchain_core.runnables import RunnableParallel, RunnablePassthrough
from langchain_core.documents.base import Document
import os, sys

#DB
import lancedb
from langchain.vectorstores.lancedb import LanceDB

#Chroma
#from langchain.vectorstores.chroma import Chroma
#from langchain.vectorstores.utils import filter_complex_metadata

files_directory = "/Users/sean/Downloads/posts"

all_splits = None
my_emb = OllamaEmbeddings(model="llama2:70b-chat")
table = None
db = lancedb.connect("./lance.db")
vectorstore = None

#Generating the vectors only has to be done when the data changes
def do_loader():
    #List each file in files_directory and loop through them creating an UnstructuredMarkdownLoader for each file
    all_splits = []
    for filename in os.listdir(files_directory):
        full_path = os.path.join(files_directory, filename)
        loader = UnstructuredMarkdownLoader(full_path, mode="elements", strategy="hi_res")
        data: List[Document] = loader.load()
        all_splits.extend(data)
        continue

    print(f"Got {len(all_splits)} documents")

    table = db.create_table(
        "rag",
        data=[
            {
                "vector": my_emb.embed_query("Hello World"),
                "text": "Hello World",
                "id": "1",
            }
        ],
        mode="overwrite",
    )

    #New 
    vectorstore = LanceDB.from_documents(all_splits, my_emb, connection=table)
    print("Added docs to vector store")

#Not calling do_loader() because I have already populated LanceDB with the vectors.
table = db.open_table("rag")
vectorstore = LanceDB(connection=table, embedding=my_emb)
retriever = vectorstore.as_retriever()

print("Loaded DB")
 
# Prompt
# Optionally, pull from the Hub
# from langchain import hub
# prompt = hub.pull("rlm/rag-prompt")
# Or, define your own:
template = """Answer the question based only on the following context:
{context}

Question: {question}
"""
prompt = ChatPromptTemplate.from_template(template)

# LLM
ollama_llm = "llama2:70b-chat"
model = ChatOllama(model=ollama_llm)

print("Created Ollama model")

# RAG chain
chain = (
    RunnableParallel({"context": retriever, "question": RunnablePassthrough()})
    | prompt
    | model
    | StrOutputParser()
)

# Add typing for input
class Question(BaseModel):
    __root__: str

chain = chain.with_types(input_type=Question)

print("Done with chain.py")
```

Error:

```

INFO:     Application startup complete.
INFO:     127.0.0.1:64594 - "GET /rag-chroma-private/playground/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:64594 - "GET /rag-chroma-private/playground/assets/index-52e8ab2f.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:64595 - "GET /rag-chroma-private/playground/assets/index-6a0f524c.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:64595 - "GET /rag-chroma-private/playground/favicon.ico HTTP/1.1" 200 OK
INFO:     127.0.0.1:64594 - "POST /rag-chroma-private/stream_log HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/sean/dev/cc/cc/ccvenv/lib/python3.12/site-packages/sse_starlette/sse.py", line 269, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/Users/sean/dev/cc/cc/ccvenv/lib/python3.12/site-packages/sse_starlette/sse.py", line 258, in wrap
    await func()
  File "/Users/sean/dev/cc/cc/ccvenv/lib/python3.12/site-packages/sse_starlette/sse.py", line 215, in listen_for_disconnect
    message = await receive()
              ^^^^^^^^^^^^^^^
  File "/Users/sean/dev/cc/cc/ccvenv/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 538, in receive
    await self.message_event.wait()
  File "/opt/homebrew/Cellar/python@3.12/3.12.1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/locks.py", line 212, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 15bc21f40

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/Users/sean/dev/cc/cc/ccvenv/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/Users/sean/dev/cc/cc/ccvenv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
  |     return await self.app(scope, receive, send)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/Users/sean/dev/cc/cc/ccvenv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "/Users/sean/dev/cc/cc/ccvenv/lib/python3.12/site-packages/starlette/applications.py", line 116, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/Users/sean/dev/cc/cc/ccvenv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
  |     raise exc
  |   File "/Users/sean/dev/cc/cc/ccvenv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
  |     await self.app(scope, receive, _send)
  |   File "/Users/sean/dev/cc/cc/ccvenv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "/Users/sean/dev/cc/cc/ccvenv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/Users/sean/dev/cc/cc/ccvenv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/Users/sean/dev/cc/cc/ccvenv/lib/python3.12/site-packages/starlette/routing.py", line 754, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/Users/sean/dev/cc/cc/ccvenv/lib/python3.12/site-packages/starlette/routing.py", line 774, in app
  |     await route.handle(scope, receive, send)
  |   File "/Users/sean/dev/cc/cc/ccvenv/lib/python3.12/site-packages/starlette/routing.py", line 296, in handle
  |     await self.app(scope, receive, send)
  |   File "/Users/sean/dev/cc/cc/ccvenv/lib/python3.12/site-packages/starlette/routing.py", line 75, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "/Users/sean/dev/cc/cc/ccvenv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/Users/sean/dev/cc/cc/ccvenv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/Users/sean/dev/cc/cc/ccvenv/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
  |     await response(scope, receive, send)
  |   File "/Users/sean/dev/cc/cc/ccvenv/lib/python3.12/site-packages/sse_starlette/sse.py", line 255, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/Users/sean/dev/cc/cc/ccvenv/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/Users/sean/dev/cc/cc/ccvenv/lib/python3.12/site-packages/langserve/serialization.py", line 90, in default
    |     return super().default(obj)
    |            ^^^^^^^
    | RuntimeError: super(): __class__ cell not found
    |
    | The above exception was the direct cause of the following exception:
    |
    | Traceback (most recent call last):
    |   File "/Users/sean/dev/cc/cc/ccvenv/lib/python3.12/site-packages/sse_starlette/sse.py", line 258, in wrap
    |     await func()
    |   File "/Users/sean/dev/cc/cc/ccvenv/lib/python3.12/site-packages/sse_starlette/sse.py", line 245, in stream_response
    |     async for data in self.body_iterator:
    |   File "/Users/sean/dev/cc/cc/ccvenv/lib/python3.12/site-packages/langserve/api_handler.py", line 1049, in _stream_log
    |     "data": self._serializer.dumps(data).decode("utf-8"),
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/sean/dev/cc/cc/ccvenv/lib/python3.12/site-packages/langserve/serialization.py", line 168, in dumps
    |     return orjson.dumps(obj, default=default)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | TypeError: Type is not JSON serializable: numpy.ndarray
    +------------------------------------
```

### Expected behavior

It's not clear to me which part of the stack is failing, but the expected behavior is that the LLM should generate some output rather than crashing.

**Comment by keenborder786** [comment]
@allquixotic I am seeing the error and will get back to you.

**Comment by keenborder786** [comment]
@allquixotic `do_loader` runs one time off correct?

**Comment by keenborder786** [comment]
Like when you start the server or need to add new data.

**Comment by allquixotic** [comment]
@keenborder786 Yes, I normally run `do_loader()` when I'm ingesting my data, then I turn it off so that the code path that uses the existing database works.

I'm still developing my solution; eventually I'll have a runtime parameter that determines whether to run the `do_loader()` path or the "existing vectorstore" path that excludes it. That's why the code looks so hacky right now :)

FWIW, I got it to work with DeepLake, so the problem appears to be with LanceDB. Basically, if you swap out LanceDB for a local DeepLake, this example works fine.

**Comment by keenborder786** [comment]
@allquixotic the following code worked for me I used Ollama and LanceDB. Everything seems to be working. I feel like you are loading something wrong with your document loader. Their is nothing wrong with LanceDB. If you can send me a sample of Markdown file that you are loading then I might be able to help you better:

```python

from langchain.chat_models import ChatOllama
from langchain.embeddings import OllamaEmbeddings
from langchain.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnableParallel, RunnablePassthrough
from langchain.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough
from langchain.chat_models import ChatOllama
from langchain.vectorstores.lancedb import LanceDB
import lancedb
my_emb = OllamaEmbeddings(model="llama2")
db = lancedb.connect("data/lance.db",)
table = db.create_table("rag",data=[
            {
                "vector": my_emb.embed_query("Hello World"),
                "text": "Hello World",
                "id": "1",
            }
        ],
        mode="overwrite",)
vectorstore = LanceDB.from_texts(texts = ["harrison worked at kensho"],embedding=my_emb,connection=table)
retriever=vectorstore.as_retriever()
template = """Answer the question based only on the following context:
{context}

Question: {question}
"""
prompt = ChatPromptTemplate.from_template(template)
# LLM
ollama_llm = "llama2"
model = ChatOllama(model=ollama_llm)
print("Created Ollama model")
def func(_dict):
    return list(map(lambda x:x.page_content,_dict["context"]))
# RAG chain
chain = (
    RunnableParallel({"context": retriever, "question": RunnablePassthrough()})
    | prompt
    | model
    | StrOutputParser()
)


from fastapi import FastAPI
from fastapi.responses import RedirectResponse
from langserve import add_routes
app = FastAPI()
@app.get("/")
async def redirect_root_to_docs():
    return RedirectResponse("/docs")
add_routes(app, chain, path="/rag-lancedb-private")
if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
```


You can also use the following changes to chain, which will only give the page content of your file, perhaps that might fix your issue:


```python
def func(_dict):
    return list(map(lambda x:x.page_content,_dict["context"]))
# RAG chain
chain = (
    RunnableParallel({"context": retriever, "question": RunnablePassthrough()})
    | RunnableParallel({"context":RunnableLambda(func),"question":RunnableLambda(lambda x:x["question"])})
    | RunnableParallel({"context":RunnableLambda(lambda x:"\n\n".join(x["context"])),"question":RunnableLambda(lambda x:x["question"])})
    | prompt
    | model
    | StrOutputParser()
)
```

**Comment by MarkEdmondson1234** [comment]
I get a similar crash, which seems related to the output of the LanceDB retriever being a numpy object rather than the page_content:

```python
from langchain.prompts import ChatPromptTemplate
from langchain_community.vectorstores import LanceDB
from langchain_core.runnables import RunnableParallel, RunnablePassthrough, RunnableLambda
from langchain_core.pydantic_v1 import BaseModel
from langchain_core.output_parsers import StrOutputParser
from sunholo.components import get_llm_chat, get_embeddings
from sunholo.logging import setup_logging
import lancedb
from operator import itemgetter

log = setup_logging()

embeddings = get_embeddings("rag_lance")

db = lancedb.connect("db")
table = db.open_table("my_table")
vectorstore = LanceDB(table, embeddings)

log.info(f"Table versions: {table.list_versions()}")

retriever = vectorstore.as_retriever(search_kwargs={"k": 3})

docs = vectorstore.similarity_search("Know anything about RAG?")
log.info(docs)

template = """Answer the question based only on the following context.:
{context}

If the context does not help if not relevant to the question, answer "I can't help with your question, it doesn't seem related to my memory."

Question: {question}
Your Answer (only if relevant to the question, say "I can't help with your question" otherwise):
"""
prompt = ChatPromptTemplate.from_template(template)

model = get_llm_chat("rag_lance")

_inputs = RunnableParallel({
        "context": itemgetter("question") | retriever,
        "question": itemgetter("question")
    })

chain = _inputs | prompt | model | StrOutputParser()

class Question(BaseModel):
    question: str

chain = chain.with_types(input_type=Question)
```

Gives:

```
 | RuntimeError: super(): __class__ cell not found
    | 
    | The above exception was the direct cause of the following exception:
    | 
    | Traceback (most recent call last):
    |   File "/Users/mark/dev/sunholo/multivac/.venv/lib/python3.12/site-packages/sse_starlette/sse.py", line 258, in wrap
    |     await func()
    |   File "/Users/mark/dev/sunholo/multivac/.venv/lib/python3.12/site-packages/sse_starlette/sse.py", line 245, in stream_response
    |     async for data in self.body_iterator:
    |   File "/Users/mark/dev/sunholo/multivac/.venv/lib/python3.12/site-packages/langserve/api_handler.py", line 1085, in _stream_log
    |     "data": self._serializer.dumps(data).decode("utf-8"),
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/mark/dev/sunholo/multivac/.venv/lib/python3.12/site-packages/langserve/serialization.py", line 168, in dumps
    |     return orjson.dumps(obj, default=default)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | TypeError: Type is not JSON serializable: numpy.ndarray
```

The above chain works with Chromadb:

```python
...

# Load existing embeddings
vectorstore = Chroma(
    persist_directory="db",
    collection_name="rag_simple",
    embedding_function=embeddings,
)

log.info(f"### There are {vectorstore._collection.count()} in the collection")

retriever = vectorstore.as_retriever(search_kwargs={"k": 3})

docs = vectorstore.similarity_search("Know anything about RAG?")
log.info(docs)

template = """Answer the question based only on the following context.:
{context}

If the context does not help if not relevant to the question, answer "I can't help with your question, it doesn't seem related to my memory."

Question: {question}
Your Answer (only if relevant to the question, say "I can't help with your question" otherwise):
"""
prompt = ChatPromptTemplate.from_template(template)

model = get_llm_chat("rag_simple")

_inputs = RunnableParallel({
        "context": itemgetter("question") | retriever,
        "question": itemgetter("question")
    })
class Question(BaseModel):
    question: str

chain = _inputs | prompt | model | StrOutputParser()

chain = chain.with_types(input_type=Question)
```

The `"context": itemgetter("question") | retriever` I found after the documented way of using it to get context did not work:

```python

_inputs = RunnableParallel({
        "context": retriever,
        "question": itemgetter("question")
    })

chain = _inputs | prompt | model | StrOutputParser()

class Question(BaseModel):
    question: str

chain = chain.with_types(input_type=Question)
```

I suspect that is a Langserve issue:

```
|     token = encoding.encode(
    |             ^^^^^^^^^^^^^^^^
    |   File "/Users/mark/dev/sunholo/multivac/.venv/lib/python3.12/site-packages/tiktoken/core.py", line 116, in encode
    |     if match := _special_token_regex(disallowed_special).search(text):
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | TypeError: expected string or buffer
    +------------------------------------
 ```

**Comment by MarkEdmondson1234** [comment]
I found a fix by modifying the `similarity_search` method to remove the "vector" metadata key.  The vector is then dropped so the numpy conversion isn't needed.

```python
from __future__ import annotations

import uuid
from typing import Any, Iterable, List, Optional

from langchain_core.documents import Document
from langchain_core.embeddings import Embeddings
from langchain_core.vectorstores import VectorStore


class LanceDB(VectorStore):
    """`LanceDB` vector store.

    To use, you should have ``lancedb`` python package installed.

    Example:
        .. code-block:: python

            db = lancedb.connect('./lancedb')
            table = db.open_table('my_table')
            vectorstore = LanceDB(table, embedding_function)
            vectorstore.add_texts(['text1', 'text2'])
            result = vectorstore.similarity_search('text1')
    """

    def __init__(
        self,
        connection: Any,
        embedding: Embeddings,
        vector_key: Optional[str] = "vector",
        id_key: Optional[str] = "id",
        text_key: Optional[str] = "text",
    ):
        """Initialize with Lance DB connection"""
        try:
            import lancedb
        except ImportError:
            raise ImportError(
                "Could not import lancedb python package. "
                "Please install it with `pip install lancedb`."
            )
        if not isinstance(connection, lancedb.db.LanceTable):
            raise ValueError(
                "connection should be an instance of lancedb.db.LanceTable, ",
                f"got {type(connection)}",
            )
        self._connection = connection
        self._embedding = embedding
        self._vector_key = vector_key
        self._id_key = id_key
        self._text_key = text_key

    @property
    def embeddings(self) -> Embeddings:
        return self._embedding

    def add_texts(
        self,
        texts: Iterable[str],
        metadatas: Optional[List[dict]] = None,
        ids: Optional[List[str]] = None,
        **kwargs: Any,
    ) -> List[str]:
        """Turn texts into embedding and add it to the database

        Args:
            texts: Iterable of strings to add to the vectorstore.
            metadatas: Optional list of metadatas associated with the texts.
            ids: Optional list of ids to associate with the texts.

        Returns:
            List of ids of the added texts.
        """
        # Embed texts and create documents
        docs = []
        ids = ids or [str(uuid.uuid4()) for _ in texts]
        embeddings = self._embedding.embed_documents(list(texts))
        for idx, text in enumerate(texts):
            embedding = embeddings[idx]
            metadata = metadatas[idx] if metadatas else {}
            docs.append(
                {
                    self._vector_key: embedding,
                    self._id_key: ids[idx],
                    self._text_key: text,
                    **metadata,
                }
            )

        self._connection.add(docs)
        return ids

    def similarity_search(self, query: str, k: int = 4, **kwargs: Any) -> List[Document]:
        """Return documents most similar to the query

        Args:
            query: String to query the vectorstore with.
            k: Number of documents to return.

        Returns:
            List of documents most similar to the query.
        """
        embedding = self._embedding.embed_query(query)
        docs = self._connection.search(embedding).limit(k).to_df()
        return [
            Document(
                page_content=row[self._text_key],
                # Filter out the 'vector' key from the metadata if it exists
                metadata={key: value for key, value in row[docs.columns != self._text_key].items() if key != 'vector'},
            )
            for _, row in docs.iterrows()
        ]
...

```

**Comment by MarkEdmondson1234** [comment]
A better fix is updating the `docs = self._connection.search(embedding).limit(k).to_df()` to use `.select(["vector"]).` and only select the columns not including "vector"
