### ISSUE TITLE
langchain is not `pyinstaller` friendly due to dependency on external files, e.g. `llm_summarization_checker`

### ISSUE THREAD

**Issue by tigerinus** [langchain-ai/langchain#15386]
### System Info

```
langchain==0.0.335
```

```
python 3.11
```

### Who can help?

@hwchase17 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Create simple `test.py`:

```python
from langchain.chains.llm_summarization_checker.base import LLMSummarizationCheckerChain
from langchain.llms.fake import FakeListLLM

llm = FakeListLLM(responses=[])

chain = LLMSummarizationCheckerChain.from_llm(llm)
```

2. Install `pyinstaller` via `pip install -U pyinstaller`

3. Run

```
pyinstaller test.py`
```

4. Wait until it's done.

5. Run

```
$ ./dist/test/test 
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from langchain.chains.llm_summarization_checker.base import LLMSummarizationCheckerChain
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "langchain/chains/__init__.py", line 51, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "langchain/chains/llm_summarization_checker/base.py", line 20, in <module>
  File "langchain_core/prompts/prompt.py", line 202, in from_file
FileNotFoundError: [Errno 2] No such file or directory: '/home/tiger/junk/tt/dist/test/_internal/langchain/chains/llm_summarization_checker/prompts/create_facts.txt'
[789522] Failed to execute script 'test' due to unhandled exception!
```

### Expected behavior

```
CREATE_ASSERTIONS_PROMPT = PromptTemplate.from_file(PROMPTS_DIR / "create_facts.txt")
CHECK_ASSERTIONS_PROMPT = PromptTemplate.from_file(PROMPTS_DIR / "check_facts.txt")
REVISED_SUMMARY_PROMPT = PromptTemplate.from_file(PROMPTS_DIR / "revise_summary.txt")
ARE_ALL_TRUE_PROMPT = PromptTemplate.from_file(PROMPTS_DIR / "are_all_true_prompt.txt")
```

These lines from https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/chains/llm_summarization_checker/base.py should be changed to something like lazy loading, or just hard code the `.txt` files.

PS - I'm using `llama2` so these prompts do not work anyway.

**Comment by tigerinus** [comment]
nevermind - solution is the `--collect-all` argument from `pyinstaller`.
