### ISSUE TITLE
similarity_search get 2 validation errors for DocArrayDoc

### ISSUE THREAD

**Issue by dove-young** [langchain-ai/langchain#15394]
### System Info

```
pip show langchain_community
Name: langchain-community
Version: 0.0.3
```

```
python --version
Python 3.10.12
```

```
pip show langchain_core
Name: langchain-core
Version: 0.1.1
```

```
pip show pydantic
Name: pydantic
Version: 2.5.1
```

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
/root/jupyter/pydantic/pydantic/_migration.py:283: UserWarning: `pydantic.error_wrappers:ValidationError` has been moved to `pydantic:ValidationError`.
  warnings.warn(f'`{import_path}` has been moved to `{new_location}`.')
Traceback (most recent call last):
  File "/root/jupyter/GitHub-Issues/david/langC-rag-lcel.py", line 86, in <module>
    chain.invoke("where did harrison work?")
  File "/root/jupyter/virtualenv/slack-dev-3.10/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1514, in invoke
    input = step.invoke(
  File "/root/jupyter/virtualenv/slack-dev-3.10/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2040, in invoke
    output = {key: future.result() for key, future in zip(steps, futures)}
  File "/root/jupyter/virtualenv/slack-dev-3.10/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2040, in <dictcomp>
    output = {key: future.result() for key, future in zip(steps, futures)}
  File "/opt/python-3.10.12/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/opt/python-3.10.12/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/opt/python-3.10.12/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/jupyter/virtualenv/slack-dev-3.10/lib/python3.10/site-packages/langchain_core/retrievers.py", line 112, in invoke
    return self.get_relevant_documents(
  File "/root/jupyter/virtualenv/slack-dev-3.10/lib/python3.10/site-packages/langchain_core/retrievers.py", line 211, in get_relevant_documents
    raise e
  File "/root/jupyter/virtualenv/slack-dev-3.10/lib/python3.10/site-packages/langchain_core/retrievers.py", line 204, in get_relevant_documents
    result = self._get_relevant_documents(
  File "/root/jupyter/virtualenv/slack-dev-3.10/lib/python3.10/site-packages/langchain_core/vectorstores.py", line 656, in _get_relevant_documents
    docs = self.vectorstore.similarity_search(query, **self.search_kwargs)
  File "/root/jupyter/virtualenv/slack-dev-3.10/lib/python3.10/site-packages/langchain_community/vectorstores/docarray/base.py", line 127, in similarity_search
    results = self.similarity_search_with_score(query, k=k, **kwargs)
  File "/root/jupyter/virtualenv/slack-dev-3.10/lib/python3.10/site-packages/langchain_community/vectorstores/docarray/base.py", line 106, in similarity_search_with_score
    query_doc = self.doc_cls(embedding=query_embedding)  # type: ignore
  File "/root/jupyter/pydantic/pydantic/main.py", line 166, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for DocArrayDoc
text
  Field required [type=missing, input_value={'embedding': [0.00177018... -0.018160881474614143]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing
metadata
  Field required [type=missing, input_value={'embedding': [0.00177018... -0.018160881474614143]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing
```

### Expected behavior

it should run successfully

**Comment by rommik** [comment]
The issue is with pydantic version, it's `2.0.0+` and not compatible with docarray.
Instead it should be pydantic==1.10.9

source: https://stackoverflow.com/questions/76880224/error-using-using-docarrayinmemorysearch-in-langchain-could-not-import-docarray
