### ISSUE TITLE
KeyError: 'usage'

### ISSUE THREAD

**Issue by pydaxing** [langchain-ai/langchain#15448]
### System Info

langchain                 0.0.353
langchain-community       0.0.7
langchain-core            0.1.4
langchain-experimental    0.0.47
Python 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] on linuxd
openai                    0.28.0

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```python
import os  
from langchain.llms import AzureOpenAI
from langchain.agents import initialize_agent, AgentType, AgentExecutor  
from langchain.chat_models import ChatOpenAI  
from langchain.prompts import PromptTemplate, ChatPromptTemplate, MessagesPlaceholder  
from langchain.tools import tool  
import openai

os.environ["OPENAI_API_TYPE"] = "azure"
os.environ["OPENAI_API_VERSION"] = "2023-06-01-preview"
os.environ["OPENAI_API_BASE"] = "xxx"
os.environ["OPENAI_API_KEY"] = "xxx"

 
prompt_template = ChatPromptTemplate.from_messages([  
    ("system", "You are a powerful assistant. But you do not know how to calculate the length of a word"),  
    ("user", "{input}"), 
])  


llm = AzureOpenAI(
    model_name="gpt-4",
    engine="gpt-4"
)


@tool  
def get_word_length(word):  
    """get the length of a word"""  
    return len(word)  


tools = [get_word_length]  

agent = initialize_agent(  
    tools,  
    llm,  
    agent=AgentType.OPENAI_FUNCTIONS,  
    verbose=True  
)  

agent.run("how many letters are there in Oslo and Beijing?")
```

```
> Entering new AgentExecutor chain...
Traceback (most recent call last):
  File "/mnt/workspace/workgroup/lengmou/Tars-Code-Agent/pages/5.py", line 115, in <module>
    agent.run("how many letters are there in Oslo and Beijing?")
  File "/mnt/workspace/workgroup/shared/miniconda3/envs/code-agent/lib/python3.10/site-packages/langchain/chains/base.py", line 507, in run
    return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[
  File "/mnt/workspace/workgroup/shared/miniconda3/envs/code-agent/lib/python3.10/site-packages/langchain/chains/base.py", line 312, in __call__
    raise e
  File "/mnt/workspace/workgroup/shared/miniconda3/envs/code-agent/lib/python3.10/site-packages/langchain/chains/base.py", line 306, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/mnt/workspace/workgroup/shared/miniconda3/envs/code-agent/lib/python3.10/site-packages/langchain/agents/agent.py", line 1312, in _call
    next_step_output = self._take_next_step(
  File "/mnt/workspace/workgroup/shared/miniconda3/envs/code-agent/lib/python3.10/site-packages/langchain/agents/agent.py", line 1038, in _take_next_step
    [
  File "/mnt/workspace/workgroup/shared/miniconda3/envs/code-agent/lib/python3.10/site-packages/langchain/agents/agent.py", line 1038, in <listcomp>
    [
  File "/mnt/workspace/workgroup/shared/miniconda3/envs/code-agent/lib/python3.10/site-packages/langchain/agents/agent.py", line 1066, in _iter_next_step
    output = self.agent.plan(
  File "/mnt/workspace/workgroup/shared/miniconda3/envs/code-agent/lib/python3.10/site-packages/langchain/agents/openai_functions_agent/base.py", line 96, in plan
    predicted_message = self.llm.predict_messages(
  File "/mnt/workspace/workgroup/shared/miniconda3/envs/code-agent/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 946, in predict_messages
    content = self(text, stop=_stop, **kwargs)
  File "/mnt/workspace/workgroup/shared/miniconda3/envs/code-agent/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 892, in __call__
    self.generate(
  File "/mnt/workspace/workgroup/shared/miniconda3/envs/code-agent/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 666, in generate
    output = self._generate_helper(
  File "/mnt/workspace/workgroup/shared/miniconda3/envs/code-agent/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 553, in _generate_helper
    raise e
  File "/mnt/workspace/workgroup/shared/miniconda3/envs/code-agent/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 540, in _generate_helper
    self._generate(
  File "/mnt/workspace/workgroup/shared/miniconda3/envs/code-agent/lib/python3.10/site-packages/langchain_community/llms/openai.py", line 1152, in _generate
    "token_usage": full_response["usage"],
KeyError: 'usage'
```

### Expected behavior

Please look at this issue, thanks!

**Comment by pydaxing** [comment]
> _🤖_
> 
> Hello @pydaxing! 🚀 I'm [Dosu](https://dosu.dev), an AI bot here to help you troubleshoot bugs, answer your queries, and guide you on your journey to becoming a contributor. While the human maintainers are busy, I'm here to assist you. Let's solve this puzzle together! 🧩
> 
> The error you're encountering is due to the fact that the 'usage' key is not present in the 'full_response' dictionary. This is happening in the `_generate` method of the `AzureOpenAI` class in the LangChain codebase. Here is the relevant part of the code:
> 
> ```python
> "token_usage": full_response["usage"],
> ```
> 
> The 'usage' key is expected to be present in the 'full_response' dictionary, but it seems like it's not there in your case. This could be due to a variety of reasons, such as a change in the response structure from the Azure OpenAI API, or a problem with the request that was sent.
> 
> Unfortunately, without more information about the structure of the 'full_response' dictionary or the exact request that was sent, it's difficult to provide a more specific solution.
> 
> As a workaround, you could add a check before this line of code to see if the 'usage' key is in the 'full_response' dictionary, and handle the case where it's not. Here's an example of how you could do this:
> 
> ```python
> "token_usage": full_response.get("usage", default_value),
> ```
> 
> In this code, `default_value` is the value you want to use when the 'usage' key is not present in the 'full_response' dictionary. You would need to replace `default_value` with an appropriate value based on your use case.
> 
> Please let me know if this helps, or if you need further assistance.
> 
> ## Sources
> * [libs/langchain/langchain/agents/openai_tools/base.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/agents/openai_tools/base.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

I have print the full_response, there is an error.
```python
print(full_response)
        llm_output = {
            "token_usage": full_response["usage"],
            "model_name": self.model_name,
        }
```

```
{
  "error": {
    "message": "Unrecognized request argument supplied: functions",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
```
