### ISSUE TITLE
HuggingFaceTextGenInference Streaming does not output 

### ISSUE THREAD

**Issue by PeterTucker** [langchain-ai/langchain#15516]
### System Info

langchain==0.0.354
text_generation==0.6.1

python:3.10-slim

### Who can help?

@agola11 @hwaking 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [X] Callbacks/Tracing
- [X] Async

### Reproduction

Model: TheBloke/Llama-2-7B-Chat-GPTQ, but I've also tried TheBloke/Mistral-7B-OpenOrca-GPTQ
FastAPI example with HuggingFaceTextGenInference streaming:
```python

from fastapi import FastAPI

import langchain
from langchain.llms import HuggingFaceTextGenInference
from langchain.chains import LLMChain
from langchain.prompts import PromptTemplate
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

import os
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI()
langchain.debug = True

# Enable CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # You can specify the list of allowed origins or use "*" for any origin
    allow_credentials=True,
    allow_methods=["*"],  # You can specify the HTTP methods that are allowed
    allow_headers=["*"],  # You can specify the HTTP headers that are allowed
)

# Configuration for local LLM
ai_url = "http://tgi-ai-server:" + str(os.getenv("AI_PORT", 80)) + "/generate"

# Configure the LLM
llm = HuggingFaceTextGenInference(
    inference_server_url=ai_url,
    max_new_tokens=20,
    streaming=True,
)

template = """
[INST] <<SYS>>
You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe.  Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature. If a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information.
<</SYS>>
{prompt}[/INST]
"""
prompt_template = PromptTemplate(
    template=template, 
    input_variables= ["prompt"]
)

# Initialize the LLM Chain
llm_chain = LLMChain(llm=llm, prompt=prompt_template)

@app.get("/chat")
async def chat():

    prompt = {"prompt":"What is the Nickelodeon channel?"}
    # Generate the response using the LLM Chain and stream the output
    async def generate():
        for text in llm_chain.run(prompt):
            yield text
            

    return StreamingResponse(generate(), media_type="text/plain")

# Run the server (if running this script directly)
# Use the command: uvicorn script_name:app --reload
if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
```

Output:
```
[chain/start] [1:chain:LLMChain] Entering Chain run with input:
{
  "prompt": "What is the Nickelodeon channel?"
}
[llm/start] [1:chain:LLMChain > 2:llm:HuggingFaceTextGenInference] Entering LLM run with input:
{
  "prompts": [
    "[INST] <<SYS>>\nYou are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe.  Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature. If a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information.\n<</SYS>>\nWhat is the Nickelodeon channel?[/INST]"
  ]
}
[llm/end] [1:chain:LLMChain > 2:llm:HuggingFaceTextGenInference] [765ms] Exiting LLM run with output:
{
  "generations": [
    [
      {
        "text": "",
        "generation_info": null,
        "type": "Generation"
      }
    ]
  ],
  "llm_output": null,
  "run": null
}
[chain/end] [1:chain:LLMChain] [765ms] Exiting Chain run with output:
{
  "text": ""
}
```

### Expected behavior

HuggingFaceTextGenInference does not return any streaming data. Works fine when streaming=False in parameters.

**Comment by PeterTucker** [comment]
@dosu-bot 
Also streaming via curl from command line works fine:
```
curl 127.0.0.1:3331/generate_stream \
    -X POST \
    -d '{"inputs":"What is Deep Learning?","parameters":{"max_new_tokens":17}}' \
    -H 'Content-Type: application/json'
```

Output:
```
data:{"token":{"id":13,"text":"\n","logprob":-0.3269043,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":13,"text":"\n","logprob":-2.6054688,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":2772,"text":"De","logprob":-0.017089844,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":1022,"text":"ep","logprob":-0.000064492226,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":6509,"text":" learning","logprob":-0.004310608,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":338,"text":" is","logprob":-0.15283203,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":263,"text":" a","logprob":-0.0038261414,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":11306,"text":" subset","logprob":-0.11029053,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":310,"text":" of","logprob":-0.000018119812,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":4933,"text":" machine","logprob":-0.0003349781,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":6509,"text":" learning","logprob":-0.0001887083,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":393,"text":" that","logprob":-0.0065727234,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":20789,"text":" involves","logprob":-0.004333496,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":278,"text":" the","logprob":-0.0018758774,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":671,"text":" use","logprob":-0.00043320656,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":310,"text":" of","logprob":-0.0000046491623,"special":false},"generated_text":null,"details":null}

data:{"token":{"id":23116,"text":" artificial","logprob":-0.14477539,"special":false},"generated_text":"\n\nDeep learning is a subset of machine learning that involves the use of artificial","details":null}
```

**Comment by PeterTucker** [comment]
@dosu-bot @hwchase17  Wondering if it might be an issue similar to this: 
https://github.com/langchain-ai/langchain/pull/6211/commits

**Comment by PeterTucker** [comment]
@dosu-bot Your code did not work
```python
@app.get("/chat")
async def chat():

    prompt = {"prompt":"What is the Nickelodeon channel?"}
    # Generate the response using the LLM Chain and stream the output
    async def generate():
        async for text in llm_chain.run(prompt):
            yield text
            

    return StreamingResponse(generate(), media_type="text/plain")
```

This is the error I received:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 255, in wrap
    await func()
  File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 244, in stream_response
    async for chunk in self.body_iterator:
  File "/app/fastapi_server.py", line 78, in generate
    async for text in llm_chain.run(prompt):
TypeError: 'async for' requires an object with __aiter__ method, got str
```

**Comment by PeterTucker** [comment]
Just to close this, it was a mistake on my end. URL should have had '_stream' on the end. wompidy womp
```
ai_url = "http://tgi-ai-server:" + str(os.getenv("AI_PORT", 80)) + "/generate_stream"

not

ai_url = "http://tgi-ai-server:" + str(os.getenv("AI_PORT", 80)) + "/generate"
```
