### ISSUE TITLE
AsyncChromiumloader gives attribute error : COBOL

### ISSUE THREAD

**Issue by rogerbarretocode** [langchain-ai/langchain#15524]
### System Info

python 3.9.13

langchain==0.0.316
langchain-community==0.0.1
langchain-core==0.0.13

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

import pprint

from langchain.text_splitter import RecursiveCharacterTextSplitter

from langchain_community.document_loaders import AsyncChromiumLoader
from langchain_community.document_transformers import BeautifulSoupTransformer

from langchain.chains import create_extraction_chain

from langchain_community.chat_models import ChatOpenAI

### Expected behavior

i am getting the following error when i try to import asyncchromiumloader 

Traceback (most recent call last):
  File "C:\Users\roger\OneDrive\Desktop\testlinkedinllm.py", line 5, in <module>
    from langchain_community.document_loaders import AsyncChromiumLoader
  File "C:\Users\roger\anaconda3new\lib\site-packages\langchain_community\document_loaders\__init__.py", line 51, in <module>
    from langchain_community.document_loaders.blackboard import BlackboardLoader
  File "C:\Users\roger\anaconda3new\lib\site-packages\langchain_community\document_loaders\blackboard.py", line 10, in <module>
    from langchain_community.document_loaders.pdf import PyPDFLoader
  File "C:\Users\roger\anaconda3new\lib\site-packages\langchain_community\document_loaders\pdf.py", line 18, in <module>
    from langchain_community.document_loaders.parsers.pdf import (
  File "C:\Users\roger\anaconda3new\lib\site-packages\langchain_community\document_loaders\parsers\__init__.py", line 5, in <module>
    from langchain_community.document_loaders.parsers.language import LanguageParser
  File "C:\Users\roger\anaconda3new\lib\site-packages\langchain_community\document_loaders\parsers\language\__init__.py", line 1, in <module>
    from langchain_community.document_loaders.parsers.language.language_parser import (
  File "C:\Users\roger\anaconda3new\lib\site-packages\langchain_community\document_loaders\parsers\language\language_parser.py", line 24, in <module>
    "cobol": Language.COBOL,
  File "C:\Users\roger\anaconda3new\lib\enum.py", line 429, in __getattr__
    raise AttributeError(name) from None
AttributeError: COBOL

**Comment by sarthakmadhamshettiwar** [comment]
I was facing the same problem when I was trying on a local machine, I switched to Colab and not its working fine. Not sure why this happened.

**Comment by georgioooo** [comment]
And me too i have the same problem

**Comment by pven93** [comment]
I faced a similar issue but not for COBOL but for C language defined on the enum, got resolved after upgrading langchain version.
