### ISSUE TITLE
`UnstructuredFileLoader` shows `TypeError: expected str, bytes or os.PathLike object, not list` when a list of files is passed in

### ISSUE THREAD

**Issue by JoshLoecker** [langchain-ai/langchain#15607]
### System Info

LangChain version: 0.0.354
LangChain Community version: 0.0.8
Platform: Apple M3 Pro chip on MacOS Sonoma (MacOS 14.2.1)
Python version: 3.11.7

### Who can help?

@baskaryan has the most recent commits on this section of the code, but it was for moving items to the `langchain_community` package. I'm not sure who is the original author

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Create a list of file paths
2. Attempt to load using `UnstructuredFileLoader`

```python
from langchain_community.document_loaders import UnstructuredFileLoader

files = [
    "file_1.txt",
    "file_2.txt"
]

loader = UnstructuredFileLoader(file_path=files)
documents = loader.load()  # Error occurs on this line
```

Contents of `file_1.txt` 
```txt
some stuff
```

Contents of `file_2.txt`
```txt
some more stuff
```

Stack trace
```
Traceback (most recent call last):
  File "/Users/joshl/Library/Application Support/JetBrains/PyCharm2023.3/scratches/scratch.py", line 9, in <module>
    documents = loader.load()  # Error occurs on this line
                ^^^^^^^^^^^^^
  File "/Users/joshl/miniforge3/envs/MechanisticLLM/lib/python3.11/site-packages/langchain_community/document_loaders/unstructured.py", line 87, in load
    elements = self._get_elements()
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/joshl/miniforge3/envs/MechanisticLLM/lib/python3.11/site-packages/langchain_community/document_loaders/unstructured.py", line 173, in _get_elements
    return partition(filename=self.file_path, **self.unstructured_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joshl/miniforge3/envs/MechanisticLLM/lib/python3.11/site-packages/unstructured/partition/auto.py", line 278, in partition
    filetype = detect_filetype(
               ^^^^^^^^^^^^^^^^
  File "/Users/joshl/miniforge3/envs/MechanisticLLM/lib/python3.11/site-packages/unstructured/file_utils/filetype.py", line 248, in detect_filetype
    _, extension = os.path.splitext(_filename)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 118, in splitext
TypeError: expected str, bytes or os.PathLike object, not list

Process finished with exit code 1

```

### Expected behavior

A list of strings should be able to be passed to the `UnstructuredFileLoader` class based on the `__init__` arguments

```python
class UnstructuredFileLoader(UnstructuredBaseLoader):
    def __init__(
        self,
        file_path: Union[str, List[str]],
        mode: str = "single",
        **unstructured_kwargs: Any,
    ):
```

**Comment by dewasahu2003** [comment]
if you mind can i take up the issue ?

**Comment by JoshLoecker** [comment]
@dewasahu2003 That's totally ok with me!

**Comment by dewasahu2003** [comment]
Thanks i would take on this issue
