### ISSUE TITLE
Google Trend utility makes assumptions on keys from response

### ISSUE THREAD

**Issue by lpezet** [langchain-ai/langchain#15859]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.

### Example Code

The following code:
```
import os
from langchain_community.utilities.google_trends import GoogleTrendsAPIWrapper

os.environ['SERPAPI_API_KEY'] = ''

tool = GoogleTrendsAPIWrapper()
tool.run("Something that will yield an error like totally")
```
will yield this:
```
Traceback (most recent call last):
  File "/home/ubuntu/Work/luc/langchain-google-trends-issue-1/langchain_google_trends_issue_1/main.py", line 9, in <module>
    tool.run("Something that will yield an error like totally")
  File "/home/ubuntu/Work/luc/langchain-google-trends-issue-1/.venv/lib/python3.10/site-packages/langchain_community/utilities/google_trends.py", line 68, in run
    total_results = client.get_dict()["interest_over_time"]["timeline_data"]
KeyError: 'interest_over_time'
```

### Description

* I'm trying to use the Google Trends tool with some AI agent. 
* Now the (not so smart) agent ran a query with Google Trend that did NOT return what its implementation expected.
* I would expect the implementation to follow a more foolproof logic.

### System Info

# pyproject.toml
python = "^3.10"
langchain = "0.0.354"
pytest = "^7.4.4"
google-search-results = "^2.4.2"

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

**Comment by lpezet** [comment]
@dosu-bot This is definitely one way to go about it, and it will work. I, personally, would like to fix it at the source (root cause).
Specifically:
https://github.com/langchain-ai/langchain/blob/v0.1.0/libs/community/langchain_community/utilities/google_trends.py#L68

Something like this patch:
```
index f0f15000c..c94dee6be 100644
--- a/libs/community/langchain_community/utilities/google_trends.py
+++ b/libs/community/langchain_community/utilities/google_trends.py
@@ -65,7 +65,8 @@ class GoogleTrendsAPIWrapper(BaseModel):
 
         total_results = []
         client = self.serp_search_engine(params)
-        total_results = client.get_dict()["interest_over_time"]["timeline_data"]
+        client_dict = client.get_dict()
+        total_results = client_dict["interest_over_time"]["timeline_data"] if "interest_over_time" in client_dict else None
 
         if not total_results:
             return "No good Trend Result was found"
```

I'd also add a test (unit? integration?). I'm not sure how integration tests are run (using actual keys?) but something of the sort would fail today and succeed after applying the patch:
```
# test_google_trends.py
"""Test for Google Trends API Wrapper."""
from langchain_community.utilities.google_trends import GoogleTrendsAPIWrapper
from unittest.mock import patch
import os

@patch('serpapi.SerpApiClient.get_json')
def test_unexpected_response(mocked_serpapiclient):
  os.environ['SERPAPI_API_KEY'] = '123abcd'
  resp = {
    'search_metadata': {
            'id': '659f32ec36e6a9107b46b5b4', 
            'status': 'Error', 
            'json_endpoint': 'https://serpapi.com/searches/1060a69da6ea9d1a/659f32ec36e6a9107b46b5b4.json', 
            'created_at': '2024-01-11 00:14:36 UTC', 
            'processed_at': '2024-01-11 00:14:36 UTC', 
            'google_trends_url': 'https://trends.google.com/trends/api/explore?tz=420&req=%7B%22comparisonItem%22%3A%5B%7B%22keyword%22%3A%22Lego+building+trends+2022%22%2C%22geo%22%3A%22%22%2C%22time%22%3A%22today+12-m%22%7D%5D%2C%22category%22%3A0%2C%22property%22%3A%22%22%2C%22userConfig%22%3A%22%7BuserType%3A+%5C%22USER_TYPE_LEGIT_USER%5C%22%7D%22%7D', 
            'prettify_html_file': 'https://serpapi.com/searches/1060a69da6ea9d1a/659f32ec36e6a9107b46b5b4.prettify', 
            'total_time_taken': 90.14
    }, 
    'search_parameters': {
        'engine': 'google_trends', 
        'q': 'Lego building trends 2022', 
        'date': 'today 12-m', 
        'tz': '420', 
        'data_type': 'TIMESERIES'
    }, 
    'error': "We couldn't get valid results for this search. Please try again later."
  }
  mocked_serpapiclient.return_value = resp
  tool = GoogleTrendsAPIWrapper()
  tool.run("does not matter")
```

**Comment by lpezet** [comment]
PR submitted: #15864
