### ISSUE TITLE
retriever=retriever has a yellow underline, unable to perform the retrieval of vector database function

### ISSUE THREAD

**Issue by yen111445** [langchain-ai/langchain#16014]
### Issue with current documentation:

import os
from langchain.chat_models import ChatOpenAI
from langchain.chains import ConversationalRetrievalChain
from langchain.memory import ConversationTokenBufferMemory
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores.qdrant import Qdrant
from langchain_core.prompts import ChatPromptTemplate, SystemMessagePromptTemplate, MessagesPlaceholder, \
    HumanMessagePromptTemplate
from qdrant_client import QdrantClient

os.environ['OPENAI_API_KEY'] = "key"
client = QdrantClient(host="192.168.0.312", port=6333)
COLLECTION_NAME = "embed"
embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
vectorstore = Qdrant(
    client=client,
    collection_name=COLLECTION_NAME,
    embeddings=embeddings
)
prompt = ChatPromptTemplate(
    messages=[
        SystemMessagePromptTemplate.from_template(
            "You are robot."
        ),
        MessagesPlaceholder(variable_name="chat_history"),
        HumanMessagePromptTemplate.from_template("{question}"),
    ]
)
llm_name = "gpt-3.5-turbo"
llm = ChatOpenAI(model_name=llm_name, temperature=0)
memory_token_limit = 100
retriever = vectorstore.as_retriever()
memory = ConversationTokenBufferMemory(
    llm=llm,
    prompt=prompt,
    max_token_limit=int(memory_token_limit),
    memory_key="chat_history",
    return_messages=True,
)

qa = ConversationalRetrievalChain.from_llm(
    llm=llm,
    retriever=retriever,
    memory=memory,
    verbose=True,
)

chat_history = []
while True:
    memory.load_memory_variables({"chat_history": chat_history})
    question = input('提問：')
    result = qa.run({'question': question, 'chat_history': chat_history})
    print(result)
    chat_history.append([f'User: {question}', f'Ai: {result}'])
    print(chat_history)
    if question.lower() == 'bye':
        break
![image](https://github.com/langchain-ai/langchain/assets/103471919/815f0775-676c-4a05-aff2-ddba1961c66b)

### Idea or request for content:

During each round of questioning, OpenAI will retrieve and reference similar conversation histories from a vector database before providing a response

**Comment by yen111445** [comment]
> ### Issue with current documentation:
> import os from langchain.chat_models import ChatOpenAI from langchain.chains import ConversationalRetrievalChain from langchain.memory import ConversationTokenBufferMemory from langchain_community.embeddings import HuggingFaceEmbeddings from langchain_community.vectorstores.qdrant import Qdrant from langchain_core.prompts import ChatPromptTemplate, SystemMessagePromptTemplate, MessagesPlaceholder, HumanMessagePromptTemplate from qdrant_client import QdrantClient
> 
> os.environ['OPENAI_API_KEY'] = "key" client = QdrantClient(host="192.168.0.312", port=6333) COLLECTION_NAME = "embed" embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2") vectorstore = Qdrant( client=client, collection_name=COLLECTION_NAME, embeddings=embeddings ) prompt = ChatPromptTemplate( messages=[ SystemMessagePromptTemplate.from_template( "You are robot." ), MessagesPlaceholder(variable_name="chat_history"), HumanMessagePromptTemplate.from_template("{question}"), ] ) llm_name = "gpt-3.5-turbo" llm = ChatOpenAI(model_name=llm_name, temperature=0) memory_token_limit = 100 retriever = vectorstore.as_retriever() memory = ConversationTokenBufferMemory( llm=llm, prompt=prompt, max_token_limit=int(memory_token_limit), memory_key="chat_history", return_messages=True, )
> 
> qa = ConversationalRetrievalChain.from_llm( llm=llm, retriever=retriever, memory=memory, verbose=True, )
> 
> chat_history = [] while True: memory.load_memory_variables({"chat_history": chat_history}) question = input('提問：') result = qa.run({'question': question, 'chat_history': chat_history}) print(result) chat_history.append([f'User: {question}', f'Ai: {result}']) print(chat_history) if question.lower() == 'bye': break

Traceback (most recent call last):
  File "C:\Users\syz\Downloads\Chat-Bot-using-gpt-3.5-turbo-main\models\qdmemory.py", line 42, in <module>
    qa = ConversationalRetrievalChain.from_llm(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\syz\.conda\envs\1222\Lib\site-packages\langchain\chains\conversational_retrieval\base.py", line 228, in from_llm
    return cls(
           ^^^^
  File "C:\Users\syz\.conda\envs\1222\Lib\site-packages\langchain\load\serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ConversationalRetrievalChain
retriever
  instance of BaseRetriever expected (type=type_error.arbitrary_type; expected_arbitrary_type=BaseRetriever)
