### ISSUE TITLE
MultiQueryRetriever with Ollama: ValueError: Expected each embedding in the embeddings to be a list, got [None]

### ISSUE THREAD

**Issue by Naegionn** [langchain-ai/langchain#16415]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.

### Example Code

I adapted the example for MultiQueryRetrieval to use a local ollama server with llama2 as LLM.
when running it I get an Value error: Expected each embedding in the embeddings to be a list, got [None].

This is my Code:
```python
# Build a sample vectorDB
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.document_loaders import WebBaseLoader
from langchain_community.vectorstores import Chroma
from langchain_community.llms import Ollama
from langchain_community.embeddings import OllamaEmbeddings
from langchain.retrievers.multi_query import MultiQueryRetriever
import logging
model_name = "llama2"

ollama = Ollama(base_url='http://localhost:11434',
model=model_name)

oembed = OllamaEmbeddings(base_url="http://localhost:11434", model=model_name)


# Load blog post
loader = WebBaseLoader("https://lilianweng.github.io/posts/2023-06-23-agent/")
data = loader.load()

# Split
text_splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=0)
splits = text_splitter.split_documents(data)

# VectorDB
vectordb = Chroma.from_documents(documents=splits, embedding=oembed)


question = "What are the approaches to Task Decomposition?"

llm =ollama
retriever_from_llm = MultiQueryRetriever.from_llm(
    retriever=vectordb.as_retriever(), llm=llm
)

# Set logging for the queries

logging.basicConfig()
logging.getLogger("langchain.retrievers.multi_query").setLevel(logging.INFO)

unique_docs = retriever_from_llm.get_relevant_documents(query=question)
print(len(unique_docs))
```
Does anyone have an idea what to do to fix this?

### Description

This is the error I get:
Traceback (most recent call last):
  File "/home/lukas/code/content-assist/test-multi.py", line 41, in <module>
    unique_docs = retriever_from_llm.get_relevant_documents(query=question)
  File "/home/lukas/.local/lib/python3.10/site-packages/langchain_core/retrievers.py", line 223, in get_relevant_documents
    raise e
  File "/home/lukas/.local/lib/python3.10/site-packages/langchain_core/retrievers.py", line 216, in get_relevant_documents
    result = self._get_relevant_documents(
  File "/home/lukas/.local/lib/python3.10/site-packages/langchain/retrievers/multi_query.py", line 175, in _get_relevant_documents
    documents = self.retrieve_documents(queries, run_manager)
  File "/home/lukas/.local/lib/python3.10/site-packages/langchain/retrievers/multi_query.py", line 210, in retrieve_documents
    docs = self.retriever.get_relevant_documents(
  File "/home/lukas/.local/lib/python3.10/site-packages/langchain_core/retrievers.py", line 223, in get_relevant_documents
    raise e
  File "/home/lukas/.local/lib/python3.10/site-packages/langchain_core/retrievers.py", line 216, in get_relevant_documents
    result = self._get_relevant_documents(
  File "/home/lukas/.local/lib/python3.10/site-packages/langchain_core/vectorstores.py", line 654, in _get_relevant_documents
    docs = self.vectorstore.similarity_search(query, **self.search_kwargs)
  File "/home/lukas/.local/lib/python3.10/site-packages/langchain_community/vectorstores/chroma.py", line 348, in similarity_search
    docs_and_scores = self.similarity_search_with_score(
  File "/home/lukas/.local/lib/python3.10/site-packages/langchain_community/vectorstores/chroma.py", line 438, in similarity_search_with_score
    results = self.__query_collection(
  File "/home/lukas/.local/lib/python3.10/site-packages/langchain_core/utils/utils.py", line 35, in wrapper
    return func(*args, **kwargs)
  File "/home/lukas/.local/lib/python3.10/site-packages/langchain_community/vectorstores/chroma.py", line 155, in __query_collection
    return self._collection.query(
  File "/home/lukas/.local/lib/python3.10/site-packages/chromadb/api/models/Collection.py", line 188, in query
    validate_embeddings(maybe_cast_one_to_many(query_embeddings))
  File "/home/lukas/.local/lib/python3.10/site-packages/chromadb/api/types.py", line 311, in validate_embeddings
    raise ValueError(
ValueError: Expected each embedding in the embeddings to be a list, got [None]

### System Info

langchain==0.1.2
langchain-community==0.0.14
langchain-core==0.1.14
langchain-openai==0.0.3

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

**Comment by running-frog** [comment]
在哪儿得到更新？我也遇到了同样的问题。chromadb==0.5.0了
