### ISSUE TITLE
ADD A TRY BLOCK TO `merge_dicts`

### ISSUE THREAD

**Issue by Dobiichi-Origami** [langchain-ai/langchain#16441]
### Feature request

add an additional try block to function `merge_dicts` in `langchain_core.utils._merge` and makes function more robust:

original:
```python
def merge_dicts(left: Dict[str, Any], right: Dict[str, Any]) -> Dict[str, Any]:
    merged = left.copy()
    for k, v in right.items():
        if k not in merged:
            merged[k] = v
        ...
        else:
            raise TypeError(
                f"Additional kwargs key {k} already exists in left dict and value has "
                f"unsupported type {type(merged[k])}."
            )
    return merged
```

new:
```python
def merge_dicts(left: Dict[str, Any], right: Dict[str, Any]) -> Dict[str, Any]:
    merged = left.copy()
    for k, v in right.items():
        if k not in merged:
            merged[k] = v
        ...
        else:
            try:
                merged[k] = str(v)
            except Exception as e:
                raise TypeError(
                    f"Additional kwargs key {k} already exists in left dict and value has "
                    f"unsupported type {type(merged[k])}."
                )
    return merged
```

### Motivation

Some function has been malfunctioned due to the introduction of `merge_dicts` since langchain-core 0.1.13 releasing, we think this function should be more robust for a more generic scenario. 

### Your contribution

as above

**Comment by hinthornw** [comment]
Do you have example code of the malfunctioning functions?

**Comment by Dobiichi-Origami** [comment]
> Do you have example code of the malfunctioning functions?

here it is:
```python
from langchain.chat_models.baidu_qianfan_endpoint import QianfanChatEndpoint

cm = QianfanChatEndpoint(streaming=True)
for chunk in cm.stream("请你尽可能长的描述霍金的一生"):
    print(chunk)
```

**Comment by Dobiichi-Origami** [comment]
> Do you have example code of the malfunctioning functions?

@hinthornw 
Here it is, but specific credentials are required to run it:
```python
from langchain.chat_models.baidu_qianfan_endpoint import QianfanChatEndpoint

cm = QianfanChatEndpoint(streaming=True)
for chunk in cm.stream("请你尽可能长的描述霍金的一生"):
    print(chunk)
```

so here's one of calling stack which this glitch occurred:
```
TypeError("Additional kwargs key created already exists in left dict and value has unsupported type <class 'int'>.")Traceback (most recent call last):


  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/chains/base.py", line 156, in invoke
    self._call(inputs, run_manager=run_manager)


  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/agents/agent.py", line 1376, in _call
    next_step_output = self._take_next_step(


  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/agents/agent.py", line 1102, in _take_next_step
    [


  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/agents/agent.py", line 1102, in <listcomp>
    [


  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/agents/agent.py", line 1130, in _iter_next_step
    output = self.agent.plan(


  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/agents/agent.py", line 392, in plan
    for chunk in self.runnable.stream(inputs, config={"callbacks": callbacks}):


  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2405, in stream
    yield from self.transform(iter([input]), config, **kwargs)


  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2392, in transform
    yield from self._transform_stream_with_config(


  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1486, in _transform_stream_with_config
    chunk: Output = context.run(next, iterator)  # type: ignore


  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2356, in _transform
    for output in final_pipeline:


  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1024, in transform
    for chunk in input:


  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 3972, in transform
    yield from self.bound.transform(


  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1034, in transform
    yield from self.stream(final, config, **kwargs)


  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 249, in stream
    raise e


  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 240, in stream
    generation += chunk


  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain_core/outputs/chat_generation.py", line 57, in __add__
    generation_info = merge_dicts(


  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain_core/utils/_merge.py", line 40, in merge_dicts
    raise TypeError(


TypeError: Additional kwargs key created already exists in left dict and value has unsupported type <class 'int'>.
```

**Comment by baskaryan** [comment]
looks like you're trying to merge two dicts with ints for the same key, and it's not clear how to do that (and just turning them to strings would avoid the error but the output wouldn't make sense). probably want to update the output of the model stream, so that instead of ints your return a list or something else merge-able
