### ISSUE TITLE
Devcontainer hangs on Poetry dependency resolution

### ISSUE THREAD

**Issue by cvansteenburg** [langchain-ai/langchain#16552]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

To reproduce, simply open a dev container [here](https://github.com/langchain-ai/langchain/tree/master/.devcontainer#vs-code-dev-containers).

### Two problems:
1. Dependency azure-ai-vision [has been yanked ](https://pypi.org/project/azure-ai-vision/) from Pypi and replaced by [another MS package](replaced by https://pypi.org/project/azure-ai-vision-imageanalysis/1.0.0b1/). This change is not reflected in `pyproject.toml`.
2. Upon updating the package reference, Poetry dependency resolution takes hours before it ultimately crashes.

### The first problem is here:
```
#13 [langchain langchain-dev-dependencies 5/5] RUN poetry install --no-interaction --no-ansi --with dev,test,docs
2024-01-25 02:25:15.795Z: #13 1.180 Updating dependencies
2024-01-25 02:25:15.945Z: #13 1.180 Resolving dependencies...
2024-01-25 02:25:21.202Z: #13 6.587 
#13 6.587 Because langchain depends on azure-ai-vision (^0.11.1b1) which doesn't match any versions, version solving failed.
2024-01-25 02:25:21.653Z: #13 ERROR: process "/bin/sh -c poetry install --no-interaction --no-ansi --with dev,test,docs" did not complete successfully: exit code: 1
2024-01-25 02:25:21.750Z: ------
 > [langchain langchain-dev-dependencies 5/5] RUN poetry install --no-interaction --no-ansi --with dev,test,docs:
1.180 Updating dependencies
1.180 Resolving dependencies...
6.587 
6.587 Because langchain depends on azure-ai-vision (^0.11.1b1) which doesn't match any versions, version solving failed.
```
### The full stack trace is 1.5M lines (poetry solving dependencies in verbose mode), but the final message error is:
*(You may notice the poetry command is missing `--with dev,test,docs`. This is because I was experimenting with different installs to see if one would solve. The outcome is the same with or without.)*
```
failed to solve: process "/bin/sh -c poetry install -vvv --no-interaction --no-ansi --no-cache" did not complete successfully: exit code: 1
[2024-01-25T01:29:33.420Z] Stop (11249526 ms): Run: docker compose --project-name langchain_devcontainer -f /workspaces/langchain/.devcontainer/docker-compose.yaml -f /tmp/devcontainercli-root/docker-compose/docker-compose.devcontainer.build-1706134923893.yml build
[2024-01-25T01:29:34.801Z] Error: Command failed: docker compose --project-name langchain_devcontainer -f /workspaces/langchain/.devcontainer/docker-compose.yaml -f /tmp/devcontainercli-root/docker-compose/docker-compose.devcontainer.build-1706134923893.yml build
[2024-01-25T01:29:34.801Z]     at pw (/root/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:427:522)
[2024-01-25T01:29:34.801Z]     at runMicrotasks (<anonymous>)
[2024-01-25T01:29:34.801Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2024-01-25T01:29:34.801Z]     at async L$ (/root/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:427:2493)
[2024-01-25T01:29:34.802Z]     at async N$ (/root/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:409:3165)
[2024-01-25T01:29:34.802Z]     at async tAA (/root/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:479:3833)
[2024-01-25T01:29:34.802Z]     at async CC (/root/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:479:4775)
[2024-01-25T01:29:34.802Z]     at async NeA (/root/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:612:11107)
[2024-01-25T01:29:34.802Z]     at async MeA (/root/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:612:10848)
[2024-01-25T01:29:34.942Z] Stop (11253362 ms): Run in container: node /root/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-7edf6f65-e5f1-47df-8de6-ecd2483665631706134915493 --workspace-folder /workspaces/langchain --workspace-mount-consistency cached --id-label vsch.local.repository=https://github.com/cvansteenburg/langchain --id-label vsch.local.repository.volume=langchain-d0a07d0e50de76837e566b51dfd52879223a47f0cf6c9249f8998de5ea549f4c --id-label vsch.local.repository.folder=langchain --id-label devcontainer.config_file=/workspaces/langchain/.devcontainer/devcontainer.json --log-level debug --log-format json --config /workspaces/langchain/.devcontainer/devcontainer.json --override-config /tmp/devcontainer-b183d847-3f84-4dfc-bf18-cb61dde92812.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=langchain-d0a07d0e50de76837e566b51dfd52879223a47f0cf6c9249f8998de5ea549f4c,target=/workspaces,external=true --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default off --mount-workspace-git-root --terminal-columns 178 --terminal-rows 15
[2024-01-25T01:29:34.945Z] Exit code 1
[2024-01-25T01:29:34.948Z] Start: Run: docker rm -f d465e5855c617b703922f6eafccdf2bde11f6140c0baaa5e1e9f860bc70973ac
[2024-01-25T01:29:34.964Z] Command failed: node /root/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-7edf6f65-e5f1-47df-8de6-ecd2483665631706134915493 --workspace-folder /workspaces/langchain --workspace-mount-consistency cached --id-label vsch.local.repository=https://github.com/cvansteenburg/langchain --id-label vsch.local.repository.volume=langchain-d0a07d0e50de76837e566b51dfd52879223a47f0cf6c9249f8998de5ea549f4c --id-label vsch.local.repository.folder=langchain --id-label devcontainer.config_file=/workspaces/langchain/.devcontainer/devcontainer.json --log-level debug --log-format json --config /workspaces/langchain/.devcontainer/devcontainer.json --override-config /tmp/devcontainer-b183d847-3f84-4dfc-bf18-cb61dde92812.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=langchain-d0a07d0e50de76837e566b51dfd52879223a47f0cf6c9249f8998de5ea549f4c,target=/workspaces,external=true --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default off --mount-workspace-git-root --terminal-columns 178 --terminal-rows 15
[2024-01-25T01:29:34.965Z] Exit code 1
[2024-01-25T01:29:35.311Z] Stop (11256492 ms): Run in container: /bin/sh
[2024-01-25T01:29:35.311Z] Container server terminated (code: 137, signal: null).
[2024-01-25T01:29:35.312Z] Stop (11256684 ms): Run in container: /bin/sh
[2024-01-25T01:29:35.647Z] Stop (699 ms): Run: docker rm -f d465e5855c617b703922f6eafccdf2bde11f6140c0baaa5e1e9f860bc70973ac
[2024-01-25T01:30:34.625Z] Start: Run: docker volume ls -q
[2024-01-25T01:30:34.707Z] Stop (82 ms): Run: docker volume ls -q
[2024-01-25T01:30:34.785Z] Start: Run: docker version --format {{.Server.APIVersion}}
[2024-01-25T01:30:34.953Z] Stop (168 ms): Run: docker version --format {{.Server.APIVersion}}
[2024-01-25T01:30:34.953Z] 1.43
```

### Description

See above.

### System Info

VSCode and docker on MacOS 14.2.1 and on Github Codespaces.

**Comment by cvansteenburg** [comment]
That does solve the first of the two problems, but it doesn't resolve the dependency resolution issue.

**Comment by mad-cat-lon** [comment]
Experiencing this issue as well, hope this get fixed soon.

**Comment by mad-cat-lon** [comment]
@cvansteenburg 
I was able to get it working by cherrypicking [this commit](https://github.com/langchain-ai/langchain/commit/50f822daed776dd34e154ef13030f9b69ba58d94) from this [fork](https://github.com/slangenbach/langchain/tree/fix-devcontainer). 
Here's the link to the [open PR](https://github.com/langchain-ai/langchain/pull/12484)

**Comment by cgalo5758** [comment]
This is no longer an issue. We can go ahead and close this.

**Comment by cvansteenburg** [comment]
This is indeed fixed. Closing.
