### ISSUE TITLE
Community tracers not being injected properly in some cases

### ISSUE THREAD

**Issue by Lothiraldan** [langchain-ai/langchain#16635]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### First reproduction script:

```python
import os

# os.environ["LANGCHAIN_WANDB_TRACING"] = "true"
os.environ["LANGCHAIN_COMET_TRACING"] = "true"


from langchain_openai import OpenAI
# import langchain_community.callbacks

llm = OpenAI(temperature=0.9)

llm_result = llm.generate(["Tell me a joke"])
```

### Second reproduction script:

```python
import os

# os.environ["LANGCHAIN_WANDB_TRACING"] = "true"
os.environ["LANGCHAIN_COMET_TRACING"] = "true"

from langchain.chains import LLMChain
from langchain_openai import OpenAI
from langchain.prompts import PromptTemplate

llm = OpenAI(temperature=0.9)

template = """You are a playwright. Given the title of play, it is your job to write a synopsis for that title.
Title: {title}
Playwright: This is a synopsis for the above play:"""
prompt_template = PromptTemplate(input_variables=["title"], template=template)
synopsis_chain = LLMChain(llm=llm, prompt=prompt_template)

test_prompts = [{"title": "Documentary about Bigfoot in Paris"}]
print(synopsis_chain.apply(test_prompts))
```

### Description

I've encountered cases where my langchain runs were not traced with Comet tracer even when enabled. I was able to reproduce with the first minimal reproducing script.

To reproduce the issue, runs into an environment without `comet_ml` nor `wandb` being installed. If you run it as is, the script will runs just fine and won't try to log the LLM generation to Comet or Wandb. If you uncomment the import to `langchain_community.callbacks`, it will now fails with:

```
Traceback (most recent call last):
  File "/home/lothiraldan/.virtualenvs/tempenv-49bf135724739/lib/python3.10/site-packages/langchain_community/callbacks/tracers/comet.py", line 27, in import_comet_llm_api
    from comet_llm import (
ModuleNotFoundError: No module named 'comet_llm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/bug_tracers_langchain.py", line 11, in <module>
    llm_result = llm.generate(["Tell me a joke"])
  File "/home/lothiraldan/.virtualenvs/tempenv-49bf135724739/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 655, in generate
    CallbackManager.configure(
  File "/home/lothiraldan/.virtualenvs/tempenv-49bf135724739/lib/python3.10/site-packages/langchain_core/callbacks/manager.py", line 1400, in configure
    return _configure(
  File "/home/lothiraldan/.virtualenvs/tempenv-49bf135724739/lib/python3.10/site-packages/langchain_core/callbacks/manager.py", line 1960, in _configure
    var_handler = var.get() or cast(Type[BaseCallbackHandler], handler_class)()
  File "/home/lothiraldan/.virtualenvs/tempenv-49bf135724739/lib/python3.10/site-packages/langchain_community/callbacks/tracers/comet.py", line 62, in __init__
    self._initialize_comet_modules()
  File "/home/lothiraldan/.virtualenvs/tempenv-49bf135724739/lib/python3.10/site-packages/langchain_community/callbacks/tracers/comet.py", line 65, in _initialize_comet_modules
    comet_llm_api = import_comet_llm_api()
  File "/home/lothiraldan/.virtualenvs/tempenv-49bf135724739/lib/python3.10/site-packages/langchain_community/callbacks/tracers/comet.py", line 38, in import_comet_llm_api
    raise ImportError(
ImportError: To use the CometTracer you need to have the `comet_llm>=2.0.0` python package installed. Please install it with `pip install -U comet_llm`
```

It also happens with Wandb tracer. If you uncomment the line containing `LANGCHAIN_WANDB_TRACING` and run it, you should see the following error:

```
Traceback (most recent call last):
  File "/home/lothiraldan/.virtualenvs/tempenv-49bf135724739/lib/python3.10/site-packages/langchain_community/callbacks/tracers/wandb.py", line 449, in __init__
    import wandb
ModuleNotFoundError: No module named 'wandb'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/bug_tracers_langchain.py", line 11, in <module>
    llm_result = llm.generate(["Tell me a joke"])
  File "/home/lothiraldan/.virtualenvs/tempenv-49bf135724739/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 655, in generate
    CallbackManager.configure(
  File "/home/lothiraldan/.virtualenvs/tempenv-49bf135724739/lib/python3.10/site-packages/langchain_core/callbacks/manager.py", line 1400, in configure
    return _configure(
  File "/home/lothiraldan/.virtualenvs/tempenv-49bf135724739/lib/python3.10/site-packages/langchain_core/callbacks/manager.py", line 1960, in _configure
    var_handler = var.get() or cast(Type[BaseCallbackHandler], handler_class)()
  File "/home/lothiraldan/.virtualenvs/tempenv-49bf135724739/lib/python3.10/site-packages/langchain_community/callbacks/tracers/wandb.py", line 452, in __init__
    raise ImportError(
ImportError: Could not import wandb python package.Please install it with `pip install -U wandb`.
```

I've tried a more advanced example using a chain (second reproduction script)  and it always fails.

I'm not sure if it's a bug or not. This was definitely surprising for me as I was expected to get my langchain runs with the first shared script. If it's not a bug, it think it would be useful to clarify when users can expect community tracers to be injected and when they wouldn't.

Let me know what you think about this issue and how can I help. 

### System Info

```
System Information
------------------
> OS:  Linux
> OS Version:  #1 SMP PREEMPT_DYNAMIC Tue Jan 16 01:35:34 UTC 2024
> Python Version:  3.10.12 (main, Jul 27 2023, 14:43:19) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)]

Package Information
-------------------
> langchain_core: 0.1.16
> langchain: 0.1.4
> langchain_community: 0.0.16
> langchain_openai: 0.0.5

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve
```

**Comment by eyurtsev** [comment]
It doesn't sound like a bug. In LangChain, virtually all packages are optional by design to keep the package light. The import error says which packages should be installed to use the tracer.

**Comment by eyurtsev** [comment]
Going to close, but feel free to re-open if this was wrong

**Comment by Lothiraldan** [comment]
Hi @eyurtsev, sorry for the confusion about my bug report.

This issue is about the `CometTracer` not being injected automatically when the environment variable `LANGCHAIN_COMET_TRACING` is not set. The easiest way for me to reproduce the issue was to run the attached scripts in an environment that doesn't have the `comet_ml` library for the `CometTracer` callback. This way, if the script crash with the exception:
```ImportError: To use the CometTracer you need to have the `comet_llm>=2.0.0` ...```
It means that the `CometTracer` have been injected automatically.

I tried several different examples and it's not very clear when an end-user can expect the community tracers to being injected or no. I do think that's it's a confusing behavior and that's potentially a bug. @eyurtsev let me know what you think and if you agree that it's a bug, could you re-open it, I don't think I have permission to do it.

**Comment by Lothiraldan** [comment]
Hi @eyurtsev, here is how I should have probably reported this behavior in the first place. I have the following reproduction script:

```python
import comet_ml

# Making sure that a Comet API Key is correctly set
comet_ml.init()

import os
os.environ["LANGCHAIN_COMET_TRACING"] = "true"

from langchain_openai import OpenAI
llm = OpenAI(temperature=0.9)
llm_result = llm.generate(["Tell me a joke"])
print(llm_result)
```

In my testing environment, I have the Comet LLM SDK installed (`comet_llm`) and a valid Comet API Key set. When running the script, nothing is being reported on my Comet dashboard.

If I change the reproduction script slightly by adding an explicit import to `langchain_community.callbacks.manager`, the OpenAI trace will be uploaded to Comet as expected:

```diff
--- langchain_tracer.py	2024-03-28 10:34:14.236601671 +0100
+++ langchain_tracer_working.py	2024-03-28 10:39:05.132861578 +0100
@@ -5,6 +5,7 @@
 
 import os
 os.environ["LANGCHAIN_COMET_TRACING"] = "true"
+import langchain_community.callbacks.manager
 
 from langchain_openai import OpenAI
 llm = OpenAI(temperature=0.9)
```

My main concern is that in some cases, from an end-user perspective, third-party tracers works as expected (I'm guessing when `langchain_community.callbacks.manager` is imported under the hood) and in other cases, third-party tracers are not working. In such cases, it's very hard for end-users to understand how to know ahead of time which chain would be logged or not and how to debug such cases.

@eyurtsev I hope I made a clearer description of my issue, please let me know if you have any questions. And please let me know if it would be possible to re-open this issue

**Comment by Lothiraldan** [comment]
Hi @eyurtsev, did you had a chance to take another look at this issue? I would be happy to help and open a pull-request to help once we figure out the best way forward to reduce user confusion in such cases.
