### ISSUE TITLE
Nvidia Nemotron integration with langchain with TritonTensorRTLLM

### ISSUE THREAD

**Issue by Nima-Nilchian** [langchain-ai/langchain#16719]
### Description

I'm trying to integrate my Nemotron LLM with langchain, I use the source code in langchain_nvidia_trt.llms.py, for having streaming but gives an exception.

### Example Code

```python
from llms import TritonTensorRTLLM

llm = TritonTensorRTLLM(server_url="localhost:8001", model_name="Nemotron-rlhf")
res = llm.invoke("HI")
```

### Error Message and Stack Trace (if applicable)

and the Exeption is bellow
```Traceback (most recent call last):
  File "/workspace/workspace/tens.py", line 4, in <module>
    res = llm.invoke("HI")
  File "/usr/local/lib/python3.10/dist-packages/langchain_core/language_models/llms.py", line 230, in invoke
    self.generate_prompt(
  File "/usr/local/lib/python3.10/dist-packages/langchain_core/language_models/llms.py", line 525, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/langchain_core/language_models/llms.py", line 698, in generate
    output = self._generate_helper(
  File "/usr/local/lib/python3.10/dist-packages/langchain_core/language_models/llms.py", line 562, in _generate_helper
    raise e
  File "/usr/local/lib/python3.10/dist-packages/langchain_core/language_models/llms.py", line 549, in _generate_helper
    self._generate(
  File "/workspace/workspace/llms.py", line 153, in _generate
    result: str = self._request(
  File "/workspace/workspace/llms.py", line 206, in _request
    result_str += token
TypeError: can only concatenate str (not "InferenceServerException") to str
```

the InferenceServerException is bellow:

`unexpected inference output 'text_output' for model 'Nemotron-rlhf'`

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #163-Ubuntu SMP Fri Mar 17 18:26:02 UTC 2023
> Python Version:  3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

Package Information
-------------------
> langchain_core: 0.1.16
> langchain: 0.1.4
> langchain_community: 0.0.16

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve

**Comment by fciannella** [comment]
Hi Nima,

we are aware of this issue, we are working on a fix.

Here is the bug I filed: https://github.com/langchain-ai/langchain/issues/15045

@jdye64  for Viz.
