### ISSUE TITLE
SQLDocStore is incompatible with sqlite

### ISSUE THREAD

**Issue by pprados** [langchain-ai/langchain#16726]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

@gcheron,

```python
from langchain_community.storage.sql import SQLDocStore
SQLDocStore(connection_string="sqlite:///tmp/test.db")
```
Result: 
```
sqlalchemy.exc.CompileError: (in table 'langchain_storage_collection', column 'uuid'): Compiler <sqlalchemy.dialects.sqlite.base.SQLiteTypeCompiler object at 0x7f525b78d270> can't render element of type UUID
```

### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "/home/pprados/workspace.bda/langchain-rag/.venv/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 139, in _compiler_dispatch
    meth = getter(visitor)
AttributeError: 'SQLiteTypeCompiler' object has no attribute 'visit_UUID'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/pprados/workspace.bda/langchain-rag/.venv/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 6522, in visit_create_table
    processed = self.process(
  File "/home/pprados/workspace.bda/langchain-rag/.venv/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 912, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/pprados/workspace.bda/langchain-rag/.venv/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 143, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
  File "/home/pprados/workspace.bda/langchain-rag/.venv/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 6553, in visit_create_column
    text = self.get_column_specification(column, first_pk=first_pk)
  File "/home/pprados/workspace.bda/langchain-rag/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/base.py", line 1534, in get_column_specification
    coltype = self.dialect.type_compiler_instance.process(
  File "/home/pprados/workspace.bda/langchain-rag/.venv/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 957, in process
    return type_._compiler_dispatch(self, **kw)
  File "/home/pprados/workspace.bda/langchain-rag/.venv/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 141, in _compiler_dispatch
    return visitor.visit_unsupported_compilation(self, err, **kw)  # type: ignore  # noqa: E501
  File "/home/pprados/workspace.bda/langchain-rag/.venv/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 962, in visit_unsupported_compilation
    raise exc.UnsupportedCompilationError(self, element) from err
sqlalchemy.exc.UnsupportedCompilationError: Compiler <sqlalchemy.dialects.sqlite.base.SQLiteTypeCompiler object at 0x7f525b78d270> can't render element of type UUID (Background on this error at: https://sqlalche.me/e/20/l7de)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/pprados/workspace.bda/langchain-rag/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-aac51bc0ae83>", line 1, in <module>
    SQLDocStore(connection_string="sqlite:////tmp/test.db")
  File "/usr/lib/python3.10/typing.py", line 957, in __call__
    result = self.__origin__(*args, **kwargs)
  File "/home/pprados/workspace.bda/langchain-rag/.venv/lib/python3.10/site-packages/langchain_community/storage/sql.py", line 185, in __init__
    self.__post_init__()
  File "/home/pprados/workspace.bda/langchain-rag/.venv/lib/python3.10/site-packages/langchain_community/storage/sql.py", line 194, in __post_init__
    self.__create_tables_if_not_exists()
  File "/home/pprados/workspace.bda/langchain-rag/.venv/lib/python3.10/site-packages/langchain_community/storage/sql.py", line 204, in __create_tables_if_not_exists
    Base.metadata.create_all(self._conn)
  File "/home/pprados/workspace.bda/langchain-rag/.venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 5832, in create_all
    bind._run_ddl_visitor(
  File "/home/pprados/workspace.bda/langchain-rag/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2448, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/pprados/workspace.bda/langchain-rag/.venv/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 671, in traverse_single
    return meth(obj, **kw)
  File "/home/pprados/workspace.bda/langchain-rag/.venv/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 919, in visit_metadata
    self.traverse_single(
  File "/home/pprados/workspace.bda/langchain-rag/.venv/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 671, in traverse_single
    return meth(obj, **kw)
  File "/home/pprados/workspace.bda/langchain-rag/.venv/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 957, in visit_table
    )._invoke_with(self.connection)
  File "/home/pprados/workspace.bda/langchain-rag/.venv/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 315, in _invoke_with
    return bind.execute(self)
  File "/home/pprados/workspace.bda/langchain-rag/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
  File "/home/pprados/workspace.bda/langchain-rag/.venv/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 181, in _execute_on_connection
    return connection._execute_ddl(
  File "/home/pprados/workspace.bda/langchain-rag/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1525, in _execute_ddl
    compiled = ddl.compile(
  File "/home/pprados/workspace.bda/langchain-rag/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 309, in compile
    return self._compiler(dialect, **kw)
  File "/home/pprados/workspace.bda/langchain-rag/.venv/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 69, in _compiler
    return dialect.ddl_compiler(dialect, self, **kw)
  File "/home/pprados/workspace.bda/langchain-rag/.venv/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 867, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/home/pprados/workspace.bda/langchain-rag/.venv/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 912, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/pprados/workspace.bda/langchain-rag/.venv/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 143, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
  File "/home/pprados/workspace.bda/langchain-rag/.venv/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 6532, in visit_create_table
    raise exc.CompileError(
sqlalchemy.exc.CompileError: (in table 'langchain_storage_collection', column 'uuid'): Compiler <sqlalchemy.dialects.sqlite.base.SQLiteTypeCompiler object at 0x7f525b78d270> can't render element of type UUID

### Description

This new class presents a few problems.
- It is not sqlite compatible
- It uses a `connection_string` parameter, whereas `db_url` is used everywhere.
- It does not allow the call to be encapsulated in a transaction, as it cannot receive an engine parameter instead of `db_url`.

The usage with langchain is to propose an engine parameter to manipulate SQL.
Is the case for :

langchain_community.cache.SQLAlchemyCache
langchain_community.cache.SQLAlchemyMd5Cache

### System Info

langchain==0.1.4
langchain-community @ file:///home/pprados/workspace.bda/langchain/libs/community
langchain-core==0.1.16
langchain-openai==0.0.2.post1
langchain-qa-with-references==0.0.330

**Comment by eyurtsev** [comment]
SQLStore got reverted I think due to some implementation issues, closing issue for now
