### ISSUE TITLE
how to display just the message from this, openai.BadRequestError: Error code: 400 - {'error': {'message': "This model's maximum context length is 16385 tokens. However, your messages resulted in 16648 tokens. Please reduce the length of the messages.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}

### ISSUE THREAD

**Issue by jyoti194** [langchain-ai/langchain#16781]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

def chat1(question):
    
    
    greetings = ["hi", "hello", "hey"]  
    # if any(greeting in question.lower() for greeting in greetings):
    if any(greeting == question.lower() for greeting in greetings):

        return "Hello! How can I assist you today?"
   
    
    PROMPT = """ 
    Given an input question, create a syntactically correct MSSQL query, 
    then look at the results of the query and return the answer.
    Do not execute any query if the question is not relavent. 
    If a column name is not present, refrain from writing the SQL query. column like UAN number, PF number are not not present do not consider such columns.
    Write the query only for the column names which are present in view. 
    Execute the query and analyze the results to formulate a response. 
    Return the answer in user friendly form.

    
    The question: {question}
    """
    
    answer = None
    
    # conn = engine.connect()
    
    # If not in SQL format, create a database chain and run the question
    db_chain = SQLDatabaseChain.from_llm(llm, db, verbose=True)
    
    try: 
    #     answer = db_chain.run(PROMPT.format(question=question))
    #     return answer
    # except Exception as e:
    #     return f"An error occurred: {str(e)}"
    
    
    # result_df = pd.read_sql(answer, conn)
    # if result_df.empty:
    #     return "No results found"
        answer = db_chain.run(PROMPT.format(question=question))
        return answer
    
    except exc.ProgrammingError as e:
        # Check for a specific SQL error related to invalid column name
        if "Invalid column name" in str(e):
            print("Answer: Error Occured while processing the question")
            print(str(e))
            return "Invalid question. Please check your column names."
        
        else:
            print("Error Occured while processing")
            print(str(e))
            # return "Unknown ProgrammingError Occured"
            return "Invalid question."
          
        
    except openai.RateLimitError as e:
        print("Error Occured while fetching the answer")
        print(str(e))
        return "Rate limit exceeded. Please, Mention the Specific Columns you need!"
    
    except openai.BadRequestError as e:
        print("Error Occured while fetching the answer")
      
        # print(str(e.errcode))
        print(str(e))
      
        # return e.message
        
        return "Context length exceeded: This model's maximum context length is 16385 tokens. Please reduce the length of the messages."
        
    except Exception as e:
        print("Error Occured while processing")
        print(str(e))
        return "Unknown Error Occured"
    
Answer:Error Occured while fetching the answer
Error code: 400 - {'error': {'message': "This model's maximum context length is 16385 tokens. However, your messages resulted in 16648 tokens. Please reduce the length of the messages.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}

how to return just message present in the error code

### Error Message and Stack Trace (if applicable)

raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "This model's maximum context length is 16385 tokens. However, your messages resulted in 16648 tokens. Please reduce the length of the messages.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}

### Description

if the openai.BadRequestError is coming how to return just the message in exception in the code in error handling

### System Info

python 3.11
langchain: latest

**Comment by jyoti194** [comment]
Answer:Error Occured while fetching the answer
Traceback (most recent call last):
  File "c:\Users\rndbcpsoft\OneDrive\Desktop\test\main6.py", line 118, in chat1
    answer = db_chain.run(PROMPT.format(question=question))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rndbcpsoft\OneDrive\Desktop\test\envtest\Lib\site-packages\langchain\chains\base.py", line 505, in run
    return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rndbcpsoft\OneDrive\Desktop\test\envtest\Lib\site-packages\langchain\chains\base.py", line 310, in __call__
    raise e
  File "C:\Users\rndbcpsoft\OneDrive\Desktop\test\envtest\Lib\site-packages\langchain\chains\base.py", line 304, in __call__
    self._call(inputs, run_manager=run_manager)
  File "C:\Users\rndbcpsoft\OneDrive\Desktop\test\envtest\Lib\site-packages\langchain_experimental\sql\base.py", line 214, in _call
    raise exc
  File "C:\Users\rndbcpsoft\OneDrive\Desktop\test\envtest\Lib\site-packages\langchain_experimental\sql\base.py", line 195, in _call
    final_result = self.llm_chain.predict(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rndbcpsoft\OneDrive\Desktop\test\envtest\Lib\site-packages\langchain\chains\llm.py", line 298, in predict
    return self(kwargs, callbacks=callbacks)[self.output_key]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rndbcpsoft\OneDrive\Desktop\test\envtest\Lib\site-packages\langchain\chains\base.py", line 310, in __call__
    raise e
  File "C:\Users\rndbcpsoft\OneDrive\Desktop\test\envtest\Lib\site-packages\langchain\chains\base.py", line 304, in __call__
    self._call(inputs, run_manager=run_manager)
  File "C:\Users\rndbcpsoft\OneDrive\Desktop\test\envtest\Lib\site-packages\langchain\chains\llm.py", line 108, in _call
    response = self.generate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rndbcpsoft\OneDrive\Desktop\test\envtest\Lib\site-packages\langchain\chains\llm.py", line 120, in generate
    return self.llm.generate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rndbcpsoft\OneDrive\Desktop\test\envtest\Lib\site-packages\langchain\chat_models\base.py", line 459, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rndbcpsoft\OneDrive\Desktop\test\envtest\Lib\site-packages\langchain\chat_models\base.py", line 349, in generate
    raise e
  File "C:\Users\rndbcpsoft\OneDrive\Desktop\test\envtest\Lib\site-packages\langchain\chat_models\base.py", line 339, in generate
    self._generate_with_cache(
  File "C:\Users\rndbcpsoft\OneDrive\Desktop\test\envtest\Lib\site-packages\langchain\chat_models\base.py", line 492, in _generate_with_cache
    return self._generate(
           ^^^^^^^^^^^^^^^
  File "C:\Users\rndbcpsoft\OneDrive\Desktop\test\envtest\Lib\site-packages\langchain\chat_models\openai.py", line 422, in _generate
    response = self.completion_with_retry(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rndbcpsoft\OneDrive\Desktop\test\envtest\Lib\site-packages\langchain\chat_models\openai.py", line 344, in completion_with_retry
    return self.client.create(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rndbcpsoft\OneDrive\Desktop\test\envtest\Lib\site-packages\openai\_utils\_utils.py", line 271, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rndbcpsoft\OneDrive\Desktop\test\envtest\Lib\site-packages\openai\resources\chat\completions.py", line 643, in create
    return self._post(
           ^^^^^^^^^^^
  File "C:\Users\rndbcpsoft\OneDrive\Desktop\test\envtest\Lib\site-packages\openai\_base_client.py", line 1112, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rndbcpsoft\OneDrive\Desktop\test\envtest\Lib\site-packages\openai\_base_client.py", line 859, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\rndbcpsoft\OneDrive\Desktop\test\envtest\Lib\site-packages\openai\_base_client.py", line 949, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "This model's maximum context length is 16385 tokens. However, your messages resulted in 16647 tokens. Please reduce the length of the messages.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\rndbcpsoft\OneDrive\Desktop\test\main6.py", line 251, in <module>
    result = chat1("give all department names")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rndbcpsoft\OneDrive\Desktop\test\main6.py", line 146, in chat1
    error_message = e.error['message']
                    ^^^^^^^
AttributeError: 'BadRequestError' object has no attribute 'error'

**Comment by jyoti194** [comment]
@dosubot

from the error code, how to track back from where the error is coming from?
