### ISSUE TITLE
Agent with empty tools is not working

### ISSUE THREAD

**Issue by qingtian1771** [langchain-ai/langchain#16812]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

I tried following example code:
https://python.langchain.com/docs/modules/agents/agent_types/react
And change the code from:
```Python
tools = [TavilySearchResults(max_results=1)]
```
to:
```Python
tools[]
```

it outputs following error:
ValueError: An output parsing error occurred. In order to pass this error back to the agent and have it try again, pass `handle_parsing_errors=True` to the AgentExecutor. This is the error: Could not parse LLM output: ` I should try to find information about LangChain on the internet
Action: Search for "LangChain" on Google`

And I also tried this example code:
https://python.langchain.com/docs/modules/agents/agent_types/openai_functions_agent
And change the code from:
```Python
tools = [TavilySearchResults(max_results=1)]
```
to:
```Python
tools[]
```
it outputs following error:
raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "[] is too short - 'functions'", 'type': 'invalid_request_error', 'param': None, 'code': None}}

### Error Message and Stack Trace (if applicable)

> Entering new AgentExecutor chain...
Traceback (most recent call last):
  File "/home/tq/code/langchain/test/env/lib/python3.11/site-packages/langchain/agents/agent.py", line 1125, in _iter_next_step
    output = self.agent.plan(
             ^^^^^^^^^^^^^^^^
  File "/home/tq/code/langchain/test/env/lib/python3.11/site-packages/langchain/agents/agent.py", line 387, in plan
    for chunk in self.runnable.stream(inputs, config={"callbacks": callbacks}):
  File "/home/tq/code/langchain/test/env/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 2424, in stream
    yield from self.transform(iter([input]), config, **kwargs)
  File "/home/tq/code/langchain/test/env/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 2411, in transform
    yield from self._transform_stream_with_config(
  File "/home/tq/code/langchain/test/env/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 1497, in _transform_stream_with_config
    chunk: Output = context.run(next, iterator)  # type: ignore
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tq/code/langchain/test/env/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 2375, in _transform
    for output in final_pipeline:
  File "/home/tq/code/langchain/test/env/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 1045, in transform
    yield from self.stream(final, config, **kwargs)
  File "/home/tq/code/langchain/test/env/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 580, in stream
    yield self.invoke(input, config, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tq/code/langchain/test/env/lib/python3.11/site-packages/langchain_core/output_parsers/base.py", line 176, in invoke
    return self._call_with_config(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tq/code/langchain/test/env/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 1246, in _call_with_config
    context.run(
  File "/home/tq/code/langchain/test/env/lib/python3.11/site-packages/langchain_core/runnables/config.py", line 326, in call_func_with_variable_args
    return func(input, **kwargs)  # type: ignore[call-arg]
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tq/code/langchain/test/env/lib/python3.11/site-packages/langchain_core/output_parsers/base.py", line 177, in <lambda>
    lambda inner_input: self.parse_result([Generation(text=inner_input)]),
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tq/code/langchain/test/env/lib/python3.11/site-packages/langchain_core/output_parsers/base.py", line 219, in parse_result
    return self.parse(result[0].text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tq/code/langchain/test/env/lib/python3.11/site-packages/langchain/agents/output_parsers/react_single_input.py", line 84, in parse
    raise OutputParserException(
langchain_core.exceptions.OutputParserException: Could not parse LLM output: ` I should try to find information about LangChain on the internet
Action: Search for "LangChain" on Google`

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tq/code/langchain/test/Agent/test2.py", line 22, in <module>
    agent_executor.invoke({"input": "what is LangChain?"})
  File "/home/tq/code/langchain/test/env/lib/python3.11/site-packages/langchain/chains/base.py", line 162, in invoke
    raise e
  File "/home/tq/code/langchain/test/env/lib/python3.11/site-packages/langchain/chains/base.py", line 156, in invoke
    self._call(inputs, run_manager=run_manager)
  File "/home/tq/code/langchain/test/env/lib/python3.11/site-packages/langchain/agents/agent.py", line 1391, in _call
    next_step_output = self._take_next_step(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tq/code/langchain/test/env/lib/python3.11/site-packages/langchain/agents/agent.py", line 1097, in _take_next_step
    [
  File "/home/tq/code/langchain/test/env/lib/python3.11/site-packages/langchain/agents/agent.py", line 1097, in <listcomp>
    [
  File "/home/tq/code/langchain/test/env/lib/python3.11/site-packages/langchain/agents/agent.py", line 1136, in _iter_next_step
    raise ValueError(
ValueError: An output parsing error occurred. In order to pass this error back to the agent and have it try again, pass `handle_parsing_errors=True` to the AgentExecutor. This is the error: Could not parse LLM output: ` I should try to find information about LangChain on the internet
Action: Search for "LangChain" on Google`

### Description

I think Agent should be robust enough to deal with empty tools problem.

### System Info

langchain                                0.1.4
langchain-cli                            0.0.20
langchain-community                      0.0.15
langchain-core                           0.1.17
langchain-openai                         0.0.5
langchainhub                             0.1.14
langgraph                                0.0.19
langserve                                0.0.39
langsmith                                0.0.83

**Comment by nikhitaKanoj** [comment]
@qingtian1771 , i am also facing the same issue , did u get the solution for this ?

**Comment by ZeroTimo** [comment]
i also have the same issue, but only if i use an openai model. If i use an open source model, it works.

**Comment by nikhitaKanoj** [comment]
@ZeroTimo  Hey even i want to use open source models but not getting it , can you explain how u got it ? 
I dont want to use tools , tools=[] is not working
