### ISSUE TITLE
gpt-4-vision cannot be used in AzureChatOpenAI?

### ISSUE THREAD

**Issue by pydaxing** [langchain-ai/langchain#16815]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```python
os.environ["AZURE_OPENAI_API_KEY"] = ""
            os.environ["AZURE_OPENAI_ENDPOINT"] = ""
            llm = AzureChatOpenAI(
                openai_api_version="2023-12-01-preview",
                azure_deployment=self.model,
                streaming=True
            )
```

### Error Message and Stack Trace (if applicable)

```
Traceback (most recent call last):
  File "/mnt/workspace/workgroup/lengmou/Tars-Code-Agent/components/model/llm.py", line 80, in <module>
    for i in res:
  File "/mnt/workspace/workgroup/lengmou/miniconda3/envs/llamaindex/lib/python3.9/site-packages/langchain_core/runnables/base.py", line 2424, in stream
    yield from self.transform(iter([input]), config, **kwargs)
  File "/mnt/workspace/workgroup/lengmou/miniconda3/envs/llamaindex/lib/python3.9/site-packages/langchain_core/runnables/base.py", line 2411, in transform
    yield from self._transform_stream_with_config(
  File "/mnt/workspace/workgroup/lengmou/miniconda3/envs/llamaindex/lib/python3.9/site-packages/langchain_core/runnables/base.py", line 1497, in _transform_stream_with_config
    chunk: Output = context.run(next, iterator)  # type: ignore
  File "/mnt/workspace/workgroup/lengmou/miniconda3/envs/llamaindex/lib/python3.9/site-packages/langchain_core/runnables/base.py", line 2375, in _transform
    for output in final_pipeline:
  File "/mnt/workspace/workgroup/lengmou/miniconda3/envs/llamaindex/lib/python3.9/site-packages/langchain_core/runnables/base.py", line 1045, in transform
    yield from self.stream(final, config, **kwargs)
  File "/mnt/workspace/workgroup/lengmou/miniconda3/envs/llamaindex/lib/python3.9/site-packages/langchain_core/language_models/chat_models.py", line 250, in stream
    raise e
  File "/mnt/workspace/workgroup/lengmou/miniconda3/envs/llamaindex/lib/python3.9/site-packages/langchain_core/language_models/chat_models.py", line 234, in stream
    for chunk in self._stream(
  File "/mnt/workspace/workgroup/lengmou/miniconda3/envs/llamaindex/lib/python3.9/site-packages/langchain_community/chat_models/openai.py", line 399, in _stream
    if len(chunk["choices"]) == 0:
TypeError: object of type 'NoneType' has no len()
```

### Description

gpt-4-vision cannot be used in AzureChatOpenAI?

gpt-3.5-turbo、gpt-4、gpt-4-32k、gpt-4-turbo can be used in AzureChatOpenAI, but, gpt-4-vision cannot be used in it.

However, in the following way, gpt-4-vision can be used.

```
curl http://xxxxxxxxxxxxxxxx/2023-12-01-preview/chat \
  -H "Content-Type: application/json" \
  -H "tenant: 请用租户名称替换我"  \
  -d '{
    "model": "gpt-4-vision",
    "stream":false,
    "max_tokens":100,
    "messages": [{"role": "user","content":[{"type":"text","text":"Describe this picture:"},{"type":"image_url","image_url": {"url":"image_path"}}]}]
  }'
```

### System Info

langchain==0.0.351
langchain-community==0.0.4
langchain-core==0.1.17
langchain-openai==0.0.5
openai==1.10.0

**Comment by timxieICN** [comment]
Hi,
I was also trying to call gpt-4 (vision preview) in AzureChatOpenAI, but I got a different error:

```
openai.error.InvalidRequestError: Request 12f3d9cd-cbd5-4072-b2ef-e34aa9e6dcc2: 1 validation error for Request
body -> max_tokens
  none is not an allowed value (type=type_error.none.not_allowed)

```

**Comment by timxieICN** [comment]
Hi @alvaradojl - looks like you are calling the gpt-4-turbo model, not the vision model.
https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#gpt-4-and-gpt-4-turbo-preview-models

**Comment by vasisthasinghal** [comment]
As a follow up question, I'd like to know what the exact role of each parameter of the AzureChatOpenAI class has. For example, model_name, model_version, deployment_name etc. When these things are incompatible, for example, if my deployment is a gpt-4-turbo deployment but the model_version corresponds to gpt-3.5-turbo, which will take precedence? How is the ambiguity resolved and is there a way of checking which version is actually being used to generate responses?

**Comment by vasisthasinghal** [comment]
Also, can sometime provide a working example of how to instantiate a model using the AzureChatOpenAI class with the gpt-4-vision model?

**Comment by timxieICN** [comment]
@dosubot

I'm still having issue connecting to Azure OpenAI gpt-4-vision-preview

**Comment by timxieICN** [comment]
@dosu-bot

I'm still having issue connecting to Azure OpenAI `gpt-4-vision-preview` model
