### ISSUE TITLE
How to add memory in SQLDatabaseChain chatbot with sql to natural language query

### ISSUE THREAD

**Issue by jyoti194** [langchain-ai/langchain#16826]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

# Set the OPENAI_API_KEY environment variable
os.environ['OPENAI_API_KEY'] = openapi_key

# Define connection parameters using constants
from urllib.parse import quote_plus
server_name = constants.server_name
database_name = constants.database_name
username = constants.username 
password = constants.password
encoded_password = quote_plus(password)
connection_uri = f"mssql+pyodbc://{username}:{encoded_password}@{server_name}/{database_name}?driver=ODBC+Driver+17+for+SQL+Server"

# Create an engine to connect to the SQL database
engine = create_engine(connection_uri)
model_name="gpt-3.5-turbo-16k"
db = SQLDatabase(engine, view_support=True, include_tables=['EGV_emp_departments_ChatGPT'])

llm = ChatOpenAI(temperature=0, verbose=False, model=model_name) 

# Define a function named chat that takes a question and SQL format indicator as input
def chat1(question):
    
    
    greetings = ["hi", "hello", "hey"]  
    # if any(greeting in question.lower() for greeting in greetings):
    if any(greeting == question.lower() for greeting in greetings):

        return "Hello! How can I assist you today?"
   
    
    PROMPT = """ 
    Given an input question, create a syntactically correct MSSQL query, 
    then look at the results of the query and return the answer.
    Do not execute any query if the question is not relavent.
    If a question lacks specific details, do not write and execute the query, like 'what is the employee name'.
    If a column name is not present, refrain from writing the SQL query. column like UAN number, PF number are not not      present do not consider such columns.
    Write the query only for the column names which are present in view. 
    Execute the query and analyze the results to formulate a response. 
    Return the answer in user friendly form.

    
    The question: {question}
    """
    
    answer = None
    
    memory = ConversationBufferMemory(input_key='input', memory_key="history")
    
    # conn = engine.connect()
    
    # If not in SQL format, create a database chain and run the question
    # db_chain = SQLDatabaseChain.from_llm(llm, db, verbose=True, memory=memory)
    db_chain = SQLDatabaseChain(
        llm_chain=LLMChain(llm, memory=memory),
        database=db, 
        verbose=True
    )
    
    try: 
   
        answer = db_chain.run(PROMPT.format(question=question))
        return answer
    
    except exc.ProgrammingError as e:
        # Check for a specific SQL error related to invalid column name
        if "Invalid column name" in str(e):
            print("Answer: Error Occured while processing the question")
            print(str(e))
            return "Invalid question. Please check your column names."
        
        else:
            print("Error Occured while processing")
            print(str(e))
            # return "Unknown ProgrammingError Occured"
            return "Invalid question."
          
        
    except openai.RateLimitError as e:
        print("Error Occured while fetching the answer")
        print(str(e))
        return "Rate limit exceeded. Please, Mention the Specific Columns you need!"
    
    except openai.BadRequestError as e:
        print("Error Occured while fetching the answer")
    
        print(str(e.message))
        # return err_msg 
        
        return "Context length exceeded: This model's maximum context length is 16385 tokens. Please reduce the length of the messages."
       
    except Exception as e:
        print("Error Occured while processing")
        print(str(e))
        return "Unknown Error Occured"
        
  here is m code in which i'm trying to integrate the memory so that the model can remember previous question and and answer for next question, but im not sure with the exact method, 

### Error Message and Stack Trace (if applicable)

in above code while running with 
db_chain = SQLDatabaseChain.from_llm(llm, db, verbose=True, memory=memory)

where i have given memory=memory, but here while running the code im getting answer as "Unknown Error Occured" which is just goin to exception

like this 
The question: what is employee name ofAD####

SQLQuery:SELECT [EmployeeName]
FROM [EGV_emp_departments_ChatGPT]
WHERE [EmployeeID] = 'AD####'SELECT [EmployeeName]
FROM [EGV_emp_departments_ChatGPT]
WHERE [EmployeeID] = 'AD####'
[('H########i',)]

SQLResult: [('H########',)]
Answer:The employee name of AD#### is H######.
> Finished chain.
Error Occured while processing
'input'
Unknown Error Occured

while using like this 

db_chain = SQLDatabaseChain(
        llm_chain=LLMChain(llm, memory=memory),
        database=db, 
        verbose=True
    )

its not fetching the answer

C:\Users\rndbcpsoft\OneDrive\Desktop\test\envtest\Lib\site-packages\langchain\__init__.py:34: UserWarning: Importing LLMChain from langchain root module is no longer supported. Please use langchain.chains.LLMChain instead.
  warnings.warn(
C:\Users\rndbcpsoft\OneDrive\Desktop\test\envtest\Lib\site-packages\langchain\__init__.py:34: UserWarning: Importing OpenAI from langchain root module is no longer supported. Please use langchain.llms.OpenAI instead.
  warnings.warn(
C:\Users\rndbcpsoft\OneDrive\Desktop\test\envtest\Lib\site-packages\langchain\__init__.py:34: UserWarning: Importing SQLDatabase from langchain root module is no longer supported. Please use langchain.utilities.SQLDatabase instead.
  warnings.warn(
Traceback (most recent call last):
  File "c:\Users\rndbcpsoft\OneDrive\Desktop\test\main6.py", line 217, in <module>
    result= chat1("what is employee name of AD22050853")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rndbcpsoft\OneDrive\Desktop\test\main6.py", line 115, in chat1
    llm_chain=LLMChain(llm, memory=memory),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Serializable.__init__() takes 1 positional argument but 2 were given

### Description

in above code while running with 
db_chain = SQLDatabaseChain.from_llm(llm, db, verbose=True, memory=memory)

where i have given memory=memory, but here while running the code im getting answer as "Unknown Error Occured" which is just goin to exception

like this 
The question: what is employee name ofAD####

SQLQuery:SELECT [EmployeeName]
FROM [EGV_emp_departments_ChatGPT]
WHERE [EmployeeID] = 'AD####'SELECT [EmployeeName]
FROM [EGV_emp_departments_ChatGPT]
WHERE [EmployeeID] = 'AD####'
[('H########i',)]

SQLResult: [('H########',)]
Answer:The employee name of AD#### is H######.
> Finished chain.
Error Occured while processing
'input'
Unknown Error Occured

while using like this 

db_chain = SQLDatabaseChain(
        llm_chain=LLMChain(llm, memory=memory),
        database=db, 
        verbose=True
    )

its not fetching the answer

C:\Users\rndbcpsoft\OneDrive\Desktop\test\envtest\Lib\site-packages\langchain\__init__.py:34: UserWarning: Importing LLMChain from langchain root module is no longer supported. Please use langchain.chains.LLMChain instead.
  warnings.warn(
C:\Users\rndbcpsoft\OneDrive\Desktop\test\envtest\Lib\site-packages\langchain\__init__.py:34: UserWarning: Importing OpenAI from langchain root module is no longer supported. Please use langchain.llms.OpenAI instead.
  warnings.warn(
C:\Users\rndbcpsoft\OneDrive\Desktop\test\envtest\Lib\site-packages\langchain\__init__.py:34: UserWarning: Importing SQLDatabase from langchain root module is no longer supported. Please use langchain.utilities.SQLDatabase instead.
  warnings.warn(
Traceback (most recent call last):
  File "c:\Users\rndbcpsoft\OneDrive\Desktop\test\main6.py", line 217, in <module>
    result= chat1("what is employee name of AD22050853")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rndbcpsoft\OneDrive\Desktop\test\main6.py", line 115, in chat1
    llm_chain=LLMChain(llm, memory=memory),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Serializable.__init__() takes 1 positional argument but 2 were given

### System Info

python : 3.11
langchain: latest

**Comment by jyoti194** [comment]
@dosubot

can you give me the method, how add memory in SQLDatabaseChain, or in above code?

**Comment by jyoti194** [comment]
from langchain.memory import BaseMemory
ImportError: cannot import name 'BaseMemory' from 'langchain.memory'

**Comment by jyoti194** [comment]
@dosubot
here is my code for adding memory to the chatbot working with SQLDatabaseChain 
import pandas as pd 
import sqlalchemy as sal 
import os, sys #openai
import constants 
from langchain.sql_database import SQLDatabase
from langchain.llms.openai import OpenAI
from langchain_experimental.sql import SQLDatabaseChain
from sqlalchemy import create_engine, text, exc
from langchain.chat_models import ChatOpenAI 
from typing import List, Optional
import openai
from secret_key import openapi_key 
from langchain.prompts import PromptTemplate
from secret_key import openapi_key 
from fpdf import FPDF 
from langchain_experimental.tools import PythonREPLTool
from langchain_experimental.tools.python import tool


import dotenv
dotenv.load_dotenv(override=False)
from langchain import SQLDatabase 
from langchain.agents import (AgentExecutor, Tool, ZeroShotAgent,
                              initialize_agent, load_tools)

from langchain.chains.conversation.memory import ConversationBufferMemory

from typing import Dict, Any, List
from langchain.utilities import SQLDatabase
from langchain.prompts import PromptTemplate

# Set the OPENAI_API_KEY environment variable
os.environ['OPENAI_API_KEY'] = openapi_key

# Define connection parameters using constants
from urllib.parse import quote_plus
server_name = constants.server_name
database_name = constants.database_name
username = constants.username 
password = constants.password
encoded_password = quote_plus(password)


# Define a function named chat that takes a question and SQL format indicator as input
# def chat1(question):
    
connection_uri = f"mssql+pyodbc://{username}:{encoded_password}@{server_name}/{database_name}?driver=ODBC+Driver+17+for+SQL+Server"

# Create an engine to connect to the SQL database
engine = create_engine(connection_uri)
# model_name="gpt-3.5-turbo-16k"
# llm = ChatOpenAI(temperature=0, verbose=False, model=model_name)
model_name="gpt-3.5-turbo-instruct"
include_tables=['EGV_emp_departments_ChatGPT']
# db = SQLDatabase(engine, view_support=True, include_tables=['RND360_ChatGPT_BankView'])
db = SQLDatabase(engine, view_support=True, include_tables=include_tables)

llm = OpenAI(temperature=0, verbose=True, model=model_name) 

# memory = ConversationBufferMemory(memory_key="history", input_key="input")
memory = ConversationBufferMemory()

PROMPT_SUFFIX = """Only use the following tables:
{table_info}
Previous Conversation:
{history}
Question: {input}"""

_DEFAULT_TEMPLATE = """Given an input question, first create a syntactically correct {dialect} query to run, then look at the results of the query and return the answer. Unless the user specifies in his question a specific number of examples he wishes to obtain, always limit your query to at most {top_k} results. You can order the results by a relevant column to return the most interesting examples in the database.
Never query for all the columns from a specific table, only ask for a the few relevant columns given the question.
Pay attention to use only the column names that you can see in the schema description. Be careful to not query for columns that do not exist. Also, pay attention to which column is in which table.
Use the following format:
Question: Question here
SQLQuery: SQL Query to run
SQLResult: Result of the SQLQuery
Answer: Final answer here
"""

PROMPT = PromptTemplate.from_template(
    _DEFAULT_TEMPLATE + PROMPT_SUFFIX,
)

db_chain = SQLDatabaseChain.from_llm(llm, db, prompt=PROMPT, verbose=True, memory=memory)

# db_chain.run("what is employee name of AD22050853")
db_chain.run("to which department they belong too")
print(memory.load_memory_variables({}))




> Entering new SQLDatabaseChain chain...
what is employee name of AD22050853
SQLQuery:SELECT EmployeeName FROM EGV_emp_departments_ChatGPT WHERE EmployeeID = 'AD####'
SQLResult: [('Harin V#####',)]
Answer:Harin V#####
> Finished chain.
{'history': 'Human: what is employee name of AD####\nAI: Harin V#####'}

but after running 2nd question, its not taking the 1st question into consideration, instead it like a new question
> Entering new SQLDatabaseChain chain...
to which department they belong too
SQLQuery:SELECT DepartmentName FROM EGV_emp_departments_ChatGPT WHERE EmployeeName = 'S####'
SQLResult: [('Facility Management',)]
Answer:Facility Management
> Finished chain.
{'history': 'Human: to which department they belong too\nAI: Facility Management'}

**Comment by jyoti194** [comment]
hi @dosubot
here is my code which is using ConversationBufferMemory to store the memory
os.environ['OPENAI_API_KEY'] = openapi_key

# Define connection parameters using constants
from urllib.parse import quote_plus
server_name = constants.server_name
database_name = constants.database_name
username = constants.username 
password = constants.password
encoded_password = quote_plus(password)
connection_uri = f"mssql+pyodbc://{username}:{encoded_password}@{server_name}/{database_name}?driver=ODBC+Driver+17+for+SQL+Server"

# Create an engine to connect to the SQL database
engine = create_engine(connection_uri)
model_name="gpt-3.5-turbo-16k"
# llm = ChatOpenAI(temperature=0, verbose=False, model=model_name)
# model_name="gpt-3.5-turbo-instruct"
# db = SQLDatabase(engine, view_support=True, include_tables=['RND360_ChatGPT_BankView'])
db = SQLDatabase(engine, view_support=True, include_tables=['EGV_emp_departments_ChatGPT'])

db_chain = None

llm = ChatOpenAI(temperature=0, verbose=False, model=model_name) 

# PROMPT = """ 
#     Given an input question, create a syntactically correct MSSQL query by considering only the matching column names from the question, 
#     then look at the results of the query and return the answer.
#     If a column name is not present, refrain from writing the SQL query. column like UAN number, PF number are not not present do not consider such columns.
#     Write the query only for the column names which are present in view. 
#     Execute the query and analyze the results to formulate a response. 
#     Return the answer in sentence form.

    
#     The question: {question}
#     """


PROMPT_SUFFIX = """Only use the following tables:
{table_info}
Previous Conversation:
{history}
Question: {input}"""

_DEFAULT_TEMPLATE = """Given an input question, first create a syntactically correct {dialect} query to run, 
then look at the results of the query and return the answer. 
Unless the user specifies in his question a specific number of examples he wishes to obtain, 
If a column name is not present, refrain from writing the SQL query. column like UAN number, PF number are not not present do not consider such columns.
You can order the results by a relevant column to return the most interesting examples in the database.
Never query for all the columns from a specific table, only ask for a the few relevant columns given the question.
Pay attention to use only the column names that you can see in the schema description. Be careful to not query for columns that do not exist. Also, pay attention to which column is in which table.
Return the answer in user friendly form.

"""

PROMPT = PromptTemplate.from_template(_DEFAULT_TEMPLATE + PROMPT_SUFFIX)
    
memory = None

# Define a function named chat that takes a question and SQL format indicator as input
def chat1(question):
    
    
    global db_chain
    
    
    
    global memory
    
    if memory == None:
        
        # llm = ChatOpenAI(temperature=0, verbose=False, model=model_name) 
        
        memory = ConversationBufferMemory()
        
        
        # db_chain = SQLDatabaseChain.from_llm(llm, db, prompt=PROMPT, verbose=True, memory=memory)
        db_chain = SQLDatabaseChain.from_llm(llm, db, prompt=PROMPT, verbose=True, memory=memory)
        
    # while True: 
    # try:
    
    # print("*****")
    # print(memory.load_memory_variables({})['history'])
    # question = input("Enter your Question : ")
    greetings = ["hi", "hello", "hey"]

    if any(greeting == question.lower() for greeting in greetings):
        print(question)
        print("Hello! How can I assist you today?")
        return "Hello! How can I assist you today?"
    else:
        answer = db_chain.run(question)
        print(memory.load_memory_variables({}))
        return answer
        
      but here when im asking 2nd question its trowing error as "pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near 'Jyothi'." but when im asking 3rd question which is not related to first 2, its giving answer and storing memory, like this
