### ISSUE TITLE
RedisCache does't handle errors from redis. 

### ISSUE THREAD

**Issue by dingusagar** [langchain-ai/langchain#16866]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

Same code as in the docs [here](https://python.langchain.com/docs/integrations/llms/llm_caching#redis-cache) 

### Error Message and Stack Trace (if applicable)

```
Traceback (most recent call last):
  File "/Users/dingusagar/inference.py", line 181, in infer
    response = self.chain.invoke(inputs)
  File "/Users/dingusagar/envs/python_env/lib/python3.9/site-packages/langchain/schema/runnable/base.py", line 1213, in invoke
    input = step.invoke(
  File "/Users/dingusagar/envs/python_env/lib/python3.9/site-packages/langchain/chat_models/base.py", line 142, in invoke
    self.generate_prompt(
  File "/Users/dingusagar/envs/python_env/lib/python3.9/site-packages/langchain/chat_models/base.py", line 459, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
  File "/Users/dingusagar/envs/python_env/lib/python3.9/site-packages/langchain/chat_models/base.py", line 349, in generate
    raise e
  File "/Users/dingusagar/envs/python_env/lib/python3.9/site-packages/langchain/chat_models/base.py", line 339, in generate
    self._generate_with_cache(
  File "/Users/dingusagar/envs/python_env/lib/python3.9/site-packages/langchain/chat_models/base.py", line 500, in _generate_with_cache
    cache_val = llm_cache.lookup(prompt, llm_string)
  File "/Users/dingusagar/envs/python_env/lib/python3.9/site-packages/langchain/cache.py", line 392, in lookup
    results = self.redis.hgetall(self._key(prompt, llm_string))
  File "/Users/dingusagar/envs/python_env/lib/python3.9/site-packages/redis/commands/core.py", line 4867, in hgetall
    return self.execute_command("HGETALL", name)
  File "/Users/dingusagar/envs/python_env/lib/python3.9/site-packages/redis/client.py", line 1255, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/Users/dingusagar/envs/python_env/lib/python3.9/site-packages/redis/connection.py", line 1441, in get_connection
    connection.connect()
  File "/Users/dingusagar/envs/python_env/lib/python3.9/site-packages/redis/connection.py", line 704, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to 127.0.0.1:6379. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dingusagar/envs/python_env/lib/python3.9/site-packages/redis/connection.py", line 698, in connect
    sock = self.retry.call_with_retry(
  File "/Users/dingusagar/envs/python_env/lib/python3.9/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/Users/dingusagar/envs/python_env/lib/python3.9/site-packages/redis/connection.py", line 699, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/Users/dingusagar/envs/python_env/lib/python3.9/site-packages/redis/connection.py", line 1089, in _connect
    sock = super()._connect()
  File "/Users/dingusagar/envs/python_env/lib/python3.9/site-packages/redis/connection.py", line 987, in _connect
    raise err
  File "/Users/dingusagar/envs/python_env/lib/python3.9/site-packages/redis/connection.py", line 975, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused
```

### Description

I am using RedisCache as per the docs [here](https://python.langchain.com/docs/integrations/llms/llm_caching#redis-cache) 

Was testing how robust the system is if the redis connection fails for somereason or it goes out of memory. 
Looks like if the redis connection URL is not reachable, the system throws an error.

I wanted langchain to internally handle redis failure and do a direct API calls to the LLM on failure. we can ofcourse log the error. This will make the system more robust to failures. 

Does it make sense to add this feature? If so, I can help with raising a PR.  

### System Info

langchain==0.0.333

**Comment by dingusagar** [comment]
The bot response is good. But would appreciate it if a real human could acknowledge and let me know if this feature request makes sense. 
@sbusso @jarib @deepblue

**Comment by keenborder786** [comment]
I don't understand exactly what exactly is failing. Because I tried invoking the llm with cache multiple times and everything is working fine at my end. Can you please post your code snipped. Also if you want to handle Redis Failure just use your custom exception.

**Comment by dingusagar** [comment]
@keenborder786 , This issue doesn't happen every time. As mentioned, it happens only when the Redis server fails for some reason. If you want to replicate this, connect to a local redis server and try running the code. To simulate redis server failure, kill the server and execute the langchain code. 
The code used is the same as that in the [docs](https://python.langchain.com/docs/integrations/llms/llm_caching#redis-cache).

**Comment by keenborder786** [comment]
okay. @dingusagar I guess have already created PR to resolve this issue.
