### ISSUE TITLE
astream_events doesn't pass config properly

### ISSUE THREAD

**Issue by kaurelia** [langchain-ai/langchain#16944]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```py
    async def stream_tokens():
        async for event in agent.astream_events(
            {"input": prompt},
            {"configurable": {"session_id": "some_hard_coded_value"}},
            version="v1",
        ):
            kind = event["event"]
            if kind == "on_chat_model_stream":
                content = event["data"]["chunk"].content
                if content:
                    yield content
        yield ""
```

```py
    agent_with_history = RunnableWithMessageHistory(
        agent,
        lambda session_id: CassandraChatMessageHistory(
            keyspace="some_hard_coded_value", 
            session=cluster.connect(),
            session_id="some_hard_coded_value"
        ),
        input_messages_key="input",
        history_messages_key="history",
    )
   agent = AgentExecutor(
        agent=agent_with_history,
        tools=tools,
        verbose=True,
        handle_parsing_errors="Check your output and make sure it conforms, use the Action/Action Input syntax",
    )
```

### Error Message and Stack Trace (if applicable)

[chain/error] [1:chain:AgentExecutor] [2ms] Chain run errored with error:
"ValueError(\"Missing keys ['session_id'] in config['configurable'] Expected keys are ['session_id'].When using via .invoke() or .stream(), pass in a config; e.g., chain.invoke({'input': 'foo'}, {'configurable': {'session_id': '[your-value-here]'}})\")Traceback (most recent call last):\n\n\n  File \"/x/x/Library/Caches/pypoetry/virtualenvs/backend-python-Nj9PzyUh-py3.11/lib/python3.11/site-packages/langchain/agents/agent_iterator.py\", line 240, in __aiter__\n    async for chunk in self.agent_executor._aiter_next_step(\n\n\n  File \"/x/x/Library/Caches/pypoetry/virtualenvs/backend-python-Nj9PzyUh-py3.11/lib/python3.11/site-packages/langchain/agents/agent.py\", line 1262, in _aiter_next_step\n    output = await self.agent.aplan(\n             ^^^^^^^^^^^^^^^^^^^^^^^\n\n\n  File \"/x/x/Library/Caches/pypoetry/virtualenvs/backend-python-Nj9PzyUh-py3.11/lib/python3.11/site-packages/langchain/agents/agent.py\", line 422, in aplan\n    async for chunk in self.runnable.astream(\n\n\n  File \"/x/x/Library/Caches/pypoetry/virtualenvs/backend-python-Nj9PzyUh-py3.11/lib/python3.11/site-packages/langchain_core/runnables/base.py\", line 4123, in astream\n    self._merge_configs(config),\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n\n  File \"/x/x/Library/Caches/pypoetry/virtualenvs/backend-python-Nj9PzyUh-py3.11/lib/python3.11/site-packages/langchain_core/runnables/history.py\", line 454, in _merge_configs\n    raise ValueError(\n\n\nValueError: Missing keys ['session_id'] in config['configurable'] Expected keys are ['session_id'].When using via .invoke() or .stream(), pass in a config; e.g., chain.invoke({'input': 'foo'}, {'configurable': {'session_id': '[your-value-here]'}})"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/x/x/Library/Caches/pypoetry/virtualenvs/backend-python-Nj9PzyUh-py3.11/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/x/x/Library/Caches/pypoetry/virtualenvs/backend-python-Nj9PzyUh-py3.11/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/x/x/Library/Caches/pypoetry/virtualenvs/backend-python-Nj9PzyUh-py3.11/lib/python3.11/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/x/x/Library/Caches/pypoetry/virtualenvs/backend-python-Nj9PzyUh-py3.11/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/x/x/Library/Caches/pypoetry/virtualenvs/backend-python-Nj9PzyUh-py3.11/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/x/x/Library/Caches/pypoetry/virtualenvs/backend-python-Nj9PzyUh-py3.11/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/x/x/Library/Caches/pypoetry/virtualenvs/backend-python-Nj9PzyUh-py3.11/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/x/x/Library/Caches/pypoetry/virtualenvs/backend-python-Nj9PzyUh-py3.11/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/x/x/Library/Caches/pypoetry/virtualenvs/backend-python-Nj9PzyUh-py3.11/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/x/x/Library/Caches/pypoetry/virtualenvs/backend-python-Nj9PzyUh-py3.11/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/x/x/Library/Caches/pypoetry/virtualenvs/backend-python-Nj9PzyUh-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/x/x/Library/Caches/pypoetry/virtualenvs/backend-python-Nj9PzyUh-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/x/x/Library/Caches/pypoetry/virtualenvs/backend-python-Nj9PzyUh-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/x/x/Library/Caches/pypoetry/virtualenvs/backend-python-Nj9PzyUh-py3.11/lib/python3.11/site-packages/starlette/responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "/x/x/Library/Caches/pypoetry/virtualenvs/backend-python-Nj9PzyUh-py3.11/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/x/x/Library/Caches/pypoetry/virtualenvs/backend-python-Nj9PzyUh-py3.11/lib/python3.11/site-packages/starlette/responses.py", line 273, in wrap
    await func()
  File "/x/x/Library/Caches/pypoetry/virtualenvs/backend-python-Nj9PzyUh-py3.11/lib/python3.11/site-packages/starlette/responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "/x/x/Documents/programming/x/backend-python/source/server/routes/ask_agent_endpoint/ask_agent_endpoint.py", line 39, in stream_tokens
    async for event in agent.astream_events(
  File "/x/x/Library/Caches/pypoetry/virtualenvs/backend-python-Nj9PzyUh-py3.11/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 889, in astream_events
    async for log in _astream_log_implementation(  # type: ignore[misc]
  File "/x/x/Library/Caches/pypoetry/virtualenvs/backend-python-Nj9PzyUh-py3.11/lib/python3.11/site-packages/langchain_core/tracers/log_stream.py", line 612, in _astream_log_implementation
    await task
  File "/x/x/Library/Caches/pypoetry/virtualenvs/backend-python-Nj9PzyUh-py3.11/lib/python3.11/site-packages/langchain_core/tracers/log_stream.py", line 567, in consume_astream
    async for chunk in runnable.astream(input, config, **kwargs):
  File "/x/x/Library/Caches/pypoetry/virtualenvs/backend-python-Nj9PzyUh-py3.11/lib/python3.11/site-packages/langchain/agents/agent.py", line 1551, in astream
    async for step in iterator:
  File "/x/x/Library/Caches/pypoetry/virtualenvs/backend-python-Nj9PzyUh-py3.11/lib/python3.11/site-packages/langchain/agents/agent_iterator.py", line 240, in __aiter__
    async for chunk in self.agent_executor._aiter_next_step(
  File "/x/x/Library/Caches/pypoetry/virtualenvs/backend-python-Nj9PzyUh-py3.11/lib/python3.11/site-packages/langchain/agents/agent.py", line 1262, in _aiter_next_step
    output = await self.agent.aplan(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/x/x/Library/Caches/pypoetry/virtualenvs/backend-python-Nj9PzyUh-py3.11/lib/python3.11/site-packages/langchain/agents/agent.py", line 422, in aplan
    async for chunk in self.runnable.astream(
  File "/x/x/Library/Caches/pypoetry/virtualenvs/backend-python-Nj9PzyUh-py3.11/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 4123, in astream
    self._merge_configs(config),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/x/x/Library/Caches/pypoetry/virtualenvs/backend-python-Nj9PzyUh-py3.11/lib/python3.11/site-packages/langchain_core/runnables/history.py", line 454, in _merge_configs
    raise ValueError(
ValueError: Missing keys ['session_id'] in config['configurable'] Expected keys are ['session_id'].When using via .invoke() or .stream(), pass in a config; e.g., chain.invoke({'input': 'foo'}, {'configurable': {'session_id': '[your-value-here]'}})

### Description

I'm trying to integrate chat history with Cassandra, like I did for chain. With astream_events on AgentExecutor I have problem that config isn't passed down, so it throws error like in traceback. I tried to manually edit source code at /Library/Caches/pypoetry/virtualenvs/backend-python-Nj9PzyUh-py3.11/lib/python3.11/site-packages/langchain_core/runnables/base.py line 4123, and add on my own to final config configurable["session_id"]. After that, it's working. I'm working with GPT-4, but this bug should appear no matter which LLM you are using.

### System Info

langchain==0.1.4
langchain-community==0.0.16
langchain-core==0.1.17
langchain-experimental==0.0.49
langchain-openai==0.0.5
langchainhub==0.1.14

MacOS Sonoma 14.1.2 with ARM M3 CPU
Python 3.11.7 (main, Dec 20 2023, 12:17:39) [Clang 15.0.0 (clang-1500.0.40.1)] on darwin

**Comment by kaurelia** [comment]
@dosu-bot my patch is low quality to make it just works. I would be appreciated to let fix that by someone from langchain team, because I don't know the codebase well enough to make good quality fix.

**Comment by eyurtsev** [comment]
Thanks for reporting!

**Comment by eyurtsev** [comment]
@kaurelia i am unable to reproduce the issue. Added unit tests that confirm that config is propagated correctly.

 https://github.com/langchain-ai/langchain/pull/17055/files#diff-e512e3f84daf23029ebcceb11460f1c82056314653673e450a5831147d8cb84dR1149

Would you mind producing a minimal example that demonstrates the issue?

**Comment by kaurelia** [comment]
Hi @eyurtsev, while making the repository with reproduction, I found out that in my code I improperly passed the result from RunnableWithMessageHistory into AgentExecutor. It shouldn't be passed inside AgentExecutor in that case. I appreciate your work, and I'm thankful for your help. 

I will close this issue.

**Comment by eyurtsev** [comment]
Awesome! Thanks for following up!
