### ISSUE TITLE
Vertex AI Gemini Pro doesn't handle safety measures

### ISSUE THREAD

**Issue by shikanime** [langchain-ai/langchain#17032]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```
llm = ChatVertexAI(model_name="gemini-pro", convert_system_message_to_human=True, temperature=0)
[SystemMessage(content="Use the following optional pieces of information to fullfil the user's request in French and in markdown format.\n\nPotentially Useful Information:\n\nQuestion: Qu'est-ce qu'une question débile ?"), HumanMessage(content="Qu'est-ce qu'une question débile ?")]
llm.invoke(msgs)
```

### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspaces/metabot-backend/.venv/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 165, in invoke
    self.generate_prompt(
  File "/workspaces/metabot-backend/.venv/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 543, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/metabot-backend/.venv/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 407, in generate
    raise e
  File "/workspaces/metabot-backend/.venv/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 397, in generate
    self._generate_with_cache(
  File "/workspaces/metabot-backend/.venv/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 576, in _generate_with_cache
    return self._generate(
           ^^^^^^^^^^^^^^^
  File "/workspaces/metabot-backend/.venv/lib/python3.11/site-packages/langchain_google_vertexai/chat_models.py", line 375, in _generate
    response = chat.send_message(
               ^^^^^^^^^^^^^^^^^^
  File "/workspaces/metabot-backend/.venv/lib/python3.11/site-packages/vertexai/generative_models/_generative_models.py", line 709, in send_message
    return self._send_message(
           ^^^^^^^^^^^^^^^^^^^
  File "/workspaces/metabot-backend/.venv/lib/python3.11/site-packages/vertexai/generative_models/_generative_models.py", line 805, in _send_message
    raise ResponseBlockedError(
vertexai.generative_models._generative_models.ResponseBlockedError: The response was blocked.

### Description

The code snippet you provided is trying to use the Gemini Pro language model through the Langchain library to answer a question in French. However, it's encountering an error because the Gemini Pro model has a safety feature that Langchain doesn't currently handle.

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #1 SMP Thu Oct 5 21:02:42 UTC 2023
> Python Version:  3.11.7 (main, Jan 26 2024, 08:55:53) [GCC 11.4.0]

Package Information
-------------------
> langchain_core: 0.1.10
> langchain: 0.1.0
> langchain_community: 0.0.12
> langserve: Not Found

**Comment by mfernandezsidn** [comment]
Any solution to this problem?
