### ISSUE TITLE
SemanticChunker error with single sentence documents

### ISSUE THREAD

**Issue by sberk42** [langchain-ai/langchain#17106]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```python
from langchain_experimental.text_splitter import SemanticChunker
...
text_splitter=SemanticChunker(embeddings)
docs = text_splitter.split_documents(documents)

-> IndexError: index -1 is out of bounds for axis 0 with size 0


### Error Message and Stack Trace (if applicable)

  File "/usr/local/lib/python3.10/dist-packages/langchain_experimental/text_splitter.py", line 138, in create_documents
    for chunk in self.split_text(text):
  File "/usr/local/lib/python3.10/dist-packages/langchain_experimental/text_splitter.py", line 103, in split_text
    breakpoint_distance_threshold = np.percentile(
  File "/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py", line 4283, in percentile
    return _quantile_unchecked(
  File "/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py", line 4555, in _quantile_unchecked
    return _ureduce(a,
  File "/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py", line 3823, in _ureduce
    r = func(a, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py", line 4721, in _quantile_ureduce_func
    result = _quantile(arr,
  File "/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py", line 4830, in _quantile
    slices_having_nans = np.isnan(arr[-1, ...])
IndexError: index -1 is out of bounds for axis 0 with size 0

### Description

I'm trying the SemanticChunker and noticed that it fails for documents that can't be splitted into multiple sentences.
I guess using the SemanticChunker for such short documents does not really make sense, however it should cause an exception.

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #1 SMP Thu Oct 5 21:02:42 UTC 2023
> Python Version:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

Package Information
-------------------
> langchain_core: 0.1.18
> langchain: 0.1.5
> langchain_community: 0.0.17
> langchain_experimental: 0.0.50
> langchain_openai: 0.0.5

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve

**Comment by Aryazaky** [comment]
@dosu-bot I don't know if this is a different issue or a related issue. If `distances` is empty in the 'gradient' option of semantic chunker it causes numpy to go IndexError. 

```python
IndexError                                Traceback (most recent call last)
[<ipython-input-9-dd360b9e5d4f>](https://localhost:8080/#) in <cell line: 31>()
     29     return chunks
     30 
---> 31 chunks = text_splitter.split_documents(docs)
     32 chunks = calculate_chunk_ids(chunks)
     33 print(f"Split into {len(chunks)} chunks")

4 frames
[/usr/local/lib/python3.10/dist-packages/langchain_experimental/text_splitter.py](https://localhost:8080/#) in split_documents(self, documents)
    279             texts.append(doc.page_content)
    280             metadatas.append(doc.metadata)
--> 281         return self.create_documents(texts, metadatas=metadatas)
    282 
    283     def transform_documents(

[/usr/local/lib/python3.10/dist-packages/langchain_experimental/text_splitter.py](https://localhost:8080/#) in create_documents(self, texts, metadatas)
    264         for i, text in enumerate(texts):
    265             start_index = 0
--> 266             for chunk in self.split_text(text):
    267                 metadata = copy.deepcopy(_metadatas[i])
    268                 if self._add_start_index:

[/usr/local/lib/python3.10/dist-packages/langchain_experimental/text_splitter.py](https://localhost:8080/#) in split_text(self, text)
    226                 breakpoint_distance_threshold,
    227                 breakpoint_array,
--> 228             ) = self._calculate_breakpoint_threshold(distances)
    229 
    230         indices_above_thresh = [

[/usr/local/lib/python3.10/dist-packages/langchain_experimental/text_splitter.py](https://localhost:8080/#) in _calculate_breakpoint_threshold(self, distances)
    155         elif self.breakpoint_threshold_type == "gradient":
    156             # Calculate the threshold based on the distribution of gradient of distance array. # noqa: E501
--> 157             distance_gradient = np.gradient(distances, range(0, len(distances)))
    158             return cast(
    159                 float,

[/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py](https://localhost:8080/#) in gradient(f, axis, edge_order, *varargs)
   1180             # if distances are constant reduce to the scalar case
   1181             # since it brings a consistent speedup
-> 1182             if (diffx == diffx[0]).all():
   1183                 diffx = diffx[0]
   1184             dx[i] = diffx

IndexError: index 0 is out of bounds for axis 0 with size 0
```

Here is the relevant code from `text_splitter.py`:
```python
elif self.breakpoint_threshold_type == "gradient":
            # Calculate the threshold based on the distribution of gradient of distance array. # noqa: E501
            distance_gradient = np.gradient(distances, range(0, len(distances)))
            return cast(
                float,
                np.percentile(distance_gradient, self.breakpoint_threshold_amount),
            ), distance_gradient
```
