### ISSUE TITLE
Error raised by bedrock service: An error occurred (ValidationException) when calling the InvokeModel operation.

### ISSUE THREAD

**Issue by pattabhia** [langchain-ai/langchain#17170]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```

from langchain.chains import ConversationalRetrievalChain
from langchain.llms.bedrock import Bedrock
from langchain.prompts import PromptTemplate

llm_jurassic_ultra = Bedrock(
    model_id="ai21.j2-ultra-v1",
    endpoint_url="https://bedrock.us-east-1.amazonaws.com",
    model_kwargs={"temperature": 0.7, "maxTokens": 500, "numResults": 1}
   

print('llm_jurassic_ultra:', llm_jurassic_ultra);

llm_jurassic_mid = Bedrock(
    model_id="amazon.titan-text-express-v1",
    endpoint_url="https://bedrock.us-east-1.amazonaws.com",
    model_kwargs={"temperature": 0.7, "maxTokenCount": 300, "topP": 1}
)

print('llm_jurassic_mid:', llm_jurassic_mid);

#Create template for combining chat history and follow up question into a standalone question.
question_generator_chain_template = """
Here is some chat history contained in the <chat_history> tags and a follow-up question in the <follow_up> tags:

<chat_history>
{chat_history}
</chat_history>

<follow_up>
{question}
</follow_up>

Combine the chat history and follow up question into a standalone question.
"""

question_generator_chain_prompt = PromptTemplate.from_template(question_generator_chain_template)

print('question_generator_chain_prompt:', question_generator_chain_prompt);

#Create template for asking the question of the given context.
combine_docs_chain_template = """
You are a friendly, concise chatbot. Here is some context, contained in <context> tags:

<context>
{context}
</context>

Given the context answer this question: {question}
"""
combine_docs_chain_prompt = PromptTemplate.from_template(combine_docs_chain_template)

# RetrievalQA instance with custom prompt template
qa = ConversationalRetrievalChain.from_llm(
    llm=llm_jurassic_ultra,
    condense_question_llm=llm_jurassic_mid,
    retriever=retriever,
    return_source_documents=True,
    condense_question_prompt=question_generator_chain_prompt,
    combine_docs_chain_kwargs={"prompt": combine_docs_chain_prompt}
)

more here : https://github.com/aws-samples/amazon-bedrock-kendra-lex-chatbot/blob/main/lambda/app.py

```

### Error Message and Stack Trace (if applicable)

```
[ERROR] ValueError: Error raised by bedrock service: An error occurred (ValidationException) when calling the InvokeModel operation: The requested operation is not recognized by the service.
Traceback (most recent call last):
  File "/var/task/app.py", line 128, in lambda_handler
    result = qa(input_variables)
  File "/var/lang/lib/python3.9/site-packages/langchain/chains/base.py", line 310, in __call__
    raise e
  File "/var/lang/lib/python3.9/site-packages/langchain/chains/base.py", line 304, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/var/lang/lib/python3.9/site-packages/langchain/chains/conversational_retrieval/base.py", line 159, in _call
    answer = self.combine_docs_chain.run(
  File "/var/lang/lib/python3.9/site-packages/langchain/chains/base.py", line 510, in run
    return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[
  File "/var/lang/lib/python3.9/site-packages/langchain/chains/base.py", line 310, in __call__
    raise e
  File "/var/lang/lib/python3.9/site-packages/langchain/chains/base.py", line 304, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/var/lang/lib/python3.9/site-packages/langchain/chains/combine_documents/base.py", line 122, in _call
    output, extra_return_dict = self.combine_docs(
  File "/var/lang/lib/python3.9/site-packages/langchain/chains/combine_documents/stuff.py", line 171, in combine_docs
    return self.llm_chain.predict(callbacks=callbacks, **inputs), {}
  File "/var/lang/lib/python3.9/site-packages/langchain/chains/llm.py", line 298, in predict
    return self(kwargs, callbacks=callbacks)[self.output_key]
  File "/var/lang/lib/python3.9/site-packages/langchain/chains/base.py", line 310, in __call__
    raise e
  File "/var/lang/lib/python3.9/site-packages/langchain/chains/base.py", line 304, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/var/lang/lib/python3.9/site-packages/langchain/chains/llm.py", line 108, in _call
    response = self.generate([inputs], run_manager=run_manager)
  File "/var/lang/lib/python3.9/site-packages/langchain/chains/llm.py", line 120, in generate
    return self.llm.generate_prompt(
  File "/var/lang/lib/python3.9/site-packages/langchain/llms/base.py", line 507, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
  File "/var/lang/lib/python3.9/site-packages/langchain/llms/base.py", line 656, in generate
    output = self._generate_helper(
  File "/var/lang/lib/python3.9/site-packages/langchain/llms/base.py", line 544, in _generate_helper
    raise e
  File "/var/lang/lib/python3.9/site-packages/langchain/llms/base.py", line 531, in _generate_helper
    self._generate(
  File "/var/lang/lib/python3.9/site-packages/langchain/llms/base.py", line 1053, in _generate
    self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)
  File "/var/lang/lib/python3.9/site-packages/langchain/llms/bedrock.py", line 427, in _call
    return self._prepare_input_and_invoke(prompt=prompt, stop=stop, **kwargs)
  File "/var/lang/lib/python3.9/site-packages/langchain/llms/bedrock.py", line 266, in _prepare_input_and_invoke
    raise ValueError(f"Error raised by bedrock service: {e}")

```

### Description

I am trying langchain to fetch response from Bedrock and have error as described. I validated if any access related issues and there is nothing as such.

Working on this example: https://github.com/aws-samples/amazon-bedrock-kendra-lex-chatbot/blob/main/lambda/app.py

### System Info

Running on AWS Lambda.

**Comment by tmin97** [comment]
seems like is the endpoint url issue. Should use this instead

endpoint_url="https://bedrock-runtime.us-east-1.amazonaws.com" 

reference: https://stackoverflow.com/questions/77215634/how-to-send-a-request-to-aws-bedrock-properly
