### ISSUE TITLE
Amadeus searchflight not working

### ISSUE THREAD

**Issue by SiruX21** [langchain-ai/langchain#17375]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_community.agent_toolkits.amadeus.toolkit import AmadeusToolkit
from langchain import hub
from langchain.agents import AgentExecutor, create_react_agent
llm = ChatGoogleGenerativeAI(model="gemini-pro")
toolkit = AmadeusToolkit(llm=llm)
tools = toolkit.get_tools()
prompt = hub.pull("sirux21/react")
agent = create_react_agent(llm, tools, prompt)
val = {
     "input": "Find flights from NYC to LAX tomorrow",
}
agent_executor = AgentExecutor(
    agent=agent,
    tools=tools,
    verbose=True,
    agent=AgentType.STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION,
)

agent_executor.invoke(val)
```

### Error Message and Stack Trace (if applicable)

NYC is too broad of a location, I should narrow it down to a specific airport
Action: closest_airport
Action Input: {
    "location": "New York City, NY"
}content='```json\n{\n  "iataCode": "JFK"\n}\n```'JFK is the closest airport to NYC, I will use that as the origin airport
Action: single_flight_search
Action Input: {
    "originLocationCode": "JFK",
    "destinationLocationCode": "LAX",
    "departureDateTimeEarliest": "2023-06-08T00:00:00",
    "departureDateTimeLatest": "2023-06-08T23:59:59"
}Traceback (most recent call last):
  File "C:\Users\sirux21\Nextcloud\CodeRed-Oddysey\CodeRed-Odyssey\python\main4.py", line 24, in <module>
    agent_executor.invoke(val)
  File "C:\Users\sirux21\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\langchain\chains\base.py", line 162, in invoke
    raise e
  File "C:\Users\sirux21\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\langchain\chains\base.py", line 156, in invoke
    self._call(inputs, run_manager=run_manager)
  File "C:\Users\sirux21\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\langchain\agents\agent.py", line 1391, in _call
    next_step_output = self._take_next_step(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sirux21\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\langchain\agents\agent.py", line 1097, in _take_next_step
    [
  File "C:\Users\sirux21\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\langchain\agents\agent.py", line 1097, in <listcomp>
    [
  File "C:\Users\sirux21\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\langchain\agents\agent.py", line 1182, in _iter_next_step
    yield self._perform_agent_action(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sirux21\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\langchain\agents\agent.py", line 1204, in _perform_agent_action
    observation = tool.run(
                  ^^^^^^^^^
  File "C:\Users\sirux21\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\langchain_core\tools.py", line 364, in run
    raise e
  File "C:\Users\sirux21\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\langchain_core\tools.py", line 355, in run
    parsed_input = self._parse_input(tool_input)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sirux21\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\langchain_core\tools.py", line 258, in _parse_input
    input_args.validate({key_: tool_input})
  File "C:\Users\sirux21\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\v1\main.py", line 711, in validate
    return cls(**value)
           ^^^^^^^^^^^^
  File "C:\Users\sirux21\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\v1\main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 3 validation errors for FlightSearchSchema
destinationLocationCode
  field required (type=value_error.missing)
departureDateTimeEarliest
  field required (type=value_error.missing)
departureDateTimeLatest
  field required (type=value_error.missing)

### Description

FlightSearchSchema is unable to parse the input

### System Info

langchain==0.1.6
langchain-community==0.0.19
langchain-core==0.1.22
langchain-google-genai==0.0.8
langchainhub==0.1.14
windows
3.11

**Comment by SiruX21** [comment]
@dosu-bot If you look, that is exactly what is passed through, 
```
Action Input: {
"originLocationCode": "JFK",
"destinationLocationCode": "LAX",
"departureDateTimeEarliest": "2023-06-08T00:00:00",
"departureDateTimeLatest": "2023-06-08T23:59:59"
}
```
by the agent AI, and the issue still persists.

**Comment by caidwang** [comment]
@SiruX21 did you solve it? I meet the same problem. Does prompt optimize work?

**Comment by caidwang** [comment]
Hi,@SiruX21. This problem has be solved in the latest doc. [Amadeus Tool](https://python.langchain.com/docs/integrations/toolkits/amadeus)
