### ISSUE TITLE
RuntimeError: There is no current event loop in thread 'asyncio_0'. Utilizing Sanic as my web framework as choice. Error occurs when attempting to use `PGVector.afrom_documents`

### ISSUE THREAD

**Issue by na-stewart** [langchain-ai/langchain#17485]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```
app = Sanic("app")

async def create_collection(col_id, docs, embeddings):
    return await PGVector.afrom_documents(
        embedding=embeddings,
        documents=docs,
        collection_name=f"col_{col_id}",
        connection_string=config.CONNECTION_STRING,
        pre_delete_collection=True,
    )

@app.post("/collection")
async def chat_collection(request):
    docs = []
    session = request.args.get("session")
    if not session:
        raise ValueError("Session ID is required.")
    for file in request.files.getlist("collection"):
        for page in document_split_chunk(file.body, "pdf"):
            docs.append(page)
    await create_collection(session, docs, embeddings)
    return json("Collection created.")

if __name__ == "__main__":
    app.run(host="127.0.0.1", port=8000, workers=1, debug=True)
```

### Error Message and Stack Trace (if applicable)

```
Executing <Task pending name='Task-8' coro=<HttpProtocol.connection_task() running at C:\Users\Aidan Stewart\PycharmProjects\x\venv\lib\site-packages\sanic\server\protocols\http_protocol.py:155> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at C:\Users\Aidan Stewart\AppData\Local\Programs\Python\Python39\lib\asyncio\futures.py:384, <TaskWakeupMethWrapper object at 0x0000016B66DC5CA0>()] created at C:\Users\Aidan Stewart\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py:429> created at C:\Users\Aidan Stewart\PycharmProjects\x\venv\lib\site-packages\sanic\server\protocols\http_protocol.py:283> took 1.016 seconds
Traceback (most recent call last):
  File "C:\Users\Aidan Stewart\PycharmProjects\x\venv\lib\site-packages\langchain_community\vectorstores\pgvector.py", line 253, in create_vector_extension
    session.execute(statement)
  File "C:\Users\Aidan Stewart\PycharmProjects\x\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2308, in execute
    return self._execute_internal(
  File "C:\Users\Aidan Stewart\PycharmProjects\x\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2180, in _execute_internal
    conn = self._connection_for_bind(bind)
  File "C:\Users\Aidan Stewart\PycharmProjects\x\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2047, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
  File "<string>", line 2, in _connection_for_bind
  File "C:\Users\Aidan Stewart\PycharmProjects\x\venv\lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\Aidan Stewart\PycharmProjects\x\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1143, in _connection_for_bind
    conn = bind.connect()
  File "C:\Users\Aidan Stewart\PycharmProjects\x\venv\lib\site-packages\sqlalchemy\engine\base.py", line 3269, in connect
    return self._connection_cls(self)
  File "C:\Users\Aidan Stewart\PycharmProjects\x\venv\lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "C:\Users\Aidan Stewart\PycharmProjects\x\venv\lib\site-packages\sqlalchemy\engine\base.py", line 3293, in raw_connection
    return self.pool.connect()
  File "C:\Users\Aidan Stewart\PycharmProjects\x\venv\lib\site-packages\sqlalchemy\pool\base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\Aidan Stewart\PycharmProjects\x\venv\lib\site-packages\sqlalchemy\pool\base.py", line 1269, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\Aidan Stewart\PycharmProjects\x\venv\lib\site-packages\sqlalchemy\pool\base.py", line 716, in checkout
    rec = pool._do_get()
  File "C:\Users\Aidan Stewart\PycharmProjects\x\venv\lib\site-packages\sqlalchemy\pool\impl.py", line 148, in _do_get
    return self._pool.get(wait, self._timeout)
  File "C:\Users\Aidan Stewart\PycharmProjects\x\venv\lib\site-packages\sqlalchemy\util\queue.py", line 309, in get
    return self.get_nowait()
  File "C:\Users\Aidan Stewart\PycharmProjects\x\venv\lib\site-packages\sqlalchemy\util\queue.py", line 303, in get_nowait
    return self._queue.get_nowait()
  File "C:\Users\Aidan Stewart\PycharmProjects\x\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 1146, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "C:\Users\Aidan Stewart\PycharmProjects\x\venv\lib\site-packages\sqlalchemy\util\queue.py", line 278, in _queue
    queue = asyncio.Queue(maxsize=self.maxsize)
  File "C:\Users\Aidan Stewart\AppData\Local\Programs\Python\Python39\lib\asyncio\queues.py", line 36, in __init__
    self._loop = events.get_event_loop()
  File "C:\Users\Aidan Stewart\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'asyncio_0'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Aidan Stewart\PycharmProjects\x\venv\lib\site-packages\sanic\app.py", line 1385, in handle_request
    response = await response
  File "C:\Users\Aidan Stewart\PycharmProjects\x\py_orchestrator\blueprints\chat\view.py", line 41, in chat_collection
    await create_collection(session, files, embeddings)
  File "C:\Users\Aidan Stewart\PycharmProjects\x\py_orchestrator\common\document_service.py", line 35, in create_collection
    return await PGVector.afrom_documents(
  File "C:\Users\Aidan Stewart\PycharmProjects\x\venv\lib\site-packages\langchain_core\vectorstores.py", line 520, in afrom_documents
    return await cls.afrom_texts(texts, embedding, metadatas=metadatas, **kwargs)
  File "C:\Users\Aidan Stewart\PycharmProjects\x\venv\lib\site-packages\langchain_core\vectorstores.py", line 542, in afrom_texts
    return await run_in_executor(
  File "C:\Users\Aidan Stewart\PycharmProjects\x\venv\lib\site-packages\langchain_core\runnables\config.py", line 493, in run_in_executor
    return await asyncio.get_running_loop().run_in_executor(
  File "C:\Users\Aidan Stewart\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Aidan Stewart\PycharmProjects\x\venv\lib\site-packages\langchain_community\vectorstores\pgvector.py", line 662, in from_texts
    return cls.__from(
  File "C:\Users\Aidan Stewart\PycharmProjects\x\venv\lib\site-packages\langchain_community\vectorstores\pgvector.py", line 349, in __from
    store = cls(
  File "C:\Users\Aidan Stewart\PycharmProjects\x\venv\lib\site-packages\langchain_community\vectorstores\pgvector.py", line 212, in __init__
    self.__post_init__()
  File "C:\Users\Aidan Stewart\PycharmProjects\x\venv\lib\site-packages\langchain_community\vectorstores\pgvector.py", line 218, in __post_init__
    self.create_vector_extension()
  File "C:\Users\Aidan Stewart\PycharmProjects\x\venv\lib\site-packages\langchain_community\vectorstores\pgvector.py", line 256, in create_vector_extension
    raise Exception(f"Failed to create vector extension: {e}") from e
Exception: Failed to create vector extension: There is no current event loop in thread 'asyncio_0'.
```

### Description

When attempting to create a collection for a set of documents, I run into the error demonstrated. It appears that sqlalchemy cannot find the existing async loop created by Sanic when the server is running. Not entirely sure what the cause is nor the solution as it appears to be an internal Langchain issue when attempting to execute SQLAlchemy code in an async executor.

### System Info

aiofiles==23.2.1
aiohttp==3.9.2
aiosignal==1.3.1
aiosqlite==0.17.0
annotated-types==0.6.0
anyio==4.2.0
async-timeout==4.0.3
asyncpg==0.29.0
attrs==23.2.0
black==24.1.1
certifi==2023.11.17
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
dataclasses-json==0.6.3
distro==1.9.0
exceptiongroup==1.2.0
frozenlist==1.4.1
greenlet==3.0.3
h11==0.14.0
html5tagger==1.3.0
httpcore==1.0.2
httptools==0.6.1
httpx==0.26.0
idna==3.6
iso8601==1.1.0
jsonpatch==1.33
jsonpointer==2.4
langchain==0.1.4
langchain-community==0.0.16
langchain-core==0.1.17
langchain-openai==0.0.5
langsmith==0.0.84
marshmallow==3.20.2
multidict==6.0.4
mypy-extensions==1.0.0
numpy==1.26.3
openai==1.10.0
packaging==23.2
pathspec==0.12.1
pgvector==0.2.4
platformdirs==4.1.0
psycopg2-binary==2.9.9
pydantic==2.6.0
pydantic_core==2.16.1
pypdf==4.0.1
pypika-tortoise==0.1.6
pytz==2023.4
PyYAML==6.0.1
regex==2023.12.25
requests==2.31.0
sanic==23.12.1
sanic-routing==23.12.0
sniffio==1.3.0
SQLAlchemy==2.0.25
tenacity==8.2.3
tiktoken==0.5.2
tomli==2.0.1
tortoise-orm==0.20.0
tqdm==4.66.1
tracerite==1.1.1
typing-inspect==0.9.0
typing_extensions==4.9.0
urllib3==2.1.0
websockets==12.0
yarl==1.9.4

Windows 10
Python 3.9

**Comment by na-stewart** [comment]
PGVector.afrom_documents is an async method. Also you cannot pass kwargs into run_in_executor. Your answer is very wrong.

**Comment by na-stewart** [comment]
Rewriting the code as such

```
    loop = asyncio.get_running_loop()
    return await loop.run_in_executor(None, functools.partial(PGVector.from_documents,
                                      embedding=embeddings,
                                      documents=docs,
                                      collection_name=f"col_{col_id}",
                                      connection_string=config.CONNECTION_STRING,
                                      pre_delete_collection=True
                                      ))
```
produces the same error.

**Comment by na-stewart** [comment]
@dosu-bot

PGVector.afrom_documents is an async method and also you cannot pass kwargs into run_in_executor. Your answer is syntactially wrong but I was able to fix it by rewriting the code as such
```
    loop = asyncio.get_running_loop()
    return await loop.run_in_executor(None, functools.partial(PGVector.from_documents,
                                      embedding=embeddings,
                                      documents=docs,
                                      collection_name=f"col_{col_id}",
                                      connection_string=config.CONNECTION_STRING,
                                      pre_delete_collection=True
                                      ))
```
However the same error (There is no current event loop in thread 'asyncio_0'.) is produced.

**Comment by na-stewart** [comment]
@dosu-bot

Your solution results in same error unfortunately.

**Comment by na-stewart** [comment]
and it's out of ideas. Any assistance from a real person? Thanks.

**Comment by na-stewart** [comment]
The solution was to use psycopg instead of asyncpg
