### ISSUE TITLE
AzureSearch.semantic_hybrid_search_with_score_and_rerank not working when METADATA_FIELD not in index

### ISSUE THREAD

**Issue by solrac156** [langchain-ai/langchain#17587]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

When you instantiate an AzureSearch instance with a search type of `semantic_hybrid` and the metadata is not on the list of fields for the `fields` of the vector store or in the index, the `semantic_hybrid_search_with_score_and_rerank` method fails.

### Error Message and Stack Trace (if applicable)

```
Traceback (most recent call last):
  File "/Users/carlos/PycharmProjects/project/backend/api/app/controllers/session/send_message.py", line 76, in send_message
    response = agent({"input": prompt})
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/PycharmProjects/project/backend/api/services/agent.py", line 166, in __call__
    return self._executor.invoke(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/PycharmProjects/project/.venv/lib/python3.11/site-packages/langchain/chains/base.py", line 162, in invoke
    raise e
  File "/Users/carlos/PycharmProjects/project/.venv/lib/python3.11/site-packages/langchain/chains/base.py", line 156, in invoke
    self._call(inputs, run_manager=run_manager)
  File "/Users/carlos/PycharmProjects/project/.venv/lib/python3.11/site-packages/langchain/agents/agent.py", line 1391, in _call
    next_step_output = self._take_next_step(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/PycharmProjects/project/.venv/lib/python3.11/site-packages/langchain/agents/agent.py", line 1097, in _take_next_step
    [
  File "/Users/carlos/PycharmProjects/project/.venv/lib/python3.11/site-packages/langchain/agents/agent.py", line 1097, in <listcomp>
    [
  File "/Users/carlos/PycharmProjects/project/.venv/lib/python3.11/site-packages/langchain/agents/agent.py", line 1182, in _iter_next_step
    yield self._perform_agent_action(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/PycharmProjects/project/.venv/lib/python3.11/site-packages/langchain/agents/agent.py", line 1204, in _perform_agent_action
    observation = tool.run(
                  ^^^^^^^^^
  File "/Users/carlos/PycharmProjects/project/.venv/lib/python3.11/site-packages/langchain_core/tools.py", line 401, in run
    raise e
  File "/Users/carlos/PycharmProjects/project/.venv/lib/python3.11/site-packages/langchain_core/tools.py", line 358, in run
    self._run(*tool_args, run_manager=run_manager, **tool_kwargs)
  File "/Users/carlos/PycharmProjects/project/backend/api/services/agent.py", line 254, in _run
    docs = self.vectorstore.semantic_hybrid_search(query=query, k=4)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/PycharmProjects/project/.venv/lib/python3.11/site-packages/langchain_community/vectorstores/azuresearch.py", line 520, in semantic_hybrid_search
    docs_and_scores = self.semantic_hybrid_search_with_score_and_rerank(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/PycharmProjects/project/.venv/lib/python3.11/site-packages/langchain_community/vectorstores/azuresearch.py", line 582, in semantic_hybrid_search_with_score_and_rerank
    docs = [
           ^
  File "/Users/carlos/PycharmProjects/project/.venv/lib/python3.11/site-packages/langchain_community/vectorstores/azuresearch.py", line 606, in <listcomp>
    json.loads(result["metadata"]).get("key"),
               ~~~~~~^^^^^^^^^^^^
KeyError: 'metadata'
```

### Description

A fix was introduced in PR #15642 and the bug was re-introduced in PR #15659.

For this to work the method should look like this:
```python
    def semantic_hybrid_search_with_score_and_rerank(
        self, query: str, k: int = 4, filters: Optional[str] = None
    ) -> List[Tuple[Document, float, float]]:
        """Return docs most similar to query with an hybrid query.

        Args:
            query: Text to look up documents similar to.
            k: Number of Documents to return. Defaults to 4.

        Returns:
            List of Documents most similar to the query and score for each
        """
        from azure.search.documents.models import VectorizedQuery

        results = self.client.search(
            search_text=query,
            vector_queries=[
                VectorizedQuery(
                    vector=np.array(self.embed_query(query), dtype=np.float32).tolist(),
                    k_nearest_neighbors=k,
                    fields=FIELDS_CONTENT_VECTOR,
                )
            ],
            filter=filters,
            query_type="semantic",
            semantic_configuration_name=self.semantic_configuration_name,
            query_caption="extractive",
            query_answer="extractive",
            top=k,
        )
        # Get Semantic Answers
        semantic_answers = results.get_answers() or []
        semantic_answers_dict: Dict = {}
        for semantic_answer in semantic_answers:
            semantic_answers_dict[semantic_answer.key] = {
                "text": semantic_answer.text,
                "highlights": semantic_answer.highlights,
            }
        # Convert results to Document objects
        docs = [
            (
                Document(
                    page_content=result.pop(FIELDS_CONTENT),
                    metadata={
                        **(
                            json.loads(result[FIELDS_METADATA])
                            if FIELDS_METADATA in result
                            else {
                                k: v
                                for k, v in result.items()
                                if k != FIELDS_CONTENT_VECTOR
                            }
                        ),
                        **{
                            "captions": {
                                "text": result.get("@search.captions", [{}])[0].text,
                                "highlights": result.get("@search.captions", [{}])[
                                    0
                                ].highlights,
                            }
                            if result.get("@search.captions")
                            else {},
                            "answers": semantic_answers_dict.get(
                                json.loads(result[FIELDS_METADATA]).get("key")
                                if FIELDS_METADATA in result
                                else "",
                                "",
                            ),
                        },
                    },
                ),
                float(result["@search.score"]),
                float(result["@search.reranker_score"]),
            )
            for result in results
        ]
        return docs
```

### System Info

Python 3.11
Langchain 0.1.7

**Comment by alexmanie** [comment]
@solrac156 new PR to fix the error https://github.com/langchain-ai/langchain/pull/19502
