### ISSUE TITLE
Use of pwd in document loaders causes failure in Windows with langchain_community 0.0.20

### ISSUE THREAD

**Issue by mark-ramsey-ri** [langchain-ai/langchain#17651]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

        loader = Docx2txtLoader(filename)
        docs = loader.load()

### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "C:\Users\MarkRamsey\PycharmProjects\ri_genaipro_source\RI_GenAIPro_Data_Pipeline.py", line 57, in <module>
    from loaders_local import *
  File "C:\Users\MarkRamsey\PycharmProjects\ri_genaipro_source\loaders_local.py", line 1, in <module>
    from langchain_community.document_loaders import Docx2txtLoader
  File "C:\Users\MarkRamsey\PycharmProjects\ri_genaipro_source\.venv\Lib\site-packages\langchain_community\document_loaders\__init__.py", line 163, in <module>
    from langchain_community.document_loaders.pebblo import PebbloSafeLoader
  File "C:\Users\MarkRamsey\PycharmProjects\ri_genaipro_source\.venv\Lib\site-packages\langchain_community\document_loaders\pebblo.py", line 5, in <module>
    import pwd
ModuleNotFoundError: No module named 'pwd'

### Description

the document_loaders\pebblo.py module is using pwd which is only valid in Linux, so it fails on windows

### System Info

platform Windows 11
python 3.11.8

**Comment by smach** [comment]
Same problem. Until fixed, It would really be great to mention in the documentation that this doesn't currently work on Windows.
