### ISSUE TITLE
Error in StructuredQueryOutputParser using SelfQueryRetriever with Pinecone

### ISSUE THREAD

**Issue by darthShana** [langchain-ai/langchain#17696]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

Im using a standard SelfQueryRetriver to extract relevant documents (car listings) that match a user query. Its has been working pretty well but recently it started giving me errors (stack trace attached).
ise
`     retriever = SelfQueryRetriever.from_llm(
         llm,
         vectordb,
         document_content_description,
         metadata_field_info,
         verbose=True
     )`

### Error Message and Stack Trace (if applicable)

OutputParserException('Parsing text\n```json\n{\n    "query": "with bluetooth and a reversing camera recent",\n    "filter": "or(eq(\\"vehicle_type\\", \\"Hatchback\\"), eq(\\"vehicle_type\\", \\"Sedan\\")), in(\\"location\\", [\\"Westgate\\", \\"North Shore\\", \\"Otahuhu\\", \\"Penrose\\", \\"Botany\\", \\"Manukau\\"])"\n}\n```\n raised following error:\nUnexpected token Token(\'COMMA\', \',\') at line 1, column 65.\nExpected one of: \n\t* $END\n')Traceback (most recent call last):

  File "/home/dharshana/.local/share/virtualenvs/tina-virtual-assistant-eLldwkZS/lib/python3.11/site-packages/lark/parsers/lalr_parser_state.py", line 77, in feed_token
    action, arg = states[state][token.type]
                  ~~~~~~~~~~~~~^^^^^^^^^^^^


KeyError: 'COMMA'



During handling of the above exception, another exception occurred:



Traceback (most recent call last):


  File "/home/dharshana/.local/share/virtualenvs/tina-virtual-assistant-eLldwkZS/lib/python3.11/site-packages/langchain/chains/query_constructor/base.py", line 56, in parse
    parsed["filter"] = self.ast_parse(parsed["filter"])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


  File "/home/dharshana/.local/share/virtualenvs/tina-virtual-assistant-eLldwkZS/lib/python3.11/site-packages/lark/lark.py", line 658, in parse
    return self.parser.parse(text, start=start, on_error=on_error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


  File "/home/dharshana/.local/share/virtualenvs/tina-virtual-assistant-eLldwkZS/lib/python3.11/site-packages/lark/parser_frontends.py", line 104, in parse
    return self.parser.parse(stream, chosen_start, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


  File "/home/dharshana/.local/share/virtualenvs/tina-virtual-assistant-eLldwkZS/lib/python3.11/site-packages/lark/parsers/lalr_parser.py", line 42, in parse
    return self.parser.parse(lexer, start)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


  File "/home/dharshana/.local/share/virtualenvs/tina-virtual-assistant-eLldwkZS/lib/python3.11/site-packages/lark/parsers/lalr_parser.py", line 88, in parse
    return self.parse_from_state(parser_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


  File "/home/dharshana/.local/share/virtualenvs/tina-virtual-assistant-eLldwkZS/lib/python3.11/site-packages/lark/parsers/lalr_parser.py", line 111, in parse_from_state
    raise e


  File "/home/dharshana/.local/share/virtualenvs/tina-virtual-assistant-eLldwkZS/lib/python3.11/site-packages/lark/parsers/lalr_parser.py", line 102, in parse_from_state
    state.feed_token(token)


  File "/home/dharshana/.local/share/virtualenvs/tina-virtual-assistant-eLldwkZS/lib/python3.11/site-packages/lark/parsers/lalr_parser_state.py", line 80, in feed_token
    raise UnexpectedToken(token, expected, state=self, interactive_parser=None)


lark.exceptions.UnexpectedToken: Unexpected token Token('COMMA', ',') at line 1, column 65.
Expected one of: 
	* $END




During handling of the above exception, another exception occurred:



Traceback (most recent call last):


  File "/home/dharshana/.local/share/virtualenvs/tina-virtual-assistant-eLldwkZS/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 1246, in _call_with_config
    context.run(


  File "/home/dharshana/.local/share/virtualenvs/tina-virtual-assistant-eLldwkZS/lib/python3.11/site-packages/langchain_core/runnables/config.py", line 326, in call_func_with_variable_args
    return func(input, **kwargs)  # type: ignore[call-arg]
           ^^^^^^^^^^^^^^^^^^^^^


  File "/home/dharshana/.local/share/virtualenvs/tina-virtual-assistant-eLldwkZS/lib/python3.11/site-packages/langchain_core/output_parsers/base.py", line 168, in <lambda>
    lambda inner_input: self.parse_result(
                        ^^^^^^^^^^^^^^^^^^


  File "/home/dharshana/.local/share/virtualenvs/tina-virtual-assistant-eLldwkZS/lib/python3.11/site-packages/langchain_core/output_parsers/base.py", line 219, in parse_result
    return self.parse(result[0].text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^


  File "/home/dharshana/.local/share/virtualenvs/tina-virtual-assistant-eLldwkZS/lib/python3.11/site-packages/langchain/chains/query_constructor/base.py", line 63, in parse
    raise OutputParserException(


langchain_core.exceptions.OutputParserException: Parsing text
```json
{
    "query": "with bluetooth and a reversing camera recent",
    "filter": "or(eq(\"vehicle_type\", \"Hatchback\"), eq(\"vehicle_type\", \"Sedan\")), in(\"location\", [\"Westgate\", \"North Shore\", \"Otahuhu\", \"Penrose\", \"Botany\", \"Manukau\"])"
}
```
 raised following error:
Unexpected token Token('COMMA', ',') at line 1, column 65.
Expected one of: 
	* $END

### Description

im getting
lark.exceptions.UnexpectedToken: Unexpected token Token('COMMA', ',') at line 1, column 65.
Expected one of: 
	* $END

Seems its not happy with a COMMA.
Im not entirely sure if the cause of the error is change in the Pinecone query api or an update in langchain version



### System Info

        "langchain": {
            "hashes": [
                "sha256:29d95f12afe9690953820970205dba3b098ee1f7531e80eb18c1236d3feda921",
                "sha256:b40fbe2b65360afe6c0d5bbf37e79469f990779460640edde5b906175c49807e"
            ],
            "index": "pypi",
            "version": "==0.1.7"
        },
        "langchain-community": {
            "hashes": [
                "sha256:bd112b5813702919c50f89b1afa2b63adf1da89999df4842b327ee11220f8c39",
                "sha256:c56c48bc77d24e1fc399a9ee9a637d96e3b2ff952e3a080b5a41820d9d00fb3c"
            ],
            "index": "pypi",
            "version": "==0.0.20"
        },
        "langchain-core": {
            "hashes": [
                "sha256:34359cc8b6f8c3d45098c54a6a9b35c9f538ef58329cd943a2249d6d7b4e5806",
                "sha256:d42fac013c39a8b0bcd7e337a4cb6c17c16046c60d768f89df582ad73ec3c5cb"
            ],
            "markers": "python_full_version >= '3.8.1' and python_version < '4.0'",
            "version": "==0.1.23"
        },
        "langchain-openai": {
            "hashes": [
                "sha256:2ef040e4447a26a9d3bd45dfac9cefa00797ea58555a3d91ab4f88699eb3a005",
                "sha256:f5c4ebe46f2c8635c8f0c26cc8df27700aacafea025410e418d5a080039974dd"
            ],
            "index": "pypi",
            "version": "==0.0.6"
        },

**Comment by darthShana** [comment]
hi.. so two things 

1. i don't agree with your logical assessment of the query if This filter query checks if the vehicle_type is either "Hatchback" or "Sedan" and if the location is in the list ["Westgate", "North Shore", "Otahuhu", "Penrose", "Botany", "Manukau"]. then the query should be
and(
  or(
    eq(\"vehicle_type\", \"Hatchback\"), 
    eq(\"vehicle_type\", \"Sedan\")
  ), 
  in(\"location\", [\"Westgate\", \"North Shore\", \"Otahuhu\", \"Penrose\", \"Botany\", \"Manukau\"])
)"
note () specifying the operators to which the or operator should apply

2. As im using a SelfQueryRetriver i didnt write this query. Should'nt the langchain prompts be asking the llm to construct the query in the correct syntax? btw im using  model="gpt-4-turbo-preview"

**Comment by colajoy** [comment]
> hi.. so two things
> 
> 1. i don't agree with your logical assessment of the query if This filter query checks if the vehicle_type is either "Hatchback" or "Sedan" and if the location is in the list ["Westgate", "North Shore", "Otahuhu", "Penrose", "Botany", "Manukau"]. then the query should be
>    and(
>    or(
>    eq("vehicle_type", "Hatchback"),
>    eq("vehicle_type", "Sedan")
>    ),
>    in("location", ["Westgate", "North Shore", "Otahuhu", "Penrose", "Botany", "Manukau"])
>    )"
>    note () specifying the operators to which the or operator should apply
> 2. As im using a SelfQueryRetriver i didnt write this query. Should'nt the langchain prompts be asking the llm to construct the query in the correct syntax? btw im using  model="gpt-4-turbo-preview"

Hello brother, I have encountered the same problem. Have you resolved it
