### ISSUE TITLE
langchain serve TypeError: Type is not JSON serializable: ModelMetaclass

### ISSUE THREAD

**Issue by 1100111GTH** [langchain-ai/langchain#17700]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```
# Self file
import os
import sys
current_dir = os.path.dirname(os.path.abspath(__file__))  # 获取当前文件的绝对路径
parent_dir = os.path.dirname(current_dir)  # 获取父目录的路径
sys.path.append(parent_dir)  # 把父目录添加到 sys.path
from packages.core.api_invoke import return_mode_choose, base_answer, database_answer, database_answer_nolimit, clean_history, better_query
# Basic
from fastapi import FastAPI
from fastapi.responses import RedirectResponse
from langserve import add_routes


app = FastAPI(
    title="XiaoGuangLLM", 
    version="1.2.0"
)

add_routes(
    app, 
    return_mode_choose, 
    path="/return_mode_choose", 
    disabled_endpoints=["playground"]
)
add_routes(
    app, 
    base_answer, 
    path="/base_answer", 
    disabled_endpoints=["playground"]
)
add_routes(
    app, 
    database_answer, 
    path="/database_answer", 
    disabled_endpoints=["playground"]
)
add_routes(
    app, 
    database_answer_nolimit, 
    path="/database_answer_nolimit", 
    disabled_endpoints=["playground"]
)
add_routes(
    app, 
    clean_history, 
    path="/clean_history", 
    disabled_endpoints=["playground"]
)
add_routes(
    app, 
    better_query, 
    path="/better_query", 
    disabled_endpoints=["playground"]
)

@app.get("/")
async def redirect_root_to_docs():
    return RedirectResponse("/docs")

if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8000)
```

### Error Message and Stack Trace (if applicable)

```
INFO:     123.185.63.166:0 - "POST /base_answer/invoke HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
RuntimeError: super(): __class__ cell not found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/langserve/server.py", line 464, in invoke
    return await api_handler.invoke(request)
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/langserve/api_handler.py", line 720, in invoke
    output=self._serializer.dumpd(output),
  File "/root/miniconda3/envs/xg/lib/python3.9/site-packages/langserve/serialization.py", line 164, in dumpd
    return orjson.loads(orjson.dumps(obj, default=default))
TypeError: Type is not JSON serializable: ModelMetaclass
```

### Description

is anyone knows how to fix this?

### System Info

ubuntu 20.4 LTS

**Comment by 1100111GTH** [comment]
> _🤖_
> 
> Hey there @1100111GTH! 👋 Great to see you back with us. Diving into this intriguing issue of yours - hang tight, I'll get back to you with something solid soon! 🛠️😉

hope you can help me

**Comment by 1100111GTH** [comment]
> _🤖_
> 
> 该错误消息`TypeError: Type is not JSON serializable: ModelMetaclass`表明您正在尝试序列化不可 JSON 序列化的 Python 对象。在 LangChain 的上下文中，当您尝试将`BaseLanguageModel`或`BaseTool`（或其任何子类）的实例传递给`create_json_chat_agent`函数，然后尝试将生成的代理序列化为 JSON 时，可能会发生这种情况。
> 
> 要解决此问题，您应该确保您没有尝试序列化代理本身。相反，您应该只序列化代理方法的输出`invoke`，该输出应该是 JSON 可序列化字典。
> 
> 以下是如何调用代理并尝试序列化输出的示例：
> 
> ```python
> from langchain import hub
> from langchain_community.chat_models import ChatOpenAI
> from langchain.agents import AgentExecutor, create_json_chat_agent
> import json
> 
> prompt = hub.pull("hwchase17/react-chat-json")
> model = ChatOpenAI()
> tools = ...
> 
> agent = create_json_chat_agent(model, tools, prompt)
> agent_executor = AgentExecutor(agent=agent, tools=tools)
> 
> result = agent_executor.invoke({"input": "hi"})
> 
> # This is where the error might be happening
> json.dumps(result)  # This should work if `result` is a dictionary
> ```
> 
> 如果在确保仅尝试序列化代理`invoke`方法的输出后仍然遇到错误，则问题可能出在方法`invoke`本身的输出上。在这种情况下，您可能需要修改该类`JSONAgentOutputParser`以确保它仅返回 JSON 可序列化数据。
> 
> `ModelMetaclass`至于导致错误的结构`TypeError: Type is not JSON serializable`，我无法在 LangChain 存储库中找到具体信息。有可能是在or`ModelMetaclass`的定义中使用的元类，但如果没有更多信息，很难确定。如果您能提供有关消息来源的更多详细信息，我也许能够提供更准确的答案。`BaseLanguageModel``BaseTool``ModelMetaclass`
> 
> 您可以在[LangChain 存储库](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/agents/json_chat/base.py)中找到有关该`create_json_chat_agent`函数和类的更多信息。`JSONAgentOutputParser`[](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/agents/json_chat/base.py)
> 
> ## 来源
> * [libs/langchain/langchain/agents/json_chat/base.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/agents/json_chat/base.py)
> 
> #### 关于多苏
> 此回复旨在有用并节省您的时间。它并不是**一个精确的解决方案**，而是您自己研究的起点。
> 
> 帮助我变得更有用！如果这有帮助，请留下 👍；如果不相关，请留下 👎。
> 
> 如果您想继续对话，请以以下方式开始回复@dosu-bot。

i

**Comment by 1100111GTH** [comment]
> _🤖_
> 
> The error message `TypeError: Type is not JSON serializable: ModelMetaclass` suggests that you're trying to serialize a Python object that is not JSON serializable. In the context of LangChain, this could be happening when you're trying to pass an instance of `BaseLanguageModel` or `BaseTool` (or any of their subclasses) to the `create_json_chat_agent` function, and then trying to serialize the resulting agent to JSON.
> 
> To resolve this issue, you should ensure that you're not trying to serialize the agent itself. Instead, you should only serialize the output of the agent's `invoke` method, which should be a JSON serializable dictionary.
> 
> Here's an example of how you might be invoking the agent and trying to serialize the output:
> 
> ```python
> from langchain import hub
> from langchain_community.chat_models import ChatOpenAI
> from langchain.agents import AgentExecutor, create_json_chat_agent
> import json
> 
> prompt = hub.pull("hwchase17/react-chat-json")
> model = ChatOpenAI()
> tools = ...
> 
> agent = create_json_chat_agent(model, tools, prompt)
> agent_executor = AgentExecutor(agent=agent, tools=tools)
> 
> result = agent_executor.invoke({"input": "hi"})
> 
> # This is where the error might be happening
> json.dumps(result)  # This should work if `result` is a dictionary
> ```
> 
> If you're still encountering the error after ensuring that you're only trying to serialize the output of the agent's `invoke` method, then the issue might be with the output of the `invoke` method itself. In that case, you might need to modify the `JSONAgentOutputParser` class to ensure that it only returns JSON serializable data.
> 
> As for the structure of the `ModelMetaclass` that is causing the `TypeError: Type is not JSON serializable` error, I wasn't able to find specific information within the LangChain repository. It's possible that the `ModelMetaclass` is a metaclass used in the definition of `BaseLanguageModel` or `BaseTool`, but without more information, it's hard to say for sure. If you could provide more details about where the `ModelMetaclass` is coming from, I might be able to provide a more accurate answer.
> 
> You can find more information about the `create_json_chat_agent` function and the `JSONAgentOutputParser` class in the [LangChain repository](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/agents/json_chat/base.py).
> 
> ## Sources
> * [libs/langchain/langchain/agents/json_chat/base.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/agents/json_chat/base.py)
> 
> #### About Dosu
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

I don't even know the object is... just try to find what's wrong with my own code

**Comment by 1100111GTH** [comment]
> _🤖_
> 
> The error message `TypeError: Type is not JSON serializable: ModelMetaclass` suggests that you're trying to serialize a Python object that is not JSON serializable. In the context of LangChain, this could be happening when you're trying to pass an instance of `BaseLanguageModel` or `BaseTool` (or any of their subclasses) to the `create_json_chat_agent` function, and then trying to serialize the resulting agent to JSON.
> 
> To resolve this issue, you should ensure that you're not trying to serialize the agent itself. Instead, you should only serialize the output of the agent's `invoke` method, which should be a JSON serializable dictionary.
> 
> Here's an example of how you might be invoking the agent and trying to serialize the output:
> 
> ```python
> from langchain import hub
> from langchain_community.chat_models import ChatOpenAI
> from langchain.agents import AgentExecutor, create_json_chat_agent
> import json
> 
> prompt = hub.pull("hwchase17/react-chat-json")
> model = ChatOpenAI()
> tools = ...
> 
> agent = create_json_chat_agent(model, tools, prompt)
> agent_executor = AgentExecutor(agent=agent, tools=tools)
> 
> result = agent_executor.invoke({"input": "hi"})
> 
> # This is where the error might be happening
> json.dumps(result)  # This should work if `result` is a dictionary
> ```
> 
> If you're still encountering the error after ensuring that you're only trying to serialize the output of the agent's `invoke` method, then the issue might be with the output of the `invoke` method itself. In that case, you might need to modify the `JSONAgentOutputParser` class to ensure that it only returns JSON serializable data.
> 
> As for the structure of the `ModelMetaclass` that is causing the `TypeError: Type is not JSON serializable` error, I wasn't able to find specific information within the LangChain repository. It's possible that the `ModelMetaclass` is a metaclass used in the definition of `BaseLanguageModel` or `BaseTool`, but without more information, it's hard to say for sure. If you could provide more details about where the `ModelMetaclass` is coming from, I might be able to provide a more accurate answer.
> 
> You can find more information about the `create_json_chat_agent` function and the `JSONAgentOutputParser` class in the [LangChain repository](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/agents/json_chat/base.py).
> 
> ## Sources
> * [libs/langchain/langchain/agents/json_chat/base.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/agents/json_chat/base.py)
> 
> #### About Dosu
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

you try to tell me edit source code of langchain?

**Comment by 1100111GTH** [comment]
> _🤖_
> 
> The error you're encountering, `TypeError: Type is not JSON serializable: ModelMetaclass`, is likely due to an attempt to serialize a Pydantic model class (which is an instance of `ModelMetaclass`) into JSON. This is happening when the LangChain framework is trying to serialize the output of your language model.
> 
> The error occurs in the `invoke` method of the `APIHandler` class in the `langserve/api_handler.py` file, specifically at this line:
> 
> ```python
> output=self._serializer.dumpd(output),
> ```
> 
> Here, `self._serializer` is an instance of the `Serializer` class from `langserve/serialization.py`, and `dumpd` is a method that serializes a Python object into a JSON string. The `output` object that's being passed to `dumpd` seems to be an instance of `ModelMetaclass`, which is not JSON serializable.
> 
> To fix this issue, you need to ensure that the `output` object is JSON serializable before it's passed to `dumpd`. If `output` is a Pydantic model, you can convert it into a dictionary using its `dict()` method, which will make it JSON serializable. Here's an example of how you can do this:
> 
> ```python
> if isinstance(output, ModelMetaclass):
>     output = output.dict()
> output=self._serializer.dumpd(output),
> ```
> 
> This code checks if `output` is an instance of `ModelMetaclass`, and if it is, it converts it into a dictionary before passing it to `dumpd`.
> 
> However, without more information about the `base_answer` object and its related code, it's hard to provide a more specific solution. Could you provide more details about the `base_answer` object and the code that's causing the error?
> 
> As for the `add_routes` function, I'm sorry but I couldn't find any information about it in the LangChain repository. It seems to be a function from your own code or from another library you're using. Could you provide more information about this function and where it's defined? This would help me understand your code better and provide a more accurate solution.
> 
> For more information about the `Serializer` class and the `dumpd` method, you can check the `langserve/serialization.py` file in the LangChain repository. For more information about Pydantic models and the `dict()` method, you can check the [Pydantic documentation](https://pydantic-docs.helpmanual.io/).
> 
> I hope this helps! If you have any more questions or need further clarification, feel free to ask.
> 
> ## Sources
> * [libs/langchain/langchain/output_parsers/pydantic.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/output_parsers/pydantic.py)
> 
> #### About Dosu

```
llm = ChatOpenAI(
    api_key="EMPTY", 
    base_url="http://127.0.0.1:8000/v1", 
    temperature=read_persist_var("temperature"), 
    max_tokens=read_persist_var("max_tokens"),  
    model="qwen-14b-chat"
)
prompt_0 = ChatPromptTemplate.from_messages(
    [
        ("system", f"{read_persist_var('system_prompt')}"), 
        MessagesPlaceholder(variable_name="history"),
        ("human", "{input}")
        ]
)
@chain
def base_answer(Any) -> Any:
    RunnableWithMessageHistory(
        prompt_0 | llm,
        RedisChatMessageHistory,
        input_messages_key="input",
        history_messages_key="history",
    ) | StrOutputParser()
    return RunnableWithMessageHistory
```

This is my code of base_answer

**Comment by 1100111GTH** [comment]
> _🤖_
> 
> 您遇到的错误消息`TypeError: Type is not JSON serializable: ModelMetaclass`表明 LangChain 框架正在尝试序列化不可序列化为 JSON 的类的对象。`json`发生这种情况的原因可能是，您的语言模型的输出或其某些部分是 Python模块不知道如何转换为 JSON 兼容格式的类的实例。
> 
> 查看您的代码，该对象似乎`RunnableWithMessageHistory`可能是问题的原因。该类`RunnableWithMessageHistory`不可 JSON 序列化，并且您似乎正在尝试从函数返回此类的实例`base_answer`。
> 
> 您应该返回类的实例，而不是`RunnableWithMessageHistory`返回类本身。以下是修改`base_answer`函数的方法：
> 
> ```python
> @chain
> def base_answer(input: Any) -> Any:
>     runnable = RunnableWithMessageHistory(
>         prompt_0 | llm,
>         RedisChatMessageHistory,
>         input_messages_key="input",
>         history_messages_key="history",
>     )
>     return runnable(input) | StrOutputParser()
> ```
> 
> 在此修改版本中，`runnable(input)`使用`RunnableWithMessageHistory`输入调用实例，然后由 解析输出`StrOutputParser()`。这应该返回一个 JSON 可序列化对象，它应该可以解决`TypeError`您遇到的问题。
> 
> 请尝试此修改，如果它解决了您的问题或者您遇到任何其他问题，请告诉我。
> 
> ## 来源
> * [libs/langchain/langchain/schema/runnable/router.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/schema/runnable/router.py)
> 
> #### 关于多苏

thanks for your answer, that fix my problems, bu there is another bug shows up, can you help look at it?
`ValueError: Missing keys ['session_id'] in config['configurable'] Expected keys are ['session_id'].When using via .invoke() or .stream(), pass in a config; e.g., chain.invoke({'input': 'foo'}, {'configurable': {'session_id': '[your-value-here]'}})`
my code is `base_answer.invoke({"input": "我该如何称呼你"}, config={"configurable": {"session_id": "a"}})`. i already use session_id, bu the bug show me not pass

**Comment by 1100111GTH** [comment]
> _🤖_
> 
> The error message you're encountering, `TypeError: Type is not JSON serializable: ModelMetaclass`, suggests that the LangChain framework is trying to serialize an object of a class that is not serializable to JSON. This is likely happening because the output of your language model, or some part of it, is an instance of a class that Python's `json` module doesn't know how to convert to a JSON-compatible format.
> 
> Looking at your code, it seems like the `RunnableWithMessageHistory` object might be the cause of the issue. The `RunnableWithMessageHistory` class is not JSON serializable, and it seems like you're trying to return an instance of this class from your `base_answer` function.
> 
> Instead of returning the `RunnableWithMessageHistory` class itself, you should return an instance of it. Here's how you can modify your `base_answer` function:
> 
> ```python
> @chain
> def base_answer(input: Any) -> Any:
>     runnable = RunnableWithMessageHistory(
>         prompt_0 | llm,
>         RedisChatMessageHistory,
>         input_messages_key="input",
>         history_messages_key="history",
>     )
>     return runnable(input) | StrOutputParser()
> ```
> 
> In this modified version, `runnable(input)` invokes the `RunnableWithMessageHistory` instance with the input, and the output is then parsed by `StrOutputParser()`. This should return a JSON serializable object, which should resolve the `TypeError` you're encountering.
> 
> Please try this modification and let me know if it resolves your issue or if you encounter any other problems.
> 
> ## Sources
> * [libs/langchain/langchain/schema/runnable/router.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/schema/runnable/router.py)
> 
> #### About Dosu


thanks for your answer, that fix my problems, bu there is another bug shows up, can you help look at it?
`ValueError: Missing keys ['session_id'] in config['configurable'] Expected keys are ['session_id'].When using via .invoke() or .stream(), pass in a config; e.g., chain.invoke({'input': 'foo'}, {'configurable': {'session_id': '[your-value-here]'}})`
my code is `base_answer.invoke({"input": "我该如何称呼你"}, config={"configurable": {"session_id": "a"}})`. i already use session_id, bu the bug show me not pass
