### ISSUE TITLE
ChatZhipuAI invoke error

### ISSUE THREAD

**Issue by yskgood** [langchain-ai/langchain#17863]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

When I was testing with the ChatZhipuAI provided by the official documentation, an AttributeError occurred: module 'zhipuai' has no attribute 'model_api'. The documentation URL is：https://python.langchain.com/docs/integrations/chat/zhipuai
```
from langchain_community.chat_models import ChatZhipuAI
from langchain_core.messages import AIMessage, HumanMessage, SystemMessage

chat = ChatZhipuAI(
    temperature=0.5,
    api_key="my key***",
    model="chatglm_turbo",
)

messages = [
    AIMessage(content="Hi."),
    SystemMessage(content="Your role is a poet."),
    HumanMessage(content="Write a short poem about AI in four lines."),
]

response = chat(messages)
print(response.content)
```

### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "/Users/ysk/Library/Mobile Documents/com~apple~CloudDocs/langchain/zhipu/simple.py", line 17, in <module>
    response = chat(messages)
  File "/Users/ysk/anaconda3/envs/langchain/lib/python3.10/site-packages/langchain_core/_api/deprecation.py", line 145, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/ysk/anaconda3/envs/langchain/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 691, in __call__
    generation = self.generate(
  File "/Users/ysk/anaconda3/envs/langchain/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 408, in generate
    raise e
  File "/Users/ysk/anaconda3/envs/langchain/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 398, in generate
    self._generate_with_cache(
  File "/Users/ysk/anaconda3/envs/langchain/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 577, in _generate_with_cache
    return self._generate(
  File "/Users/ysk/anaconda3/envs/langchain/lib/python3.10/site-packages/langchain_community/chat_models/zhipuai.py", line 265, in _generate
    response = self.invoke(prompt)
  File "/Users/ysk/anaconda3/envs/langchain/lib/python3.10/site-packages/langchain_community/chat_models/zhipuai.py", line 183, in invoke
    return self.zhipuai.model_api.invoke(
AttributeError: module 'zhipuai' has no attribute 'model_api'

### Description

 I was testing with the ChatZhipuAI provided by the official documentation

### System Info

langchain==0.1.8
langchain-community==0.0.21
langchain-core==0.1.24
langchain-openai==0.0.6
langchainhub==0.1.14
platform mac
python 3.10

**Comment by liugddx** [comment]
Maybe you need upgrade zhipuai

**Comment by BinNong** [comment]
I just encountered the same problem, and I have also upgraded `zhipuai`, but it doesn't work.

**Comment by BinNong** [comment]
> I just encountered the same problem, and I have also upgraded `zhipuai`, but it doesn't work.

I have found the reason.  The original official Python SDK from ZHIPU AI has transferred to [zhipuai-sdk-python-v4](https://github.com/zhipuai/zhipuai-sdk-python-v4).

**Comment by icexun** [comment]
Do you know how to fix it? I got the same problem.

**Comment by liugddx** [comment]
> it

I‘ll handle it.

**Comment by ChanForWang** [comment]
I encountered the same issue, how to fix it??

**Comment by 1137882300** [comment]
I encountered the same issue, how to fix it??

**Comment by liugddx** [comment]
Check this #16695
