### ISSUE TITLE
community: [MongoDBAtlasVectorSearch] Fix KeyError 'embedding' when using MMR

### ISSUE THREAD

**Issue by certified-dodo** [langchain-ai/langchain#17963]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code
```python
# test.py
from langchain_openai import OpenAIEmbeddings
from langchain_community.vectorstores.mongodb_atlas import MongoDBAtlasVectorSearch

embeddings = OpenAIEmbeddings()

MONGO_CONNECTION_URI = "mongo uri"
VECTORS_DB_NAME = "db name"
VECTOR_SEARCH_INDEX_NAME = "index name"

db = MongoDBAtlasVectorSearch.from_connection_string(
    MONGO_CONNECTION_URI,
    VECTORS_DB_NAME,
    embeddings,
    index_name=VECTOR_SEARCH_INDEX_NAME,
)

db_query = "Find info related to ..."
num_of_db_results = 10

raw_contexts = db.max_marginal_relevance_search(query=db_query, k=num_of_db_results, lambda_mult=0)
```

### Error Message and Stack Trace (if applicable)

```cmd
Traceback (most recent call last):
  File ".../test.py", line 39, in <module>
    raw_contexts = db.max_marginal_relevance_search(query=db_query, k=num_of_db_results, lambda_mult=0)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.12/site-packages/langchain_community/vectorstores/mongodb_atlas.py", line 325, in max_marginal_relevance_search
    [doc.metadata[self._embedding_key] for doc, _ in docs],
     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: 'embedding'
```

### Description
* Error when using MMR (max marginal relevance) search. This includes
  - calling. `max_marginal_relevance_search` directly
  - using `db.as_retriever(search_type="mmr")`
* `self._embedding_key` is deleted from `docs` in `_similarity_search_with_score`
https://github.com/langchain-ai/langchain/blob/f6e3aa9770e32216954c3e0f2fa6825e5d89bd75/libs/community/langchain_community/vectorstores/mongodb_atlas.py#L212
the following method `maximal_marginal_relevance` tries to access the deleted field resulting in an error
https://github.com/langchain-ai/langchain/blob/f6e3aa9770e32216954c3e0f2fa6825e5d89bd75/libs/community/langchain_community/vectorstores/mongodb_atlas.py#L325

Expectation
* MMR option working with no error

### System Info

Python 
`v3.12.0`

requirements.txt
```
langchain==0.1.8
langchain-community==0.0.21
langchain-core==0.1.25
langchain-openai==0.0.5
langsmith==0.1.5
openai==1.11.1
```

**Comment by certified-dodo** [comment]
https://github.com/langchain-ai/langchain/pull/17971
