### ISSUE TITLE
raise AttributeError(name) from None  AttributeError: C

### ISSUE THREAD

**Issue by Khan-Tzar** [langchain-ai/langchain#18076]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

from langchain_community.document_loaders import UnstructuredWordDocumentLoader

### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "/home/imxsys/flask-ui/prototypes/LangChainProto/./deeplake_vector_docxi.py", line 2, in <module>
    from langchain_community.document_loaders import UnstructuredWordDocumentLoader
  File "/home/imxsys/.local/lib/python3.11/site-packages/langchain_community/document_loaders/__init__.py", line 53, in <module>
    from langchain_community.document_loaders.blackboard import BlackboardLoader
  File "/home/imxsys/.local/lib/python3.11/site-packages/langchain_community/document_loaders/blackboard.py", line 10, in <module>
    from langchain_community.document_loaders.pdf import PyPDFLoader
  File "/home/imxsys/.local/lib/python3.11/site-packages/langchain_community/document_loaders/pdf.py", line 18, in <module>
    from langchain_community.document_loaders.parsers.pdf import (
  File "/home/imxsys/.local/lib/python3.11/site-packages/langchain_community/document_loaders/parsers/__init__.py", line 8, in <module>
    from langchain_community.document_loaders.parsers.language import LanguageParser
  File "/home/imxsys/.local/lib/python3.11/site-packages/langchain_community/document_loaders/parsers/language/__init__.py", line 1, in <module>
    from langchain_community.document_loaders.parsers.language.language_parser import (
  File "/home/imxsys/.local/lib/python3.11/site-packages/langchain_community/document_loaders/parsers/language/language_parser.py", line 39, in <module>
    "c": Language.C,
         ^^^^^^^^^^
  File "/usr/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: C

### Description

I can't include UnstructuredWordDocumentLoader from langchain_community.document_loaders

### System Info

pip3.11 list | grep langch
langchain                                0.1.7
langchain-community                      0.0.21
langchain-core                           0.1.26
langchain-google-vertexai                0.0.5
langchain-openai                         0.0.6

**Comment by Khan-Tzar** [comment]
I succeed to fix my trouble as update up to langchain-0.1.9
