### ISSUE TITLE
TypeError: object Run can't be used in 'await' expression

### ISSUE THREAD

**Issue by RicardoRobledo** [langchain-ai/langchain#18337]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
@classmethod
    async def run_message(cls, text, thread_id):
        """
        Put a message in our conversation thread

        :param thread: and int that contain our thread identifier
        :param text: message
        """

        # Error in 'await'
        msg = await OpenAIAssistantRunnable(assistant_id=settings.ASSISTANT_ID, as_agent=True).ainvoke({
            "content": text,
            "thread_id": thread_id
        })

        return msg.return_values["output"]
```

### Error Message and Stack Trace (if applicable)

```
Traceback (most recent call last):
  File "C:\Users\Kyo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyo\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 277, in __call__
    return call_result.result()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyo\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyo\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\RSSpe\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 353, in main_wrap
    result = await self.awaitable(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 60, in _view_wrapper
    return await view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyo\AppData\Local\Programs\Python\Python311\Lib\site-packages\adrf\views.py", line 77, in async_dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyo\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Kyo\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Kyo\AppData\Local\Programs\Python\Python311\Lib\site-packages\adrf\views.py", line 70, in async_dispatch
    response = await handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyo\AppData\Local\Programs\Python\Python311\Lib\site-packages\adrf\decorators.py", line 50, in handler
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyo\Desktop\chatbot-django-capacitacion-ventas\apps\chatbot\views\openai_views.py", line 86, in post_message
    text = await openairep.post_user_message(text, thread_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyo\Desktop\chatbot-django-capacitacion-ventas\apps\chatbot\repositories\openai_repository.py", line 18, in post_user_message
    response = await OpenAISingleton.add_message(text, thread)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyo\Desktop\chatbot-django-capacitacion-ventas\apps\chatbot\desing_patterns\creational_patterns\singleton\openai_singleton.py", line 134, in add_message
    msg = await OpenAIAssistantRunnable(assistant_id=settings.ASSISTANT_ID, as_agent=True).ainvoke({
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyo\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\agents\openai_assistant\base.py", line 418, in ainvoke
    raise e
  File "C:\Users\Kyo\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\agents\openai_assistant\base.py", line 408, in ainvoke
    run = await self._create_run(input)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object Run can't be used in 'await' expression
```

### Description

Some days ago I was using OpenAIAssistantRunnable with await for async, but now I can´t use it. If call it without an 'await' expression I get a coroutine.

### System Info

```
langchain==0.1.3
langchain-community==0.0.15
langchain-core==0.1.15
langchain-openai==0.0.3
langcodes==3.3.0
langsmith==0.0.83
openai==1.9.0
Django==5.0.2
djangorestframework==3.14.0
```

Python version: 3.11.6

**Comment by RicardoRobledo** [comment]
My langchain version is 0.1.9, I forgot change it.

**Comment by Mitesh-Celigo** [comment]
Getting same error, also using 0.1.9.

**Comment by olegoleg1111121** [comment]
`Traceback (most recent call last):
  File "C:\Users\oleg\AppData\Local\Programs\Python\Python39\lib\site-packages\openai\_base_client.py", line 1457, in _request
    response = await self._client.send(
TypeError: object Response can't be used in 'await' expression`
OpenAI v1.13.3
`async def _request(
        self,
        cast_to: Type[ResponseT],
        options: FinalRequestOptions,
        *,
        stream: bool,
        stream_cls: type[_AsyncStreamT] | None,
        remaining_retries: int | None,
    ) -> ResponseT | _AsyncStreamT:
        cast_to = self._maybe_override_cast_to(cast_to, options)
        await self._prepare_options(options)

        retries = self._remaining_retries(remaining_retries, options)
        request = self._build_request(options)
        await self._prepare_request(request)

        kwargs: HttpxSendArgs = {}
        if self.custom_auth is not None:
            kwargs["auth"] = self.custom_auth

        try:
            response = await self._client.send(
                request,
                stream=stream or self._should_stream_response_body(request=request),
                **kwargs,
            )
        except httpx.TimeoutException as err:
            log.debug("Encountered httpx.TimeoutException", exc_info=True)

            if retries > 0:
                return await self._retry_request(
                    options,
                    cast_to,
                    retries,
                    stream=stream,
                    stream_cls=stream_cls,
                    response_headers=None,
                )

            log.debug("Raising timeout error")
            raise APITimeoutError(request=request) from err
        except Exception as err:
            log.debug("Encountered Exception", exc_info=True)

            if retries > 0:
                return await self._retry_request(
                    options,
                    cast_to,
                    retries,
                    stream=stream,
                    stream_cls=stream_cls,
                    response_headers=None,
                )
`

**Comment by shbfy** [comment]
> I my case it looks OpenAIAssistantRunnable: ainvoke () implementation is not using async counterparts of helpers, not sure if this is intentional. It worked for me after changing them.

Please could you consider adding the fix here or raising a PR with the fix? :)

**Comment by Mitesh-Celigo** [comment]
Hi, @shbfy , seems this [PR](https://github.com/langchain-ai/langchain/pull/21378) is fixing it.
