### ISSUE TITLE
missing ScriptRunContext

### ISSUE THREAD

**Issue by AtomAsking** [langchain-ai/langchain#18684]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from __future__ import annotations

import typing as t

import streamlit as st
from langchain.callbacks.base import BaseCallbackHandler
from langchain_community.chat_message_histories import StreamlitChatMessageHistory
from langchain_core.messages import AIMessage
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.runnables.history import RunnableWithMessageHistory
from langchain_openai import AzureChatOpenAI


class StreamHandler(BaseCallbackHandler):
    def __init__(
        self,
        container,
        initial_text: str = "",
    ) -> None:
        self.container = container
        self.text = initial_text

    def on_llm_start(
        self,
        serialized: t.Dict[str, t.Any],
        prompts: t.List[str],
        **kwargs: t.Any,
    ) -> t.Any:
        formatted_prompts = "\n".join(prompts)
        print(f"Prompt:\n{formatted_prompts}")

    def on_llm_new_token(
        self,
        token: str,
        **kwargs,
    ) -> None:
        self.text += token
        self.container.markdown(self.text + "▌")

    def on_llm_end(
        self,
        response,
        **kwargs,
    ) -> None:
        self.container.markdown(self.text)
        st.toast("Ready!", icon="🥞")


memory = StreamlitChatMessageHistory(key="langchain_messages")

if len(memory.messages) == 0:
    memory.clear()
    memory.add_message(AIMessage("How can I help you?"))

prompt = ChatPromptTemplate.from_messages(
    [
        ("system", ""),
        MessagesPlaceholder(variable_name="history"),
        ("human", "{input}"),
    ],
)

llm = AzureChatOpenAI(
    azure_endpoint="https://foo.openai.azure.com/",
    deployment_name="GPT-4-NEW",
    openai_api_version="2024-02-15-preview",
    openai_api_key="bar",
    streaming=True,
)

chain = prompt | llm

chain_with_history = RunnableWithMessageHistory(
    chain,
    lambda session_id: memory,
    input_messages_key="input",
    history_messages_key="history",
)

for msg in memory.messages:
    st.chat_message(msg.type).write(msg.content)

if user_input := st.chat_input():
    st.chat_message("human").write(user_input)

    with st.chat_message("ai"):
        stream_handler = StreamHandler(st.empty())
        chain_with_history.invoke(
            {"input": user_input},
            config={
                "callbacks": [stream_handler],
                "configurable": {"session_id": "any"},
            },
        )
```

### Error Message and Stack Trace (if applicable)

```
2024-03-07 01:23:00.591 Thread 'ThreadPoolExecutor-1_0': missing ScriptRunContext
2024-03-07 01:23:00.592 Uncaught app exception
Traceback (most recent call last):
  File "/Users/qux/.venv/lib/python3.10/site-packages/streamlit/runtime/state/session_state.py", line 398, in __getitem__
    return self._getitem(widget_id, key)
  File "/Users/qux/.venv/lib/python3.10/site-packages/streamlit/runtime/state/session_state.py", line 443, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/qux/.venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/Users/qux/demo.py", line 88, in <module>
    chain_with_history.invoke(
  File "/Users/qux/.venv/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 4069, in invoke
    return self.bound.invoke(
  File "/Users/qux/.venv/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 4069, in invoke
    return self.bound.invoke(
  File "/Users/qux/.venv/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2075, in invoke
    input = step.invoke(
  File "/Users/qux/.venv/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 4069, in invoke
    return self.bound.invoke(
  File "/Users/qux/.venv/lib/python3.10/site-packages/langchain_core/runnables/passthrough.py", line 419, in invoke
    return self._call_with_config(self._invoke, input, config, **kwargs)
  File "/Users/qux/.venv/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1262, in _call_with_config
    context.run(
  File "/Users/qux/.venv/lib/python3.10/site-packages/langchain_core/runnables/config.py", line 326, in call_func_with_variable_args
    return func(input, **kwargs)  # type: ignore[call-arg]
  File "/Users/qux/.venv/lib/python3.10/site-packages/langchain_core/runnables/passthrough.py", line 406, in _invoke
    **self.mapper.invoke(
  File "/Users/qux/.venv/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2712, in invoke
    output = {key: future.result() for key, future in zip(steps, futures)}
  File "/Users/qux/.venv/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2712, in <dictcomp>
    output = {key: future.result() for key, future in zip(steps, futures)}
  File "/Users/jenrey/.pyenv/versions/3.10.12/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/Users/jenrey/.pyenv/versions/3.10.12/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/jenrey/.pyenv/versions/3.10.12/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/qux/.venv/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 4069, in invoke
    return self.bound.invoke(
  File "/Users/qux/.venv/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 3523, in invoke
    return self._call_with_config(
  File "/Users/qux/.venv/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1262, in _call_with_config
    context.run(
  File "/Users/qux/.venv/lib/python3.10/site-packages/langchain_core/runnables/config.py", line 326, in call_func_with_variable_args
    return func(input, **kwargs)  # type: ignore[call-arg]
  File "/Users/qux/.venv/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 3397, in _invoke
    output = call_func_with_variable_args(
  File "/Users/qux/.venv/lib/python3.10/site-packages/langchain_core/runnables/config.py", line 326, in call_func_with_variable_args
    return func(input, **kwargs)  # type: ignore[call-arg]
  File "/Users/qux/.venv/lib/python3.10/site-packages/langchain_core/runnables/history.py", line 409, in _enter_history
    return hist.messages.copy()
  File "/Users/qux/.venv/lib/python3.10/site-packages/langchain_community/chat_message_histories/streamlit.py", line 32, in messages
    return st.session_state[self._key]
  File "/Users/qux/.venv/lib/python3.10/site-packages/streamlit/runtime/state/session_state_proxy.py", line 90, in __getitem__
    return get_session_state()[key]
  File "/Users/qux/.venv/lib/python3.10/site-packages/streamlit/runtime/state/safe_session_state.py", line 91, in __getitem__
    return self._state[key]
  File "/Users/qux/.venv/lib/python3.10/site-packages/streamlit/runtime/state/session_state.py", line 400, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "langchain_messages". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization'
```

### Description

* I use `streamlit` for front-end page rendering, and I hope to use `StreamlitChatMessageHistory` to store the history of chat records.
* In `langchain==0.1.9`, the above example code worked fine, but I updated to `langchain==0.1.11` which created the problem. This error was actually already present in `langchain==0.1.9`, but could only be reproduced in `Docker python:3.10-slim`, which led me to suspect that it was a problem with `Docker`. However, when I updated to `langchain 0.1.11`, I reproduced the same error locally.
* I hope to confirm whether it's my problem, or if this bug really exists.

### System Info

* macOS 12.7.3
* Python 3.10.13
* langchain==0.1.11
* langchain-openai==0.0.6
* streamlit==1.31.1
* pydantic==1.10.13

**Comment by AtomAsking** [comment]
* In order to make the testing more rigorous and reduce the workload of project developers, I have done extra tests.
* I tested with the same code in `langchain ==0.1.0`, `streamlit==1.30.0`, and the error is as follows:
```
2024-03-07 02:05:17.076 Uncaught app exception
Traceback (most recent call last):
  File "/Users/bar/.venv/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/Users/bar/demo.py", line 53, in <module>
    memory.add_message(AIMessage("How can I help you?"))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Serializable.__init__() takes 1 positional argument but 2 were given
```
To solve this non-critical error, I replaced the code of the line that reported the error, as shown below.
```python
memory.add_ai_message("Please describe your requirements")
```
At this point, everything is fine!
At this point, I'm fairly certain that this is a bug caused by the langchain version update.

Looking forward to your reply. Thank you!

**Comment by AtomAsking** [comment]
## Supplement the test results once again
- `langchain==0.1.7`
- `streamlit==1.31.1`
- `Python 3.10.12`

The code on the first floor runs smoothly and achieves the final expected effect. There have been no problems at all.

**Comment by AtomAsking** [comment]
@baskaryan Hope to get your help, thank you.

**Comment by baskaryan** [comment]
cc @sfc-gh-jcarroll

**Comment by sfc-gh-jcarroll** [comment]
Hi @AtomAsking I just wanted to confirm how are you executing the app? Is it using `streamlit run`?

Will take a look and see if we can repro this on the Streamlit side.

**Comment by AtomAsking** [comment]
> Hi @AtomAsking I just wanted to confirm how are you executing the app? Is it using `streamlit run`?
> 
> Will take a look and see if we can repro this on the Streamlit side.

Hi @sfc-gh-jcarroll ，I followed the official `streamlit` guide and tried two ways to start the App, and carefully read the related configuration of `streamlit`, but this problem still cannot be solved.
While waiting for your reply, I found that another developer encountered the same problem as me, and I have linked his question here. 
The above are my multiple test results. I am quite sure that from `langchain-community==0.0.25` onwards, to the current latest version, this issue still exists.
* `$ python -m streamlit run demo.py`
* `$ streamlit run demo.py`

Looking forward to your reply, thank you.

**Comment by sfc-gh-jcarroll** [comment]
I believe I have a fix up here: https://github.com/langchain-ai/langchain/pull/18834

Seems like the issue was introduced by logic change during mypy cleanup in https://github.com/langchain-ai/langchain/pull/18250, sorry I missed it during code review

**Comment by AtomAsking** [comment]
> I believe I have a fix up here: #18834
> 
> Seems like the issue was introduced by logic change during mypy cleanup in #18250, sorry I missed it during code review

According to your plan, I tried making source code changes locally, and this indeed solved the problem. Thank you.

**Comment by AtomAsking** [comment]
The problem has been resolved, I will close this issue.
