### ISSUE TITLE
TimeoutError with Longer Prompts

### ISSUE THREAD

**Issue by sdhutchins** [langchain-ai/langchain#18855]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

I am using the below url/api endpoint for accessing a server based Ollama model.

Below is me testing locally to ensure it works.

```python
from langchain_community.llms import Ollama

llm = Ollama(
    base_url="http://138.26.48.126:11434",
    model="gemma"
)

prompt = 'Give me one name for a new national park with jungle terrain?'
print(llm.invoke(prompt))
```

I am however using this in the context of a streamlit app and asking for a longer prompt. When I try a longer prompt, it times out. Is there a way to increase the timeout length?

### Error Message and Stack Trace (if applicable)

```console
2024-03-09 14:41:53.979 Uncaught app exception
Traceback (most recent call last):
  File "/Users/shutchens/Documents/Git-Repos/Grant_Guide/env/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/Users/shutchens/Documents/Git-Repos/Grant_Guide/env/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/Users/shutchens/Documents/Git-Repos/Grant_Guide/env/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/shutchens/Documents/Git-Repos/Grant_Guide/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/Users/shutchens/Documents/Git-Repos/Grant_Guide/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/Users/shutchens/Documents/Git-Repos/Grant_Guide/env/lib/python3.10/site-packages/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/usr/local/Cellar/python@3.10/3.10.13_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.10/3.10.13_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python@3.10/3.10.13_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/Users/shutchens/Documents/Git-Repos/Grant_Guide/env/lib/python3.10/site-packages/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "/Users/shutchens/Documents/Git-Repos/Grant_Guide/env/lib/python3.10/site-packages/urllib3/connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x137bbff10>, 'Connection to 138.26.49.149 timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/shutchens/Documents/Git-Repos/Grant_Guide/env/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/shutchens/Documents/Git-Repos/Grant_Guide/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/Users/shutchens/Documents/Git-Repos/Grant_Guide/env/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='138.26.49.149', port=11434): Max retries exceeded with url: /api/generate (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x137bbff10>, 'Connection to 138.26.49.149 timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/shutchens/Documents/Git-Repos/Grant_Guide/env/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/Users/shutchens/Documents/Git-Repos/Grant_Guide/streamlit/app_no_db.py", line 129, in <module>
    show_grant_guide_page()
  File "/Users/shutchens/Documents/Git-Repos/Grant_Guide/streamlit/app_no_db.py", line 42, in show_grant_guide_page
    documents = grant_generate.search_grant_guide_vectorstore(query=aims, store=vectorstore)
  File "/Users/shutchens/Documents/Git-Repos/Grant_Guide/Grant_Guide/generate.py", line 30, in search_grant_guide_vectorstore
    docs = docsearch.get_relevant_documents(query)
  File "/Users/shutchens/Documents/Git-Repos/Grant_Guide/env/lib/python3.10/site-packages/langchain_core/retrievers.py", line 244, in get_relevant_documents
    raise e
  File "/Users/shutchens/Documents/Git-Repos/Grant_Guide/env/lib/python3.10/site-packages/langchain_core/retrievers.py", line 237, in get_relevant_documents
    result = self._get_relevant_documents(
  File "/Users/shutchens/Documents/Git-Repos/Grant_Guide/env/lib/python3.10/site-packages/langchain_core/vectorstores.py", line 674, in _get_relevant_documents
    docs = self.vectorstore.similarity_search(query, **self.search_kwargs)
  File "/Users/shutchens/Documents/Git-Repos/Grant_Guide/env/lib/python3.10/site-packages/langchain_community/vectorstores/faiss.py", line 548, in similarity_search
    docs_and_scores = self.similarity_search_with_score(
  File "/Users/shutchens/Documents/Git-Repos/Grant_Guide/env/lib/python3.10/site-packages/langchain_community/vectorstores/faiss.py", line 420, in similarity_search_with_score
    embedding = self._embed_query(query)
  File "/Users/shutchens/Documents/Git-Repos/Grant_Guide/env/lib/python3.10/site-packages/langchain_community/vectorstores/faiss.py", line 157, in _embed_query
    return self.embedding_function(text)
  File "/Users/shutchens/Documents/Git-Repos/Grant_Guide/env/lib/python3.10/site-packages/langchain_core/_api/deprecation.py", line 145, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/shutchens/Documents/Git-Repos/Grant_Guide/env/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 991, in __call__
    self.generate(
  File "/Users/shutchens/Documents/Git-Repos/Grant_Guide/env/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 741, in generate
    output = self._generate_helper(
  File "/Users/shutchens/Documents/Git-Repos/Grant_Guide/env/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 605, in _generate_helper
    raise e
  File "/Users/shutchens/Documents/Git-Repos/Grant_Guide/env/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 592, in _generate_helper
    self._generate(
  File "/Users/shutchens/Documents/Git-Repos/Grant_Guide/env/lib/python3.10/site-packages/langchain_community/llms/ollama.py", line 408, in _generate
    final_chunk = super()._stream_with_aggregation(
  File "/Users/shutchens/Documents/Git-Repos/Grant_Guide/env/lib/python3.10/site-packages/langchain_community/llms/ollama.py", line 317, in _stream_with_aggregation
    for stream_resp in self._create_generate_stream(prompt, stop, **kwargs):
  File "/Users/shutchens/Documents/Git-Repos/Grant_Guide/env/lib/python3.10/site-packages/langchain_community/llms/ollama.py", line 159, in _create_generate_stream
    yield from self._create_stream(
  File "/Users/shutchens/Documents/Git-Repos/Grant_Guide/env/lib/python3.10/site-packages/langchain_community/llms/ollama.py", line 220, in _create_stream
    response = requests.post(
  File "/Users/shutchens/Documents/Git-Repos/Grant_Guide/env/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Users/shutchens/Documents/Git-Repos/Grant_Guide/env/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/shutchens/Documents/Git-Repos/Grant_Guide/env/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/shutchens/Documents/Git-Repos/Grant_Guide/env/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/shutchens/Documents/Git-Repos/Grant_Guide/env/lib/python3.10/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='138.26.49.149', port=11434): Max retries exceeded with url: /api/generate (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x137bbff10>, 'Connection to 138.26.49.149 timed out. (connect timeout=None)'))
```

### Description

When I text connecting the the api endpoint, it works perfectly fine.

When I try to do so within my streamlit app, it errors out.

### System Info

```console
System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.3.0: Wed Dec 20 21:28:58 PST 2023; root:xnu-10002.81.5~7/RELEASE_X86_64
> Python Version:  3.10.13 (main, Aug 24 2023, 12:59:26) [Clang 15.0.0 (clang-1500.0.40.1)]

Package Information
-------------------
> langchain_core: 0.1.30
> langchain: 0.1.11
> langchain_community: 0.0.27
> langsmith: 0.1.23
> langchain_text_splitters: 0.0.1

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve
```

**Comment by eyurtsev** [comment]
This is not a bug, but a usage question. Please use Q&A discussion for usage questions going forward.

Here's the API reference: https://api.python.langchain.com/en/latest/llms/langchain_community.llms.ollama.Ollama.html#langchain_community.llms.ollama.Ollama
