### ISSUE TITLE
`UpstashRedisEntityStore` initializer does not work. Upstash Redis Instance could not be created.

### ISSUE THREAD

**Issue by albertpurnama** [langchain-ai/langchain#18891]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

The following code will not work:

```
from langchain.memory.entity import UpstashRedisEntityStore

entity_store = UpstashRedisEntityStore(
    session_id="my-session",
    url="your-upstash-url",
    token="your-upstash-redis-token",
    ttl=600,
)
```

### Error Message and Stack Trace (if applicable)

Upstash Redis instance could not be initiated.
Traceback (most recent call last):
  File "/Users/albertpurnama/Documents/dev/qornetto/main.py", line 27, in <module>
    entity_store = UpstashRedisEntityStore(
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/albertpurnama/Documents/dev/qornetto/.venv/lib/python3.11/site-packages/langchain/memory/entity.py", line 106, in __init__
    self.session_id = session_id
    ^^^^^^^^^^^^^^^
  File "/Users/albertpurnama/Documents/dev/qornetto/.venv/lib/python3.11/site-packages/pydantic/v1/main.py", line 357, in __setattr__
    raise ValueError(f'"{self.__class__.__name__}" object has no field "{name}"')
ValueError: "UpstashRedisEntityStore" object has no field "session_id"

### Description

I'm trying to use `UpstashRedisEntityStore` but the initializer does not work.

### System Info

langchain==0.1.11
langchain-community==0.0.27
langchain-core==0.1.30
langchain-openai==0.0.8
langchain-text-splitters==0.0.1
langchainhub==0.1.15

mac

python 3.11.6

**Comment by albertpurnama** [comment]
For those who's encountering the same problem

The current workaround I have is to make a subclass from UpstashRedisEntityStore, initialize those properties and let the initializer run afterwards. This seems to make the error disappear.
```python
class FixedUpstashRedisEntityStore(UpstashRedisEntityStore):
    redis_client: Any
    session_id: str = "default"
    key_prefix: str = "memory_store"
    ttl: Optional[int] = 60 * 60 * 24
    recall_ttl: Optional[int] = 60 * 60 * 24 * 3

    def __init__(
        self,
        *args: Any,
        **kwargs: Any,
      ):
        super().__init__(*args, **kwargs)

entity_store = FixedUpstashRedisEntityStore(
    session_id="my-session",
    url="https://enabling-anemone-37187.upstash.io",
    token=os.getenv("UPSTASH_REDIS_TOKEN", "invalid-upstash-redis-token"),
    ttl=600,
)
```
