### ISSUE TITLE
OpenAI's legacy completion API causes that stop words do not work, patches are attached.

### ISSUE THREAD

**Issue by marvelliu** [langchain-ai/langchain#19062]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

The patches are listed below:

```
diff -x *.pyc -r ~/venv/lib/python3.9/site-packages/langchain_openai/llms/base.py langchain_openai/llms/base.py
207c207,210
<             values["client"] = openai.OpenAI(**client_params).completions
---
>             client = openai.OpenAI(**client_params)
>             completion = client.chat.completions
>             values["client"] = completion
>             #values["client"] = openai.OpenAI(**client_params).completions
340c343,352
<                 response = self.client.create(prompt=_prompts, **params)
---
>                 from openai.types.chat.chat_completion_user_message_param import ChatCompletionUserMessageParam
>
>                 umessage = ChatCompletionUserMessageParam(content=_prompts[0], role = "user")
>                 messages=[umessage,]
>                 response = self.client.create(messages=messages, **params)
>                 #response = self.client.create(prompt=_prompts, **params)
454c466,467
<                         text=choice["text"],
---
>                         #text=choice["text"],
>                         text=choice["message"]["content"],
```

### Error Message and Stack Trace (if applicable)

```Entering new SQLDatabaseChain chain...

Given an input question, first create a syntactically correct postgresql query to run, then look at the results of the query and return the answer.
Use the following format:

Question: Question here
SQLQuery: SQL Query to run
SQLResult: Result of the SQLQuery
Answer: Final answer here

how many tasks?

SQLQuery:SELECT COUNT(*) FROM tasks
SQLResult:
count
-----
3
Answer: There are 3 tasks in the tasks table.(psycopg2.errors.SyntaxError) syntax error at or near ":"
LINE 2: SQLResult:
                 ^

[SQL: SELECT COUNT(*) FROM tasks
SQLResult:
count
-----
3
Answer: There are 3 tasks in the tasks table.]
(Background on this error at: https://sqlalche.me/e/20/f405)
Traceback (most recent call last):
  File "/Users/marvel/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/marvel/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.SyntaxError: syntax error at or near ":"
LINE 2: SQLResult:
                 ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/marvel/Nutstore Files/programs/ai/xiaoyi-robot/codes/postgres_agent.py", line 61, in get_prompt
    print(db_chain.run(question))
  File "/Users/marvel/venv/lib/python3.9/site-packages/langchain_core/_api/deprecation.py", line 145, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/marvel/venv/lib/python3.9/site-packages/langchain/chains/base.py", line 538, in run
    return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[
  File "/Users/marvel/venv/lib/python3.9/site-packages/langchain_core/_api/deprecation.py", line 145, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/marvel/venv/lib/python3.9/site-packages/langchain/chains/base.py", line 363, in __call__
    return self.invoke(
  File "/Users/marvel/venv/lib/python3.9/site-packages/langchain/chains/base.py", line 162, in invoke
    raise e
  File "/Users/marvel/venv/lib/python3.9/site-packages/langchain/chains/base.py", line 156, in invoke
    self._call(inputs, run_manager=run_manager)
  File "/Users/marvel/venv/lib/python3.9/site-packages/langchain_experimental/sql/base.py", line 201, in _call
    raise exc
  File "/Users/marvel/venv/lib/python3.9/site-packages/langchain_experimental/sql/base.py", line 146, in _call
    result = self.database.run(sql_cmd)
  File "/Users/marvel/venv/lib/python3.9/site-packages/langchain_community/utilities/sql_database.py", line 436, in run
    result = self._execute(command, fetch)
  File "/Users/marvel/venv/lib/python3.9/site-packages/langchain_community/utilities/sql_database.py", line 413, in _execute
    cursor = connection.execute(text(command))
  File "/Users/marvel/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
  File "/Users/marvel/venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 517, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/marvel/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1639, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/marvel/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1848, in _execute_context
    return self._exec_single_context(
  File "/Users/marvel/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1988, in _exec_single_context
    self._handle_dbapi_exception(
  File "/Users/marvel/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2344, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/marvel/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/marvel/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near ":"
LINE 2: SQLResult:
                 ^

[SQL: SELECT COUNT(*) FROM tasks
SQLResult:
count
-----
3
Answer: There are 3 tasks in the tasks table.]

```
<img width="1563" alt="error" src="https://github.com/langchain-ai/langchain/assets/905594/3c9ff8a4-d1b0-482f-ac46-70bd15a240b4">

### Description

I followed the article (https://coinsbench.com/chat-with-your-databases-using-langchain-bb7d31ed2e76) to make langchain interact with postgres DB, but I have got error response from OpenAI recently, error message are listed below.

<img width="1488" alt="chat-comp" src="https://github.com/langchain-ai/langchain/assets/905594/7616ecf9-1ea0-4726-910e-8ace52825fae">
<img width="1559" alt="comp" src="https://github.com/langchain-ai/langchain/assets/905594/ab5386d8-8c5c-431a-abde-11427630f63a">

It seems that OpenAI has stopped supporting Completions API and stop words in the request fail to work. OpenAI's suggestions are(https://openai.com/blog/gpt-4-api-general-availability):

> Starting today, all paying API customers have access to GPT-4. In March, we [introduced the ChatGPT API](https://openai.com/blog/introducing-chatgpt-and-whisper-apis), and earlier this month we [released our first updates](https://openai.com/blog/function-calling-and-other-api-updates) to the chat-based models. We envision a future where chat-based models can support any use case. Today we’re announcing a deprecation plan for older models of the Completions API, and recommend that users adopt the Chat Completions API.

So I did some research of current codes and decided to modify langchain_openai/llms/base.py, the modifications are list above. finally it works
<img width="849" alt="finally" src="https://github.com/langchain-ai/langchain/assets/905594/bd0e33be-6921-4ac0-b264-322f928ed3c7">

### System Info

 % pip list|grep langchain
langchain                     0.1.5
langchain-community           0.0.17
langchain-core                0.1.18
langchain-experimental        0.0.50
langchain-openai              0.0.5
 % pip list|grep openai
langchain-openai              0.0.5
openai                        1.11.1

**Comment by eyurtsev** [comment]
The issue contains a lot of unnecessary information. As far as I'm aware stop tokens work with current openai chat models.

Test with

```
model = ChatOpenAI()
model.bind(stop=['my_token'])
model.invoke()
```

if that fails, feel free to open a minimal issue that's describing the problem precisely.
