### ISSUE TITLE
milvus retriever.get_relevant_documents has bug?

### ISSUE THREAD

**Issue by Songjiadong** [langchain-ai/langchain#19106]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```py
user_input = "你好"
    embedding_model_name = fr"/usr/local/models/BAAI/bge-m3"
    hf = HuggingFaceBgeEmbeddings(
        model_name=embedding_model_name,
        model_kwargs={"device": "cpu"},
        encode_kwargs={
            "normalize_embeddings": True,
            "batch_size": 32
        }
    )
    milvus_store = Milvus(
        embedding_function=hf,
        collection_name="qa",
        drop_old=False,
        text_field="content",
        primary_field= "id",
        vector_field = "vector",
        # search_params={
        #     "metric_type": "IP",
        #     "index_type": "IVF_FLAT",
        #     "params": {"nprobe": 10, "nlist": 128}
        # },
        connection_args={
            "host": "10.3.1.187",
            "port": "19530",
            "user": "",
            "password": "",
            "db_name": "qa"
        },

    )
    retriever=milvus_store.as_retriever(
        search_type="similarity_score_threshold",
        search_kwargs={"score_threshold": 0.8}
    )
    docs= retriever.get_relevant_documents(query=user_input)
```

### Error Message and Stack Trace (if applicable)

```
Traceback (most recent call last):
  File "/usr/local/churchill/lib/python3.10/site-packages/langchain_core/retrievers.py", line 244, in get_relevant_documents
    raise e
  File "/usr/local/churchill/lib/python3.10/site-packages/langchain_core/retrievers.py", line 237, in get_relevant_documents
    result = self._get_relevant_documents(
  File "/usr/local/churchill/lib/python3.10/site-packages/langchain_core/vectorstores.py", line 677, in _get_relevant_documents
    self.vectorstore.similarity_search_with_relevance_scores(
  File "/usr/local/churchill/lib/python3.10/site-packages/langchain_core/vectorstores.py", line 324, in similarity_search_with_relevance_scores
    docs_and_similarities = self._similarity_search_with_relevance_scores(
  File "/usr/local/churchill/lib/python3.10/site-packages/langchain_core/vectorstores.py", line 271, in _similarity_search_with_relevance_scores
    relevance_score_fn = self._select_relevance_score_fn()
  File "/usr/local/churchill/lib/python3.10/site-packages/langchain_core/vectorstores.py", line 228, in _select_relevance_score_fn
    raise NotImplementedError
NotImplementedError
```

### Description

I want to get `get_relevant_documents` using retriever ,but it has bug.

### System Info

langchain 0.1.9
python version 3.10
centos 8

**Comment by liugddx** [comment]
Yes The `select_relevance_score_fn` method is not implemented in Milvus.

**Comment by hagemon** [comment]
We can create a custom retriever to solve this problem, all we need to do is to replace `similarity_search_with_relevance_scores` function with `similarity_search_with_score` in the original `_get_relevant_documents`.

```python
from langchain.schema.vectorstore import VectorStoreRetriever
from langchain.schema.document import Document
from langchain.callbacks.manager import (
    CallbackManagerForRetrieverRun,
    AsyncCallbackManagerForRetrieverRun,
)

from typing import List


class CustomRetriever(VectorStoreRetriever):
    def _get_relevant_documents(
        self, query: str, *, run_manager: CallbackManagerForRetrieverRun
    ) -> List[Document]:
        if self.search_type == "similarity":
            docs = self.vectorstore.similarity_search(query, **self.search_kwargs)
        elif self.search_type == "similarity_score_threshold":

            # the core code is here
            docs_and_similarities = self.vectorstore.similarity_search_with_score(query)
            
             # you can extend code here, e.g. using `score` variable to filter docs under specific threshold
            threshold = self.search_kwargs.get("score_threshold", 0)
            return [doc for doc, score in docs_and_similarities if score > threshold]
        elif self.search_type == "mmr":
            docs = self.vectorstore.max_marginal_relevance_search(
                query, **self.search_kwargs
            )
        else:
            raise ValueError(f"search_type of {self.search_type} not allowed.")
        return docs

    async def _aget_relevant_documents(
        self, query: str, *, run_manager: AsyncCallbackManagerForRetrieverRun
    ) -> List[Document]:
        if self.search_type == "similarity":
            docs = await self.vectorstore.asimilarity_search(
                query, **self.search_kwargs
            )
        elif self.search_type == "similarity_score_threshold":

            # the core code is here
            docs_and_similarities = (
                await self.vectorstore.asimilarity_search_with_score(query)
            )
            
            # you can extend code here, e.g. using `score` variable to filter docs under specific threshold
            threshold = self.search_kwargs.get("score_threshold", 0)
            return [doc for doc, score in docs_and_similarities if score > threshold]
        elif self.search_type == "mmr":
            docs = await self.vectorstore.amax_marginal_relevance_search(
                query, **self.search_kwargs
            )
        else:
            raise ValueError(f"search_type of {self.search_type} not allowed.")
        return docs
```

then we can use it as a retriever, which can be feed into chains, just like official demo does:

```python
from langchain.chains.combine_documents import create_stuff_documents_chain
from langchain.chains.history_aware_retriever import create_history_aware_retriever
from langchain.chains.retrieval import create_retrieval_chain

prompt_template = ChatPromptTemplate.from_messages(.......) # use whatever template
vectorstore = Milvus(
        embedding_function=hf,
        collection_name="qa",
        connection_args={
            "host": "10.3.1.187",
            "port": "19530",
            "db_name": "qa"
      },
)
retriever = CustomRetriever(
    vectorstore= vectorstore,
    search_type="similarity_score_threshold",
    search_kwargs={"score_threshold": 0.5},
)
llm = get_model(temperature=0, max_tokens=8192)  # some function that get LLM modle

stuff_documents_chain = create_stuff_documents_chain(llm, prompt_template)
history_aware_retriever = create_history_aware_retriever(
    llm, retriever, prompt_template
)
retrieval_chain = create_retrieval_chain(
    history_aware_retriever, stuff_documents_chain
)
retrieval_chain.invoke("Hello")
```

and you can also use `get_relevant_documents(query=user_input)` as your wish:

```python
docs= retriever.get_relevant_documents(query=user_input)
```

**Comment by liugddx** [comment]
> then we can use it as a retriever, which can be feed into chains, just like official demo does:

Good job

**Comment by Songjiadong** [comment]
@kwunhang  yes,of course

**Comment by dyh2024** [comment]
vector_store.as_retriever(
    # search_type="similarity",
    # search_type="mmr",
    search_type="similarity_score_threshold",
    search_kwargs={'score_threshold': 0.8}
).invoke("where did i work?")  got the same error.  ("similarity" and "mmr" are OK)

python 3.12
![image](https://github.com/user-attachments/assets/713692fc-31e8-4099-87f2-8cdcda3d08c1)

**Comment by zc277584121** [comment]
fixed at: https://github.com/langchain-ai/langchain-milvus/pull/18

**Comment by wo-yashsinghvi** [comment]
How can I get the relevance score in results using the Milvus Vector Store Retriever?
