### ISSUE TITLE
AttributeError: 'function' object has no attribute 'embed_query' with OpenAI llm and custom tool for Data Lake with Activeloop

### ISSUE THREAD

**Issue by Rafael-Silva-Oliveira** [langchain-ai/langchain#19171]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

    tools = load_tools(["ddg-search", "wikipedia", "llm-math"], llm=llm)
        retriever = db.as_retriever()
        repl_tool = Tool(
            name="python_repl",
            description="A Python shell. Use this to execute python commands. Input should be a valid python command. If you want to see the output of a value, you should print it out with `print(...)`.",
            func=PythonREPL().run,
        )

        retrieve_tool = create_retriever_tool(
            retriever,
            "SearchDocuments",
            "Searches and returns results from documents to answer queries.",
        )

        tools += [repl_tool, retrieve_tool]

        return tools

### Error Message and Stack Trace (if applicable)

> Entering new AgentExecutor chain...

Invoking: `SearchDocuments` with `list all documents`      

2024-03-15 23:40:14.938 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Rafael\anaconda3\envs\kaggle\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\Rafael\OneDrive - Artificial Intelligence Expert\Documents\BioChat_v2\BioChat\src\app.py", line 196, in <module>
    main(constants_path=f"./config/CONSTANTS.json")        
  File "C:\Users\Rafael\OneDrive - Artificial Intelligence Expert\Documents\BioChat_v2\BioChat\src\app.py", line 165, in main
    result = st.session_state["agent"].invoke(
  File "C:\Users\Rafael\anaconda3\envs\kaggle\lib\site-packages\langchain\chains\base.py", line 163, in invoke        
    raise e
  File "C:\Users\Rafael\anaconda3\envs\kaggle\lib\site-packages\langchain\chains\base.py", line 153, in invoke        
    self._call(inputs, run_manager=run_manager)
  File "C:\Users\Rafael\anaconda3\envs\kaggle\lib\site-packages\langchain\agents\agent.py", line 1432, in _call       
    next_step_output = self._take_next_step(
  File "C:\Users\Rafael\anaconda3\envs\kaggle\lib\site-packages\langchain\agents\agent.py", line 1138, in _take_next_step
    [
  File "C:\Users\Rafael\anaconda3\envs\kaggle\lib\site-packages\langchain\agents\agent.py", line 1138, in <listcomp>  
    [
  File "C:\Users\Rafael\anaconda3\envs\kaggle\lib\site-packages\langchain\agents\agent.py", line 1223, in _iter_next_step
    yield self._perform_agent_action(
  File "C:\Users\Rafael\anaconda3\envs\kaggle\lib\site-packages\langchain\agents\agent.py", line 1245, in _perform_agent_action
    observation = tool.run(
  File "C:\Users\Rafael\anaconda3\envs\kaggle\lib\site-packages\langchain_core\tools.py", line 417, in run
    raise e
  File "C:\Users\Rafael\anaconda3\envs\kaggle\lib\site-packages\langchain_core\tools.py", line 376, in run
    self._run(*tool_args, run_manager=run_manager, **tool_kwargs)
  File "C:\Users\Rafael\anaconda3\envs\kaggle\lib\site-packages\langchain_core\tools.py", line 580, in _run
    else self.func(*args, **kwargs)
  File "C:\Users\Rafael\OneDrive - Artificial Intelligence Expert\Documents\BioChat_v2\BioChat/src\agent.py", line 165, in <lambda>
    func=lambda query: retriever_tool(query),
  File "C:\Users\Rafael\OneDrive - Artificial Intelligence Expert\Documents\BioChat_v2\BioChat/src\agent.py", line 148, in retriever_tool
    docs = retriever.get_relevant_documents(query)
  File "C:\Users\Rafael\anaconda3\envs\kaggle\lib\site-packages\langchain_core\retrievers.py", line 244, in get_relevant_documents
    raise e
  File "C:\Users\Rafael\anaconda3\envs\kaggle\lib\site-packages\langchain_core\retrievers.py", line 237, in get_relevant_documents
    result = self._get_relevant_documents(
  File "C:\Users\Rafael\anaconda3\envs\kaggle\lib\site-packages\langchain_core\vectorstores.py", line 674, in _get_relevant_documents
    docs = self.vectorstore.similarity_search(query, **self.search_kwargs)
  File "C:\Users\Rafael\anaconda3\envs\kaggle\lib\site-packages\langchain_community\vectorstores\deeplake.py", line 541, in similarity_search
    return self._search(
  File "C:\Users\Rafael\anaconda3\envs\kaggle\lib\site-packages\langchain_community\vectorstores\deeplake.py", line 421, in _search
    _embedding_function = self._embedding_function.embed_query
AttributeError: 'function' object has no attribute 'embed_query'

### Description

I'm trying to add a custom tool so that an agent can retrieve information from data lake activeloop however I keep getting the error

`AttributeError: 'function' object has no attribute 'embed_query'`

How can I fix this?

### System Info

langchain==0.1.12
langchain-community==0.0.28
langchain-core==0.1.32
langchain-experimental==0.0.54
langchain-google-vertexai==0.1.0
langchain-openai==0.0.8
langchain-text-splitters==0.0.1
langchainhub==0.1.15

**Comment by Rafael-Silva-Oliveira** [comment]
Any help on this?
