### ISSUE TITLE
Why redis vectorstore filter parameter make syntax error

### ISSUE THREAD

**Issue by luckymanx** [langchain-ai/langchain#19323]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from common_base.llm_base import embedding_model
redis_url = "redis://:mypassword@127.0.0.1:6379"
from langchain_community.vectorstores.redis import Redis

from langchain_community.vectorstores.redis.filters import RedisFilter

rds: Redis = Redis.from_existing_index(
    embedding_model,
    redis_url=redis_url,
    index_name="teacher_report",
    schema="teacher_report/teacher_report.yaml",
)
email_filter = RedisFilter.text('teacher_email') == 'asdf@path.how'
asdf = rds.similarity_search(query='asdf',k=3, filter=email_filter)
print(asdf)
```
```yaml
text:
- name: teacher_email
  no_index: false
  no_stem: false
  sortable: false
  weight: 1
  withsuffixtrie: false
- name: clinic_title
  no_index: false
  no_stem: false
  sortable: false
  weight: 1
  withsuffixtrie: false
- name: content
  no_index: false
  no_stem: false
  sortable: false
  weight: 1
  withsuffixtrie: false
vector:
- algorithm: FLAT
  block_size: 1000
  datatype: FLOAT32
  dims: 1536
  distance_metric: COSINE
  initial_cap: 20000
  name: content_vector
```

### Error Message and Stack Trace (if applicable)

```
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/langchain_community/vectorstores/redis/base.py", line 946, in similarity_search_by_vector
    results = self.client.ft(self.index_name).search(redis_query, params_dict)  # type: ignore  # noqa: E501
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/redis/commands/search/commands.py", line 501, in search
    res = self.execute_command(SEARCH_CMD, *args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/redis/client.py", line 543, in execute_command
    return conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/redis/client.py", line 544, in <lambda>
    lambda: self._send_command_parse_response(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/redis/client.py", line 520, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/redis/client.py", line 560, in parse_response
    response = connection.read_response()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/redis/connection.py", line 536, in read_response
    raise response
redis.exceptions.ResponseError: Syntax error at offset 22 near path

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jimmykim/workspace/deus-path-machina/test2.py", line 15, in <module>
    asdf = rds.similarity_search(query='asdf',k=3, fetch_k=10, filter=email_filter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/langchain_community/vectorstores/redis/base.py", line 882, in similarity_search
    return self.similarity_search_by_vector(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/langchain_community/vectorstores/redis/base.py", line 950, in similarity_search_by_vector
    raise ValueError(
ValueError: Query failed with syntax error. This is likely due to malformation of filter, vector, or query argument

```

### Description

I have written a simple sample code to filter and search data using Redis VectorStore. Despite creating a filter with RedisFilterExpression and passing it as a parameter as described in the documentation, I encounter a syntax error. When I do not pass the filter, the search works correctly across all vector data. I suspect this might be a bug, what do you think?

### System Info

langchain==0.1.12
langchain-community==0.0.28
langchain-core==0.1.32
langchain-experimental==0.0.45
langchain-openai==0.0.8
langchain-text-splitters==0.0.1
MAC OS M1
Python 3.11.8

**Comment by luckymanx** [comment]
I think when filter data include "@", make syntax error
