### ISSUE TITLE
AgentExecutor fails to use StructuredTool

### ISSUE THREAD

**Issue by alramalho** [langchain-ai/langchain#19437]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from typing import Annotated

from langchain.tools import StructuredTool
from pydantic import BaseModel, Field


class ToolSchema(BaseModel):
    question: Annotated[
        str,
        Field(
            description="Question to be done to the search engine. Make it clear and complete. Should be formulated always in the language the user is using with you."
        ),
    ]
    page: Annotated[int, Field(ge=0, le=1, description="Result page to be searched in")]


class SearchInternetTool(StructuredTool):

    def __init__(self):

        super(StructuredTool, self).__init__(
            name="Search Internet",
            description=f"""
            Useful for getting recent & factual information. 
            If this tool is used, it is mandatory to include the sources in your response afterwards.
            You can only use this tool 2 times.
            """.replace(
                "    ", ""
            ).replace(
                "\n", " "
            ),
            args_schema=ToolSchema,
            func=self.function,
        )

    def function(self, question: str, page: int) -> str:
        return f"Question: {question}, Page: {page}"


tool = SearchInternetTool()

print(tool.run("""{"question": "How old is Snoop dogg", "page": 0}"""))

```

### Error Message and Stack Trace (if applicable)

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/alramalho/workspace/jarvis/jarvis-clean/backend/spike.py", line 42, in <module>
    print(tool.run("""{"question": "How old is Snoop dogg", "page": 0}"""))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alramalho/Library/Caches/pypoetry/virtualenvs/backend-jarvis-Xbe6mXa_-py3.11/lib/python3.11/site-packages/langchain_core/tools.py", line 388, in run
    raise e
  File "/Users/alramalho/Library/Caches/pypoetry/virtualenvs/backend-jarvis-Xbe6mXa_-py3.11/lib/python3.11/site-packages/langchain_core/tools.py", line 379, in run
    parsed_input = self._parse_input(tool_input)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alramalho/Library/Caches/pypoetry/virtualenvs/backend-jarvis-Xbe6mXa_-py3.11/lib/python3.11/site-packages/langchain_core/tools.py", line 279, in _parse_input
    input_args.validate({key_: tool_input})
  File "pydantic/main.py", line 711, in pydantic.main.BaseModel.validate
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ToolSchema
page
  field required (type=value_error.missing)
  ```

### Description

i am trying to update my AgentExecutor to make use of `args_schema` on tool usage.
Nevertheless, it internally is calling the tool.run (`AgentExecutor._perform_agent_action`), which is failing to the error above, reproducible by the given code

### System Info

```
langchain==0.1.13
langchain-community==0.0.29
langchain-core==0.1.33
langchain-openai==0.1.0
langchain-text-splitters==0.0.1
```

**Comment by alramalho** [comment]
hello?

**Comment by alramalho** [comment]
_In dead code, silence—
issues fade, untracked, unseen,
ghosts in the machine._

**Comment by styk-tv** [comment]
@alramalho 

_Unseen circuits hum,
echoes of forgotten code,
haunting the machine's core._
