### ISSUE TITLE
Run zhipuai api with Langchain get an error 

### ISSUE THREAD

**Issue by yanghu861004** [langchain-ai/langchain#19581]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

messages = chat_template.format_messages(resume=data)

from langchain_community.chat_models import ChatZhipuAI

for question in question_prompt:
    messages = chat_template.format_messages(resume=data)
    messages.append(
        HumanMessage(
            content=question
        )
    )
    llm = ChatZhipuAI(
        temperature=0.01,
        model="glm-4",
        max_tokens=1024,
        stream=False,
    )
    messages.append(
        AIMessage(
            content=llm(messages).content
        )
    )
    print(messages[-1].content)

### Error Message and Stack Trace (if applicable)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: The function `__call__` was deprecated in LangChain 0.1.7 and will be removed in 0.2.0. Use invoke instead.
  warn_deprecated(
Traceback (most recent call last):
  File "/Users/yanghu/Downloads/resume_extraction.py", line 65, in <module>
    content=llm(messages).content
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain_core/_api/deprecation.py", line 145, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 729, in __call__
    generation = self.generate(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 407, in generate
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 397, in generate
    self._generate_with_cache(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 589, in _generate_with_cache
    result = self._generate(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain_community/chat_models/zhipuai.py", line 267, in _generate
    if response["code"] != 200:
TypeError: 'NoneType' object is not subscriptable

### Description

when I run my python file on my Mac own terminal. It appears an error like below:

<img width="1316" alt="iShot_2024-03-26_15 43 52" src="https://github.com/langchain-ai/langchain/assets/358248/9b1903aa-08c5-4e6a-bcf0-8e478c514a08">
 if response["code"] != 200:
TypeError: 'NoneType' object is not subscriptable

### System Info

langchain                  0.1.13
langchain-community        0.0.29
langchain-core             0.1.33
zhipuai                    2.0.1

macOS 14.4.1

**Comment by liugddx** [comment]
Refer to https://github.com/langchain-ai/langchain/issues/17863

**Comment by liugddx** [comment]
https://github.com/langchain-ai/langchain/pull/16695
