### ISSUE TITLE
[bedrock][claude-sonnet-v3][bedrockchat] BedrockChat: UnrecognizedClientException when calling the InvokeModel operation

### ISSUE THREAD

**Issue by abhishekkumar-9** [langchain-ai/langchain#19677]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

BedrockChat(client=None
                               ,model_id="anthropic.claude-3-sonnet-20240229-v1:0"
                               ,streaming=True
                               , region_name="us-east-1"
                               ,model_kwargs={"max_tokens": 100000})

### Error Message and Stack Trace (if applicable)

Error raised by bedrock service: An error occurred (UnrecognizedClientException) when calling the InvokeModel operation: The security token included in the request is invalid.
Traceback (most recent call last):
  File "/home/codespace/.python/current/lib/python3.10/site-packages/langchain_community/llms/bedrock.py", line 532, in _prepare_input_and_invoke
    response = self.client.invoke_model(**request_options)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/botocore/client.py", line 1009, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException) when calling the InvokeModel operation: The security token included in the request is invalid.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspaces/cortex-api/app/middleware/interceptor.py", line 111, in run
    async for msg in self.intercept_messages(
  File "/workspaces/cortex-api/app/middleware/interceptor.py", line 63, in intercept_messages
    async for message in messages:
  File "/workspaces/cortex-api/app/core/model.py", line 252, in run
    async for message in self.prepare_response(chain_step.run(params), message_id=message_id):
  File "/workspaces/cortex-api/app/core/model.py", line 313, in prepare_response
    async for fragment in response:
  File "/workspaces/cortex-api/app/chaining/base_chain.py", line 286, in run
    user_params = await task
  File "/workspaces/cortex-api/app/chaining/base_chain.py", line 248, in __run
    return_to_user = await self._run(params)
  File "/workspaces/cortex-api/app/chaining/doc_chain.py", line 121, in _run
    await self._generate_chain(template=self._model_config.with_context_prompt_template).arun(
  File "/home/codespace/.python/current/lib/python3.10/site-packages/langchain_core/_api/deprecation.py", line 154, in awarning_emitting_wrapper
    return await wrapped(*args, **kwargs)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/langchain/chains/base.py", line 627, in arun
    await self.acall(
  File "/home/codespace/.python/current/lib/python3.10/site-packages/langchain_core/_api/deprecation.py", line 154, in awarning_emitting_wrapper
    return await wrapped(*args, **kwargs)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/langchain/chains/base.py", line 428, in acall
    return await self.ainvoke(
  File "/home/codespace/.python/current/lib/python3.10/site-packages/langchain/chains/base.py", line 212, in ainvoke
    raise e
  File "/home/codespace/.python/current/lib/python3.10/site-packages/langchain/chains/base.py", line 203, in ainvoke
    await self._acall(inputs, run_manager=run_manager)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "/home/codespace/.python/current/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 556, in agenerate_prompt
    return await self.agenerate(
  File "/home/codespace/.python/current/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 516, in agenerate
    raise exceptions[0]
  File "/home/codespace/.python/current/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 638, in _agenerate_with_cache
    result = await self._agenerate(
  File "/home/codespace/.python/current/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 676, in _agenerate
    return await run_in_executor(
  File "/home/codespace/.python/current/lib/python3.10/site-packages/langchain_core/runnables/config.py", line 514, in run_in_executor
    return await asyncio.get_running_loop().run_in_executor(
  File "/home/codespace/.python/current/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/langchain_community/chat_models/bedrock.py", line 290, in _generate
    completion = self._prepare_input_and_invoke(
  File "/home/codespace/.python/current/lib/python3.10/site-packages/langchain_community/llms/bedrock.py", line 539, in _prepare_input_and_invoke
    raise ValueError(f"Error raised by bedrock service: {e}")
ValueError: Error raised by bedrock service: An error occurred (UnrecognizedClientException) when calling the InvokeModel operation: The security token included in the request is invalid.

### Description

I am trying to use the BedrockChat which currently supports the v3 but when I am running via langchain , it is throwing me the above error. Please try to help.

### System Info

langchain==0.1.13
langchain-community==0.0.29
langchain-core==0.1.33
langchain-experimental==0.0.49
langchain-text-splitters==0.0.1

macOS : latest
python 10

**Comment by cipher982** [comment]
I have to pass in a boto3 client when I'm using it.

```
bedrock = boto3.client(service_name="bedrock-runtime", region_name="us-east-1")
chat = BedrockChat(
    client=bedrock,    
    model_id=model,
)
```

**Comment by abhishekkumar-9** [comment]
I tried but it remained the same.

**Comment by abhishekkumar-9** [comment]
I had to add AWS policy for enabling STS assume role to fix this.
I am using below snippet code.

```
BedrockChat(
                credentials_profile_name=config.bedrock_credential_profile_name,
                model_id=llm_config.model_name.lower(),
                streaming=True,
                region_name=config.bedrock_region,
            )
```
