### ISSUE TITLE
langchain_mistralai 0.1.0 broken ( KeyError: 'choices' )

### ISSUE THREAD

**Issue by BERRADA-Omar** [langchain-ai/langchain#19759]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from langchain_mistralai.chat_models import ChatMistralAI
from langchain_core.messages import HumanMessage


chat_model = ChatMistralAI(
    endpoint="https://<endpoint>.<region>.inference.ai.azure.com",
    mistral_api_key="somekey",
    verbose=True,
    model="Mistral-large"
)

messages = [HumanMessage(content="knock knock")]
print(chat_model.invoke(messages))
```

### Error Message and Stack Trace (if applicable)

```python
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    print(chat_model.invoke(messages))
  File "...\.venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 154, in invoke
    self.generate_prompt(
  File "...\.venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 550, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
  File "...\.venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 411, in generate
    raise e
  File "...\.venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 401, in generate
    self._generate_with_cache(
  File "...\.venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 618, in _generate_with_cache
    result = self._generate(
  File "...\.venv\Lib\site-packages\langchain_mistralai\chat_models.py", line 312, in _generate
    return self._create_chat_result(response)
  File "...\.venv\Lib\site-packages\langchain_mistralai\chat_models.py", line 316, in _create_chat_result
    for res in response["choices"]:
KeyError: 'choices'
```

### Description

I use a Mistral AI model deployed on Azure.
It works perfectelly with the mistralai lib client in python.
But when i use the langchain_mistralai==0.1.0, it would not work and produce the given error.
when i downgrade to langchain_mistralai==0.0.5, it works again.

Can you help with the issue ? 

### System Info

```env
langchain==0.1.13
langchain-community==0.0.29
langchain-core==0.1.36
langchain-mistralai==0.1.0
langchain-openai==0.0.8
langchain-text-splitters==0.0.1
langchainhub==0.1.15
```

platform : windows
python 3.11.3

**Comment by adsellor** [comment]
Had the same issue recently. Appending `/v1` to the `endpoint` solved it for me.

```diff

chat_model = ChatMistralAI(
-      endpoint="https://<endpoint>.<region>.inference.ai.azure.com",
+      endpoint="https://<endpoint>.<region>.inference.ai.azure.com/v1",
         mistral_api_key="<key>",
)

```

**Comment by BERRADA-Omar** [comment]
@adsellor this solves the issue indeed ! thank you

**Comment by paluchasz** [comment]
Experienced the same issue with direct call to the Mistral api. After: `httpx - HTTP Request: POST https://api.mistral.ai/v1/chat/completions "HTTP/1.1 504 Gateway Timeout"` 

```
langchain_mistralai/chat_models.py", line 392, in _create_chat_result
    for res in response["choices"]:
KeyError: 'choices'
```
