### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'int' and 'simsimd.DistancesTensor'

### ISSUE THREAD

**Issue by amitjoy** [langchain-ai/langchain#19905]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
_embedding = VertexAIEmbeddings(project="PROJECT_ID",
                                             credentials=gcp_auth.credentials,
                                             model_name="textembedding-gecko@003",
                                             location="PROJECT_LOCATION")

 _db = PGVector(connection_string="CONN",
                            collection_name="COLLECTION_NAME",
                            embedding_function=_embedding,
                            use_jsonb=True)

_db.search(query="test", search_type="mmr")
```

### Error Message and Stack Trace (if applicable)

```
Traceback (most recent call last):
  File "/Users/amit/telly/telly-backend/backend/agent/healthcheck/components/hc_vector_db.py", line 29, in check_health
    db.search(query="test", search_type=self.settings.vector_db.retriever.type)
  File "/Users/amit/telly/telly-backend/backend/venv/lib/python3.12/site-packages/langchain_core/vectorstores.py", line 160, in search
    return self.max_marginal_relevance_search(query, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amit/telly/telly-backend/backend/venv/lib/python3.12/site-packages/langchain_community/vectorstores/pgvector.py", line 1236, in max_marginal_relevance_search
    return self.max_marginal_relevance_search_by_vector(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amit/telly/telly-backend/backend/venv/lib/python3.12/site-packages/langchain_community/vectorstores/pgvector.py", line 1314, in max_marginal_relevance_search_by_vector
    docs_and_scores = self.max_marginal_relevance_search_with_score_by_vector(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amit/telly/telly-backend/backend/venv/lib/python3.12/site-packages/langchain_community/vectorstores/pgvector.py", line 1196, in max_marginal_relevance_search_with_score_by_vector
    mmr_selected = maximal_marginal_relevance(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amit/telly/telly-backend/backend/venv/lib/python3.12/site-packages/langchain_community/vectorstores/utils.py", line 34, in maximal_marginal_relevance
    similarity_to_query = cosine_similarity(query_embedding, embedding_list)[0]
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amit/telly/telly-backend/backend/venv/lib/python3.12/site-packages/langchain_community/utils/math.py", line 29, in cosine_similarity
    Z = 1 - simd.cdist(X, Y, metric="cosine")
        ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'int' and 'simsimd.DistancesTensor'
           INFO     Cannot execute Healthcheck: hc-vector-db  hc_vector_db.py:33
```

### Description

Library Versions Used:
* langchain~=0.1.14
* langchain-google-vertexai~=0.1.2
* simsimd~=4.2.2

### System Info

NA

**Comment by liugddx** [comment]
Let me see

**Comment by QiuruiChen** [comment]
i also enounter the similar problem with  LaserEmbeddings embedding:(

**Comment by QiuruiChen** [comment]
installing simsimd == 3.7.7 works for me from [andy-tmpt-me](https://github.com/andy-tmpt-me)'s answer.
https://github.com/langchain-ai/langchain/issues/18022
