### ISSUE TITLE
DOC: <Please write a comprehensive title after the 'DOC: ' prefix>

### ISSUE THREAD

**Issue by AbdulHadi806** [langchain-ai/langchain#20619]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

#Langchain arguments to the tool are not passing correctly

### Error
Im having this error with all tools, basically the llm is unable to pass whole arguments to the tools in my case only a is being passed.
`Traceback (most recent call last):
  File "d:\chatbots\360 agent - Jarvis\main.py", line 47, in <module>
    main()
  File "d:\chatbots\360 agent - Jarvis\main.py", line 45, in main
    chain.invoke("What is 3 * 12?")
  File "C:\Users\Dev\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain_core\runnables\base.py", line 2075, in invoke
    input = step.invoke(
            ^^^^^^^^^^^^
  File "C:\Users\Dev\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain_core\runnables\base.py", line 3523, in invoke
    return self._call_with_config(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dev\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain_core\runnables\base.py", line 1262, in _call_with_config
    context.run(
  File "C:\Users\Dev\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain_core\runnables\config.py", line 326, in call_func_with_variable_args
    return func(input, **kwargs)  # type: ignore[call-arg]
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dev\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain_core\runnables\base.py", line 3397, in _invoke
    output = call_func_with_variable_args(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dev\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain_core\runnables\config.py", line 326, in call_func_with_variable_args
    return func(input, **kwargs)  # type: ignore[call-arg]
           ^^^^^^^^^^^^^^^^^^^^^
  File "d:\chatbots\360 agent - Jarvis\main.py", line 39, in call_tools
    tool_call["output"] = tool_map[tool_call["function"]["name"]].invoke(tool_call["function"]["arguments"])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dev\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain_core\tools.py", line 240, in invoke
    return self.run(
           ^^^^^^^^^
  File "C:\Users\Dev\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain_core\tools.py", line 382, in run
    raise e
  File "C:\Users\Dev\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain_core\tools.py", line 373, in run
    parsed_input = self._parse_input(tool_input)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dev\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain_core\tools.py", line 276, in _parse_input
    input_args.validate({key_: tool_input})
  File "C:\Users\Dev\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\v1\main.py", line 711, in validate
    return cls(**value)
           ^^^^^^^^^^^^
  File "C:\Users\Dev\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\v1\main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for multiplySchema
b
  field required (type=value_error.missing)`
### My code:
`from langchain_core.tools import tool
from langchain_openai import ChatOpenAI
from langchain_core.messages import AIMessage
from langchain_core.runnables import (
    Runnable,
    RunnableLambda,
    RunnableMap,
    RunnablePassthrough,
)
import json
@tool
def add(a: int, b: int) -> int:
    """Adds a and b."""
    return a + b

@tool
def multiply(a, b):
    """Multiplies a and b."""
    print(b)
    return b

@tool
def exponentiate(base, exponent):
    """Exponentiate the base to the exponent power."""
    return base**exponent

def main():
    llm = ChatOpenAI(model="gpt-3.5-turbo-0613",  openai_api_key="your_key")
    tools = [multiply, exponentiate, add]
    llm_with_tools = llm.bind_tools(tools)

    def call_tools(msg: AIMessage) -> Runnable:
        """Simple sequential tool calling helper."""
        tool_map = {tool.name: tool for tool in tools}
        tool_calls = msg.additional_kwargs['tool_calls']
        for tool_call in tool_calls:
            print(tool_map[tool_call["function"]["name"]], 'tool_call["function"]["naasdme"as]')
            tool_call["output"] = tool_map[tool_call["function"]["name"]].invoke(tool_call["function"]["arguments"])
        print(tool_calls, ':tool_calls')
        return tool_calls

    chain = llm_with_tools | call_tools
    chain.invoke("What is 3 * 12?")
if '__main__':
    main()`

I would also love if you can explain the code a bit the langchain documentation explains nothing. 

Docs that I followed [https://python.langchain.com/docs/use_cases/tool_use/multiple_tools/](https://python.langchain.com/docs/use_cases/tool_use/multiple_tools/)

### Idea or request for content:

You should I also provide json and step by step code on how the agent, chatbot or functions are working.

**Comment by sepiatone** [comment]
@AbdulHadi806 This [page](https://python.langchain.com/docs/modules/model_io/chat/function_calling/)  explains LangChain tool calling (also called function calling) feature, including the `bind_tools` method of a model supporting this feature and the `tool_calls` attribute of the message returned by the model.
