### ISSUE TITLE
Cannot import ChatGroq  `ImportError: cannot import name 'make_invalid_tool_call' from 'langchain_core.output_parsers.openai_tools'`

### ISSUE THREAD

**Issue by Travis-Barton** [langchain-ai/langchain#20714]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

simply the following code:
```
from langchain_groq import ChatGroq
from llm_utils import get_chat_prompt

chat = ChatGroq(temperature=0.7,
                groq_api_key="API_KEY",
                model_name="mixtral-8x7b-32768")
```

causes the failure:

```
ImportError: cannot import name 'make_invalid_tool_call' from 'langchain_core.output_parsers.openai_tools' (/Users/travisbarton/opt/anaconda3/envs/trivia-gpt-backend39/lib/python3.9/site-packages/langchain_core/output_parsers/openai_tools.py)
```

### Error Message and Stack Trace (if applicable)

```Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/travisbarton/opt/anaconda3/envs/trivia-gpt-backend39/lib/python3.9/site-packages/langchain_groq/__init__.py", line 1, in <module>
    from langchain_groq.chat_models import ChatGroq
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/travisbarton/opt/anaconda3/envs/trivia-gpt-backend39/lib/python3.9/site-packages/langchain_groq/chat_models.py", line 58, in <module>
    from langchain_core.output_parsers.openai_tools import (
ImportError: cannot import name 'make_invalid_tool_call' from 'langchain_core.output_parsers.openai_tools' (/Users/travisbarton/opt/anaconda3/envs/trivia-gpt-backend39/lib/python3.9/site-packages/langchain_core/output_parsers/openai_tools.py)
```

### Description

Just the import seems to be broken 

### System Info

```

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:49 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6020
> Python Version:  3.9.19 (main, Mar 21 2024, 12:08:14) 
[Clang 14.0.6 ]

Package Information
-------------------
> langchain_core: 0.1.45
> langchain: 0.1.14
> langchain_community: 0.0.31
> langsmith: 0.1.38
> langchain_anthropic: 0.1.4
> langchain_groq: 0.1.2
> langchain_openai: 0.1.1
> langchain_text_splitters: 0.0.1

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve

```

**Comment by qingdengyue** [comment]
try `pip install langchain-groq`? if jupyter need reboot kernel

**Comment by zlinksphinx** [comment]
+1 I am facing the same issue, langchain-groq is installed, else it would show langchain_groq not found

**Comment by TheRealPolatic** [comment]
Facing the same issue with multiple integrations (ChatFireworks, ChatOctoAI to name two)

**Comment by sahandilshan** [comment]
The problem is that you all might have specified a specific `langchain-core` version. `langchain-groq` install a newer version of `langchain-core` pip and it uninstalls the previous `langchain-core` version in the process. So if you have specified a `langchain-core` version in the requirement.txt, make sure to update it to a latest version

![Screenshot 2024-05-09 at 6 20 15 PM](https://github.com/langchain-ai/langchain/assets/32576163/85b2e9ff-ae87-4a4f-8873-19204315c501)

**Comment by davidkgp** [comment]
I deleted the langchain-core lib from my venv and restarted the kernel , seems that worked for me
