### ISSUE TITLE
Vertex AI Gemini video support

### ISSUE THREAD

**Issue by WaterKnight1998** [langchain-ai/langchain#20738]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
import base64
import json
import os

import vertexai
from google.oauth2.service_account import Credentials
from langchain_core.messages.human import HumanMessage
from langchain_google_vertexai import ChatVertexAI

llm_model = ChatVertexAI(
    model_name="gemini-1.5-pro-preview-0409",
    convert_system_message_to_human=True,
    temperature=0.7,
)

with open("/Users/david/Downloads/1713170355070_sample_1.mp4", "rb") as f:
    video_b64 = base64.b64encode(f.read()).decode("utf-8")


google_credentials = Credentials.from_service_account_info(
    json.loads(os.getenv("GCP_LIC"), strict=False)
)
vertexai.init(
    project=os.getenv("GCP_PROJECT_ID"),
    location=os.getenv("GCP_REGION"),
    credentials=google_credentials,
)


res = llm_model.invoke(
    [
        HumanMessage(
            content=[
                {"type": "text", "text": "Summary of video"},
                {"type": "media", "mimeType": "video/mp4", "data": video_b64},
            ]
        ),
    ]
)

print(res)

```

JS Code Example: https://js.langchain.com/docs/use_cases/media

### Error Message and Stack Trace (if applicable)

```
Traceback (most recent call last):
  File "/Users/david/Documents/test2/langchain_error.py", line 30, in <module>
    res = llm_model.invoke(
  File "/Users/david/Documents/test2/.venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 158, in invoke
    self.generate_prompt(
  File "/Users/david/Documents/test2/.venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 560, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
  File "/Users/david/Documents/test2/.venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 421, in generate
    raise e
  File "/Users/david/Documents/test2/.venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 411, in generate
    self._generate_with_cache(
  File "/Users/david/Documents/test2/.venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 632, in _generate_with_cache
    result = self._generate(
  File "/Users/david/Documents/test2/.venv/lib/python3.10/site-packages/langchain_google_vertexai/chat_models.py", line 497, in _generate
    system_instruction, history_gemini = _parse_chat_history_gemini(
  File "/Users/david/Documents/test2/.venv/lib/python3.10/site-packages/langchain_google_vertexai/chat_models.py", line 215, in _parse_chat_history_gemini
    parts = _convert_to_parts(message)
  File "/Users/david/Documents/test2/.venv/lib/python3.10/site-packages/langchain_google_vertexai/chat_models.py", line 166, in _convert_to_parts
    return [_convert_to_prompt(part) for part in raw_content]
  File "/Users/david/Documents/test2/.venv/lib/python3.10/site-packages/langchain_google_vertexai/chat_models.py", line 166, in <listcomp>
    return [_convert_to_prompt(part) for part in raw_content]
  File "/Users/david/Documents/test2/.venv/lib/python3.10/site-packages/langchain_google_vertexai/chat_models.py", line 160, in _convert_to_prompt
    raise ValueError("Only text and image_url types are supported!")
ValueError: Only text and image_url types are supported!
```

### Description

- I would expect this to work as this sample code is based on JS sample.

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.3.0: Wed Dec 20 21:31:00 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6020
> Python Version:  3.10.0 (default, Nov 11 2023, 18:46:15) [Clang 15.0.0 (clang-1500.0.40.1)]

Package Information
-------------------
> langchain_core: 0.1.45
> langchain: 0.1.16
> langchain_community: 0.0.34
> langsmith: 0.1.49
> langchain_anthropic: 0.1.11
> langchain_error: Installed. No version info available.
> langchain_google_vertexai: 1.0.1
> langchain_openai: 0.0.8
> langchain_text_splitters: 0.0.1
> langchainhub: 0.1.15

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve

**Comment by yikai-presien** [comment]
I think video support in python need to added! I faced the same issue as well!

**Comment by pelguetat** [comment]
Having the same issue. Lack of documentation on Google's part is also a problem.

**Comment by braca51e** [comment]
same here! Any progress on this?

**Comment by jdelard** [comment]
We need this feature urgently to be able to use Langchain in our company. (and Langsmith subsequently)
