### ISSUE TITLE
The tool cannot be called correctly when calling the Groq model through langchain——KeyError: 'tool_calls'

### ISSUE THREAD

**Issue by SheldonLiu0412** [langchain-ai/langchain#20811]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

memory = ConversationBufferMemory(
    memory_key="chat_history", return_messages=True
)
prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            "You are a helpful assistant, designed to use tools tell me the distance between cities.",
        ),
        ("placeholder", "{chat_history}"),
        ("human", "{input}"),
        ("placeholder", "{agent_scratchpad}"),
    ]
)

tools=load_tools(['wolfram-alpha'])

agent = create_tool_calling_agent(
 llm = ChatGroq(temperature=0,
               model_name="llama3-8b-8192"),
 tools=tools,
 prompt=prompt,
)
agent_executor = AgentExecutor(agent=agent, tools=tools, memory=memory,verbose=True)
agent_executor.invoke({"input": "How far is New York City to Tokyo?"})

### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "/Users/jay/pythonProject/Wolfram-lc-Groq-llama3.py", line 33, in <module>
    agent_executor.invoke({"input": "How far is New York City to Tokyo?"})
  File "/Users/jay/opt/anaconda3/envs/langchain/lib/python3.10/site-packages/langchain/chains/base.py", line 163, in invoke
    raise e
  File "/Users/jay/opt/anaconda3/envs/langchain/lib/python3.10/site-packages/langchain/chains/base.py", line 153, in invoke
    self._call(inputs, run_manager=run_manager)
  File "/Users/jay/opt/anaconda3/envs/langchain/lib/python3.10/site-packages/langchain/agents/agent.py", line 1432, in _call
    next_step_output = self._take_next_step(
  File "/Users/jay/opt/anaconda3/envs/langchain/lib/python3.10/site-packages/langchain/agents/agent.py", line 1138, in _take_next_step
    [
  File "/Users/jay/opt/anaconda3/envs/langchain/lib/python3.10/site-packages/langchain/agents/agent.py", line 1138, in <listcomp>
    [
  File "/Users/jay/opt/anaconda3/envs/langchain/lib/python3.10/site-packages/langchain/agents/agent.py", line 1166, in _iter_next_step
    output = self.agent.plan(
  File "/Users/jay/opt/anaconda3/envs/langchain/lib/python3.10/site-packages/langchain/agents/agent.py", line 514, in plan
    for chunk in self.runnable.stream(inputs, config={"callbacks": callbacks}):
  File "/Users/jay/opt/anaconda3/envs/langchain/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2875, in stream
    yield from self.transform(iter([input]), config, **kwargs)
  File "/Users/jay/opt/anaconda3/envs/langchain/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2862, in transform
    yield from self._transform_stream_with_config(
  File "/Users/jay/opt/anaconda3/envs/langchain/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1880, in _transform_stream_with_config
    chunk: Output = context.run(next, iterator)  # type: ignore
  File "/Users/jay/opt/anaconda3/envs/langchain/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2826, in _transform
    for output in final_pipeline:
  File "/Users/jay/opt/anaconda3/envs/langchain/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1283, in transform
    for chunk in input:
  File "/Users/jay/opt/anaconda3/envs/langchain/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 4728, in transform
    yield from self.bound.transform(
  File "/Users/jay/opt/anaconda3/envs/langchain/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1300, in transform
    yield from self.stream(final, config, **kwargs)
  File "/Users/jay/opt/anaconda3/envs/langchain/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 249, in stream
    raise e
  File "/Users/jay/opt/anaconda3/envs/langchain/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 229, in stream
    for chunk in self._stream(messages, stop=stop, **kwargs):
  File "/Users/jay/opt/anaconda3/envs/langchain/lib/python3.10/site-packages/langchain_groq/chat_models.py", line 290, in _stream
    for rtc in message.additional_kwargs["tool_calls"]
KeyError: 'tool_calls'

### Description

The tool cannot be called correctly when calling the Groq model through langchain.
It would be perfectly fine to switch the model here to gpt3.5, but I would like to use other models like llama3, gemini, etc. It seems that only openai can call multiple tools through proxies very well
I guess it may be an agent problem, but I really don't know how to customize a suitable agent to solve the problem

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:41 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8103
> Python Version:  3.10.12 (main, Jul  5 2023, 15:34:07) [Clang 14.0.6 ]

Package Information
-------------------
> langchain_core: 0.1.45
> langchain: 0.1.16
> langchain_community: 0.0.34
> langsmith: 0.1.38
> langchain_cli: 0.0.21
> langchain_decorators: 0.5.4
> langchain_experimental: 0.0.56
> langchain_google_genai: 1.0.1
> langchain_google_vertexai: 0.1.2
> langchain_groq: 0.1.2
> langchain_openai: 0.1.1
> langchain_text_splitters: 0.0.1
> langchainhub: 0.1.15
> langserve: 0.1.0

**Comment by lzy83925** [comment]
me the same

**Comment by hussein987** [comment]
@efriis So how to basically include the fix while it's not in a tagged release of langchain?

**Comment by ccurme** [comment]
Release just went through, let me know if there are still issues.

**Comment by hussein987** [comment]
@ccurme Yeah, it's working now, I had to install langchain from source though.

**Comment by ardakocaman100101** [comment]
@ccurme I updated the langchain_groq library but still getting this same error

**Comment by SheldonLiu0412** [comment]
> @ccurme Yeah, it's working now, I had to install langchain from source though.

This fix is not currently in the tagged version, may I ask you how to install langchain through the source code, thank you @hussein987

**Comment by SheldonLiu0412** [comment]
> pip install -e .

I'll create a new virtual environment and try it out, thanks! @hussein987
