### ISSUE TITLE
set_llm_cache doesn't work. Returns TimeoutError: Didn't ever...

### ISSUE THREAD

**Issue by mrbuslov** [langchain-ai/langchain#20882]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

Example is taken from [this cookbook](https://github.com/langchain-ai/langchain/blob/master/cookbook/mongodb-langchain-cache-memory.ipynb)
```
import time
from langchain_mongodb import MongoDBAtlasVectorSearch
from pymongo import MongoClient
from langchain_openai import OpenAIEmbeddings
from langchain.callbacks.manager import get_openai_callback
from langchain_core.globals import set_llm_cache
from langchain_mongodb.cache import MongoDBAtlasSemanticCache


DB_NAME = "vector-search-db"
COLLECTION_NAME = "vector-search"
ATLAS_VECTOR_SEARCH_INDEX_NAME = "test-vector-index"
MONGODB_URI = ""
client = MongoClient(MONGODB_URI, appname="devrel.content.python")
collection = client[DB_NAME][COLLECTION_NAME]
OPENAI_API_KEY = ''



# Using the text-embedding-ada-002 since that's what was used to create embeddings in the movies dataset
embeddings = OpenAIEmbeddings(
    openai_api_key=OPENAI_API_KEY, model="text-embedding-ada-002"
)

vector_store = MongoDBAtlasVectorSearch.from_connection_string(
    connection_string=MONGODB_URI,
    namespace=DB_NAME + "." + COLLECTION_NAME,
    embedding=embeddings,
    index_name=ATLAS_VECTOR_SEARCH_INDEX_NAME,
)


retriever = vector_store.as_retriever(search_type="similarity", search_kwargs={"k": 5})
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_openai import ChatOpenAI

# Generate context using the retriever, and pass the user question through
retrieve = {
    "context": retriever | (lambda docs: "\n\n".join([d.page_content for d in docs])),
    "question": RunnablePassthrough(),
}
template = """Answer the question based only on the following context: \
{context}

Question: {question}
"""
# Defining the chat prompt
prompt = ChatPromptTemplate.from_template(template)
# Defining the model to be used for chat completion
model = ChatOpenAI(temperature=0, openai_api_key=OPENAI_API_KEY)
# Parse output as a string
parse_output = StrOutputParser()

# Naive RAG chain
naive_rag_chain = retrieve | prompt | model | parse_output



set_llm_cache(
    MongoDBAtlasSemanticCache(
        connection_string=MONGODB_URI,
        embedding=embeddings,
        collection_name="semantic_cache",
        database_name=DB_NAME,
        index_name=ATLAS_VECTOR_SEARCH_INDEX_NAME,
        wait_until_ready=True,
    )
)

question = "When formally independence was declared?"

with get_openai_callback() as cb:
    start = time.time()
    res = naive_rag_chain.invoke(question)
    end = time.time()
    if naive_rag_chain:
        print(res)
        print("--- cb")
        print(str(cb) + f"({end - start:.2f} seconds)")
    else:
        print('no compressed_docs')


with get_openai_callback() as cb:
    start = time.time()
    res = naive_rag_chain.invoke(question)
    end = time.time()
    if naive_rag_chain:
        print(res)
        print("--- cb")
        print(str(cb) + f"({end - start:.2f} seconds)")
    else:
        print('no compressed_docs')
```

### Error Message and Stack Trace (if applicable)

```
Traceback (most recent call last):
  File "/home/dmitry/Desktop/vector-search-from-cookbook.py", line 77, in <module>
    res = naive_rag_chain.invoke(question)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmitry/.pyenv/versions/3.11.6/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 2499, in invoke
    input = step.invoke(
            ^^^^^^^^^^^^
  File "/home/dmitry/.pyenv/versions/3.11.6/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 158, in invoke
    self.generate_prompt(
  File "/home/dmitry/.pyenv/versions/3.11.6/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 560, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmitry/.pyenv/versions/3.11.6/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 421, in generate
    raise e
  File "/home/dmitry/.pyenv/versions/3.11.6/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 411, in generate
    self._generate_with_cache(
  File "/home/dmitry/.pyenv/versions/3.11.6/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 651, in _generate_with_cache
    llm_cache.update(prompt, llm_string, result.generations)
  File "/home/dmitry/.pyenv/versions/3.11.6/lib/python3.11/site-packages/langchain_mongodb/cache.py", line 293, in update
    _wait_until(is_indexed, return_val)
  File "/home/dmitry/.pyenv/versions/3.11.6/lib/python3.11/site-packages/langchain_mongodb/cache.py", line 119, in _wait_until
    raise TimeoutError("Didn't ever %s" % success_description)
TimeoutError: Didn't ever [ChatGeneration(text='Independence was formally declared on July 4, 1776.', generation_info={'finish_reason': 'stop', 'logprobs': None}, message=AIMessage(content='Independence was formally declared on July 4, 1776.', response_metadata={'token_usage': {'completion_tokens': 14, 'prompt_tokens': 639, 'total_tokens': 653}, 'model_name': 'gpt-3.5-turbo', 'system_fingerprint': 'fp_c2295e73ad', 'finish_reason': 'stop', 'logprobs': None}, id='run-0295bd5f-b95e-4b85-98ee-f3bcc8a1cdec-0'))]
```

### Description

I was following this Example from [this cookbook](https://github.com/langchain-ai/langchain/blob/master/cookbook/mongodb-langchain-cache-memory.ipynb)
I loaded own data (splitted text by paragraphs and uploaded to mongo db with this code (using the same index)
```
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000, 
    chunk_overlap=0, 
    separators=["\n\n", "\n", "(?<=\. )", " "], 
    length_function=len
)

# split by \n
docs = text_splitter.split_text(data)
print(docs)

client = MongoClient(mongodb_conn_string)
collection = client[db_name][collection_name]

# Insert the documents in MongoDB Atlas with their embedding
docsearch = MongoDBAtlasVectorSearch.from_texts(
    docs, 
    embeddings, 
    collection=collection, 
    index_name=vector_index_name
)
```
So data is uploaded like this:
![image](https://github.com/langchain-ai/langchain/assets/68155915/3138bd2d-9c52-4ef4-964b-9105826b7341)

The problem is, that when I don't use `wait_until_ready` param in set_llm_cache, it returns relevant results, BUT without taking it from cache - the executing time is the same:
```
--- cb
Tokens Used: 653
        Prompt Tokens: 639
        Completion Tokens: 14
Successful Requests: 1
Total Cost (USD): $0.0009865(5.72 seconds)

Independence was formally declared on July 4, 1776.
--- cb
Tokens Used: 653
        Prompt Tokens: 639
        Completion Tokens: 14
Successful Requests: 1
Total Cost (USD): $0.0009865(3.00 seconds)
``` 
So I ran it multiple times, 5-6 secs remain.
I assume we don't wait cache indexing, but with `wait_until_ready` it raises error.

Though something is being written in cache collection
![image](https://github.com/langchain-ai/langchain/assets/68155915/f4960177-4a07-46e0-b94f-eeb8b8bf860b)

My vector settings
![image](https://github.com/langchain-ai/langchain/assets/68155915/c218afe1-af64-4c8f-9881-74d84f9c5a39)

### System Info

```
langchain==0.1.16
langchain-anthropic==0.1.6
langchain-community==0.0.34
langchain-core==0.1.45
langchain-mongodb==0.1.3
langchain-openai==0.1.3
langchain-text-splitters==0.0.1
```

**Comment by Hadi2525** [comment]
I have bumped into the same error and still can't figure out how to solve this.
