### ISSUE TITLE
Groq can not work

### ISSUE THREAD

**Issue by Rainismer** [langchain-ai/langchain#21061]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

from langchain_core.prompts import ChatPromptTemplate
from langchain_groq import ChatGroq

chat = ChatGroq(
    temperature=0,
    api_key="xxxxxxxxxx",
    model="llama3-70b-8192"
)

system = "You are a helpful assistant."
human = "{text}"
prompt = ChatPromptTemplate.from_messages([("system", system), ("human", human)])

chain = prompt | chat
result = chain.invoke({"text": "Explain the importance of low latency LLMs."})
print(result.content)

### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "D:\AIGC\idataai_py\test\groq.py", line 7, in <module>
    chat = ChatGroq(
           ^^^^^^^^^
  File "D:\AIGC\idataai_py\venv\Lib\site-packages\langchain_core\load\serializable.py", line 120, in __init__
    super().__init__(**kwargs)
  File "D:\AIGC\idataai_py\venv\Lib\site-packages\pydantic\v1\main.py", line 339, in __init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AIGC\idataai_py\venv\Lib\site-packages\pydantic\v1\main.py", line 1100, in validate_model
    values = validator(cls_, values)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AIGC\idataai_py\venv\Lib\site-packages\langchain_groq\chat_models.py", line 190, in validate_environment
    import groq
  File "D:\AIGC\idataai_py\test\groq.py", line 7, in <module>
    chat = ChatGroq(
           ^^^^^^^^^
  File "D:\AIGC\idataai_py\venv\Lib\site-packages\langchain_core\load\serializable.py", line 120, in __init__
    super().__init__(**kwargs)
  File "D:\AIGC\idataai_py\venv\Lib\site-packages\pydantic\v1\main.py", line 339, in __init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AIGC\idataai_py\venv\Lib\site-packages\pydantic\v1\main.py", line 1100, in validate_model
    values = validator(cls_, values)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AIGC\idataai_py\venv\Lib\site-packages\langchain_groq\chat_models.py", line 193, in validate_environment
    values["client"] = groq.Groq(**client_params).chat.completions
                       ^^^^^^^^^
AttributeError: partially initialized module 'groq' has no attribute 'Groq' (most likely due to a circular import)

### Description

I am testing groq with langchain

### System Info

win10
python 3.11

**Comment by Mao-Siang** [comment]
Try not to name your file `groq.py`? There might be a circular import as the error shows. Your code works for me.
