### ISSUE TITLE
Error when running the tutorial codes (retrieval) by langchain: unexpected keyword argument 'context'

### ISSUE THREAD

**Issue by jygeucd** [langchain-ai/langchain#21234]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

The following codes were copied from https://github.com/hwchase17/langchain-0.1-guides/blob/master/retrieval.ipynb. Nothing was changed. 

```
from dotenv import load_dotenv, find_dotenv
load_dotenv(find_dotenv())

from langchain_community.document_loaders import WebBaseLoader
loader = WebBaseLoader("https://docs.smith.langchain.com/overview")

docs = loader.load()

from langchain.text_splitter import RecursiveCharacterTextSplitter


text_splitter = RecursiveCharacterTextSplitter()
documents = text_splitter.split_documents(docs)

from langchain_openai import OpenAIEmbeddings
from langchain_community.vectorstores import FAISS

embeddings = OpenAIEmbeddings()
vector = FAISS.from_documents(documents, embeddings)
```

### Error Message and Stack Trace (if applicable)

```
Traceback (most recent call last):
  File "/Users/jyg/Documents/Programs/Codes/RAG/src/EarlyInvestigation/test_retrieval.py", line 19, in <module>
    vector = FAISS.from_documents(documents, embeddings)
  File "/Users/jyg/anaconda3/envs/genv/lib/python3.10/site-packages/langchain_core/vectorstores.py", line 550, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
  File "/Users/jyg/anaconda3/envs/genv/lib/python3.10/site-packages/langchain_community/vectorstores/faiss.py", line 930, in from_texts
    embeddings = embedding.embed_documents(texts)
  File "/Users/jyg/anaconda3/envs/genv/lib/python3.10/site-packages/langchain_openai/embeddings/base.py", line 489, in embed_documents
    return self._get_len_safe_embeddings(texts, engine=engine)
  File "/Users/jyg/anaconda3/envs/genv/lib/python3.10/site-packages/langchain_openai/embeddings/base.py", line 351, in _get_len_safe_embeddings
    response = response.model_dump()
  File "/Users/jyg/anaconda3/envs/genv/lib/python3.10/site-packages/pydantic/main.py", line 347, in model_dump
    return self.__pydantic_serializer__.to_python(
TypeError: SchemaSerializer.to_python() got an unexpected keyword argument 'context' 



### Description

The codes were copied from https://github.com/hwchase17/langchain-0.1-guides/blob/master/retrieval.ipynb. Nothing was changed. I also updated my langchain, langchain-community, and langchain-openai to latest versions.

```

### System Info
```
langchain==0.1.17
langchain-ai21==0.1.3
langchain-community==0.0.36
langchain-core==0.1.50
langchain-experimental==0.0.57
langchain-google-genai==1.0.2
langchain-groq==0.0.1
langchain-openai==0.1.6
langchain-text-splitters==0.0.1
```

**Comment by adnanrahin** [comment]
If you are running your code locally, Like using Ollama or LM-Studio, I suggest change the below
`vector = FAISS.from_documents(documents, embeddings`
`vector = Chroma.from_documents(documents, embeddings )`

**Comment by jygeucd** [comment]
I did another test. It seems the error may not be related to faiss or embeddings, but probably the conda environment.

In my current env, I have the following packages, and the run failed with error
```
$ pip freeze | grep langchain
langchain==0.1.17
langchain-ai21==0.1.3
langchain-community==0.0.36
langchain-core==0.1.50
langchain-experimental==0.0.57
langchain-google-genai==1.0.3
langchain-groq==0.0.1
langchain-openai==0.1.6
langchain-text-splitters==0.0.1
```

I setup another new environment, and the run was successful.  

```
$ pip freeze | grep langchain
langchain==0.1.17
langchain-community==0.0.36
langchain-core==0.1.50
langchain-google-genai==1.0.3
langchain-openai==0.1.6
langchain-text-splitters==0.0.1
```

The versions of the langchain related packages look the same. And the codes are super simple. There must be some wrong with the dependencies, I guess. 

Then I switched to Chroma, but failed because of an old pydantic version. So I upgrade pydantic with "pip install pydantic --upgrade". Then, both Chroma and FAISS worked. 

So, I guess the error was because of the old version of pydantic.
