### ISSUE TITLE
LocalProtocolError: Illegal header value b'Bearer '

### ISSUE THREAD

**Issue by andysingal** [langchain-ai/langchain#21261]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```py
!pip install langchain_openai langchain-core langchain-mistralai -qU

from typing import Optional

from langchain_core.pydantic_v1 import BaseModel, Field


class Person(BaseModel):
    """Information about a person."""

    # ^ Doc-string for the entity Person.
    # This doc-string is sent to the LLM as the description of the schema Person,
    # and it can help to improve extraction results.

    # Note that:
    # 1. Each field is an `optional` -- this allows the model to decline to extract it!
    # 2. Each field has a `description` -- this description is used by the LLM.
    # Having a good description can help improve extraction results.
    name: Optional[str] = Field(default=None, description="The name of the person")
    hair_color: Optional[str] = Field(
        default=None, description="The color of the peron's hair if known"
    )
    height_in_meters: Optional[str] = Field(
        default=None, description="Height measured in meters"
    )

from typing import Optional

from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.pydantic_v1 import BaseModel, Field
from langchain_openai import ChatOpenAI

# Define a custom prompt to provide instructions and any additional context.
# 1) You can add examples into the prompt template to improve extraction quality
# 2) Introduce additional parameters to take context into account (e.g., include metadata
#    about the document from which the text was extracted.)
prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            "You are an expert extraction algorithm. "
            "Only extract relevant information from the text. "
            "If you do not know the value of an attribute asked to extract, "
            "return null for the attribute's value.",
        ),
        # Please see the how-to about improving performance with
        # reference examples.
        # MessagesPlaceholder('examples'),
        ("human", "{text}"),
    ]
)

from langchain_mistralai import ChatMistralAI

llm = ChatMistralAI(model="mistral-large-latest", temperature=0)

runnable = prompt | llm.with_structured_output(schema=Person)

text = "Alan Smith is 6 feet tall and has blond hair."
runnable.invoke({"text": text})

```

### Error Message and Stack Trace (if applicable)

```
---------------------------------------------------------------------------
LocalProtocolError                        Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py](https://localhost:8080/#) in map_httpcore_exceptions()
     68     try:
---> 69         yield
     70     except Exception as exc:

28 frames
LocalProtocolError: Illegal header value b'Bearer '

The above exception was the direct cause of the following exception:

LocalProtocolError                        Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py](https://localhost:8080/#) in map_httpcore_exceptions()
     84 
     85         message = str(exc)
---> 86         raise mapped_exc(message) from exc
     87 
     88 

LocalProtocolError: Illegal header value b'Bearer '

```

### Description

Trying https://python.langchain.com/docs/use_cases/extraction/quickstart/ 

### System Info

```

System Information
------------------
> OS:  Linux
> OS Version:  #1 SMP PREEMPT_DYNAMIC Sat Nov 18 15:31:17 UTC 2023
> Python Version:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

Package Information
-------------------
> langchain_core: 0.1.50
> langsmith: 0.1.53
> langchain_mistralai: 0.1.6
> langchain_openai: 0.1.6

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve
```

**Comment by conditionedstimulus** [comment]
You're missing the API key, and you'll need to read it using dotenv. If you're using Mistral, create the API key in your Mistral account. If you're using OpenAI, generate the API key there instead.


It's also part of the documentation:
```
# Set env vars for the relevant model or load from a .env file:
import dotenv
dotenv.load_dotenv()
```

**Comment by andysingal** [comment]
Thanks David , I guess I need to add my Mistral key in  .env . Can you
please update the docs too. Thanks Again!!

**Comment by MusanjeRichard5** [comment]
I am also using Mistral Api but am receiving the same error

**Comment by Antony-M1** [comment]
Hello I am getting this error from my CI/CD pipeline. I'm using the github actions when the github workflow is running I'm getting this error.

```py
Run python codex_code_generator.py > generated_code.py
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.[12](https://github.com/Antony-M1/CodePipelineX/actions/runs/11181621969/job/31086064363#step:6:13)/x64/lib/python3.10/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 101, in handle_request
    return self._connection.handle_request(request)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/httpcore/_sync/http11.py", line [14](https://github.com/Antony-M1/CodePipelineX/actions/runs/11181621969/job/31086064363#step:6:15)3, in handle_request
    raise exc
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 93, in handle_request
    self._send_request_headers(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/httpcore/_sync/http11.py", line [15](https://github.com/Antony-M1/CodePipelineX/actions/runs/11181621969/job/31086064363#step:6:16)1, in _send_request_headers
    with map_exceptions({h11.LocalProtocolError: LocalProtocolError}):
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.LocalProtocolError: Illegal header value b'Bearer '

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/openai/_base_client.py", line 983, in _request
    response = self._client.send(
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/httpx/_transports/default.py", line 235, in handle_request
    with map_httpcore_exceptions():
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.LocalProtocolError: Illegal header value b'Bearer '

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/CodePipelineX/CodePipelineX/codex_code_generator.py", line 30, in <module>
    generated_code = generate_code(prompt)
  File "/home/runner/work/CodePipelineX/CodePipelineX/codex_code_generator.py", line [16](https://github.com/Antony-M1/CodePipelineX/actions/runs/11181621969/job/31086064363#step:6:17), in generate_code
    response = openai.completions.create(
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/openai/resources/completions.py", line 539, in create
    return self._post(
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/openai/_base_client.py", line 1270, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/openai/_base_client.py", line 947, in request
    return self._request(
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/openai/_base_client.py", line 1007, in _request
    return self._retry_request(
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/openai/_base_client.py", line 1085, in _retry_request
    return self._request(
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/openai/_base_client.py", line 1007, in _request
    return self._retry_request(
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/openai/_base_client.py", line 1085, in _retry_request
    return self._request(
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/openai/_base_client.py", line 10[17](https://github.com/Antony-M1/CodePipelineX/actions/runs/11181621969/job/31086064363#step:6:18), in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.
```

**Comment by tkfischer** [comment]
Hi,

Any update on above ? Can you plz reopen the issue.
The same error happens with a valid OpenAI API key. 

> 
> httpcore.LocalProtocolError: Illegal header value b'Bearer '
> 
> The above exception was the direct cause of the following exception:



Upon checking my OpenAI a/c, it shows no usage i.e API connection thru' langchain was not established.
Also, I am successfully using this API key for a different project and hence know the API key is valid.

Thanks,
TKF

**Comment by irisdominguez** [comment]
For those lost souls getting this error despite having set up the Mistral API key: double check that the variable name is "**MISTRAL_API_KEY**", and not "MISTRALAI_API_KEY". The [documentation](https://python.langchain.com/docs/integrations/text_embedding/mistralai/) has the wrong name.

**Comment by githubcramirez** [comment]
I have the same Issue with OpenAI key,  there is any update for the issue?

**Comment by ehsanahmadkhan525** [comment]
> I have the same Issue with OpenAI key, there is any update for the issue?

Yes facing similar issue

**Comment by ividal** [comment]
> double check that the variable name is "MISTRAL_API_KEY", and not "MISTRALAI_API_KEY"

@irisdominguez Thank you! That was it 🙌

**Comment by Canadaniel** [comment]
Same issue with Open AI key. Thank you.

**Comment by DeliciousYellow** [comment]
ANTHROPIC_API_KEY 也有同样的问题

**Comment by DeliciousYellow** [comment]
我回来了
anthropic._client.Anthropic._bearer_auth
/lib/python3.12/site-packages/anthropic/_client.py:97
从这两处我发现
"Authorization": f"Bearer {auth_token}"
这个请求头是从环境变量ANTHROPIC_AUTH_TOKEN获取值的。
所以应确保ANTHROPIC_AUTH_TOKEN有值。

其他的LLM应该可以用同样的方法排查
