### ISSUE TITLE
Input to ChatPromptTemplate is missing variables {'chat_history'}

### ISSUE THREAD

**Issue by luke1212** [langchain-ai/langchain#21278]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
def function_call_prompt():
    prompt = ChatPromptTemplate.from_messages([
        ("system", "you are a helpful assistant"),
        MessagesPlaceholder(variable_name="chat_history"),  
        ("user", "{input}"),
        MessagesPlaceholder(variable_name="agent_scratchpad"),
    ])
    return prompt

def groq_agent():
    chat = ChatGroq(model_name="llama3-8b-8192")
    
    prompt = function_call_prompt()
    tools = tool_lib.tools
    agent = create_openai_tools_agent(chat, tools, prompt)

    agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True, stream_runnable = False)
    return agent_executor
```

### Error Message and Stack Trace (if applicable)

> Entering new AgentExecutor chain...
Traceback (most recent call last):
  File "D:\DndNPC\groq_service.py", line 136, in <module>
    print(agent.invoke({"input": "我叫luke 很高兴认识你"}))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\envs\voiceAgent\Lib\site-packages\langchain\chains\base.py", line 163, in invoke
    raise e
  File "D:\Anaconda3\envs\voiceAgent\Lib\site-packages\langchain\chains\base.py", line 153, in invoke
    self._call(inputs, run_manager=run_manager)
  File "D:\Anaconda3\envs\voiceAgent\Lib\site-packages\langchain\agents\agent.py", line 1432, in _call
    next_step_output = self._take_next_step(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\envs\voiceAgent\Lib\site-packages\langchain\agents\agent.py", line 1138, in _take_next_step
    [
  File "D:\Anaconda3\envs\voiceAgent\Lib\site-packages\langchain\agents\agent.py", line 1138, in <listcomp>
    [
  File "D:\Anaconda3\envs\voiceAgent\Lib\site-packages\langchain\agents\agent.py", line 1166, in _iter_next_step
    output = self.agent.plan(
             ^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\envs\voiceAgent\Lib\site-packages\langchain\agents\agent.py", line 520, in plan
    final_output = self.runnable.invoke(inputs, config={"callbacks": callbacks})
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\envs\voiceAgent\Lib\site-packages\langchain_core\runnables\base.py", line 2499, in invoke
    input = step.invoke(
            ^^^^^^^^^^^^
  File "D:\Anaconda3\envs\voiceAgent\Lib\site-packages\langchain_core\prompts\base.py", line 128, in invoke
    return self._call_with_config(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\envs\voiceAgent\Lib\site-packages\langchain_core\runnables\base.py", line 1626, in _call_with_config
    context.run(
  File "D:\Anaconda3\envs\voiceAgent\Lib\site-packages\langchain_core\runnables\config.py", line 347, in call_func_with_variable_args
    return func(input, **kwargs)  # type: ignore[call-arg]
  File "D:\Anaconda3\envs\voiceAgent\Lib\site-packages\langchain_core\prompts\base.py", line 111, in _format_prompt_with_error_handling
    _inner_input = self._validate_input(inner_input)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\envs\voiceAgent\Lib\site-packages\langchain_core\prompts\base.py", line 103, in _validate_input
    raise KeyError(
KeyError: "Input to ChatPromptTemplate is missing variables {'chat_history'}.  Expected: ['agent_scratchpad', 'chat_history', 'input'] Received: ['input', 'intermediate_steps', 'agent_scratchpad']"

### Description

I'm trying to use langchain agent to run groq. I am expect to see the agent run but I got this error where there is a history issue. I am wondering where should I put the history at? 

### System Info

python 3.11

**Comment by maximeperrindev** [comment]
Hi @luke1212 ,

Try 
```python
print(agent.invoke({"input": "我叫luke 很高兴认识你", "chat_history": []}))
```

**Comment by eyurtsev** [comment]
Thank @maximeperrindev 

Closing as this is a usage error
