### ISSUE TITLE
Unable to launch provided Devcontainer. Directory ../partners/openai does not exist

### ISSUE THREAD

**Issue by RadoslawLemiec** [langchain-ai/langchain#21886]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

Not applicable 

### Error Message and Stack Trace (if applicable)

 => ERROR [langchain langchain-dev-dependencies 6/6] RUN poetry install -  1.6s
------
 > [langchain langchain-dev-dependencies 6/6] RUN poetry install --no-interaction --no-ansi --with dev,test,docs:
1.464 
1.465 Directory ../partners/openai does not exist
------
[2024-05-19T18:27:00.124Z] failed to solve: process "/bin/sh -c poetry install --no-interaction --no-ansi --with dev,test,docs" did not complete successfully: exit code: 1
[2024-05-19T18:27:00.128Z] Stop (30914 ms): Run: docker compose --project-name devcontainer -f /mnt/c/IT/Projects/langchain/langchain/.devcontainer/docker-compose.yaml -f /tmp/devcontainercli-devcontainers/docker-compose/docker-compose.devcontainer.build-1716143189213.yml build
[2024-05-19T18:27:00.129Z] Error: Command failed: docker compose --project-name devcontainer -f /mnt/c/IT/Projects/langchain/langchain/.devcontainer/docker-compose.yaml -f /tmp/devcontainercli-devcontainers/docker-compose/docker-compose.devcontainer.build-1716143189213.yml build
[2024-05-19T18:27:00.129Z]     at Km (/home/devcontainers/.vscode-remote-containers/dist/dev-containers-cli-0.366.0/dist/spec-node/devContainersSpecCLI.js:429:525)
[2024-05-19T18:27:00.129Z]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-05-19T18:27:00.129Z]     at async QtA (/home/devcontainers/.vscode-remote-containers/dist/dev-containers-cli-0.366.0/dist/spec-node/devContainersSpecCLI.js:429:2476)
[2024-05-19T18:27:00.130Z]     at async utA (/home/devcontainers/.vscode-remote-containers/dist/dev-containers-cli-0.366.0/dist/spec-node/devContainersSpecCLI.js:409:3506)
[2024-05-19T18:27:00.130Z]     at async KtA (/home/devcontainers/.vscode-remote-containers/dist/dev-containers-cli-0.366.0/dist/spec-node/devContainersSpecCLI.js:481:3865)
[2024-05-19T18:27:00.130Z]     at async AB (/home/devcontainers/.vscode-remote-containers/dist/dev-containers-cli-0.366.0/dist/spec-node/devContainersSpecCLI.js:481:4807)
[2024-05-19T18:27:00.130Z]     at async hrA (/home/devcontainers/.vscode-remote-containers/dist/dev-containers-cli-0.366.0/dist/spec-node/devContainersSpecCLI.js:661:13255)
[2024-05-19T18:27:00.130Z]     at async lrA (/home/devcontainers/.vscode-remote-containers/dist/dev-containers-cli-0.366.0/dist/spec-node/devContainersSpecCLI.js:661:12996)
[2024-05-19T18:27:00.134Z] Stop (32915 ms): Run in Host: /home/devcontainers/.vscode-remote-containers/bin/f209ce35ef894bd32c12057724e8d1f1139c433f/node /home/devcontainers/.vscode-remote-containers/dist/dev-containers-cli-0.366.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-747ad587-40d5-4457-ba1a-99c12d4be9721716143184888 --workspace-folder /mnt/c/IT/Projects/langchain/langchain --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\IT\Projects\langchain\langchain --id-label devcontainer.config_file=/mnt/c/IT/Projects/langchain/langchain/.devcontainer/devcontainer.json --log-level debug --log-format json --config /mnt/c/IT/Projects/langchain/langchain/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=/run/user/1000/wayland-0,target=/tmp/vscode-wayland-104b6397-6aed-4445-8184-e94bff82c011.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2024-05-19T18:27:00.134Z] Exit code 1
[2024-05-19T18:27:00.138Z] Command failed: /home/devcontainers/.vscode-remote-containers/bin/f209ce35ef894bd32c12057724e8d1f1139c433f/node /home/devcontainers/.vscode-remote-containers/dist/dev-containers-cli-0.366.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-747ad587-40d5-4457-ba1a-99c12d4be9721716143184888 --workspace-folder /mnt/c/IT/Projects/langchain/langchain --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\IT\Projects\langchain\langchain --id-label devcontainer.config_file=/mnt/c/IT/Projects/langchain/langchain/.devcontainer/devcontainer.json --log-level debug --log-format json --config /mnt/c/IT/Projects/langchain/langchain/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=/run/user/1000/wayland-0,target=/tmp/vscode-wayland-104b6397-6aed-4445-8184-e94bff82c011.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2024-05-19T18:27:00.139Z] Exit code 1
[2024-05-19T18:27:04.194Z] Start: Run in Host: wslpath -w c:/IT/Projects/langchain/langchain/.devcontainer/devcontainer.json
[2024-05-19T18:27:04.204Z] Stop (10 ms): Run in Host: wslpath -w c:/IT/Projects/langchain/langchain/.devcontainer/devcontainer.json

### Description

I'm trying to launch Devcontainer with .devcontainer provided in repository using VSCode. Launch failes during poetry install with message `Directory ../partners/openai does not exist`. This was a fresh clone from repository. No changes were introduced.

### System Info

VSCode Version: 1.90.0-insider
OS: Windows_NT x64 10.0.22631

**Comment by DCharles01** [comment]
Hi, can you assign this issue to me?
