### ISSUE TITLE
langchain_community.chat_models.hunyuan.ChatHunyuan do not work

### ISSUE THREAD

**Issue by uniqueSkeeter** [langchain-ai/langchain#22107]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

tencent_llm_resp = TENCENT_LLM.invoke("你好，你是谁")
print("TENCENT_LLM example", tencent_llm_resp)

### Error Message and Stack Trace (if applicable)

C:\Users\w00012491\PycharmProjects\pythonProject\pythonProject\QianFanRobot\.venv\Scripts\python.exe C:\Users\w00012491\PycharmProjects\pythonProject\pythonProject\QianFanRobot\IASA\tests\test_models.py 
Traceback (most recent call last):
  File "C:\Users\w00012491\PycharmProjects\pythonProject\pythonProject\QianFanRobot\.venv\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\w00012491\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\w00012491\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\w00012491\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\w00012491\PycharmProjects\pythonProject\pythonProject\QianFanRobot\IASA\tests\test_models.py", line 35, in <module>
    tencent_llm_resp = TENCENT_LLM.invoke("你好，你是谁")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\w00012491\PycharmProjects\pythonProject\pythonProject\QianFanRobot\.venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 170, in invoke
    self.generate_prompt(
  File "C:\Users\w00012491\PycharmProjects\pythonProject\pythonProject\QianFanRobot\.venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 599, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\w00012491\PycharmProjects\pythonProject\pythonProject\QianFanRobot\.venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 456, in generate
    raise e
  File "C:\Users\w00012491\PycharmProjects\pythonProject\pythonProject\QianFanRobot\.venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 446, in generate
    self._generate_with_cache(
  File "C:\Users\w00012491\PycharmProjects\pythonProject\pythonProject\QianFanRobot\.venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 671, in _generate_with_cache
    result = self._generate(
             ^^^^^^^^^^^^^^^
  File "C:\Users\w00012491\PycharmProjects\pythonProject\pythonProject\QianFanRobot\.venv\Lib\site-packages\langchain_community\chat_models\hunyuan.py", line 251, in _generate
    response = res.json()
               ^^^^^^^^^^
  File "C:\Users\w00012491\PycharmProjects\pythonProject\pythonProject\QianFanRobot\.venv\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### Description

hi guys, langchain_community.chat_models.hunyuan.ChatHunyuan do not work. anyone know why?
![截图](https://github.com/langchain-ai/langchain/assets/7637222/0d8fe5ee-02a0-4a09-822c-957520b7b42d)

### System Info

![截图3](https://github.com/langchain-ai/langchain/assets/7637222/286b2ce6-ad20-413e-8651-caeb92608419)

**Comment by duongleh** [comment]
I got the same error but with the latest version of `langchain_openai` package

**Comment by shelltea** [comment]
Encountering the same problem, is there any solution?

**Comment by shelltea** [comment]
I found a temporary solution, using [hunyuan.py](https://raw.githubusercontent.com/langchain-ai/langchain/9a6c84183ce8f47fd5b845acba88bed0b956dc88/libs/community/langchain_community/chat_models/hunyuan.py)

Replace the current version with this file.

**Comment by uniqueSkeeter** [comment]
@shelltea How did you solve it?

**Comment by shelltea** [comment]
@uniqueSkeeter 

1. Download this [file](https://raw.githubusercontent.com/langchain-ai/langchain/9a6c84183ce8f47fd5b845acba88bed0b956dc88/libs/community/langchain_community/chat_models/hunyuan.py)
2. from hunyuan import ChatHunyuan
