### ISSUE TITLE
AttributeError in Chroma: 'LocalAPI' object has no attribute 'get_or_create_collection'

### ISSUE THREAD

**Issue by sgrening** [langchain-ai/langchain#2213]
While using the LangChain package to create a Vectorstore index, I encountered an AttributeError in the chroma.py file. The traceback indicates that the 'LocalAPI' object does not have the attribute 'get_or_create_collection'. This issue occurred when trying to create an index using the following code:

`index = VectorstoreIndexCreator().from_loaders([loader])`

Here's the full traceback:

Traceback (most recent call last):
 ```
 File "main.py", line 29, in <module>
    index = VectorstoreIndexCreator().from_loaders([loader])
  File "/home/runner/VioletWarpedDeclarations/venv/lib/python3.10/site-packages/langchain/indexes/vectorstore.py", line 71, in from_loaders
    vectorstore = self.vectorstore_cls.from_documents(
  File "/home/runner/VioletWarpedDeclarations/venv/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 268, in from_documents
    return cls.from_texts(
  File "/home/runner/VioletWarpedDeclarations/venv/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 231, in from_texts
    chroma_collection = cls(
  File "/home/runner/VioletWarpedDeclarations/venv/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 81, in __init__
    self._collection = self._client.get_or_create_collection(
AttributeError: 'LocalAPI' object has no attribute 'get_or_create_collection'. Did you mean: 'create_collection'?
```
It seems like the 'LocalAPI' object is missing the 'get_or_create_collection' method or the method's name might have been changed in the recent updates.

**Comment by kn-neeraj** [comment]
I was facing this problem. Downgraded the package version to 0.3.15 and it worked. Some issue on latest version it seems!
