### ISSUE TITLE
openai.NotFoundError

### ISSUE THREAD

**Issue by haogecat** [langchain-ai/langchain#22233]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

`OPENAI_API_BASE` and `OPENAI_API_KEY`.
```python
os.environ["OPENAI_API_KEY"] = "xxxxxxxx"
os.environ["OPENAI_API_BASE"] = "xxxxxxx"

from langchain_core.messages import HumanMessage, SystemMessage
model = ChatOpenAI(model="gpt-3.5-turbo")
messages = [
    SystemMessage(content="Translate the following from English into Italian"),
    HumanMessage(content="hi!"),
]
model.invoke(messages)

loader = WebBaseLoader("https://docs.smith.langchain.com/overview")
docs = loader.load()
documents = RecursiveCharacterTextSplitter(
    chunk_size=1000, chunk_overlap=200
).split_documents(docs)

# error occurred, openai.NotFoundError
vector = FAISS.from_documents(documents, OpenAIEmbeddings())

# The same error occurs
embeddings=OpenAIEmbeddings()
embeddings.embed_documents(["cat","dog","fish"])


### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/qjh/miniforge3/envs/langchain/lib/python3.12/site-packages/langchain_openai/embeddings/base.py", line 489, in embed_documents
    return self._get_len_safe_embeddings(texts, engine=engine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qjh/miniforge3/envs/langchain/lib/python3.12/site-packages/langchain_openai/embeddings/base.py", line 347, in _get_len_safe_embeddings
    response = self.client.create(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/qjh/miniforge3/envs/langchain/lib/python3.12/site-packages/openai/resources/embeddings.py", line 114, in create
    return self._post(
           ^^^^^^^^^^^
  File "/home/qjh/miniforge3/envs/langchain/lib/python3.12/site-packages/openai/_base_client.py", line 1240, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qjh/miniforge3/envs/langchain/lib/python3.12/site-packages/openai/_base_client.py", line 921, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/qjh/miniforge3/envs/langchain/lib/python3.12/site-packages/openai/_base_client.py", line 1020, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

### Description

I am learning to use LangChain according to the tutorial, and the LLM model works fine, but the embedding model does not. I have correctly set the values for  OPENAI_API_BASE and OPENAI_API_KEY.

Langchain-core==0.2.1
Langchain==0.2.1

### System Info

aiohttp                                  3.9.5
aiosignal                                1.3.1
annotated-types                          0.7.0
anyio                                    4.3.0
asgiref                                  3.8.1
attrs                                    23.2.0
backoff                                  2.2.1
bcrypt                                   4.1.3
beautifulsoup4                           4.12.3
bs4                                      0.0.2
build                                    1.2.1
cachetools                               5.3.3
certifi                                  2024.2.2
charset-normalizer                       3.3.2
chroma-hnswlib                           0.7.3
chromadb                                 0.5.0
click                                    8.1.7
coloredlogs                              15.0.1
dataclasses-json                         0.6.6
Deprecated                               1.2.14
distro                                   1.9.0
dnspython                                2.6.1
email_validator                          2.1.1
fastapi                                  0.111.0
fastapi-cli                              0.0.4
filelock                                 3.14.0
flatbuffers                              24.3.25
frozenlist                               1.4.1
fsspec                                   2024.5.0
google-auth                              2.29.0
googleapis-common-protos                 1.63.0
greenlet                                 3.0.3
grpcio                                   1.64.0
h11                                      0.14.0
httpcore                                 1.0.5
httptools                                0.6.1
httpx                                    0.27.0
huggingface-hub                          0.23.1
humanfriendly                            10.0
idna                                     3.7
importlib-metadata                       7.0.0
importlib_resources                      6.4.0
Jinja2                                   3.1.4
jsonpatch                                1.33
jsonpointer                              2.4
jsonschema                               4.22.0
jsonschema-specifications                2023.12.1
kubernetes                               29.0.0
langchain                                0.2.1
langchain-chroma                         0.1.1
langchain-community                      0.2.1
langchain-core                           0.2.1
langchain-openai                         0.1.7
langchain-text-splitters                 0.2.0
langserve                                0.2.1
langsmith                                0.1.63
markdown-it-py                           3.0.0
MarkupSafe                               2.1.5
marshmallow                              3.21.2
mdurl                                    0.1.2
mmh3                                     4.1.0
monotonic                                1.6
mpmath                                   1.3.0
multidict                                6.0.5
mypy-extensions                          1.0.0
numpy                                    1.26.4
oauthlib                                 3.2.2
onnxruntime                              1.18.0
openai                                   1.30.2
opentelemetry-api                        1.24.0
opentelemetry-exporter-otlp-proto-common 1.24.0
opentelemetry-exporter-otlp-proto-grpc   1.24.0
opentelemetry-instrumentation            0.45b0
opentelemetry-instrumentation-asgi       0.45b0
opentelemetry-instrumentation-fastapi    0.45b0
opentelemetry-proto                      1.24.0
opentelemetry-sdk                        1.24.0
opentelemetry-semantic-conventions       0.45b0
opentelemetry-util-http                  0.45b0
orjson                                   3.10.3
overrides                                7.7.0
packaging                                23.2
pip                                      24.0
posthog                                  3.5.0
protobuf                                 4.25.3
pyasn1                                   0.6.0
pyasn1_modules                           0.4.0
pydantic                                 2.7.1
pydantic_core                            2.18.2
Pygments                                 2.18.0
PyPika                                   0.48.9
pyproject_hooks                          1.1.0
pyproject-toml                           0.0.10
python-dateutil                          2.9.0.post0
python-dotenv                            1.0.1
python-multipart                         0.0.9
PyYAML                                   6.0.1
referencing                              0.35.1
regex                                    2024.5.15
requests                                 2.32.2
requests-oauthlib                        2.0.0
rich                                     13.7.1
rpds-py                                  0.18.1
rsa                                      4.9
setuptools                               69.5.1
shellingham                              1.5.4
six                                      1.16.0
sniffio                                  1.3.1
soupsieve                                2.5
SQLAlchemy                               2.0.30
sse-starlette                            1.8.2
starlette                                0.37.2
sympy                                    1.12
tenacity                                 8.3.0
tiktoken                                 0.7.0
tokenizers                               0.19.1
toml                                     0.10.2
tqdm                                     4.66.4
typer                                    0.12.3
typing_extensions                        4.12.0
typing-inspect                           0.9.0
ujson                                    5.10.0
urllib3                                  2.2.1
uvicorn                                  0.29.0
uvloop                                   0.19.0
watchfiles                               0.21.0
websocket-client                         1.8.0
websockets                               12.0
wheel                                    0.43.0
wrapt                                    1.16.0
yarl                                     1.9.4
zipp                                     3.18.2

**Comment by hwchase17** [comment]
I am unable to replicate... I would guess this has something to do with the connection to openai. are you using a proxy/non-standard OPENAI_API_BASE?

**Comment by haogecat** [comment]
> I am unable to replicate... I would guess this has something to do with the connection to openai. are you using a proxy/non-standard OPENAI_API_BASE?

Thank you for your help. The problem with OPENAI_API_BASE is real. I changed the correct proxy address to solve the problem. I still don't know why the original proxy could use a model and not an embeddings, but that doesn't matter. Thank you!
