### ISSUE TITLE
Facing ORA-51805: Vector is not properly formatted (dimension value  is either not a number or infinity) error while using OracleVS

### ISSUE THREAD

**Issue by sameera14** [langchain-ai/langchain#22469]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

The following code 
``` python
    from langchain_community.vectorstores.oraclevs import OracleVS
    from langchain_community.vectorstores.utils import DistanceStrategy
    from langchain_core.documents import Document
    import oracledb
    
    username = ""
    password = ""
    dsn = ""

    try:
        conn = oracledb.connect(user=username, password=password, dsn=dsn)
        print("Connection successful!")
    except Exception as e:
        print("Connection failed!")
        sys.exit(1)
    
    
    chunks_with_mdata=[]
    chunks = [Document(page_content='My name is Stark',metadata={'source':"pdf"}),
              Document(page_content='Stark works in ABC Ltd.',metadata={'source':"pdf"})]
    for id, doc in enumerate(chunks):
        chunk_metadata = doc.metadata.copy()
        chunk_metadata["id"] = str(id)
        chunk_metadata["document_id"] = str(id)
        chunks_with_mdata.append(
            Document(page_content=str(doc.page_content), metadata=chunk_metadata)
        )
    
    from langchain_cohere import CohereEmbeddings
    embeddings = CohereEmbeddings(cohere_api_key=cohere_key, model='embed-english-v3.0')
  
    vector_store = OracleVS.from_texts(
        texts=[doc.page_content for doc in chunks_with_mdata],
        metadatas=[doc.metadata for doc in chunks_with_mdata],
        embedding=embeddings,
        client=conn,
        table_name="pdf_vector_cosine",
        distance_strategy=DistanceStrategy.COSINE,
    )


### Error Message and Stack Trace (if applicable)

2024-06-04 15:55:22,275 - ERROR - An unexpected error occurred: ORA-51805: Vector is not properly formatted (dimension value  is either not a number or infinity).
Help: https://docs.oracle.com/error-help/db/ora-51805/
Traceback (most recent call last):
  File "/home/testuser/projects/venv/lib/python3.9/site-packages/langchain_community/vectorstores/oraclevs.py", line 54, in wrapper
    return func(*args, **kwargs)
  File "/home/testuser/projects/venv/lib/python3.9/site-packages/langchain_community/vectorstores/oraclevs.py", line 535, in add_texts
    cursor.executemany(
  File "/home/testuser/projects/venv/lib/python3.9/site-packages/oracledb/cursor.py", line 751, in executemany
    self._impl.executemany(
  File "src/oracledb/impl/thin/cursor.pyx", line 218, in oracledb.thin_impl.ThinCursorImpl.executemany
  File "src/oracledb/impl/thin/protocol.pyx", line 438, in oracledb.thin_impl.Protocol._process_single_message
  File "src/oracledb/impl/thin/protocol.pyx", line 439, in oracledb.thin_impl.Protocol._process_single_message
  File "src/oracledb/impl/thin/protocol.pyx", line 432, in oracledb.thin_impl.Protocol._process_message
oracledb.exceptions.DatabaseError: ORA-51805: Vector is not properly formatted (dimension value  is either not a number or infinity).
Help: https://docs.oracle.com/error-help/db/ora-51805/
2024-06-04 15:55:22,277 - ERROR - DB-related error occurred.
Traceback (most recent call last):
  File "/home/testuser/projects/venv/lib/python3.9/site-packages/langchain_community/vectorstores/oraclevs.py", line 54, in wrapper
    return func(*args, **kwargs)
  File "/home/testuser/projects/venv/lib/python3.9/site-packages/langchain_community/vectorstores/oraclevs.py", line 535, in add_texts
    cursor.executemany(
  File "/home/testuser/projects/venv/lib/python3.9/site-packages/oracledb/cursor.py", line 751, in executemany
    self._impl.executemany(
  File "src/oracledb/impl/thin/cursor.pyx", line 218, in oracledb.thin_impl.ThinCursorImpl.executemany
  File "src/oracledb/impl/thin/protocol.pyx", line 438, in oracledb.thin_impl.Protocol._process_single_message
  File "src/oracledb/impl/thin/protocol.pyx", line 439, in oracledb.thin_impl.Protocol._process_single_message
  File "src/oracledb/impl/thin/protocol.pyx", line 432, in oracledb.thin_impl.Protocol._process_message
oracledb.exceptions.DatabaseError: ORA-51805: Vector is not properly formatted (dimension value  is either not a number or infinity).
Help: https://docs.oracle.com/error-help/db/ora-51805/

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/testuser/projects/venv/lib/python3.9/site-packages/langchain_community/vectorstores/oraclevs.py", line 54, in wrapper
    return func(*args, **kwargs)
  File "/home/testuser/projects/venv/lib/python3.9/site-packages/langchain_community/vectorstores/oraclevs.py", line 934, in from_texts
    vss.add_texts(texts=list(texts), metadatas=metadatas)
  File "/home/testuser/projects/venv/lib/python3.9/site-packages/langchain_community/vectorstores/oraclevs.py", line 68, in wrapper
    raise RuntimeError("Unexpected error: {}".format(e)) from e
RuntimeError: Unexpected error: ORA-51805: Vector is not properly formatted (dimension value  is either not a number or infinity).
Help: https://docs.oracle.com/error-help/db/ora-51805/
Traceback (most recent call last):
  File "/home/testuser/projects/venv/lib/python3.9/site-packages/langchain_community/vectorstores/oraclevs.py", line 54, in wrapper
    return func(*args, **kwargs)
  File "/home/testuser/projects/venv/lib/python3.9/site-packages/langchain_community/vectorstores/oraclevs.py", line 535, in add_texts
    cursor.executemany(
  File "/home/testuser/projects/venv/lib/python3.9/site-packages/oracledb/cursor.py", line 751, in executemany
    self._impl.executemany(
  File "src/oracledb/impl/thin/cursor.pyx", line 218, in oracledb.thin_impl.ThinCursorImpl.executemany
  File "src/oracledb/impl/thin/protocol.pyx", line 438, in oracledb.thin_impl.Protocol._process_single_message
  File "src/oracledb/impl/thin/protocol.pyx", line 439, in oracledb.thin_impl.Protocol._process_single_message
  File "src/oracledb/impl/thin/protocol.pyx", line 432, in oracledb.thin_impl.Protocol._process_message
oracledb.exceptions.DatabaseError: ORA-51805: Vector is not properly formatted (dimension value  is either not a number or infinity).
Help: https://docs.oracle.com/error-help/db/ora-51805/

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/testuser/projects/venv/lib/python3.9/site-packages/langchain_community/vectorstores/oraclevs.py", line 54, in wrapper
    return func(*args, **kwargs)
  File "/home/testuser/projects/venv/lib/python3.9/site-packages/langchain_community/vectorstores/oraclevs.py", line 934, in from_texts
    vss.add_texts(texts=list(texts), metadatas=metadatas)
  File "/home/testuser/projects/venv/lib/python3.9/site-packages/langchain_community/vectorstores/oraclevs.py", line 68, in wrapper
    raise RuntimeError("Unexpected error: {}".format(e)) from e
RuntimeError: Unexpected error: ORA-51805: Vector is not properly formatted (dimension value  is either not a number or infinity).
Help: https://docs.oracle.com/error-help/db/ora-51805/

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/testuser/projects/zscratch/oracle_vs.py", line 227, in <module>
    oraclevs_langchain(conn=conn,chunks=chunks_with_mdata,embeddings=embeddings)
  File "/home/testuser/projects/venvzscratch/oracle_vs.py", line 206, in oraclevs_langchain
    vector_store = OracleVS.from_texts(
  File "/home/testuser/projects/venv/lib/python3.9/site-packages/langchain_community/vectorstores/oraclevs.py", line 58, in wrapper
    raise RuntimeError(
RuntimeError: Failed due to a DB issue: Unexpected error: ORA-51805: Vector is not properly formatted (dimension value  is either not a number or infinity).
Help: https://docs.oracle.com/error-help/db/ora-51805/

### Description

I'm trying to use OracleVS with latest Database version Oracle23ai which supports VECTOR datatype for storing embedings. While trying to store the vector embeddings I'm facing the error **ORA-51805: Vector is not properly formatted (dimension value  is either not a number or infinity).** 
I identified bug in the langchain_community/vectorstores/oraclevs.py in line 524. After type-casting the embeddings to string datatype it started running smoothly.
(id_, text, json.dumps(metadata), array.array("f", embedding))  -> (id_, text, json.dumps(metadata), str(embedding))

I was facing the same error during retrieval as well and applied the same fix in line 616:
embedding_arr = array.array("f", embedding) -> embedding_arr = str(embedding)


### System Info

langchain==0.2.1
langchain-cohere==0.1.5
langchain-community==0.2.1
langchain-core==0.2.3
langchain-experimental==0.0.59
langchain-google-genai==1.0.5
langchain-openai==0.1.8
langchain-text-splitters==0.2.0
oracledb==2.2.1

**Comment by fileames** [comment]
Thanks for reporting this. I wasn't able to reproduce the issue. If you encounter it again or can provide more details, feel free to reopen the issue.
