### ISSUE TITLE
langchain agents executor throws: assert generation is not None

### ISSUE THREAD

**Issue by archine** [langchain-ai/langchain#22585]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from langchain_core.tools import tool
from langchain_openai import ChatOpenAI
from langchain.agents import AgentExecutor, create_tool_calling_agent
from langchain.prompts import ChatPromptTemplate


@tool
def multiply(first_int: int, second_int: int) -> int:
    """Multiply two integers together."""
    return first_int * second_int


@tool
def add(first_int: int, second_int: int) -> int:
    """Add two integers.
    """
    return first_int + second_int


tools = [multiply, add,]

if __name__ == '__main__':

    prompt = ChatPromptTemplate.from_messages(
        [
            ("system", "You are a helpful assistant"),
            ("placeholder", "{chat_history}"),
            ("human", "{input}"),
            ("placeholder", "{agent_scratchpad}"),
        ]
    )

    bind_tools = llm.bind_tools(tools)

    calling_agent = create_tool_calling_agent(llm, tools, prompt)

    agent_executor = AgentExecutor(agent=calling_agent, tools=tools, verbose=True)

    response = agent_executor.invoke({
        "input": "what is the value of multiply(5, 42)?",
    })
```

### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "E:\PycharmProjects\agent-tool-demo\main.py", line 61, in <module>
    stream = agent_executor.invoke({
  File "E:\conda\env\agent-tool-demo\lib\site-packages\langchain\chains\base.py", line 166, in invoke
    raise e
  File "E:\conda\env\agent-tool-demo\lib\site-packages\langchain\chains\base.py", line 156, in invoke
    self._call(inputs, run_manager=run_manager)
  File "E:\conda\env\agent-tool-demo\lib\site-packages\langchain\agents\agent.py", line 1433, in _call
    next_step_output = self._take_next_step(
  File "E:\conda\env\agent-tool-demo\lib\site-packages\langchain\agents\agent.py", line 1139, in _take_next_step
    [
  File "E:\conda\env\agent-tool-demo\lib\site-packages\langchain\agents\agent.py", line 1139, in <listcomp>
    [
  File "E:\conda\env\agent-tool-demo\lib\site-packages\langchain\agents\agent.py", line 1167, in _iter_next_step
    output = self.agent.plan(
  File "E:\conda\env\agent-tool-demo\lib\site-packages\langchain\agents\agent.py", line 515, in plan
    for chunk in self.runnable.stream(inputs, config={"callbacks": callbacks}):
  File "E:\conda\env\agent-tool-demo\lib\site-packages\langchain_core\runnables\base.py", line 2775, in stream
    yield from self.transform(iter([input]), config, **kwargs)
  File "E:\conda\env\agent-tool-demo\lib\site-packages\langchain_core\runnables\base.py", line 2762, in transform
    yield from self._transform_stream_with_config(
  File "E:\conda\env\agent-tool-demo\lib\site-packages\langchain_core\runnables\base.py", line 1778, in _transform_stream_with_config
    chunk: Output = context.run(next, iterator)  # type: ignore
  File "E:\conda\env\agent-tool-demo\lib\site-packages\langchain_core\runnables\base.py", line 2726, in _transform
    for output in final_pipeline:
  File "E:\conda\env\agent-tool-demo\lib\site-packages\langchain_core\runnables\base.py", line 1154, in transform
    for ichunk in input:
  File "E:\conda\env\agent-tool-demo\lib\site-packages\langchain_core\runnables\base.py", line 4644, in transform
    yield from self.bound.transform(
  File "E:\conda\env\agent-tool-demo\lib\site-packages\langchain_core\runnables\base.py", line 1172, in transform
    yield from self.stream(final, config, **kwargs)
  File "E:\conda\env\agent-tool-demo\lib\site-packages\langchain_core\language_models\chat_models.py", line 265, in stream
    raise e
  File "E:\conda\env\agent-tool-demo\lib\site-packages\langchain_core\language_models\chat_models.py", line 257, in stream
    assert generation is not None
AssertionError

### Description

An error occurred when I used the agent executor invoke

### System Info

langchain 0.2.1

**Comment by lucas-tucker** [comment]
This seems to be fixed in langchain 0.2.2

**Comment by archine** [comment]
> This seems to be fixed in langchain 0.2.2

No, I upgraded to 0.2.3, and using the official example, assert generation is not None

**Comment by lucas-tucker** [comment]
I cannot seem to replicate the error, even after upgrading to 0.2.3. How are you creating `llm`? Also could you please clarify what the "official example" is?

**Comment by archine** [comment]
> I cannot seem to replicate the error, even after upgrading to 0.2.3. How are you creating `llm`? Also could you please clarify what the "official example" is?

I re-edited the sample code in my last answer, which is a demo from the dependency library comments。
![image](https://github.com/langchain-ai/langchain/assets/35919643/c33df735-7730-4960-968a-57ca4a1c8dac)

**Comment by sanderw3** [comment]
Hello,

I'm encountering an issue when trying to use Azure's inference endpoint with the following code:

```python
async def testfunc(input: Input):

    tools = [get_weather]
    llm = ChatOpenAI(
        base_url=os.getenv("MISTRAL_CONNECTION_URL"),
        api_key=os.getenv("MISTRAL_API_KEY"),
        streaming=False
    )
    # I also tried this:
    # llm = ChatMistralAI(
    #     temperature=0.6,
    #     endpoint=os.getenv("MISTRAL_CONNECTION_URL"),
    #     mistral_api_key=os.getenv("MISTRAL_API_KEY"),
    #     streaming=True,
    # )
    
    agent = create_openai_tools_agent(llm, tools, llama_prompt_template)
    executor = AgentExecutor(agent=agent, tools=tools, verbose=True)

    result = executor.invoke(
        {"input": input["prompt"], "chat_history": input["chat_history"]}
    )

    return result["output"]
```
When the LLM attempts to call a tool, I consistently encounter the error: `assert generation is not None`. I tried replacing ChatOpenAI with AzureMLChatOnlineEndpoint, which resolved the error, but the agent stopped invoking the tools altogether.

Any insights or suggestions?

here is the tool i tried with:
```python
@tool
def get_weather(location: str):
    """Returns the weather information for todays weather, based on a given location."""
    print("get_weather tool called")
    return "48c, sunny"
```

**Comment by Ignorance19941019** [comment]
Did your issue get resolved? I encountered a similar problem while using ChatAnthropic.

**Comment by Subham07** [comment]
Was this issue resolved? I am facing this error for some queries in which the agent needs to call multiple tools parallelly. @archine , @lucas-tucker
