### ISSUE TITLE
'error': {'message': "Missing parameter 'tool_call_id': messages with role 'tool' must have a 'tool_call_id'

### ISSUE THREAD

**Issue by roadcode** [langchain-ai/langchain#22600]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
class AgentState(TypedDict):
    input: str
    chat_history: list[BaseMessage]
    agent_outcome: Union[AgentAction, AgentFinish, None]
    intermediate_steps: Annotated[list[tuple[AgentAction, str]], operator.add]

def plan(self, data):
    agent_outcome = self.agent.invoke(data)
    return {'agent_outcome': agent_outcome}

def execute(self, data):
    res = {"intermediate_steps": [], 'results': []}
    for agent_action in data['agent_outcome']:
        invocation = ToolInvocation(tool=agent_action.tool, tool_input=agent_action.tool_input)
        output = self.tool_executor.invoke(invocation)
        res["intermediate_steps"].append((agent_action, str({"result": output})))
    return res
```

### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "D:\project\po_fbb\demo.py", line 121, in <module>
    for s in app.stream(inputs, config=config, debug=True):
  File "C:\Users\Anaconda3\lib\site-packages\langgraph\pregel\__init__.py", line 876, in stream
    _panic_or_proceed(done, inflight, step)
  File "C:\Users\Anaconda3\lib\site-packages\langgraph\pregel\__init__.py", line 1422, in _panic_or_proceed
    raise exc
  File "C:\Users\Anaconda3\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Anaconda3\lib\site-packages\langgraph\pregel\retry.py", line 66, in run_with_retry
    task.proc.invoke(task.input, task.config)
  File "C:\Users\Anaconda3\lib\site-packages\langchain_core\runnables\base.py", line 2393, in invoke
    input = step.invoke(
  File "C:\Users\Anaconda3\lib\site-packages\langgraph\pregel\__init__.py", line 1333, in invoke
    for chunk in self.stream(
  File "C:\Users\Anaconda3\lib\site-packages\langgraph\pregel\__init__.py", line 876, in stream
    _panic_or_proceed(done, inflight, step)
  File "C:\Users\Anaconda3\lib\site-packages\langgraph\pregel\__init__.py", line 1422, in _panic_or_proceed
    raise exc
  File "C:\Users\Anaconda3\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Anaconda3\lib\site-packages\langgraph\pregel\retry.py", line 66, in run_with_retry
    task.proc.invoke(task.input, task.config)
  File "C:\Users\Anaconda3\lib\site-packages\langchain_core\runnables\base.py", line 2393, in invoke
    input = step.invoke(
  File "C:\Users\Anaconda3\lib\site-packages\langgraph\utils.py", line 89, in invoke
    ret = context.run(self.func, input, **kwargs)
  File "D:\project\po_fbb\plan_execute.py", line 54, in plan
    agent_outcome = self.agent.invoke(data)
  File "C:\Users\Anaconda3\lib\site-packages\langchain_core\runnables\base.py", line 2393, in invoke
    input = step.invoke(
  File "C:\Users\Anaconda3\lib\site-packages\langchain_core\runnables\base.py", line 4427, in invoke
    return self.bound.invoke(
  File "C:\Users\Anaconda3\lib\site-packages\langchain_core\language_models\chat_models.py", line 170, in invoke
    self.generate_prompt(
  File "C:\Users\Anaconda3\lib\site-packages\langchain_core\language_models\chat_models.py", line 599, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
  File "C:\Users\Anaconda3\lib\site-packages\langchain_core\language_models\chat_models.py", line 456, in generate
    raise e
  File "C:\Users\Anaconda3\lib\site-packages\langchain_core\language_models\chat_models.py", line 446, in generate
    self._generate_with_cache(
  File "C:\Users\Anaconda3\lib\site-packages\langchain_core\language_models\chat_models.py", line 671, in _generate_with_cache
    result = self._generate(
  File "C:\Users\Anaconda3\lib\site-packages\langchain_openai\chat_models\base.py", line 522, in _generate
    response = self.client.create(messages=message_dicts, **params)
  File "C:\Users\Anaconda3\lib\site-packages\openai\_utils\_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Anaconda3\lib\site-packages\openai\resources\chat\completions.py", line 590, in create
    return self._post(
  File "C:\Users\Anaconda3\lib\site-packages\openai\_base_client.py", line 1240, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "C:\Users\Anaconda3\lib\site-packages\openai\_base_client.py", line 921, in request
    return self._request(
  File "C:\Users\Anaconda3\lib\site-packages\openai\_base_client.py", line 1020, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "An assistant message with 'tool_calls' must be followed by tool messages responding to each 'tool_call_id'. The following tool_call_ids did not have response messages: call_O4TQIqkzFaYavyeNQfrHhQla (request id: 2024060617051887706039753292306) (request id: 2024060605051875537495502347588)", 'type': 'invalid_request_error', 'param': 'messages', 'code': None}}

### Description

when run at agent_outcome = self.agent.invoke(data), it raise error
openai.BadRequestError: Error code: 400 - {'error': {**'message': "Missing parameter 'tool_call_id': messages with role 'tool' must have a 'tool_call_id'**. (request id: 2024060617221462310269294550807) (request id: 20240606172214601955429dCigdvQs) (request id: 2024060617230165205730616076552) (request id: 2024060617221459456075403364817) (request id: 2024060617221456172038051798941) (request id: 2024060605221444438203159022960)", 'type': 'invalid_request_error', 'param': 'messages.[3].tool_call_id', 'code': None}}

where the tool message have tool_call_id，the message:
SystemMessage(content="XXX\n"),

HumanMessage(content='PO_num: XXX, task_id: XXX'),

AIMessage(content='', additional_kwargs={'tool_calls': [{'id': 'call_9kI8hcLdO0nxMl2oyXyKf5Rf', 'function': {'arguments': '{"task_id":"XXX","po_num":"XXX"}', 'name': 'po_info'}, 'type': 'function'}]}, response_metadata={'token_usage': {'completion_tokens': 34, 'prompt_tokens': 1020, 'total_tokens': 1054}, 'model_name': 'gpt-3.5-turbo-0125', 'system_fingerprint': None, 'finish_reason': 'tool_calls', 'logprobs': None}, id='run-61620ce1-f4f9-4a6e-bf85-f34ba26047fd-0', tool_calls=[{'name': 'po_info', 'args': {'task_id': 'XXX', 'po_num': 'XXX'}, 'id': 'call_9kI8hcLdO0nxMl2oyXyKf5Rf'}]),

**ToolMessage(content="{'result': (True, )}", additional_kwargs={'name': 'po_info'}, tool_call_id='call_9kI8hcLdO0nxMl2oyXyKf5Rf'),**

AIMessage(content='', additional_kwargs={'tool_calls': [{'id': 'call_knIR5jqxgXEigmOrqksyk0ch', 'function': {'arguments': '{"task_id":"XXX","sub_names":["XXX"],"suffix":["xls","xlsx"],"result_key":"finish_report_path"}', 'name': 'find_files'}, 'type': 'function'}]}, response_metadata={'token_usage': {'completion_tokens': 48, 'prompt_tokens': 1074, 'total_tokens': 1122}, 'model_name': 'gpt-3.5-turbo-0125', 'system_fingerprint': None, 'finish_reason': 'tool_calls', 'logprobs': None}, id='run-823edff7-03f1-4981-8d2a-b6b8f6f18f87-0', tool_calls=[{'name': 'find_files', 'args': {'task_id': 'XXX', 'sub_names': ['XXX'], 'suffix': ['xls', 'xlsx'], 'result_key': 'finish_report_path'}, 'id': 'call_knIR5jqxgXEigmOrqksyk0ch'}]),

**ToolMessage(content="{'result': (True, ['XXX\\XXX.xls'])}", additional_kwargs={'name': 'find_files'}, tool_call_id='call_knIR5jqxgXEigmOrqksyk0ch'),**

AIMessage(content='', additional_kwargs={'tool_calls': [{'id': 'call_KoQG2PTuIAwmaJWF9VgpAyGD', 'function': {'arguments': '{"excel_path":"XXX\\XXX.xls","key_list":["Item",],"result_key":"finish_info"}', 'name': 'excel_column_extract'}, 'type': 'function'}]}, response_metadata={'token_usage': {'completion_tokens': 65, 'prompt_tokens': 1158, 'total_tokens': 1223}, 'model_name': 'gpt-3.5-turbo-0125', 'system_fingerprint': None, 'finish_reason': 'tool_calls', 'logprobs': None}, id='run-900a681a-4921-4268-a4d6-7bbdbc7b7a39-0', tool_calls=[{'name': 'excel_column_extract', 'args': {'excel_path': 'XXX\XXX.xls', 'key_list': ['Item', ], 'result_key': 'finish_info'}, 'id': 'call_KoQG2PTuIAwmaJWF9VgpAyGD'}]),

**ToolMessage(content="{'result': (True, )}", additional_kwargs={'name': 'excel_column_extract'}, tool_call_id='call_KoQG2PTuIAwmaJWF9VgpAyGD')**

### System Info

langchain 0.2.1
langchain-community 0.2.1
langchain-core 0.2.1
langchain-experimental 0.0.59
langchain-openai 0.1.7
langchain-text-splitters 0.2.0
langgraph 0.0.55
langsmith 0.1.50

**Comment by straygar** [comment]
I get this as well, but extremely sporadically/seemingly at random.
