### ISSUE TITLE
Invalid Milvus URI when using Milvus lite with local DB

### ISSUE THREAD

**Issue by ErikTromp** [langchain-ai/langchain#22953]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

Directly from the documentation:

```
URI = "./milvus_demo.db"

vector_db = Milvus.from_documents(
    docs,
    embeddings,
    connection_args={"uri": URI},
)
```

### Error Message and Stack Trace (if applicable)

```
ERROR:langchain_community.vectorstores.milvus:Invalid Milvus URI: ./milvus_demo.db
Traceback (most recent call last):
  File "/home/erik/RAGMeUp/server/server.py", line 13, in <module>
    raghelper = RAGHelper(logger)
                ^^^^^^^^^^^^^^^^^
  File "/home/erik/RAGMeUp/server/RAGHelper.py", line 113, in __init__
    self.loadData()
  File "/home/erik/RAGMeUp/server/RAGHelper.py", line 258, in loadData
    vector_db = Milvus.from_documents(
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/erik/anaconda3/envs/rag/lib/python3.11/site-packages/langchain_core/vectorstores.py", line 550, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/erik/anaconda3/envs/rag/lib/python3.11/site-packages/langchain_community/vectorstores/milvus.py", line 1010, in from_texts
    vector_db = cls(
                ^^^^
  File "/home/erik/anaconda3/envs/rag/lib/python3.11/site-packages/langchain_core/_api/deprecation.py", line 183, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/erik/anaconda3/envs/rag/lib/python3.11/site-packages/langchain_community/vectorstores/milvus.py", line 206, in __init__
    self.alias = self._create_connection_alias(connection_args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/erik/anaconda3/envs/rag/lib/python3.11/site-packages/langchain_community/vectorstores/milvus.py", line 254, in _create_connection_alias
    raise ValueError("Invalid Milvus URI: %s", uri)
ValueError: ('Invalid Milvus URI: %s', './milvus_demo.db')
```

### Description

* Milvus should work with local file DB
* Connection URI cannot be anything local, triggers above error

### System Info

```
langchain==0.2.2
langchain-community==0.2.2
langchain-core==0.2.4
langchain-huggingface==0.0.2
langchain-milvus==0.1.1
langchain-postgres==0.0.6
langchain-text-splitters==0.2.1
milvus-lite==2.4.7
pymilvus==2.4.3
```

**Comment by ErikTromp** [comment]
Never mind, imported from the wrong place. Import should be:
`from langchain_milvus.vectorstores import Milvus`
