### ISSUE TITLE
Cannot save multi message chat prompt

### ISSUE THREAD

**Issue by okomarov** [langchain-ai/langchain#2341]
Can check here: https://replit.com/@OlegAzava/LangChainChatSave

```python
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    chat_prompt.save('./test.json')
  File "/home/runner/LangChainChatSave/venv/lib/python3.10/site-packages/langchain/prompts/chat.py", line 187, in save
    raise NotImplementedError
NotImplementedError
```
<img width="1460" alt="image" src="https://user-images.githubusercontent.com/3731173/229548079-44063f13-9ea3-4eff-a236-68d57ceee011.png">

**Comment by okomarov** [comment]
It seems like this one is a blocker also to get PromptLayer Registry working with the multi message prompts: https://github.com/MagnivOrg/prompt-layer-library/issues/8
