### ISSUE TITLE
ValueError: not enough values to unpack

### ISSUE THREAD

**Issue by avelican** [langchain-ai/langchain#2385]
```
MSI@GT62VR MINGW64 ~/dev/gpt/langchain/llm.py
$ python llm.py


> Entering new AgentExecutor chain...
Thought: I need to ask the human a question about what they want to do.

Action:
```
{
  "action": "Human",
  "action_input": "What do you want to do?"
}
```


What do you want to do?
Find out the similarities and differences between LangChain, Auto-GPT and GPT-Index (a.k.a. LlamaIndex)

Observation: Find out the similarities and differences between LangChain, Auto-GPT and GPT-Index (a.k.a. LlamaIndex)
Thought:Traceback (most recent call last):
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\agents\chat\base.py", line 50, in _extract_tool_and_input
    _, action, _ = text.split("```")
    ^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 3, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MSI\dev\gpt\langchain\llm.py\llm.py", line 24, in <module>
    agent.run("Ask the human what they want to do")
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chains\base.py", line 213, in run
    return self(args[0])[self.output_keys[0]]
           ^^^^^^^^^^^^^
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chains\base.py", line 116, in __call__
    raise e
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chains\base.py", line 113, in __call__
    outputs = self._call(inputs)
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\agents\agent.py", line 632, in _call
    next_step_output = self._take_next_step(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\agents\agent.py", line 548, in _take_next_step
    output = self.agent.plan(intermediate_steps, **inputs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\agents\agent.py", line 281, in plan
    action = self._get_next_action(full_inputs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\agents\agent.py", line 243, in _get_next_action
    parsed_output = self._extract_tool_and_input(full_output)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\agents\chat\base.py", line 55, in _extract_tool_and_input
    raise ValueError(f"Could not parse LLM output: {text}")
ValueError: Could not parse LLM output: I need to gather information about LangChain, Auto-GPT, and GPT-Index (a.k.a. LlamaIndex) to find out their similarities and differences. I will start by searching for information on these topics.
```

Here is my Python script:

```
# adapted from https://news.ycombinator.com/context?id=35328414

from langchain.agents import load_tools
from langchain.agents import initialize_agent
from langchain.chat_models import ChatOpenAI
 
llm = ChatOpenAI(model='gpt-4',temperature=0)

tools = load_tools(['python_repl', 'requests', 'terminal', 'serpapi', 'wikipedia', 'human',  'pal-math', 'pal-colored-objects'], llm=llm)
 
agent = initialize_agent(tools, llm, agent="chat-zero-shot-react-description", verbose=True)
 
agent.run("Ask the human what they want to do")
```

**Comment by avelican** [comment]
I got the same error again, this time as soon as I ran the script, before it even prompted me or performed any actions.

```
MSI@GT62VR MINGW64 ~/dev/gpt/langchain/llm.py
$ python llm.py


> Entering new AgentExecutor chain...
Traceback (most recent call last):
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\agents\chat\base.py", line 50, in _extract_tool_and_input
    _, action, _ = text.split("```")
    ^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 3, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MSI\dev\gpt\langchain\llm.py\llm.py", line 24, in <module>
    agent.run("Ask the human what they want to do")
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chains\base.py", line 213, in run
    return self(args[0])[self.output_keys[0]]
           ^^^^^^^^^^^^^
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chains\base.py", line 116, in __call__
    raise e
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chains\base.py", line 113, in __call__
    outputs = self._call(inputs)
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\agents\agent.py", line 632, in _call
    next_step_output = self._take_next_step(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\agents\agent.py", line 548, in _take_next_step
    output = self.agent.plan(intermediate_steps, **inputs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\agents\agent.py", line 281, in plan
    action = self._get_next_action(full_inputs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\agents\agent.py", line 243, in _get_next_action
    parsed_output = self._extract_tool_and_input(full_output)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\agents\chat\base.py", line 55, in _extract_tool_and_input
    raise ValueError(f"Could not parse LLM output: {text}")
ValueError: Could not parse LLM output: I cannot directly communicate with the human as an AI language model. However, I can help answer any questions or provide assistance with various tasks. Please let me know what you need help with or what question you want to ask.
```

**Comment by avelican** [comment]
I thought it might be due to running it in Git Bash, but running in cmd.exe produces the same result.

**Comment by gururise** [comment]
What is happening is the "Final Answer" is sometimes not appearing. Tends to happen when the scratchpad gets larger, seems the chat model forgets.
