### ISSUE TITLE
SQLiteCache under async setup randomly breaks due to sqlite3.IntegrityError (langchain_community.cache)

### ISSUE THREAD

**Issue by ziqizhang** [langchain-ai/langchain#23904]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

The following code is self-contained **except you need to download the public dataset** I use in order to replicate the problem. Please read the documentation below for where to get it.

```
import asyncio,sys,csv, random
from typing import Any, Dict, List
from langchain_community.cache import SQLiteCache
from langchain.callbacks.base import AsyncCallbackHandler
from langchain_community.callbacks import get_openai_callback
from langchain_core.messages import HumanMessage
from langchain_core.outputs import LLMResult
from langchain_openai import ChatOpenAI
from langchain_core.globals import set_llm_cache

class CustomAsyncHandler(AsyncCallbackHandler):

    async def on_chat_model_start(self, serialized: Dict[str, Any], prompts: List[str], **kwargs: Any
    ) -> None:
        pass

    """Async callback handler that can be used to handle callbacks from langchain."""
    async def on_llm_start(
        self, serialized: Dict[str, Any], prompts: List[str], **kwargs: Any
    ) -> None:
        pass

    async def on_llm_end(self, response: LLMResult, **kwargs: Any) -> None:
        await asyncio.sleep(1)
        #print(" >>> Your joke: {}".format(response.generations[0][0].text))

async def summarize(chat, text):
    # To enable streaming, we pass in `streaming=True` to the ChatModel constructor
    # Additionally, we pass in a list with our custom handler

    res=None
    with get_openai_callback() as cb:
        res=await chat.agenerate([[HumanMessage(content="Summarise the following text in 50 words:\n\n```\n{}\n```".format(text))]])
    return res.generations[0][0].text, cb.total_cost


async def test_batch(api, data:list, batchsize=10):
    chat = ChatOpenAI(
        model_name='gpt-4o',
        openai_api_key=api,
        callbacks=[CustomAsyncHandler()],
    )
    tasks = []
    for i in range(0, batchsize):
        text=random.choice(data)
        tasks.append(summarize(chat, text))

    return await asyncio.gather(*tasks)

def run_async(api, data:list, batchsize=10):
    count = 1
    loop = asyncio.new_event_loop()
    while True:
        print("[batch={} of {} chat jobs]".format(count, batchsize))
        res = loop.run_until_complete(test_batch(api, data, batchsize))
        total_cost=sum([r[1] for r in res])
        print("\tcompleted with {} results, cost={}".format(len(res), total_cost))
        count += 1

def read_sample_data(in_csv:str, topn_lines):
    stop=0
    rows=[]
    with open(in_csv, mode='r', encoding='utf-8') as file:
        # Create a CSV reader object with the specified delimiter and quote character
        csv_reader = csv.reader(file, delimiter=',', quotechar='"')
        for row in csv_reader:
            if stop==0:
                stop+=1
                continue
            rows.append(row[0])
            stop+=1
            if stop>topn_lines:
                break
    return rows

if __name__=='__main__':
    cache = SQLiteCache(database_path="example_cache.db")
    set_llm_cache(cache)
    #this is downloaded from https://www.kaggle.com/datasets/alfathterry/bbc-full-text-document-classification?resource=download
    #reads just the top n lines, then for each async job, takes a random text to summarise. eventually,
    #everything should've been cached
    data=read_sample_data('/home/zz/Data/news_text_samples/bbc_data.csv', topn_lines=100)
    #this line will run forever until you stop it. batchsize indiciates how many parallel chat jobs to run
    run_async(sys.argv[1], data, batchsize=20)
```

### Error Message and Stack Trace (if applicable)

```
Traceback (most recent call last):
  File "/home/zz/.cache/pypoetry/virtualenvs/charity-kg-dBz_RD7O-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1960, in _exec_single_context
    self.dialect.do_execute(
  File "/home/zz/.cache/pypoetry/virtualenvs/charity-kg-dBz_RD7O-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: full_llm_cache.prompt, full_llm_cache.llm, full_llm_cache.idx

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zz/Work/charity-kg/src/charitykg/sandbox/example_langchain_async.py", line 84, in <module>
    run_async(sys.argv[1], data, batchsize=20)
  File "/home/zz/Work/charity-kg/src/charitykg/sandbox/example_langchain_async.py", line 55, in run_async
    res = loop.run_until_complete(test_batch(api, data, batchsize))
  File "/home/zz/Programs/miniconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/zz/Work/charity-kg/src/charitykg/sandbox/example_langchain_async.py", line 48, in test_batch
    return await asyncio.gather(*tasks)
  File "/home/zz/Work/charity-kg/src/charitykg/sandbox/example_langchain_async.py", line 33, in summarize
    res=await chat.agenerate([[HumanMessage(content="Summarise the following text in 50 words:\n\n```\n{}\n```".format(text))]])
  File "/home/zz/.cache/pypoetry/virtualenvs/charity-kg-dBz_RD7O-py3.10/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 651, in agenerate
    raise exceptions[0]
  File "/home/zz/.cache/pypoetry/virtualenvs/charity-kg-dBz_RD7O-py3.10/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 855, in _agenerate_with_cache
    await llm_cache.aupdate(prompt, llm_string, result.generations)
  File "/home/zz/.cache/pypoetry/virtualenvs/charity-kg-dBz_RD7O-py3.10/lib/python3.10/site-packages/langchain_core/caches.py", line 138, in aupdate
    return await run_in_executor(None, self.update, prompt, llm_string, return_val)
  File "/home/zz/.cache/pypoetry/virtualenvs/charity-kg-dBz_RD7O-py3.10/lib/python3.10/site-packages/langchain_core/runnables/config.py", line 557, in run_in_executor
    return await asyncio.get_running_loop().run_in_executor(
  File "/home/zz/Programs/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zz/.cache/pypoetry/virtualenvs/charity-kg-dBz_RD7O-py3.10/lib/python3.10/site-packages/langchain_core/runnables/config.py", line 548, in wrapper
    return func(*args, **kwargs)
  File "/home/zz/.cache/pypoetry/virtualenvs/charity-kg-dBz_RD7O-py3.10/lib/python3.10/site-packages/langchain_community/cache.py", line 284, in update
    with Session(self.engine) as session, session.begin():
  File "/home/zz/.cache/pypoetry/virtualenvs/charity-kg-dBz_RD7O-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/util.py", line 146, in __exit__
    with util.safe_reraise():
  File "/home/zz/.cache/pypoetry/virtualenvs/charity-kg-dBz_RD7O-py3.10/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/zz/.cache/pypoetry/virtualenvs/charity-kg-dBz_RD7O-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/util.py", line 144, in __exit__
    self.commit()
  File "<string>", line 2, in commit
  File "/home/zz/.cache/pypoetry/virtualenvs/charity-kg-dBz_RD7O-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/zz/.cache/pypoetry/virtualenvs/charity-kg-dBz_RD7O-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/zz/.cache/pypoetry/virtualenvs/charity-kg-dBz_RD7O-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/zz/.cache/pypoetry/virtualenvs/charity-kg-dBz_RD7O-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "/home/zz/.cache/pypoetry/virtualenvs/charity-kg-dBz_RD7O-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4296, in flush
    self._flush(objects)
  File "/home/zz/.cache/pypoetry/virtualenvs/charity-kg-dBz_RD7O-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4431, in _flush
    with util.safe_reraise():
  File "/home/zz/.cache/pypoetry/virtualenvs/charity-kg-dBz_RD7O-py3.10/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/zz/.cache/pypoetry/virtualenvs/charity-kg-dBz_RD7O-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4392, in _flush
    flush_context.execute()
  File "/home/zz/.cache/pypoetry/virtualenvs/charity-kg-dBz_RD7O-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/zz/.cache/pypoetry/virtualenvs/charity-kg-dBz_RD7O-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/zz/.cache/pypoetry/virtualenvs/charity-kg-dBz_RD7O-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/zz/.cache/pypoetry/virtualenvs/charity-kg-dBz_RD7O-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1048, in _emit_insert_statements
    result = connection.execute(
  File "/home/zz/.cache/pypoetry/virtualenvs/charity-kg-dBz_RD7O-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1408, in execute
    return meth(
  File "/home/zz/.cache/pypoetry/virtualenvs/charity-kg-dBz_RD7O-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 513, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/zz/.cache/pypoetry/virtualenvs/charity-kg-dBz_RD7O-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1630, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/zz/.cache/pypoetry/virtualenvs/charity-kg-dBz_RD7O-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1839, in _execute_context
    return self._exec_single_context(
  File "/home/zz/.cache/pypoetry/virtualenvs/charity-kg-dBz_RD7O-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1979, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/zz/.cache/pypoetry/virtualenvs/charity-kg-dBz_RD7O-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2335, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/zz/.cache/pypoetry/virtualenvs/charity-kg-dBz_RD7O-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1960, in _exec_single_context
    self.dialect.do_execute(
  File "/home/zz/.cache/pypoetry/virtualenvs/charity-kg-dBz_RD7O-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: full_llm_cache.prompt, full_llm_cache.llm, full_llm_cache.idx
[SQL: INSERT INTO full_llm_cache (prompt, llm, idx, response) VALUES (?, ?, ?, ?)]
[parameters: ('[{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "HumanMessage"], "kwargs": {"content": "Summarise the following text in 5 ... (1288 characters truncated) ... se money for the relief fund. A release date has yet to be set for the recording, which was organised by Sharon Osbourne. \\n```", "type": "human"}}]', '{"id": ["langchain", "chat_models", "openai", "ChatOpenAI"], "kwargs": {"max_retries": 2, "model_name": "gpt-4o", "n": 1, "openai_api_key": {"id": [" ... (12 characters truncated) ... EY"], "lc": 1, "type": "secret"}, "openai_proxy": "", "temperature": 0.7}, "lc": 1, "name": "ChatOpenAI", "type": "constructor"}---[(\'stop\', None)]', 0, '{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "output", "ChatGeneration"], "kwargs": {"text": "Sir Elton John performed a charity co ... (1181 characters truncated) ... 0b-5074984500f1-0", "usage_metadata": {"input_tokens": 314, "output_tokens": 65, "total_tokens": 379}, "tool_calls": [], "invalid_tool_calls": []}}}}')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

```

### Description

When using SQLite cache in an async setup where X number of chat jobs are running in parallel, sqlite3.IntegrityError happens at randomly point. It seems to be caused by having the same key (prompt? llm_string?) inserted into the DB simultaneously, even though I am already using **.agenerate**

Note that this problem happens randomly so it is difficult to catch. I have written a minimal program above to replicate this error. 

**What does the minimal program do:**
- Reads top 50 news text from a csv file on your local OS (you need to download it from 'https://www.kaggle.com/datasets/alfathterry/bbc-full-text-document-classification?resource=download')
- (note: you MIGHT be able to reproduce the error using shorter texts instead but I am not sure. I just try to replicate my setup as close as possible as my program sends long prompts)
- Randomly chooses 20 news from the above 50
- Creates 20 chat jobs to run simultaneously (as a single 'batch'), each asking GPT to summarise the news
- Uses a shared SQLite cache object
- The program will print the total cost for each batch so eventually, you should see the cost remain constant at 0 meaning all calls go through the cache. But I never reached that point before the exception takes place.

**What will happen:**
Randomly at some point, the program will break with the error above. Make sure you delete the generated cache between different program runs. 

I ran the program 3 times:
- 1st time it breaks at batch 7
- 2nd time it breaks at batch 10
- 3rd time it breaks at batch 4

### System Info

langchain                0.2.6       
langchain-community      0.2.6
langchain-core           0.2.11
langchain-openai         0.1.14

OS: Ubuntu 22.04
Python: 3.10 managed by pyenv and poetry.

**Comment by brycepg** [comment]
Just encountered this error: `sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: full_llm_cache.prompt, full_llm_cache.llm, full_llm_cache.idx
[SQL: INSERT INTO full_llm_cache (prompt, llm, idx, response) VALUES (?, ?, ?, ?)]`
