### ISSUE TITLE
UnstructuredMarkdownLoader PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by AIDeepx** [langchain-ai/langchain#24388]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from langchain_community.embeddings import SparkLLMTextEmbeddings
from langchain.text_splitter import CharacterTextSplitter
from langchain_community.document_loaders import UnstructuredMarkdownLoader

import os
os.environ['TMPDIR'] = './.caches'
os.environ['TEMP'] = './.caches'

markdown_path = "./llms/doc1.md"
loader = UnstructuredMarkdownLoader(markdown_path)
documnets = loader.load()

print(loader)
```

### Error Message and Stack Trace (if applicable)

```bash
(LangChain) F:\PythonProject\LangChain>python ./llms/SparkLLMTextEmbeddings.py
Traceback (most recent call last):
  File "F:\PythonProject\LangChain\llms\SparkLLMTextEmbeddings.py", line 21, in <module>
    documnets = loader.load()
                ^^^^^^^^^^^^^
  File "C:\Users\asus\.conda\envs\LangChain\Lib\site-packages\langchain_core\document_loaders\base.py", line 30, in load
    return list(self.lazy_load())
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\.conda\envs\LangChain\Lib\site-packages\langchain_community\document_loaders\unstructured.py", line 89, in lazy_load
    elements = self._get_elements()
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\.conda\envs\LangChain\Lib\site-packages\langchain_community\document_loaders\markdown.py", line 45, in _get_elements
    return partition_md(filename=self.file_path, **self.unstructured_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\.conda\envs\LangChain\Lib\site-packages\unstructured\documents\elements.py", line 593, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\.conda\envs\LangChain\Lib\site-packages\unstructured\file_utils\filetype.py", line 626, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\.conda\envs\LangChain\Lib\site-packages\unstructured\file_utils\filetype.py", line 582, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\.conda\envs\LangChain\Lib\site-packages\unstructured\chunking\dispatch.py", line 74, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\.conda\envs\LangChain\Lib\site-packages\unstructured\partition\md.py", line 110, in partition_md
    return partition_html(
           ^^^^^^^^^^^^^^^
  File "C:\Users\asus\.conda\envs\LangChain\Lib\site-packages\unstructured\documents\elements.py", line 593, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\.conda\envs\LangChain\Lib\site-packages\unstructured\file_utils\filetype.py", line 626, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\.conda\envs\LangChain\Lib\site-packages\unstructured\file_utils\filetype.py", line 582, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\.conda\envs\LangChain\Lib\site-packages\unstructured\chunking\dispatch.py", line 74, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\.conda\envs\LangChain\Lib\site-packages\unstructured\partition\html\partition.py", line 107, in partition_html
    document.elements,
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\.conda\envs\LangChain\Lib\site-packages\unstructured\utils.py", line 187, in __get__
    value = self._fget(obj)
            ^^^^^^^^^^^^^^^
  File "C:\Users\asus\.conda\envs\LangChain\Lib\site-packages\unstructured\documents\html.py", line 76, in elements
    return list(iter_elements())
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\.conda\envs\LangChain\Lib\site-packages\unstructured\documents\html.py", line 71, in iter_elements
    for e in self._iter_elements(self._main):
  File "C:\Users\asus\.conda\envs\LangChain\Lib\site-packages\unstructured\documents\html.py", line 145, in _iter_elements
    yield from self._process_text_tag(tag_elem)
  File "C:\Users\asus\.conda\envs\LangChain\Lib\site-packages\unstructured\documents\html.py", line 450, in _process_text_tag
    element = self._parse_tag(tag_elem, include_tail_text)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\.conda\envs\LangChain\Lib\site-packages\unstructured\documents\html.py", line 409, in _parse_tag
    ElementCls = self._classify_text(text, tag_elem.tag)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\.conda\envs\LangChain\Lib\site-packages\unstructured\documents\html.py", line 94, in _classify_text
    if tag not in HEADING_TAGS and is_possible_narrative_text(text):
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\.conda\envs\LangChain\Lib\site-packages\unstructured\partition\text_type.py", line 80, in is_possible_narrative_text
    if exceeds_cap_ratio(text, threshold=cap_threshold):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\.conda\envs\LangChain\Lib\site-packages\unstructured\partition\text_type.py", line 276, in exceeds_cap_ratio
    if sentence_count(text, 3) > 1:
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\.conda\envs\LangChain\Lib\site-packages\unstructured\partition\text_type.py", line 225, in sentence_count
    sentences = sent_tokenize(text)
                ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\.conda\envs\LangChain\Lib\site-packages\unstructured\nlp\tokenize.py", line 136, in sent_tokenize
    _download_nltk_packages_if_not_present()
  File "C:\Users\asus\.conda\envs\LangChain\Lib\site-packages\unstructured\nlp\tokenize.py", line 130, in _download_nltk_packages_if_not_present
    download_nltk_packages()
  File "C:\Users\asus\.conda\envs\LangChain\Lib\site-packages\unstructured\nlp\tokenize.py", line 88, in download_nltk_packages
    urllib.request.urlretrieve(NLTK_DATA_URL, tgz_file)
  File "C:\Users\asus\.conda\envs\LangChain\Lib\urllib\request.py", line 250, in urlretrieve
    tfp = open(filename, 'wb')
          ^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'F:\\PythonProject\\LangChain\\.caches\\tmp27mpsjp4'
```

### Description

I don't know where I went wrong

### System Info

platform windows
Python 3.12.4

**Comment by fs-sudo** [comment]
what was the issue? got the same error here.

**Comment by aixelbsck** [comment]
How did you resolved it ?

**Comment by fs-sudo** [comment]
I am not able to, but saw the bug is closed :)

**Comment by aixelbsck** [comment]
i just resolved it doing :

`pip uninstall unstructured`
`pip install unstructured`

**Comment by SupJoeeeeeey** [comment]
> i just resolved it doing :
> 
> `pip uninstall unstructured` `pip install unstructured`

You just saved my day! How did you find this out?
