### ISSUE TITLE
Wrong prompt variable name in the RetryOutputParser class. "innput" should be replaced by "completion"

### ISSUE THREAD

**Issue by jameswpm** [langchain-ai/langchain#24440]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
# Code for example.py

from langchain.output_parsers import RetryOutputParser
from langchain_core.output_parsers.pydantic import PydanticOutputParser
from langchain_core.pydantic_v1 import BaseModel
from langchain_openai import ChatOpenAI
from langchain_core.runnables import RunnableLambda, RunnableParallel
from langchain_core.exceptions import OutputParserException


from langchain_core.prompts import (
    PromptTemplate,
)

class CustomParser(PydanticOutputParser):         

    def parse(self, output: str) -> dict:
        raise OutputParserException("Failed to parse")

    
    @property
    def _type(self) -> str:
        return "custom_parser_throw_exception"
    
class TestModel(BaseModel):
    a: int
    b: str

parser = CustomParser(pydantic_object=TestModel)

model = ChatOpenAI(temperature=0)

retry_parser = RetryOutputParser.from_llm(parser=parser, llm=model.with_structured_output(TestModel), max_retries=3)

def parse_with_prompt(args):
    completion = args['completion']

    if (type(completion) is TestModel):
        args = args.copy()
        del args['completion']
        completion = completion.json(ensure_ascii=False)
        args['completion'] = completion

    return retry_parser.parse_with_prompt(**args)

prompt = PromptTemplate(
    template="Answer the user query.\n{format_instructions}\n{query}\n",
    input_variables=["query"],
    partial_variables={"format_instructions": parser.get_format_instructions()},
)

completion_chain = prompt | model.with_structured_output(TestModel, include_raw=False)

main_chain = RunnableParallel(
    completion=completion_chain, prompt_value=prompt
) | RunnableLambda(parse_with_prompt)


print(main_chain.invoke({"query": "who is leo di caprios gf?"}))
```

I created a Custom Parser inheriting it from the `PydanticOutputParser` to force it to throw an `OutputParserException.` The code encapsulates it with the `RetryOutputParser`.

### Error Message and Stack Trace (if applicable)

```
Traceback (most recent call last):
  File "C:\Projects\ENV\Lib\site-packages\langchain\output_parsers\retry.py", line 90, in parse_with_prompt
    return self.parser.parse(completion)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\src\example.py", line 18, in parse
    raise OutputParserException("Failed to parse")
langchain_core.exceptions.OutputParserException: Failed to parse

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Projects\src\example.py", line 59, in <module>
    print(main_chain.invoke({"query": "who is leo di caprios gf?"}))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\ENV\Lib\site-packages\langchain_core\runnables\base.py", line 2824, in invoke
    input = step.invoke(input, config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\ENV\Lib\site-packages\langchain_core\runnables\base.py", line 4387, in invoke
    return self._call_with_config(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\ENV\Lib\site-packages\langchain_core\runnables\base.py", line 1734, in _call_with_config
    context.run(
  File "C:\Projects\ENV\Lib\site-packages\langchain_core\runnables\config.py", line 379, in call_func_with_variable_args
    return func(input, **kwargs)  # type: ignore[call-arg]
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\ENV\Lib\site-packages\langchain_core\runnables\base.py", line 4243, in _invoke
    output = call_func_with_variable_args(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\ENV\Lib\site-packages\langchain_core\runnables\config.py", line 379, in call_func_with_variable_args
    return func(input, **kwargs)  # type: ignore[call-arg]
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\src\example.py", line 44, in parse_with_prompt
    return retry_parser.parse_with_prompt(**args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\ENV\Lib\site-packages\langchain\output_parsers\retry.py", line 103, in parse_with_prompt
    completion = self.retry_chain.invoke(
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\ENV\Lib\site-packages\langchain_core\runnables\base.py", line 2822, in invoke
    input = step.invoke(input, config, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\ENV\Lib\site-packages\langchain_core\prompts\base.py", line 179, in invoke
    return self._call_with_config(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\ENV\Lib\site-packages\langchain_core\runnables\base.py", line 1734, in _call_with_config
    context.run(
  File "C:\Projects\ENV\Lib\site-packages\langchain_core\runnables\config.py", line 379, in call_func_with_variable_args
    return func(input, **kwargs)  # type: ignore[call-arg]
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\ENV\Lib\site-packages\langchain_core\prompts\base.py", line 153, in _format_prompt_with_error_handling
    _inner_input = self._validate_input(inner_input)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\ENV\Lib\site-packages\langchain_core\prompts\base.py", line 145, in _validate_input
    raise KeyError(
KeyError: "Input to PromptTemplate is missing variables {'completion'}.  Expected: ['completion', 'prompt'] Received: ['prompt', 'input']"
```

### Description

The `RetryOutputParser` is apparently a bit buggy, and it's already demanding some custom workarounds to work appropriately with Pydantic data (cf. [this issue](https://github.com/langchain-ai/langchain/issues/19145), from which I adapted the workaround code).

However, the bug I'm flagging is for a wrong-named prompt variable in the code.

What I expect: Since the parser throws the exception, I expect that the Retry Parser calls the LLM again with the prompt and the error message to perform the retry.

What is happening: It throws an error `KeyError: "Input to PromptTemplate is missing variables {'completion'}.  Expected: ['completion', 'prompt'] Received: ['prompt', 'input']"`

Looking at the source code for the `RetryOutputParser` it's possible to see that indeed it's passing the completion value labeled with input.

```python
class RetryOutputParser(BaseOutputParser[T]):
   #[...]
   def parse_with_prompt(self, completion: str, prompt_value: PromptValue) -> T:
        """Parse the output of an LLM call using a wrapped parser.

        Args:
            completion: The chain completion to parse.
            prompt_value: The prompt to use to parse the completion.

        Returns:
            The parsed completion.
        """
        retries = 0

        while retries <= self.max_retries:
            try:
                return self.parser.parse(completion)
            except OutputParserException as e:
                if retries == self.max_retries:
                    raise e
                else:
                    retries += 1
                    if self.legacy and hasattr(self.retry_chain, "run"):
                        completion = self.retry_chain.run(
                            prompt=prompt_value.to_string(),
                            completion=completion,
                            error=repr(e),
                        )
                    else:
                        completion = self.retry_chain.invoke(
                            dict(
                                prompt=prompt_value.to_string(),
                                input=completion,  # <<<<<--------- WRONG NAME
                            )
                        )

        raise OutputParserException("Failed to parse")
   #[...]

```

### System Info

System Information
------------------
> OS:  Windows
> OS Version:  10.0.22621
> Python Version:  3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]

Package Information
-------------------
> langchain_core: 0.2.21
> langchain: 0.2.9
> langchain_community: 0.2.5
> langsmith: 0.1.90
> langchain_openai: 0.1.17
> langchain_text_splitters: 0.2.1
> langchainhub: 0.1.20

**Comment by jameswpm** [comment]
I can do the PR (already tested briefly with a local version), but I prefer someone else to confirm the bug before to ensure the problem is not with my environment. If so, it can be assigned to me.

**Comment by eyurtsev** [comment]
Have you confirmed that the issue is present on master? We had a fix merged for RetryOutputParser just recently(https://github.com/langchain-ai/langchain/pull/23967)

**Comment by jameswpm** [comment]
I tried on the last stable version, but not in the master branch. I didn't find this issue/PR in my search, probably because I used the wrong terms.

Based on the description, the PR mentioned should solve the issue.
