### ISSUE TITLE
groq.NotFoundError: Error code: 404 , Route POST:/openai/v1/chat/completions not found

### ISSUE THREAD

**Issue by njnuwjq** [langchain-ai/langchain#25160]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

llm = ChatGroq(base_url="http://10.xx.xx.127:8080",temperature=0, groq_api_key="gsk_...", model_name="llama3-8b-8192")

input = "how to restart linux server"

agent_executor.invoke({"input": input})

### Error Message and Stack Trace (if applicable)

errInfo:: how to restart linux server

> Entering new AgentExecutor chain...
Traceback (most recent call last):
  File "/Usr-xxx/pyProj/testLangchainCompileAssist.py", line 101, in <module>
    agent_executor.invoke({"input": input})
  File "/Usr-xxx/anaconda3/lib/python3.11/site-packages/langchain/chains/base.py", line 166, in invoke
    raise e
  File "/Usr-xxx/anaconda3/lib/python3.11/site-packages/langchain/chains/base.py", line 156, in invoke
    self._call(inputs, run_manager=run_manager)
  File "/Usr-xxx/anaconda3/lib/python3.11/site-packages/langchain/agents/agent.py", line 1636, in _call
    next_step_output = self._take_next_step(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Usr-xxx/anaconda3/lib/python3.11/site-packages/langchain/agents/agent.py", line 1342, in _take_next_step
    [
  File "/Usr-xxx/anaconda3/lib/python3.11/site-packages/langchain/agents/agent.py", line 1342, in <listcomp>
    [
  File "/Usr-xxx/anaconda3/lib/python3.11/site-packages/langchain/agents/agent.py", line 1370, in _iter_next_step
    output = self.agent.plan(
             ^^^^^^^^^^^^^^^^
  File "/Usr-xxx/anaconda3/lib/python3.11/site-packages/langchain/agents/agent.py", line 580, in plan
    for chunk in self.runnable.stream(inputs, config={"callbacks": callbacks}):
  File "/Usr-xxx/anaconda3/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 3253, in stream
    yield from self.transform(iter([input]), config, **kwargs)
  File "/Usr-xxx/anaconda3/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 3240, in transform
    yield from self._transform_stream_with_config(
  File "/Usr-xxx/anaconda3/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 2053, in _transform_stream_with_config
    chunk: Output = context.run(next, iterator)  # type: ignore
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Usr-xxx/anaconda3/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 3202, in _transform
    for output in final_pipeline:
  File "/Usr-xxx/anaconda3/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 1271, in transform
    for ichunk in input:
  File "/Usr-xxx/anaconda3/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 5267, in transform
    yield from self.bound.transform(
  File "/Usr-xxx/anaconda3/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 1289, in transform
    yield from self.stream(final, config, **kwargs)
  File "/Usr-xxx/anaconda3/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 373, in stream
    raise e
  File "/Usr-xxx/anaconda3/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 353, in stream
    for chunk in self._stream(messages, stop=stop, **kwargs):
  File "/Usr-xxx/anaconda3/lib/python3.11/site-packages/langchain_groq/chat_models.py", line 507, in _stream
    response = self.client.create(
               ^^^^^^^^^^^^^^^^^^^
  File "/Usr-xxx/anaconda3/lib/python3.11/site-packages/groq/resources/chat/completions.py", line 289, in create
    return self._post(
           ^^^^^^^^^^^
  File "/Usr-xxx/anaconda3/lib/python3.11/site-packages/groq/_base_client.py", line 1225, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Usr-xxx/anaconda3/lib/python3.11/site-packages/groq/_base_client.py", line 920, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/Usr-xxx/anaconda3/lib/python3.11/site-packages/groq/_base_client.py", line 1018, in _request
    raise self._make_status_error_from_response(err.response) from None
groq.NotFoundError: Error code: 404 - {'message': 'Route POST:/openai/v1/chat/completions not found', 'error': 'Not Found', 'statusCode': 404}

### Description

run jan and api server on 10.xxxx.127:8080, and can visit the apis on my mac

get: http://10.xxxx.127:8080/v1/models
rsp: {"object":"list","data":[{"sources":[{"filename":"aya-23-35B-Q4_K_M.gguf",.....

get:http://localhost:8080/v1/models/llama3-8b-8192
rsp: {"sources":[{"url":"https://groq.com"}],"id":"llama3-8b-8192","object":"model","name":"Groq Llama 3 8b","version":"1.1","description":"Groq Llama 3 8b with supercharged speed!","format":"api","settings":{},"parameters":{"max_tokens":8192,"temperature":0.7,"top_p":0.95,"stream":true,"stop":[],"frequency_penalty":0,"presence_penalty":0},"metadata":{"author":"Meta","tags":["General","Big Context Length"]},"engine":"groq"}

get: http://10.xxx.127:8080/openai/v1/chat/completions
rsp: {"message":"Route GET:/openai/v1/chat/completions not found","error":"Not Found","statusCode":404}

### System Info

pip freeze | grep langchain
langchain==0.2.7
langchain-cli==0.0.25
langchain-community==0.2.7
langchain-core==0.2.25
langchain-experimental==0.0.62
langchain-google-community==1.0.6
langchain-groq==0.1.6
langchain-ollama==0.1.0
langchain-openai==0.1.15
langchain-text-splitters==0.2.2
langchainhub==0.1.20

Python 3.11.3 (main, Apr 19 2023, 18:49:55) [Clang 14.0.6 ] on darwin

**Comment by njnuwjq** [comment]
hi 
seems not the same topic
https://github.com/langchain-ai/langchain/issues/25022 is the connection issue, while my issue is api path not correct

llm = ChatGroq(temperature=0](http://10.xx.xx.127:8080%22,temperature=0/), groq_api_key="gsk_...", model_name="llama3-8b-8192")
llm.invoke("hello") work well

llm = ChatGroq(base_url="http://10.xx.xx.127:8080",temperature=0](http://10.xx.xx.127:8080%22,temperature=0/), groq_api_key="gsk_...", model_name="llama3-8b-8192")
get the error /openai/v1/chat/completions not found', 'error': 'Not Found', 'statusCode': 404

the groq is hosted with Jan on the mac, the base url refer to the api server by Jan
and the path is  /v1/chat/completions, but not  /openai/v1/chat/completions

according to https://platform.openai.com/docs/api-reference/chat
[Create chat completion](https://platform.openai.com/docs/api-reference/chat/create)
post  https://api.openai.com/v1/chat/completions

so seems the url encoded in langchain is incompatible with Jan and openapi?
could you look deeper into this issue?

thanks a lot

**Comment by njnuwjq** [comment]
<img width="1440" alt="Screenshot 2024-08-14 at 10 54 29" src="https://github.com/user-attachments/assets/3c1b01c0-fee7-4922-8835-1d8ffc47f0ed">


could you install Jan, start local http server, and the error will occurs with the code


llm = ChatGroq(temperature=0](http://127.0.0.1:1337%22,temperature=0/), groq_api_key="gsk_...", model_name="llama3-8b-8192")
llm.invoke("hello")
