### ISSUE TITLE
OpenAIModerationChain doesn't handle API key correctly for openai>=v1.0.0

### ISSUE THREAD

**Issue by alex-seymour** [langchain-ai/langchain#25176]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from langchain.chains import OpenAIModerationChain
from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import OpenAI

api_key = "..."
model = OpenAI(openai_api_key=api_key)
prompt = ChatPromptTemplate.from_messages([("human", "the sky is")])
moderate = OpenAIModerationChain(openai_api_key=api_key)
chain = prompt | model | moderate
print(chain.invoke({}))
```

### Error Message and Stack Trace (if applicable)

```
Traceback (most recent call last):
  File "/app/demo.py", line 8, in <module>
    moderate = OpenAIModerationChain(openai_api_key=api_key)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/langchain_core/load/serializable.py", line 113, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.12/site-packages/pydantic/v1/main.py", line 339, in __init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pydantic/v1/main.py", line 1048, in validate_model
    input_data = validator(cls_, input_data)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/langchain/chains/moderation.py", line 69, in validate_environment
    values["client"] = openai.OpenAI()
                       ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/openai/_client.py", line 105, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
```

### Description

It appears that the fix for #13685 may be incomplete. openai >= v1.0.0 moved to prefer explicit instantiation of clients, but `OpenAIModerationChain.validate_environment` still assigns the API key to `openai.api_key` regardless of the version of openai that's installed.
https://github.com/langchain-ai/langchain/blob/d77c7c4236df8e56fbe3acc8e0a71b57b48f1678/libs/langchain/langchain/chains/moderation.py#L58

Using `OpenAIModerationChain(openai_api_key="...")` instead of using the `OPENAI_API_KEY` env var results in `openai.OpenAI` throwing an exception because it expects the key to be passed to the `api_key` parameter if the env var isn't present.
https://github.com/langchain-ai/langchain/blob/d77c7c4236df8e56fbe3acc8e0a71b57b48f1678/libs/langchain/langchain/chains/moderation.py#L69-L70

Looking at [where the key is checked](https://github.com/openai/openai-python/blob/90dd21531efe351b72ce0a72150048b6c7f640e0/src/openai/_client.py#L102-L112) in `openai.OpenAI`, it looks like the same is also true of the organization.

### System Info

```
System Information
------------------
> OS:  Linux
> OS Version:  #1 SMP Fri Mar 29 23:14:13 UTC 2024
> Python Version:  3.12.5 (main, Aug  7 2024, 19:13:36) [GCC 12.2.0]

Package Information
-------------------
> langchain_core: 0.2.29
> langchain: 0.2.12
> langsmith: 0.1.98
> langchain_openai: 0.1.20
> langchain_text_splitters: 0.2.2

Optional packages not installed
-------------------------------
> langgraph
> langserve

Other Dependencies
------------------
> aiohttp: 3.10.1
> async-timeout: Installed. No version info available.
> jsonpatch: 1.33
> numpy: 1.26.4
> openai: 1.40.1
> orjson: 3.10.6
> packaging: 24.1
> pydantic: 2.8.2
> PyYAML: 6.0.2
> requests: 2.32.3
> SQLAlchemy: 2.0.32
> tenacity: 8.5.0
> tiktoken: 0.7.0
> typing-extensions: 4.12.2
```

**Comment by varjas** [comment]
Hi,

This issue is still occurring on recent versions and isn't usable when passing the API key as an argument.

### Example Code
```py
from langchain.chains import OpenAIModerationChain

api_key = "..."

moderation = OpenAIModerationChain(openai_api_key=api_key)
```

### Error Message and Stack Trace
```
---------------------------------------------------------------------------
OpenAIError                               Traceback (most recent call last)
Cell In[2], line 1
----> 1 moderation = OpenAIModerationChain(openai_api_key=api_key)

File /usr/local/lib/python3.11/site-packages/langchain_core/load/serializable.py:125, in Serializable.__init__(self, *args, **kwargs)
    123 def __init__(self, *args: Any, **kwargs: Any) -> None:
    124     """"""
--> 125     super().__init__(*args, **kwargs)

    [... skipping hidden 1 frame]

File /usr/local/lib/python3.11/site-packages/langchain/chains/moderation.py:70, in OpenAIModerationChain.validate_environment(cls, values)
     68         values["client"] = openai.Moderation
     69     else:
---> 70         values["client"] = openai.OpenAI()
     71         values["async_client"] = openai.AsyncOpenAI()
     73 except ImportError:

File /usr/local/lib/python3.11/site-packages/openai/_client.py:110, in OpenAI.__init__(self, api_key, organization, project, base_url, websocket_base_url, timeout, max_retries, default_headers, default_query, http_client, _strict_response_validation)
    108     api_key = os.environ.get("OPENAI_API_KEY")
    109 if api_key is None:
--> 110     raise OpenAIError(
    111         "The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable"
    112     )
    113 self.api_key = api_key
    115 if organization is None:

OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
```

### System Info
```
System Information
------------------
> OS: Linux
> OS Version: amazonlinux:2023.6.20241111.0
> Python Version: 3.11.6

Package Information
-------------------
> langchain==0.3.14
> langchain-core==0.3.29
> langchain-openai==0.3.0
> langchain-text-splitters==0.3.5
> openai==1.59.6
```
