### ISSUE TITLE
Chat model Tencent Hunyuan should deal with system prompt message.

### ISSUE THREAD

**Issue by icejean** [langchain-ai/langchain#25475]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

import os
from keys import keys   # My secret ID and secret keys are stored in it.

from langchain_community.chat_models import ChatHunyuan
from langchain_core.messages import HumanMessage, SystemMessage
from langchain.prompts import (
    ChatPromptTemplate,
    MessagesPlaceholder,
    HumanMessagePromptTemplate,
    SystemMessagePromptTemplate
)

llm = ChatHunyuan(
    hunyuan_app_id=1303211952,         # Replace it with yours.
    hunyuan_secret_id = keys.tx_id,    # Replace it with yours.
    hunyuan_secret_key = keys.tx_key,  # Replace it with yours.
    model = "hunyuan-pro"
)

system_template="""
You're a helpful assistant.
"""
system_message_prompt = SystemMessagePromptTemplate.from_template(system_template)

human_template="""
Please introduce yourself to me.
"""
human_message_prompt = HumanMessagePromptTemplate.from_template(human_template)

chat_prompt = ChatPromptTemplate.from_messages(
    [system_message_prompt, MessagesPlaceholder("chat_history"), human_message_prompt]
)

chain = chat_prompt | llm

chat_history = []
answer = chain.invoke({
    "chat_history": chat_history,
    })
print(answer.content)

### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/anaconda3/envs/graphrag/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 2878, in invoke
    input = context.run(step.invoke, input, config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/anaconda3/envs/graphrag/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 291, in invoke
    self.generate_prompt(
  File "/usr/lib64/anaconda3/envs/graphrag/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 791, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/anaconda3/envs/graphrag/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 648, in generate
    raise e
  File "/usr/lib64/anaconda3/envs/graphrag/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 638, in generate
    self._generate_with_cache(
  File "/usr/lib64/anaconda3/envs/graphrag/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 860, in _generate_with_cache
    result = self._generate(
             ^^^^^^^^^^^^^^^
  File "/usr/lib64/anaconda3/envs/graphrag/lib/python3.11/site-packages/langchain_community/chat_models/hunyuan.py", line 217, in _generate
    res = self._chat(messages, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/anaconda3/envs/graphrag/lib/python3.11/site-packages/langchain_community/chat_models/hunyuan.py", line 268, in _chat
    "Messages": [_convert_message_to_dict(m) for m in messages],
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/anaconda3/envs/graphrag/lib/python3.11/site-packages/langchain_community/chat_models/hunyuan.py", line 268, in <listcomp>
    "Messages": [_convert_message_to_dict(m) for m in messages],
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/anaconda3/envs/graphrag/lib/python3.11/site-packages/langchain_community/chat_models/hunyuan.py", line 47, in _convert_message_to_dict
    raise TypeError(f"Got unknown type {message}")
TypeError: Got unknown type content="\nYou're a helpful assistant.\n"
>>> print(answer.content)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'answer' is not defined

### Description

The function _convert_message_to_dict() in hunyuan.py should deal with system prompt message:
```
def _convert_message_to_dict(message: BaseMessage) -> dict:
    message_dict: Dict[str, Any]
    if isinstance(message, ChatMessage):
        message_dict = {"Role": message.role, "Content": message.content}
    elif isinstance(message, HumanMessage):
        message_dict = {"Role": "user", "Content": message.content}
    elif isinstance(message, AIMessage):
        message_dict = {"Role": "assistant", "Content": message.content}
    else:
        raise TypeError(f"Got unknown type {message}")

    return message_dict
```
And the following modified version is O.K.:
```
def _convert_message_to_dict(message: BaseMessage) -> dict:
    message_dict: Dict[str, Any]
    if isinstance(message, ChatMessage):
        message_dict = {"Role": message.role, "Content": message.content}
    elif isinstance(message, HumanMessage):
        message_dict = {"Role": "user", "Content": message.content}
    elif isinstance(message, AIMessage):
        message_dict = {"Role": "assistant", "Content": message.content}
    elif isinstance(message, SystemMessage):
        message_dict = {"Role": "system", "Content": message.content}
    else:
        raise TypeError(f"Got unknown type {message}")

    return message_dict
```

### System Info

(graphrag) root@Jean-Y9000X:~# pip freeze | grep langchain
langchain==0.2.13
langchain-cli==0.0.25
langchain-community==0.2.12
langchain-core==0.2.30
langchain-experimental==0.0.62
langchain-google-genai==1.0.7
langchain-google-vertexai==1.0.6
langchain-groq==0.1.6
langchain-openai==0.1.16
langchain-text-splitters==0.2.2
langchain-wenxin==0.10.2

platform WSL2 Ubuntu 22
python version 3.11

**Comment by AffanBinFaisal** [comment]
Do you still have errors after modifying the code?

**Comment by icejean** [comment]
It's addressed in that way.
