### ISSUE TITLE
SelfQueryRetriever interprets numbers in queries as strings

### ISSUE THREAD

**Issue by mdieterle** [langchain-ai/langchain#25659]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
        llm_model = Ollama(model="llama3.1:70b-instruct-q5_K_M", temperature=0)

        docs = [
            Document(
                page_content="A bunch of scientists bring back dinosaurs and mayhem breaks loose",
                metadata={"year": 1993, "rating": 7.7, "genre": "science fiction"},
            ),
            Document(
                page_content="Leo DiCaprio gets lost in a dream within a dream within a dream within a ...",
                metadata={"year": 2010, "director": "Christopher Nolan", "rating": 8.2},
            ),
            Document(
                page_content="A psychologist / detective gets lost in a series of dreams within dreams within dreams and Inception reused the idea",
                metadata={"year": 2006, "director": "Satoshi Kon", "rating": 8.6},
            ),
            Document(
                page_content="A bunch of normal-sized women are supremely wholesome and some men pine after them",
                metadata={"year": 2019, "director": "Greta Gerwig", "rating": 8.3},
            ),
            Document(
                page_content="Toys come alive and have a blast doing so",
                metadata={"year": 1995, "genre": "animated"},
            ),
            Document(
                page_content="Three men walk into the Zone, three men walk out of the Zone",
                metadata={
                    "year": 1979,
                    "director": "Andrei Tarkovsky",
                    "genre": "science fiction",
                    "rating": 9.9,
                },
            ),
        ]

        embeddings = OllamaEmbeddings(
            model="llama3.1:70b-instruct-q5_K_M"
        )

        vectorstore_db = Chroma.from_documents(documents=docs,
                                               embedding=embeddings)

        metadata_field_info = [
            AttributeInfo(
                name="genre",
                description="The genre of the movie",
                type="string or list[string]",
            ),
            AttributeInfo(
                name="year",
                description="The year the movie was released",
                type="integer",
            ),
            AttributeInfo(
                name="director",
                description="The name of the movie director",
                type="string",
            ),
            AttributeInfo(
                name="rating", description="A 1-10 rating for the movie", type="float"
            ),
        ]

        document_content_description = "Brief summary of a movie"

        retriever = SelfQueryRetriever.from_llm(
            llm_model,
            vectorstore_db,
            document_content_description,
            metadata_field_info,
            verbose=True
        )

        retriever.invoke("I want to watch a movie rated higher than 8.5")
```

### Error Message and Stack Trace (if applicable)

```
Traceback (most recent call last):
  File "/home/krn/workspace/ai2ch/query_patient_json_vdb.py", line 24, in <module>
    run()
  File "/home/krn/workspace/ai2ch/query_patient_json_vdb.py", line 19, in run
    runner._query_json_vdb()
  File "/home/krn/workspace/ai2ch/src/utils/llm_runner.py", line 257, in _query_json_vdb
    results = retriever.invoke("What's a highly rated (above 8.5) science fiction film?")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/krn/miniconda3/envs/ollama_p3_11/lib/python3.11/site-packages/langchain_core/retrievers.py", line 221, in invoke
    raise e
  File "/home/krn/miniconda3/envs/ollama_p3_11/lib/python3.11/site-packages/langchain_core/retrievers.py", line 214, in invoke
    result = self._get_relevant_documents(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/krn/miniconda3/envs/ollama_p3_11/lib/python3.11/site-packages/langchain/retrievers/self_query/base.py", line 269, in _get_relevant_documents
    docs = self._get_docs_with_query(new_query, search_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/krn/miniconda3/envs/ollama_p3_11/lib/python3.11/site-packages/langchain/retrievers/self_query/base.py", line 243, in _get_docs_with_query
    docs = self.vectorstore.search(query, self.search_type, **search_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/krn/miniconda3/envs/ollama_p3_11/lib/python3.11/site-packages/langchain_core/vectorstores/base.py", line 562, in search
    return self.similarity_search(query, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/krn/miniconda3/envs/ollama_p3_11/lib/python3.11/site-packages/langchain_community/vectorstores/chroma.py", line 349, in similarity_search
    docs_and_scores = self.similarity_search_with_score(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/krn/miniconda3/envs/ollama_p3_11/lib/python3.11/site-packages/langchain_community/vectorstores/chroma.py", line 439, in similarity_search_with_score
    results = self.__query_collection(
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/krn/miniconda3/envs/ollama_p3_11/lib/python3.11/site-packages/langchain_core/utils/utils.py", line 47, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/krn/miniconda3/envs/ollama_p3_11/lib/python3.11/site-packages/langchain_community/vectorstores/chroma.py", line 156, in __query_collection
    return self._collection.query(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/krn/miniconda3/envs/ollama_p3_11/lib/python3.11/site-packages/chromadb/api/models/Collection.py", line 184, in query
    ) = self._validate_and_prepare_query_request(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/krn/miniconda3/envs/ollama_p3_11/lib/python3.11/site-packages/chromadb/api/models/CollectionCommon.py", line 363, in _validate_and_prepare_query_request
    valid_where = validate_where(where) if where else {}
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/krn/miniconda3/envs/ollama_p3_11/lib/python3.11/site-packages/chromadb/api/types.py", line 385, in validate_where
    raise ValueError(
ValueError: Expected operand value to be an int or a float for operator $gt, got 8.5
```

### Description

I implemented a self-querying retriever following the example from langchain [https://python.langchain.com/v0.2/docs/integrations/retrievers/self_query/chroma_self_query/](url) with ollama.

However, the example is not working, producing the above error.

It seems that the number '8.5' is interpreted as string rather than float. Consequently the chroma filter crashes, since the required $gt operator is only supported for numerical values - int or float values, not strings.

### System Info

python -m langchain_core.sys_info

System Information
------------------
> OS:  Linux
> OS Version:  #1 SMP Sun Jan 14 23:40:17 UTC 2024
> Python Version:  3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0]

Package Information
-------------------
> langchain_core: 0.2.24
> langchain: 0.2.8
> langchain_community: 0.2.6
> langsmith: 0.1.93
> langchain_text_splitters: 0.2.2

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve

**Comment by mdieterle** [comment]
@ccurme thanks for taking care of it. do you have an update on this?
