### ISSUE TITLE
We could not parse the JSON body of your request. The content of 'assistant' should be a string type.

### ISSUE THREAD

**Issue by NowLoadY** [langchain-ai/langchain#25701]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [x] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

https://python.langchain.com/v0.2/docs/how_to/tool_artifacts/#creating-from-basetool-class

```python
from langchain_openai.chat_models import ChatOpenAI
from langchain_core.messages import HumanMessage
from langgraph.checkpoint.memory import MemorySaver
from langgraph.prebuilt import create_react_agent
from langchain.tools import BaseTool
from typing import List, Tuple
import random


class GenerateRandomFloats(BaseTool):
    name: str = "generate_random_floats"
    description: str = "Generate size random floats in the range [min, max]."
    response_format: str = "content_and_artifact"

    ndigits: int = 2

    def _run(self, min: float, max: float, size: int) -> Tuple[str, List[float]]:
        range_ = max - min
        array = [
            round(min + (range_ * random.random()), ndigits=self.ndigits)
            for _ in range(size)
        ]
        content = f"Generated {size} floats in [{min}, {max}], rounded to {self.ndigits} decimals."
        return content, array
    
class MyAgent:
    def __init__(self):
        self.llm_langchain = ChatOpenAI(temperature=0, model="gpt-4o-mini",
                                        openai_api_key="api_key",
                                        base_url="https://api.deepbricks.ai/v1/")
        self.memory_langchain = MemorySaver()
        self.tools = [GenerateRandomFloats()]
        self.agent_langchain = create_react_agent(
            self.llm_langchain,
            self.tools,
            checkpointer=self.memory_langchain,
        )

    def gpt_response(self, prompt):
        config = {"configurable": {"thread_id": "default_thread"}}
        response_full = self.agent_langchain.invoke(
            {"messages": [HumanMessage(content=prompt)]}, config
        )
        print("Response received:", response_full)
        return response_full

    def run(self):
        while True:
            user_input = input("You: ")
            if user_input.lower() in ["exit", "quit"]:
                break
            response = self.gpt_response(user_input)
            print("Agent:", response['messages'][-1].content)

if __name__ == "__main__":
    agent = MyAgent()
    agent.run()
```

### Error Message and Stack Trace (if applicable)

**You: generate_random_floats**
Response received: {'messages': [HumanMessage(content='generate_random_floats', id='6f43e374-9f5e-409f-84ed-028b5975b4ba'), AIMessage(content='Please provide the following parameters to generate random floats:\n\n1. **min** - The minimum value of the range.\n2. **max** - The maximum value of the range.\n3. **size** - The number of random floats to generate.', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 51, 'prompt_tokens': 65, 'total_tokens': 116}, 'model_name': 'gpt-4o-mini', 'system_fingerprint': 'fp_48196bc67a', 'finish_reason': 'stop', 'logprobs': None}, id='run-0abe502c-5790-4e8a-88cb-33ae12deb5ec-0', usage_metadata={'input_tokens': 65, 'output_tokens': 51, 'total_tokens': 116})]}

**Agent**: Please provide the following parameters to generate random floats:

1. **min** - The minimum value of the range.
2. **max** - The maximum value of the range.
3. **size** - The number of random floats to generate.

**You: 0,5,2**

Traceback (most recent call last):
  File "D:\code\python\VITS-fast-fine-tuning-main\agent_chat_test.py", line 57, in <module>
    agent.run()
  File "D:\code\python\VITS-fast-fine-tuning-main\agent_chat_test.py", line 52, in run
    response = self.gpt_response(user_input)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\python\VITS-fast-fine-tuning-main\agent_chat_test.py", line 41, in gpt_response    
    response_full = self.agent_langchain.invoke(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\app_install_path\miniconda3\envs\311_main\Lib\site-packages\langgraph\pregel\__init__.py", line 1307, in invoke
    for chunk in self.stream(
  File "D:\app_install_path\miniconda3\envs\311_main\Lib\site-packages\langgraph\pregel\__init__.py", line 993, in stream
    _panic_or_proceed(all_futures, loop.step)
  File "D:\app_install_path\miniconda3\envs\311_main\Lib\site-packages\langgraph\pregel\__init__.py", line 1423, in _panic_or_proceed
    raise exc
  File "D:\app_install_path\miniconda3\envs\311_main\Lib\site-packages\langgraph\pregel\executor.py", line 60, in done
    task.result()
  File "D:\app_install_path\miniconda3\envs\311_main\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "D:\app_install_path\miniconda3\envs\311_main\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "D:\app_install_path\miniconda3\envs\311_main\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\app_install_path\miniconda3\envs\311_main\Lib\site-packages\langgraph\pregel\retry.py", line 26, in run_with_retry
    task.proc.invoke(task.input, task.config)
  File "D:\app_install_path\miniconda3\envs\311_main\Lib\site-packages\langchain_core\runnables\base.py", line 2876, in invoke
    input = context.run(step.invoke, input, config, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\app_install_path\miniconda3\envs\311_main\Lib\site-packages\langchain_core\runnables\base.py", line 4475, in invoke
    return self._call_with_config(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\app_install_path\miniconda3\envs\311_main\Lib\site-packages\langchain_core\runnables\base.py", line 1785, in _call_with_config
    context.run(
  File "D:\app_install_path\miniconda3\envs\311_main\Lib\site-packages\langchain_core\runnables\config.py", line 397, in call_func_with_variable_args
    return func(input, **kwargs)  # type: ignore[call-arg]
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\app_install_path\miniconda3\envs\311_main\Lib\site-packages\langchain_core\runnables\base.py", line 4331, in _invoke
    output = call_func_with_variable_args(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\app_install_path\miniconda3\envs\311_main\Lib\site-packages\langchain_core\runnables\config.py", line 397, in call_func_with_variable_args
    return func(input, **kwargs)  # type: ignore[call-arg]
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\app_install_path\miniconda3\envs\311_main\Lib\site-packages\langgraph\prebuilt\chat_agent_executor.py", line 445, in call_model
    response = model_runnable.invoke(state, config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\app_install_path\miniconda3\envs\311_main\Lib\site-packages\langchain_core\runnables\base.py", line 2878, in invoke
    input = context.run(step.invoke, input, config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\app_install_path\miniconda3\envs\311_main\Lib\site-packages\langchain_core\runnables\base.py", line 5094, in invoke
    return self.bound.invoke(
           ^^^^^^^^^^^^^^^^^^
  File "D:\app_install_path\miniconda3\envs\311_main\Lib\site-packages\langchain_core\language_models\chat_models.py", line 276, in invoke
    self.generate_prompt(
  File "D:\app_install_path\miniconda3\envs\311_main\Lib\site-packages\langchain_core\language_models\chat_models.py", line 776, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\app_install_path\miniconda3\envs\311_main\Lib\site-packages\langchain_core\language_models\chat_models.py", line 633, in generate
    raise e
  File "D:\app_install_path\miniconda3\envs\311_main\Lib\site-packages\langchain_core\language_models\chat_models.py", line 623, in generate
    self._generate_with_cache(
  File "D:\app_install_path\miniconda3\envs\311_main\Lib\site-packages\langchain_core\language_models\chat_models.py", line 845, in _generate_with_cache
    result = self._generate(
             ^^^^^^^^^^^^^^^
  File "D:\app_install_path\miniconda3\envs\311_main\Lib\site-packages\langchain_openai\chat_models\base.py", line 635, in _generate
    response = self.client.create(**payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\app_install_path\miniconda3\envs\311_main\Lib\site-packages\openai\_utils\_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\app_install_path\miniconda3\envs\311_main\Lib\site-packages\openai\resources\chat\completions.py", line 668, in create
    return self._post(
           ^^^^^^^^^^^
  File "D:\app_install_path\miniconda3\envs\311_main\Lib\site-packages\openai\_base_client.py", line 1259, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))      
or_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "We could not parse the JSON body of your request. The content of 'assistant' should be a string type.", 'type': 'invalid_request_error', 'code': 'invalid_param', 'param': None}}

### Description

Hello,
I encountered a problem while using the Langchain library. When defining a tool and invoking it, I received the following error:
```bash
openai.BadRequestError: Error code: 400 - {'error': {'message': "We could not parse the JSON body of your request. The content of 'assistant' should be a string type.", 'type': 'invalid_request_error', 'code': 'invalid_param', 'param': None}}
```
I have correctly defined the tool (GenerateRandomFloats) according to the documentation, ensuring that I specified response_format="content_and_artifact". However, it seems that the JSON body of the request cannot be parsed correctly when calling the tool.
(I suspect this issue might be related to the API hosting site, but I'm not certain. )

### System Info

langchain                     0.2.14
langchain-community           0.2.12
langchain-core                0.2.34
langchain-openai              0.1.22
langchain-text-splitters      0.2.2
langgraph                     0.2.12
langgraph-checkpoint          1.0.5
langsmith                     0.1.104

System Information
------------------
> OS:  Windows
> OS Version:  10.0.26120
> Python Version:  3.11.9 | packaged by Anaconda, Inc. | (main, Apr 19 2024, 16:40:41) [MSC v.1916 64 bit (AMD64)]

Package Information
-------------------
> langchain_core: 0.2.34
> langchain: 0.2.14
> langchain_community: 0.2.12
> langsmith: 0.1.104
> langchain_openai: 0.1.22
> langchain_text_splitters: 0.2.2
> langchain_tools: Installed. No version info available.
> langgraph: 0.2.12

Optional packages not installed
-------------------------------
> langserve

Other Dependencies
------------------
> aiohttp: 3.9.5
> async-timeout: Installed. No version info available.
> dataclasses-json: 0.6.7
> httpx: 0.27.0
> jsonpatch: 1.33
> langgraph-checkpoint: 1.0.5
> numpy: 1.24.4
> openai: 1.40.6
> orjson: 3.10.5
> packaging: 23.2
> pydantic: 1.10.17
> PyYAML: 6.0.1
> requests: 2.31.0
> SQLAlchemy: 2.0.31
> tenacity: 8.4.2
> tiktoken: 0.7.0
> typing-extensions: 4.12.2

**Comment by NowLoadY** [comment]
Hi 1sopropanol,

I noticed the download link you provided, but my system is warning me about potential risks associated with the file. Could you please provide more information about the 'gcc' selection in the installer menu and how it relates to the fix? I'd appreciate any clarification to ensure the safety and compatibility of the download.
![image](https://github.com/user-attachments/assets/c621e41b-189f-4ca9-8a8a-a112a3dcadc4)

**Comment by keenborder786** [comment]
Yes this is due this due to the hosting site. I tried without `https://api.deepbricks.ai/v1/` and it works like a charm.

**Comment by NowLoadY** [comment]
> Yes this is due this due to the hosting site. I tried without `https://api.deepbricks.ai/v1/` and it works like a charm.

Thanks so much! I didn't have a chance to change the host site. That's why I'm not so sure 😃
