### ISSUE TITLE
Strict mode not compatible with Azure OpenAI GPT-4o 2024-05-13 function calling when binding to pydantic model

### ISSUE THREAD

**Issue by sebastiantimwagner** [langchain-ai/langchain#25842]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

prompt_template = ChatPromptTemplate.from_messages(
            [
                ("system", SYSTEM_PROMPT),
                ("human", ANERKANNT_PROMPT)
            ]
        )

        class GerichtlicheAnerkennung(BaseModel):
            betriebskosten_posten: list = Field(description="Bezeichnung der BKA Position als Liste in derselben Reihenfolge wie die anderen Attribute.")
            gerichtlich_anerkannt: list = Field(description="Gerichtlichen Anerkennung (Ja/Nein/Unbekannt) der Positionen in der Abrechnung als Liste in der gleichen Reihenfolge wie die Poisitionen.")
            begruendung: list = Field(description="Erlaeuternden Begruendung worauf das Ergebnis `gerichtlich_anerkannt` basiert als Liste in der gleichen Reihenfolge wie die Positionen. "
                                                " Bitte nenne die Bezeichnung des Posten explizit in der Begruendung.")

        llm = get_model(model)
        dataextract_function = [
            convert_pydantic_to_openai_function(GerichtlicheAnerkennung)
        ]
        dataextract_model = llm.bind(
            functions=dataextract_function,
            function_call={"name": "GerichtlicheAnerkennung"}
        )
        chain = prompt_template | dataextract_model
        gerichtlich_anerkannt = chain.invoke(
            {"betriebskosten_posten": [pos.bezeichnung for pos in self.bka_positionen]},
             config={"callbacks":[LANGFUSE_HANDLER]})

### Error Message and Stack Trace (if applicable)

2024-08-29 12:32:10.274 Uncaught app exception
Traceback (most recent call last):
  File "/home/sebastian/leegle/betriebskosten-checker/venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "/home/sebastian/leegle/betriebskosten-checker/pages/3_ 3️⃣_BK Abrechnung prüfen.py", line 389, in <module>
    analyze_betriebskostenabrechnung(placeholders)
  File "/home/sebastian/leegle/betriebskosten-checker/pages/3_ 3️⃣_BK Abrechnung prüfen.py", line 284, in analyze_betriebskostenabrechnung
    st.session_state.nka_pruefung.bka_pruefung.ergebnis.materielle_pruefung.run_pruefung_gerichtliche_anerkennung(model=selected_model_6_2)
  File "/home/sebastian/leegle/betriebskosten-checker/venv/lib/python3.10/site-packages/langfuse/decorators/langfuse_decorator.py", line 219, in sync_wrapper
    self._handle_exception(observation, e)
  File "/home/sebastian/leegle/betriebskosten-checker/venv/lib/python3.10/site-packages/langfuse/decorators/langfuse_decorator.py", line 422, in _handle_exception
    raise e
  File "/home/sebastian/leegle/betriebskosten-checker/venv/lib/python3.10/site-packages/langfuse/decorators/langfuse_decorator.py", line 217, in sync_wrapper
    result = func(*args, **kwargs)
  File "/home/sebastian/leegle/betriebskosten-checker/models/pruefung.py", line 1465, in run_pruefung_gerichtliche_anerkennung
    gerichtlich_anerkannt = chain.invoke(
  File "/home/sebastian/leegle/betriebskosten-checker/venv/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2878, in invoke
    input = context.run(step.invoke, input, config)
  File "/home/sebastian/leegle/betriebskosten-checker/venv/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 5092, in invoke
    return self.bound.invoke(
  File "/home/sebastian/leegle/betriebskosten-checker/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 277, in invoke
    self.generate_prompt(
  File "/home/sebastian/leegle/betriebskosten-checker/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 777, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
  File "/home/sebastian/leegle/betriebskosten-checker/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 634, in generate
    raise e
  File "/home/sebastian/leegle/betriebskosten-checker/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 624, in generate
    self._generate_with_cache(
  File "/home/sebastian/leegle/betriebskosten-checker/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 846, in _generate_with_cache
    result = self._generate(
  File "/home/sebastian/leegle/betriebskosten-checker/venv/lib/python3.10/site-packages/langchain_openai/chat_models/base.py", line 658, in _generate
    response = self.client.create(**payload)
  File "/home/sebastian/leegle/betriebskosten-checker/venv/lib/python3.10/site-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
  File "/home/sebastian/leegle/betriebskosten-checker/venv/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 668, in create
    return self._post(
  File "/home/sebastian/leegle/betriebskosten-checker/venv/lib/python3.10/site-packages/openai/_base_client.py", line 1259, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/sebastian/leegle/betriebskosten-checker/venv/lib/python3.10/site-packages/openai/_base_client.py", line 936, in request
    return self._request(
  File "/home/sebastian/leegle/betriebskosten-checker/venv/lib/python3.10/site-packages/openai/_base_client.py", line 1040, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "Invalid function definition for 'GerichtlicheAnerkennung': the 'strict' parameter is only permitted in 'tools'.", 'type': 'invalid_request_error', 'param': 'functions[0].strict', 'code': 'invalid_function_parameters'}}
received error response: {'message': 'Invalid request data', 'errors': ['Expected object, received string']}
received error response: {'message': 'Invalid request data', 'errors': ['Expected object, received string']}
received error response: {'message': 'Invalid request data', 'errors': ['Expected object, received string']}
Giving up execute_task_with_backoff(...) after 3 tries (langfuse.request.APIError: {'message': 'Invalid request data', 'errors': ['Expected object, received string']} (400): None)
Giving up execute_task_with_backoff(...) after 3 tries (langfuse.request.APIError: {'message': 'Invalid request data', 'errors': ['Expected object, received string']} (400): None)
Giving up execute_task_with_backoff(...) after 3 tries (langfuse.request.APIError: {'message': 'Invalid request data', 'errors': ['Expected object, received string']} (400): None)
Giving up execute_task_with_backoff(...) after 3 tries (langfuse.request.APIError: {'message': 'Invalid request data', 'errors': ['Expected object, received string']} (400): None)
error uploading: {'message': 'Invalid request data', 'errors': ['Expected object, received string']} (400): None
Traceback (most recent call last):
  File "/home/sebastian/leegle/betriebskosten-checker/venv/lib/python3.10/site-packages/langfuse/task_manager.py", line 160, in upload
    self._upload_batch(batch)
  File "/home/sebastian/leegle/betriebskosten-checker/venv/lib/python3.10/site-packages/langfuse/task_manager.py", line 187, in _upload_batch
    execute_task_with_backoff(batch)
  File "/home/sebastian/leegle/betriebskosten-checker/venv/lib/python3.10/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/home/sebastian/leegle/betriebskosten-checker/venv/lib/python3.10/site-packages/langfuse/task_manager.py", line 185, in execute_task_with_backoff
    return self._client.batch_post(batch=batch, metadata=metadata)
  File "/home/sebastian/leegle/betriebskosten-checker/venv/lib/python3.10/site-packages/langfuse/request.py", line 56, in batch_post
    return self._process_response(
  File "/home/sebastian/leegle/betriebskosten-checker/venv/lib/python3.10/site-packages/langfuse/request.py", line 120, in _process_response
    raise APIError(res.status_code, payload)
langfuse.request.APIError: {'message': 'Invalid request data', 'errors': ['Expected object, received string']} (400): None

### Description

* I'm trying to use the strict mode with function calling to receive structured JSON Output from the LLM

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #41~22.04.1tux1 SMP PREEMPT_DYNAMIC Wed Aug 21 22:16:53 UTC 2024
> Python Version:  3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]

Package Information
-------------------
> langchain_core: 0.2.36
> langchain: 0.2.15
> langsmith: 0.1.93
> langchain_google_genai: 1.0.8
> langchain_google_vertexai: 1.0.7
> langchain_openai: 0.1.23
> langchain_text_splitters: 0.2.2

Optional packages not installed
-------------------------------
> langgraph
> langserve

Other Dependencies
------------------
> aiohttp: 3.9.5
> anthropic[vertexai]: Installed. No version info available.
> async-timeout: 4.0.3
> google-cloud-aiplatform: 1.59.0
> google-cloud-storage: 2.18.0
> google-generativeai: 0.7.2
> jsonpatch: 1.33
> numpy: 1.26.4
> openai: 1.40.2
> orjson: 3.10.6
> packaging: 23.2
> pillow: 10.4.0
> pydantic: 2.8.2
> PyYAML: 6.0.1
> requests: 2.32.3
> SQLAlchemy: 2.0.31
> tenacity: 8.5.0
> tiktoken: 0.7.0
> typing-extensions: 4.12.2

**Comment by arne-rustad** [comment]
Any updates on this yet? Seems like a pretty huge limitation given the number of businesses using the Azure OpenAI API (especially businesses in Europe)
