### ISSUE TITLE
FAISS similarity_search not work

### ISSUE THREAD

**Issue by fengjial** [langchain-ai/langchain#2587]
hi, i am trying use FAISS to do similarity_search, but it failed with errs:
>>> db.similarity_search("123")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/langchain/vectorstores/faiss.py", line 207, in similarity_search
    docs_and_scores = self.similarity_search_with_score(query, k)
  File "/usr/local/lib/python3.10/site-packages/langchain/vectorstores/faiss.py", line 176, in similarity_search_with_score
    embedding = self.embedding_function(query)
  File "/usr/local/lib/python3.10/site-packages/langchain/embeddings/openai.py", line 279, in embed_query
    embedding = self._embedding_func(text, engine=self.query_model_name)
  File "/usr/local/lib/python3.10/site-packages/langchain/embeddings/openai.py", line 235, in _embedding_func
    return self._get_len_safe_embeddings([text], engine=engine)[0]
  File "/usr/local/lib/python3.10/site-packages/langchain/embeddings/openai.py", line 193, in _get_len_safe_embeddings
    encoding = tiktoken.model.encoding_for_model(self.document_model_name)
AttributeError: module 'tiktoken' has no attribute 'model'

anyone can give me some advise?

**Comment by dxv2k** [comment]
Probably you should reinstall tiktoken

**Comment by sunwooz** [comment]
> Probably you should reinstall tiktoken

Thanks, this worked! Upgrading and downgrading didn't seem to help.
