### ISSUE TITLE
Error when extracting images with PyMuPDFLoader and PyPDFLoader

### ISSUE THREAD

**Issue by BennisonDevadoss** [langchain-ai/langchain#26225]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

1. Use the following code to load a PDF with image extraction enabled with PyMuPDFLoader:

```python
########################################
# PyMuPDFLoader
########################################
loader = PyMuPDFLoader("google-2024-environmental-report.pdf", extract_images=True)
pages = loader.load()

for page in pages:
    print(page.page_content)
```

2. Download the PDF located at: [Google 2024 Environmental Report](https://www.gstatic.com/gumdrop/sustainability/google-2024-environmental-report.pdf).
3. Additionally, I also tried using PyPDFLoader with the same PDF, and I encountered the same issue.

### Error Message and Stack Trace (if applicable)

```
Traceback (most recent call last):
  File "/mnt/c/Users/BennisonJ/Yavar/projects/zypher-2.0/backend/apps/rag/main.py", line 811, in store_doc
    data = loader.load()
           ^^^^^^^^^^^^^
  File "/home/bennison/miniconda3/envs/open-webui/lib/python3.11/site-packages/langchain_community/document_loaders/pdf.py", line 387, in load
    return list(self._lazy_load(**kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bennison/miniconda3/envs/open-webui/lib/python3.11/site-packages/langchain_community/document_loaders/pdf.py", line 384, in _lazy_load
    yield from parser.lazy_parse(blob)
  File "/home/bennison/miniconda3/envs/open-webui/lib/python3.11/site-packages/langchain_community/document_loaders/parsers/pdf.py", line 244, in lazy_parse
    yield from [
               ^
  File "/home/bennison/miniconda3/envs/open-webui/lib/python3.11/site-packages/langchain_community/document_loaders/parsers/pdf.py", line 247, in <listcomp>
    + self._extract_images_from_page(doc, page),
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bennison/miniconda3/envs/open-webui/lib/python3.11/site-packages/langchain_community/document_loaders/parsers/pdf.py", line 283, in _extract_images_from_page
    return extract_from_images_with_rapidocr(imgs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bennison/miniconda3/envs/open-webui/lib/python3.11/site-packages/langchain_community/document_loaders/parsers/pdf.py", line 74, in extract_from_images_with_rapidocr
    result, _ = ocr(img)
                ^^^^^^^^
  File "/home/bennison/miniconda3/envs/open-webui/lib/python3.11/site-packages/rapidocr_onnxruntime/rapid_ocr_api.py", line 80, in __call__
    dt_boxes, det_elapse = self.text_detector(img)
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bennison/miniconda3/envs/open-webui/lib/python3.11/site-packages/rapidocr_onnxruntime/ch_ppocr_v3_det/text_detect.py", line 66, in __call__
    data = transform(data, self.preprocess_op)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bennison/miniconda3/envs/open-webui/lib/python3.11/site-packages/rapidocr_onnxruntime/ch_ppocr_v3_det/utils.py", line 220, in transform
    data = op(data)
           ^^^^^^^^
  File "/home/bennison/miniconda3/envs/open-webui/lib/python3.11/site-packages/rapidocr_onnxruntime/ch_ppocr_v3_det/utils.py", line 75, in __call__
    data['image'] = (img * self.scale - self.mean) / self.std
                     ~~~~~~~~~~~~~~~~~^~~~~~~~~~~
ValueError: operands could not be broadcast together with shapes (896,800) (1,1,3)
```

### Description

I am encountering a ValueError when using both PyMuPDFLoader and PyPDFLoader to extract images from certain PDFs. The error message indicates that operands could not be broadcast together with shapes (896,800) (1,1,3). This occurs specifically when the extract_images parameter is set to True.

**Expected Behavior**
The code should successfully extract text and images from the PDF without errors.

**Additional Information**
This issue seems to occur with specific PDFs that may have unique formatting or image properties. I would appreciate any guidance on how to resolve this issue or if there are any workarounds available. 

### System Info

```
langchain==0.1.16
langchain-chroma==0.1.0
langchain-community==0.0.34
langchain-core==0.1.52
langchain-text-splitters==0.0.2

PyMuPDF Version: 1.24.10
PyPDF Version: 4.2.0
Operating System: Ubuntu 22 LTS
```

**Comment by venkatram-dev** [comment]
Looks like you might be using a old version of rapidocr_onnxruntime.
Please upgrade to latest or  1.3.24.

I did not get the error using this version.

pip show rapidocr_onnxruntime
Name: rapidocr-onnxruntime
Version: 1.3.24




https://github.com/RapidAI/RapidOCR/blob/50ce26671ab4a78955f8bc773348f82ad9fe0024/python/rapidocr_onnxruntime/ch_ppocr_v3_det/utils.py#L44](https://github.com/RapidAI/RapidOCR/commit/1de4db02497f832536ed1578e9bce5195850db8f)

**Comment by kartheekyakkala** [comment]
I think rapidocr-onnxruntime is a required package for extracting information from images. Can you please provide the versions of the rapidocr-onnxruntime?.

I have used all the latest versions of the packages. It worked fine.

**Comment by BennisonDevadoss** [comment]
@kartheekyakkala, Thank you for addressing the issue!

After upgrading to the latest versions of the packages, the solution now works correctly for most scanned documents, which is a significant improvement.

However, I encountered a new issue when testing with the following PDF:

[Scan Sample PDF](https://solutions.weblite.ca/pdfocrx/scansmpl.pdf)

Unfortunately, the updated solution does not work for this particular PDF. The problem persists in a similar manner, where the image extraction and processing fail.

**Details**
1. RapidOCR ONNXRuntime Version: 1.3.24
2. Python Version: 3.11

Here I have attached the screenshot of the error
![image](https://github.com/user-attachments/assets/9d0d21ea-d838-4701-89a2-cb40e2fb2cbf)

**Comment by venkatram-dev** [comment]
@BennisonDevadoss ,
This new error is coming from langchain-community package.
Looks like you are using a older version of it.

Please upgrade to latest version of langchain-community. Using the latest version worked for above file without any errors.

You might also want to update all the other langchain packages also to latest.

**Comment by BennisonDevadoss** [comment]
@venkatram-dev, I updated the plugin versions to the latest, but I'm still encountering the same issue. 

Below are my updated package versions:
```requirements.txt
langchain-community: 0.2.16
langchain-core:  0.2.38
langchain :0.2.16
```

**Comment by BennisonDevadoss** [comment]
@venkatram-dev , as I mentioned earlier, I'm still encountering the issue we discussed previously, even with the latest version of the LangChain modules. I've shared the reproducible code on Google Colab, which you can access via the link below: [Colab Link](https://colab.research.google.com/drive/12NMHOT6aYQVRQBsiJegCpdwtCUtIjttq?usp=drive_link)

Additionally, here's the PDF link I used to read the text from: [PDF link](https://solutions.weblite.ca/pdfocrx/scansmpl.pdf)

Please let me know if you find any breakthroughs!

**Comment by jamesrooti** [comment]
Is there progress on this? Experiencing the same issue. Thanks

**Comment by BennisonDevadoss** [comment]
@jamesrooti, Yes I am having same issue.

**Comment by BennisonDevadoss** [comment]
Yes, this issue still exists.

**Comment by skyking363** [comment]
Me too

**Comment by john01kpeazu** [comment]
Same here. Not able to extract OCR information from PDFs using PyMuPDFLoader or PyPDFLoader.

**Comment by eugeneo17** [comment]
I'd like to take this issue and submit a fix. Let me know if anyone is already working on it!

**Comment by mdrxy** [comment]
@eugeneo17 you got it
