### ISSUE TITLE
Exception when trying to pull Google GenAI prompt

### ISSUE THREAD

**Issue by FedericoOmoto** [langchain-ai/langchain#26554]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from langchain import hub as prompts
prompts.pull("prompt_name", include_model=True)
```

### Error Message and Stack Trace (if applicable)

  File "/home/federicoomoto/src/fairway/pr/fairway-fastapi/app/firebase/prompts.py", line 14, in get_prompt
    prompt = prompts.pull(
             ^^^^^^^^^^^^^
  File "/home/federicoomoto/.cache/pypoetry/virtualenvs/fairway-fastapi-VcPivsSZ-py3.12/lib/python3.12/site-packages/langchain/hub.py", line 114, in pull
    response = client.pull_prompt(owner_repo_commit, include_model=include_model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/federicoomoto/.cache/pypoetry/virtualenvs/fairway-fastapi-VcPivsSZ-py3.12/lib/python3.12/site-packages/langsmith/client.py", line 5301, in pull_prompt
    prompt = loads(json.dumps(prompt_object.manifest))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/federicoomoto/.cache/pypoetry/virtualenvs/fairway-fastapi-VcPivsSZ-py3.12/lib/python3.12/site-packages/langchain_core/_api/beta_decorator.py", line 110, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/federicoomoto/.cache/pypoetry/virtualenvs/fairway-fastapi-VcPivsSZ-py3.12/lib/python3.12/site-packages/langchain_core/load/load.py", line 181, in loads
    return json.loads(
           ^^^^^^^^^^^
  File "/usr/lib64/python3.12/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/federicoomoto/.cache/pypoetry/virtualenvs/fairway-fastapi-VcPivsSZ-py3.12/lib/python3.12/site-packages/langchain_core/load/load.py", line 119, in __call__
    raise ValueError(
ValueError: Trying to deserialize something that cannot be deserialized in current version of langchain-core: ('langchain', 'chat_models', 'google_genai', 'ChatGoogleGenerativeAI')

### Description

When trying to pull a Google GenAI prompt from LangSmith, including the model, I get the following exception:

ValueError: Trying to deserialize something that cannot be deserialized in current version of langchain-core: ('langchain', 'chat_models', 'google_genai', 'ChatGoogleGenerativeAI')

If I try to pull the prompt without the model, everything works as expected.

The model config is as follows:

![image](https://github.com/user-attachments/assets/282baf32-9766-4484-b9a8-24a016e30de7)

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #1 SMP PREEMPT_DYNAMIC Sun Aug 11 15:32:50 UTC 2024
> Python Version:  3.12.4 (main, Jun  7 2024, 00:00:00) [GCC 14.1.1 20240607 (Red Hat 14.1.1-5)]

Package Information
-------------------
> langchain_core: 0.3.0
> langchain: 0.3.0
> langsmith: 0.1.121
> langchain_google_genai: 2.0.0
> langchain_openai: 0.2.0
> langchain_text_splitters: 0.3.0

Optional packages not installed
-------------------------------
> langgraph
> langserve

Other Dependencies
------------------
> aiohttp: 3.10.5
> async-timeout: Installed. No version info available.
> google-generativeai: 0.7.2
> httpx: 0.27.2
> jsonpatch: 1.33
> numpy: 1.26.4
> openai: 1.45.1
> orjson: 3.10.7
> packaging: 24.1
> pillow: 10.4.0
> pydantic: 2.9.1
> PyYAML: 6.0.2
> requests: 2.32.3
> SQLAlchemy: 2.0.34
> tenacity: 8.5.0
> tiktoken: 0.7.0
> typing-extensions: 4.12.2

**Comment by mfernandezsidn** [comment]
Same with VertexAI help

**Comment by arinaazmi** [comment]
Hi! My name is Arina, I'm working with a team at UTSC as part of a group project to contribute to LangChain. We're interested in working on this issue, and were hoping to take a crack at it. Is there any additional information that can be provided to help us tackle this?

**Comment by FedeOmoto** [comment]
Hi Arina!
Thank you for taking care of this issue, if there is any additional information that will help you and your team to work on fixing this issue, please don't hesitate to let me know.

**Comment by FedeOmoto** [comment]
As an update, from the time I created the GH issue, we're actually using the latest dependency versions:
- langchain: 0.3.4
- lanchain-core: 0.3.12
- langchain-google-genai: 2.0.1
- langsmith: 0.1.136

**Comment by arinaazmi** [comment]
Hi @FedeOmoto!
We were able to successfully pull the prompt from LangSmith, but we ran into a different issue during invocation:
`Error during invocation: Invalid input type <class 'langchain_core.messages.ai.AIMessage'>. Must be a PromptValue, str, or list of BaseMessages.
Full Traceback:
Traceback (most recent call last):
  File "/Users/Arina/GitHub/langchain/test.py", line 55, in <module>
    response = chain.invoke(input_message)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Arina/anaconda3/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 3024, in invoke
    input = context.run(step.invoke, input, config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Arina/anaconda3/lib/python3.11/site-packages/langchain_core/language_models/llms.py", line 391, in invoke
    [self._convert_input(input)],
     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Arina/anaconda3/lib/python3.11/site-packages/langchain_core/language_models/llms.py", line 341, in _convert_input
    raise ValueError(msg)
ValueError: Invalid input type <class 'langchain_core.messages.ai.AIMessage'>. Must be a PromptValue, str, or list of BaseMessages.
`
We were wondering if your original issue still persists or if any recent updates have resolved it on your end. In the meantime, we will be investigating the "Invalid input type" issue further to find a solution.

Looking forward to your input!

**Comment by FarhanChowdhury248** [comment]
@FedeOmoto I am working with @arinaazmi on this issue. I was able to successfully execute the example code using the following dependency versions:
```
langchain: 0.3.5
langchain-core: 0.3.13
langchain-google-genai: 2.0.3
langchain-openai: 0.2.4
langchain-text-splitters: 0.3.1
langsmith: 0.1.137
```
The output I receive is:
```
first=ChatPromptTemplate(input_variables=['question'], input_types={}, partial_variables={}, metadata={'lc_hub_owner': '-', 'lc_hub_repo': 'test-prompt', 'lc_hub_commit_hash': 'b59240cedfb86d67cd43e3dc971ade092126e025ad7ec844bdb95d5d6ec7b960'}, messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You are a chatbot.'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['question'], input_types={}, partial_variables={}, template='{question} Is your name Arina?'), additional_kwargs={})]) middle=[] last=RunnableBinding(bound=ChatGoogleGenerativeAI(model='models/gemini-1.5-pro', google_api_key=SecretStr('**********'), temperature=0.0, top_p=1.0, client=<google.ai.generativelanguage_v1beta.services.generative_service.client.GenerativeServiceClient object at 0x7f45f105a310>, default_metadata=()), kwargs={}, config={}, config_factories=[])
```
Is it possible for you to upgrade and try with the aforementioned dependency versions?

**Comment by glenrs** [comment]
Those versions hang for google models. 

I've also updated to lastest packages. Any prompt template with google model hangs when specifying `include_model`.

```{python}
from langchain import hub as prompts
prompts.pull("temp", include_model=True)
```

```
aiohappyeyeballs==2.4.4
aiohttp==3.11.11
aiosignal==1.3.2
annotated-types==0.7.0
anthropic==0.45.2
anyio==4.8.0
attrs==24.3.0
blinker==1.9.0
CacheControl==0.14.2
cachetools==5.5.0
certifi==2024.12.14
cffi==1.17.1
charset-normalizer==3.4.1
click==8.1.8
cloudevents==1.9.0
coverage==7.6.10
cryptography==44.0.0
dataclasses-json==0.6.7
defusedxml==0.7.1
deprecation==2.1.0
distro==1.9.0
elephant-ai-functions @ file:///Users/rexsumsion/Documents/proj/elephant-ai/functions_py
factory_boy==3.3.1
Faker==33.3.1
filetype==1.2.0
firebase-admin==6.6.0
firebase-functions==0.4.2
Flask==3.1.0
Flask-Cors==5.0.0
freezegun==1.5.1
frozenlist==1.5.0
functions-framework==3.8.2
google-ai-generativelanguage==0.6.15
google-api-core==2.24.0
google-api-python-client==2.158.0
google-auth==2.37.0
google-auth-httplib2==0.2.0
google-cloud-core==2.4.1
google-cloud-firestore==2.19.0
google-cloud-storage==2.19.0
google-crc32c==1.6.0
google-events==0.14.0
google-generativeai==0.8.4
google-resumable-media==2.7.2
googleapis-common-protos==1.66.0
grpcio==1.69.0
grpcio-status==1.69.0
gunicorn==23.0.0
h11==0.14.0
httpcore==1.0.7
httplib2==0.22.0
httpx==0.28.1
httpx-sse==0.4.0
idna==3.10
inflection==0.5.1
iniconfig==2.0.0
itsdangerous==2.2.0
Jinja2==3.1.5
jiter==0.8.2
jsonpatch==1.33
jsonpointer==3.0.0
langchain==0.3.17
langchain-anthropic==0.3.7
langchain-community==0.3.16
langchain-core==0.3.34
langchain-google-genai==2.0.9
langchain-openai==0.3.4
langchain-text-splitters==0.3.6
langgraph==0.2.69
langgraph-checkpoint==2.0.10
langgraph-sdk==0.1.51
langsmith==0.3.6
MarkupSafe==3.0.2
marshmallow==3.25.1
msgpack==1.1.0
multidict==6.1.0
mypy-extensions==1.0.0
numpy==2.2.2
openai==1.61.1
orjson==3.10.14
packaging==24.2
pluggy==1.5.0
propcache==0.2.1
proto-plus==1.25.0
protobuf==5.29.3
pyasn1==0.6.1
pyasn1_modules==0.4.1
pycparser==2.22
pydantic==2.10.5
pydantic-settings==2.7.1
pydantic_core==2.27.2
PyJWT==2.10.1
pyparsing==3.2.1
pytest==8.0.0
pytest-cov==4.1.0
pytest-factoryboy==2.7.0
pytest-mock==3.12.0
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
PyYAML==6.0.2
regex==2024.11.6
requests==2.32.3
requests-toolbelt==1.0.0
rsa==4.9
six==1.17.0
sniffio==1.3.1
SQLAlchemy==2.0.37
tenacity==9.0.0
tiktoken==0.8.0
tqdm==4.67.1
typing-inspect==0.9.0
typing_extensions==4.12.2
uritemplate==4.1.1
urllib3==2.3.0
watchdog==6.0.0
Werkzeug==3.1.3
yarl==1.18.3
zstandard==0.23.0
```
