### ISSUE TITLE
OpenAI Base Chat Model fails in combining llm output as llm_output for token_usage has nested dictionaries

### ISSUE THREAD

**Issue by dubbl-d** [langchain-ai/langchain#26606]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

'''python

        from langchain.chains import MapReduceDocumentsChain, ReduceDocumentsChain

        topic_summary_parser = PydanticOutputParser(pydantic_object=TopicSummary)
        topic_summary_list_parser = PydanticOutputParser(pydantic_object=TopicSummaries)
        transcript_summary_parser = PydanticOutputParser(pydantic_object=TranscriptFullSummary)
        # TODO: Convert this chain so it is expressed as LCEL
        map_prompt = PromptTemplate(template=topic_summary_map_prompt,
                                    input_variables=["transcript"],
                                    partial_variables={
                                        "format_instructions": topic_summary_parser.get_format_instructions()})
        map_chain = LLMChain(llm=self.llm, prompt=map_prompt)

        reduce_prompt = PromptTemplate.from_template(template=topic_summary_reduce_prompt,
                                                     partial_variables={
                                                         "format_instructions": transcript_summary_parser.get_format_instructions()})
        reduce_chain = LLMChain(llm=self.llm, prompt=reduce_prompt, verbose=True)

        combine_documents_chain = StuffDocumentsChain(llm_chain=reduce_chain, document_variable_name="topic_summaries")

        reduce_documents_chain = ReduceDocumentsChain(combine_documents_chain=combine_documents_chain,
                                                      collapse_documents_chain=combine_documents_chain,
                                                      token_max=4000, verbose=True
                                                      )

        map_reduce_chain = MapReduceDocumentsChain(llm_chain=map_chain,
                                                   reduce_documents_chain=reduce_documents_chain,
                                                   document_variable_name="transcript",
                                                   return_intermediate_steps=True,
                                                   verbose=True
                                                   )

        text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=3000,
            chunk_overlap=0,
            length_function=len,
            is_separator_regex=False,
        )

        transcript_splits = text_splitter.create_documents([transcript.stringify()])

        topic_summary = map_reduce_chain.invoke(transcript_splits)

'''

### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/langsmith/run_helpers.py", line 449, in wrapper
    function_result = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/app/sellect/llm/llm_inferences.py", line 129, in infer_transcript_topic_summary
    topic_summary = map_reduce_chain.invoke(transcript_splits)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain/chains/base.py", line 162, in invoke
    raise e
  File "/usr/local/lib/python3.11/site-packages/langchain/chains/base.py", line 156, in invoke
    self._call(inputs, run_manager=run_manager)
  File "/usr/local/lib/python3.11/site-packages/langchain/chains/combine_documents/base.py", line 136, in _call
    output, extra_return_dict = self.combine_docs(
                                ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain/chains/combine_documents/map_reduce.py", line 225, in combine_docs
    map_results = self.llm_chain.apply(
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain/chains/llm.py", line 227, in apply
    raise e
  File "/usr/local/lib/python3.11/site-packages/langchain/chains/llm.py", line 224, in apply
    response = self.generate(input_list, run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain/chains/llm.py", line 115, in generate
    return self.llm.generate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 544, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 413, in generate
    llm_output = self._combine_llm_outputs([res.llm_output for res in results])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain_openai/chat_models/base.py", line 374, in _combine_llm_outputs
    overall_token_usage[k] += v
TypeError: unsupported operand type(s) for +=: 'dict' and 'dict'

### Description

* This code worked until Friday, 9/13. I think this is because the expected output from OpenAI has changes. See below for full details *
* It breaks in .pyenv/versions/3.11.7/lib/python3.11/site-packages/langchain_openai/chat_models/base.py LINE: (LINE 371)
   in the `_combine_llm_outputs(...) method
* This is happening because the results of the MapReduceChain have multiple LLMResults each with a llm_output value set.
* It looks like the format of the expected `llm_output` coming back from OpenAI has a new, nested dictionary. This is the new output:

`{'model_name': 'gpt-4-turbo', 'system_fingerprint': 'fp_1f2231a495', 'token_usage': {'completion_tokens': 315, 'completion_tokens_details': {'reasoning_tokens': 0}, 'prompt_tokens': 1011, 'total_tokens': 1326}}`

NOTE the dict value for the key `completion_tokens_details`

I have coded up a fix that I can also put in a PR if you would like. I could also push this up into the LLMResult object itself if you prefer. I have to give this more thought. For now this fix is in the `langchain_openai/chat_models/base.py` library:

```python

    def _flatten_dict(self,  the_dict: dict, accumulator: dict):
        for k, v in the_dict.items():
            if isinstance(v, dict):
                self._flatten_dict(v, accumulator)
            else :
                accumulator[k] = v
        return accumulator
    
    def _combine_llm_outputs(self, llm_outputs: List[Optional[dict]]) -> dict:
        overall_token_usage: dict = {}
        system_fingerprint = None
        for output in llm_outputs:
            if output is None:
                # Happens in streaming
                continue
            accumulator = {}
            token_usage = self._flatten_dict(output["token_usage"], accumulator)
            if token_usage is not None:
                for k, v in token_usage.items():
                    if k in overall_token_usage:
                        overall_token_usage[k] += v
                    else:
                        overall_token_usage[k] = v
            if system_fingerprint is None:
                system_fingerprint = output.get("system_fingerprint")
        combined = {"token_usage": overall_token_usage, "model_name": self.model_name}
        if system_fingerprint:
            combined["system_fingerprint"] = system_fingerprint
        return combined
```

### System Info

$ python -m langchain_core.sys_info   

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.1.0: Mon Oct  9 21:32:11 PDT 2023; root:xnu-10002.41.9~7/RELEASE_ARM64_T6030
> Python Version:  3.11.7 (main, Jan 10 2024, 14:29:12) [Clang 15.0.0 (clang-1500.1.0.2.5)]

Package Information
-------------------
> langchain_core: 0.2.0
> langchain: 0.2.0
> langsmith: 0.1.17
> langchain_cli: 0.0.21
> langchain_openai: 0.0.6
> langchain_text_splitters: 0.0.2
> langchainhub: 0.1.14
> langserve: 0.0.41

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph

NOTE: I upgraded from v0.1 to v0.2 and both versions break the same way. This lead me to confirm that I think OpenAI has changed the format of the `llm_output` to contain this nested dictionary.

**Comment by efriis** [comment]
howdy! this is fixed in langchain-openai 0.1.25 or 0.2.0. Let me know if you're seeing this on either of those versions!

**Comment by efriis** [comment]
If you're in a jupyter notebook or repl, make sure to restart your kernel/repl!

**Comment by iammkullah** [comment]
that's the same issue I am facing right now as well, It was working all okay before but don't know what's wrong with this. 

here's the error:
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Work\bave_technologies\scraping at scale\resonance_github\ai-scraper\llm\utils\data_handler.py", line 131, in forLongContext
    else self.summary_generator.getTechnicalDescriptionChain(newDocs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Work\bave_technologies\scraping at scale\resonance_github\ai-scraper\llm\utils\summary_generator.py", line 217, in getTechnicalDescriptionChain
    return map_reduce_chain.run(docs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\pc planet\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain_core\_api\deprecation.py", line 168, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\pc planet\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain\chains\base.py", line 600, in run
    return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\pc planet\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain_core\_api\deprecation.py", line 168, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\pc planet\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain\chains\base.py", line 383, in __call__
    return self.invoke(
           ^^^^^^^^^^^^
  File "c:\Users\pc planet\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain\chains\base.py", line 166, in invoke
    raise e
  File "c:\Users\pc planet\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain\chains\base.py", line 156, in invoke
    self._call(inputs, run_manager=run_manager)
  File "c:\Users\pc planet\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain\chains\combine_documents\base.py", line 138, in _call
    output, extra_return_dict = self.combine_docs(
                                ^^^^^^^^^^^^^^^^^^
  File "c:\Users\pc planet\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain\chains\combine_documents\map_reduce.py", line 228, in combine_docs
    map_results = self.llm_chain.apply(
                  ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\pc planet\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain\chains\llm.py", line 252, in apply
    raise e
  File "c:\Users\pc planet\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain\chains\llm.py", line 249, in apply
    response = self.generate(input_list, run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\pc planet\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain\chains\llm.py", line 140, in generate
    return self.llm.generate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\pc planet\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain_core\language_models\chat_models.py", line 714, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\pc planet\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain_core\language_models\chat_models.py", line 576, in generate
    llm_output = self._combine_llm_outputs([res.llm_output for res in results])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\pc planet\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain_community\chat_models\openai.py", line 379, in _combine_llm_outputs
    overall_token_usage[k] += v
TypeError: unsupported operand type(s) for +=: 'dict' and 'dict'`

if we get any help, kindly let me know, 
thanks

**Comment by dubbl-d** [comment]
@efriis Right on. I was punting on the upgrade to deal with the Pydantic issue. Time to get it done. I have verified that langchain-openai v0.2.0 fixed it. Thank you for the prompt reply.

@iammkullah This upgrade does fix the issue. The fix I put up will work if you need a local hack for testing while you do the upgrade. It is pretty painless so I recommend just doing that.

**Comment by dubbl-d** [comment]
@efriis I am closing since I have verified this is fixed via the patch in the upgrade.

**Comment by iammkullah** [comment]
@dubbl-d thank you for the issue. yeah it works well after updating packages. thanks
