### ISSUE TITLE
Tool enabled model with ChatOllama not recognized as tool enabled

### ISSUE THREAD

**Issue by TimmyTimTim1337** [langchain-ai/langchain#26654]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

Minimal code for the error. Note that "llama3.1" is a manually downloaded model from HF (which may be the heart of the problem).

``` 
from typing import List

from langchain_core.tools import tool
from langchain_ollama import ChatOllama


@tool
def validate_user(user_id: int, addresses: List[str]) -> bool:
    """Validate user using historical addresses.

    Args:
        user_id (int): the user ID.
        addresses (List[str]): Previous addresses as a list of strings.
    """
    return True

llm = ChatOllama(
    model="llama3.1",
    temperature=0,
).bind_tools([validate_user])

result = llm.invoke(
    "Could you validate user 123? They previously lived at "
    "123 Fake St in Boston MA and 234 Pretend Boulevard in "
    "Houston TX."
)
result.tool_calls

```

### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "scratch.py", line 91, in <module>
    result = llm.invoke(
             ^^^^^^^^^^^
  File "Lib\site-packages\langchain_core\runnables\base.py", line 5313, in invoke
    return self.bound.invoke(
           ^^^^^^^^^^^^^^^^^^
  File "Lib\site-packages\langchain_core\language_models\chat_models.py", line 286, in invoke
    self.generate_prompt(
  File "Lib\site-packages\langchain_core\language_models\chat_models.py", line 786, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Lib\site-packages\langchain_core\language_models\chat_models.py", line 643, in generate
    raise e
  File "Lib\site-packages\langchain_core\language_models\chat_models.py", line 633, in generate
    self._generate_with_cache(
  File "Lib\site-packages\langchain_core\language_models\chat_models.py", line 855, in _generate_with_cache
    result = self._generate(
             ^^^^^^^^^^^^^^^
  File "Lib\site-packages\langchain_ollama\chat_models.py", line 644, in _generate
    final_chunk = self._chat_stream_with_aggregation(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Lib\site-packages\langchain_ollama\chat_models.py", line 545, in _chat_stream_with_aggregation
    for stream_resp in self._create_chat_stream(messages, stop, **kwargs):
  File "Lib\site-packages\langchain_ollama\chat_models.py", line 517, in _create_chat_stream
    yield self._client.chat(
          ^^^^^^^^^^^^^^^^^^
  File "Lib\site-packages\ollama\_client.py", line 102, in _request_stream
    return self._stream(*args, **kwargs) if stream else self._request(*args, **kwargs).json()
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Lib\site-packages\ollama\_client.py", line 78, in _request
    raise ResponseError(e.response.text, e.response.status_code) from None
ollama._types.ResponseError: llama3.1 does not support tools

### Description

Because I am behind a corporate proxy (with authentication, etc.) , I have to download the .gguf of the model from HuggingFace, and then create the model with 
```
ollama create example -f Modelfile
ollama run example
```

For the code I am writing, I want to try out the "tool" enabled models through Ollama. I have downloaded llama3.1 (which should accept tool calling. But I also tried Groq and others. 
Does anyone know if there is a flag to raise somewhere in the model description when downloading manually to indicate to LangChain that the model is tool enabled ? 

### System Info

System Information
------------------
> OS:  Windows
> OS Version:  10
> Python Version:  3.11.9 

Package Information
-------------------
> langchain_core: 0.3.0
> langchain: 0.3.0
> langchain_community: 0.3.0
> langsmith: 0.1.121
> langchain_experimental: 0.3.0
> langchain_mistralai: 0.2.0
> langchain_ollama: 0.2.0
> langchain_text_splitters: 0.3.0
> langchain_unstructured: 0.1.2

Optional packages not installed
-------------------------------
> langgraph
> langserve

Other Dependencies
------------------
> aiohttp: 3.10.5
> async-timeout: Installed. No version info available.
> dataclasses-json: 0.6.7
> httpx: 0.27.2
> httpx-sse: 0.4.0
> jsonpatch: 1.33
> numpy: 1.26.4
> ollama: 0.3.3
> orjson: 3.10.7
> packaging: 24.1
> pydantic: 2.8.2
> pydantic-settings: 2.5.2
> PyYAML: 6.0.2
> requests: 2.32.3
> SQLAlchemy: 2.0.34
> tenacity: 8.5.0
> tokenizers: 0.19.1
> typing-extensions: 4.12.2
> unstructured-client: 0.24.1
> unstructured[all-docs]: Installed. No version info available.

**Comment by TimmyTimTim1337** [comment]
For an example link where I downloaded llama3.1 with tool calling:
[llama3.1-8B](https://huggingface.co/lmstudio-community/Meta-Llama-3.1-8B-Instruct-GGUF/blob/main/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf)
