### ISSUE TITLE
Chat agent does not parse properly when model returns a code block

### ISSUE THREAD

**Issue by sachit-menon** [langchain-ai/langchain#2679]
When you ask GPT to produce code, you get an error since the way responses are parsed splits the cleaned output by triple backticks, which doesn't account for possible usage of triple backticks in the output itself. 

To reproduce:
```python
llm = ChatOpenAI(model_name="gpt-3.5-turbo")
memory = ConversationBufferMemory(memory_key="chat_history", return_messages=True)

tools = load_tools(["llm-math"], llm=llm)
agent = initialize_agent(tools, 
                         llm, 
                         agent=AgentType.CHAT_CONVERSATIONAL_REACT_DESCRIPTION, 
                         verbose=True, 
                         memory=memory)


agent.run(input='Write a program for Hello World in Python.')
```

Traceback:
~~~
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File [~/opt/miniconda3/envs/misc/lib/python3.10/site-packages/langchain/agents/conversational_chat/base.py:106](https://vscode-interactive+.vscode-resource.vscode-cdn.net//~/opt/miniconda3/envs/misc/lib/python3.10/site-packages/langchain/agents/conversational_chat/base.py:106), in ConversationalChatAgent._extract_tool_and_input(self, llm_output)
    [105](file:///Users/sachit/opt/miniconda3/envs/misc/lib/python3.10/site-packages/langchain/agents/conversational_chat/base.py?line=104) try:
--> [106](file:///Users/sachit/opt/miniconda3/envs/misc/lib/python3.10/site-packages/langchain/agents/conversational_chat/base.py?line=105)     response = self.output_parser.parse(llm_output)
    [107](file:///Users/sachit/opt/miniconda3/envs/misc/lib/python3.10/site-packages/langchain/agents/conversational_chat/base.py?line=106)     return response["action"], response["action_input"]

File [~/opt/miniconda3/envs/misc/lib/python3.10/site-packages/langchain/agents/conversational_chat/base.py:43](https://vscode-interactive+.vscode-resource.vscode-cdn.net//~/opt/miniconda3/envs/misc/lib/python3.10/site-packages/langchain/agents/conversational_chat/base.py:43), in AgentOutputParser.parse(self, text)
     [42](file:///Users/sachit/opt/miniconda3/envs/misc/lib/python3.10/site-packages/langchain/agents/conversational_chat/base.py?line=41) if "```" in cleaned_output:
---> [43](file:///Users/sachit/opt/miniconda3/envs/misc/lib/python3.10/site-packages/langchain/agents/conversational_chat/base.py?line=42)     cleaned_output, _ = cleaned_output.split("```")
     [44](file:///Users/sachit/opt/miniconda3/envs/misc/lib/python3.10/site-packages/langchain/agents/conversational_chat/base.py?line=43) if cleaned_output.startswith("```json"):

ValueError: too many values to unpack (expected 2)

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
[/Users/sachit/Documents/Documents](https://vscode-interactive+.vscode-resource.vscode-cdn.net/Users/sachit/Documents/Documents) - Sachit’s MacBook Pro[/Projects/ai_assistant/import](https://vscode-interactive+.vscode-resource.vscode-cdn.net/Projects/ai_assistant/import) openai.py in line 1
----> [38](file:///Users/sachit/Documents/Documents%20-%20Sachit%E2%80%99s%20MacBook%20Pro/Projects/ai_assistant/import%20openai.py?line=37) agent.run(input=query)

File [~/opt/miniconda3/envs/misc/lib/python3.10/site-packages/langchain/chains/base.py:216](https://vscode-interactive+.vscode-resource.vscode-cdn.net//~/opt/miniconda3/envs/misc/lib/python3.10/site-packages/langchain/chains/base.py:216), in Chain.run(self, *args, **kwargs)
    [213](file:///Users/sachit/opt/miniconda3/envs/misc/lib/python3.10/site-packages/langchain/chains/base.py?line=212)     return self(args[0])[self.output_keys[0]]
    [215](file:///Users/sachit/opt/miniconda3/envs/misc/lib/python3.10/site-packages/langchain/chains/base.py?line=214) if kwargs and not args:
--> [216](file:///Users/sachit/opt/miniconda3/envs/misc/lib/python3.10/site-packages/langchain/chains/base.py?line=215)     return self(kwargs)[self.output_keys[0]]
    [218](file:///Users/sachit/opt/miniconda3/envs/misc/lib/python3.10/site-packages/langchain/chains/base.py?line=217) raise ValueError(
...
{
    "action": "Final Answer",
    "action_input": "Here is an example program for 'Hello World' in Python: \n\n```python\nprint('Hello, World!')\n```"
}
```

~~~

**Comment by Kav-K** [comment]
Have this issue too!

**Comment by Jiankun-Huang** [comment]
Have this issue too!

**Comment by Kav-K** [comment]
```
Traceback (most recent call last):
  File "/home/gptbot/cogs/search_service_cog.py", line 290, in on_message
    response, stdout_output = await capture_stdout(
  File "/home/gptbot/cogs/search_service_cog.py", line 47, in capture_stdout
    result = await func(*args, **kwargs)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/dist-packages/langchain/chains/base.py", line 213, in run
    return self(args[0])[self.output_keys[0]]
  File "/usr/local/lib/python3.9/dist-packages/langchain/chains/base.py", line 116, in __call__
    raise e
  File "/usr/local/lib/python3.9/dist-packages/langchain/chains/base.py", line 113, in __call__
    outputs = self._call(inputs)
  File "/usr/local/lib/python3.9/dist-packages/langchain/agents/agent.py", line 792, in _call
    next_step_output = self._take_next_step(
  File "/usr/local/lib/python3.9/dist-packages/langchain/agents/agent.py", line 672, in _take_next_step
    output = self.agent.plan(intermediate_steps, **inputs)
  File "/usr/local/lib/python3.9/dist-packages/langchain/agents/agent.py", line 385, in plan
    return self.output_parser.parse(full_output)
  File "/usr/local/lib/python3.9/dist-packages/langchain/agents/conversational_chat/output_parser.py", line 20, in parse
    cleaned_output, _ = cleaned_output.split("```")
ValueError: too many values to unpack (expected 2)


```

**Comment by axiomofjoy** [comment]
Seeing this issue as well.

**Comment by whisperdrive** [comment]
experiencing this issue as well.

**Comment by Jawabiscuit** [comment]
Room for one more?

**Comment by Kav-K** [comment]
Still experiencing this unfortunately!

**Comment by Jawabiscuit** [comment]
Looks like https://github.com/hwchase17/langchain/pull/3480 is the most likely candidate for resolving these types of issues.

**Comment by rickbraddy-pharma** [comment]
Sure need this to work with code

**Comment by rickbraddy-pharma** [comment]
This is now fixed and available in pull request #5037

**Comment by pjerryhu** [comment]
This bug is still persisting.

**Comment by pjerryhu** [comment]
my fix is switching from `CHAT_CONVERSATIONAL_REACT_DESCRIPTION` to `CONVERSATIONAL_REACT_DESCRIPTION`

**Comment by aminehd** [comment]
I implemented output pareser and passed to to agent initializer
```
def converationtional_agent_creator(tools):
    return initialize_agent(
    agent=AgentType.CHAT_CONVERSATIONAL_REACT_DESCRIPTION,
    llm=llm,
    tools=tools,
    ...
    agent_kwargs={'output_parser': CustomConvoOutputParser()}
)
```

**Comment by Kav-K** [comment]
This is still relevant!

**Comment by hussainwali74** [comment]
why did you create langchain just why bro there was no need so much bloat
