### ISSUE TITLE
VectorStoreIndexCreator can't load from UnstructuredFileLoader

### ISSUE THREAD

**Issue by MinhCndS64** [langchain-ai/langchain#2685]
Expectation: 
Loading a text file via UnstructuredFileLoader then passing the output docs to VectorStoreIndexCreator should work
Observation:
Crash when attempting to call `VectorstoreIndexCreator().from_loaders(unstructuredFileLoader)`

Crashlog:
```
Traceback (most recent call last):
  File "/Users/minhcnd/Repos/llm-demo/llm_demo/main.py", line 30, in <module>
    index = VectorstoreIndexCreator().from_loaders(loaders)
  File "/Users/minhcnd/Library/Caches/pypoetry/virtualenvs/llm-demo-yOjCLQYD-py3.9/lib/python3.9/site-packages/langchain/indexes/vectorstore.py", line 71, in from_loaders
    vectorstore = self.vectorstore_cls.from_documents(
  File "/Users/minhcnd/Library/Caches/pypoetry/virtualenvs/llm-demo-yOjCLQYD-py3.9/lib/python3.9/site-packages/langchain/vectorstores/chroma.py", line 334, in from_documents
    return cls.from_texts(
  File "/Users/minhcnd/Library/Caches/pypoetry/virtualenvs/llm-demo-yOjCLQYD-py3.9/lib/python3.9/site-packages/langchain/vectorstores/chroma.py", line 303, in from_texts
    chroma_collection.add_texts(texts=texts, metadatas=metadatas, ids=ids)
  File "/Users/minhcnd/Library/Caches/pypoetry/virtualenvs/llm-demo-yOjCLQYD-py3.9/lib/python3.9/site-packages/langchain/vectorstores/chroma.py", line 114, in add_texts
    self._collection.add(
  File "/Users/minhcnd/Library/Caches/pypoetry/virtualenvs/llm-demo-yOjCLQYD-py3.9/lib/python3.9/site-packages/chromadb/api/models/Collection.py", line 85, in add
    metadatas = validate_metadatas(maybe_cast_one_to_many(metadatas)) if metadatas else None
  File "/Users/minhcnd/Library/Caches/pypoetry/virtualenvs/llm-demo-yOjCLQYD-py3.9/lib/python3.9/site-packages/chromadb/api/types.py", line 108, in validate_metadatas
    validate_metadata(metadata)
  File "/Users/minhcnd/Library/Caches/pypoetry/virtualenvs/llm-demo-yOjCLQYD-py3.9/lib/python3.9/site-packages/chromadb/api/types.py", line 99, in validate_metadata
    raise ValueError(f"Expected metadata value to be a str, int, or float, got {value}")
ValueError: Expected metadata value to be a str, int, or float, got seneca.txt
```

Root cause:
In unstructured.py, `_get_metadata()` returns a **PoxisPath** object, but validate_metadata expects a str, int or float

**Comment by alexclaydon** [comment]
I'm having the same problem on `0.0.145` when using a Document returned by `BSHTMLLoader` from a single html file, in cases where I was passing `file_path` as a `pathlib.Path` instead of a string.

```
Exception has occurred: ValueError
Expected metadata value to be a str, int, or float, got /Users/alexclaydon/Downloads/fdsa/asdf.html
  File "/Users/alexclaydon/dev/dev-projects/claytools/src/libllm/blueprints/qa/qa_on_vectorize_stuff_docs_v01.py", line 59, in main
    index = Chroma.from_documents(
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alexclaydon/dev/dev-projects/claytools/src/libllm/blueprints/qa/qa_on_vectorize_stuff_docs_v01.py", line 84, in <module>
    app()
ValueError: Expected metadata value to be a str, int, or float, got /Users/alexclaydon/Downloads/fdsa/asdf.html
```
Weirdly enough, it was only happening when working with single Documents.  If I instead I wrap `BSHTMLLoader` in a `DirectoryLoader` as follows:

```
html_loader = DirectoryLoader(
    path=document_dir, glob="**/*.html", loader_cls=BSHTMLLoader
)
```
then it didn't matter that I was passing `path` to `DirectoryLoader` as a `pathlib.Path`, which made it tricky to debug.  Perhaps `DirectoryLoader` correctly parses out the `.as_posix()` pathstring while `BSHTMLLoader` doesn't.

In any event, in my case I was able to solve it by making sure I appended `.as_posix()` to any `pathlib.Path` passed to `BSHTMLLoader`, or by simply ensuring that I only passed strings to the loader.

**Comment by ghoto** [comment]
+1

**Comment by smuskal** [comment]
MIght be useful for those with slightly different error:   

loaders = [UnstructuredPDFLoader(os.path.join(text_folder, fn)) for fn in os.listdir(text_folder) if not fn.startswith('.')]
