### ISSUE TITLE
HF_HUB_OFFLINE environment variable breaks HuggingFaceEndpoints

### ISSUE THREAD

**Issue by ladi-pomsar** [langchain-ai/langchain#27113]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

export HF_HUB_OFFLINE="1"

### Error Message and Stack Trace (if applicable)

 | [2024-10-04 09:58:56,644] ERROR in app: Exception on /endpoint [POST]
 | Traceback (most recent call last):
 |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
 |     response = self.full_dispatch_request()
 |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
 |     rv = self.handle_user_exception(e)
 |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 |   File "/usr/local/lib/python3.11/site-packages/flask_cors/extension.py", line 178, in wrapped_function
 |     return cors_after_request(app.make_response(f(*args, **kwargs)))
 |                                                 ^^^^^^^^^^^^^^^^^^
 |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
 |     rv = self.dispatch_request()
 |          ^^^^^^^^^^^^^^^^^^^^^^^
 |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
 |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
 |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 |   //USER CODE
 |     
 |   File "/usr/local/lib/python3.11/site-packages/celery/local.py", line 182, in __call__
 |     return self._get_current_object()(*a, **kw)
 |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 |   File "/usr/local/lib/python3.11/site-packages/celery/app/task.py", line 411, in __call__
 |     return self.run(*args, **kwargs)
 |            ^^^^^^^^^^^^^^^^^^^^^^^^^
 |   //USER CODE
 |   
 |  
 |   File "/usr/local/lib/python3.11/site-packages/langchain_core/vectorstores/base.py", line 277, in add_documents
 |     return self.add_texts(texts, metadatas, **kwargs)
 |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 |   File "/usr/local/lib/python3.11/site-packages/langchain_postgres/vectorstores.py", line 885, in add_texts
 |     embeddings = self.embedding_function.embed_documents(texts_)
 |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 |   File "/usr/local/lib/python3.11/site-packages/langchain_huggingface/embeddings/huggingface_endpoint.py", line 112, in embed_documents
 |     responses = self.client.post(
 |                 ^^^^^^^^^^^^^^^^^
 |   File "/usr/local/lib/python3.11/site-packages/huggingface_hub/inference/_client.py", line 259, in post
 |     response = get_session().post(
 |                ^^^^^^^^^^^^^^^^^^^
 |   File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
 |     return self.request("POST", url, data=data, json=json, **kwargs)
 |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 |   File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
 |     resp = self.send(prep, **send_kwargs)
 |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 |   File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
 |     r = adapter.send(request, **kwargs)
 |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 |   File "/usr/local/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 77, in send
 |     raise OfflineModeIsEnabled(
 | huggingface_hub.errors.OfflineModeIsEnabled: Cannot reach http://localhost:80/: offline mode is enabled. To disable it, please unset the `HF_HUB_OFFLINE` environment variable.

### Description

Hi everyone,

I am using Langchain with TEI for embeddings. As I usually use it on-prem + offline, I would prefer it not checking HF repeatedly, while still being able to work locally. 

At some point, huggingface_hub introduced environment variable "HF_HUB_OFFLINE", that should do approximately that, [quoting the first line](https://huggingface.co/docs/huggingface_hub/v0.22.0.rc0/package_reference/environment_variables):

> If set, no HTTP calls will me made to the Hugging Face Hub.

However, as noted later on - 
> "If HF_HUB_OFFLINE=1 is set as environment variable and you call any method of [HfApi](https://huggingface.co/docs/huggingface_hub/v0.22.0.rc0/en/package_reference/hf_api#huggingface_hub.HfApi), an [OfflineModeIsEnabled](https://huggingface.co/docs/huggingface_hub/v0.22.0.rc0/en/package_reference/utilities#huggingface_hub.utils.OfflineModeIsEnabled) exception will be raised."

This seems to be consistent with observed behaviour, but I would argue it is not desired, as it pretty much disables langchain as well, as embedding functionality seems to be provided through [Inference client.](https://huggingface.co/docs/huggingface_hub/package_reference/inference_client#huggingface_hub.InferenceClient)

I don't have a good idea how to solve this, aside from reworking Langchain to use REST APIs (did check, can retrieve the embeddings) or HF HUB blocking just calls to HF. I will also rise this issue in HuggingFace Hub repo as I am not sure how often do HF people frequent issues here and hopefully we converge somewhere.

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jul 13 16:27:29 UTC 2
> Python Version:  3.11.10 (main, Sep 27 2024, 06:09:18) [GCC 12.2.0]

Package Information
-------------------
> langchain_core: 0.3.8
> langchain: 0.3.2
> langchain_community: 0.3.1
> langsmith: 0.1.131
> langchain_huggingface: 0.1.0
> langchain_openai: 0.2.1
> langchain_postgres: 0.0.12
> langchain_text_splitters: 0.3.0

Optional packages not installed
-------------------------------
> langgraph
> langserve

Other Dependencies
------------------
> aiohttp: 3.9.5
> async-timeout: 4.0.3
> dataclasses-json: 0.6.6
> httpx: 0.27.0
> huggingface-hub: 0.23.4
> jsonpatch: 1.33
> numpy: 1.26.4
> openai: 1.40.6
> orjson: 3.10.3
> packaging: 23.2
> pgvector: 0.2.5
> psycopg: 3.1.19
> psycopg-pool: 3.2.2
> pydantic: 2.7.4
> pydantic-settings: 2.5.2
> PyYAML: 6.0.1
> requests: 2.32.3
> requests-toolbelt: 1.0.0
> sentence-transformers: 2.7.0
> sqlalchemy: 2.0.30
> SQLAlchemy: 2.0.30
> tenacity: 8.3.0
> tiktoken: 0.7.0
> tokenizers: 0.19.1
> transformers: 4.42.3
> typing-extensions: 4.12.0

**Comment by ladi-pomsar** [comment]
Closing as workaround is provided in HF_Hub repo
