### ISSUE TITLE
llm.with_structure_output requires missing parameter toolSpec.description

### ISSUE THREAD

**Issue by netageva** [langchain-ai/langchain#27152]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
    llm = ChatBedrockConverse(
        client=bedrock_client,
        model=config.BEDROCK_MODEL_ID,
        temperature=0.0,
        max_tokens=4096)

    structured_llm = llm.with_structured_output(DndTariff)

    # Invoke the LLM with the structured output
    response = structured_llm.invoke(messages)


```

### Error Message and Stack Trace (if applicable)

```
Traceback (most recent call last):
  File "/Users/Neta/repos/py-dnd-contract-to-tariffs-converter-service/.venv/lib/python3.9/site-packages/langchain_core/runnables/base.py", line 3020, in invoke
    input = context.run(step.invoke, input, config, **kwargs)
  File "/Users/Neta/repos/py-dnd-contract-to-tariffs-converter-service/.venv/lib/python3.9/site-packages/langchain_core/runnables/base.py", line 5337, in invoke
    return self.bound.invoke(
  File "/Users/Neta/repos/py-dnd-contract-to-tariffs-converter-service/.venv/lib/python3.9/site-packages/langchain_core/language_models/chat_models.py", line 284, in invoke
    self.generate_prompt(
  File "/Users/Neta/repos/py-dnd-contract-to-tariffs-converter-service/.venv/lib/python3.9/site-packages/langchain_core/language_models/chat_models.py", line 784, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
  File "/Users/Neta/repos/py-dnd-contract-to-tariffs-converter-service/.venv/lib/python3.9/site-packages/langchain_core/language_models/chat_models.py", line 641, in generate
    raise e
  File "/Users/Neta/repos/py-dnd-contract-to-tariffs-converter-service/.venv/lib/python3.9/site-packages/langchain_core/language_models/chat_models.py", line 631, in generate
    self._generate_with_cache(
  File "/Users/Neta/repos/py-dnd-contract-to-tariffs-converter-service/.venv/lib/python3.9/site-packages/langchain_core/language_models/chat_models.py", line 850, in _generate_with_cache
    result = self._generate(
  File "/Users/Neta/repos/py-dnd-contract-to-tariffs-converter-service/.venv/lib/python3.9/site-packages/langchain_aws/chat_models/bedrock_converse.py", line 492, in _generate
    response = self.client.converse(
  File "/Users/Neta/repos/py-dnd-contract-to-tariffs-converter-service/.venv/lib/python3.9/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/Neta/repos/py-dnd-contract-to-tariffs-converter-service/.venv/lib/python3.9/site-packages/botocore/client.py", line 980, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/Users/Neta/repos/py-dnd-contract-to-tariffs-converter-service/.venv/lib/python3.9/site-packages/botocore/client.py", line 1047, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/Users/Neta/repos/py-dnd-contract-to-tariffs-converter-service/.venv/lib/python3.9/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid length for parameter toolConfig.tools[0].toolSpec.description, value: 0, valid min length: 1
```

### Description

Im using langchain-aws to parse llm output to pydantic data class.
It requiers toolConfig.tools[0].toolSpec.description to be not empty (length > 0) but it can not be passed as parameter

When manually changed structured_llm --> steps --> 0 --> kwargs --> tools --> 0 --> toolspec--> description to be with some string it works, but it can not be controled outside debugging mode. 

### System Info

langchain-aws = 0.2.2

**Comment by tioans** [comment]
Hi @netageva, I ran into the same issue again. Could you tell me what's the solution?

**Comment by netageva** [comment]
@tioans see solution in recent edit
