### ISSUE TITLE
Self query retriever not working with float dtype.

### ISSUE THREAD

**Issue by abhijithnair1** [langchain-ai/langchain#27204]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
def setup_retriever(
    vectorstore: QdrantVectorStore,
    llm: BaseChatOpenAI,
    similarity_threshold: float = 0.4,
) -> RePhraseQueryRetriever:
    """Setup the SelfQueryRetriever and the compressed retriever pipeline."""
    retriever = SelfQueryRetriever.from_llm(
        llm=llm,
        vectorstore=vectorstore,
        document_contents=document_content_description,
        metadata_field_info=metadata_field_info,
        use_original_query=False,
        enable_limit=False,
        chain_kwargs={"examples": FILTER_EXAMPLES, "fix_invalid": False},
    )

    retriever.search_kwargs["k"] = 5

    # Embeddings filter for compression
    embeddings_filter = EmbeddingsFilter(
        embeddings=embeddings, similarity_threshold=similarity_threshold, k=5
    )

    # Create compressed retriever
    compression_retriever = ContextualCompressionRetriever(
        base_compressor=embeddings_filter, base_retriever=retriever
    )

    # Set up the rephrased query retriever
    REPHRASE_TEMPLATE_UPDATE = PromptTemplate.from_template(REPHRASE_TEMPLATE)

    return RePhraseQueryRetriever.from_llm(
        retriever=compression_retriever,
        llm=llm,  # type: ignore[arg-type]
        prompt=REPHRASE_TEMPLATE_UPDATE,
    )
    
   retriever = setup_retriever(....)
   docs = retriever_from_llm.invoke(question) -> this is invoking the self query retriever from langchain.
```

**Filter generated by self-query retriever:**

```
{
  "generations": [
    [
      {
        "text": "```json\n{\n    \"query\": \"Series A start-ups\",\n    \"filter\": \"and(like(\\\"funding_stage\\\", \\\"series a\\\"), eq(\\\"revenue_min\\\", 1000000.0), eq(\\\"revenue_max\\\", 1000000.0))\"\n}\n```",
        "generation_info": {
          "finish_reason": "stop",
          "logprobs": null
        },
        "type": "ChatGeneration",
        "message": {
          "lc": 1,
          "type": "constructor",
          "id": [
            "langchain",
            "schema",
            "messages",
            "AIMessage"
          ],
          "kwargs": {
            "content": "```json\n{\n    \"query\": \"Series A start-ups\",\n    \"filter\": \"and(like(\\\"funding_stage\\\", \\\"series a\\\"), eq(\\\"revenue_min\\\", 1000000.0), eq(\\\"revenue_max\\\", 1000000.0))\"\n}\n```",
            "additional_kwargs": {
              "refusal": null
            },
            "response_metadata": {
              "token_usage": {
                "completion_tokens": 61,
                "prompt_tokens": 2467,
                "total_tokens": 2528,
                "completion_tokens_details": {
                  "audio_tokens": null,
                  "reasoning_tokens": 0
                },
                "prompt_tokens_details": {
                  "audio_tokens": null,
                  "cached_tokens": 2304
                }
              },
              "model_name": "gpt-4o-2024-08-06",
              "system_fingerprint": "fp_2f406b9113",
              "finish_reason": "stop",
              "logprobs": null
            },
            "type": "ai",
            "id": "run-982ccef4-5182-4619-a0fd-1d5812a4489a-0",
            "usage_metadata": {
              "input_tokens": 2467,
              "output_tokens": 61,
              "total_tokens": 2528,
              "input_token_details": {
                "cache_read": 2304
              },
              "output_token_details": {
                "reasoning": 0
              }
            },
            "tool_calls": [],
            "invalid_tool_calls": []
          }
        }
      }
    ]
  ],
  "llm_output": {
    "token_usage": {
      "completion_tokens": 61,
      "prompt_tokens": 2467,
      "total_tokens": 2528,
      "completion_tokens_details": {
        "audio_tokens": null,
        "reasoning_tokens": 0
      },
      "prompt_tokens_details": {
        "audio_tokens": null,
        "cached_tokens": 2304
      }
    },
    "model_name": "gpt-4o-2024-08-06",
    "system_fingerprint": "fp_2f406b9113"
  },
  "run": null,
  "type": "LLMResult"
}
```

### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "/random_path_1/app/inception_agent/pipeline.py", line 24, in run_pipeline
    docs: List[Document] = retriever_from_llm.invoke(question)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/random_path_2/.venv/lib/python3.12/site-packages/langchain_core/retrievers.py", line 254, in invoke
    raise e
  File "/random_path_2/.venv/lib/python3.12/site-packages/langchain_core/retrievers.py", line 247, in invoke
    result = self._get_relevant_documents(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/random_path_2/.venv/lib/python3.12/site-packages/langchain/retrievers/re_phraser.py", line 78, in _get_relevant_documents
    docs = self.retriever.invoke(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/random_path_2/.venv/lib/python3.12/site-packages/langchain_core/retrievers.py", line 254, in invoke
    raise e
  File "/random_path_2/.venv/lib/python3.12/site-packages/langchain_core/retrievers.py", line 247, in invoke
    result = self._get_relevant_documents(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/random_path_2/.venv/lib/python3.12/site-packages/langchain/retrievers/contextual_compression.py", line 44, in _get_relevant_documents
    docs = self.base_retriever.invoke(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/random_path_2/.venv/lib/python3.12/site-packages/langchain_core/retrievers.py", line 254, in invoke
    raise e
  File "/random_path_2/.venv/lib/python3.12/site-packages/langchain_core/retrievers.py", line 247, in invoke
    result = self._get_relevant_documents(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/random_path_2/.venv/lib/python3.12/site-packages/langchain/retrievers/self_query/base.py", line 287, in _get_relevant_documents
    new_query, search_kwargs = self._prepare_query(query, structured_query)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/random_path_2/.venv/lib/python3.12/site-packages/langchain/retrievers/self_query/base.py", line 249, in _prepare_query
    new_query, new_kwargs = self.structured_query_translator.visit_structured_query(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/random_path_2/.venv/lib/python3.12/site-packages/langchain_community/query_constructors/qdrant.py", line 95, in visit_structured_query
    filter = structured_query.filter.accept(self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/random_path_2/.venv/lib/python3.12/site-packages/langchain_core/structured_query.py", line 89, in accept
    return getattr(visitor, f"visit_{_to_snake_case(self.__class__.__name__)}")(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/random_path_2/.venv/lib/python3.12/site-packages/langchain_community/query_constructors/qdrant.py", line 50, in visit_operation
    args = [arg.accept(self) for arg in operation.arguments]
            ^^^^^^^^^^^^^^^^
  File "/random_path_2/.venv/lib/python3.12/site-packages/langchain_core/structured_query.py", line 89, in accept
    return getattr(visitor, f"visit_{_to_snake_case(self.__class__.__name__)}")(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/random_path_2/.venv/lib/python3.12/site-packages/langchain_community/query_constructors/qdrant.py", line 72, in visit_comparison
    key=attribute, match=rest.MatchValue(value=comparison.value)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/random_path_2/.venv/lib/python3.12/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 3 validation errors for MatchValue
value.bool
  Input should be a valid boolean [type=bool_type, input_value=1000000.0, input_type=float]
    For further information visit https://errors.pydantic.dev/2.9/v/bool_type
value.int
  Input should be a valid integer [type=int_type, input_value=1000000.0, input_type=float]
    For further information visit https://errors.pydantic.dev/2.9/v/int_type
value.str
  Input should be a valid string [type=string_type, input_value=1000000.0, input_type=float]
    For further information visit https://errors.pydantic.dev/2.9/v/string_type

### Description

I am trying to user self query retriever but facing an issue with float dtype metadata filtering. Any help is appreciated.

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 24.1.0: Mon Sep 30 00:10:33 PDT 2024; root:xnu-11215.40.63~39/RELEASE_ARM64_T8112
> Python Version:  3.12.6 (main, Sep  6 2024, 19:03:47) [Clang 16.0.0 (clang-1600.0.26.3)]

Package Information
-------------------
> langchain_core: 0.3.9
> langchain: 0.3.2
> langchain_community: 0.3.1
> langsmith: 0.1.131
> langchain_experimental: 0.3.2
> langchain_openai: 0.2.2
> langchain_qdrant: 0.1.4
> langchain_text_splitters: 0.3.0
> langchainhub: 0.1.21
> langgraph: 0.2.34

Optional packages not installed
-------------------------------
> langserve

Other Dependencies
------------------
> aiohttp: 3.10.9
> async-timeout: Installed. No version info available.
> dataclasses-json: 0.6.7
> fastembed: Installed. No version info available.
> httpx: 0.27.2
> jsonpatch: 1.33
> langgraph-checkpoint: 2.0.1
> numpy: 1.26.4
> openai: 1.51.0
> orjson: 3.10.7
> packaging: 24.1
> pydantic: 2.9.2
> pydantic-settings: 2.5.2
> PyYAML: 6.0.2
> qdrant-client: 1.11.3
> requests: 2.32.3
> requests-toolbelt: 1.0.0
> SQLAlchemy: 2.0.35
> tenacity: 8.5.0
> tiktoken: 0.8.0
> types-requests: 2.32.0.20240914
> typing-extensions: 4.12.2

**Comment by Ahmetyasin** [comment]
It looks like the error occurs because the filter generated by SelfQueryRetriever uses float values (e.g., 1000000.0) for metadata fields like revenue_min and revenue_max, but the filter logic (via pydantic) expects types like bool, int, or str. To resolve this, the metadata field types in the vector store should be adjusted to handle float values, or the filter generation logic should cast these floats to the expected types (e.g., integers or strings).
