### ISSUE TITLE
LangChain Zep Integration Fails Due to Deprecated Import

### ISSUE THREAD

**Issue by rabbit19981023** [langchain-ai/langchain#27356]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from langchain_community.memory.zep_memory import ZepMemory

memory = ZepMemory(
    session_id="SESSION ID",
    url="http://localhost:8000",
    api_key="ZEP SECRET",
)
```

### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "/home/andrew/my-projects/ai-learning/langchain-zep-test/.venv/lib/python3.12/site-packages/langchain_community/chat_message_histories
/zep.py", line 79, in __init__
    from zep_python import ZepClient
ImportError: cannot import name 'ZepClient' from 'zep_python' (/home/andrew/my-projects/ai-learning/langchain-zep-test/.venv/lib/python3.12/s
ite-packages/zep_python/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andrew/my-projects/ai-learning/langchain-zep-test/.venv/bin/langchain-zep-test", line 5, in <module>
    from langchain_zep_test import main
  File "/home/andrew/my-projects/ai-learning/langchain-zep-test/src/langchain_zep_test/__init__.py", line 7, in <module>
    memory = ZepMemory(
             ^^^^^^^^^^
  File "/home/andrew/my-projects/ai-learning/langchain-zep-test/.venv/lib/python3.12/site-packages/langchain_community/memory/zep_memory.py",
 line 91, in __init__
    chat_message_history = ZepChatMessageHistory(
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrew/my-projects/ai-learning/langchain-zep-test/.venv/lib/python3.12/site-packages/langchain_community/chat_message_histories
/zep.py", line 81, in __init__
    raise ImportError(
ImportError: Could not import zep-python package. Please install it with `pip install zep-python`.

### Description

I found the source code uses `ZepClient`, which is deprecated, now Zep provides `Zep` and `AsyncZep` to use.

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #1 SMP Fri Mar 29 23:14:13 UTC 2024
> Python Version:  3.12.6 (main, Sep  9 2024, 22:11:19) [Clang 18.1.8 ]

Package Information
-------------------
> langchain_core: 0.3.10
> langchain: 0.3.3
> langchain_community: 0.3.2
> langsmith: 0.1.135
> langchain_groq: 0.2.0
> langchain_text_splitters: 0.3.0
> langchain_zep_test: 0.1.0

Optional packages not installed
-------------------------------
> langgraph
> langserve

Other Dependencies
------------------
> aiohttp: 3.10.10
> async-timeout: Installed. No version info available.
> dataclasses-json: 0.6.7
> groq: 0.11.0
> httpx: 0.27.2
> jsonpatch: 1.33
> langchain-community>=0.3.2: Installed. No version info available.
> langchain-groq>=0.2.0: Installed. No version info available.
> numpy: 1.26.4
> orjson: 3.10.7
> packaging: 24.1
> pydantic: 2.9.2
> pydantic-settings: 2.5.2
> PyYAML: 6.0.2
> requests: 2.32.3
> requests-toolbelt: 1.0.0
> SQLAlchemy: 2.0.35
> tenacity: 8.5.0
> typing-extensions: 4.12.2
> zep-python>=2.0.2: Installed. No version info available.

**Comment by Jacky3003** [comment]
Hello, interested in diving deeper into this issue and I also would like to work on a fix if possible. Have you found any potential solutions as of now @rabbit19981023?

**Comment by rabbit19981023** [comment]
> Have you found any potential solutions as of now

@Jacky3003  I think just to update some interface to get working without error, something like `ZepClient.memory.get_memory` -> `Zep.memory.get`.

But I haven't tried to solve it yet. If you can fix it, that would be a big help

**Comment by Jacky3003** [comment]
@rabbit19981023 `Zep `and `AsyncZep` exist within langchain under `libs/community/langchain_community/memory/zep_cloud_memory.py`, and `libs/community/langchain_community/chat_message_histories/zep_cloud.py`, so you could try using those as such:

`from langchain_community.memory.zep_cloud_memory import ZepCloudMemory`

But it also seems to have its fair share of issues, so either way a fix is needed, just wanted to give an update.
