### ISSUE TITLE
When unicode character is in API key, non-specific error is returned (instead of invalid API key)

### ISSUE THREAD

**Issue by jasonkaedingrhino** [langchain-ai/langchain#27365]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage

#######################
#### CONFIGURATION ####
#######################

configs = dict(
    model = 'gpt-4-turbo-preview',
    openai_api_key = 'здравейздравейздравейздравей',  # This is the bad one
)

client = ChatOpenAI(**configs)

######################
###### RUN TEST ######
######################

message = 'Hello!'

response = client.invoke([HumanMessage(content=message)])

print(response)
```

### Error Message and Stack Trace (if applicable)

```
Traceback (most recent call last):
  File "C:\Users\jason\Documents\source\bug-test\venv\working\langchain-api-key-bug\test-basic.py", line 23, in <module>
    response = client.invoke([HumanMessage(content=message)])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason\Documents\source\bug-test\venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 286, in invoke
    self.generate_prompt(
  File "C:\Users\jason\Documents\source\bug-test\venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 786, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason\Documents\source\bug-test\venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 643, in generate
    raise e
  File "C:\Users\jason\Documents\source\bug-test\venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 633, in generate
    self._generate_with_cache(
  File "C:\Users\jason\Documents\source\bug-test\venv\Lib\site-packages\langchain_core\language_models\chat_models.py", line 851, in _generate_with_cache
    result = self._generate(
             ^^^^^^^^^^^^^^^
  File "C:\Users\jason\Documents\source\bug-test\venv\Lib\site-packages\langchain_openai\chat_models\base.py", line 683, in _generate
    response = self.client.create(**payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason\Documents\source\bug-test\venv\Lib\site-packages\openai\_utils\_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason\Documents\source\bug-test\venv\Lib\site-packages\openai\resources\chat\completions.py", line 668, in create
    return self._post(
           ^^^^^^^^^^^
  File "C:\Users\jason\Documents\source\bug-test\venv\Lib\site-packages\openai\_base_client.py", line 1260, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason\Documents\source\bug-test\venv\Lib\site-packages\openai\_base_client.py", line 937, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\jason\Documents\source\bug-test\venv\Lib\site-packages\openai\_base_client.py", line 963, in _request
    request = self._build_request(options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason\Documents\source\bug-test\venv\Lib\site-packages\openai\_base_client.py", line 459, in _build_request
    headers = self._build_headers(options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason\Documents\source\bug-test\venv\Lib\site-packages\openai\_base_client.py", line 417, in _build_headers
    headers = httpx.Headers(headers_dict)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason\Documents\source\bug-test\venv\Lib\site-packages\httpx\_models.py", line 70, in __init__
    self._list = [
                 ^
  File "C:\Users\jason\Documents\source\bug-test\venv\Lib\site-packages\httpx\_models.py", line 74, in <listcomp>
    normalize_header_value(v, encoding),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason\Documents\source\bug-test\venv\Lib\site-packages\httpx\_utils.py", line 53, in normalize_header_value
    return value.encode(encoding or "ascii")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'ascii' codec can't encode characters in position 7-34: ordinal not in range(128)
```

### Description

* A unicode character was accidentally used in the API key
* Langchain throws a difficult to understand unicode error because it does not appear to have "sanity checked" the value it was passing to httpx
* This caused us to spend multiple days trying to find the source of the problem assuming the error was in the message content, when an error like "invalid API key" would have pinpointed the source of the error and allowed us to find the root cause faster.

This was reported previously in #19144 but has been ignored/closed

### System Info

System Information
------------------
> OS:  Windows
> OS Version:  10.0.22631
> Python Version:  3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]

Package Information
-------------------
> langchain_core: 0.3.10
> langchain: 0.3.3
> langsmith: 0.1.135
> langchain_openai: 0.2.2
> langchain_text_splitters: 0.3.0

Optional packages not installed
-------------------------------
> langgraph
> langserve

Other Dependencies
------------------
> aiohttp: 3.8.5
> async-timeout: 4.0.3
> httpx: 0.26.0
> jsonpatch: 1.33
> numpy: 1.26.4
> openai: 1.44.0
> orjson: 3.9.15
> packaging: 24.0
> pydantic: 2.9.2
> PyYAML: 6.0.1
> requests: 2.31.0
> requests-toolbelt: 1.0.0
> SQLAlchemy: 2.0.25
> tenacity: 8.2.3
> tiktoken: 0.7.0
> typing-extensions: 4.12.2

**Comment by AndrewEffendi** [comment]
I Created a simple check and error message to address this issue

**Comment by jasonkaedingrhino** [comment]
Reported issue with `openai` library/package since it appears to be root cause
