### ISSUE TITLE
sqlalchemy.exc.NoInspectionAvailable: No inspection system is available for object of type <class 'langchain_community.utilities.sql_database.SQLDatabase'>

### ISSUE THREAD

**Issue by green999** [langchain-ai/langchain#27401]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

I am trying to connect to MSSQL (integrated authentication) with the following code:

conn_str = "mssql+pyodbc:///?odbc_connect=DRIVER={ODBC Driver 18 for SQL Server};SERVER=my-db-name50;DATABASE=DataProducts_dbname;Trusted_Connection=yes;"

db_engine = SQLDatabase.from_uri(conn_str)  **//This line works, connecting to DB.**

db = SQLDatabase(db_engine, schema="dbo")   // This line throws the error below. 

### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "C:\Users\k\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\k\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\k\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\__main__.py", line 71, in <module>
    cli.main()
  File "c:\Users\k\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy/..\debugpy\server\cli.py", line 501, in main
    run()
  File "c:\Users\k\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy/..\debugpy\server\cli.py", line 351, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\k\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 310, in run_path        
    return _run_module_code(code, init_globals, run_name, pkg_name=pkg_name, script_name=fname)
  File "c:\Users\k\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 127, in _run_module_code
    _run_code(code, mod_globals, init_globals, mod_name, mod_spec, pkg_name, script_name)
  File "c:\Users\k\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 118, in _run_code       
    exec(code, run_globals)
  File "C:\Users\k\OneDrive - NGC\Home\1.Project\1.IntegratedAnalytics\Source\rag-upgraded\projects\Sql\NL2SQL_chainlit.py", line 85, in <module>
    db = SQLDatabase(db_engine, schema="dbo")
  File "c:\Users\Source\rag-upgraded\.venv\lib\site-packages\langchain_community\utilities\sql_database.py", line 70, in __init__
    self._inspector = inspect(self._engine)
  File "c:\Users\Source\rag-upgraded\.venv\lib\site-packages\sqlalchemy\inspection.py", line 147, in inspect
    raise exc.NoInspectionAvailable(
sqlalchemy.exc.NoInspectionAvailable: No inspection system is available for object of type <class 'langchain_community.utilities.sql_database.SQLDatabase'>

### Description

As mentioned above, only the following line throws the error.
db = SQLDatabase(db_engine, schema="dbo")   // This line throws the error below. 

### System Info

langchain                                0.2.14
langchain-chroma                         0.1.4
langchain-cli                            0.0.31
langchain-community                      0.2.12
langchain-core                           0.2.33
langchain-openai                         0.1.22
langchain-text-splitters                 0.2.2
langdetect                               1.0.9
langserve                                0.2.2
langsmith                                0.1.101

**Comment by JoeZhou1234** [comment]
Hello, we (a group of 4) are planning to investigate this issue.

**Comment by green999** [comment]
I am sorry, so dumb. I got it.  The second line is not required. 

db = SQLDatabase.from_uri(conn_str) //This line works, connecting to DB.

#db = SQLDatabase(db_engine, schema="dbo") // This line is not needed.

**Comment by green999** [comment]
close this
