### ISSUE TITLE
Issue with chat history ValueError: Unexpected message with type <class 'langchain_core.messages.base.BaseMessage'> at the position 2

### ISSUE THREAD

**Issue by martyphee** [langchain-ai/langchain#27454]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python
import operator
from typing import TypedDict, Annotated, Union

from langchain.agents import create_tool_calling_agent
from langchain.agents.output_parsers.tools import ToolAgentAction
from langchain_core.agents import AgentAction, AgentFinish
from langchain_core.messages import BaseMessage
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.tools import tool
from langchain_google_vertexai import ChatVertexAI
from langgraph.checkpoint.postgres import PostgresSaver
from langgraph.graph import END, StateGraph
from langgraph.prebuilt import ToolNode

llm = ChatVertexAI(model="gemini-pro", temperature=0)


class AgentState(TypedDict):
    # The input string from human
    input: str
    # The list of previous messages in the conversation
    chat_history: list[BaseMessage]
    # The outcome of a given call to the agent
    # Needs 'list' as a valid type as the tool agent returns a list.
    # Needs `None` as a valid type, since this is what this will start as
    # this state will be overwritten with the latest everytime the agent is run
    agent_outcome: Union[AgentAction, list, ToolAgentAction, AgentFinish, None]

    # List of actions and corresponding observations
    # These actions should be added onto the existing so we use `operator.add`
    # to append to the list of past intermediate steps
    intermediate_steps: Annotated[list[Union[tuple[AgentAction, str], tuple[ToolAgentAction, str]]], operator.add]


# setup the simple tools using LangChain tool decorator
@tool
def add(a: int, b: int) -> int:
    """Add two numbers."""
    return a + b


@tool
def multiply(a: int, b: int) -> int:
    """Multiply two numbers."""
    return a * b


@tool
def square(a: int) -> int:
    """Calculates the square of a number."""
    a = int(a)
    return a * a


# setup the toolkit
toolkit = [add, multiply, square]

# define system prompt for tool calling agent
system_prompt = """ You are a mathematical assistant.
        Use your tools to answer questions. If you do not have a tool to
        answer the question, say so. """

tool_calling_prompt = ChatPromptTemplate.from_messages(
    [
        ("system", system_prompt),
        MessagesPlaceholder("chat_history", optional=True),
        ("human", "{input}"),
        MessagesPlaceholder("agent_scratchpad"),
    ]
)

tool_runnable = create_tool_calling_agent(llm, toolkit, prompt=tool_calling_prompt)
tool_actions = tool_runnable.invoke({"input": "hi! what's 1+1 and  2 times 2", 'intermediate_steps': []})


def run_tool_agent(state):
    agent_outcome = tool_runnable.invoke(state)

    # this agent will overwrite the agent outcome state variable
    return {"agent_outcome": agent_outcome}


# tool executor invokes the tool action specified from the agent runnable
# they will become the nodes that will be called when the agent decides on a tool action.

tool_executor = ToolNode(toolkit)


# Define the function to execute tools
# This node will run a different tool as specified in the state variable agent_outcome
def execute_tools(state):
    # Get the most recent agent_outcome - this is the key added in the `agent` above
    agent_action = state['agent_outcome']
    if type(agent_action) is not list:
        agent_action = [agent_action]
    steps = []
    # sca only returns an action while tool calling returns a list
    # convert single actions to a list

    for action in agent_action:
        # Execute the tool
        output = tool_executor.invoke(action)
        print(f"The agent action is {action}")
        print(f"The tool result is: {output}")
        steps.append((action, str(output)))
    # Return the output
    return {"intermediate_steps": steps}


def should_continue(data):
    # If the agent outcome is an AgentFinish, then we return `exit` string
    # This will be used when setting up the graph to define the flow
    if isinstance(data['agent_outcome'], AgentFinish):
        return "END"
    # Otherwise, an AgentAction is returned
    # Here we return `continue` string
    # This will be used when setting up the graph to define the flow
    else:
        return "CONTINUE"


# Define a new graph
workflow = StateGraph(AgentState)

# When nodes are called, the functions for to the tools will be called.
workflow.add_node("agent", run_tool_agent)

# Add tool invocation node to the graph
workflow.add_node("action", execute_tools)

# Define which node the graph will invoke at start.
workflow.set_entry_point("agent")

# Add flow logic with static edge.
# Each time a tool is invoked and completed we want to
# return the result to the agent to assess if task is complete or to take further actions

# each action invocation has an edge leading to the agent node.
workflow.add_edge('action', 'agent')

# Add flow logic with conditional edge.
workflow.add_conditional_edges(
    # first parameter is the starting node for the edge
    "agent",
    # the second parameter specifies the logic function to be run
    # to determine which node the edge will point to given the state.
    should_continue,

    # third parameter defines the mapping between the logic function
    # output and the nodes on the graph
    # For each possible output of the logic function there must be a valid node.
    {
        # If 'continue' we proceed to the action node.
        "CONTINUE": "action",
        # Otherwise we end invocations with the END node.
        "END": END
    }
)

DB_URI = "postgres://postgres:postgres@localhost:5432/ps?sslmode=disable"
with PostgresSaver.from_conn_string(DB_URI) as checkpointer:
    checkpointer.setup()
    # Finally, compile the graph!
    # This compiles it into a LangChain Runnable,
    app = workflow.compile(checkpointer=checkpointer)

    inputs = {"input": {"role": "human", "content": "give me 1+1 and then 2 times 2"}}
    config = {"configurable": {"thread_id": "1"}}

    for s in app.stream(inputs, config=config):
        print(list(s.values())[0])
        print("----")
```

### Error Message and Stack Trace (if applicable)

```shell
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1729160303.393526 30209994 fork_posix.cc:77] Other threads are currently calling into gRPC, skipping fork() handlers
Traceback (most recent call last):
  File "/Users/marty/develop/jump-tech/predicate-search/predicate-search-api/scripts/vertex/chat_basic.py", line 171, in <module>
    for s in app.stream(inputs, config=config):
  File "/Users/marty/Library/Caches/pypoetry/virtualenvs/predicate-search-api-p3WC1ATU-py3.11/lib/python3.11/site-packages/langgraph/pregel/__init__.py", line 1307, in stream
    for _ in runner.tick(
  File "/Users/marty/Library/Caches/pypoetry/virtualenvs/predicate-search-api-p3WC1ATU-py3.11/lib/python3.11/site-packages/langgraph/pregel/runner.py", line 56, in tick
    run_with_retry(t, retry_policy)
  File "/Users/marty/Library/Caches/pypoetry/virtualenvs/predicate-search-api-p3WC1ATU-py3.11/lib/python3.11/site-packages/langgraph/pregel/retry.py", line 29, in run_with_retry
    task.proc.invoke(task.input, config)
  File "/Users/marty/Library/Caches/pypoetry/virtualenvs/predicate-search-api-p3WC1ATU-py3.11/lib/python3.11/site-packages/langgraph/utils/runnable.py", line 410, in invoke
    input = context.run(step.invoke, input, config, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marty/Library/Caches/pypoetry/virtualenvs/predicate-search-api-p3WC1ATU-py3.11/lib/python3.11/site-packages/langgraph/utils/runnable.py", line 184, in invoke
    ret = context.run(self.func, input, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marty/develop/jump-tech/predicate-search/predicate-search-api/scripts/vertex/chat_basic.py", line 78, in run_tool_agent
    agent_outcome = tool_runnable.invoke(state)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marty/Library/Caches/pypoetry/virtualenvs/predicate-search-api-p3WC1ATU-py3.11/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 3024, in invoke
    input = context.run(step.invoke, input, config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marty/Library/Caches/pypoetry/virtualenvs/predicate-search-api-p3WC1ATU-py3.11/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 5354, in invoke
    return self.bound.invoke(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/marty/Library/Caches/pypoetry/virtualenvs/predicate-search-api-p3WC1ATU-py3.11/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 286, in invoke
    self.generate_prompt(
  File "/Users/marty/Library/Caches/pypoetry/virtualenvs/predicate-search-api-p3WC1ATU-py3.11/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 786, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marty/Library/Caches/pypoetry/virtualenvs/predicate-search-api-p3WC1ATU-py3.11/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 643, in generate
    raise e
  File "/Users/marty/Library/Caches/pypoetry/virtualenvs/predicate-search-api-p3WC1ATU-py3.11/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 633, in generate
    self._generate_with_cache(
  File "/Users/marty/Library/Caches/pypoetry/virtualenvs/predicate-search-api-p3WC1ATU-py3.11/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 851, in _generate_with_cache
    result = self._generate(
             ^^^^^^^^^^^^^^^
  File "/Users/marty/Library/Caches/pypoetry/virtualenvs/predicate-search-api-p3WC1ATU-py3.11/lib/python3.11/site-packages/langchain_google_vertexai/chat_models.py", line 1184, in _generate
    return self._generate_gemini(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marty/Library/Caches/pypoetry/virtualenvs/predicate-search-api-p3WC1ATU-py3.11/lib/python3.11/site-packages/langchain_google_vertexai/chat_models.py", line 1340, in _generate_gemini
    request = self._prepare_request_gemini(messages=messages, stop=stop, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marty/Library/Caches/pypoetry/virtualenvs/predicate-search-api-p3WC1ATU-py3.11/lib/python3.11/site-packages/langchain_google_vertexai/chat_models.py", line 1254, in _prepare_request_gemini
    system_instruction, contents = _parse_chat_history_gemini(messages)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marty/Library/Caches/pypoetry/virtualenvs/predicate-search-api-p3WC1ATU-py3.11/lib/python3.11/site-packages/langchain_google_vertexai/chat_models.py", line 437, in _parse_chat_history_gemini
    raise ValueError(
ValueError: Unexpected message with type <class 'langchain_core.messages.base.BaseMessage'> at the position 2.

Process finished with exit code 1
```

### Description

First run of the script works fine but during the second run I get the above error. Following through the debugger it seems to be something with the `system_prompt`. 

```python
system_prompt = """ You are a mathematical assistant.
        Use your tools to answer questions. If you do not have a tool to
        answer the question, say so. """

tool_calling_prompt = ChatPromptTemplate.from_messages(
    [
        ("system", system_prompt),
        MessagesPlaceholder("chat_history", optional=True),
        ("human", "{input}"),
        MessagesPlaceholder("agent_scratchpad"),
    ]
)
```

From the history which is passed into `langchain_core/messages/utils.py._convert_to_message`

```
SystemMessage(content=' You are a mathematical assistant.\n        Use your tools to answer questions. If you do not have a tool to\n        answer the question, say so. ', additional_kwargs={}, response_metadata={})
HumanMessage(content="{'role': 'human', 'content': 'give me 1+1 and then 2 times 2'}", additional_kwargs={}, response_metadata={})
BaseMessage(content=['I am a mathematical assistant. I can help you with addition, multiplication, and squaring of numbers. \n...': 129, 'cached_content_token_count': 0}, 'finish_reason': 'STOP'}, type='ai', id='run-1eb29ec4-c145-4678-8a92-4ea342f9c114-0')
ToolMessage(content="{'messages': [ToolMessage(content='5', name='add', tool_call_id='55567e66-746f-4319-a759-70afae8dff2b')]}", tool_call_id='55567e66-746f-4319-a759-70afae8dff2b')
BaseMessage(content="I am a mathematical assistant. I can help you with addition, multiplication, and squaring of numbers. \n\...': 250, 'cached_content_token_count': 0}, 'finish_reason': 'STOP'}, type='ai', id='run-35657ec3-932e-4067-abd0-cb40c469258c-0')
ToolMessage(content="{'messages': [ToolMessage(content='5', name='add', tool_call_id='59571307-a78e-43ce-b107-740a00d21d42')]}", tool_call_id='59571307-a78e-43ce-b107-740a00d21d42')
```

The script above was taken basically verbatim from https://medium.com/@ipeksahbazoglu/building-a-multi-tool-agent-with-langgraph-and-google-vertex-ai-e37aa6d41265

I've deleted the tables and tried running again with the same results.

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6030
> Python Version:  3.11.6 (v3.11.6:8b6ee5ba3b, Oct  2 2023, 11:18:21) [Clang 13.0.0 (clang-1300.0.29.30)]

Package Information
-------------------
> langchain_core: 0.3.10
> langchain: 0.3.3
> langchain_community: 0.3.2
> langsmith: 0.1.135
> langchain_google_vertexai: 2.0.5
> langchain_openai: 0.2.2
> langchain_text_splitters: 0.3.0
> langgraph: 0.2.38

Optional packages not installed
-------------------------------
> langserve

Other Dependencies
------------------
> aiohttp: 3.10.10
> anthropic[vertexai]: Installed. No version info available.
> async-timeout: Installed. No version info available.
> dataclasses-json: 0.6.7
> google-cloud-aiplatform: 1.69.0
> google-cloud-storage: 2.18.2
> httpx: 0.27.2
> httpx-sse: 0.4.0
> jsonpatch: 1.33
> langchain-mistralai: Installed. No version info available.
> langgraph-checkpoint: 2.0.1
> langgraph-sdk: 0.1.33
> numpy: 1.26.4
> openai: 1.51.2
> orjson: 3.10.7
> packaging: 24.1
> pydantic: 2.9.2
> pydantic-settings: 2.5.2
> PyYAML: 6.0.2
> requests: 2.32.3
> requests-toolbelt: 1.0.0
> SQLAlchemy: 2.0.35
> tenacity: 8.5.0
> tiktoken: 0.8.0
> typing-extensions: 4.12.2

**Comment by delorenzotommaso** [comment]
@martyphee I am getting the same error. Were you able to solve it?

**Comment by martyphee** [comment]
I never did. I moved to `ChatOpenAI` for my conversation.

Just seems like a lot of the google code is preview and was having a lot of issues getting things to work properly. Might revisit if I move away from langchain.

**Comment by MarcosEich** [comment]
I'm not sure it is your problem but I got an error while trying to run a similar chatbot that ended up having two messages with type system using Gemini. I fixed the issue by ensuring only one message with type system was sent to Gemini.

**Comment by brianmuse** [comment]
This is still an issue for me, and the fix suggested here https://github.com/langchain-ai/langchain/issues/27052#issuecomment-2389602212 does fix it.
