### ISSUE TITLE
AzureSearch error

### ISSUE THREAD

**Issue by codenamics** [langchain-ai/langchain#27643]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
index_name: str = "langchain-vector-demo"
vector_store: AzureSearch = AzureSearch(
    azure_search_endpoint=vector_store_address,
    azure_search_key=vector_store_password,
    index_name=index_name,
    embedding_function=embeddings.embed_query,
)
```

### Error Message and Stack Trace (if applicable)

Exception ignored in: <function AzureSearch.__del__ at 0x000002B588070FE0>                                      
Traceback (most recent call last):
  File "C:\Users\n\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_community\vectorstores\azuresearch.py", line 393, in __del__
  File "C:\Users\n\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 761, in get_event_loop_policy
  File "C:\Users\n\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 754, in _init_event_loop_policy
ImportError: sys.meta_path is None, Python is likely shutting down

### Description

Made everything as here:

https://python.langchain.com/docs/integrations/vectorstores/azuresearch/

when calling it i get error like above

### System Info

python 3.12
langchain latest

**Comment by keenborder786** [comment]
It has nothing to do with Langchain, their is something wrong with your python environment. Or how you are starting the asyncio event loop. Can you share code so I can help you better

**Comment by paprocki-r** [comment]
related https://github.com/langchain-ai/langchain/issues/27511

**Comment by thecaptain2000** [comment]
The issue is still relevant, I have created the environment today in two different systems using conda  and these ar the packages I install:
azure-storage
azure-storage-blob
azure-identity
azure-search-documents
langchain-openai
langchain-community
langchain-text-splitters
python-dotenv
streamlit
streamlit-chat
unstructured

model = "gpt-4o-mini"

#vector_store_address: str = f"https://${os.environ.get('AZURE_COGNITIVE_SEARCH_SERVICE_NAME')}.search.windows.net"
vector_store_address: str = f"https://{os.environ.get('AZURE_COGNITIVE_SEARCH_SERVICE_NAME')}.search.windows.net"


os.environ["OPENAI_API_KEY"]=os.getenv("MYOPENAI_API_KEY")

#embeddings: OpenAIEmbeddings = OpenAIEmbeddings(deployment=model, chunk_size=1)
embeddings  = OpenAIEmbeddings(  deployment=model, 
                                 chunk_size=1000,
                                 openai_api_key=os.environ["OPENAI_API_KEY"]
)

index_name: str = "langchain-vector-demo"
#



def sync_embed_query(text):
    return asyncio.run(embeddings.aembed_query(text))

vector_store = AzureSearch(
    azure_search_endpoint=vector_store_address,
    azure_search_key=os.environ.get("AZURE_COGNITIVE_SEARCH_API_KEY"),
    index_name=index_name,
#    embedding_function=embeddings.embed_query,
     embedding_function=embeddings.embed_query,
    
)

loader = AzureBlobStorageContainerLoader(
    conn_str=os.environ.get("AZURE_CONN_STRING"),
    container=os.environ.get("CONTAINER_NAME"),
)
documents = loader.load()

text_splitter = CharacterTextSplitter(chunk_size=150, chunk_overlap=20)
docs = text_splitter.split_documents(documents)

returns an error:
Exception ignored in: <function AzureSearch.__del__ at 0x77dff6bee4c0>
Traceback (most recent call last):
  File "/home/renato/miniconda3/envs/azure/lib/python3.9/site-packages/langchain_community/vectorstores/azuresearch.py", line 422, in __del__
  File "/home/renato/miniconda3/envs/azure/lib/python3.9/asyncio/events.py", line 725, in get_event_loop_policy
  File "/home/renato/miniconda3/envs/azure/lib/python3.9/asyncio/events.py", line 718, in _init_event_loop_policy
ImportError: sys.meta_path is None, Python is likely shutting down


the result is the metadata is loaded into the index WITHOUT the embeddigs.

**Comment by ivanvaccarics** [comment]
The only workaround i found is to encapsulate the code inside an async function, any news on this topic?

**Comment by thecaptain2000** [comment]
no and the workaround does not work as I do not see the  embedding vector
value in the vector DB


Il giorno mer 2 apr 2025 alle ore 17:02 Ivan Vaccari <
***@***.***> ha scritto:
