### ISSUE TITLE
Multi-agent supervisor example not working with ChatOllama, breaks when attempting to use two system messages. Must be an issue with using two system prompts in ChatOllama.

### ISSUE THREAD

**Issue by aguilarcarboni** [langchain-ai/langchain#27656]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
python
from langchain_openai import ChatOpenAI
from langchain_ollama import ChatOllama
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.messages import SystemMessage, HumanMessage
from langchain_core.output_parsers import StrOutputParser
from typing import Literal
from pydantic import BaseModel

class routeResponse(BaseModel):
    next: Literal["FINISH", "Researcher", "Coder"]

llm = ChatOpenAI(model="gpt-4o-mini", api_key='')
llm = ChatOllama(model="llama3.2:latest")

members = ["Researcher", "Coder"]
system_prompt = (
    "You are a supervisor tasked with managing a conversation between the"
    " following workers:  {members}. Given the following user request,"
    " respond with the worker to act next. Each worker will perform a"
    " task and respond with their results and status. When finished,"
    " respond with FINISH."
)
# Our team supervisor is an LLM node. It just picks the next agent to process
# and decides when the work is completed
options = ["FINISH"] + members

template = ChatPromptTemplate.from_messages(
    [
        SystemMessage(content=system_prompt),
        MessagesPlaceholder(variable_name="messages"),
        SystemMessage(content="Given the conversation above, who should act next? Or should we FINISH? Select one of: {options}"),
    ]
).partial(options=str(["FINISH", "Researcher", "Coder"]), members=", ".join(members))

structured_llm = llm.with_structured_output(routeResponse)
supervisor_chain = template | structured_llm
result = supervisor_chain.invoke({"messages": [HumanMessage(content="What is 9 + 10>")]})
print(result)

### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "/Users/andres/Documents/Projects/Athena/app/frameworks/multiagent_supervisor.py", line 112, in <module>
    for s in graph.stream(
  File "/Users/andres/.pyenv/versions/3.11.9/lib/python3.11/site-packages/langgraph/pregel/__init__.py", line 1315, in stream
    for _ in runner.tick(
  File "/Users/andres/.pyenv/versions/3.11.9/lib/python3.11/site-packages/langgraph/pregel/runner.py", line 56, in tick
    run_with_retry(t, retry_policy)
  File "/Users/andres/.pyenv/versions/3.11.9/lib/python3.11/site-packages/langgraph/pregel/retry.py", line 29, in run_with_retry
    task.proc.invoke(task.input, config)
  File "/Users/andres/.pyenv/versions/3.11.9/lib/python3.11/site-packages/langgraph/utils/runnable.py", line 412, in invoke
    input = context.run(step.invoke, input, config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andres/.pyenv/versions/3.11.9/lib/python3.11/site-packages/langgraph/utils/runnable.py", line 184, in invoke
    ret = context.run(self.func, input, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andres/.pyenv/versions/3.11.9/lib/python3.11/site-packages/langgraph/graph/graph.py", line 93, in _route
    result = self.path.invoke(value, config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andres/.pyenv/versions/3.11.9/lib/python3.11/site-packages/langgraph/utils/runnable.py", line 176, in invoke
    ret = context.run(self.func, input, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andres/Documents/Projects/Athena/app/frameworks/multiagent_supervisor.py", line 105, in <lambda>
    workflow.add_conditional_edges("supervisor", lambda x: x['next'], conditional_map)
                                                           ~^^^^^^^^
KeyError: 'next'

### Description

Running the code above produces Error message when ran with ChatOllama, while if run with ChatOpenAI, it works no problem. Showing minimal reproducible version of Multi-agent example. Interestingly, if changing the second system message in the template to a HumanMessage, the example works but it works half way anyways. Must be an issue with using two system prompts in ChatOllama.

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 24.1.0: Thu Oct 10 21:02:26 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T8122
> Python Version:  3.11.9 (main, Jul 15 2024, 14:34:44) [Clang 15.0.0 (clang-1500.3.9.4)]

Package Information
-------------------
> langchain_core: 0.3.12
> langchain: 0.3.4
> langchain_community: 0.3.3
> langsmith: 0.1.137
> langchain_chroma: 0.1.4
> langchain_experimental: 0.3.2
> langchain_ollama: 0.2.0
> langchain_openai: 0.2.3
> langchain_text_splitters: 0.3.0
> langgraph: 0.2.39

Optional packages not installed
-------------------------------
> langserve

Other Dependencies
------------------
> aiohttp: 3.9.5
> async-timeout: 4.0.3
> chromadb: 0.5.15
> dataclasses-json: 0.6.7
> fastapi: 0.111.0
> httpx: 0.27.0
> jsonpatch: 1.33
> langgraph-checkpoint: 2.0.2
> langgraph-sdk: 0.1.34
> numpy: 1.26.4
> ollama: 0.3.3
> openai: 1.52.2
> orjson: 3.10.7
> packaging: 23.2
> pydantic: 2.9.2
> pydantic-settings: 2.5.2
> PyYAML: 6.0.2
> requests: 2.32.3
> requests-toolbelt: 1.0.0
> SQLAlchemy: 2.0.35
> tenacity: 8.5.0
> tiktoken: 0.7.0
> typing-extensions: 4.12.2


EDIT: Modified code as I pasted wrong version

**Comment by EmPajak21** [comment]
I also have the same issue and error message

**Comment by aguilarcarboni** [comment]
Has to do with Ollama's API and how it handle's system prompts, not langchain.
