### ISSUE TITLE
create_react_agent will reset max_length = 20

### ISSUE THREAD

**Issue by my36z** [langchain-ai/langchain#27699]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
hf = HuggingFacePipeline.from_model_id(
    model_id="Qwen/Qwen2.5-3B-Instruct-AWQ",
    task="text-generation",
    device=0,
    pipeline_kwargs={"max_new_tokens": 512},
)

agent = create_react_agent(hf, tools, custom_prompt)
agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True")
agent_executor.invoke({"input": conten})
```

### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "D:\AI\anaconda3\envs\autotest\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "D:\AI\anaconda3\envs\autotest\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "D:\AI\anaconda3\envs\autotest\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\anaconda3\envs\autotest\Lib\site-packages\transformers\generation\utils.py", line 2068, in generate
    self._validate_generated_length(generation_config, input_ids_length, has_default_max_length)
  File "D:\AI\anaconda3\envs\autotest\Lib\site-packages\transformers\generation\utils.py", line 1383, in _validate_generated_length
    raise ValueError(
ValueError: Input length of input_ids is 617, but `max_length` is set to 20. This can lead to unexpected behavior. You should consider increasing `max_length` or, better yet, setting `max_new_tokens`.

### Description

but if use initialize_agent ,it work.

### System Info

System Information
------------------
> OS:  Windows
> OS Version:  10.0.19045
> Python Version:  3.11.10 | packaged by Anaconda, Inc. | (main, Oct  3 2024, 07:22:26) [MSC v.1929 64 bit (AMD64)]

Package Information
-------------------
> langchain_core: 0.3.12
> langchain: 0.3.4
> langchain_community: 0.3.3
> langsmith: 0.1.137
> langchain_huggingface: 0.1.0
> langchain_text_splitters: 0.3.0

Optional packages not installed
-------------------------------
> langgraph
> langserve

Other Dependencies
------------------
> aiohttp: 3.10.10
> async-timeout: Installed. No version info available.
> dataclasses-json: 0.6.7
> httpx: 0.27.2
> huggingface-hub: 0.26.1
> jsonpatch: 1.33
> numpy: 1.26.4
> orjson: 3.10.10
> packaging: 24.1
> pydantic: 2.9.2
> pydantic-settings: 2.6.0
> PyYAML: 6.0.2
> requests: 2.32.3
> requests-toolbelt: 1.0.0
> sentence-transformers: 3.2.1
> SQLAlchemy: 2.0.36
> tenacity: 9.0.0
> tokenizers: 0.20.1
> transformers: 4.46.0
> typing-extensions: 4.12.2

**Comment by keenborder786** [comment]
Please set up `max_length` as follow:
```python
hf = HuggingFacePipeline.from_model_id(
    model_id="Qwen/Qwen2.5-3B-Instruct-AWQ",
    task="text-generation",
    device=0,
    pipeline_kwargs={"max_length": 2000},
)
```

**Comment by my36z** [comment]
```
hf = HuggingFacePipeline.from_model_id(
    model_id="Qwen/Qwen2.5-3B-Instruct-AWQ",
    task="text-generation",
    device=0,
    pipeline_kwargs={"max_length": 1000},
)
```

```
    hf = HuggingFacePipeline.from_model_id(
        model_id="Qwen/Qwen2.5-3B-Instruct-AWQ",
        task="text-generation",
        device=0,
        pipeline_kwargs={"max_length": 2048, "max_new_tokens": 2048},
    )
```
both error. I think create_react_agent  or agent_executor.invoke reset the max_length.

**Comment by nai-kon** [comment]
I have a same problem. This problem seems fatal.
Did you solve this?

**Comment by nai-kon** [comment]
@my36z  @keenborder786 
I have the same problem.

When I debugged `generate()` of `site-packages/transformers/generation/utils.py`, `generation_config` argument was `None`. 
And this causes max_length = 20 (default value when generation_config is None)

```python
    @torch.no_grad()
    def generate(
        self,
        inputs: Optional[torch.Tensor] = None,
        generation_config: Optional[GenerationConfig] = None,
```
-> generation_config is None and this causes max_length=20 (default value).

On the other hand, when calling without create_react_agent(), 
the correct generation config value (max_new_tokens=512) was passed.

```python
hf = HuggingFacePipeline.from_model_id(
    model_id="Qwen/Qwen2.5-3B-Instruct-AWQ",
    task="text-generation",
    device=0,
    pipeline_kwargs={"max_new_tokens": 512},
)
hf.invoke(content)
```


It seems that the generation_setting is not passed when using create_react_agent().
