### ISSUE TITLE
Error when loading pdf with PyPDFLoader

### ISSUE THREAD

**Issue by PabloVD** [langchain-ai/langchain#27770]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from langchain_community.document_loaders import PyPDFLoader
import requests
from pathlib import Path

# Get data from url
url = 'https://camels.readthedocs.io/_/downloads/en/latest/pdf/'
r = requests.get(url, stream=True)
document_path = Path('data.pdf')

document_path.write_bytes(r.content)
loader = PyPDFLoader(document_path)
documents = loader.load()
```

### Error Message and Stack Trace (if applicable)

```
Traceback (most recent call last):
  File "/home/tda/GenAICourse/RAG/ragbot_langchain/loadpdf.py", line 12, in <module>
    documents = loader.load()
  File "/home/tda/miniconda3/envs/ragbot2/lib/python3.10/site-packages/langchain_core/document_loaders/base.py", line 31, in load
    return list(self.lazy_load())
  File "/home/tda/miniconda3/envs/ragbot2/lib/python3.10/site-packages/langchain_community/document_loaders/pdf.py", line 257, in lazy_load
    yield from self.parser.parse(blob)
  File "/home/tda/miniconda3/envs/ragbot2/lib/python3.10/site-packages/langchain_core/document_loaders/base.py", line 127, in parse
    return list(self.lazy_parse(blob))
  File "/home/tda/miniconda3/envs/ragbot2/lib/python3.10/site-packages/langchain_community/document_loaders/parsers/pdf.py", line 124, in lazy_parse
    yield from [
  File "/home/tda/miniconda3/envs/ragbot2/lib/python3.10/site-packages/langchain_community/document_loaders/parsers/pdf.py", line 126, in <listcomp>
    page_content=_extract_text_from_page(page=page)
  File "/home/tda/miniconda3/envs/ragbot2/lib/python3.10/site-packages/langchain_community/document_loaders/parsers/pdf.py", line 117, in _extract_text_from_page
    return page.extract_text(
  File "/home/tda/miniconda3/envs/ragbot2/lib/python3.10/site-packages/pypdf/_page.py", line 2393, in extract_text
    return self._extract_text(
  File "/home/tda/miniconda3/envs/ragbot2/lib/python3.10/site-packages/pypdf/_page.py", line 1868, in _extract_text
    cmaps[f] = build_char_map(f, space_width, obj)
  File "/home/tda/miniconda3/envs/ragbot2/lib/python3.10/site-packages/pypdf/_cmap.py", line 33, in build_char_map
    font_subtype, font_halfspace, font_encoding, font_map = build_char_map_from_dict(
  File "/home/tda/miniconda3/envs/ragbot2/lib/python3.10/site-packages/pypdf/_cmap.py", line 56, in build_char_map_from_dict
    encoding, map_dict = get_encoding(ft)
  File "/home/tda/miniconda3/envs/ragbot2/lib/python3.10/site-packages/pypdf/_cmap.py", line 129, in get_encoding
    map_dict, int_entry = _parse_to_unicode(ft)
  File "/home/tda/miniconda3/envs/ragbot2/lib/python3.10/site-packages/pypdf/_cmap.py", line 212, in _parse_to_unicode
    return _type1_alternative(ft, map_dict, int_entry)
  File "/home/tda/miniconda3/envs/ragbot2/lib/python3.10/site-packages/pypdf/_cmap.py", line 530, in _type1_alternative
    map_dict[chr(i)] = v
UnboundLocalError: local variable 'v' referenced before assignment
```

### Description

I'm trying to load a pdf with PyPDFLoader for a RAG application but it raises an error. I tried both with a local file or requesting it from the url like in the example. It does not happen with other pdf files I tried.

### System Info

```
System Information
------------------
> OS:  Linux
> OS Version:  #134~20.04.1-Ubuntu SMP Tue Oct 1 15:27:33 UTC 2024
> Python Version:  3.10.0 (default, Mar  3 2022, 09:58:08) [GCC 7.5.0]

Package Information
-------------------
> langchain_core: 0.3.14
> langchain: 0.3.5
> langchain_community: 0.3.3
> langsmith: 0.1.138
> langchain_chroma: 0.1.4
> langchain_mistralai: 0.2.0
> langchain_openai: 0.2.4
> langchain_text_splitters: 0.3.1

Optional packages not installed
-------------------------------
> langgraph
> langserve

Other Dependencies
------------------
> aiohttp: 3.10.10
> async-timeout: 4.0.3
> chromadb: 0.5.16
> dataclasses-json: 0.6.7
> fastapi: 0.115.4
> httpx: 0.27.2
> httpx-sse: 0.4.0
> jsonpatch: 1.33
> numpy: 1.26.4
> openai: 1.53.0
> orjson: 3.10.10
> packaging: 24.1
> pydantic: 2.9.2
> pydantic-settings: 2.6.0
> PyYAML: 6.0.2
> requests: 2.32.3
> requests-toolbelt: 1.0.0
> SQLAlchemy: 2.0.36
> tenacity: 9.0.0
> tiktoken: 0.8.0
> tokenizers: 0.20.1
> typing-extensions: 4.12.2
```

**Comment by PabloVD** [comment]
Seems to be a problem related to the last pypdf release 5.1.0. Uninstalling and installing version 5.0.1 fixed the issue.

**Comment by stefan6419846** [comment]
*pypdf* maintainer here (although I usually do not look in the issues of the *langchain* repository): We still have an open PR (https://github.com/py-pdf/pypdf/pull/3029) to fix this, but although this issue here is the third report I am reading, nobody has been able to provide me a file which would show this behavior to keep this from happening in the future.

I appreciate anyone who is able to provide a reproducing file (either publicly or by private e-mail). The above link does not raise for me with the latest *pypdf* code, but apparently it has been changed after the initial report on 2024-11-29.

**Comment by PabloVD** [comment]
I tried with 5.2.0 and it worked fine, yes! Great that the problem was already solved! :D
Many thanks!

**Comment by sorooshsorkhani** [comment]
I had the same issue with `pydf==5.3.0`. Changing it to `pydf==5.2.0` solved it. The attached file is the file that caused this error for me.

[2022 - Microbial Community-Level Physiological Profiles and Genetic Prokaryotic Structure of Burned Soils Under Mediterranean Sclerophyll Forests in Central Chile.pdf](https://github.com/user-attachments/files/18773895/2022.-.Microbial.Community-Level.Physiological.Profiles.and.Genetic.Prokaryotic.Structure.of.Burned.Soils.Under.Mediterranean.Sclerophyll.Forests.in.Central.Chile.pdf)

**Comment by stefan6419846** [comment]
5.3.0 should have fixed this and running this locally did not yield any issues. Please provide some more details if you are indeed still experiencing exceptions with the latest release.

**Comment by sorooshsorkhani** [comment]
I apologize, it's fixed now.
Previously, to fix the issue, I just upgraded my package to `5.3.0` but the problem didn't get fixed.
I uninstalled and installed `5.2.0`, then it was fixed.

Now, to test it again, I uninstalled `5.2.0` and installed `5.3.0` and it's fixed.
