### ISSUE TITLE
Windows 11 - langchain_huggingface/sentence-transformers unable to run

### ISSUE THREAD

**Issue by codenamics** [langchain-ai/langchain#27785]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
from langchain_huggingface.embeddings import HuggingFaceEmbeddings

model_name = "mixedbread-ai/mxbai-embed-large-v1"
hf_embeddings = HuggingFaceEmbeddings(
    model_name=model_name,
)
texts = ["Hello, world!", "How are you?"]
print(hf_embeddings.embed_documents(texts))
```

### Error Message and Stack Trace (if applicable)

```
Traceback (most recent call last):
  File "C:\Users\x\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_huggingface\embeddings\huggingface.py", line 52, in __init__    
    import sentence_transformers  # type: ignore[import]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentence_transformers\__init__.py", line 10, in <module>
    from sentence_transformers.cross_encoder.CrossEncoder import CrossEncoder
  File "C:\Users\x\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentence_transformers\cross_encoder\__init__.py", line 3, in <module>     
    from .CrossEncoder import CrossEncoder
  File "C:\Users\x\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentence_transformers\cross_encoder\CrossEncoder.py", line 10, in <module>
    from torch import Tensor, nn
  File "C:\Users\x\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\__init__.py", line 1, in <module>
    from .module import Module
  File "C:\Users\x\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 8, in <module>
    from torch._prims_common import DeviceLikeType
ModuleNotFoundError: No module named 'torch._prims_common'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\x\Desktop\Python\huggingface_embeddings\app.py", line 4, in <module>
    hf_embeddings = HuggingFaceEmbeddings(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_huggingface\embeddings\huggingface.py", line 54, in __init__    
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
```

### Description

pip install langchain
pip install huggingface_hub
pip install sentence_transformers
pip install langchain_huggingface

All latest versions installed on windows 11 when i run above code to get embeddings i got error stack as posted

BUT on linux works

### System Info

Windows 11 - not working
Linux - working

all packages latests version

**Comment by anujsahanids3** [comment]
I am facing the same issue !!
