### ISSUE TITLE
langchain_ollama.embeddings.OllamaEmbeddings throws "invalid input type" error with ChromaDB 

### ISSUE THREAD

**Issue by simingy** [langchain-ai/langchain#27831]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

``` python
from langchain_ollama import OllamaLLM
from langchain_core.output_parsers import StrOutputParser

from langchain_chroma import Chroma as LangchainChroma
from langchain_ollama.embeddings import OllamaEmbeddings
embed_model = OllamaEmbeddings(model='mxbai-embed-large')
vector_store = LangchainChroma(collection_name = 'some-collection, 
                               embedding_function = embed_model)
llm = OllamaLLM(model='llama3')
chain = (
    {
        "docs": vector_store.as_retriever()
        "question": RunnablePassthrough(),
    }
    | SOME_PROMPT
    | llm
    | StrOutputParser()
)
```

### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "/path/lib/python3.10/site-packages/chainlit/utils.py", line 44, in wrapper
    return await user_function(**params_values)
  File "/path/lib/python3.10/site-packages/chainlit/callbacks.py", line 118, in with_parent_id
    await func(message)
  File "/path/rag_poc/main.py", line 25, in on_message
    async for chunk in runnable.astream(
  File "/path/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 5537, in astream
    async for item in self.bound.astream(
  File "/path/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 3432, in astream
    async for chunk in self.atransform(input_aiter(), config, **kwargs):
  File "/path/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 3415, in atransform
    async for chunk in self._atransform_stream_with_config(
  File "/path/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2308, in _atransform_stream_with_config
    chunk = cast(Output, await py_anext(iterator))
  File "/path/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 3385, in _atransform
    async for output in final_pipeline:
  File "/path/lib/python3.10/site-packages/langchain_core/output_parsers/transform.py", line 84, in atransform
    async for chunk in self._atransform_stream_with_config(
  File "/path/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2261, in _atransform_stream_with_config
    final_input: Optional[Input] = await py_anext(input_for_tracing, None)
  File "/path/lib/python3.10/site-packages/langchain_core/utils/aiter.py", line 76, in anext_impl
    return await __anext__(iterator)
  File "/path/lib/python3.10/site-packages/langchain_core/utils/aiter.py", line 125, in tee_peer
    item = await iterator.__anext__()
  File "/path/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1455, in atransform
    async for ichunk in input:
  File "/path/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1455, in atransform
    async for ichunk in input:
  File "/path/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 3916, in atransform
    async for chunk in self._atransform_stream_with_config(
  File "/path/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2308, in _atransform_stream_with_config
    chunk = cast(Output, await py_anext(iterator))
  File "/path/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 3903, in _atransform
    chunk = AddableDict({step_name: task.result()})
  File "/path/.pyenv/versions/3.10.14/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/path/.pyenv/versions/3.10.14/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/path/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 3886, in get_next_chunk
    return await py_anext(generator)
  File "/path/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 3415, in atransform
    async for chunk in self._atransform_stream_with_config(
  File "/path/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2308, in _atransform_stream_with_config
    chunk = cast(Output, await py_anext(iterator))
  File "/path/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 3385, in _atransform
    async for output in final_pipeline:
  File "/path/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 4943, in atransform
    async for output in self._atransform_stream_with_config(
  File "/path/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2261, in _atransform_stream_with_config
    final_input: Optional[Input] = await py_anext(input_for_tracing, None)
  File "/path/lib/python3.10/site-packages/langchain_core/utils/aiter.py", line 76, in anext_impl
    return await __anext__(iterator)
  File "/path/lib/python3.10/site-packages/langchain_core/utils/aiter.py", line 125, in tee_peer
    item = await iterator.__anext__()
  File "/path/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1473, in atransform
    async for output in self.astream(final, config, **kwargs):
  File "/path/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1018, in astream
    yield await self.ainvoke(input, config, **kwargs)
  File "/path/lib/python3.10/site-packages/langchain_core/retrievers.py", line 317, in ainvoke
    raise e
  File "/path/lib/python3.10/site-packages/langchain_core/retrievers.py", line 310, in ainvoke
    result = await self._aget_relevant_documents(
  File "/path/lib/python3.10/site-packages/langchain_core/vectorstores/base.py", line 1101, in _aget_relevant_documents
    docs = await self.vectorstore.asimilarity_search(
  File "/path/lib/python3.10/site-packages/langchain_core/vectorstores/base.py", line 651, in asimilarity_search
    return await run_in_executor(None, self.similarity_search, query, k=k, **kwargs)
  File "/path/lib/python3.10/site-packages/langchain_core/runnables/config.py", line 588, in run_in_executor
    return await asyncio.get_running_loop().run_in_executor(
  File "/path/.pyenv/versions/3.10.14/lib/python3.10/asyncio/futures.py", line 285, in __await__
    yield self  # This tells Task to wait for completion.
  File "/path/.pyenv/versions/3.10.14/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/path/.pyenv/versions/3.10.14/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/path/.pyenv/versions/3.10.14/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/path/lib/python3.10/site-packages/langchain_core/runnables/config.py", line 579, in wrapper
    return func(*args, **kwargs)
  File "/path/lib/python3.10/site-packages/langchain_chroma/vectorstores.py", line 582, in similarity_search
    docs_and_scores = self.similarity_search_with_score(
  File "/path/lib/python3.10/site-packages/langchain_chroma/vectorstores.py", line 679, in similarity_search_with_score
    query_embedding = self._embedding_function.embed_query(query)
  File "/path/lib/python3.10/site-packages/langchain_ollama/embeddings.py", line 164, in embed_query
    return self.embed_documents([text])[0]
  File "/path/lib/python3.10/site-packages/langchain_ollama/embeddings.py", line 159, in embed_documents
    embedded_docs = self._client.embed(self.model, texts)["embeddings"]
  File "/path/lib/python3.10/site-packages/ollama/_client.py", line 262, in embed
    return self._request(
  File "/path/lib/python3.10/site-packages/ollama/_client.py", line 75, in _request
    raise ResponseError(e.response.text, e.response.status_code) from None
ollama._types.ResponseError: invalid input type

### Description

```python
from langchain_ollama.embeddings import OllamaEmbeddings
from langchain_community.embeddings import OllamaEmbeddings
```

It seems like the newer version of `OllamaEmbeddings` have issues with ChromaDB - throws exception. Swapping to the older version continues to work

Doing some digging i found out that, with the same code but swapping just the embedding class from legacy to new, the submitted api to Ollama's `/api/embed` is different:

with: `langchain_community.embeddings.OllamaEmbeddings` the legacy code, you get the following payload:

```
{'json': {'model': 'mxbai-embed-large', 
          'prompt': "query: {'input': 'What is OTEL SIP, what are its features and benefits?'}", 
          'options': {'mirostat': None, 'mirostat_eta': None, 'mirostat_tau': None, 'num_ctx': None, 'num_gpu': None, 'num_thread': None, 'repeat_last_n': None, 'repeat_penalty': None, 'temperature': None, 'stop': None, 'tfs_z': None, 'top_k': None, 'top_p': None}}}
```
-> this works fine

With `langchain_ollama.embeddings.OllamaEmbeddings` - the newer one, you get 

```
{'json': {'input': [{'input': 'Some question'}],
          'keep_alive': None,
          'model': 'mxbai-embed-large',
          'options': {},
          'truncate': True}}
```
-> this blows up
notice the different in `'input'` key vs `'prompt'`

### System Info

langchain                                0.3.6
langchain-chroma                         0.1.4
langchain-cli                            0.0.24
langchain-community                      0.3.2
langchain-core                           0.3.15
langchain-ollama                         0.2.0
langchain-text-splitters                 0.3.0

**Comment by keenborder786** [comment]
I guess you are passing a dict as your input. Please see the code below, that might help (I tested it and it works):
```python

from langchain_chroma import Chroma as LangchainChroma
from langchain_ollama.embeddings import OllamaEmbeddings
from langchain_ollama.chat_models import ChatOllama
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import PromptTemplate
embed_model = OllamaEmbeddings(model='mxbai-embed-large')
vector_store = LangchainChroma.from_texts(["Harrison Lives in New York"], embedding=embed_model)
llm = ChatOllama(model='llama3')
SOME_PROMPT = PromptTemplate.from_template("""
Answer the following question: {question}
using the given context:
{docs}
""")
chain = (
    {"docs": vector_store.as_retriever(), "question": RunnablePassthrough()}
    | SOME_PROMPT
    | llm
    | StrOutputParser()
)

```

**Comment by simingy** [comment]
thank you for the help
it seems like the dict as input _used_ to work. Strange.
