### ISSUE TITLE
AzureMLChatOnlineEndpoint not compatible with create_react_agent (NotImplementedError for bind_tool method)

### ISSUE THREAD

**Issue by informatica92** [langchain-ai/langchain#28129]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
import os
from langchain_community.chat_models.azureml_endpoint import AzureMLChatOnlineEndpoint,  AzureMLEndpointApiType, CustomOpenAIChatContentFormatter
from langchain_community.utilities import SQLDatabase
from langchain_community.agent_toolkits.sql.toolkit import SQLDatabaseToolkit
from langchain import hub
from langgraph.prebuilt import create_react_agent

if __name__ == "__main__":
    db = SQLDatabase.from_uri("sqlite:///Chinook.db")

    url = os.environ.get("AZUREML_ENDPOINT_URL")
    key = os.environ.get("AZUREML_ENDPOINT_KEY")
    timeout = 60 * 5  # default = 60 * 5 = 5 minutes

    llm = AzureMLChatOnlineEndpoint(
        endpoint_url=url,
        endpoint_api_type=AzureMLEndpointApiType.serverless,
        endpoint_api_key=key,
        content_formatter=CustomOpenAIChatContentFormatter(),
        timeout=timeout  # default = 60 * 5 = 5 minutes
    )

    toolkit = SQLDatabaseToolkit(db=db, llm=llm)

    prompt_template = hub.pull("langchain-ai/sql-agent-system-prompt")

    system_message = prompt_template.format(dialect="SQLite", top_k=5)

    agent_executor = create_react_agent(llm, toolkit.get_tools(), state_modifier=system_message)

    example_query = "Which country's customers spent the most?"

    events = agent_executor.stream(
        {"messages": [("user", example_query)]},
        stream_mode="values",
    )
    for event in events:
        event["messages"][-1].pretty_print()
```

### Error Message and Stack Trace (if applicable)

```
"C:\Users\...\git\Text2SQL\Text2SQL - ENV\Scripts\python.exe" C:\Users\...\git\Text2SQL\text2sql\main_agent_llama.py 
C:\Users\...\git\Text2SQL\Text2SQL - ENV\Lib\site-packages\langsmith\client.py:221: LangSmithMissingAPIKeyWarning: API key must be provided when using hosted LangSmith API
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\...\git\Text2SQL\text2sql\main_agent_llama.py", line 571, in <module>
    agent_executor = create_react_agent(llm, toolkit.get_tools(), state_modifier=system_message)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\git\Text2SQL\Text2SQL - ENV\Lib\site-packages\langgraph\_api\deprecation.py", line 80, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\git\Text2SQL\Text2SQL - ENV\Lib\site-packages\langgraph\prebuilt\chat_agent_executor.py", line 512, in create_react_agent
    model = cast(BaseChatModel, model).bind_tools(tool_classes)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\git\Text2SQL\Text2SQL - ENV\Lib\site-packages\langchain_core\language_models\chat_models.py", line 1115, in bind_tools
    raise NotImplementedError
NotImplementedError

```

### Description

I'm trying to implement a future-ready **SQL Agent** with an open weights model  (Meta LLama) hosted into an **Azure AI infrastructure**.
My code is pretty simple and it's just one of the various how-to guides in which I switched from the original OpenAI model to a **AzureMLChatOnlineEndpoint**.

But the execution interrupts pretty soon since the flow relies on the BaseModel bind_tool implementation that just throw a "**NotImplementedError**".

**Is there ant chance to make AzureMLChatOnlineEndpoint compatible with this method?** 
Consider that the direction in which LangChain is moving is LangGraph so makes no sense now to create an agent using create_sql_agent from from langchain_community.agent_toolkits

### System Info

System Information
------------------
> OS:  Windows
> OS Version:  10.0.22631
> Python Version:  3.11.7 | packaged by Anaconda, Inc. | (main, Dec 15 2023, 18:05:47) [MSC v.1916 64 bit (AMD64)]

Package Information
-------------------
> langchain_core: 0.3.15
> langchain: 0.3.6
> langchain_community: 0.3.4
> langsmith: 0.1.138
> langchain_groq: 0.2.1
> langchain_openai: 0.2.4
> langchain_text_splitters: 0.3.1
> langgraph: 0.2.41

Optional packages not installed
-------------------------------
> langserve

Other Dependencies
------------------
> aiohttp: 3.10.10
> async-timeout: Installed. No version info available.
> dataclasses-json: 0.6.7
> groq: 0.11.0
> httpx: 0.27.2
> httpx-sse: 0.4.0
> jsonpatch: 1.33
> langgraph-checkpoint: 2.0.2
> langgraph-sdk: 0.1.35
> numpy: 1.26.4
> openai: 1.53.0
> orjson: 3.10.10
> packaging: 24.1
> pydantic: 2.9.2
> pydantic-settings: 2.6.0
> PyYAML: 6.0.2
> requests: 2.32.3
> requests-toolbelt: 1.0.0
> SQLAlchemy: 2.0.36
> tenacity: 8.5.0
> tiktoken: 0.8.0
> typing-extensions: 4.12.2

**Comment by Allaye** [comment]
@informatica92 have you found any solution for this problem? i did implement my own bind_tools but it is clearly not working

**Comment by informatica92** [comment]
unfortunately no, I also tried the solution to use the **OpenAI compatible interface** using something like: 
```python 
from langchain_openai import  ChatOpenAI
llm = ChatOpenAI(
    default_headers={"extra-parameters": "pass-through"},  # <-- required to avoid an error
    base_url=llama3_model_url,
    api_key=key,
)
```

but the interaction with the tools end at the first stage.

The only solution I adopt at the moment is to deploy a **MistralAI** model instead of a Llama3.X, always on **Azure AI Studio**, and use the **MistralAI langchain library (langchain_mistralai)**.

Please note that, at least with the versions I am using there is a weird issue about a **pass-through parameter** (as the additional pass-through that I passed above into ChatOpenAI).

So my solution to work with Azure deployed models requires few precautions:
- use a **MistralAI** (not Llama3.x)
- install **langchain_mistralai**
- create a **custom MistralAI Chat** class to f**orce the pass-through header** as discussed below:

```python
import os
import httpx

from langchain_core.messages.ai import AIMessage
from langchain_community.utilities import SQLDatabase
from langchain_community.agent_toolkits.sql.toolkit import SQLDatabaseToolkit

from langchain import hub
from langgraph.prebuilt import create_react_agent

# 1. Import ChatMistralAI
from langchain_mistralai import ChatMistralAI

# 2. Create the custom ChatMistralAI to force pass-through header
class NewMistralAI(ChatMistralAI):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        headers = {
            "Content-Type": "application/json",
            "Accept": "application/json",
            "Authorization": f"Bearer {self.mistral_api_key.get_secret_value()}",
            "extra-parameters": "pass-through",
        }

        httpx_client_kwargs = {
            "base_url": self.endpoint,
            "headers": headers,
            "timeout": self.timeout,
        }

        self.client = httpx.Client(**httpx_client_kwargs)
        self.async_client = httpx.AsyncClient(**httpx_client_kwargs)
        self.safe_mode = None


if __name__ == "__main__":
    # Database
    db = SQLDatabase.from_uri("sqlite:///../../Chinook.db")

    # Model
    key = os.environ.get("MISTRAL_AZURE_API_KEY")
    timeout = 60 * 5  # default = 60 * 5 = 5 minutes

    # using the default ChatMistralAI class the flow returns an error similar to the following:
    # Error code: 400 - {'detail': "Extra parameters ['safe_prompt'] are not allowed when extra-parameters is not set or set to be 'error'. Set extra-parameters to 'pass-through' to pass to the model."}
    # so there are 2 ways:
    # - use a custom version of the ChatMistralAI that forces the "extra-parameters": "pass-through" header
    # - use the OpenAI-compatible endpoint to pass extra-parameters additional header. NB: base_url and api_key look like unsupported, but they are NOT

    # 3. Use the NewMistralAI Custom Class
    llm = NewMistralAI(  # ChatOpenAI, NewMistralAI
        endpoint=mistralai_on_azure_model_url,
        mistral_api_key=key,
        timeout=timeout,
        max_retries=5,
        # other params...
    )

    # Toolkit
    toolkit = SQLDatabaseToolkit(db=db, llm=llm)

    # System Prompt
    prompt_template = hub.pull("langchain-ai/sql-agent-system-prompt")
    system_message = prompt_template.format(dialect="SQLite", top_k=5)
    # print(system_message)

    # Executor
    agent_executor = create_react_agent(llm, toolkit.get_tools(), state_modifier=system_message)

    example_query = "Which country's customers spent the most?"
    # example_query = "Tell me something about Paris and its history"

    events = agent_executor.stream(
        {"messages": [("user", example_query)]},
        stream_mode="values",
    )

    input_tokens = 0
    output_tokens = 0
    total_tokens = 0
    for event in events:
        event["messages"][-1].pretty_print()
        if isinstance(event["messages"][-1], AIMessage):
            print(event["messages"][-1].usage_metadata)
            input_tokens += event["messages"][-1].usage_metadata.get("input_tokens")
            output_tokens += event["messages"][-1].usage_metadata.get("output_tokens")
            total_tokens += event["messages"][-1].usage_metadata.get("total_tokens")

    print("\nTOTALS")
    print(f" - input_tokens:  {input_tokens}")
    print(f" - output_tokens: {output_tokens}")
    print(f" - total_tokens:  {total_tokens}")

```

**Comment by hschmied** [comment]
I also just started experimenting with AzureMLChatOnlineEndpoint and noticed that binding tools is an issue as well as multimodal messaging (e.g. images).

Since AzureMLChat isn't one of the featured providers, I guess it's to be expected that certain features might not be available/work right away.
https://python.langchain.com/docs/integrations/chat/

It's probably also more difficult with all the potential different implementations of tool calls  a model hosted on azure can have e.g. llama, mistral,...

I know for mistral there's some work-in-progress to get the mistral-provider to work with models hosted on azure, but it's not ready/approved yet: https://github.com/langchain-ai/langchain/pull/28301

Anyway... looking forward to what comes next.

**Comment by informatica92** [comment]
I AM using MistralAI models deployed on Azure and it's already working as expected (apart from the pass-through parameter)

**Comment by Allaye** [comment]
> I AM using MistralAI models deployed on Azure and it's already working as expected (apart from the pass-through parameter)

i see, i wanted to use the https://models.inference.ai.azure.com/, so i created a working solution, but now, i needed the models, llama, mistra and co to use tools, that is where i am struggling with now.

**Comment by hschmied** [comment]
I've now spent some time with it and as you said, directly with the modified ChatMistralAI it's working; the other task has to do w/ making it available via the 'init_chat_model' method and be able to use configure to switch between them.
but this workaround and at least mistral working is helpful. thx!
