### ISSUE TITLE
`init_chat_model` doesn't work with huggingface models

### ISSUE THREAD

**Issue by SauravMaheshkar** [langchain-ai/langchain#28226]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

Snippet

```python
from langchain.chat_models import init_chat_model


llm = init_chat_model(
    model="microsoft/Phi-3-mini-4k-instruct",
    model_provider="huggingface",
    temperature=0,
    max_tokens=1024,
    timeout=None,
    max_retries=2,
)
```

### Error Message and Stack Trace (if applicable)

```bash
Traceback (most recent call last):
  File "/Users/sauravmaheshkar/dev/papersai/mre.py", line 4, in <module>
    llm = init_chat_model(
  File "/Users/sauravmaheshkar/dev/papersai/.venv/lib/python3.10/site-packages/langchain/chat_models/base.py", line 304, in init_chat_model
    return _init_chat_model_helper(
  File "/Users/sauravmaheshkar/dev/papersai/.venv/lib/python3.10/site-packages/langchain/chat_models/base.py", line 393, in _init_chat_model_helper
    return ChatHuggingFace(model_id=model, **kwargs)
  File "/Users/sauravmaheshkar/dev/papersai/.venv/lib/python3.10/site-packages/langchain_huggingface/chat_models/huggingface.py", line 317, in __init__
    super().__init__(**kwargs)
  File "/Users/sauravmaheshkar/dev/papersai/.venv/lib/python3.10/site-packages/langchain_core/load/serializable.py", line 125, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/sauravmaheshkar/dev/papersai/.venv/lib/python3.10/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ChatHuggingFace
llm
  Field required [type=missing, input_value={'model_id': 'microsoft/P... None, 'max_retries': 2}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
```

### Description

* I'm trying to use the [`init_chat_model`](https://python.langchain.com/api_reference/langchain/chat_models/langchain.chat_models.base.init_chat_model.html) function to instantiate a model from the huggingface hub.

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 24.0.0: Tue Sep 24 23:36:26 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T8103
> Python Version:  3.10.15 (main, Sep  9 2024, 22:43:48) [Clang 18.1.8 ]

Package Information
-------------------
> langchain_core: 0.3.19
> langchain: 0.3.7
> langsmith: 0.1.143
> langchain_anthropic: 0.2.3
> langchain_huggingface: 0.1.2
> langchain_text_splitters: 0.3.2

Optional packages not installed
-------------------------------
> langgraph
> langserve

Other Dependencies
------------------
> aiohttp: 3.11.6
> anthropic: 0.36.2
> async-timeout: 4.0.3
> defusedxml: 0.7.1
> httpx: 0.27.2
> huggingface-hub: 0.26.2
> jsonpatch: 1.33
> numpy: 1.26.4
> orjson: 3.10.11
> packaging: 24.2
> pydantic: 2.9.2
> PyYAML: 6.0.2
> requests: 2.32.3
> requests-toolbelt: 1.0.0
> sentence-transformers: 3.3.1
> SQLAlchemy: 2.0.36
> tenacity: 9.0.0
> tokenizers: 0.20.3
> transformers: 4.46.3
> typing-extensions: 4.12.2

**Comment by dkincaid** [comment]
I'm getting the same error here. Is there any workaround?

**Comment by SauravMaheshkar** [comment]
> I'm getting the same error here. Is there any workaround?

I just migrated to `litellm` 🤷🏼‍♂️

**Comment by Ramana-vummenthala** [comment]
You can replace init_chat_model with HuggingFaceEndpoint:

`from langchain_huggingface import HuggingFaceEndpoint

model = HuggingFaceEndpoint(
    repo_id="mistralai/Mistral-7B-Instruct-v0.2",
    max_length=128,
    temperature=0.1,
    huggingfacehub_api_token=os.environ["HUGGINGFACEHUB_API_TOKEN"]
)
`

This should work as a direct alternative.

**Comment by bhavan-kaya** [comment]
Facing the same issue. Any possible solutions?

**Comment by zizaola** [comment]
Similar error while using `init_embeddings`. 
`langchain` version 2.35.

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\Users\zizaola\Dropbox\Proyectos\MIK\OrbeaAgent\.venv\Lib\site-packages\langchain\embeddings\base.py", line 210, in init_embeddings
    return HuggingFaceEmbeddings(model_name=model_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\zizaola\Dropbox\Proyectos\MIK\OrbeaAgent\.venv\Lib\site-packages\langchain_huggingface\embeddings\huggingface.py", line 64, in __init__
    super().__init__(**kwargs)
  File "c:\Users\zizaola\Dropbox\Proyectos\MIK\OrbeaAgent\.venv\Lib\site-packages\pydantic\main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for HuggingFaceEmbeddings
api_key
  Extra inputs are not permitted [type=extra_forbidden, input_value='hf_MORD[REDACTED by EUGENE]', input_type=str]
    For further information visit https://errors.pydantic.dev/2.11/v/extra_forbidden`

**Comment by eyurtsev** [comment]
@zizaola you leaked a secret: `hf_MORDXy[REDACTED]` please revoke the key immediately and assume it's been compromised

**Comment by eyurtsev** [comment]
@SauravMaheshkar It looks like it should be working based on the existing code.

what is the output of `python -m langchain_core.sys_info`

**Comment by zizaola** [comment]
@eyurtsev  Thanks for the note in the API_KEY. Here is the output

python -m langchain_core.sys_info

System Information
------------------
> OS:  Windows
> OS Version:  10.0.19045
> Python Version:  3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:16:22) [MSC v.1916 64 bit (AMD64)]

Package Information
-------------------
> langchain_core: 0.3.68
> langchain: 0.3.25
> langchain_community: 0.3.25
> langsmith: 0.3.45
> langchain_anthropic: 0.3.17
> langchain_chroma: 0.2.4
> langchain_google_vertexai: 2.0.27
> langchain_huggingface: 0.3.0
> langchain_openai: 0.3.22
> langchain_text_splitters: 0.3.8

Optional packages not installed
-------------------------------
> langserve

Other Dependencies
------------------
> aiohttp<4.0.0,>=3.8.3: Installed. No version info available.
> anthropic<1,>=0.57.0: Installed. No version info available.
> anthropic[vertexai]: Installed. No version info available.
> async-timeout<5.0.0,>=4.0.0;: Installed. No version info available.
> bottleneck: 1.5.0
> chromadb>=1.0.9: Installed. No version info available.
> dataclasses-json<0.7,>=0.5.7: Installed. No version info available.
> google-cloud-aiplatform: 1.101.0
> google-cloud-storage: 2.19.0
> httpx: 0.28.1
> httpx-sse: 0.4.0
> httpx-sse<1.0.0,>=0.4.0: Installed. No version info available.
> huggingface-hub>=0.30.2: Installed. No version info available.
> jsonpatch<2.0,>=1.33: Installed. No version info available.
> langchain-anthropic;: Installed. No version info available.
> langchain-aws;: Installed. No version info available.
> langchain-azure-ai;: Installed. No version info available.
> langchain-cohere;: Installed. No version info available.
> langchain-community;: Installed. No version info available.
> langchain-core<1.0.0,>=0.3.51: Installed. No version info available.
> langchain-core<1.0.0,>=0.3.58: Installed. No version info available.
> langchain-core<1.0.0,>=0.3.64: Installed. No version info available.
> langchain-core<1.0.0,>=0.3.65: Installed. No version info available.
> langchain-core<1.0.0,>=0.3.68: Installed. No version info available.
> langchain-core>=0.3.60: Installed. No version info available.
> langchain-deepseek;: Installed. No version info available.
> langchain-fireworks;: Installed. No version info available.
> langchain-google-genai;: Installed. No version info available.
> langchain-google-vertexai;: Installed. No version info available.
> langchain-groq;: Installed. No version info available.
> langchain-huggingface;: Installed. No version info available.
> langchain-mistralai: Installed. No version info available.
> langchain-mistralai;: Installed. No version info available.
> langchain-ollama;: Installed. No version info available.
> langchain-openai;: Installed. No version info available.
> langchain-perplexity;: Installed. No version info available.
> langchain-text-splitters<1.0.0,>=0.3.8: Installed. No version info available.    
> langchain-together;: Installed. No version info available.
> langchain-xai;: Installed. No version info available.
> langchain<1.0.0,>=0.3.25: Installed. No version info available.
> langsmith-pyo3: Installed. No version info available.
> langsmith<0.4,>=0.1.125: Installed. No version info available.
> langsmith<0.4,>=0.1.17: Installed. No version info available.
> langsmith>=0.3.45: Installed. No version info available.
> numexpr: 2.11.0
> numpy>=1.26.0;: Installed. No version info available.
> numpy>=1.26.2;: Installed. No version info available.
> numpy>=2.1.0;: Installed. No version info available.
> openai-agents: Installed. No version info available.
> openai<2.0.0,>=1.68.2: Installed. No version info available.
> opentelemetry-api: 1.34.1
> opentelemetry-exporter-otlp-proto-http: Installed. No version info available.    
> opentelemetry-sdk: 1.34.1
> orjson: 3.10.18
> packaging: 24.2
> packaging<25,>=23.2: Installed. No version info available.
> pyarrow: 19.0.1
> pydantic: 2.11.5
> pydantic-settings<3.0.0,>=2.4.0: Installed. No version info available.
> pydantic<3.0.0,>=2.7.4: Installed. No version info available.
> pydantic>=2.7.4: Installed. No version info available.
> pytest: 8.4.0
> PyYAML>=5.3: Installed. No version info available.
> requests: 2.32.4
> requests-toolbelt: 1.0.0
> requests<3,>=2: Installed. No version info available.
> rich: 14.0.0
> sentence-transformers>=2.6.0;: Installed. No version info available.
> SQLAlchemy<3,>=1.4: Installed. No version info available.
> tenacity!=8.4.0,<10,>=8.1.0: Installed. No version info available.
> tenacity!=8.4.0,<10.0.0,>=8.1.0: Installed. No version info available.
> tiktoken<1,>=0.7: Installed. No version info available.
> tokenizers>=0.19.1: Installed. No version info available.
> transformers>=4.39.0;: Installed. No version info available.
> typing-extensions>=4.7: Installed. No version info available.
> validators: 0.35.0
> zstandard: 0.23.0

**Comment by aaron-seq** [comment]
I'd like to work on this, @mrdrxy

**Comment by aaron-seq** [comment]
Hey, I have a solution, let me know if anyone is still working on this @mdrxy

**Comment by aaron-seq** [comment]
From my initial investigation, it seems like the _init_chat_model_helper function in langchain/chat_models/base.py is incorrectly instantiating ChatHuggingFace. It's passing a model_id string directly, but the ChatHuggingFace class expects a fully initialized llm object (like a HuggingFacePipeline instance) in its constructor.

My plan is to:

Modify the helper function to first create a HuggingFacePipeline instance.

Pass this llm instance to the ChatHuggingFace wrapper.

Add a unit test to verify that init_chat_model works correctly with model_provider="huggingface".

I'll submit a PR with the fix and the new test. Let me know if that sounds right!

**Comment by AkibDa** [comment]
You need to update your code to initialize the model in two steps: first create the Hugging Face pipeline, then wrap it with LangChain's `ChatHuggingFace`.

Here is the corrected code:

```
from transformers import pipeline
from langchain_huggingface import ChatHuggingFace

# 1. Create a pipeline from the transformers library
pipe = pipeline(
    "text-generation",
    model="microsoft/Phi-3-mini-4k-instruct",
    max_new_tokens=1024, # Note: max_tokens is now max_new_tokens
    # You can add other pipeline-specific arguments here
    # For deterministic output like temperature=0, you can use do_sample=False
    do_sample=False,
    # The pipeline will automatically use a GPU if available
)

# 2. Wrap the pipeline in the LangChain ChatHuggingFace class
llm = ChatHuggingFace(llm=pipe)

# Now you can use the llm object as intended
print(llm.invoke("What are the three main laws of thermodynamics?").content)
```

**Comment by KunjShah95** [comment]
is anybody working on this or can i work on it

**Comment by Accidental-MVP** [comment]
Hi all, I noticed that while #33167 is fixing the core issue, there isn’t full test or docs coverage yet for init_chat_model(model_provider="huggingface").

I’d be happy to open a separate PR that:

• Adds offline/mocked regression tests (basic HF init, max_tokens vs max_new_tokens tolerance, and timeout/max_retries).

• Adds a small docs snippet showing correct usage + troubleshooting.

This would complement the fix PR and help prevent regressions in the future. If this isn’t needed or should be folded into #33167 instead, happy to adjust.

Thanks!

**Comment by KushagraaWadhwa** [comment]
Hi, I'd like to work on this issue. I see there are already some PRs in progress, but I'd be happy to help review them or contribute additional test coverage and documentation if needed.

**Comment by ccurme** [comment]
Hi all, thanks for reporting the issue here.

I've merged https://github.com/langchain-ai/langchain/pull/33167 into `langchain-classic`, it will go out in the next release.

However, I think some more thought is required around this:
- How do we support instantiation for both [HuggingFaceEndpoint and HuggingFacePipeline](https://docs.langchain.com/oss/python/integrations/chat/huggingface#instantiation)
- How do we control what kwargs are passed to the LLM and what are passed to the chat model

HuggingFace definitely breaks the mold and we'd welcome thoughts here. We'll also need to port to `langchain` (v1.0) once the design is set.

**Comment by aaron-seq** [comment]
Hey team!

I see that PR #33167 was successfully merged to fix the core HuggingFace `init_chat_model` issue. Great work on resolving that!

I wanted to follow up and suggest some **documentation improvements** that would help prevent similar issues and make `init_chat_model` more accessible to users:

## Documentation Enhancement Proposal

### 1. Comprehensive init_chat_model Guide

I'd love to help create a dedicated documentation page that covers:

- **Provider-specific examples** for all supported model providers (OpenAI, Anthropic, HuggingFace, Google, etc.)
- **Common parameter patterns** and their usage across different providers
- **Error handling** and troubleshooting for common issues like the HuggingFace one we just fixed
- **Best practices** for parameter validation and model initialization

### 2. Provider-Specific Sections

Each provider could have its own section showing:

```python
# HuggingFace examples with proper parameter usage
llm = init_chat_model(
    model="microsoft/Phi-3-mini-4k-instruct",
    model_provider="huggingface",
    task="text-generation",  # Required for HF models
    temperature=0.7,
    max_tokens=1024
)

# Anthropic examples
llm = init_chat_model(
    model="claude-3-sonnet-20240229",
    model_provider="anthropic",
    temperature=0.7,
    max_tokens=1024
)
```

### 3. Migration Guide

A section helping users migrate from provider-specific imports to `init_chat_model`:

```python
# Old way
from langchain_huggingface import ChatHuggingFace, HuggingFacePipeline

# New way with init_chat_model
from langchain.chat_models import init_chat_model
```

## Next Steps

Would the team be interested in having me:

1. **Create a comprehensive documentation PR** covering `init_chat_model` usage patterns?
2. **Add provider-specific examples** to the existing documentation?
3. **Write a troubleshooting guide** for common `init_chat_model` issues?

I've got experience with technical documentation and would be happy to contribute to making LangChain more accessible for developers!

Let me know if this aligns with the project's documentation roadmap. Thanks for all the great work on LangChain!

**Comment by ccurme** [comment]
Hi @aaron-seq,

I don't think we need a separate guide, but adding a HuggingFace example to the chat model tabs [here](https://github.com/langchain-ai/docs/blob/main/src/snippets/chat-model-tabs.mdx) would be useful.

This is a re-usable snippet that appears across our docs (for example [here](https://docs.langchain.com/oss/python/langchain/models#initialize-a-model)).

Thank you for your thoughts on this!

**Comment by aaron-seq** [comment]
@ccurme Absolutely, that's a much cleaner approach. The reusable snippet strategy ensures consistency across all documentation pages.

I'll add HuggingFace examples to the chat-model-tabs.mdx file. Based on your earlier comment about supporting both HuggingFaceEndpoint and HuggingFacePipeline, I plan to include:

1. **API-based example** using HuggingFaceEndpoint for inference API calls
2. **Local pipeline example** for users running models locally
3. **Parameter mapping guidance** showing max_tokens vs max_new_tokens differences

This addresses the dual instantiation challenge you mentioned while providing clear usage patterns in the standard documentation format.

Should I include both patterns in a single HuggingFace tab with subsections, or would separate tabs for "HuggingFace API" and "HuggingFace Local" be preferable?

I can have a PR ready for the docs repository by early next week.

**Comment by ccurme** [comment]
I would keep it minimal and just show one pattern. The tab will have a link to the HuggingFace [integration page](https://docs.langchain.com/oss/python/integrations/chat/huggingface); if there's information missing on that page we can flesh it out and maybe update examples to initialize using `init_chat_model` (source for that page is [here](https://github.com/langchain-ai/docs/blob/main/src/oss/python/integrations/chat/huggingface.mdx)).

Thanks for your help!

**Comment by uvansh** [comment]
Is someone assigned to this issue ?

**Comment by aaron-seq** [comment]
Looking at the current state of this issue - PR #33943 by @georgeykalangi has a solid implementation that addresses all the core problems:

**Technical Implementation:**
- Properly extracts and defaults the `task` parameter to "text-generation"
- Correctly separates pipeline-specific kwargs (backend, device, device_map, model_kwargs, pipeline_kwargs, batch_size) from ChatHuggingFace kwargs (timeout, max_retries)
- Maps generation parameters appropriately: `max_tokens` → `max_new_tokens`, plus temperature, top_p, top_k, repetition_penalty, do_sample into pipeline_kwargs
- Includes test coverage that verifies the ValidationError about missing 'llm' field is resolved

**PR Status:**
The PR has been open since November 13, 2024 and appears to be waiting for:
1. CI checks to complete
2. Maintainer review

**Documentation:**
As discussed in the thread, @akhilreddy097 added HuggingFace examples to the docs in PR langchain-ai/docs#1522, which was merged successfully.

@ccurme @eyurtsev - could you review #33943 when you have a moment? The fix properly handles the parameter routing issue that caused the original ValidationError.

**Comment by ujjwaltwri** [comment]
I’d like to work on this as a first issue.
Plan: update the huggingface branch of _init_chat_model_helper to correctly construct ChatHuggingFace (using from_model_id or a proper HF LLM wrapper) and add a unit test.I’d like to work on this as a first issue.
Plan: update the huggingface branch of _init_chat_model_helper to correctly construct ChatHuggingFace (using from_model_id or a proper HF LLM wrapper) and add a unit test.

**Comment by tysoncung** [comment]
I'm interested in working on this issue. Could you provide more context about what you're looking for? Any additional details about requirements or constraints would be helpful.
