### ISSUE TITLE
Trying to use SQLDatabaseLoader gives error

### ISSUE THREAD

**Issue by JuanSaavedra** [langchain-ai/langchain#28349]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

    def  initialise(self):       
        print("initialising...")
        
        connect_Url = URL.create(
            drivername="mssql+pyodbc",
            username=ConfigSettings.userId,
            password=ConfigSettings.password,
            host=ConfigSettings.server,
            database=ConfigSettings.database,
            query={"driver": "ODBC Driver 17 for SQL Server"},
        )
        
        engine = create_engine(connect_Url,echo=False)
        con = engine.connect()
               
        #self.db = SQLDatabase(engine=engine)
        self.db = SQLDatabase.from_uri(connect_Url, include_tables=["TestTable"], sample_rows_in_table_info=2)
        
        #table_names = self.db.get_usable_table_names()
        #print("Number of tables: ", len(table_names))
        
        #response = self.db.run("SELECT top 10 * FROM InvoiceStatus")
        #print(response)
               
        query = "SELECT top 10 * FROM TestTable"
        
        self.llm = OpenAI(api_key=OPENAI_API_KEY)
        
        databaseLoader = SQLDatabaseLoader(db=self.db,query=query)
        docs = databaseLoader.load()
        print("Number of documents: ", len(docs))
        
        print("Exiting...\n\n")

### Error Message and Stack Trace (if applicable)

    def  initialise(self):       
        print("initialising...")
        
        connect_Url = URL.create(
            drivername="mssql+pyodbc",
            username=ConfigSettings.userId,
            password=ConfigSettings.password,
            host=ConfigSettings.server,
            database=ConfigSettings.database,
            query={"driver": "ODBC Driver 17 for SQL Server"},
        )
        
        engine = create_engine(connect_Url,echo=False)
        con = engine.connect()
               
        #self.db = SQLDatabase(engine=engine)
        self.db = SQLDatabase.from_uri(connect_Url, include_tables=["TestTable"], sample_rows_in_table_info=2)
        
        #table_names = self.db.get_usable_table_names()
        #print("Number of tables: ", len(table_names))
        
        #response = self.db.run("SELECT top 10 * FROM InvoiceStatus")
        #print(response)
               
        query = "SELECT top 10 * FROM TestTable"
        
        self.llm = OpenAI(api_key=OPENAI_API_KEY)
        
        databaseLoader = SQLDatabaseLoader(db=self.db,query=query)
        docs = databaseLoader.load()
        print("Number of documents: ", len(docs))
        
        print("Exiting...\n\n")

### Description

Hi there, 

I'm new here so apologies if its a silly question.

I'm trying to query the database using the **SQLDatabaseLoader** but getting an error when calling load().

**sqlalchemy.exc.DBAPIError: (pyodbc.Error) ('HY010', '[HY010] [Microsoft][ODBC Driver 17 for SQL Server]Function sequence error (0) (SQLFetch)')**

If I do any arbitrary SQL query, it works fine e.g

#response = self.db.run("SELECT top 10 * FROM InvoiceStatus")
#print(response)

I tried different versions of SQLAlchemy with no luck either..

However, when calling load() it gives the following error:

----------------- RAG Db With OpenAI ----------------
initialising...
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\engine\cursor.py", line 1109, in fetchone
    row = dbapi_cursor.fetchone()
          ^^^^^^^^^^^^^^^^^^^^^^^
pyodbc.Error: ('HY010', '[HY010] [Microsoft][ODBC Driver 17 for SQL Server]Function sequence error (0) (SQLFetch)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Projects\Python\main.py", line 28, in <module>
    dbRag1.initialise()
  File "E:\Projects\Python\ragWithOpenAI_Database.py", line 82, in initialise
    docs = databaseLoader.load()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\langchain_core\document_loaders\base.py", line 31, in load
    return list(self.lazy_load())
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\langchain_community\document_loaders\sql_database.py", line 90, in lazy_load
    for i, row in enumerate(result.mappings()):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\engine\result.py", line 508, in iterrows
    for raw_row in self._fetchiter_impl():
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\engine\cursor.py", line 2086, in _fetchiter_impl
    row = fetchone(self, self.cursor)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\engine\cursor.py", line 1114, in fetchone
    self.handle_exception(result, dbapi_cursor, e)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\engine\cursor.py", line 1085, in handle_exception
    result.connection._handle_dbapi_exception(
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\engine\base.py", line 2325, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\engine\cursor.py", line 1109, in fetchone
    row = dbapi_cursor.fetchone()
          ^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.DBAPIError: (pyodbc.Error) ('HY010', '[HY010] [Microsoft][ODBC Driver 17 for SQL Server]Function sequence error (0) (SQLFetch)')

Any help would be greatly appreciated.

Thank you all,

J

### System Info

System Information
------------------
> OS:  Windows
> OS Version:  10.0.22631
> Python Version:  3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]

Package Information
-------------------
> langchain_core: 0.3.21
> langchain: 0.3.8
> langchain_community: 0.3.8
> langsmith: 0.1.146
> langchain_experimental: 0.3.3
> langchain_text_splitters: 0.3.2

Optional packages not installed
-------------------------------
> langserve

Other Dependencies
------------------
> aiohttp: 3.10.10
> async-timeout: Installed. No version info available.
> dataclasses-json: 0.6.7
> httpx: 0.27.2
> httpx-sse: 0.4.0
> jsonpatch: 1.33
> numpy: 1.26.4
> orjson: 3.10.11
> packaging: 24.1
> pydantic: 2.9.2
> pydantic-settings: 2.6.1
> PyYAML: 6.0.2
> requests: 2.32.3
> requests-toolbelt: 1.0.0
> SQLAlchemy: 2.0.0
> tenacity: 8.5.0

**Comment by thisnotebooksuser** [comment]
I'm getting the same error. I created a specific file for testing this and, even with minimal implementation, I still get the issue.

PS: sorry for a billion edits, I'm new to the website and can't format my stuff correctly.

>from langchain_community.utilities.sql_database import SQLDatabase
>from langchain_community.document_loaders.sql_database import SQLDatabaseLoader
>from sqlalchemy import create_engine, text
>from langchain_core.documents import Document
>
>
>db_user = 'lanchain_issue'
>db_password = 'pwd_langchain_issue'
>db_host = 'localhost'
>db_name = 'langchain_issue'
>
>sql_server_uri = f"mssql+pyodbc://{db_user}:{db_password}@{db_host}/{db_name}?driver=ODBC+Driver+17+for+SQL+Server"
>
>query = 'SELECT CONTENT FROM docs_test'
>
>def load_documents_from_sql():
>    engine = create_engine(sql_server_uri)
>    documents = []
>
>    with engine.connect() as connection:
>        result = connection.execute(text(query))
>        for row in result:
>            doc = Document(page_content=str(row.CONTENT))
>            documents.append(doc)
>    return documents
>
>documents = load_documents_from_sql()
>
>print(documents)
>
>print("OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO") #this is only here so it's easier to tell apart the outputs of the different parts of the code; without this, looking at the console was giving me headaches - and yes, I realize I could have been smarter about this
>
>print("OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO")
>
>print("OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO")
>
>sql_db = SQLDatabase.from_uri(sql_server_uri)
>
>sql_loader = SQLDatabaseLoader(query=query, db = sql_db)
>
>sql_loaded = sql_loader.load()
>
>print(sql_loaded)

Here's what I get in the console:
> "C:\Users\User\PycharmProjects\langchain_moretests\.venv\Scripts\python.exe" "C:\Users\User\PycharmProjects\langchain_moretests\.venv\run.py" 
> [Document(metadata={}, page_content='im not an error!')]
> OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
> OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
> OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
> Traceback (most recent call last):
>   File "C:\Users\User\PycharmProjects\langchain_moretests\.venv\Lib\site-packages\sqlalchemy\engine\cursor.py", line 1106, in fetchone
>     row = dbapi_cursor.fetchone()
> pyodbc.Error: ('HY010', '[HY010] [Microsoft][ODBC Driver 17 for SQL Server]Function sequence error (0) (SQLFetch)')
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "C:\Users\User\PycharmProjects\langchain_moretests\.venv\run.py", line 37, in <module>
>     sql_loaded = sql_loader.load()
>   File "C:\Users\User\PycharmProjects\langchain_moretests\.venv\Lib\site-packages\langchain_core\document_loaders\base.py", line 32, in load
>     return list(self.lazy_load())
>   File "C:\Users\User\PycharmProjects\langchain_moretests\.venv\Lib\site-packages\langchain_community\document_loaders\sql_database.py", line 90, in lazy_load
>     for i, row in enumerate(result.mappings()):
>                   ~~~~~~~~~^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\User\PycharmProjects\langchain_moretests\.venv\Lib\site-packages\sqlalchemy\engine\result.py", line 527, in iterrows
>     for raw_row in self._fetchiter_impl():
>                    ~~~~~~~~~~~~~~~~~~~~^^
>   File "C:\Users\User\PycharmProjects\langchain_moretests\.venv\Lib\site-packages\sqlalchemy\engine\cursor.py", line 2126, in _fetchiter_impl
>     row = fetchone(self, self.cursor)
>   File "C:\Users\User\PycharmProjects\langchain_moretests\.venv\Lib\site-packages\sqlalchemy\engine\cursor.py", line 1111, in fetchone
>     self.handle_exception(result, dbapi_cursor, e)
>     ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\User\PycharmProjects\langchain_moretests\.venv\Lib\site-packages\sqlalchemy\engine\cursor.py", line 1082, in handle_exception
>     result.connection._handle_dbapi_exception(
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
>         err, None, None, dbapi_cursor, result.context
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     )
>     ^
>   File "C:\Users\User\PycharmProjects\langchain_moretests\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2355, in _handle_dbapi_exception
>     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
>   File "C:\Users\User\PycharmProjects\langchain_moretests\.venv\Lib\site-packages\sqlalchemy\engine\cursor.py", line 1106, in fetchone
>     row = dbapi_cursor.fetchone()
> sqlalchemy.exc.DBAPIError: (pyodbc.Error) ('HY010', '[HY010] [Microsoft][ODBC Driver 17 for SQL Server]Function sequence error (0) (SQLFetch)')
> (Background on this error at: https://sqlalche.me/e/20/dbapi)

I have:

>langchain==0.3.27
>langchain-cohere==0.4.5
>langchain-community==0.3.29
>langchain-core==0.3.75
>langchain-text-splitters==0.3.9
>langgraph==0.6.6
>langgraph-checkpoint==2.1.1
>langgraph-prebuilt==0.6.4
>langgraph-sdk==0.2.3
>langsmith==0.4.19

Running on python 3.13.3 on Windows 10.0.26100. No langserve, just like OP.

Full pip freeze:

> aiohappyeyeballs==2.6.1
> aiohttp==3.12.15
> aiosignal==1.4.0
> annotated-types==0.7.0
> anyio==4.10.0
> attrs==25.3.0
> beautifulsoup4==4.13.5
> bs4==0.0.2
> certifi==2025.8.3
> charset-normalizer==3.4.3
> cohere==5.17.0
> colorama==0.4.6
> dataclasses-json==0.6.7
> fastavro==1.12.0
> filelock==3.19.1
> frozenlist==1.7.0
> fsspec==2025.7.0
> greenlet==3.2.4
> h11==0.16.0
> httpcore==1.0.9
> httpx==0.28.1
> httpx-sse==0.4.0
> huggingface-hub==0.34.4
> idna==3.10
> jsonpatch==1.33
> jsonpointer==3.0.0
> langchain==0.3.27
> langchain-cohere==0.4.5
> langchain-community==0.3.29
> langchain-core==0.3.75
> langchain-text-splitters==0.3.9
> langgraph==0.6.6
> langgraph-checkpoint==2.1.1
> langgraph-prebuilt==0.6.4
> langgraph-sdk==0.2.3
> langsmith==0.4.19
> marshmallow==3.26.1
> multidict==6.6.4
> mypy_extensions==1.1.0
> numpy==2.3.2
> orjson==3.11.3
> ormsgpack==1.10.0
> packaging==25.0
> propcache==0.3.2
> pydantic==2.11.7
> pydantic-settings==2.10.1
> pydantic_core==2.33.2
> pyodbc==5.2.0
> python-dotenv==1.1.1
> PyYAML==6.0.2
> requests==2.32.5
> requests-toolbelt==1.0.0
> sniffio==1.3.1
> soupsieve==2.8
> SQLAlchemy==2.0.43
> tenacity==9.1.2
> tokenizers==0.21.4
> tqdm==4.67.1
> types-PyYAML==6.0.12.20250822
> types-requests==2.32.4.20250809
> typing-inspect==0.9.0
> typing-inspection==0.4.1
> typing_extensions==4.15.0
> urllib3==2.5.0
> xxhash==3.5.0
> yarl==1.20.1
> zstandard==0.24.0
