### ISSUE TITLE
AttributeError: 'HumanMessage' object has no attribute 'get'

### ISSUE THREAD

**Issue by jacopo-chevallard** [langchain-ai/langchain#28531]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

The following code raises the error `AttributeError: 'HumanMessage' object has no attribute 'get'`
```python
from langchain_core.messages import HumanMessage, AIMessage, ToolMessage
from pydantic import BaseModel
from typing import List

from datetime import datetime
from typing import Any, Generator, Tuple, List
from uuid import UUID, uuid4

from langchain_core.messages import AIMessage, HumanMessage

class ChatMessage(BaseModel):
    chat_id: UUID
    message_id: UUID
    brain_id: UUID | None
    msg: AIMessage | HumanMessage
    message_time: datetime
    metadata: dict[str, Any]


class ChatHistory:

    def __init__(self, chat_id: UUID, brain_id: UUID | None) -> None:
        """Init a new ChatHistory object.

        Args:
            chat_id (UUID): A unique identifier for the chat session.
            brain_id (UUID | None): An optional identifier for the brain associated with the chat.
        """
        self.id = chat_id
        self.brain_id = brain_id
        # TODO(@aminediro): maybe use a deque() instead ?
        self._msgs: list[ChatMessage] = []

    def get_chat_history(self, newest_first: bool = False) -> List[ChatMessage]:
        """
        Retrieves the chat history, optionally sorted in reverse chronological order.

        Args:
            newest_first (bool, optional): If True, returns the messages in reverse order (newest first). Defaults to False.

        Returns:
            List[ChatMessage]: A sorted list of chat messages.
        """
        history = sorted(self._msgs, key=lambda msg: msg.message_time)
        if newest_first:
            return history[::-1]
        return history

    def __len__(self):
        return len(self._msgs)

    def append(
        self, langchain_msg: AIMessage | HumanMessage, metadata: dict[str, Any] = {}
    ):
        """
        Appends a new message to the chat history.

        Args:
            langchain_msg (AIMessage | HumanMessage): The message content (either an AI or Human message).
            metadata (dict[str, Any], optional): Additional metadata related to the message. Defaults to an empty dictionary.
        """
        chat_msg = ChatMessage(
            chat_id=self.id,
            message_id=uuid4(),
            brain_id=self.brain_id,
            msg=langchain_msg,
            message_time=datetime.now(),
            metadata=metadata,
        )
        self._msgs.append(chat_msg)

    def iter_pairs(self) -> Generator[Tuple[HumanMessage, AIMessage], None, None]:
        """
        Iterates over the chat history in pairs, returning a HumanMessage followed by an AIMessage.

        Yields:
            Tuple[HumanMessage, AIMessage]: Pairs of human and AI messages.

        Raises:
            AssertionError: If the messages in the pair are not in the expected order (i.e., a HumanMessage followed by an AIMessage).
        """
        # Reverse the chat_history, newest first
        it = iter(self.get_chat_history(newest_first=True))
        for ai_message, human_message in zip(it, it, strict=False):
            assert isinstance(
                human_message.msg, HumanMessage
            ), f"msg {human_message} is not HumanMessage"
            assert isinstance(
                ai_message.msg, AIMessage
            ), f"msg {human_message} is not AIMessage"
            yield (human_message.msg, ai_message.msg)

    def to_list(self) -> List[HumanMessage | AIMessage]:
        """
        Converts the chat history into a list of raw HumanMessage or AIMessage objects.

        Returns:
            list[HumanMessage | AIMessage]: A list of messages in their raw form, without metadata.
        """

        return [_msg.msg for _msg in self._msgs]


if __name__ == "__main__":
    human_msg = HumanMessage(content="i'm human")
    ai_msg = AIMessage(content="i'm AI")
    tool_msg = ToolMessage(content="i'm tool", tool_call_id="123")

    chat_history = ChatHistory(chat_id=uuid4(), brain_id=uuid4())
    chat_history.append(human_msg)
    chat_history.append(ai_msg)

```

### Error Message and Stack Trace (if applicable)

```
Traceback (most recent call last):
  File "/Users/jchevall/Coding/quivr-enterprise/backend/core/examples/tmp/test_temp.py", line 110, in <module>
    chat_history.append(human_msg)
  File "/Users/jchevall/Coding/quivr-enterprise/backend/core/examples/tmp/test_temp.py", line 62, in append
    chat_msg = ChatMessage(
               ^^^^^^^^^^^^
  File "/Users/jchevall/Coding/quivr-enterprise/backend/core/examples/tmp/.venv/lib/python3.11/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jchevall/Coding/quivr-enterprise/backend/core/examples/tmp/.venv/lib/python3.11/site-packages/langchain_core/messages/ai.py", line 202, in _backwards_compat_tool_calls
    check_additional_kwargs = not any(
                                  ^^^^
  File "/Users/jchevall/Coding/quivr-enterprise/backend/core/examples/tmp/.venv/lib/python3.11/site-packages/langchain_core/messages/ai.py", line 203, in <genexpr>
    values.get(k)
    ^^^^^^^^^^
  File "/Users/jchevall/Coding/quivr-enterprise/backend/core/examples/tmp/.venv/lib/python3.11/site-packages/pydantic/main.py", line 856, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'HumanMessage' object has no attribute 'get'
```

### Description

This error appeared when upgrading to langchain > 0.3.

Following the solution in #26967, I created a new, clean venv and reinstalled the dependencies, but I still get the error.

### System Info

Output of `python -m langchain_core.sys_info`
```
System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.5.0: Wed May  1 20:17:33 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6031
> Python Version:  3.11.9 (main, Aug 14 2024, 04:17:21) [Clang 18.1.8 ]

Package Information
-------------------
> langchain_core: 0.3.21
> langchain: 0.3.9
> langchain_community: 0.3.9
> langsmith: 0.1.139
> langchain_anthropic: 0.3.0
> langchain_cohere: 0.3.3
> langchain_experimental: 0.3.3
> langchain_openai: 0.2.11
> langchain_text_splitters: 0.3.2
> langgraph_sdk: 0.1.35

Optional packages not installed
-------------------------------
> langserve

Other Dependencies
------------------
> aiohttp: 3.10.10
> anthropic: 0.39.0
> async-timeout: Installed. No version info available.
> cohere: 5.11.3
> dataclasses-json: 0.6.7
> defusedxml: 0.7.1
> httpx: 0.27.2
> httpx-sse: 0.4.0
> jsonpatch: 1.33
> numpy: 1.26.3
> openai: 1.54.4
> orjson: 3.10.11
> packaging: 23.2
> pandas: 2.2.3
> pydantic: 2.9.2
> pydantic-settings: 2.6.1
> PyYAML: 6.0.2
> requests: 2.32.3
> requests-toolbelt: 1.0.0
> SQLAlchemy: 2.0.36
> tabulate: 0.9.0
> tenacity: 8.5.0
> tiktoken: 0.8.0
> typing-extensions: 4.12.2
```

Output of `pip freeze`
```
aiofiles==23.2.1
aiohappyeyeballs==2.4.3
aiohttp==3.10.10
aiosignal==1.3.1
amqp==5.2.0
annotated-types==0.7.0
anthropic==0.39.0
anyascii==0.3.2
anyio==4.6.2.post1
appnope==0.1.4
asttokens==2.4.1
asyncer==0.0.7
asyncpg==0.30.0
attrs==24.2.0
backoff==2.2.1
beautifulsoup4==4.12.3
bidict==0.23.1
billiard==4.2.1
black==24.10.0
cachetools==5.5.0
celery==5.4.0
certifi==2022.12.7
cffi==1.17.1
cfgv==3.4.0
chainlit==1.3.2
chardet==5.2.0
charset-normalizer==2.1.1
chevron==0.14.0
click==8.1.7
click-didyoumean==0.3.1
click-plugins==1.1.1
click-repl==0.3.0
cohere==5.11.3
colorama==0.4.6
colorlog==6.9.0
comm==0.2.2
contourpy==1.3.0
coverage==7.6.4
cryptography==43.0.3
cycler==0.12.1
dataclasses-json==0.6.7
debugpy==1.8.7
decorator==5.1.1
defusedxml==0.7.1
Deprecated==1.2.14
deprecation==2.1.0
diff-match-patch==20241021
dirtyjson==1.0.8
distlib==0.3.9
distro==1.9.0
docx2txt==0.8
dropbox==12.0.2
ecdsa==0.19.0
emoji==2.14.0
et_xmlfile==2.0.0
execnet==2.1.1
executing==2.1.0
faiss-cpu==1.9.0
fastapi==0.115.5
fastavro==1.9.7
filelock==3.13.1
filetype==1.2.0
flake8==7.1.1
flake8-black==0.3.6
flower==2.0.1
fonttools==4.54.1
fpdf2==2.8.1
frozenlist==1.5.0
fsspec==2024.2.0
google-api-core==2.22.0
google-api-python-client==2.151.0
google-auth==2.35.0
google-auth-httplib2==0.2.0
google-auth-oauthlib==1.2.1
googleapis-common-protos==1.65.0
gotrue==2.10.0
gprof2dot==2024.6.6
greenlet==3.1.1
grpcio==1.67.1
h11==0.14.0
h2==4.1.0
h5py==3.10.0
hiredis==3.0.0
hpack==4.0.0
httpcore==1.0.6
httplib2==0.22.0
httpx==0.27.2
httpx-sse==0.4.0
huggingface-hub==0.26.2
humanize==4.11.0
hyperframe==6.0.1
identify==2.6.1
idna==3.4
importlib_metadata==8.4.0
iniconfig==2.0.0
ipykernel==6.29.5
ipython==8.29.0
jedi==0.19.1
Jinja2==3.1.3
jiter==0.7.0
joblib==1.4.2
jsonpatch==1.33
jsonpath-python==1.0.6
jsonpointer==3.0.0
jsonschema==4.23.0
jsonschema-specifications==2024.10.1
jupyter_client==8.6.3
jupyter_core==5.7.2
kiwisolver==1.4.7
kombu==5.4.2
langchain==0.3.9
langchain-anthropic==0.3.0
langchain-cohere==0.3.3
langchain-community==0.3.9
langchain-core==0.3.21
langchain-experimental==0.3.3
langchain-openai==0.2.11
langchain-text-splitters==0.3.2
langdetect==1.0.9
langgraph==0.2.44
langgraph-checkpoint==2.0.2
langgraph-sdk==0.1.35
langsmith==0.1.139
Lazify==0.4.0
litellm==1.51.3
literalai==0.0.623
llama-cloud==0.1.4
llama-index==0.11.23
llama-index-agent-openai==0.3.4
llama-index-cli==0.3.1
llama-index-core==0.11.23
llama-index-embeddings-openai==0.2.5
llama-index-indices-managed-llama-cloud==0.4.0
llama-index-legacy==0.9.48.post3
llama-index-llms-openai==0.2.16
llama-index-multi-modal-llms-openai==0.2.3
llama-index-program-openai==0.2.0
llama-index-question-gen-openai==0.2.0
llama-index-readers-file==0.3.0
llama-index-readers-llama-parse==0.3.0
llama-parse==0.5.13
llvmlite==0.43.0
loguru==0.7.2
lxml==5.3.0
markdown-it-py==3.0.0
markdownify==0.13.1
MarkupSafe==3.0.1
marshmallow==3.23.1
marshmallow-enum==1.5.1
matplotlib==3.9.2
matplotlib-inline==0.1.7
mccabe==0.7.0
mdurl==0.1.2
megaparse==0.0.43
megaparse-sdk==0.1.7
monotonic==1.6
mplcursors==0.6
mpmath==1.3.0
msal==1.31.0
msgpack==1.1.0
multidict==6.1.0
mypy==1.13.0
mypy-extensions==1.0.0
nats-py==2.9.0
nest-asyncio==1.6.0
networkx==3.2.1
nltk==3.9.1
nodeenv==1.9.1
notion-client==2.2.1
numba==0.60.0
numpy==1.26.3
oauthlib==3.2.2
openai==1.54.4
opencv-python==4.10.0.84
openpyxl==3.1.5
opentelemetry-api==1.27.0
opentelemetry-exporter-otlp==1.27.0
opentelemetry-exporter-otlp-proto-common==1.27.0
opentelemetry-exporter-otlp-proto-grpc==1.27.0
opentelemetry-exporter-otlp-proto-http==1.27.0
opentelemetry-instrumentation==0.48b0
opentelemetry-proto==1.27.0
opentelemetry-sdk==1.27.0
opentelemetry-semantic-conventions==0.48b0
orjson==3.10.11
packaging==23.2
pandas==2.2.3
parameterized==0.9.0
parso==0.8.4
pathspec==0.12.1
pdf2image==1.17.0
pexpect==4.9.0
pgvector==0.3.6
pillow==10.2.0
platformdirs==4.3.6
playwright==1.48.0
pluggy==1.5.0
ply==3.11
postgrest==0.17.2
posthog==3.7.0
pre_commit==4.0.1
prometheus_client==0.21.0
prompt_toolkit==3.0.48
propcache==0.2.0
proto-plus==1.25.0
protobuf==4.25.5
psutil==6.1.0
psycopg2-binary==2.9.10
ptyprocess==0.7.0
pure_eval==0.2.3
py-cpuinfo==9.0.0
pyasn1==0.6.1
pyasn1_modules==0.4.1
pyclipper==1.3.0.post6
pycodestyle==2.12.1
pycparser==2.22
pycryptodome==3.21.0
pydantic==2.9.2
pydantic-settings==2.6.1
pydantic_core==2.23.4
pyee==12.0.0
pyflakes==3.2.0
Pygments==2.18.0
pyinstrument==5.0.0
PyJWT==2.9.0
pyparsing==3.2.0
pypdf==5.1.0
pypdfium2==4.30.0
pyproject-api==1.6.1
pytest==8.3.3
pytest-asyncio==0.24.0
pytest-benchmark==5.1.0
pytest-cov==6.0.0
pytest-dotenv==0.5.2
pytest-mock==3.14.0
pytest-profiling==1.7.0
pytest-xdist==3.6.1
python-dateutil==2.9.0.post0
python-doctr==0.10.0
python-dotenv==1.0.1
python-engineio==4.10.1
python-iso639==2024.10.22
python-jose==3.3.0
python-json-logger==2.0.7
python-magic==0.4.27
python-multipart==0.0.9
python-socketio==5.11.4
pytz==2024.2
PyYAML==6.0.2
pyzmq==26.2.0
RapidFuzz==3.10.1
realtime==2.0.6
redis==5.2.0
referencing==0.35.1
regex==2024.9.11
requests==2.32.3
requests-oauthlib==2.0.0
requests-toolbelt==1.0.0
resend==2.4.0
rich==13.9.4
rpds-py==0.20.1
rsa==4.9
ruff==0.7.2
safetensors==0.4.5
scikit-learn==1.5.2
scipy==1.14.1
sentencepiece==0.2.0
sentry-sdk==2.18.0
shapely==2.0.6
simple-websocket==1.1.0
six==1.16.0
sniffio==1.3.1
soupsieve==2.6
SQLAlchemy==2.0.36
sqlmodel==0.0.22
stack-data==0.6.3
starlette==0.41.2
stone==3.3.1
storage3==0.8.2
striprtf==0.0.26
structlog==24.4.0
supabase==2.9.1
supafunc==0.6.2
sympy==1.13.1
syncer==2.0.3
tabulate==0.9.0
tenacity==8.5.0
threadpoolctl==3.5.0
tiktoken==0.8.0
tokenizers==0.20.1
tomli==2.1.0
torch==2.4.0
torchvision==0.19.0
tornado==6.4.1
tox==4.15.1
tqdm==4.66.5
traitlets==5.14.3
transformers==4.46.1
types-cffi==1.16.0.20240331
types-pyOpenSSL==24.1.0.20240722
types-PyYAML==6.0.12.20240917
types-redis==4.6.0.20241004
types-requests==2.31.0.6
types-setuptools==75.2.0.20241025
types-urllib3==1.26.25.14
typing-inspect==0.9.0
typing_extensions==4.12.2
tzdata==2024.2
Unidecode==1.3.8
unstructured==0.15.0
unstructured-client==0.8.1
uptrace==1.27.0
uritemplate==4.1.1
urllib3==1.26.13
uvicorn==0.25.0
uvloop==0.21.0
vine==5.1.0
virtualenv==20.27.1
watchfiles==0.20.0
wcwidth==0.2.13
websockets==13.1
wrapt==1.16.0
wsproto==1.2.0
yarl==1.17.1
zipp==3.20.2
```

**Comment by pranitsawant80** [comment]
from langchain_core.messages import HumanMessage, AIMessage
from pydantic import BaseModel
from typing import List, Any, Generator, Tuple, Dict
from datetime import datetime
from uuid import UUID, uuid4

class ChatMessage(BaseModel):
    chat_id: UUID
    message_id: UUID
    brain_id: UUID | None
    msg_type: str
#############################################################
    content: Dict[str, Any]
 ########################################################   
    message_time: datetime
    metadata: Dict[str, Any]

class ChatHistory:
    def __init__(self, chat_id: UUID, brain_id: UUID | None) -> None:
        self.id = chat_id
        self.brain_id = brain_id
        self._msgs: List[ChatMessage] = []

    def get_chat_history(self, newest_first: bool = False) -> List[ChatMessage]:
        history = sorted(self._msgs, key=lambda msg: msg.message_time)
        return history[::-1] if newest_first else history

    def __len__(self):
        return len(self._msgs)

    def append(self, langchain_msg: AIMessage | HumanMessage, metadata: Dict[str, Any] = {}):
#####################################################
        msg_type = langchain_msg.__class__.__name__
        **content = {
            "content": langchain_msg.content
          
        }
      ###########################################################  
        chat_msg = ChatMessage(
            chat_id=self.id,
            message_id=uuid4(),
            brain_id=self.brain_id,
            msg_type=msg_type,
            content=content,
            message_time=datetime.now(),
            metadata=metadata,
        )
        self._msgs.append(chat_msg)
##################################################################################
    def iter_pairs(self) -> Generator[Tuple[HumanMessage, AIMessage], None, None]:
        it = iter(self.get_chat_history(newest_first=True))
        for ai_message, human_message in zip(it, it, strict=False):
            if isinstance(human_message.content['content'], HumanMessage) and isinstance(ai_message.content['content'], AIMessage):
                yield (human_message.content['content'], ai_message.content['content'])

    def to_list(self) -> List[HumanMessage | AIMessage]:
        return [_msg.content['content'] for _msg in self._msgs]
#############################################################################
if __name__ == "__main__":
    human_msg = HumanMessage(content="I'm human")
    ai_msg = AIMessage(content="I'm AI")

    chat_history = ChatHistory(chat_id=uuid4(), brain_id=uuid4())
    chat_history.append(human_msg)
    chat_history.append(ai_msg)



Check this it might help..

The issue with langchain core   undersite packages..in ai.py file 

I tried installing the newly updated version for langchain core  ie.  0.3.22      But it did not help...

So I thought of changing our logic rather than changing that ai.py file.. 

I have put changes under ##############    in the above code. 
changes are in ChatMessage module -include a content dictionary field
append method - passing content after wrapping it under the dictionary
iter_pair - have changed to make it work for new modifications

You can adjust functions accordingly and remove unnecessary lines...

Hope this will help...🙏

**Comment by jacopo-chevallard** [comment]
Perhaps @keenborder786 or @Jakolo121, who helped on #26967, can confirm whether this is a bug or not?

**Comment by jacopo-chevallard** [comment]
thanks for the feedback @Jakolo121 

> So I guess this is not a bug. But I didn't test your code on my environment.

Ok, if you get the chance to test it, it would be great (and useful for the LangChain folks, I guess, to confirm the existence of a bug)

**Comment by Jakolo121** [comment]
I tried your code in the environment from the #26967 issue and it did not work. I also tested your code in a new environment. With the same result. I created the new env with Python 3.13 and 3.12

**Comment by jacopo-chevallard** [comment]
Thanks for your precious feedback @Jakolo121, I guess I'll wait for some feedback from the LangChain folks cc @ccurme @efriis @eyurtsev

**Comment by efriis** [comment]
simplest repro here. This is something weird going on in pydantic, not langchain

```
from pydantic import BaseModel

from langchain_core.messages import AIMessage, HumanMessage

class ChatMessage(BaseModel):
    msg: AIMessage | HumanMessage

ChatMessage(
    msg=HumanMessage(content="i'm human")
)
```

if you switch the order of the type, it works. I don't know why - some of these pydantic things are a mystery. Probably something to do with some type inference on the first type that gets passed in.
```
class ChatMessage(BaseModel):
    msg: HumanMessage | AIMessage
```

**Comment by jacopo-chevallard** [comment]
Thanks a lot @efriis, I would have never thought about switching the order! ;-)
