### ISSUE TITLE
UnstructuredMarkdownLoader can not load a markdown file which contains emoji

### ISSUE THREAD

**Issue by lesliechueng1996** [langchain-ai/langchain#28779]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from langchain_community.document_loaders import UnstructuredMarkdownLoader

loader = UnstructuredMarkdownLoader(
    file_path="./file.md",
)

docs = loader.load()
print(len(docs))
```

Here is the file.md
```markdown
🎉

```

### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "/Users/leslie/Documents/code/llm-ops/llm-ops-api/study/23-LangChain内置文档加载器使用/Markdown文档加载器.py", line 22, in <module>
    docs = loader.load()
  File "/Users/leslie/Documents/code/llm-ops/llm-ops-api/venv/lib/python3.10/site-packages/langchain_core/document_loaders/base.py", line 31, in load
    return list(self.lazy_load())
  File "/Users/leslie/Documents/code/llm-ops/llm-ops-api/venv/lib/python3.10/site-packages/langchain_community/document_loaders/unstructured.py", line 107, in lazy_load
    elements = self._get_elements()
  File "/Users/leslie/Documents/code/llm-ops/llm-ops-api/venv/lib/python3.10/site-packages/langchain_community/document_loaders/markdown.py", line 86, in _get_elements
    return partition_md(filename=self.file_path, **self.unstructured_kwargs)  # type: ignore[arg-type]
  File "/Users/leslie/Documents/code/llm-ops/llm-ops-api/venv/lib/python3.10/site-packages/unstructured/partition/md.py", line 78, in partition_md
    return partition_html(
  File "/Users/leslie/Documents/code/llm-ops/llm-ops-api/venv/lib/python3.10/site-packages/unstructured/partition/common/metadata.py", line 162, in wrapper
    elements = func(*args, **kwargs)
  File "/Users/leslie/Documents/code/llm-ops/llm-ops-api/venv/lib/python3.10/site-packages/unstructured/chunking/dispatch.py", line 74, in wrapper
    elements = func(*args, **kwargs)
  File "/Users/leslie/Documents/code/llm-ops/llm-ops-api/venv/lib/python3.10/site-packages/unstructured/partition/html/partition.py", line 91, in partition_html
    return list(_HtmlPartitioner.iter_elements(opts))
  File "/Users/leslie/Documents/code/llm-ops/llm-ops-api/venv/lib/python3.10/site-packages/unstructured/partition/html/partition.py", line 197, in iter_elements
    yield from cls(opts)._iter_elements()
  File "/Users/leslie/Documents/code/llm-ops/llm-ops-api/venv/lib/python3.10/site-packages/unstructured/partition/html/partition.py", line 205, in _iter_elements
    self._main.iter_elements()
  File "/Users/leslie/Documents/code/llm-ops/llm-ops-api/venv/lib/python3.10/site-packages/unstructured/utils.py", line 154, in __get__
    value = self._fget(obj)
  File "/Users/leslie/Documents/code/llm-ops/llm-ops-api/venv/lib/python3.10/site-packages/unstructured/partition/html/partition.py", line 234, in _main
    etree.strip_elements(
  File "src/lxml/cleanup.pxi", line 100, in lxml.etree.strip_elements
  File "src/lxml/apihelpers.pxi", line 41, in lxml.etree._documentOrRaise
TypeError: Invalid input object: NoneType

### Description

I am trying to use the UnstructuredMarkdownLoader to load an markdown file.
I expect it can load successfully.
After many tests, I found that if the markdown file contains this symbol 🎉, it will cause the program to crash.

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 24.2.0: Fri Dec  6 19:02:12 PST 2024; root:xnu-11215.61.5~2/RELEASE_ARM64_T6031
> Python Version:  3.10.11 (v3.10.11:7d4cc5aa85, Apr  4 2023, 19:05:19) [Clang 13.0.0 (clang-1300.0.29.30)]

Package Information
-------------------
> langchain_core: 0.3.25
> langchain: 0.3.12
> langchain_community: 0.3.12
> langsmith: 0.1.147
> langchain_cohere: 0.3.3
> langchain_experimental: 0.3.3
> langchain_huggingface: 0.1.2
> langchain_openai: 0.2.11
> langchain_pinecone: 0.2.0
> langchain_text_splitters: 0.3.3
> langchain_unstructured: 0.1.6
> langchain_weaviate: 0.0.3
> langgraph_sdk: 0.1.43

Optional packages not installed
-------------------------------
> langserve

Other Dependencies
------------------
> aiohttp: 3.9.5
> async-timeout: 4.0.3
> cohere: 5.13.3
> dataclasses-json: 0.6.7
> httpx: 0.27.0
> httpx-sse: 0.4.0
> huggingface-hub: 0.26.3
> jsonpatch: 1.33
> langsmith-pyo3: Installed. No version info available.
> numpy: 1.26.4
> onnxruntime: 1.19.2
> openai: 1.57.0
> orjson: 3.10.12
> packaging: 24.2
> pandas: 2.2.3
> pinecone-client: 5.0.1
> pydantic: 2.9.2
> pydantic-settings: 2.6.1
> PyYAML: 6.0.2
> requests: 2.32.3
> requests-toolbelt: 1.0.0
> sentence-transformers: 3.3.1
> simsimd: 4.4.0
> SQLAlchemy: 2.0.36
> tabulate: 0.9.0
> tenacity: 8.5.0
> tiktoken: 0.8.0
> tokenizers: 0.20.3
> transformers: 4.46.3
> typing-extensions: 4.12.2
> unstructured-client: 0.28.1
> unstructured[all-docs]: Installed. No version info available.
> weaviate-client: 4.9.6

**Comment by keenborder786** [comment]
I am not so sure what you are doing. But it is working for me, can you please upgrade `unstructured` pacakge?
