### ISSUE TITLE
GPTCache similarity caching code example encountered an error during execution.

### ISSUE THREAD

**Issue by gaye746560359** [langchain-ai/langchain#2879]
`import os
import time
import gptcache
from gptcache.processor.pre import get_prompt
from gptcache.manager.factory import get_data_manager
from langchain.cache import GPTCache, SQLiteCache
from gptcache.manager import get_data_manager, CacheBase, VectorBase
from gptcache import Cache
from gptcache.embedding import Onnx
from gptcache.similarity_evaluation.distance import SearchDistanceEvaluation
from langchain.llms import OpenAI
import langchain
import openai
from decouple import config

os.environ["OPENAI_API_KEY"] = config("OPENAI_API_KEY")
openai.api_base = config("OPENAI_API_BASE")

llm = OpenAI(model_name="text-davinci-002", n=1, best_of=1)
i = 0
file_prefix = "data_map"
llm_cache = Cache()

def init_gptcache_map(cache_obj: gptcache.Cache):
    global i
    cache_path = f'{file_prefix}_{i}.txt'
    onnx = Onnx()
    cache_base = CacheBase('sqlite')
    vector_base = VectorBase('faiss', dimension=onnx.dimension)
    data_manager = get_data_manager(cache_base, vector_base, max_size=10, clean_size=2)
    cache_obj.init(
        pre_embedding_func=get_prompt,
        embedding_func=onnx.to_embeddings,
        data_manager=data_manager,
        similarity_evaluation=SearchDistanceEvaluation(),
    )
    i += 1

langchain.llm_cache = GPTCache(init_gptcache_map)

llm("Tell me a joke")
`

error:
`Traceback (most recent call last):
  File "D:\chat-main\tt.py", line 43, in <module>
    llm("Tell me a joke")
  File "D:\chat-main\venv\Lib\site-packages\langchain\llms\base.py", line 246, in __call__
    return self.generate([prompt], stop=stop).generations[0][0].text
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\chat-main\venv\Lib\site-packages\langchain\llms\base.py", line 161, in generate
    llm_output = update_cache(
                 ^^^^^^^^^^^^^
  File "D:\chat-main\venv\Lib\site-packages\langchain\llms\base.py", line 51, in update_cache
    langchain.llm_cache.update(prompt, llm_string, result)
  File "D:\chat-main\venv\Lib\site-packages\langchain\cache.py", line 255, in update
    return adapt(
           ^^^^^^
  File "D:\chat-main\venv\Lib\site-packages\gptcache\adapter\adapter.py", line 22, in adapt
    embedding_data = time_cal(
                     ^^^^^^^^^
  File "D:\chat-main\venv\Lib\site-packages\gptcache\__init__.py", line 25, in inner
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "D:\chat-main\venv\Lib\site-packages\gptcache\embedding\onnx.py", line 58, in to_embeddings
    ort_outputs = self.ort_session.run(None, ort_inputs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files (x86)\Python311\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(int32)) , expected: (tensor(int64))`

**Comment by kennethleungty** [comment]
It worked for me the first time, but got the same error as above on subsequent tries. It seems like this error affects the similarity matching. On the other hand, when I revert to exact matching, the problem above does not happen. Certainly look forward to a solution to this since similarity matching is vital

**Comment by xusheng-gong** [comment]
I met same problem:
File "C:\Users\xxxxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\langchain\llms\base.py", line 246, in __call__
    return self.generate([prompt], stop=stop).generations[0][0].text    
  File "C:\Users\xxxxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\langchain\llms\base.py", line 161, in generate
    llm_output = update_cache(
  File "C:\Users\xxxxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\langchain\llms\base.py", line 51, in update_cache
    res = func(*args, **kwargs)
  File "C:\Users\xxxxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gptcache\embedding\onnx.py", line 58, in to_embeddings
    ort_outputs = self.ort_session.run(None, ort_inputs)
  File "C:\Users\xxxxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(int32)) , expected: (tensor(int64))

**Comment by keenborder786** [comment]
Any updates on this.

**Comment by manish-andankar** [comment]
I get the following error when using GPTCache with similarity search. I used the GPTCache example as is from the official documentation.
https://python.langchain.com/docs/integrations/llms/llm_caching 

None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
An exception is encountered during while trying to get the response from OpenAI. Details:  [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: token_type_ids for the following indices
 index: 1 Got: 528 Expected: 512
 Please fix either the inputs or the model.

**Comment by UmerQam** [comment]
I am also getting error when using similarity caching example mentioned in the  - [langchain page]([](https://python.langchain.com/docs/integrations/llms/llm_caching)). There is no issue when exact GPT caching is used 

`InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: token_type_ids for the following indices
 index: 1 Got: 1772 Expected: 512
 Please fix either the inputs or the model.`

**Comment by rishumehrotra** [comment]
any updates on this ? still hitting the same error :(

**Comment by anitaokoh** [comment]
any update on this? Still having the same error

**Comment by urirosenberg** [comment]
Same. Trying to integrate with `RetrievalQA` but also getting ONNXRuntimeError:
`InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: token_type_ids for the following indices
 index: 1 Got: 2436 Expected: 512
 Please fix either the inputs or the model.`
