### ISSUE TITLE
Error in RAG tutorials

### ISSUE THREAD

**Issue by wenzhaoabc** [langchain-ai/langchain#28866]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

get error when run the rag tutorials code

```py
import dotenv
from langchain import hub
from langchain_community.document_loaders import TextLoader
from langchain_core.documents import Document
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langgraph.graph import START, StateGraph
from typing_extensions import List, TypedDict
from langchain_community.vectorstores import FAISS
from langchain_openai import OpenAIEmbeddings
from langchain_community.docstore.in_memory import InMemoryDocstore
from langchain_openai import ChatOpenAI
import faiss

dotenv.load_dotenv()

# Load and chunk contents of the blog
docs = list[Document]
loader = TextLoader("../devs/ragtest/input/mmkg_rag.txt")
docs = loader.load()

text_splitter = RecursiveCharacterTextSplitter(chunk_size=1200, chunk_overlap=100)
all_splits = text_splitter.split_documents(docs)

embeddings = OpenAIEmbeddings(model="text-embedding-3-large")
index = faiss.IndexFlatL2()
vector_store = FAISS(
    embedding_function=embeddings,
    index=index,
    docstore=InMemoryDocstore(),
    index_to_docstore_id={},
)
# Index chunks
_ = vector_store.add_documents(documents=all_splits)

llm = ChatOpenAI(model="gpt-4o-mini", temperature=0.0)

# Define prompt for question-answering
prompt = hub.pull("rlm/rag-prompt")


# Define state for application
class State(TypedDict):
    question: str
    context: List[Document]
    answer: str


# Define application steps
def retrieve(state: State):
    retrieved_docs = vector_store.similarity_search(state["question"])
    return {"context": retrieved_docs}


def generate(state: State):
    docs_content = "\n\n".join(doc.page_content for doc in state["context"])
    messages = prompt.invoke({"question": state["question"], "context": docs_content})
    response = llm.invoke(messages)
    return {"answer": response.content}


# Compile application and test
graph_builder = StateGraph(State).add_sequence([retrieve, generate])
graph_builder.add_edge(START, "retrieve")
graph = graph_builder.compile()


response = graph.invoke({"question": "What components are in MMKG_RAG?"})
print(response["answer"])
```

### Error Message and Stack Trace (if applicable)

```txt
Traceback (most recent call last):
  File "~\workspace\projects\xxx\repos\graphrag\repeat\nativerag.py", line 33, in <module>
    _ = vector_store.add_documents(documents=all_splits)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\miniconda3\envs\py311\Lib\site-packages\langchain_core\vectorstores\base.py", line 287, in add_documents  
    return self.add_texts(texts, metadatas, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\miniconda3\envs\py311\Lib\site-packages\langchain_community\vectorstores\faiss.py", line 341, in add_texts
    return self.__add(texts, embeddings, metadatas=metadatas, ids=ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\miniconda3\envs\py311\Lib\site-packages\langchain_community\vectorstores\faiss.py", line 313, in __add    
    self.index.add(vector)
  File "~\miniconda3\envs\py311\Lib\site-packages\faiss\class_wrappers.py", line 228, in replacement_add
    assert d == self.d
           ^^^^^^^^^^^
AssertionError
```

### Description

some errro in tutorial code about FAISS

### System Info

System Information
------------------
> OS:  Windows
> OS Version:  10.0.19045
> Python Version:  3.11.11 | packaged by Anaconda, Inc. | (main, Dec 11 2024, 16:34:19) [MSC v.1929 64 bit (AMD64)]

Package Information
-------------------
> langchain_core: 0.3.28
> langchain: 0.3.13
> langchain_community: 0.3.13
> langsmith: 0.2.4
> langchain_openai: 0.2.14
> langchain_text_splitters: 0.3.4
> langgraph_sdk: 0.1.48

Optional packages not installed
-------------------------------
> langserve

Other Dependencies
------------------
> aiohttp: 3.11.11
> async-timeout: Installed. No version info available.
> dataclasses-json: 0.6.7
> httpx: 0.28.1
> httpx-sse: 0.4.0
> jsonpatch: 1.33
> langsmith-pyo3: Installed. No version info available.
> numpy: 1.26.4
> openai: 1.58.1
> orjson: 3.10.12
> packaging: 24.2
> pydantic: 2.9.2
> pydantic-settings: 2.7.0
> PyYAML: 6.0.2
> requests: 2.32.3
> requests-toolbelt: 1.0.0
> SQLAlchemy: 2.0.36
> tenacity: 9.0.0
> tiktoken: 0.8.0
> typing-extensions: 4.12.2

**Comment by keenborder786** [comment]
Just do this and it should fix your issue.

```python
index = faiss.IndexFlatL2(len(OpenAIEmbeddings(model="text-embedding-3-large").embed_query("hello world")))
```

**Comment by wenzhaoabc** [comment]
Thank you for your help! The issue has been resolved. I also suggest updating the documentation on the website to help other users who might encounter similar issues.

Thanks again for the support!
