### ISSUE TITLE
message of type RemoveMessage is not handled in langchain-

### ISSUE THREAD

**Issue by daher928** [langchain-ai/langchain#28900]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
from langchain_openai.chat_models.base import _convert_message_to_dict
from langchain_core.messages import RemoveMessage
_convert_message_to_dict(RemoveMessage(id="1"))
```

### Error Message and Stack Trace (if applicable)

```
Traceback (most recent call last):
  File "/Users/projects/my-chat/main.py", line 23, in <module>
    _convert_message_to_dict(RemoveMessage(id="1"))
  File "/Users/.pyenv/versions/chat/lib/python3.11/site-packages/langchain_openai/chat_models/base.py", line 257, in _convert_message_to_dict
    raise TypeError(f"Got unknown type {message}")
TypeError: Got unknown type content='' additional_kwargs={} response_metadata={} id='1'
```

### Description

In langchain_openai.chat_models.base (and more specifically in langchain_openai.chat_models.base._convert_message_to_dict) there is no handling of messages of type RemoveMessage and it fails over unknown type

### System Info

```
System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.6.0: Thu Sep 12 23:35:10 PDT 2024; root:xnu-10063.141.1.701.1~1/RELEASE_ARM64_T6030
> Python Version:  3.11.6 (main, Jun 24 2024, 09:02:31) [Clang 15.0.0 (clang-1500.3.9.4)]

Package Information
-------------------
> langchain_core: 0.3.28
> langchain: 0.3.13
> langchain_community: 0.3.13
> langsmith: 0.2.4
> langchain_experimental: 0.3.4
> langchain_openai: 0.2.14
> langchain_text_splitters: 0.3.4
> langgraph_api: 0.0.15
> langgraph_cli: 0.1.65
> langgraph_license: Installed. No version info available.
> langgraph_platform: Installed. No version info available.
> langgraph_sdk: 0.1.48
> langgraph_storage: Installed. No version info available.

Optional packages not installed
-------------------------------
> langserve

Other Dependencies
------------------
> aiohttp: 3.11.11
> async-timeout: Installed. No version info available.
> click: 8.1.8
> cryptography: 43.0.3
> dataclasses-json: 0.6.7
> httpx: 0.28.1
> httpx-sse: 0.4.0
> jsonpatch: 1.33
> jsonschema-rs: 0.25.1
> langgraph: 0.2.60
> langgraph-checkpoint: 2.0.9
> langsmith-pyo3: Installed. No version info available.
> numpy: 1.26.4
> openai: 1.58.1
> orjson: 3.10.12
> packaging: 24.2
> pydantic: 2.10.4
> pydantic-settings: 2.7.0
> pyjwt: 2.10.1
> python-dotenv: 1.0.1
> PyYAML: 6.0.2
> requests: 2.32.3
> requests-toolbelt: 1.0.0
> SQLAlchemy: 2.0.36
> sse-starlette: 2.1.3
> starlette: 0.41.3
> structlog: 24.4.0
> tenacity: 8.5.0
> tiktoken: 0.8.0
> typing-extensions: 4.12.2
> uvicorn: 0.34.0
> watchfiles: 1.0.3

```

**Comment by daher928** [comment]
@hwchase17 Hello Harrison, could you please take a lot at this issue?

**Comment by efriis** [comment]
Assigning to @vbarda ! I believe the `RemoveMessage` was intended as a langgraph feature, and we may want to add this as a feature of `BaseChatModel` to remove this confusion.

I don't think this is a regression (i.e. this always behaved this way). Let me know if that seems right to you!

**Comment by ddaher-augury** [comment]
It happens when I try to remove messages from graph state in LangGraph and using Azure chat model

I would appreciate fixing it as soon as possible! :) 

Thanks!

**Comment by daher928** [comment]
@efriis  It happens when I try to remove messages from graph state in LangGraph and using Azure chat model

I would appreciate fixing it as soon as possible! :)

Thanks!

**Comment by eyurtsev** [comment]
Hi @daher928 it's holidays season so many of the maintainers are out of office for another week.

The issue looks like usage error rather than a bug from the given explanation and code snippet.

Remove message should never be sent to a chat model. It's a message type that's used only by the persistence layer of langgraph. If you can share an example of the code you're using with langgraph.

**Comment by daher928** [comment]
Hi @eyurtsev thanks for your comment

What I'm trying to achieve is summarizing the conversation as part of the LLM node (after reaching a certain tokens count threshold) and remove messages from history and graph state. 
(note: I am using AzureChatOpenAI, an my own custom SingleStore checkpointer)

This is the code snippet, part of my ReAct LangGraph agent: 

```
    def call_model(self, state: AgentState):
        """
        Node: calls LLM model
        """
        messages = state['messages']
        previous_messages = messages[:-1]
        last_message = messages[-1]

        if len(messages) > 2 and isinstance(last_message, HumanMessage):
            tokens_count = self.count_tokens(str(messages))
            if tokens_count > MAX_PROMPT_TOKENS_COUNT:
                messages = self.summarize_conversation(previous_messages, state) + [last_message]

        if self.system:
            messages = [SystemMessage(content=self.system)] + messages

        response = self.model.invoke(messages)
        return {'messages': [response]}

    @traceable
    def summarize_conversation(self, messages, state: AgentState) -> list[AnyMessage]:
        summary_message = "Create a summary of the conversation above and start the response with \"summary of the conversation so far\":"
        messages = messages + [HumanMessage(content=summary_message)]
        response = model.invoke(messages)
        summary_message = SystemMessage(content=response.content)
        delete_messages = [RemoveMessage(id=m.id) for m in state["messages"][:-1]]
        return delete_messages + [summary_message]
```

The result of this code is the exception I mentioned in the issue:
```
  File "agent/agent.py", line 248, in invoke_agent
    result = agent.graph.invoke({"messages": messages}, config=agent.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.pyenv/versions/chat/lib/python3.11/site-packages/langgraph/pregel/__init__.py", line 1936, in invoke
    for chunk in self.stream(
  File "/.pyenv/versions/chat/lib/python3.11/site-packages/langgraph/pregel/__init__.py", line 1656, in stream
    for _ in runner.tick(
  File "/.pyenv/versions/chat/lib/python3.11/site-packages/langgraph/pregel/runner.py", line 167, in tick
    run_with_retry(
  File "/.pyenv/versions/chat/lib/python3.11/site-packages/langgraph/pregel/retry.py", line 40, in run_with_retry
    return task.proc.invoke(task.input, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.pyenv/versions/chat/lib/python3.11/site-packages/langgraph/utils/runnable.py", line 408, in invoke
    input = step.invoke(input, config, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.pyenv/versions/chat/lib/python3.11/site-packages/langgraph/utils/runnable.py", line 184, in invoke
    ret = context.run(self.func, input, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "agent/agent.py", line 127, in call_model
    response = self.model.invoke(messages)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.pyenv/versions/chat/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 5354, in invoke
    return self.bound.invoke(
           ^^^^^^^^^^^^^^^^^^
  File "/.pyenv/versions/chat/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 286, in invoke
    self.generate_prompt(
  File "/.pyenv/versions/chat/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 786, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.pyenv/versions/chat/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 643, in generate
    raise e
  File "/.pyenv/versions/chat/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 633, in generate
    self._generate_with_cache(
  File "/.pyenv/versions/chat/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 851, in _generate_with_cache
    result = self._generate(
             ^^^^^^^^^^^^^^^
  File "/.pyenv/versions/chat/lib/python3.11/site-packages/langchain_openai/chat_models/base.py", line 702, in _generate
    payload = self._get_request_payload(messages, stop=stop, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.pyenv/versions/chat/lib/python3.11/site-packages/langchain_openai/chat_models/base.py", line 732, in _get_request_payload
    "messages": [_convert_message_to_dict(m) for m in messages],
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.pyenv/versions/chat/lib/python3.11/site-packages/langchain_openai/chat_models/base.py", line 732, in <listcomp>
    "messages": [_convert_message_to_dict(m) for m in messages],
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.pyenv/versions/chat/lib/python3.11/site-packages/langchain_openai/chat_models/base.py", line 257, in _convert_message_to_dict
    raise TypeError(f"Got unknown type {message}")
TypeError: Got unknown type content='' additional_kwargs={} response_metadata={} id='ed223326-b423-46c9-bec3-5d61590debed'
During task with name 'llm' and id '843ba5e5-455a-f79b-b1de-23578844069e'
```

**Comment by eyurtsev** [comment]
Yeah the code is passing RemoveMessage into a chat model which won't work. 

RemoveMessage needs to be used together with an appropriate reducer and is meant to be used as part of a state update. 

We need to clarify this in the docs.

For your code start from a working summarization example in langgraph docs and then adapt to your use case.

**Comment by daher928** [comment]
I made some modifications and I did almost exactly as this guide suggests: https://langchain-ai.github.io/langgraph/how-tos/memory/add-summary-conversation-history/ 
only difference is I am using AzureChatOpenAI, and still get this error in the next iteration (so for example if the current iteration did pass throw summarizer node, the next iteration will fail)

my graph looks like this:
![image](https://github.com/user-attachments/assets/02d38ee8-c815-4e71-a75b-dbbe80f92225)

**Comment by eyurtsev** [comment]
The example from the docs is very different structurally from what your code does, and it's not related to which chat model is used. pass remove message to a **state update** with an appropriate **reducer**. instead your code is currently assing it directly to a chat model.

Start from the example which works correctly, swap the model there, and verify that it still works.

**Comment by daher928** [comment]
Thanks @eyurtsev ! I was able to solve it with your help
Closing this issue
