### ISSUE TITLE
jinja2 is not optional

### ISSUE THREAD

**Issue by dalazx** [langchain-ai/langchain#3113]
langchain was installed via `pip`

```
Traceback (most recent call last):
  File "/Users/oleksandrdanshyn/github.com/dalazx/langchain/test.py", line 1, in <module>
    from langchain.agents import load_tools, initialize_agent, AgentType
  File "/Users/oleksandrdanshyn/github.com/dalazx/langchain/langchain/__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "/Users/oleksandrdanshyn/github.com/dalazx/langchain/langchain/agents/__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "/Users/oleksandrdanshyn/github.com/dalazx/langchain/langchain/agents/agent.py", line 17, in <module>
    from langchain.chains.base import Chain
  File "/Users/oleksandrdanshyn/github.com/dalazx/langchain/langchain/chains/__init__.py", line 2, in <module>
    from langchain.chains.api.base import APIChain
  File "/Users/oleksandrdanshyn/github.com/dalazx/langchain/langchain/chains/api/base.py", line 8, in <module>
    from langchain.chains.api.prompt import API_RESPONSE_PROMPT, API_URL_PROMPT
  File "/Users/oleksandrdanshyn/github.com/dalazx/langchain/langchain/chains/api/prompt.py", line 2, in <module>
    from langchain.prompts.prompt import PromptTemplate
  File "/Users/oleksandrdanshyn/github.com/dalazx/langchain/langchain/prompts/__init__.py", line 3, in <module>
    from langchain.prompts.chat import (
  File "/Users/oleksandrdanshyn/github.com/dalazx/langchain/langchain/prompts/chat.py", line 10, in <module>
    from langchain.memory.buffer import get_buffer_string
  File "/Users/oleksandrdanshyn/github.com/dalazx/langchain/langchain/memory/__init__.py", line 11, in <module>
    from langchain.memory.entity import (
  File "/Users/oleksandrdanshyn/github.com/dalazx/langchain/langchain/memory/entity.py", line 8, in <module>
    from langchain.chains.llm import LLMChain
  File "/Users/oleksandrdanshyn/github.com/dalazx/langchain/langchain/chains/llm.py", line 11, in <module>
    from langchain.prompts.prompt import PromptTemplate
  File "/Users/oleksandrdanshyn/github.com/dalazx/langchain/langchain/prompts/prompt.py", line 8, in <module>
    from jinja2 import Environment, meta
ModuleNotFoundError: No module named 'jinja2'
```

since `prompt.py` is one of the fundamental modules and it unconditionally imports `jinja2`, `jinja2` should probably be added to the list of required dependencies.

**Comment by setu4993** [comment]
Just ran into the same issue.

**Comment by outday29** [comment]
I see this issue is due to #3013. I opened a pull request in #3123 that makes `langchain` only imports `jinja2` when `jinja2` prompt template is used. Thanks for pointing that out.

**Comment by setu4993** [comment]
Should be fixed in the latest release.
