### ISSUE TITLE
File cannot be written: WriteFileTool() throws validation error for WriteFileInput text

### ISSUE THREAD

**Issue by stefan-wiesner** [langchain-ai/langchain#3165]
I am trying to improve BabyAGI with agents example from this repo to read a file, optimize it and write the file.

I added this to the tools as from the AutoGPT example next to search and todo:

`    WriteFileTool(),
    ReadFileTool(),`

Prompt is to "Write the optimized code into a file". 

ReadFileTool is working fine... 

It looks like type is missing as a parameter even. Do I need to pass something to the tool or what am I doing wrong?
I get the following error:

`Traceback (most recent call last):
  File "baby_agi_with_agent.py", line 136, in <module>
    baby_agi({"objective": OBJECTIVE})
  File "/home/dev/anaconda3/envs/langchain/lib/python3.8/site-packages/langchain/chains/base.py", line 116, in __call__
    raise e
  File "/home/dev/anaconda3/envs/langchain/lib/python3.8/site-packages/langchain/chains/base.py", line 113, in __call__
    outputs = self._call(inputs)
  File "/home/dev/anaconda3/envs/langchain/lib/python3.8/site-packages/langchain/experimental/autonomous_agents/baby_agi/baby_agi.py", line 130, in _call
    result = self.execute_task(objective, task["task_name"])
  File "/home/dev/anaconda3/envs/langchain/lib/python3.8/site-packages/langchain/experimental/autonomous_agents/baby_agi/baby_agi.py", line 111, in execute_task
    return self.execution_chain.run(
  File "/home/dev/anaconda3/envs/langchain/lib/python3.8/site-packages/langchain/chains/base.py", line 216, in run
    return self(kwargs)[self.output_keys[0]]
  File "/home/dev/anaconda3/envs/langchain/lib/python3.8/site-packages/langchain/chains/base.py", line 116, in __call__
    raise e
  File "/home/dev/anaconda3/envs/langchain/lib/python3.8/site-packages/langchain/chains/base.py", line 113, in __call__
    outputs = self._call(inputs)
  File "/home/dev/anaconda3/envs/langchain/lib/python3.8/site-packages/langchain/agents/agent.py", line 792, in _call
    next_step_output = self._take_next_step(
  File "/home/dev/anaconda3/envs/langchain/lib/python3.8/site-packages/langchain/agents/agent.py", line 695, in _take_next_step
    observation = tool.run(
  File "/home/dev/anaconda3/envs/langchain/lib/python3.8/site-packages/langchain/tools/base.py", line 90, in run
    self._parse_input(tool_input)
  File "/home/dev/anaconda3/envs/langchain/lib/python3.8/site-packages/langchain/tools/base.py", line 58, in _parse_input
    input_args.validate({key_: tool_input})
  File "pydantic/main.py", line 711, in pydantic.main.BaseModel.validate
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for WriteFileInput
text
  field required (type=value_error.missing)`

**Comment by stefan-wiesner** [comment]
Or is it possible to use a lambda function to f.write()? But how to I pass the response from the llm and is that just the code?

**Comment by Jessie-Wilkins** [comment]
Running into the same issue as well. I'm wondering if it's a true bug, or there is an undocumented expectation for how to use this tool. My error looks like yours except I'm using a fairly basic agent with those tools appended.

**Comment by Jessie-Wilkins** [comment]
Looking into this, it turns out it has to do with how the WriteFileTool accepts the arguments. The class has this args_schema property defined which uses some pydantic Field type variables to define the file_path and text. The LLM (nor this human) knows how to properly pass in those arguments.

Since I don't know how it's expecting those to be passed in, I decided to just override the WriteFileTool like so:

`from typing import Optional, Type`
`from pydantic import BaseModel`
`from langchain.tools.file_management.write import WriteFileTool`
`import json`

`class FixedWriteFileTool(WriteFileTool):`
    `description = (`
       ` "Write file to disk." `
       ` "Takes the file path and the text content as two string arguments."`
        `"An example of this input: \"file_path\": \"test.txt\", \"text\": \"This is some test text.\""`
        `"Replace the beginning and ending brackets in the input with curly braces."`
    `)`
    `args_schema: Optional[Type[BaseModel]] = None`
    `def _run(self, file_path_and_text: str) -> str:`
        `"{" + file_path_and_text_json + "}"`
        `file_path_and_text_json = json.load(file_path_and_text)`
       `return super().run(file_path_and_text_json["file_path"], file_path_and_text_json["text"])`

Essentially, I override the description to give very specific instructions on how the LLM is supposed to input this.
Then, I override the arg_schema to the default from the BaseTool.
Finally, I create a _run function which changes the defined string to a json that can easily parse and use the values in the parent _run function.

This is a super hacky way of doing it, and I wish this just had better documentation to guide us on how to input this.

**Comment by Jessie-Wilkins** [comment]
This seems to give a hint at the input it's expecting: https://github.com/hwchase17/langchain/blob/master/docs/modules/agents/tools/examples/filesystem.ipynb

**Comment by mrhimanshu** [comment]
I'm getting "Too many arguments to single-input tool Write Files to directory. Args: ['data/hello.txt', 'hello world']"
