### ISSUE TITLE
Langchain is no longer supporting Windows because of uvloop

### ISSUE THREAD

**Issue by qiangwu05** [langchain-ai/langchain#3260]
"poetry install -E all" fails with the following error: 

 • Installing uvloop (0.17.0): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel

  Traceback (most recent call last):
    File "C:\Users\qiang\AppData\Roaming\pypoetry\venv\lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Users\qiang\AppData\Roaming\pypoetry\venv\lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\qiang\AppData\Roaming\pypoetry\venv\lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\qiang\AppData\Local\Temp\tmpd5d92sq2\.venv\lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "C:\Users\qiang\AppData\Local\Temp\tmpd5d92sq2\.venv\lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
      self.run_setup()
    File "C:\Users\qiang\AppData\Local\Temp\tmpd5d92sq2\.venv\lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\qiang\AppData\Local\Temp\tmpd5d92sq2\.venv\lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 8, in <module>
  RuntimeError: uvloop does not support Windows at the moment

  at ~\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\installation\chef.py:152 in _prepare
      148│
      149│                 error = ChefBuildError("\n\n".join(message_parts))
      150│
      151│             if error is not None:
    → 152│                 raise error from None
      153│
      154│             return path
      155│
      156│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with uvloop (0.17.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "uvloop (==0.17.0) ; python_version >= "3.7""'.

**Comment by ehsanmok** [comment]
It's the issue with [uvloop doesn't support windows yet](https://github.com/MagicStack/uvloop/issues/14) and not langchain. Other option is to use docker.

**Comment by shtratos** [comment]
You can also use WSL2 and VSCode remote development to run and develop it on Windows.

**Comment by qiangwu05** [comment]
Yes, I just did that.
It works.

Thanks!
Qiang

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
