### ISSUE TITLE
Error running GPT4ALL model: TypeError: Model.generate() got an unexpected keyword argument 'new_text_callback'

### ISSUE THREAD

**Issue by ooo27** [langchain-ai/langchain#4126]
Sample code:

```from langchain import PromptTemplate, LLMChain
from langchain.llms import GPT4All
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler

gpt4all_model_path = "./models/ggml-gpt4all-l13b-snoozy.bin"

template = """Question: {question}

Answer: Let's think step by step."""

prompt = PromptTemplate(template=template, input_variables=["question"])
callbacks = [StreamingStdOutCallbackHandler()]
llm = GPT4All(model=gpt4all_model_path, callbacks=callbacks, verbose=True)
llm_chain = LLMChain(prompt=prompt, llm=llm)
question = "What is your quest?"
llm_chain.run(question)
```

Error during initialization:
```Traceback (most recent call last):
  File "e:\src\lgtest\game_actor.py", line 27, in <module>
    llm_chain.run(question)
  File "e:\src\lgtest\.venv\Lib\site-packages\langchain\chains\base.py", line 236, in run
    return self(args[0], callbacks=callbacks)[self.output_keys[0]]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\src\lgtest\.venv\Lib\site-packages\langchain\chains\base.py", line 140, in __call__
    raise e
  File "e:\src\lgtest\.venv\Lib\site-packages\langchain\chains\base.py", line 134, in __call__
    self._call(inputs, run_manager=run_manager)
  File "e:\src\lgtest\.venv\Lib\site-packages\langchain\chains\llm.py", line 69, in _call
    response = self.generate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\src\lgtest\.venv\Lib\site-packages\langchain\chains\llm.py", line 79, in generate
    return self.llm.generate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\src\lgtest\.venv\Lib\site-packages\langchain\llms\base.py", line 127, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\src\lgtest\.venv\Lib\site-packages\langchain\llms\base.py", line 176, in generate
    raise e
  File "e:\src\lgtest\.venv\Lib\site-packages\langchain\llms\base.py", line 170, in generate
    self._generate(prompts, stop=stop, run_manager=run_manager)
  File "e:\src\lgtest\.venv\Lib\site-packages\langchain\llms\base.py", line 377, in _generate
    self._call(prompt, stop=stop, run_manager=run_manager)
  File "e:\src\lgtest\.venv\Lib\site-packages\langchain\llms\gpt4all.py", line 186, in _call
    text = self.client.generate(
           ^^^^^^^^^^^^^^^^^^^^^
TypeError: Model.generate() got an unexpected keyword argument 'new_text_callback'```

**Comment by ooo27** [comment]
I was able to fix it, PR here. https://github.com/hwchase17/langchain/pull/4136

**Comment by TatanParker** [comment]
Is not working yet. Some suggestion maybe using previous releases?

**Comment by jackxwu** [comment]
i still get this error on langChain==0.0.160.

**Comment by rafaeldelrey** [comment]
Temporary workaround is to downgrade pygpt4all

**Comment by g0dEngineer** [comment]
> I was able to fix it, PR here. #4136

That works!
