### ISSUE TITLE
NameError when importing `GenerativeAgent`

### ISSUE THREAD

**Issue by vanillechai** [langchain-ai/langchain#4275]
### System Info

Langchain version: `langchain==0.0.161` (installed with `pip`)

Python version: `Python 3.11.2`

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

To reproduce:

```python
% python
Python 3.11.2 (main, Apr 22 2023, 06:36:35) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from langchain.experimental.generative_agents import GenerativeAgent
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/.pyenv/versions/nlp/lib/python3.11/site-packages/langchain/experimental/__init__.py", line 3, in <module>
    from langchain.experimental.generative_agents.generative_agent import GenerativeAgent
  File "/Users/user/.pyenv/versions/nlp/lib/python3.11/site-packages/langchain/experimental/generative_agents/__init__.py", line 2, in <module>
    from langchain.experimental.generative_agents.generative_agent import GenerativeAgent
  File "/Users/user/.pyenv/versions/nlp/lib/python3.11/site-packages/langchain/experimental/generative_agents/generative_agent.py", line 9, in <module>
    from langchain.experimental.generative_agents.memory import GenerativeAgentMemory
  File "/Users/user/.pyenv/versions/nlp/lib/python3.11/site-packages/langchain/experimental/generative_agents/memory.py", line 8, in <module>
    from langchain.retrievers import TimeWeightedVectorStoreRetriever
  File "/Users/user/.pyenv/versions/nlp/lib/python3.11/site-packages/langchain/retrievers/__init__.py", line 9, in <module>
    from langchain.retrievers.self_query.base import SelfQueryRetriever
  File "/Users/user/.pyenv/versions/nlp/lib/python3.11/site-packages/langchain/retrievers/self_query/base.py", line 8, in <module>
    from langchain.chains.query_constructor.base import load_query_constructor_chain
  File "/Users/user/.pyenv/versions/nlp/lib/python3.11/site-packages/langchain/chains/query_constructor/base.py", line 14, in <module>
    from langchain.chains.query_constructor.parser import get_parser
  File "/Users/user/.pyenv/versions/nlp/lib/python3.11/site-packages/langchain/chains/query_constructor/parser.py", line 43, in <module>
    @v_args(inline=True)
     ^^^^^^
NameError: name 'v_args' is not defined. Did you mean: 'vars'?
```

### Expected behavior

Expected no error. Used to work a few days ago until I updated langchain just now.

**Comment by hugos99** [comment]
Hey @vanillechai  I also had this error had to downgrade to version langchain-0.0.158 for the error to disappear

**Comment by vanillechai** [comment]
@hugos99 Thanks, I know, but that's not a long-term solution 😄.

Actually, I'm stuck on langchain-0.0.153 due to other bugs. All versions after that break my scripts, and I have more and more problems with each new release. No one else seems to be noticing, so I want to make sure I'm not using it wrong (😁) before reporting.

**Comment by tasansal** [comment]
This is because the `lark` dependency is not installed. If you look at where `v_args` is coming from it is from `lark`. It is an optional dependency for some reason. Installing it will fix your issue.

**Comment by bkamapantula** [comment]
Thanks @tasansal! Installing [lark dependency](https://github.com/lark-parser/lark#install-lark) resolved it.
