### ISSUE TITLE
Invalid response object from API due to Azure content filter

### ISSUE THREAD

**Issue by arkinyaara** [langchain-ai/langchain#4324]
### System Info

We use langchain for processing medical related questions. Some of the questions are about STIs, mental health issues, etc. some of these questions are marked as inappropriate and are filtered by Azure's prompt filter. The problem is that the response sent by Azure  in this case is of the wrong format, and the parsing of the response by langchain fails.

Output:

```
Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 1.0 seconds as it raised APIError: Invalid response object from API: '{"error":{"message":"The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766","type":null,"param":"prompt","code":"content_filter","status":400}}' (HTTP response code was 400).
Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 2.0 seconds as it raised APIError: Invalid response object from API: '{"error":{"message":"The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766","type":null,"param":"prompt","code":"content_filter","status":400}}' (HTTP response code was 400).
Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIError: Invalid response object from API: '{"error":{"message":"The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766","type":null,"param":"prompt","code":"content_filter","status":400}}' (HTTP response code was 400).
Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 8.0 seconds as it raised APIError: Invalid response object from API: '{"error":{"message":"The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766","type":null,"param":"prompt","code":"content_filter","status":400}}' (HTTP response code was 400).
Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 16.0 seconds as it raised APIError: Invalid response object from API: '{"error":{"message":"The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766","type":null,"param":"prompt","code":"content_filter","status":400}}' (HTTP response code was 400).
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/Users/proj/.venv/lib/python3.9/site-packages/langchain/chains/base.py", line 116, in __call__
    raise e
  File "/Users/proj/.venv/lib/python3.9/site-packages/langchain/chains/base.py", line 113, in __call__
    outputs = self._call(inputs)
  File "/Users/proj/.venv/lib/python3.9/site-packages/langchain/chains/llm.py", line 57, in _call
    return self.apply([inputs])[0]
  File "/Users/proj/.venv/lib/python3.9/site-packages/langchain/chains/llm.py", line 118, in apply
    response = self.generate(input_list)
  File "/Users/proj/.venv/lib/python3.9/site-packages/langchain/chains/llm.py", line 62, in generate
    return self.llm.generate_prompt(prompts, stop)
  File "/Users/proj/.venv/lib/python3.9/site-packages/langchain/chat_models/base.py", line 82, in generate_prompt
    raise e
  File "/Users/proj/.venv/lib/python3.9/site-packages/langchain/chat_models/base.py", line 79, in generate_prompt
    output = self.generate(prompt_messages, stop=stop)
  File "/Users/proj/.venv/lib/python3.9/site-packages/langchain/chat_models/base.py", line 54, in generate
    results = [self._generate(m, stop=stop) for m in messages]
  File "/Users/proj/.venv/lib/python3.9/site-packages/langchain/chat_models/base.py", line 54, in <listcomp>
    results = [self._generate(m, stop=stop) for m in messages]
  File "/Users/proj/.venv/lib/python3.9/site-packages/langchain/chat_models/openai.py", line 266, in _generate
    response = self.completion_with_retry(messages=message_dicts, **params)
  File "/Users/proj/.venv/lib/python3.9/site-packages/langchain/chat_models/openai.py", line 228, in completion_with_retry
    return _completion_with_retry(**kwargs)
  File "/Users/proj/.venv/lib/python3.9/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/Users/proj/.venv/lib/python3.9/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/Users/proj/.venv/lib/python3.9/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/Users/proj/.venv/lib/python3.9/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/Users/proj/.pyenv/versions/3.9.9/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/Users/proj/.pyenv/versions/3.9.9/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/Users/proj/.venv/lib/python3.9/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/Users/proj/.venv/lib/python3.9/site-packages/langchain/chat_models/openai.py", line 226, in _completion_with_retry
    return self.client.create(**kwargs)
  File "/Users/proj/.venv/lib/python3.9/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/Users/proj/.venv/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/Users/proj/.venv/lib/python3.9/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/Users/proj/.venv/lib/python3.9/site-packages/openai/api_requestor.py", line 620, in _interpret_response
    self._interpret_response_line(
  File "/Users/proj/.venv/lib/python3.9/site-packages/openai/api_requestor.py", line 683, in _interpret_response_line
    raise self.handle_error_response(
  File "/Users/proj/.venv/lib/python3.9/site-packages/openai/api_requestor.py", line 333, in handle_error_response
    raise error.APIError(
openai.error.APIError: Invalid response object from API: '{"error":{"message":"The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766","type":null,"param":"prompt","code":"content_filter","status":400}}' (HTTP response code was 400)

```

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

code to reproduce the problem:

```python
    from langchain import PromptTemplate, LLMChain
    from langchain.chat_models import AzureChatOpenAI

    llm = AzureChatOpenAI(
        deployment_name=DEPLOYMENT_NAME,
        engine="gpt-3.5-turbo",
    )

    prompt = PromptTemplate(input_variables=["input"], template="{input}")
    chain = LLMChain(prompt=prompt, llm=llm)
    resp =  chain("too depressed, I want to end it all")

``` 

### Expected behavior

That the response from Azure be parsed without an API error and without retries

**Comment by zeke-john** [comment]
Any update? I'm also consistently getting the same error, for passing the names of products in our prompt, with actually nothing inappropriate in our prompt, or anything that should trigger the moderation system. It has almost become unusable because it keeps triggering it.

**Comment by newhardwarefound** [comment]
I have the same error. Can Azure provide info about which word triggers the error?
What's the problem with the following message for example?

`[SystemMessage(content='You are a helpful assistant extracting attributes from material names. Use start case. Exclude attributes whose values are unavailable in the name. Parse each attribute only once.', additional_kwargs={}),
 HumanMessage(content='Here is an example. (ADP NE35648C175B2501AP Evaporator Coil Upflow 4 Ton 17.5"" x 20.5"" x 25.5"") is parsed as follows:\nBrand: ADP\nOrientation: Upflow\nCapacity: 4 Ton\nLength: 17.5"\nWidth: 20.5"\nHeight: 25.5"', additional_kwargs={}, example=False),
 HumanMessage(content='For each of the material name below, break down the name into individual attributes in yaml format as in the example.\n1. (OIL BURNER PRIMARY CTL ICM1503 - Relay mounts to a standard 4" x 4" junction box, with connections for 2 wire, 24V thermostat to control a line voltage burner. No need to replace the cad cell assembly, as this control is compatible for use with existing Honeywell, or White-Rodgers cad cell assemblies. External push-button reset. Replaces Honeywell R8184G4009, R8184G1138, R8184G1427, R8184G4025; Carlin 48245; Heil 1147017; White-Rodgers 668-401.)\n2. (16X20X2 POLY FILTER NO METAL - Synthetic-Polyester woven, throw-away, air filters. These air filters come with a cardboard frame, and do not have a metal backing.)\n3. (SOLDER ACCESS TEE 3PK 1/4 OD)\n4. (PRESS 3/4 LEAD FREE BALL VL - Equipped with the Smart Connect Feature for easy identification of un-pressed connections during pressure testing. Full ported valves rated @ 600 PSI, WOG max 200 PSI @ 250F, max operating, conforms to MSS SP-110 and are NSF-61 approved.)\n5. (Adj. B-Vent)\n6. (HONEYWELL RELAY - Provides automatic, non-recycling control of intermittent ignition oil burner systems. Used in conjunction with a C554A cad cell flame detector and a 24v thermostat to switch line voltage to burner motor and ignition transformer. External push button reset after safety shutdown. Includes solid state flame sensing circuit and 24v transformer to power heating control circuit; mounts on standard 4 x 4" junction box.Electrical ratings: 45 second models - 7.4 amps @ 120v; 15 & 30 second models - 10.0 amps @ 120v.)\n7. (SOLDER ACCESS TEE 3PK 3/8 OD)\n8. (4"" Support band - Used to support the ""L"" Vent pipe as it passes through the firestop spacer. This piece typically sits on top of the firestop spacer.)\n9. (3 mfd @ 440 volt, round, run capacitor)\n10. (HONEYWELL RELAY - Same functions and specifications as standard models, but includes integral 40VA, 24 volt transformer to provide power for a low voltage cooling control system, "Y" and "G" terminals for compressor and fan relay operation.)', additional_kwargs={}, example=False)]`

**Comment by vysakhrj** [comment]
Any changes on this issue, as I'm experiencing the same with some medical data being used for data modelling.

**Comment by pidefrem** [comment]
If the `ValueError` raised by langchain is the problem. You can catch the error and deal with it, or you can customise the `AzureChatOpenAI` code on your side if you want more flexibility.

For example with `langchain-v0.3.2` and `langchain-openai-v0.2.2`:
```
from langchain_openai import AzureChatOpenAI

class LLMContentFilterError(ValueError):
    def __init__(self, message, chat_result=None):
        super().__init__(message)
        self.chat_result = chat_result

class CustomAzureChatOpenAI(AzureChatOpenAI):
    def _create_chat_result(
        self,
        response: Union[dict, openai.BaseModel],
        generation_info: Optional[Dict] = None,
    ) -> ChatResult:
        chat_result = super(AzureChatOpenAI, self)._create_chat_result(response, generation_info)

        if not isinstance(response, dict):
            response = response.model_dump()

        if "model" in response:
            model = response["model"]
            if self.model_version:
                model = f"{model}-{self.model_version}"

            chat_result.llm_output = chat_result.llm_output or {}
            chat_result.llm_output["model_name"] = model
        if "prompt_filter_results" in response:
            chat_result.llm_output = chat_result.llm_output or {}
            chat_result.llm_output["prompt_filter_results"] = response["prompt_filter_results"]
        for chat_gen, response_choice in zip(chat_result.generations, response["choices"]):
            chat_gen.generation_info = chat_gen.generation_info or {}
            chat_gen.generation_info["content_filter_results"] = response_choice.get("content_filter_results", {})

        for res in response["choices"]:
            if res.get("finish_reason", None) == "content_filter":
                raise LLMContentFilterError(
                    "Azure has not provided the response due to a content filter " "being triggered", chat_result
                )

        return chat_result
```
