### ISSUE TITLE
ChatOpenAI.agenerate seems broken in 0.0.168?

### ISSUE THREAD

**Issue by delip** [langchain-ai/langchain#4643]
### System Info

error:
```
Traceback (most recent call last):
  File "/Users/delip/workspace/tmp/main3.py", line 38, in <module>
    asyncio.run(main())
  File "/Users/delip/opt/anaconda3/envs/lhenv/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/delip/opt/anaconda3/envs/lhenv/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/delip/workspace/tmp/main3.py", line 32, in main
    await generate_concurrently()
  File "/Users/delip/workspace/tmp/main3.py", line 27, in generate_concurrently
    await asyncio.gather(*tasks)
  File "/Users/delip/workspace/tmp/main3.py", line 11, in async_generate
    resp = await llm.agenerate(
  File "/Users/delip/opt/anaconda3/envs/lhenv/lib/python3.8/site-packages/langchain/chat_models/base.py", line 128, in agenerate
    raise e
  File "/Users/delip/opt/anaconda3/envs/lhenv/lib/python3.8/site-packages/langchain/chat_models/base.py", line 118, in agenerate
    results = await asyncio.gather(
  File "/Users/delip/opt/anaconda3/envs/lhenv/lib/python3.8/site-packages/langchain/chat_models/openai.py", line 322, in _agenerate
    message_dicts, params = self._create_message_dicts(messages, stop)
  File "/Users/delip/opt/anaconda3/envs/lhenv/lib/python3.8/site-packages/langchain/chat_models/openai.py", line 304, in _create_message_dicts
    message_dicts = [_convert_message_to_dict(m) for m in messages]
  File "/Users/delip/opt/anaconda3/envs/lhenv/lib/python3.8/site-packages/langchain/chat_models/openai.py", line 304, in <listcomp>
    message_dicts = [_convert_message_to_dict(m) for m in messages]
  File "/Users/delip/opt/anaconda3/envs/lhenv/lib/python3.8/site-packages/langchain/chat_models/openai.py", line 92, in _convert_message_to_dict
    raise ValueError(f"Got unknown type {message}")
ValueError: Got unknown type ('content', 'you are a helpful bot')
```

langchain version

```
 conda env export | grep langchain
      - langchain==0.0.168
```

### Who can help?

@hwchase17 @agola11 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [X] Async

### Reproduction

minimum viable code to reproduce:

```python
import time
import asyncio

from langchain.chat_models import ChatOpenAI
from langchain.schema import HumanMessage, SystemMessage

from keys import KEYS


async def async_generate(llm):
    resp = await llm.agenerate(
        [
            SystemMessage(content="you are a helpful bot"),
            HumanMessage(content="Hello, how are you?"),
        ]
    )
    print(resp)


async def generate_concurrently():
    llm = ChatOpenAI(
        temperature=0.9,
        openai_api_key=KEYS["openai.api_key"],
        openai_organization=KEYS["openai.organization"],
    )
    tasks = [async_generate(llm) for _ in range(3)]
    await asyncio.gather(*tasks)


async def main():
    start = time.perf_counter()
    await generate_concurrently()
    elapsed = time.perf_counter() - start
    print("\033[1m" + f"Concurrent executed in {elapsed:0.2f} seconds." + "\033[0m")


if __name__ == "__main__":
    asyncio.run(main())
```

### Expected behavior

Should produce 3 generation results.

**Comment by delip** [comment]
@agola11 spotted the error: `llm.agenerate` expects a list of list of messages. Leaving this issue open to provide better error messages. Feel free to close without fixing :)

**Comment by mperezjodal** [comment]
Hi @delip , just encountered this same issue, any workaround you suggest?

**Comment by Automarita** [comment]
you'd better inspect **codes** in this repo instead of documentation on the webpage, function `agenerate` will return a coroutine object, so I think it should be fine as 
```python
generation_result = await chat.agenerate(workloads, max_tokens=128)
```
but it still get error message like below:
```
Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 2.0 second
as it raised APIConnectionError: Error communicating with OpenAI.
```

**Comment by nfcampos** [comment]
I'd suggest using `.ainvoke()` method which expects a single list of messages
