### ISSUE TITLE
Issue: Escaping { and } chars in a langchain.prompts.PromptTemplate

### ISSUE THREAD

**Issue by Th0rgal** [langchain-ai/langchain#5051]
### Issue you'd like to raise.

Hey,

I am willing to use { and } chars as an example in my prompt template (I want to prompt my chain to generate css code), but this generates this error:
```
Traceback (most recent call last):
  File "/Users/thomas/workspace/j4rvis/j4rvis/tools/document_tools.py", line 43, in <module>
    prompt=PromptTemplate(
           ^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for PromptTemplate
__root__
  Invalid prompt schema; check for mismatched or missing input parameters. ' ' (type=value_error)
  ```
  
 How could I escape those chars so they don't get interpreted as input_variables?

**Comment by strasserpatrick** [comment]
You can use jinja2 templating: 

```python 
java_code_prompt = PromptTemplate.from_template("public class {{ class_name }} { # code here }", 
                                                template_format="jinja2")

print(java_code_prompt.format_prompt(class_name="MyClass"))
```

Now you can normally use curly braces without escaping, but you need to put all your variables in double curly braces {{ var1 }}, ...

**Comment by chrisguerrero** [comment]
I'm encountering this same issue. I tried switching the template format to `jinja2`, but when I call the chain, it seems to ignore my prompt entirely and returns some random java code snippet. Has anyone else had success with the jinja2 workaround?

**Comment by lingfengchencn** [comment]
just add one more { or } , it will be ok.

# codes:
```python
template = """You are a chatbot having a conversation with a human.
java codes:
public class Main {{
  public static void main(String[] args) {{
    System.out.println("Hello World");
  }}
}}

css example:
<style>
body {{background-color: powderblue;}}
h1   {{color: blue;}}
p    {{color: red;}}
</style>


{chat_history}
Human: {human_input}
Chatbot:"""

prompt = PromptTemplate(
    input_variables=["chat_history", "human_input"], 
    template=template
)
memory = ConversationBufferMemory(memory_key="chat_history")
llm_chain = LLMChain(
    llm=llm_azure,
    prompt=prompt, 
    verbose=True, 
    memory=memory,
)
llm_chain.predict(human_input = "Hi there my friend")
```

#  result

```
> Entering new LLMChain chain...
Prompt after formatting:
You are a chatbot having a conversation with a human.
java codes:
public class Main {
  public static void main(String[] args) {
    System.out.println("Hello World");
  }
}

css example:
<style>
body {background-color: powderblue;}
h1   {color: blue;}
p    {color: red;}
<[/style](https://file+.vscode-resource.vscode-cdn.net/style)>

...
Human: Hi there my friend
Chatbot:

> Finished chain.
Output is truncated. ..
" Hello there, how may I assist you today?......
```

**Comment by lincasaires** [comment]
double brackets don't work!
