### ISSUE TITLE
SQL chain generates extra add on question if I use ChatOpenAI inplace of OpenAI

### ISSUE THREAD

**Issue by charanhu** [langchain-ai/langchain#5286]
### System Info

`import os
from langchain import OpenAI, SQLDatabase, SQLDatabaseChain
from langchain.chat_models import ChatOpenAI
from dotenv import load_dotenv
load_dotenv()
os.environ["OPENAI_API_KEY"] = os.getenv("OPENAI_API_KEY")
db = SQLDatabase.from_uri("sqlite:///data/data.db")
llm = ChatOpenAI(temperature=0, verbose=True)
db_chain = SQLDatabaseChain.from_llm(llm, db, verbose=True)
res = db_chain.run("total sales by each region?")
print(res)`

![image](https://github.com/hwchase17/langchain/assets/52596822/fbfa65bc-398b-43f1-a506-0e7a5cd57221)

But If I use text-davinici, It generates single result.

`import os
from langchain import OpenAI, SQLDatabase, SQLDatabaseChain
from langchain.chat_models import ChatOpenAI
from dotenv import load_dotenv
load_dotenv()
os.environ["OPENAI_API_KEY"] = os.getenv("OPENAI_API_KEY")
db = SQLDatabase.from_uri("sqlite:///data/data.db")
llm = OpenAI(temperature=0, verbose=True)
db_chain = SQLDatabaseChain.from_llm(llm, db, verbose=True)
res = db_chain.run("total sales by each region?")
print(res)`

![text-davinici](https://github.com/hwchase17/langchain/assets/52596822/1ccd746c-5951-42c1-85f6-1530827c1029)

how to overcome this issue in **"ChatOpenAI"**?

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

import os
from langchain import OpenAI, SQLDatabase, SQLDatabaseChain
from langchain.chat_models import ChatOpenAI
from dotenv import load_dotenv
load_dotenv()
os.environ["OPENAI_API_KEY"] = os.getenv("OPENAI_API_KEY")
db = SQLDatabase.from_uri("sqlite:///data/data.db")
llm = ChatOpenAI(temperature=0, verbose=True)
db_chain = SQLDatabaseChain.from_llm(llm, db, verbose=True)
res = db_chain.run("total sales by each region?")
print(res)

### Expected behavior

I need one answer that is for user input query only. But after the answer It again adding a question by itself. Extra add on question and query not needed in **ChatOpenAI**

**Comment by huozhong-in** [comment]
I have the same issue.
`chain = load_qa_chain(llm=llm, chain_type='stuff')`
`answer = chain.run(input_documents=docs, question=query, prompt=prompt, max_responses=1)`
`print(answer)`
extra content/QA is not need!

**Comment by Qucy** [comment]
Same here

**Comment by oskrocha** [comment]
Same issue here. 
I think this issue is a duplicate of [4840](https://github.com/hwchase17/langchain/issues/4840)

**Comment by chriskuchar** [comment]
I am using langchain developmental, and I had to put the stop word 'What' as when it kept chaining it wouldn't do "Question:/" as it did for @charanhu. For me, it would be "what is the ......?" as the continuation everytime. Adding '\nWhat' to the stop condition according to https://github.com/langchain-ai/langchain/issues/4840 did the trick for me.

**Comment by renlon** [comment]
I am running to the same issue when using SageMaker endpoint. It seems that questions are concatenated along with the actual SQL query. 
```
Question: How many log entries are there in the log file?

SQLQuery: SELECT COUNT(*) FROM alb_e29f4392d2b64810adcc20d3a1eae4db_1697521767;Failed to execute query.
Traceback (most recent call last):
  File "/opt/miniconda3/envs/minianda/lib/python3.8/site-packages/pyathena/common.py", line 520, in _execute
    query_id = retry_api_call(
  File "/opt/miniconda3/envs/minianda/lib/python3.8/site-packages/pyathena/util.py", line 68, in retry_api_call
    return retry(func, *args, **kwargs)
  File "/opt/miniconda3/envs/minianda/lib/python3.8/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/opt/miniconda3/envs/minianda/lib/python3.8/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/opt/miniconda3/envs/minianda/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/opt/miniconda3/envs/minianda/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/opt/miniconda3/envs/minianda/lib/python3.8/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/opt/miniconda3/envs/minianda/lib/python3.8/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/miniconda3/envs/minianda/lib/python3.8/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidRequestException: An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: line 1:1: mismatched input 'Question'. Expecting: 'ALTER', 'ANALYZE', 'CALL', 'COMMENT', 'COMMIT', 'CREATE', 'DEALLOCATE', 'DELETE', 'DENY', 'DESC', 'DESCRIBE', 'DROP', 'EXECUTE', 'EXPLAIN', 'GRANT', 'INSERT', 'MERGE', 'PREPARE', 'REFRESH', 'RESET', 'REVOKE', 'ROLLBACK', 'SET', 'SHOW', 'START', 'TRUNCATE', 'UNLOAD', 'UPDATE', 'USE', <query>
2023-10-16 15:49:48,861 - MiniANDA - ERROR - Error in querying access log. Error: (pyathena.error.DatabaseError) An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: line 1:1: mismatched input 'Question'. Expecting: 'ALTER', 'ANALYZE', 'CALL', 'COMMENT', 'COMMIT', 'CREATE', 'DEALLOCATE', 'DELETE', 'DENY', 'DESC', 'DESCRIBE', 'DROP', 'EXECUTE', 'EXPLAIN', 'GRANT', 'INSERT', 'MERGE', 'PREPARE', 'REFRESH', 'RESET', 'REVOKE', 'ROLLBACK', 'SET', 'SHOW', 'START', 'TRUNCATE', 'UNLOAD', 'UPDATE', 'USE', <query>
[SQL: Question: How many log entries are there in the log file?
```
As you can see, since the question is included as part of the SQL query, the DB complains about the query syntax.
