### ISSUE TITLE
Running into this error while creating embeddings out of pdf file

### ISSUE THREAD

**Issue by catchlui** [langchain-ai/langchain#5384]
### System Info

File "d:\langchain\pdfqa-app.py", line 46, in _upload_data
    Pinecone.from_texts(self.doc_chunk,embeddings,batch_size=16,index_name=self.index_name)
  File "E:\anaconda\envs\langchain\lib\site-packages\langchain\vectorstores\pinecone.py", line 232, in from_texts
    embeds = embedding.embed_documents(lines_batch)
  File "E:\anaconda\envs\langchain\lib\site-packages\langchain\embeddings\openai.py", line 297, in embed_documents
    return self._get_len_safe_embeddings(texts, engine=self.deployment)
  File "E:\anaconda\envs\langchain\lib\site-packages\langchain\embeddings\openai.py", line 221, in _get_len_safe_embeddings
    token = encoding.encode(
  File "E:\anaconda\envs\langchain\lib\site-packages\tiktoken\core.py", line 117, in encode
    if match := _special_token_regex(disallowed_special).search(text):
TypeError: expected string or buffer

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

def _load_docs(self):
        loader=PyPDFLoader("D:\langchain\data_source\\1706.03762.pdf")
        self.doc= loader.load()
        

    def _split_docs (self):
        text_splitter = RecursiveCharacterTextSplitter(chunk_size=self.chunk_size, chunk_overlap=self.chunk_overlap,separators= ["\n\n", ""])
        self.doc_chunk = text_splitter.split_documents(self.doc)
    
    def _upload_data(self):
        embeddings = OpenAIEmbeddings()
        list_of_index = pinecone.list_indexes()
        if self.index_name in list_of_index:
            Pinecone.from_texts(self.doc_chunk,embeddings,batch_size=16,index_name=self.index_name)
        else:
            pinecone.create_index(self.index_name, dimension=1024) # for open AI
            Pinecone.from_texts(self.doc_chunk,embeddings,batch_size=16,index_name=self.index_name)
    def dataloader(self):
        self._load_docs()
        self._split_docs()
        self._upload_data()

### Expected behavior

Please help with the solution

**Comment by YLFxGen** [comment]
Use `Pinecone.from_documents(self.doc_chunk, embeddings, batch_zie=16, index_name=self.index_name)` instead.
_text_splitter.split_documents_ chunks file into a list of documents instead of text.

**Comment by Rinisha160391** [comment]
> Use `Pinecone.from_documents(self.doc_chunk, embeddings, batch_zie=16, index_name=self.index_name)` instead. _text_splitter.split_documents_ chunks file into a list of documents instead of text.

it worked for me

**Comment by dobahoang** [comment]
hi @dosubot
i had the same problem when updating to the most recent version of langchain
Specifically
pip install langchain==0.1.6 pip install langchain-community==0.0.19 pip install langchain-core==0.1.23

My code assume:
def prompt_extract_information():
    prompt = """
From the following input, perform the following two tasks, determine the most suitable product in <context>
1. Extract the product name, and map the feature mentioned in the input to the feature mentioned in the context
2. Present in the following format json with key : name ( mandatory ) and some feature ( optional ) from context (Criteria)

input:
{input}

<context> {context} </context>
Output json :

"""
    answer_prompt = ChatPromptTemplate.from_template(prompt)
    return answer_prompt


def retrieval_embedding():

    vectordb = Chroma(persist_directory="database", embedding_function=OpenAIEmbeddings())
    retriever = vectordb.as_retriever(search_kwargs={"k": 2})

    return retriever

retriever = retrieval_embedding()
prompt = prompt_extract_information()
llm = ChatOpenAI(model_name="gpt-3.5-turbo-0125", temperature=0)

def format_docs(docs):

    return "\n\n".join(doc.page_content for doc in docs)


rag_chain = (
    {"context": retriever | format_docs, "input": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)


# response =  rag_chain.invoke("I want to buy a device that can make calls, browse the internet, and take photos with a large battery capacity of about 5000 mAh")
response =  rag_chain.invoke({"input": "I want to buy a smartphone"})
print(response)


Error:
Traceback (most recent call last):
  File "D:\Workspace\ChatbotAI\Chatbot_dg5\recommend_system\rag.py", line 74, in <module>
    response =  rag_chain.invoke({"input": "I want to buy a smartphone"})
  File "D:\Workspace\ChatbotAI\Chatbot_dg5\venv\lib\site-packages\langchain_core\runnables\base.py", line 2053, in invoke
    input = step.invoke(
  File "D:\Workspace\ChatbotAI\Chatbot_dg5\venv\lib\site-packages\langchain_core\runnables\base.py", line 2692, in invoke
    output = {key: future.result() for key, future in zip(steps, futures)}
  File "D:\Workspace\ChatbotAI\Chatbot_dg5\venv\lib\site-packages\langchain_core\runnables\base.py", line 2692, in <dictcomp>
    output = {key: future.result() for key, future in zip(steps, futures)}
  File "C:\Users\dbhoang\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 440, in result
    return self.__get_result()
  File "C:\Users\dbhoang\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
  File "C:\Users\dbhoang\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Workspace\ChatbotAI\Chatbot_dg5\venv\lib\site-packages\langchain_core\runnables\base.py", line 2053, in invoke
    input = step.invoke(
  File "D:\Workspace\ChatbotAI\Chatbot_dg5\venv\lib\site-packages\langchain_core\retrievers.py", line 121, in invoke
    return self.get_relevant_documents(
  File "D:\Workspace\ChatbotAI\Chatbot_dg5\venv\lib\site-packages\langchain_core\retrievers.py", line 224, in get_relevant_documents
    raise e
  File "D:\Workspace\ChatbotAI\Chatbot_dg5\venv\lib\site-packages\langchain_core\retrievers.py", line 217, in get_relevant_documents
    result = self._get_relevant_documents(
  File "D:\Workspace\ChatbotAI\Chatbot_dg5\venv\lib\site-packages\langchain_core\vectorstores.py", line 654, in _get_relevant_documents
    docs = self.vectorstore.similarity_search(query, **self.search_kwargs)
  File "D:\Workspace\ChatbotAI\Chatbot_dg5\venv\lib\site-packages\langchain_community\vectorstores\chroma.py", line 348, in similarity_search
    docs_and_scores = self.similarity_search_with_score(
  File "D:\Workspace\ChatbotAI\Chatbot_dg5\venv\lib\site-packages\langchain_community\vectorstores\chroma.py", line 437, in similarity_search_with_score
    query_embedding = self._embedding_function.embed_query(query)
  File "D:\Workspace\ChatbotAI\Chatbot_dg5\venv\lib\site-packages\langchain_openai\embeddings\base.py", line 509, in embed_query
    return self.embed_documents([text])[0]
  File "D:\Workspace\ChatbotAI\Chatbot_dg5\venv\lib\site-packages\langchain_openai\embeddings\base.py", line 480, in embed_documents
    return self._get_len_safe_embeddings(texts, engine=engine)
  File "D:\Workspace\ChatbotAI\Chatbot_dg5\venv\lib\site-packages\langchain_openai\embeddings\base.py", line 300, in _get_len_safe_embeddings
    token = encoding.encode(
  File "D:\Workspace\ChatbotAI\Chatbot_dg5\venv\lib\site-packages\tiktoken\core.py", line 116, in encode
    if match := _special_token_regex(disallowed_special).search(text):
TypeError: expected string or buffer

**Comment by dobahoang** [comment]
I discovered the cause at line my code:
response = rag_chain.invoke({"input": "I want to buy a smartphone"})

It doesn't accept dict, does the langchain tutorial on the website use dict? I do not understand?
If I edit it like this:
response = rag_chain.invoke("I want to buy a smartphone")
Everything is fine, but does that mean only 1 value is passed in?

I think the problem is in the following line of code langchain

     def embed_query(self, text: str) -> List[float]:
         """Call out to OpenAI's embedding endpoint for embedding query text.

         Args:
             text: The text to embed.

         Returns:
             Embedding for the text.
         """
         return self.embed_documents([text])[0]


Should be revised to self.embed_documents([text["input"]])[0]

Please help me check with the development team, thank you
