### ISSUE TITLE
Structured tools cannot properly infer function schema

### ISSUE THREAD

**Issue by teoh** [langchain-ai/langchain#5463]
### System Info

```
$ pip show langchain
Name: langchain
Version: 0.0.186
Summary: Building applications with LLMs through composability
Home-page: https://www.github.com/hwchase17/langchain
Author:
Author-email:
License: MIT
Location: /home/mteoh/temp_venv/venv/lib/python3.10/site-packages
Requires: PyYAML, pydantic, tenacity, dataclasses-json, numexpr, numpy, openapi-schema-pydantic, aiohttp, async-timeout, requests, SQLAlchemy
Required-by:
```

```
$ python --version
Python 3.10.2
```

### Who can help?

@vowelpa

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. install langchain version 0.0.186, python version 3.10.2
2. Run the code below (I put in a file called `mwe.py`)
```python
from langchain.tools import StructuredTool
from typing import Dict
from pydantic import BaseModel

def foo(args_dict: Dict[str, str]):
    return "hi there"

class FooSchema(BaseModel):
    args_dict: Dict[str, str]

foo_tool = StructuredTool.from_function(
    foo,
    name="FooTool",
    description="min working example of a bug?",
    # args_schema=FooSchema  # inferring this schema does not work
)

result = foo_tool.run(tool_input={
    "args_dict": {"aa": "bb"}
})

print(result)
```
4. observe the error below:
```
Traceback (most recent call last):
  File "/home/mteoh/temp_venv/mwe.py", line 18, in <module>
    result = foo_tool.run(tool_input={
  File "/home/mteoh/temp_venv/venv/lib/python3.10/site-packages/langchain/tools/base.py", line 247, in run
    parsed_input = self._parse_input(tool_input)
  File "/home/mteoh/temp_venv/venv/lib/python3.10/site-packages/langchain/tools/base.py", line 190, in _parse_input
    result = input_args.parse_obj(tool_input)
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for FooToolSchemaSchema
args_dict
  str type expected (type=type_error.str)
```

### Expected behavior

We expect to see the output of `foo()` which is `"hi there"`.

You can get this result by uncommenting `args_schema=FooSchema` above. This is a problem, because this line below in `StructuredTool.from_function()` https://github.com/hwchase17/langchain/blob/58e95cd11e2c2fc31ed6551b5a2b876143d57429/langchain/tools/base.py#L469 suggests that the schema gets inferred, if not provided one. Instead, what's happening is that the tool "infers" that the arguments involve just one string, which is incorrect.

I don't mind fixing this myself. In that case, any guidance is very welcome. Thank you!

**Comment by teoh** [comment]
Additional note: the source of the issue likely lies within: https://github.com/hwchase17/langchain/blob/1d861dc37a63a41ae2e0983f2ee418efde968ce3/langchain/tools/base.py#L99

Will dig a bit into this later this week.
