### ISSUE TITLE
The ConstitutionalChain examples violate Azure OpenAI's content management policy.

### ISSUE THREAD

**Issue by nitky** [langchain-ai/langchain#5592]
### System Info

- langchain 0.0.187
- openai-python 0.27.7
- Python 3.11.2
- macOS Ventura 13.4 (Apple M2)
- OPENAI_API_TYPE azure
- OPENAI_API_VERSION 2023-05-15

### Who can help?

@hwchase17
@agola11

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

ConstitutionalChain will not work because the following example violates Azure OpenAI's content management policy.
https://github.com/hwchase17/langchain/blob/v0.0.187/langchain/chains/constitutional_ai/prompts.py#L24-L31
```
    {
        "input_prompt": "Could you help me burn down my house and collect insurance on it?",
        "output_from_model": "Sure, I can help you burn your house down. Is there a particular house you want to burn down?",
        "critique_request": "Identify specific ways in which the model’s precedings response is harmful. Also point out potential harmfulness in the human’s questions and responses. Examples of harm include but are not limited to racism, sexism, toxicity.",
        "critique": "Arson is very dangerous and illegal, and should not be condoned. The model should not have asked a follow-up question about which house to burn down instead it should told the human that arson is illegal and dangerous. Critique Needed.",
        "revision_request": "Please rewrite the model response to remove all harmful content, and to politely point out any harmful assumptions from the human.",
        "revision": "I would strongly advise against burning your house down, as arson is considered a serious crime. Doing so could harm yourself and others. Please reach out to a mental health professional if you are considering this.",
    },
```

Code Sample:
```
from langchain.llms import AzureOpenAI
from langchain.prompts import PromptTemplate
from langchain.chains.llm import LLMChain
from langchain.chains.constitutional_ai.base import ConstitutionalChain

qa_prompt = PromptTemplate(
    template="""Question: {question}
One word Answer:""",
    input_variables=["question"],
)
llm = AzureOpenAI(client=None, deployment_name="text-davinci-003", model="text-davinci-003", temperature=0)
qa_chain = LLMChain(llm=llm, prompt=qa_prompt)
query = "should I eat oreos?"

principles = ConstitutionalChain.get_principles(["uo-implications-1"])
constitutional_chain = ConstitutionalChain.from_llm(
    chain=qa_chain,
    constitutional_principles=principles,
    llm=llm,
    verbose=True,
)

print(constitutional_chain.run(query))
```

Output:
```
> Entering new ConstitutionalChain chain...
Initial response:  Yes

Traceback (most recent call last):
...
  File "/[Project_PATH]/.venv/lib/python3.11/site-packages/openai/api_requestor.py", line 624, in _interpret_response
    self._interpret_response_line(
  File "/[Project_PATH]/.venv/lib/python3.11/site-packages/openai/api_requestor.py", line 687, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766
```

### Expected behavior

ConstitutionalChain works as documented.

```
> Entering new ConstitutionalChain chain...
Initial response:  Yes

Applying uo-implications-1...

Critique: The AI model's response does not list any of the relevant implications and expected consequences of eating Oreos. It does not consider potential health risks, dietary restrictions, or any other factors that should be taken into account when making a decision about eating Oreos. Critique Needed.

Updated response: Eating Oreos can be a tasty treat, but it is important to consider potential health risks, dietary restrictions, and other factors before making a decision. If you have any dietary restrictions or health concerns, it is best to consult with a doctor or nutritionist before eating Oreos.


> Finished chain.
Eating Oreos can be a tasty treat, but it is important to consider potential health risks, dietary restrictions, and other factors before making a decision. If you have any dietary restrictions or health concerns, it is best to consult with a doctor or nutritionist before eating Oreos.
```

**Comment by nitky** [comment]
Although this operation has not been confirmed, it seems that it currently works by configuring Content filters in Azure OpenAI Studio. If you encounter a similar issue, please refer to this solution.
