### ISSUE TITLE
Validation error for gpt4all 

### ISSUE THREAD

**Issue by ketlinapuci** [langchain-ai/langchain#6038]
### System Info

I followed the steps to install gpt4all based on this repo
https://github.com/nomic-ai/gpt4all/tree/main/gpt4all-bindings/python
I have the latest version of langchain

### Who can help?

@hwchase17 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [X] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction
```
 def mainllm():
 template = """Question: {question}

prompt = PromptTemplate(template=template, input_variables=["question"])
local_path = './models/gpt4all-converted.bin'
llm = gpt4all.GPT4All("ggml-gpt4all-j-v1.3-groovy.bin")
llm_chain = LLMChain(prompt=prompt, llm=llm)
question = "What NFL team won the Super Bowl in the year Justin Bieber was born?"
llm_chain.run(question)
    
if __name__ == '__main__':
mainllm()
```
This is the error I get related to this lines on code:

```
Traceback (most recent call last):
  File "gpt4all.py", line 174, in <module>
    mainllm()
  File "gpt4all.py", line 166, in mainllm
    llm = gpt4all.GPT4All("ggml-gpt4all-j-v1.3-groovy.bin")
TypeError: Serializable.__init__() takes 1 positional argument but 2 were given
```

### Expected behavior

Could you help me understand what is wrong?
Thanks

**Comment by hwchase17** [comment]
you need to pass `model=ggml-gpt4all-j-v1.3-groovy.bin`

**Comment by joebordes** [comment]
I'm getting the same error even with `model`

```python
import gpt4all
from langchain import PromptTemplate, LLMChain

def mainllm():
	template = """Question: {question}
	"""
	prompt = PromptTemplate(template=template, input_variables=["question"])
	llm = gpt4all.GPT4All(model='ggml-gpt4all-j-v1.3-groovy')
	llm_chain = LLMChain(prompt=prompt, llm=llm)
	question = "What NFL team won the Super Bowl in the year Justin Bieber was born?"
	llm_chain.run(question)

if __name__ == "__main__":
	mainllm()
```

```shell
Traceback (most recent call last):
  File "gpt4a.py", line 14, in <module>
    mainllm()
  File "gpt4a.py", line 8, in mainllm
    llm = gpt4all.GPT4All(model='ggml-gpt4all-j-v1.3-groovy')
  File "/home/joe/.local/lib/python3.8/site-packages/langchain/load/serializable.py", line 61, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for GPT4All
__root__
  __init__() takes 1 positional argument but 2 were given (type=type_error)
```

**Comment by joebordes** [comment]
In our case, it was that we had a local file named gpt4all.py in the same directory. Works correctly once we renamed it

**Comment by talhaanwarch** [comment]
Try this
```
from langchain.llms import GPT4All
GPT4All(
            model='ggml-gpt4all-l13b-snoozy.bin', 
            n_ctx=1000, 
            verbose=True)
```
