### ISSUE TITLE
CohereEmbeddings do not work in Context class

### ISSUE THREAD

**Issue by proxzy** [langchain-ai/langchain#6284]
### System Info

==versions==
python 3.9
langchain 0.0.186
pydantic 1.10.8
windows 11

### Who can help?

@agola

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

==run source===
from langchain.embeddings import CohereEmbeddings
from langchain.chains.base import Chain

class Neo4jContextTool(Chain):
    """Chain for context search with cohere embedding"""

    embeddings = CohereEmbeddings()

==traceback==
Traceback (most recent call last):
  File "\Python39\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 5, in <module>
  File "pydantic\main.py", line 221, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic\fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 546, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 570, in pydantic.fields.ModelField._set_default_and_type
  File "pydantic\fields.py", line 439, in pydantic.fields.ModelField.get_default
  File "pydantic\utils.py", line 693, in pydantic.utils.smart_deepcopy
  File "\Python39\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "\Python39\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "\Python39\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "\Python39\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "\Python39\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "\Python39\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "\Python39\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "\Python39\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "\Python39\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "\Python39\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "\Python39\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "\Python39\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "\Python39\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "\Python39\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "\Python39\lib\copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_queue.SimpleQueue' object

### Expected behavior

creating class without errors. 
same code with OpenAIEmbeddings do not have this error

**Comment by ananty1** [comment]
I believe the issue persists?
