### ISSUE TITLE
langchain\agents\chat\output_parser.py line 18, IndexError: list index out of range

### ISSUE THREAD

**Issue by catskytw** [langchain-ai/langchain#6322]
### System Info

langchain ver: 0.0.202
python: 3.10_3

I've got this error:
```python
Traceback (most recent call last):
  File "C:\Users\catsk\SourceCode\azure_openai_poc\venv\lib\site-packages\langchain\agents\chat\output_parser.py", line 18, in parse
    action = text.split("```")[1]
IndexError: list index out of range
``` 
while setting my agent.type is CHAT_ZERO_SHOT_REACT_DESCRIPTION

At that moment, the text content was:
<details><summary>Details</summary>
<p>

I have found the answer to the question.

Final Answer: Yes, xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.

</p>
</details> 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

* Reproduce steps:
1. Build any agent including some tools, 
2. set the AgentType as CHAT_ZERO_SHOT_REACT_DESCRIPTION
3. ask the agent doing something

Here is the code:
```python
def local_vector_search(question_str,chat_history, collection_name = hr_collection_name):
    embedding = get_openaiembeddings()
    vectorstore = Chroma( embedding_function=embedding,
                          collection_name=collection_name,
                          persist_directory=root_file_path+persist_db,
                          )

    memory = ConversationBufferMemory(memory_key="chat_history", return_messages=True, ai_prefix = "AI超級助理")

    llm = AzureOpenAI(
        deployment_name = global_deployment_id,
        model_name= global_model_name,
        temperature = 0.0)

    chat_llm = AzureChatOpenAI(
        deployment_name = global_deployment_id,
        model_name= global_model_name,
        temperature = 0.2)

    prompt = PromptTemplate(
        template=get_prompt_template_string(),
        input_variables=["question","chat_history"]
    )
    prompt.format(question=question_str,chat_history=chat_history)
    km_chain = ConversationalRetrievalChain.from_llm(
        llm=chat_llm,
        retriever=vectorstore.as_retriever(),
        memory=memory,
        condense_question_prompt=prompt,
    )
    km_tool = Tool(
        name='Knowledge Base',
        func=km_chain.run,
        description='Use this tool first when you want to answer any issue about our company'
    )

    math_math = LLMMathChain(llm=llm)
    math_tool = Tool(
        name='Calculator',
        func=math_math.run,
        description='Useful for when you need to answer questions about math.'
    )
    tools=[math_tool,km_tool]
    agent=initialize_agent(
        agent=AgentType.CHAT_ZERO_SHOT_REACT_DESCRIPTION,
        tools=tools,
        llm=chat_llm,
        verbose=True,
        memory=memory,
        max_iterations=30,
    )
    #result=km_chain(question_str)
    result=agent(question_str)
    print(result)
    return result["output"]
``` 

### Expected behavior

Give me the final answer

**Comment by sagardesai-ml-mlops** [comment]
can you post full error trace, I am not able to figure out from where error is initiated. it will help.

**Comment by devstein** [comment]
_Generated by a 🤖_

### Answer

The error occurs because the text content does not contain the expected triple backticks (```), which the code tries to split on line 18. To fix this issue, you can modify the `parse` method to check if the triple backticks are present in the text before attempting to split it.

Here's the modified `parse` method:

```python
def parse(self, text: str) -> Union[AgentAction, AgentFinish]:
    includes_answer = FINAL_ANSWER_ACTION in text
    includes_triple_backticks = "```" in text

    if includes_triple_backticks:
        try:
            action = text.split("```")[1]
            response = json.loads(action.strip())
            includes_action = "action" in response and "action_input" in response
            if includes_answer and includes_action:
                raise OutputParserException(
                    "Parsing LLM output produced a final answer "
                    f"and a parse-able action: {text}"
                )
            return AgentAction(response["action"], response["action_input"], text)

        except Exception:
            if not includes_answer:
                raise OutputParserException(f"Could not parse LLM output: {text}")
            return AgentFinish(
                {"output": text.split(FINAL_ANSWER_ACTION)[-1].strip()}, text
            )
    else:
        if not includes_answer:
            raise OutputParserException(f"Could not parse LLM output: {text}")
        return AgentFinish(
            {"output": text.split(FINAL_ANSWER_ACTION)[-1].strip()}, text
        )
```

This modification checks if the triple backticks are present in the text before attempting to split it. If they are not present, it directly proceeds to the `AgentFinish` block.

### Sources

- [langchain/agents/chat/output_parser.py](url)

**Comment by catskytw** [comment]
> 

Hi @SDcodehub 
Here you go

```python
Traceback (most recent call last):
  File "C:\Users\catsk\SourceCode\azure_openai_poc\venv\lib\site-packages\langchain\agents\chat\output_parser.py", line 18, in parse
    action = text.split("```")[1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\catsk\SourceCode\azure_openai_poc\venv\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\catsk\SourceCode\azure_openai_poc\venv\lib\site-packages\gradio\blocks.py", line 1346, in process_api
    result = await self.call_function(
  File "C:\Users\catsk\SourceCode\azure_openai_poc\venv\lib\site-packages\gradio\blocks.py", line 1074, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\catsk\SourceCode\azure_openai_poc\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\catsk\SourceCode\azure_openai_poc\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\catsk\SourceCode\azure_openai_poc\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\catsk\SourceCode\azure_openai_poc\app.py", line 691, in respond
    vector_search_message = local_vector_search(message, chat_history)
  File "C:\Users\catsk\SourceCode\azure_openai_poc\app.py", line 308, in local_vector_search
    result=agent.run(question_str)
  File "C:\Users\catsk\SourceCode\azure_openai_poc\venv\lib\site-packages\langchain\chains\base.py", line 267, in run
    return self(args[0], callbacks=callbacks, tags=tags)[self.output_keys[0]]
  File "C:\Users\catsk\SourceCode\azure_openai_poc\venv\lib\site-packages\langchain\chains\base.py", line 149, in __call__
    raise e
  File "C:\Users\catsk\SourceCode\azure_openai_poc\venv\lib\site-packages\langchain\chains\base.py", line 143, in __call__
    self._call(inputs, run_manager=run_manager)
  File "C:\Users\catsk\SourceCode\azure_openai_poc\venv\lib\site-packages\langchain\agents\agent.py", line 957, in _call
    next_step_output = self._take_next_step(
  File "C:\Users\catsk\SourceCode\azure_openai_poc\venv\lib\site-packages\langchain\agents\agent.py", line 773, in _take_next_step
    raise e
  File "C:\Users\catsk\SourceCode\azure_openai_poc\venv\lib\site-packages\langchain\agents\agent.py", line 762, in _take_next_step
    output = self.agent.plan(
  File "C:\Users\catsk\SourceCode\azure_openai_poc\venv\lib\site-packages\langchain\agents\agent.py", line 444, in plan
    return self.output_parser.parse(full_output)
  File "C:\Users\catsk\SourceCode\azure_openai_poc\venv\lib\site-packages\langchain\agents\chat\output_parser.py", line 30, in parse
    raise OutputParserException(f"Could not parse LLM output: {text}")
langchain.schema.OutputParserException: Could not parse LLM output: Knowledge Base:
長期出差通常是指一個人需要在外地或國外工作一段時間，通常是超過一個月以上的時間。這種出差通常需要安排住宿、交通、飲食等方面的問題，並需要考慮到長期分開與家人的情況。

```

**Comment by schinto** [comment]
Analog problem the https://github.com/hwchase17/langchain/blob/master/langchain/agents/conversational_chat/output_parser.py
had. Then the function `parse_json_markdown` was added, which still contains an error as reported in https://github.com/hwchase17/langchain/issues/5428 together with a proposed fix.
