### ISSUE TITLE
Getting error when using use_query_checker=True with SQLDatabaseSequentialChain

### ISSUE THREAD

**Issue by mail2mhossain** [langchain-ai/langchain#6407]
### System Info

LangChain 0.0.204, Windoews, Python 3.9.16, SQLAlchemy 2.0.15

Error: 
sqlalchemy.exc.DatabaseError: (oracledb.exceptions.DatabaseError) ORA-00933: SQL command not properly ended
[SQL: SELECT * FROM evr_region;]

Details:
SQLQuery:SELECT * FROM evr_region;Traceback (most recent call last):
  File "Z:\Users\User\anaconda3\envs\hugging_face_env\lib\site-packages\sqlalchemy\engine\base.py", line 1968, in _exec_single_context
    self.dialect.do_execute(
  File "Z:\Users\User\anaconda3\envs\hugging_face_env\lib\site-packages\sqlalchemy\engine\default.py", line 920, in do_execute
    cursor.execute(statement, parameters)
  File "Z:\Users\User\anaconda3\envs\hugging_face_env\lib\site-packages\oracledb\cursor.py", line 378, in execute
    impl.execute(self)
  File "src\oracledb\impl/thin/cursor.pyx", line 138, in oracledb.thin_impl.ThinCursorImpl.execute
  File "src\oracledb\impl/thin/protocol.pyx", line 385, in oracledb.thin_impl.Protocol._process_single_message
  File "src\oracledb\impl/thin/protocol.pyx", line 386, in oracledb.thin_impl.Protocol._process_single_message
  File "src\oracledb\impl/thin/protocol.pyx", line 379, in oracledb.thin_impl.Protocol._process_message
oracledb.exceptions.DatabaseError: ORA-00933: SQL command not properly ended

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Z:\MHossain_OneDrive\OneDrive\ChatGPT\LangChain\RAG\DatabaseQuery\sql_database_chain.py", line 89, in <module>
    chain.run("list the all values of evr region")
  File "Z:\Users\User\anaconda3\envs\hugging_face_env\lib\site-packages\langchain\chains\base.py", line 267, in run
    return self(args[0], callbacks=callbacks, tags=tags)[self.output_keys[0]]
  File "Z:\Users\User\anaconda3\envs\hugging_face_env\lib\site-packages\langchain\chains\base.py", line 149, in __call__
    raise e
  File "Z:\Users\User\anaconda3\envs\hugging_face_env\lib\site-packages\langchain\chains\base.py", line 143, in __call__
    self._call(inputs, run_manager=run_manager)
  File "Z:\Users\User\anaconda3\envs\hugging_face_env\lib\site-packages\langchain\chains\sql_database\base.py", line 280, in _call
    return self.sql_chain(
  File "Z:\Users\User\anaconda3\envs\hugging_face_env\lib\site-packages\langchain\chains\base.py", line 149, in __call__
    raise e
  File "Z:\Users\User\anaconda3\envs\hugging_face_env\lib\site-packages\langchain\chains\base.py", line 143, in __call__
    self._call(inputs, run_manager=run_manager)
  File "Z:\Users\User\anaconda3\envs\hugging_face_env\lib\site-packages\langchain\chains\sql_database\base.py", line 181, in _call
    raise exc
  File "Z:\Users\User\anaconda3\envs\hugging_face_env\lib\site-packages\langchain\chains\sql_database\base.py", line 151, in _call
    result = self.database.run(checked_sql_command)
  File "Z:\Users\User\anaconda3\envs\hugging_face_env\lib\site-packages\langchain\sql_database.py", line 348, in run
    cursor = connection.execute(text(command))
  File "Z:\Users\User\anaconda3\envs\hugging_face_env\lib\site-packages\sqlalchemy\engine\base.py", line 1413, in execute
    return meth(
  File "Z:\Users\User\anaconda3\envs\hugging_face_env\lib\site-packages\sqlalchemy\sql\elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
  File "Z:\Users\User\anaconda3\envs\hugging_face_env\lib\site-packages\sqlalchemy\engine\base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
  File "Z:\Users\User\anaconda3\envs\hugging_face_env\lib\site-packages\sqlalchemy\engine\base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "Z:\Users\User\anaconda3\envs\hugging_face_env\lib\site-packages\sqlalchemy\engine\base.py", line 1987, in _exec_single_context
    self._handle_dbapi_exception(
  File "Z:\Users\User\anaconda3\envs\hugging_face_env\lib\site-packages\sqlalchemy\engine\base.py", line 2344, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "Z:\Users\User\anaconda3\envs\hugging_face_env\lib\site-packages\sqlalchemy\engine\base.py", line 1968, in _exec_single_context
    self.dialect.do_execute(
  File "Z:\Users\User\anaconda3\envs\hugging_face_env\lib\site-packages\sqlalchemy\engine\default.py", line 920, in do_execute
    cursor.execute(statement, parameters)
  File "Z:\Users\User\anaconda3\envs\hugging_face_env\lib\site-packages\oracledb\cursor.py", line 378, in execute
    impl.execute(self)
  File "src\oracledb\impl/thin/cursor.pyx", line 138, in oracledb.thin_impl.ThinCursorImpl.execute
  File "src\oracledb\impl/thin/protocol.pyx", line 385, in oracledb.thin_impl.Protocol._process_single_message
  File "src\oracledb\impl/thin/protocol.pyx", line 386, in oracledb.thin_impl.Protocol._process_single_message
  File "src\oracledb\impl/thin/protocol.pyx", line 379, in oracledb.thin_impl.Protocol._process_message
sqlalchemy.exc.DatabaseError: (oracledb.exceptions.DatabaseError) ORA-00933: SQL command not properly ended
[SQL: SELECT * FROM evr_region;]
(Background on this error at: https://sqlalche.me/e/20/4xp6)

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

 Use **use_query_checker=True** with **SQLDatabaseSequentialChain**

chain = SQLDatabaseSequentialChain.from_llm(
    llm,
    db,
    query_prompt=PROMPT,
    verbose=True,
    use_query_checker=True,
)

### Expected behavior

There should not be error

**Comment by devstein** [comment]
_Generated by a 🤖_

This appears to be a duplicate of https://github.com/hwchase17/langchain/issues/6016

---

This response is meant to be helpful and save users time. It is not meant to be a precise solution.

Please leave a 👍 if this is helpful and 👎 if it is irrelevant

**Comment by Huwj-Ones** [comment]
https://github.com/hwchase17/langchain/issues/4768
