### ISSUE TITLE
Prebuild a dev container image to improve build time

### ISSUE THREAD

**Issue by bamurtaugh** [langchain-ai/langchain#6547]
### Feature request

Thanks so much for merging the PR to update the dev container in this repo https://github.com/hwchase17/langchain/pull/6189!

While the dev container now builds and runs successfully, it can take some time to build. One recommendation is for the LangChain team to pre-build an image.

### Motivation

We recommend pre-building images with the tools you need rather than creating and building a container image each time you open your project in a dev container. Using pre-built images will result in a faster container startup, simpler configuration, and allows you to pin to a specific version of tools to improve supply-chain security and avoid potential breaks. You can automate pre-building your image by scheduling the build using a DevOps or continuous integration (CI) service like GitHub Actions.

There's further info in our docs: https://containers.dev/implementors/reference/#prebuilding.

### Your contribution

We're more than happy to answer any questions and would love to hear feedback if you're interested in hosting a pre-built image! On the dev container team side, we're also looking to even better document pre-building: https://github.com/devcontainers/spec/issues/261, which should help as a reference for scenarios like this too.

**Comment by RadhikaBansal97** [comment]
Hi @bamurtaugh,

I have tried to run dev container multiple times both on codespaces and local machine(windows). But It always ends up giving this error.

Also attaching the creation.log file for your reference
[creation.log](https://github.com/hwchase17/langchain/files/11907200/creation.log)

executor failed running [/bin/sh -c chmod -R 0755 /tmp/dev-container-features/poetry_1 && cd /tmp/dev-container-features/poetry_1 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh]: exit code: 1
ERROR: Service 'langchain' failed to build : Build failed
2023-06-29 14:59:55.198Z: Stop: Run: docker-compose --project-name langchain_devcontainer -f /var/lib/docker/codespacemount/workspace/langchain/.devcontainer/docker-compose.yaml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose.codespaces.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose/docker-compose.devcontainer.build-1688050645299.yml build
2023-06-29 14:59:55.202Z: Error: Command failed: docker-compose --project-name langchain_devcontainer -f /var/lib/docker/codespacemount/workspace/langchain/.devcontainer/docker-compose.yaml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose.codespaces.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose/docker-compose.devcontainer.build-1688050645299.yml build
2023-06-29 14:59:55.206Z:     at Uw (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1969:412)
2023-06-29 14:59:55.207Z:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2023-06-29 14:59:55.209Z:     at async hte (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1969:2381)
2023-06-29 14:59:55.248Z:     at async fte (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1951:3170)
2023-06-29 14:59:55.249Z:     at async Lte (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2021:3833)
2023-06-29 14:59:55.254Z:     at async Hf (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2021:4775)
2023-06-29 14:59:55.256Z:     at async rne (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2152:10371)
2023-06-29 14:59:55.258Z:     at async tne (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2152:10112)
2023-06-29 14:59:55.267Z: {"outcome":"error","message":"Command failed: docker-compose --project-name langchain_devcontainer -f /var/lib/docker/codespacemount/workspace/langchain/.devcontainer/docker-compose.yaml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose.codespaces.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose/docker-compose.devcontainer.build-1688050645299.yml build","description":"An error occurred building the Docker Compose images."}
2023-06-29 14:59:55.274Z: devcontainer process exited with exit code 1

**Comment by dbline** [comment]
I am having the same issue trying to build docker-compose dev container.  it fails every time.  I can attach vscode to an already running container, but that is about it.

I can dump logs, but ultimately I am just getting the same error as the user above.  I can't find any other logging related to the failure
