### ISSUE TITLE
Problem to run on linux but not on windows 

### ISSUE THREAD

**Issue by aiakubovich** [langchain-ai/langchain#6678]
### System Info

see: https://github.com/hwchase17/langchain/discussions/1533

### Who can help?

@hwchase17 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

use FAISS on windows and next try to reuse those embeddings on lunix

### Expected behavior

```
I have a problem, when I want to run a project with langchain on windows, everything works perfectly, and with the same conditions on linux (libraries, python version, etc.) it doesn't work and throws this error, does anyone know what it could be?

2023-03-08 15:13:24 Failed to run listener function (error: search() missing 3 required positional arguments: 'k', 'distances', and 'labels')
2023-03-08 15:13:24 Traceback (most recent call last):
2023-03-08 15:13:24 File "/usr/local/lib/python3.9/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
2023-03-08 15:13:24 listener.run_ack_function(request=request, response=response)
2023-03-08 15:13:24 File "/usr/local/lib/python3.9/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
2023-03-08 15:13:24 return self.ack_function(
2023-03-08 15:13:24 File "//./main.py", line 28, in question
2023-03-08 15:13:24 response = processQuestion(query)
2023-03-08 15:13:24 File "/api.py", line 42, in processQuestion
2023-03-08 15:13:24 sources = doSimilaritySearch(index, query)
2023-03-08 15:13:24 File "/utils.py", line 87, in doSimilaritySearch
2023-03-08 15:13:24 docs = indexFaiss.similarity_search(query, k=5)
2023-03-08 15:13:24 File "/usr/local/lib/python3.9/site-packages/langchain/vectorstores/faiss.py", line 166, in similarity_search
2023-03-08 15:13:24 docs_and_scores = self.similarity_search_with_score(query, k)
2023-03-08 15:13:24 File "/usr/local/lib/python3.9/site-packages/langchain/vectorstores/faiss.py", line 136, in similarity_search_with_score
2023-03-08 15:13:24 docs = self.similarity_search_with_score_by_vector(embedding, k)
2023-03-08 15:13:24 File "/usr/local/lib/python3.9/site-packages/langchain/vectorstores/faiss.py", line 110, in similarity_search_with_score_by_vector
2023-03-08 15:13:24 scores, indices = self.index.search(np.array([embedding], dtype=np.float32), k)
2023-03-08 15:13:24 TypeError: search() missing 3 required positional arguments: 'k', 'distances', and 'labels'
```

**Comment by WitoldFracek** [comment]
I am using `faiss_cpu 1.7.4` and I still run into the issue mentioned above. I tried the solution suggested above

> _Answer generated by a 🤖_
> 
> ## Answer
> The error you're encountering is related to the FAISS library and not directly to LangChain. It seems that the FAISS library behaves differently on Windows and Linux. To fix the issue, you can try modifying the `similarity_search_with_score_by_vector` function in the `langchain/vectorstores/faiss.py` file.
> 
> Replace this line:
> 
> ```python
> scores, indices = self.index.search(np.array([embedding], dtype=np.float32), k)
> ```
> 
> with:
> 
> ```python
> embedding_array = np.array([embedding], dtype=np.float32)
> distances = np.empty((embedding_array.shape[0], k), dtype=np.float32)
> labels = np.empty((embedding_array.shape[0], k), dtype=np.int64)
> self.index.search(embedding_array, k, distances, labels)
> scores, indices = distances, labels
> ```

This does not work however. The error I get is that I'm missing one positional argument now. When I look into the documentation there is this parameter `n` that is not mentioned in the above solution. This error occurs only on Linux and not on Windows.
