### ISSUE TITLE
i try to connect mysql database,but it give me a error about llm value is not a valid dict(type=type_error.dict),how to  solve the problem?

### ISSUE THREAD

**Issue by xiaohaihui-smart** [langchain-ai/langchain#6959]
### Issue you'd like to raise.

from langchain.agents.agent_toolkits import SQLDatabaseToolkit
from langchain.sql_database import SQLDatabase
from transformers import AutoModel, AutoTokenizer
model_name = ".\\langchain-models\\THUDM\\chatglm2-6b"
local_model = AutoModel.from_pretrained(model_name, trust_remote_code=True)
local_tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
db = SQLDatabase.from_uri("mysql+pymysql://root:root@localhost/magic")
toolkit = SQLDatabaseToolkit(db=db, llm=local_model, tokenizer=local_tokenizer)
tables = toolkit.list_tables_sql_db()
print(tables)

Traceback (most recent call last):
  File "D:\chat\langchain-ChatGLM\test_sql.py", line 8, in <module>
    toolkit = SQLDatabaseToolkit(db=db, llm=local_model)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for SQLDatabaseToolkit
llm
  value is not a valid dict (type=type_error.dict)

**Comment by xiaohaihui-smart** [comment]
I tested the solution you provided, but there are several problems that need to be solved. BaseLanguageModel does not have the module from_pretrained, from langchain.agents.agent_toolkits import SQLDatabaseChain, SQLDatabaseChain fails to import the module, can you provide the code and location of these two methods, thank you
