### ISSUE TITLE
When the example is JSON it breaks PromptTemplate

### ISSUE THREAD

**Issue by eiso** [langchain-ai/langchain#700]
This is a very niche problem, but when you including JSON as one of the samples in your PromptTemplate it breaks the execution.

Code to replicate it:

```python
from langchain.llms import OpenAI
from langchain.chains import ConversationChain
from langchain import PromptTemplate, FewShotPromptTemplate
import json

prefix = """P:"""

examples = [
    {"instruction": "A", "sample": json.dumps({"a":"b"})},
    {"instruction": "B", "sample": json.dumps({"a":"b"})}
]


example_formatter_template = """{instruction}
\n
{sample}
"""

suffix = """S: {input}"""

example_prompt = PromptTemplate(
    input_variables=["instruction", "sample"],
    template=example_formatter_template,
)


few_shot_prompt = FewShotPromptTemplate(
    examples=examples,
    example_prompt=example_prompt,
    prefix=prefix,
    suffix=suffix,
    input_variables=["input"],
    example_separator="\n\n",
)

input = """TEST"""

print(few_shot_prompt.format(input=input))
```

The error is:

`Traceback (most recent call last):
  File "main.py", line 42, in <module>
    print(few_shot_prompt.format(input=input))
  File "/home/runner/Athena/venv/lib/python3.8/site-packages/langchain/prompts/few_shot.py", line 110, in format
    return DEFAULT_FORMATTER_MAPPING[self.template_format](template, **kwargs)
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/string.py", line 163, in format
    return self.vformat(format_string, args, kwargs)
  File "/home/runner/Athena/venv/lib/python3.8/site-packages/langchain/formatting.py", line 29, in vformat
    return super().vformat(format_string, args, kwargs)
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/string.py", line 167, in vformat
    result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/string.py", line 207, in _vformat
    obj, arg_used = self.get_field(field_name, args, kwargs)
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/string.py", line 272, in get_field
    obj = self.get_value(first, args, kwargs)
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/string.py", line 229, in get_value
    return kwargs[key]
KeyError: '"a"'`

**Comment by shoelsch** [comment]
Definitely a frustrating issue to hit, especially because JSON is a useful format for creating structured completions.

The issue is arising because the template's default formatter is relying on f-strings. Python's formatter is trying to interpolate the JSON-formatted string. To prevent that, the JSON will need to be escaped:

```
{{"a": "b"}}
```

```
examples = [
    {"instruction": "A", "sample": f'{{{json.dumps({"a":"b"})}}}'},
    {"instruction": "B", "sample": '{' + json.dumps({"a":"b"}) + '}'},
]
```

Another way to avoid this is to switch to the Jinja template format (and migrate your templates to the Jinja syntax):

```
few_shot_prompt = FewShotPromptTemplate(
    examples=examples,
    example_prompt=example_prompt,
    prefix=prefix,
    suffix=suffix,
    input_variables=["input"],
    example_separator="\n\n",
    template_format='jinja2',
)
```

**Comment by adumont** [comment]
Problem isn't only with JSON examples for FewShotPromptTemplate: if you have any word within curly braces `{}` in a template (even a simple PromptTemplate), it will fail when validate_template=False.

In my understanding what is not especifically declared as a `input_variables` shouldn't be replaced or looked up for replacement.

```
prompt=PromptTemplate(
    template="What is a good name for a {offending} company that makes {product}?",
    input_variables=["product"],
    validate_template=False,
)

prompt.format(product="colorful socks")
```

Error: KeyError: 'Fancy'

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[20], line 7
      1 prompt=PromptTemplate(
      2     template="What is a good name for a {Fancy} company that makes {product}?",
      3     input_variables=["product"],
      4     validate_template=False
      5 )
----> 7 prompt.format(product="colorful socks")

File c:\Users\adumont\Miniconda3\envs\ai39\lib\site-packages\langchain\prompts\prompt.py:66, in PromptTemplate.format(self, **kwargs)
     51 """Format the prompt with the inputs.
     52 
     53 Args:
   (...)
     63     prompt.format(variable1="foo")
     64 """
     65 kwargs = self._merge_partial_and_user_variables(**kwargs)
---> 66 return DEFAULT_FORMATTER_MAPPING[self.template_format](self.template, **kwargs)

File c:\Users\adumont\Miniconda3\envs\ai39\lib\string.py:161, in Formatter.format(self, format_string, *args, **kwargs)
    160 def format(self, format_string, /, *args, **kwargs):
--> 161     return self.vformat(format_string, args, kwargs)

File c:\Users\adumont\Miniconda3\envs\ai39\lib\site-packages\langchain\formatting.py:29, in StrictFormatter.vformat(self, format_string, args, kwargs)
     24 if len(args) > 0:
     25     raise ValueError(
     26         "No arguments should be provided, "
     27         "everything should be passed as keyword arguments."
     28     )
---> 29 return super().vformat(format_string, args, kwargs)

File c:\Users\adumont\Miniconda3\envs\ai39\lib\string.py:165, in Formatter.vformat(self, format_string, args, kwargs)
    163 def vformat(self, format_string, args, kwargs):
    164     used_args = set()
--> 165     result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
    166     self.check_unused_args(used_args, args, kwargs)
    167     return result

File c:\Users\adumont\Miniconda3\envs\ai39\lib\string.py:205, in Formatter._vformat(self, format_string, args, kwargs, used_args, recursion_depth, auto_arg_index)
    201     auto_arg_index = False
    203 # given the field_name, find the object it references
    204 #  and the argument it came from
--> 205 obj, arg_used = self.get_field(field_name, args, kwargs)
    206 used_args.add(arg_used)
    208 # do any conversion on the resulting object

File c:\Users\adumont\Miniconda3\envs\ai39\lib\string.py:270, in Formatter.get_field(self, field_name, args, kwargs)
    267 def get_field(self, field_name, args, kwargs):
    268     first, rest = _string.formatter_field_name_split(field_name)
--> 270     obj = self.get_value(first, args, kwargs)
    272     # loop through the rest of the field_name, doing
    273     #  getattr or getitem as needed
    274     for is_attr, i in rest:

File c:\Users\adumont\Miniconda3\envs\ai39\lib\string.py:227, in Formatter.get_value(self, key, args, kwargs)
    225     return args[key]
    226 else:
--> 227     return kwargs[key]

KeyError: 'Fancy'
```

**Comment by adumont** [comment]
As a work around we've used:

```
def preTratamiento(s: str):
    return s.replace("{", "#OPENED_CURLY_BRACE#").replace("}", "#CLOSED_CURLY_BRACE#")

def posTratamiento(s: str):
    return s.replace("#OPENED_CURLY_BRACE#", "{").replace("#CLOSED_CURLY_BRACE#", "}")

def tiktoken_len(text):
    tokens = tokenizer.encode(
        posTratamiento(text),
        disallowed_special=()
    )
    return len(tokens)
```

You'd have to process your examples with `preTratamiento()`, and then after a `promtTemplate.format()` you need to apply `posTratamiento()` again.

It worked for our case at least. If you are calling `promtTemplate.format()` directly you can easily encapsulate it in a `posTratamiento()`, if not, it can be trickier.
