### ISSUE TITLE
TypeError: issubclass() arg 1 must be a class (importing AsyncCallbackHandler)

### ISSUE THREAD

**Issue by blakebullwinkel** [langchain-ai/langchain#7037]
### System Info

Using the latest version of langchain (0.0.220).

### Who can help?

@hwchase17 @agola11 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [X] Callbacks/Tracing
- [X] Async

### Reproduction

1. `pip install langchain==0.0.220`
2. Run `from langchain.callbacks.base import AsyncCallbackHandler` in a Python script

Running this simple import gives the following traceback on my system:

```
Traceback (most recent call last):
  File "C:\Users\jblak\OneDrive\Documents\language-tutor\test.py", line 1, in <module>
    from langchain.callbacks.base import AsyncCallbackHandler
  File "C:\Users\jblak\anaconda3\lib\site-packages\langchain\__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "C:\Users\jblak\anaconda3\lib\site-packages\langchain\agents\__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "C:\Users\jblak\anaconda3\lib\site-packages\langchain\agents\agent.py", line 16, in <module>
    from langchain.agents.tools import InvalidTool
  File "C:\Users\jblak\anaconda3\lib\site-packages\langchain\agents\tools.py", line 8, in <module>
    from langchain.tools.base import BaseTool, Tool, tool
  File "C:\Users\jblak\anaconda3\lib\site-packages\langchain\tools\__init__.py", line 3, in <module>
    from langchain.tools.arxiv.tool import ArxivQueryRun
  File "C:\Users\jblak\anaconda3\lib\site-packages\langchain\tools\arxiv\tool.py", line 12, in <module>
    from langchain.utilities.arxiv import ArxivAPIWrapper
  File "C:\Users\jblak\anaconda3\lib\site-packages\langchain\utilities\__init__.py", line 3, in <module>
    from langchain.utilities.apify import ApifyWrapper
  File "C:\Users\jblak\anaconda3\lib\site-packages\langchain\utilities\apify.py", line 5, in <module>
    from langchain.document_loaders import ApifyDatasetLoader
  File "C:\Users\jblak\anaconda3\lib\site-packages\langchain\document_loaders\__init__.py", line 52, in <module>
    from langchain.document_loaders.github import GitHubIssuesLoader
  File "C:\Users\jblak\anaconda3\lib\site-packages\langchain\document_loaders\github.py", line 37, in <module>
    class GitHubIssuesLoader(BaseGitHubLoader):
  File "pydantic\main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic\fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 663, in pydantic.fields.ModelField._type_analysis
  File "pydantic\fields.py", line 808, in pydantic.fields.ModelField._create_sub_type
  File "pydantic\fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "C:\Users\jblak\anaconda3\lib\typing.py", line 852, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
```

### Expected behavior

Running this line should import the `AsyncCallbackHandler` without error.

**Comment by jeanmatthieud** [comment]
Same issue with 
`from langchain.document_loaders import PyMuPDFLoader`
