### ISSUE TITLE
Issue: Error when running `make coverage`

### ISSUE THREAD

**Issue by keenborder786** [langchain-ai/langchain#7100]
### Issue you'd like to raise.

When I run the command

```bash
make coverage
```
I get the following error:
```bash
collected 1556 items / 9 errors                                                                                                                                               
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/mohtashimkhan/mambaforge/envs/langchain/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1560, in getoption
INTERNALERROR>     val = getattr(self.option, name)
INTERNALERROR> AttributeError: 'Namespace' object has no attribute 'only_extended'
INTERNALERROR> 
INTERNALERROR> The above exception was the direct cause of the following exception:
INTERNALERROR> 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/mohtashimkhan/mambaforge/envs/langchain/lib/python3.9/site-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/mohtashimkhan/mambaforge/envs/langchain/lib/python3.9/site-packages/_pytest/main.py", line 322, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/home/mohtashimkhan/mambaforge/envs/langchain/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/home/mohtashimkhan/mambaforge/envs/langchain/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/home/mohtashimkhan/mambaforge/envs/langchain/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/mohtashimkhan/mambaforge/envs/langchain/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/mohtashimkhan/mambaforge/envs/langchain/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/mohtashimkhan/mambaforge/envs/langchain/lib/python3.9/site-packages/_pytest/main.py", line 333, in pytest_collection
INTERNALERROR>     session.perform_collect()
INTERNALERROR>   File "/home/mohtashimkhan/mambaforge/envs/langchain/lib/python3.9/site-packages/_pytest/main.py", line 668, in perform_collect
INTERNALERROR>     hook.pytest_collection_modifyitems(
INTERNALERROR>   File "/home/mohtashimkhan/mambaforge/envs/langchain/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/home/mohtashimkhan/mambaforge/envs/langchain/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/home/mohtashimkhan/mambaforge/envs/langchain/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/mohtashimkhan/mambaforge/envs/langchain/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/mohtashimkhan/mambaforge/envs/langchain/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/mohtashimkhan/langchain/tests/unit_tests/conftest.py", line 43, in pytest_collection_modifyitems
INTERNALERROR>     only_extended = config.getoption("--only-extended") or False
INTERNALERROR>   File "/home/mohtashimkhan/mambaforge/envs/langchain/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1571, in getoption
INTERNALERROR>     raise ValueError(f"no option named {name!r}") from e
INTERNALERROR> ValueError: no option named 'only_extended'
```

I am not sure what is the root cause of this issue. I created a new conda environment and installed poetry test,test_integration and main dependencies from scratch. 

### Versions:
- python: 3.9
- poetry: 1.5.1
- make: 4.3
- OS: Ubuntu 22.04.1 LTS

**Comment by NuODaniel** [comment]
Any suggestion here?
In my case:
```
python 3.10.10
OS: Centos 7.5

pytest                    7.4.0
pytest-asyncio            0.20.3
pytest-cov                4.1.0
pytest-dotenv             0.5.2
pytest-mock               3.11.1
pytest-socket             0.6.0
pytest-vcr                1.0.2
pytest-watcher            0.2.6
```

**Comment by amotl** [comment]
Same here.


### Reproduction

```shell
poetry install --no-interaction --no-ansi --with dev,test,docs,test_integration
```

```
source .venv/bin/activate
cd libs/langchain
pytest -k test_redis
```

### Details

<details>
<summary>Python Traceback</summary>

```python
(langchain-monorepo-py3.11) sink:langchain amo$ pytest -k test_redis
===================================================================== test session starts ======================================================================
platform darwin -- Python 3.11.4, pytest-7.4.0, pluggy-1.2.0
rootdir: /Users/amo/dev/crate/ecosystem/langchain/libs/langchain
configfile: pyproject.toml
plugins: asyncio-0.20.3, cov-4.1.0, vcr-1.0.2, syrupy-4.2.1, mock-3.11.1, anyio-3.7.1, dotenv-0.5.2, socket-0.6.0
asyncio: mode=Mode.STRICT
collected 2689 items / 1 error / 4 skipped
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/amo/dev/crate/ecosystem/langchain/.venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 1611, in getoption
INTERNALERROR>     val = getattr(self.option, name)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR> AttributeError: 'Namespace' object has no attribute 'only_extended'
INTERNALERROR>
INTERNALERROR> The above exception was the direct cause of the following exception:
INTERNALERROR>
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/amo/dev/crate/ecosystem/langchain/.venv/lib/python3.11/site-packages/_pytest/main.py", line 270, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>                          ^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/amo/dev/crate/ecosystem/langchain/.venv/lib/python3.11/site-packages/_pytest/main.py", line 323, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/Users/amo/dev/crate/ecosystem/langchain/.venv/lib/python3.11/site-packages/pluggy/_hooks.py", line 433, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/amo/dev/crate/ecosystem/langchain/.venv/lib/python3.11/site-packages/pluggy/_manager.py", line 112, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/amo/dev/crate/ecosystem/langchain/.venv/lib/python3.11/site-packages/pluggy/_callers.py", line 155, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/amo/dev/crate/ecosystem/langchain/.venv/lib/python3.11/site-packages/pluggy/_result.py", line 108, in get_result
INTERNALERROR>     raise exc.with_traceback(exc.__traceback__)
INTERNALERROR>   File "/Users/amo/dev/crate/ecosystem/langchain/.venv/lib/python3.11/site-packages/pluggy/_callers.py", line 80, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/amo/dev/crate/ecosystem/langchain/.venv/lib/python3.11/site-packages/_pytest/main.py", line 334, in pytest_collection
INTERNALERROR>     session.perform_collect()
INTERNALERROR>   File "/Users/amo/dev/crate/ecosystem/langchain/.venv/lib/python3.11/site-packages/_pytest/main.py", line 672, in perform_collect
INTERNALERROR>     hook.pytest_collection_modifyitems(
INTERNALERROR>   File "/Users/amo/dev/crate/ecosystem/langchain/.venv/lib/python3.11/site-packages/pluggy/_hooks.py", line 433, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/amo/dev/crate/ecosystem/langchain/.venv/lib/python3.11/site-packages/pluggy/_manager.py", line 112, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/amo/dev/crate/ecosystem/langchain/.venv/lib/python3.11/site-packages/pluggy/_callers.py", line 155, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/amo/dev/crate/ecosystem/langchain/.venv/lib/python3.11/site-packages/pluggy/_result.py", line 108, in get_result
INTERNALERROR>     raise exc.with_traceback(exc.__traceback__)
INTERNALERROR>   File "/Users/amo/dev/crate/ecosystem/langchain/.venv/lib/python3.11/site-packages/pluggy/_callers.py", line 80, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/amo/dev/crate/ecosystem/langchain/libs/langchain/tests/unit_tests/conftest.py", line 43, in pytest_collection_modifyitems
INTERNALERROR>     only_extended = config.getoption("--only-extended") or False
INTERNALERROR>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/amo/dev/crate/ecosystem/langchain/.venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 1622, in getoption
INTERNALERROR>     raise ValueError(f"no option named {name!r}") from e
INTERNALERROR> ValueError: no option named 'only_extended'
```
</details>
