### ISSUE TITLE
GPT4All generate() TypeError 'n_ctx' since a commit on GPT4All's python binding changed arguments

### ISSUE THREAD

**Issue by nb-programmer** [langchain-ai/langchain#7145]
### System Info

- langchain-0.0.222 (and all before)
- Any GPT4All python package after [this commit](https://github.com/nomic-ai/gpt4all/commit/46a0762bd5a7e605e9bd63e4f435b482eff026f6#diff-cc3ea7dfbfc9837a4c42dae1089a1eda0ed175d17f2628cf16c13d3cd9da6e13R174) was merged. So latest: >= 1.0.1.

Note this issue is in langchain caused by GPT4All's change. We need to alter the _default_params() return values to exclude many keys that were removed from GPT4All's function kwargs.

### Who can help?

@hwchase17 @agola11 👋

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Install the latest gpt4all package: `pip install --upgrade gpt4all`
2. Use the GPT4All LLM and LLMChain as normal (llm = GPT4All(model="ggml.gpt4all.xyz.bin"); chain = LLMChain(llm, prompt=any_prompt))
3. Run the chain: chain("prompt")
4. TypeError: generate() got an unexpected keyword argument 'n_ctx'

### Expected behavior

Should not cause TypeError. It should not pass n_ctx from default parameters to GPT4All's `generate()`

**Comment by nb-programmer** [comment]
Entire error traceback:
```
Traceback (most recent call last):
  File "f:\Projects\gpt\privateGPT\venv\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "f:\Projects\gpt\privateGPT\venv\lib\site-packages\gradio\blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "f:\Projects\gpt\privateGPT\venv\lib\site-packages\gradio\blocks.py", line 1093, in call_function
    prediction = await utils.async_iteration(iterator)
  File "f:\Projects\gpt\privateGPT\venv\lib\site-packages\gradio\utils.py", line 341, in async_iteration
    return await iterator.__anext__()
  File "langchain_gradio.py", line 214, in generate
    await output_task
  File "C:\Program Files\Python39\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "langchain_gradio.py", line 142, in run_chain_sync
    result = chain(inputs, callbacks=[stream_callback])
  File "f:\Projects\gpt\privateGPT\venv\lib\site-packages\langchain\chains\base.py", line 166, in __call__
    raise e
  File "f:\Projects\gpt\privateGPT\venv\lib\site-packages\langchain\chains\base.py", line 160, in __call__
    self._call(inputs, run_manager=run_manager)
  File "f:\Projects\gpt\privateGPT\venv\lib\site-packages\langchain\chains\qa_with_sources\base.py", line 128, in _call
    answer = self.combine_documents_chain.run(
  File "f:\Projects\gpt\privateGPT\venv\lib\site-packages\langchain\chains\base.py", line 293, in run
    return self(kwargs, callbacks=callbacks, tags=tags)[_output_key]
  File "f:\Projects\gpt\privateGPT\venv\lib\site-packages\langchain\chains\base.py", line 166, in __call__
    raise e
  File "f:\Projects\gpt\privateGPT\venv\lib\site-packages\langchain\chains\base.py", line 160, in __call__
    self._call(inputs, run_manager=run_manager)
  File "f:\Projects\gpt\privateGPT\venv\lib\site-packages\langchain\chains\combine_documents\base.py", line 84, in _call
    output, extra_return_dict = self.combine_docs(
  File "f:\Projects\gpt\privateGPT\venv\lib\site-packages\langchain\chains\combine_documents\stuff.py", line 87, in combine_docs
    return self.llm_chain.predict(callbacks=callbacks, **inputs), {}
  File "f:\Projects\gpt\privateGPT\venv\lib\site-packages\langchain\chains\llm.py", line 252, in predict
    return self(kwargs, callbacks=callbacks)[self.output_key]
  File "f:\Projects\gpt\privateGPT\venv\lib\site-packages\langchain\chains\base.py", line 166, in __call__
    raise e
  File "f:\Projects\gpt\privateGPT\venv\lib\site-packages\langchain\chains\base.py", line 160, in __call__
    self._call(inputs, run_manager=run_manager)
  File "f:\Projects\gpt\privateGPT\venv\lib\site-packages\langchain\chains\llm.py", line 92, in _call
    response = self.generate([inputs], run_manager=run_manager)
  File "f:\Projects\gpt\privateGPT\venv\lib\site-packages\langchain\chains\llm.py", line 102, in generate
    return self.llm.generate_prompt(
  File "f:\Projects\gpt\privateGPT\venv\lib\site-packages\langchain\llms\base.py", line 141, in generate_prompt     
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
  File "f:\Projects\gpt\privateGPT\venv\lib\site-packages\langchain\llms\base.py", line 227, in generate
    output = self._generate_helper(
  File "f:\Projects\gpt\privateGPT\venv\lib\site-packages\langchain\llms\base.py", line 178, in _generate_helper    
    raise e
  File "f:\Projects\gpt\privateGPT\venv\lib\site-packages\langchain\llms\base.py", line 165, in _generate_helper    
    self._generate(
  File "f:\Projects\gpt\privateGPT\venv\lib\site-packages\langchain\llms\base.py", line 525, in _generate
    self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)
  File "f:\Projects\gpt\privateGPT\venv\lib\site-packages\langchain\llms\gpt4all.py", line 208, in _call
    for token in self.client.generate(prompt, **params):
TypeError: generate() got an unexpected keyword argument 'n_ctx'
```

**Comment by devstein** [comment]
https://github.com/hwchase17/langchain/pull/7093

**Comment by rlancemartin** [comment]
Yes, I also hit this yesterday and put up / merged a PR to resolve:

https://github.com/hwchase17/langchain/pull/7093

Note: this *may* be a breaking change for users that upgrade LangChain, but are *still using the older* GPT4All client. If anyone has additional context on GPT4All client, I'd welcome a backwards compatible fix. My first time using GPT4All was yesterday and I noticed it was broken, so fixed it here but do not have a lot of context on the client.

**Comment by nb-programmer** [comment]
Yeah same, I encountered it by accident after updating gpt4all. I hadn't seen the PR you created as I looked straight for the issues tab.
But anyway yeah this will force people to upgrade gpt4all package to allow the langchain wrapper to function still

**Comment by rlancemartin** [comment]
> Yeah same, I encountered it by accident after updating gpt4all. I hadn't seen the PR you created as I looked straight for the issues tab.
> 
> But anyway yeah this will force people to upgrade gpt4all package to allow the langchain wrapper to function still

Got it. If you see an easy way to make it backwards compatible, feel free to put up a follow-up PR. It wasn't too obvious to me other than some fairly ugly try-catch logic, but as noted I don't have a lot of context on the GPT4All client. Perhaps a warning to tell users to upgrade the package?

**Comment by Kuramdasu-ujwala-devi** [comment]
Yeah same, I encountered it.
use this combination of versions
Name: langchain
Version: 0.0.171
Name: gpt4all
Version: 1.0.3
It worked for me. You can try this.
