### ISSUE TITLE
Chroma DB Error

### ISSUE THREAD

**Issue by aqibamir** [langchain-ai/langchain#7260]
### System Info
Error: Please install chromadb as a dependency with, e.g. `npm install -S chromadb`
    at Function.imports (file:///home/aqib/backend-11/vision/node_modules/langchain/dist/vectorstores/chroma.js:160:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Chroma.ensureCollection (file:///home/aqib/backend-11/vision/node_modules/langchain/dist/vectorstores/chroma.js:61:42)
    at async Chroma.addVectors (file:///home/aqib/backend-11/vision/node_modules/langchain/dist/vectorstores/chroma.js:88:28)
    at async Chroma.addDocuments (file:///home/aqib/backend-11/vision/node_modules/langchain/dist/vectorstores/chroma.js:56:9)
    at async Function.fromDocuments (file:///home/aqib/backend-11/vision/node_modules/langchain/dist/vectorstores/chroma.js:145:9)
    at async add (file:///home/aqib/backend-11/vision/vectorStore/db.js:24:5)
    at async run (file:///home/aqib/backend-11/vision/vectorStore/insertDocs.js:6:3)
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

**_Got this when I console Logged the error_**
ReferenceError: fetch is not defined
    at Object.<anonymous> (/home/aqib/backend-11/vision/node_modules/chromadb/dist/main/generated/runtime.js:17:24)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/home/aqib/backend-11/vision/node_modules/chromadb/dist/main/generated/api.js:17:19)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Call any Chroma method to reproduce this issue

### Expected behavior

It should've inserted the documents

**Comment by sjcuello** [comment]
any solution ?

**Comment by VikashLoomba** [comment]
Having this same issue after updating my chromadb npm package to 1.5.11 in order to get auth support. Now I am getting the error 
`(node:50497) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
error Error: Please install chromadb as a dependency with, e.g. `npm install -S chromadb`
    at Chroma.imports (file:///Users/vikashloomba/Desktop/Projects/gpt4-pdf-chatbot-langchain/node_modules/langchain/dist/vectorstores/chroma.js:287:19)`

**Comment by zhjch05** [comment]
Facing same error with langchain 0.0.153 and chroma client 1.5.11

**Comment by 6ygga** [comment]
rollback to 1.5.6

**Comment by simonry14** [comment]
Rolling back to 1.5.6 did not resolve the issue for me

**Comment by JCASTANO** [comment]
+1

**Comment by gfitzy123** [comment]
+1

**Comment by rotichbryant** [comment]
@VikashLoomba  Did you manage to solve it ? I also get a similar error.

Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)

F:\Repositories\typelly\backend\node_modules\langchain\dist\vectorstores\chroma.cjs:313
            throw new Error("Please install chromadb as a dependency with, e.g. `npm install -S chromadb`");
                  ^
Error: Please install chromadb as a dependency with, e.g. `npm install -S chromadb`
    at Function.imports (F:\Repositories\typelly\backend\node_modules\langchain\dist\vectorstores\chroma.cjs:313:19)
    at Chroma.ensureCollection (F:\Repositories\typelly\backend\node_modules\langchain\dist\vectorstores\chroma.cjs:115:42)
    at Chroma.addVectors (F:\Repositories\typelly\backend\node_modules\langchain\dist\vectorstores\chroma.cjs:152:28)
    at Function.fromDocuments (F:\Repositories\typelly\backend\node_modules\langchain\dist\vectorstores\chroma.cjs:288:9)
    at F:\Repositories\typelly\backend\src\controllers\ai_app\ai.app.controller.ts:66:37

Attached is where the code giving the error. I have installed chromadb but still get this error.

![Screenshot 2023-10-25 101752](https://github.com/langchain-ai/langchain/assets/16875378/444ba20f-3723-487f-af52-1a09e1245303)

**Comment by drifterz13** [comment]
It looks like `await import("chromadb")` syntax does not support on the `.cjs` file. I managed to work around on this by
1. Edit the the import line to `const { ChromaClient } = require("chromadb")`
2. Run `npx patch-package langchain` in order to create `patches` directory that contains diff between both versions.
3. Setup `"postinstall": "patch-package"` so it will patch the change after install packages.

**Comment by VikashLoomba** [comment]
> @VikashLoomba Did you manage to solve it ? I also get a similar error.
> 
> Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension. (Use `node --trace-warnings ...` to show where the warning was created)
> 
> F:\Repositories\typelly\backend\node_modules\langchain\dist\vectorstores\chroma.cjs:313 throw new Error("Please install chromadb as a dependency with, e.g. `npm install -S chromadb`"); ^ Error: Please install chromadb as a dependency with, e.g. `npm install -S chromadb` at Function.imports (F:\Repositories\typelly\backend\node_modules\langchain\dist\vectorstores\chroma.cjs:313:19) at Chroma.ensureCollection (F:\Repositories\typelly\backend\node_modules\langchain\dist\vectorstores\chroma.cjs:115:42) at Chroma.addVectors (F:\Repositories\typelly\backend\node_modules\langchain\dist\vectorstores\chroma.cjs:152:28) at Function.fromDocuments (F:\Repositories\typelly\backend\node_modules\langchain\dist\vectorstores\chroma.cjs:288:9) at F:\Repositories\typelly\backend\src\controllers\ai_app\ai.app.controller.ts:66:37
> 
> Attached is where the code giving the error. I have installed chromadb but still get this error.
> 
> ![Screenshot 2023-10-25 101752](https://private-user-images.githubusercontent.com/16875378/277905850-444ba20f-3723-487f-af52-1a09e1245303.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4NTk2MTYsIm5iZiI6MTcwMDg1OTMxNiwicGF0aCI6Ii8xNjg3NTM3OC8yNzc5MDU4NTAtNDQ0YmEyMGYtMzcyMy00ODdmLWFmNTItMWEwOWUxMjQ1MzAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI0VDIwNTUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkOGZkMmZmMWI2YjRlY2Q3ZTlkN2U4YmFhNWY3YjhjMGExYTYzZTkxZDU3ZDIyMGRlNzI5NWQwYWJkYmE2MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OFyz6zTbKfco2EASVEtIS1NOTOy3_Z51K0WFgQP3Rmg)

I managed to solve it, I have a repo called HelloPDF with the code on my profile
