### ISSUE TITLE
Error occurs when `import langchain.agents`

### ISSUE THREAD

**Issue by liliYY** [langchain-ai/langchain#7458]
Hi there,
I am new to langchain and I encountered some problems when import `langchain.agents`.

I run `main.py` as follows:

```python
# main.py
# python main.py
import os
os.environ["OPENAI_API_KEY"]="my key"
import langchain.agents
```

Some errors occur:

```
Traceback (most recent call last):
  File "F:\LLM_publichousing\me\main.py", line 6, in <module>
    import langchain.agents
  File "C:\ProgramData\Anaconda3\envs\ly\lib\site-packages\langchain\__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "C:\ProgramData\Anaconda3\envs\ly\lib\site-packages\langchain\agents\__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "C:\ProgramData\Anaconda3\envs\ly\lib\site-packages\langchain\agents\agent.py", line 16, in <module>
    from langchain.agents.tools import InvalidTool
  File "C:\ProgramData\Anaconda3\envs\ly\lib\site-packages\langchain\agents\tools.py", line 8, in <module>
    from langchain.tools.base import BaseTool, Tool, tool
  File "C:\ProgramData\Anaconda3\envs\ly\lib\site-packages\langchain\tools\__init__.py", line 3, in <module>
    from langchain.tools.arxiv.tool import ArxivQueryRun
  File "C:\ProgramData\Anaconda3\envs\ly\lib\site-packages\langchain\tools\arxiv\tool.py", line 12, in <module>
    from langchain.utilities.arxiv import ArxivAPIWrapper
  File "C:\ProgramData\Anaconda3\envs\ly\lib\site-packages\langchain\utilities\__init__.py", line 3, in <module>
    from langchain.utilities.apify import ApifyWrapper
  File "C:\ProgramData\Anaconda3\envs\ly\lib\site-packages\langchain\utilities\apify.py", line 5, in <module>
    from langchain.document_loaders import ApifyDatasetLoader
  File "C:\ProgramData\Anaconda3\envs\ly\lib\site-packages\langchain\document_loaders\__init__.py", line 54, in <module>
    from langchain.document_loaders.github import GitHubIssuesLoader
  File "C:\ProgramData\Anaconda3\envs\ly\lib\site-packages\langchain\document_loaders\github.py", line 37, in <module>
    class GitHubIssuesLoader(BaseGitHubLoader):
  File "pydantic\main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic\fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 663, in pydantic.fields.ModelField._type_analysis
  File "pydantic\fields.py", line 808, in pydantic.fields.ModelField._create_sub_type
  File "pydantic\fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "C:\ProgramData\Anaconda3\envs\ly\lib\typing.py", line 852, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
```

The langchain version is `0.0.228`

My system is Windows 10.

**Comment by xingyanan** [comment]
Hi @liliYY  Which version of Python?

**Comment by xingyanan** [comment]
> > Hi @liliYY Which version of Python?
> 
> 3.9.3

you can try 3.10.*

**Comment by priyamsaha1012** [comment]
pip install pydantic==1.10.8 worked for me

**Comment by pedram-tehranchi** [comment]
i have same problem. when i try to from langchain.llms import OpenAI im getting error.
pip install pydantic==1.10.11,
typing-inspect==0.8.0
typing_extensions==4.5.0
not worked for me...

**Comment by liliYY** [comment]
。
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hwchase17/langchain"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月15日(星期六) 晚上10:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hwchase17/langchain] Error occurs when `import langchain.agents` (Issue #7458)





 
i have same problem. when i try to from langchain.llms import OpenAI im getting error.
 pip install pydantic==1.10.11,
 typing-inspect==0.8.0
 typing_extensions==4.5.0
 not worked for me...
