### ISSUE TITLE
Crash occurs when using RedisSemanticCache() as a cache 

### ISSUE THREAD

**Issue by gsparsh220598** [langchain-ai/langchain#7722]
### System Info

langchain==0.0.232
python==3.8.16
M1 mac

### Who can help?

@hwchase17 @ago

The way that cache is stored in redis is like

> HGET key_name "metadata"
"{\"llm_string\": \"{\\\"lc\\\": 1, \\\"type\\\": \\\"constructor\\\", \\\"id\\\": [\\\"langchain\\\", \\\"chat_models\\\", \\\"openai\\\", \\\"ChatOpenAI\\\"], \\\"kwargs\\\": {\\\"model_name\\\": \\\"gpt-3.5-turbo-0613\\\", \\\"temperature\\\": 0.1, \\\"streaming\\\": true, \\\"openai_api_key\\\": {\\\"lc\\\": 1, \\\"type\\\": \\\"secret\\\", \\\"id\\\": [\\\"OPENAI_API_KEY\\\"]}}}---[('stop', None)]\", \"prompt\": \"[{\\\"lc\\\": 1, \\\"type\\\": \\\"constructor\\\", \\\"id\\\": [\\\"langchain\\\", \\\"schema\\\", \\\"messages\\\", \\\"HumanMessage\\\"], \\\"kwargs\\\": {\\\"content\\\": \\\"Given the following conversation and a follow up question, rephrase the follow up question to be a standalone question, in its original language.\\\\n\\\\nChat History:\\\\n\\\\nHuman: how is it similar to VQ-GAN?\\\\nAssistant: I don't know what\\\\nFollow Up Input: what is nas?\\\\nStandalone question:\\\"}}]\", \"return_val\": [\"What does NAS stand for?\"]}"

> HGET key_name "content"
"[{\"lc\": 1, \"type\": \"constructor\", \"id\": [\"langchain\", \"schema\", \"messages\", \"HumanMessage\"], \"kwargs\": {\"content\": \"Given the following conversation and a follow up question, rephrase the follow up question to be a standalone question, in its original language.\\n\\nChat History:\\n\\nHuman: how is it similar to VQ-GAN?\\nAssistant: I don't know what\\nFollow Up Input: what is nas?\\nStandalone question:\"}}]"

Is this how its supposed to be?

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

langchain.llm_cache = RedisSemanticCache(
    redis_url="redis://localhost:6379", embedding=emb_fn
)

retrieved_chat_history = RedisChatMessageHistory(
       session_id=f"{MEM_INDEX_NAME}:",
       url=REDIS_URL,
)
retrieved_memory = ConversationBufferMemory(
       chat_memory=retrieved_chat_history,
       memory_key="history",
       return_messages=True,
)
llm = ChatOpenAI(
    model_name=CHAT_MODEL,
    temperature=0.1,
    streaming=True,
    callbacks=[StreamingStdOutCallbackHandler()],
)
qa = ConversationChain(llm=llm, memory=retrieved_memory, prompt=CHAT_PROMPT)

res = qa({"question": query})

Enter a question: what is nas?
Thinking... (print_fn)
'message'
Traceback (most recent call last):
  File "chat.py", line 109, in <module>
    response = chain({"input": query})
  File "/Users/sparshgupta/mambaforge/envs/openai_env/lib/python3.8/site-packages/langchain/chains/base.py", line 243, in __call__
    raise e
  File "/Users/sparshgupta/mambaforge/envs/openai_env/lib/python3.8/site-packages/langchain/chains/base.py", line 237, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/Users/sparshgupta/mambaforge/envs/openai_env/lib/python3.8/site-packages/langchain/chains/llm.py", line 92, in _call
    response = self.generate([inputs], run_manager=run_manager)
  File "/Users/sparshgupta/mambaforge/envs/openai_env/lib/python3.8/site-packages/langchain/chains/llm.py", line 102, in generate
    return self.llm.generate_prompt(
  File "/Users/sparshgupta/mambaforge/envs/openai_env/lib/python3.8/site-packages/langchain/chat_models/base.py", line 230, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
  File "/Users/sparshgupta/mambaforge/envs/openai_env/lib/python3.8/site-packages/langchain/chat_models/base.py", line 125, in generate
    raise e
  File "/Users/sparshgupta/mambaforge/envs/openai_env/lib/python3.8/site-packages/langchain/chat_models/base.py", line 115, in generate
    self._generate_with_cache(
  File "/Users/sparshgupta/mambaforge/envs/openai_env/lib/python3.8/site-packages/langchain/chat_models/base.py", line 272, in _generate_with_cache
    return ChatResult(generations=cache_val)
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1076, in pydantic.main.validate_model
  File "pydantic/fields.py", line 895, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 928, in pydantic.fields.ModelField._validate_sequence_like
  File "pydantic/fields.py", line 1094, in pydantic.fields.ModelField._validate_singleton
  File "pydantic/fields.py", line 884, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 1101, in pydantic.fields.ModelField._validate_singleton
  File "pydantic/fields.py", line 1157, in pydantic.fields.ModelField._apply_validators
  File "pydantic/class_validators.py", line 337, in pydantic.class_validators._generic_validator_basic.lambda13
  File "pydantic/main.py", line 719, in pydantic.main.BaseModel.validate
  File "/Users/sparshgupta/mambaforge/envs/openai_env/lib/python3.8/site-packages/langchain/load/serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1102, in pydantic.main.validate_model
  File "/Users/sparshgupta/mambaforge/envs/openai_env/lib/python3.8/site-packages/langchain/schema/output.py", line 42, in set_text
    values["text"] = values["message"].content
KeyError: 'message'

### Expected behavior

Regular caching behaviour as shown in https://python.langchain.com/docs/modules/model_io/models/llms/integrations/llm_caching

**Comment by thedamnedrhino** [comment]
The problem is that the cache always returns base `Generation` instances, whereas the `ChatResult` created in the `BaseChatModel` expects `ChatGeneration` instances. And that is true for other caches as well. Have you tried this pipeline other cache classes?

**Comment by gsparsh220598** [comment]
@thedamnedrhino 

> The problem is that the cache always returns base `Generation` instances, whereas the `ChatResult` created in the `BaseChatModel` expects `ChatGeneration` instances. And that is true for other caches as well. Have you tried this pipeline other cache classes to verify?

I have tried `InMemoryCache` and `SQLiteCache`, although the code does not crash the caching does not appear to be working

for eg. 

Enter a question: tell me a joke
Thinking...
Sure, here's a joke for you:

bot: Why don't scientists trust atoms?
Because they make up everything!
> Answer (took 1.78 s.):

Enter a question: tell me a joke
Thinking...
Sure, here's a joke for you:

bot: Why don't scientists trust atoms?
Because they make up everything!
> Answer (took 1.47 s.):

It should not take this long to answer the same question the second time.

**Comment by gsparsh220598** [comment]
> The problem is that the cache always returns base `Generation` instances, whereas the `ChatResult` created in the `BaseChatModel` expects `ChatGeneration` instances.

How to fix this then? is there an open PR or can I create one to have a go at a fix?

**Comment by thedamnedrhino** [comment]
If you're using `ConversationChain` with the cache, it's expected that you wouldn't get cached results if you submit two identical queries **in one conversation**. This is because each time the current input AND the chat history is passed to the LLM.

**Comment by thedamnedrhino** [comment]
I'm looking into the `RedisSemanticCache` problem. You can submit a fix if you like, though I don't know if it's any use to you given the above. 
Actually I'm surprised that other caches are working with this chain. Are you using the same chain with `InMemoryCache`?

**Comment by thedamnedrhino** [comment]
@hwchase17 perhaps this doesn't need a fix because the cache is not meant to be used in a conversation chain to begin with..

**Comment by Vasilije1990** [comment]
I am also seeing it, even with regular cache and functions @thedamnedrhino `Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 241, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 167, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api.py", line 398, in recipe_request
    output = await agent.solution_generation(json_payload["prompt"], model_speed="slow", prompt_template=None, json_example=None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/llm_chains/chains.py", line 446, in solution_generation
    output = await chain.arun(input = prompt)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain/chains/base.py", line 524, in arun
    await self.acall(
  File "/usr/local/lib/python3.11/site-packages/langchain/chains/base.py", line 310, in acall
    raise e
  File "/usr/local/lib/python3.11/site-packages/langchain/chains/base.py", line 304, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/usr/local/lib/python3.11/site-packages/langchain/chains/llm.py", line 234, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain/chains/llm.py", line 116, in agenerate
    return await self.llm.agenerate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain/chat_models/base.py", line 240, in agenerate_prompt
    return await self.agenerate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain/chat_models/base.py", line 200, in agenerate
    raise exceptions[0]
  File "/usr/local/lib/python3.11/site-packages/langchain/chat_models/base.py", line 311, in _agenerate_with_cache
    return ChatResult(generations=cache_val)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 339, in __init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 1076, in validate_model
    v_, errors_ = field.validate(value, values, loc=field.alias, cls=cls_)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/fields.py", line 895, in validate
    v, errors = self._validate_sequence_like(v, values, loc, cls)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/fields.py", line 928, in _validate_sequence_like
    r, ee = self._validate_singleton(v_, values, v_loc, cls)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/fields.py", line 1094, in _validate_singleton
    value, error = field.validate(v, values, loc=loc, cls=cls)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/fields.py", line 884, in validate
    v, errors = self._validate_singleton(v, values, loc, cls)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/fields.py", line 1101, in _validate_singleton
    return self._apply_validators(v, values, loc, cls, self.validators)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/fields.py", line 1157, in _apply_validators
    v = validator(cls, v, values, self, self.model_config)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/class_validators.py", line 337, in <lambda>
    return lambda cls, v, values, field, config: validator(v)
                                                 ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 719, in validate
    return cls(**value_as_dict)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain/load/serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 339, in __init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 1102, in validate_model
    values = validator(cls_, values)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain/schema/output.py", line 42, in set_text
    values["text"] = values["message"].content
                     ~~~~~~^^^^^^^^^^^
KeyError: 'message'`

**Comment by baskaryan** [comment]
fix in #8041. redis cache actually doesn't support caching chat model outputs as currently implemented. #8041 skips trying to cache chat model updates so at least things don't error, but note that you still shouldn't try to use redis cache with chat models for now

**Comment by thedamnedrhino** [comment]
Does it make sense to have cache for chat models, considering they usually involve history?

**Comment by keenborder786** [comment]
> I am also seeing it, even with regular cache and functions @thedamnedrhino `Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__ await self.app(scope, receive, _send) File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__ raise exc File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__ await self.app(scope, receive, sender) File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__ raise e File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__ await self.app(scope, receive, send) File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__ await route.handle(scope, receive, send) File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle await self.app(scope, receive, send) File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app response = await func(request) ^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 241, in app raw_response = await run_endpoint_function( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 167, in run_endpoint_function return await dependant.call(**values) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/app/api.py", line 398, in recipe_request output = await agent.solution_generation(json_payload["prompt"], model_speed="slow", prompt_template=None, json_example=None) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/app/llm_chains/chains.py", line 446, in solution_generation output = await chain.arun(input = prompt) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/langchain/chains/base.py", line 524, in arun await self.acall( File "/usr/local/lib/python3.11/site-packages/langchain/chains/base.py", line 310, in acall raise e File "/usr/local/lib/python3.11/site-packages/langchain/chains/base.py", line 304, in acall await self._acall(inputs, run_manager=run_manager) File "/usr/local/lib/python3.11/site-packages/langchain/chains/llm.py", line 234, in _acall response = await self.agenerate([inputs], run_manager=run_manager) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/langchain/chains/llm.py", line 116, in agenerate return await self.llm.agenerate_prompt( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/langchain/chat_models/base.py", line 240, in agenerate_prompt return await self.agenerate( ^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/langchain/chat_models/base.py", line 200, in agenerate raise exceptions[0] File "/usr/local/lib/python3.11/site-packages/langchain/chat_models/base.py", line 311, in _agenerate_with_cache return ChatResult(generations=cache_val) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 339, in __init__ values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 1076, in validate_model v_, errors_ = field.validate(value, values, loc=field.alias, cls=cls_) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/pydantic/fields.py", line 895, in validate v, errors = self._validate_sequence_like(v, values, loc, cls) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/pydantic/fields.py", line 928, in _validate_sequence_like r, ee = self._validate_singleton(v_, values, v_loc, cls) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/pydantic/fields.py", line 1094, in _validate_singleton value, error = field.validate(v, values, loc=loc, cls=cls) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/pydantic/fields.py", line 884, in validate v, errors = self._validate_singleton(v, values, loc, cls) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/pydantic/fields.py", line 1101, in _validate_singleton return self._apply_validators(v, values, loc, cls, self.validators) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/pydantic/fields.py", line 1157, in _apply_validators v = validator(cls, v, values, self, self.model_config) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/pydantic/class_validators.py", line 337, in <lambda> return lambda cls, v, values, field, config: validator(v) ^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 719, in validate return cls(**value_as_dict) ^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/langchain/load/serializable.py", line 74, in __init__ super().__init__(**kwargs) File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 339, in __init__ values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 1102, in validate_model values = validator(cls_, values) ^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/langchain/schema/output.py", line 42, in set_text values["text"] = values["message"].content ~~~~~~^^^^^^^^^^^ KeyError: 'message'`

I am still facing the same error when using the `init_similar_cache`.
