### ISSUE TITLE
Argument 'string' has incorrect type (expected str, got lxml.etree._ElementUnicodeResult)

### ISSUE THREAD

**Issue by softzer0** [langchain-ai/langchain#7968]
### System Info

LangChain version is the latest one - 0.0.237

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```python
def text_split(documents):
    text_splitter = SpacyTextSplitter(chunk_size=1000, chunk_overlap=10, separator='\n')
    texts = []
    for document in documents:
        texts.extend(text_splitter.split_documents(document.load()))
    return texts
```
Using this simple code, I get this error:
```
  Traceback (most recent call last):
 ...
    File "/opt/project/main/genie.py", line 41, in text_split
      texts.extend(text_splitter.split_documents(document.load()))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/langchain/text_splitter.py", line 131, in split_documents
      return self.create_documents(texts, metadatas=metadatas)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/langchain/text_splitter.py", line 116, in create_documents
      for chunk in self.split_text(text):
                   ^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/langchain/text_splitter.py", line 1047, in split_text
      splits = (s.text for s in self._tokenizer(text).sents)
                                ^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/spacy/language.py", line 1030, in __call__
      doc = self._ensure_doc(text)
            ^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/spacy/language.py", line 1121, in _ensure_doc
      return self.make_doc(doc_like)
             ^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/spacy/language.py", line 1113, in make_doc
      return self.tokenizer(text)
             ^^^^^^^^^^^^^^^^^^^^
  TypeError: Argument 'string' has incorrect type (expected str, got lxml.etree._ElementUnicodeResult)
```
I've also tried approach with alternative `split_text` method, but still getting the same error.

### Expected behavior

If I put a breakpoint at [langchain/text_splitter.py:116](https://github.com/hwchase17/langchain/blob/master/langchain/text_splitter.py#L116) and execute `text = str(text)` and resume the process, only then it works.

**Comment by rjarun8** [comment]
@softzer0 Could you provide additional information on this?

Between this is what I tried. Seem to have worked ok.

```
from langchain.document_loaders import TextLoader
txt_loader1 = TextLoader(r"G:\RajArun\langchain\.venv\state_of_the_union.txt",encoding="utf-8")
txt_loader2 = TextLoader(r"G:\RajArun\langchain\.venv\state_of_the_union.txt",encoding="utf-8")
txt_loader3 = [txt_loader1,txt_loader2]

def text_split(documents):
    text_splitter = SpacyTextSplitter(chunk_size=1000, chunk_overlap=10, separator='\n')
    texts = []
    for document in documents:
        texts.extend(text_splitter.split_documents(document.load()))
    return texts

text_split(txt_loader3)

```

**Comment by softzer0** [comment]
Strangely, it works for me now too. I didn't manage to determine what was the issue though.
