### ISSUE TITLE
How can I use ConversationEntityMemory with the conversational-react-description agent?

### ISSUE THREAD

**Issue by dnkanga** [langchain-ai/langchain#801]
There seems to be an error when running the script using the `ConversationEntityMemory` class. The error message states that a key is missing from the inputs dictionary passed to the agent_chain.run() function. Specifically, the chat_history key is missing. The script is designed to use the ConversationEntityMemory class to store and retrieve conversation history, however, it seems that the chat_history key is not being passed to the agent_chain.run() function properly.

What's the best way to go about changing the memory of an agent?

Python Code:

```
from langchain import OpenAI, LLMChain
from langchain.agents import initialize_agent, ConversationalAgent, AgentExecutor
from langchain.agents import load_tools
from langchain.chains.conversation.memory import ConversationEntityMemory

if __name__ == '__main__':
    tools = load_tools(["google-search"])
    llm = OpenAI(temperature=0)
    prompt = ConversationalAgent.create_prompt(
        tools,
        input_variables=["input", "chat_history", "agent_scratchpad"]
    )
    memory = ConversationEntityMemory(llm=llm)

    llm_chain = LLMChain(llm=OpenAI(temperature=0), prompt=prompt)
    agent = ConversationalAgent(llm_chain=llm_chain, tools=tools, verbose=True)
    agent_chain = AgentExecutor.from_agent_and_tools(agent=agent, tools=tools, verbose=True, memory=memory)
    output = agent_chain.run(input="Who won the 2019 NBA Finals?")

```

Error:
```
Traceback (most recent call last):
  File "app2.py", line 18, in <module>
    output = agent_chain.run(input="Who won the 2019 NBA Finals?")
  File "/home/user/PycharmProjects/my-project/venv/lib/python3.8/site-packages/langchain/chains/base.py", line 183, in run
    return self(kwargs)[self.output_keys[0]]
  File "/home/user/PycharmProjects/my-project/venv/lib/python3.8/site-packages/langchain/chains/base.py", line 145, in __call__
    self._validate_inputs(inputs)
  File "/home/user/PycharmProjects/my-project/venv/lib/python3.8/site-packages/langchain/chains/base.py", line 101, in _validate_inputs
    raise ValueError(f"Missing some input keys: {missing_keys}")
ValueError: Missing some input keys: {'chat_history'}

```

requirements.txt
```
apturl==0.5.2
autopep8==2.0.1
beautifulsoup4==4.11.1
blinker==1.4
Brlapi==0.7.0
cachetools==5.3.0
certifi==2019.11.28
cffi==1.15.1
chardet==3.0.4
charset-normalizer==3.0.1
chrome-gnome-shell==0.0.0
Click==7.0
colorama==0.4.3
command-not-found==0.3
cryptography==38.0.4
cupshelpers==1.0
dbus-python==1.2.16
defer==1.0.6
distro==1.4.0
distro-info===0.23ubuntu1
entrypoints==0.3
google-api-core==2.11.0
google-api-python-client==2.74.0
google-auth==2.16.0
google-auth-httplib2==0.1.0
googleapis-common-protos==1.58.0
httplib2==0.21.0
idna==2.8
keyring==18.0.1
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
libvirt-python==6.1.0
louis==3.12.0
lxml==4.9.2
macaroonbakery==1.3.1
netifaces==0.10.4
numpy==1.24.1
oauthlib==3.1.0
pandas==1.5.2
pbr==5.11.1
pdfminer.six==20221105
protobuf==4.21.12
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycairo==1.16.2
pycodestyle==2.10.0
pycparser==2.21
pycups==1.9.73
PyGObject==3.36.0
PyJWT==1.7.1
pymacaroons==0.13.0
PyNaCl==1.3.0
pyparsing==3.0.9
PyPDF2==3.0.0
pyRFC3339==1.1
python-apt==2.0.0+ubuntu0.20.4.8
python-dateutil==2.8.2
python-debian===0.1.36ubuntu1
pytz==2022.7
pyxdg==0.26
PyYAML==5.3.1
requests==2.22.0
requests-unixsocket==0.2.0
rsa==4.9
SecretStorage==2.3.1
simplejson==3.16.0
six==1.14.0
soupsieve==2.3.2.post1
systemd-python==234
testresources==2.0.1
tomli==2.0.1
typing_extensions==4.4.0
ubuntu-advantage-tools==27.12
ubuntu-drivers-common==0.0.0
ufw==0.36
unattended-upgrades==0.1
uritemplate==4.1.1
urllib3==1.25.8
wadllib==1.3.3
xkit==0.0.0
```

**Comment by hwchase17** [comment]
this https://github.com/hwchase17/langchain/pull/808 should help fix that - you can then specify `chat_history_key="chat_history"` when creating the memory
