### ISSUE TITLE
Error when importing ChatOutputParser: no validator found for <class 're.Pattern'>

### ISSUE THREAD

**Issue by SpaceDandy13** [langchain-ai/langchain#8158]
### System Info

from langchain.agents.chat.output_parser import ChatOutputParser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/chatpdf/Backend/backenv/lib/python3.10/site-packages/langchain/__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "/home/ubuntu/chatpdf/Backend/backenv/lib/python3.10/site-packages/langchain/agents/__init__.py", line 10, in <module>
    from langchain.agents.agent_toolkits import (
  File "/home/ubuntu/chatpdf/Backend/backenv/lib/python3.10/site-packages/langchain/agents/agent_toolkits/__init__.py", line 6, in <module>
    from langchain.agents.agent_toolkits.csv.base import create_csv_agent
  File "/home/ubuntu/chatpdf/Backend/backenv/lib/python3.10/site-packages/langchain/agents/agent_toolkits/csv/base.py", line 4, in <module>
    from langchain.agents.agent_toolkits.pandas.base import create_pandas_dataframe_agent
  File "/home/ubuntu/chatpdf/Backend/backenv/lib/python3.10/site-packages/langchain/agents/agent_toolkits/pandas/base.py", line 18, in <module>
    from langchain.agents.types import AgentType
  File "/home/ubuntu/chatpdf/Backend/backenv/lib/python3.10/site-packages/langchain/agents/types.py", line 5, in <module>
    from langchain.agents.chat.base import ChatAgent
  File "/home/ubuntu/chatpdf/Backend/backenv/lib/python3.10/site-packages/langchain/agents/chat/base.py", line 6, in <module>
    from langchain.agents.chat.output_parser import ChatOutputParser
  File "/home/ubuntu/chatpdf/Backend/backenv/lib/python3.10/site-packages/langchain/agents/chat/output_parser.py", line 12, in <module>
    class ChatOutputParser(AgentOutputParser):
  File "pydantic/main.py", line 229, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 491, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 421, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 542, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 804, in pydantic.fields.ModelField.populate_validators
  File "pydantic/validators.py", line 723, in find_validators
RuntimeError: no validator found for <class 're.Pattern'>, see `arbitrary_types_allowed` in Config

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [X] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain.agents.chat.output_parser import ChatOutputParser

### Expected behavior

Import corrrectly.

**Comment by SpaceDandy13** [comment]
Is this a version problem? I am not familair with re.pattern, is there a

**Comment by jhnyc** [comment]
@SpaceDandy13 How did you resolve the problem eventually? I keep getting this error.

**Comment by SpaceDandy13** [comment]
> @SpaceDandy13 How did you resolve the problem eventually? I keep getting this error.

I just use the old version.

**Comment by divya-r-kamat** [comment]
@SpaceDandy13 which version did you use, please can you share the version number, even I am getting similar error. I have tried couple of older versions.

**Comment by Ezhvsalate** [comment]
Was getting same issue right now with v. 0.0.142
Was fixed for me by upgrading pydantic to 1.10.8

**Comment by gabriellopesdesouza2002** [comment]
Changing the version to pydantic==1.10.8 worked for me using a flask api in pythonanywhere

**Comment by azaiman1** [comment]
I am still getting this error even when installing pydantic 1.10.8 I was wondering if there is anything else I should do?

**Comment by MLuis-Model** [comment]
I had the exact same issue and was working with Jupyter Notebook.
It seems like Jupyter is causing this problem, as it works in Pycharm. 
So I can recommend to switch IDE.

**Comment by gilfernandes** [comment]
After downgrading to 1.10.12 this error went away for me.

Using poetry:

```
[tool.poetry.dependencies]
...
pydantic = "1.10.12"
```

```
Package operations: 0 installs, 1 update, 0 removals

  • Downgrading pydantic (2.3.0 -> 1.10.12)
```

**Comment by ilaner** [comment]
Hello, I experience the same issue after upgrading to pydantic v2.
Lanchain doesn't fully support pydantic v2?
