### ISSUE TITLE
LangChain 0.0.250 circular import bug, possibly LangSmith related

### ISSUE THREAD

**Issue by dzmitry-kankalovich** [langchain-ai/langchain#8680]
### System Info

There seems to be a circular import problem introduced with `langsmith` dependency.

I believe so, because this problem is constantly appearing in the `langchain` versions that do include `langsmith` dependency, and for example `0.0.230` seems to be ok (I don't see that one including `langsmith` as dep), but latter versions are exhibiting the same problem. And there is also `langchain` / `langsmith` back-fourth in stacktrace.

The error:
```text
Traceback (most recent call last):
  File "/Users/Dzmitry_Kankalovich/Workspace/personal/langsmith.py", line 2, in <module>
    from langchain.chat_models import ChatOpenAI
  File "/Users/Dzmitry_Kankalovich/Workspace/personal/.venv/lib/python3.11/site-packages/langchain/__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "/Users/Dzmitry_Kankalovich/Workspace/personal/.venv/lib/python3.11/site-packages/langchain/agents/__init__.py", line 31, in <module>
    from langchain.agents.agent import (
  File "/Users/Dzmitry_Kankalovich/Workspace/personal/.venv/lib/python3.11/site-packages/langchain/agents/agent.py", line 15, in <module>
    from langchain.agents.agent_iterator import AgentExecutorIterator
  File "/Users/Dzmitry_Kankalovich/Workspace/personal/.venv/lib/python3.11/site-packages/langchain/agents/agent_iterator.py", line 21, in <module>
    from langchain.callbacks.manager import (
  File "/Users/Dzmitry_Kankalovich/Workspace/personal/.venv/lib/python3.11/site-packages/langchain/callbacks/__init__.py", line 21, in <module>
    from langchain.callbacks.manager import (
  File "/Users/Dzmitry_Kankalovich/Workspace/personal/.venv/lib/python3.11/site-packages/langchain/callbacks/manager.py", line 41, in <module>
    from langchain.callbacks.tracers.langchain import LangChainTracer
  File "/Users/Dzmitry_Kankalovich/Workspace/personal/.venv/lib/python3.11/site-packages/langchain/callbacks/tracers/__init__.py", line 3, in <module>
    from langchain.callbacks.tracers.langchain import LangChainTracer
  File "/Users/Dzmitry_Kankalovich/Workspace/personal/.venv/lib/python3.11/site-packages/langchain/callbacks/tracers/langchain.py", line 11, in <module>
    from langsmith import Client
  File "/Users/Dzmitry_Kankalovich/Workspace/personal/langsmith.py", line 2, in <module>
    from langchain.chat_models import ChatOpenAI
  File "/Users/Dzmitry_Kankalovich/Workspace/personal/.venv/lib/python3.11/site-packages/langchain/chat_models/__init__.py", line 20, in <module>
    from langchain.chat_models.anthropic import ChatAnthropic
  File "/Users/Dzmitry_Kankalovich/Workspace/personal/.venv/lib/python3.11/site-packages/langchain/chat_models/anthropic.py", line 3, in <module>
    from langchain.callbacks.manager import (
ImportError: cannot import name 'AsyncCallbackManagerForLLMRun' from partially initialized module 'langchain.callbacks.manager' (most likely due to a circular import) (/Users/Dzmitr
y_Kankalovich/Workspace/personal/.venv/lib/python3.11/site-packages/langchain/callbacks/manager.py)
```

### Who can help?

@hwchase17 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [X] Callbacks/Tracing
- [ ] Async

### Reproduction
0. Use python `3.11`
1. Take sample *LangSmith* code from their tutorial:
```py
import os
from langchain.chat_models import ChatOpenAI

os.environ['LANGCHAIN_TRACING_V2'] = 'true'
os.environ['LANGCHAIN_ENDPOINT'] = "https://api.smith.langchain.com"

llm = ChatOpenAI()
llm.predict("Hello, world!")
```
2. Provision fresh `venv` with the following dependencies:
```text
langchain==0.0.250
openai==0.27.8
```
3. Observe stacktrace:
```text
    from langchain.callbacks.tracers.langchain import LangChainTracer
  File "/Users/Dzmitry_Kankalovich/Workspace/personal/.venv/lib/python3.11/site-packages/langchain/callbacks/tracers/__init__.py", line 3, in <module>
    from langchain.callbacks.tracers.langchain import LangChainTracer
  File "/Users/Dzmitry_Kankalovich/Workspace/personal/.venv/lib/python3.11/site-packages/langchain/callbacks/tracers/langchain.py", line 11, in <module>
    from langsmith import Client
  File "/Users/Dzmitry_Kankalovich/Workspace/personal/langsmith.py", line 2, in <module>
    from langchain.chat_models import ChatOpenAI
  File "/Users/Dzmitry_Kankalovich/Workspace/personal/.venv/lib/python3.11/site-packages/langchain/chat_models/__init__.py", line 20, in <module>
    from langchain.chat_models.anthropic import ChatAnthropic
  File "/Users/Dzmitry_Kankalovich/Workspace/personal/.venv/lib/python3.11/site-packages/langchain/chat_models/anthropic.py", line 3, in <module>
    from langchain.callbacks.manager import (
ImportError: cannot import name 'AsyncCallbackManagerForLLMRun' from partially initialized module 'langchain.callbacks.manager' (most likely due to a circular import) (/Users/Dzmitr
y_Kankalovich/Workspace/personal/.venv/lib/python3.11/site-packages/langchain/callbacks/manager.py)
```

### Expected behavior

No errors, llm reply received

**Comment by hinthornw** [comment]
@dzmitry-kankalovich if you rename your script from `langsmith.py` to `langsmith_test.py` or something that doesn't mask the `langsmith` module name, do you still get this error?

**Comment by dzmitry-kankalovich** [comment]
Indeed! That seems to be the case. I've changed name and don't see the problem anymore. 

Well, this one is on Python then. Can close the issue.
