### ISSUE TITLE
import DirectoryLoader generate error

### ISSUE THREAD

**Issue by qingtian1771** [langchain-ai/langchain#9609]
### System Info

langchain version: 0.0.270
python version: 3.11.0
os: Ubuntu 20.04.6 LTS

### Who can help?

@hwchase17 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

in a python file, there is only one line of code like following:

`from langchain.document_loaders import DirectoryLoader`

when run it, it generate following errorss:

```
Traceback (most recent call last):
  File "/home/tq/code/langchain/python_311/project/01_test.py", line 1, in <module>
    from langchain.document_loaders import DirectoryLoader
  File "/home/tq/anaconda3/envs/py311/lib/python3.11/site-packages/langchain/__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "/home/tq/anaconda3/envs/py311/lib/python3.11/site-packages/langchain/agents/__init__.py", line 31, in <module>
    from langchain.agents.agent import (
  File "/home/tq/anaconda3/envs/py311/lib/python3.11/site-packages/langchain/agents/agent.py", line 14, in <module>
    from langchain.agents.agent_iterator import AgentExecutorIterator
  File "/home/tq/anaconda3/envs/py311/lib/python3.11/site-packages/langchain/agents/agent_iterator.py", line 30, in <module>
    from langchain.tools import BaseTool
  File "/home/tq/anaconda3/envs/py311/lib/python3.11/site-packages/langchain/tools/__init__.py", line 41, in <module>
    from langchain.tools.gmail import (
  File "/home/tq/anaconda3/envs/py311/lib/python3.11/site-packages/langchain/tools/gmail/__init__.py", line 3, in <module>
    from langchain.tools.gmail.create_draft import GmailCreateDraft
  File "/home/tq/anaconda3/envs/py311/lib/python3.11/site-packages/langchain/tools/gmail/create_draft.py", line 7, in <module>
    from langchain.tools.gmail.base import GmailBaseTool
  File "/home/tq/anaconda3/envs/py311/lib/python3.11/site-packages/langchain/tools/gmail/base.py", line 16, in <module>
    from googleapiclient.discovery import Resource
  File "/home/tq/anaconda3/envs/py311/lib/python3.11/site-packages/googleapiclient/discovery.py", line 57, in <module>
    from googleapiclient import _auth, mimeparse
  File "/home/tq/anaconda3/envs/py311/lib/python3.11/site-packages/googleapiclient/_auth.py", line 34, in <module>
    import oauth2client.client
  File "/home/tq/anaconda3/envs/py311/lib/python3.11/site-packages/oauth2client/client.py", line 47, in <module>
    from oauth2client import crypt
  File "/home/tq/anaconda3/envs/py311/lib/python3.11/site-packages/oauth2client/crypt.py", line 55, in <module>
    from oauth2client import _pycrypto_crypt
  File "/home/tq/anaconda3/envs/py311/lib/python3.11/site-packages/oauth2client/_pycrypto_crypt.py", line 17, in <module>
    from Crypto.PublicKey import RSA
  File "/home/tq/anaconda3/envs/py311/lib/python3.11/site-packages/Crypto/PublicKey/__init__.py", line 29, in <module>
    from Crypto.Util.asn1 import (DerSequence, DerInteger, DerBitString,
  File "/home/tq/anaconda3/envs/py311/lib/python3.11/site-packages/Crypto/Util/asn1.py", line 33, in <module>
    from Crypto.Util.number import long_to_bytes, bytes_to_long
  File "/home/tq/anaconda3/envs/py311/lib/python3.11/site-packages/Crypto/Util/number.py", line 398
    s = pack('>I', n & 0xffffffffL) + s
                                ^
SyntaxError: invalid hexadecimal literal

```
please help, thanks!

### Expected behavior

import DirectoryLoader should be work.

**Comment by qingtian1771** [comment]
I got following error when I install "pip install --upgrade pycrypto"

```
(py311) tq@tq-sy:~/code/langchain/python_311/project$ pip install --upgrade pycrypto
Collecting pycrypto
  Using cached pycrypto-2.6.1.tar.gz (446 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pycrypto
  Building wheel for pycrypto (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [71 lines of output]
      checking for gcc... gcc
      checking whether the C compiler works... yes
      checking for C compiler default output file name... a.out
      checking for suffix of executables...
      checking whether we are cross compiling... no
      checking for suffix of object files... o
      checking whether we are using the GNU C compiler... yes
      checking whether gcc accepts -g... yes
      checking for gcc option to accept ISO C89... none needed
      checking for __gmpz_init in -lgmp... yes
      checking for __gmpz_init in -lmpir... no
      checking whether mpz_powm is declared... yes
      checking whether mpz_powm_sec is declared... yes
      checking how to run the C preprocessor... gcc -E
      checking for grep that handles long lines and -e... /bin/grep
      checking for egrep... /bin/grep -E
      checking for ANSI C header files... yes
      checking for sys/types.h... yes
      checking for sys/stat.h... yes
      checking for stdlib.h... yes
      checking for string.h... yes
      checking for memory.h... yes
      checking for strings.h... yes
      checking for inttypes.h... yes
      checking for stdint.h... yes
      checking for unistd.h... yes
      checking for inttypes.h... (cached) yes
      checking limits.h usability... yes
      checking limits.h presence... yes
      checking for limits.h... yes
      checking stddef.h usability... yes
      checking stddef.h presence... yes
      checking for stddef.h... yes
      checking for stdint.h... (cached) yes
      checking for stdlib.h... (cached) yes
      checking for string.h... (cached) yes
      checking wchar.h usability... yes
      checking wchar.h presence... yes
      checking for wchar.h... yes
      checking for inline... inline
      checking for int16_t... yes
      checking for int32_t... yes
      checking for int64_t... yes
      checking for int8_t... yes
      checking for size_t... yes
      checking for uint16_t... yes
      checking for uint32_t... yes
      checking for uint64_t... yes
      checking for uint8_t... yes
      checking for stdlib.h... (cached) yes
      checking for GNU libc compatible malloc... yes
      checking for memmove... yes
      checking for memset... yes
      configure: creating ./config.status
      config.status: creating src/config.h
      In file included from /home/tq/anaconda3/envs/py311/include/python3.11/Python.h:12,
                       from src/_fastmath.c:31:
      /home/tq/anaconda3/envs/py311/include/python3.11/pyconfig.h:1784: warning: "_POSIX_C_SOURCE" redefined
       1784 | #define _POSIX_C_SOURCE 200809L
            |
      In file included from /usr/include/x86_64-linux-gnu/bits/libc-header-start.h:33,
                       from /usr/include/stdio.h:27,
                       from src/_fastmath.c:29:
      /usr/include/features.h:310: note: this is the location of the previous definition
        310 | # define _POSIX_C_SOURCE 199506L
            |
      src/_fastmath.c:33:10: fatal error: longintrepr.h: 没有那个文件或目录
         33 | #include <longintrepr.h>    /* for conversions */
            |          ^~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycrypto
  Running setup.py clean for pycrypto
Failed to build pycrypto
Installing collected packages: pycrypto
  Running setup.py install for pycrypto ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for pycrypto did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      /home/tq/anaconda3/envs/py311/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      In file included from /home/tq/anaconda3/envs/py311/include/python3.11/Python.h:12,
                       from src/_fastmath.c:31:
      /home/tq/anaconda3/envs/py311/include/python3.11/pyconfig.h:1784: warning: "_POSIX_C_SOURCE" redefined
       1784 | #define _POSIX_C_SOURCE 200809L
            |
      In file included from /usr/include/x86_64-linux-gnu/bits/libc-header-start.h:33,
                       from /usr/include/stdio.h:27,
                       from src/_fastmath.c:29:
      /usr/include/features.h:310: note: this is the location of the previous definition
        310 | # define _POSIX_C_SOURCE 199506L
            |
      src/_fastmath.c:33:10: fatal error: longintrepr.h: 没有那个文件或目录
         33 | #include <longintrepr.h>    /* for conversions */
            |          ^~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pycrypto

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

```

**Comment by qingtian1771** [comment]
I unsintall pycryptodome, and it works now.
`pip uninstall pycryptodome`

**Comment by qingtian1771** [comment]
I unsintall pycryptodome, and it works now.
`pip uninstall pycryptodome`
