### ISSUE TITLE
DOC: <Please write a comprehensive title after the 'DOC: ' prefix>

### ISSUE THREAD

**Issue by Travis-Barton** [langchain-ai/langchain#9680]
### Issue with current documentation:

The basic documents for the output parser are out of date for pydantic. Tried with python 3.9 and 3.11.

```
pip install langchain
pip install python-dotenv
```

The copied code:

```
from langchain.prompts import PromptTemplate, ChatPromptTemplate, HumanMessagePromptTemplate
from langchain.llms import OpenAI
from langchain.chat_models import ChatOpenAI
from dotenv import load_dotenv
from langchain.output_parsers import PydanticOutputParser
from pydantic import BaseModel, Field, validator
from typing import List
load_dotenv()

model_name = 'text-davinci-003'
temperature = 0.0
model = OpenAI(model_name=model_name, temperature=temperature)

# Define your desired data structure.
class Joke(BaseModel):
    setup: str = Field(description="question to set up a joke")
    punchline: str = Field(description="answer to resolve the joke")
    
    # You can add custom validation logic easily with Pydantic.
    @validator('setup')
    def question_ends_with_question_mark(cls, field):
        if field[-1] != '?':
            raise ValueError("Badly formed question!")
        return field

# Set up a parser + inject instructions into the prompt template.
parser = PydanticOutputParser(pydantic_object=Joke)

prompt = PromptTemplate(
    template="Answer the user query.\n{format_instructions}\n{query}\n",
    input_variables=["query"],
    partial_variables={"format_instructions": parser.get_format_instructions()}
)

# And a query intended to prompt a language model to populate the data structure.
joke_query = "Tell me a joke."
_input = prompt.format_prompt(query=joke_query)

output = model(_input.to_string())

parser.parse(output)
```

results in:
```
<input>:21: PydanticDeprecatedSince20: Pydantic V1 style `@validator` validators are deprecated. You should migrate to Pydantic V2 style `@field_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.3/migration/
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 16, in <module>
  File "/Users/travisbarton/opt/anaconda3/envs/scratch39/lib/python3.9/site-packages/pydantic/_internal/_model_construction.py", line 130, in __new__
    cls.__pydantic_decorators__ = DecoratorInfos.build(cls)
  File "/Users/travisbarton/opt/anaconda3/envs/scratch39/lib/python3.9/site-packages/pydantic/_internal/_decorators.py", line 441, in build
    res.validators[var_name] = Decorator.build(
  File "/Users/travisbarton/opt/anaconda3/envs/scratch39/lib/python3.9/site-packages/pydantic/_internal/_decorators.py", line 249, in build
    func = shim(func)
  File "/Users/travisbarton/opt/anaconda3/envs/scratch39/lib/python3.9/site-packages/pydantic/_internal/_decorators_v1.py", line 77, in make_generic_v1_field_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: The `field` and `config` parameters are not available in Pydantic V2, please use the `info` parameter instead.
For further information visit https://errors.pydantic.dev/2.3/u/validator-field-config-info
```

### Idea or request for content:

Maybe fix the validator to match pydantic? Perhaps I'm mistaken?

**Comment by tedsecretsource** [comment]
It's not just with the documentation. When you run the code, you see warnings. Here's an example of where the old validator type is still being used

https://github.com/langchain-ai/langchain/blob/289b3422dc242da75de7976cd324ffd7b3d301dc/libs/community/langchain_community/document_loaders/googledrive.py#L103C6-L103C15

This is not a major problem, obviously, but one does tire of seeing warnings…
