### ISSUE TITLE
How to connect MS-SQL with LANG-CHAIN

### ISSUE THREAD

**Issue by AnasKhan-25** [langchain-ai/langchain#9848]
### Issue you'd like to raise.

db = SQLDatabase.from_uri(
"mysql+pyodbc://Driver={SQL Server};Server=DESKTOP-17L7UI1\SQLEXPRESS;Database=DociQDb;rusted_Connection=yes;",)

I am trying to connect to my microsoft sql server but this give me error 
sqlalchemy.exc.DBAPIError: (pyodbc.Error) ('IM010', '[IM010] [Microsoft][ODBC Driver Manager] Data source name too long (0) (SQLDriverConnect)')

**Comment by AnasKhan-25** [comment]
> _🤖_
> 
> Hello,
> 
> From the error message you provided, it seems like the issue is with the connection string you're using to connect to your MS-SQL database. The error message `Data source name too long` typically indicates that the connection string is not formatted correctly.
> 
> In your connection string, you're using the MySQL driver (`mysql+pyodbc://`) to connect to an MS-SQL database, which could be causing the issue. You should use the MS-SQL driver instead.
> 
> Here's an example of how your connection string should look:
> 
> ```python
> db = SQLDatabase.from_uri(
> "mssql+pyodbc://username:password@DESKTOP-17L7UI1\SQLEXPRESS/DociQDb?driver=SQL+Server",)
> ```
> 
> Please replace `username` and `password` with your actual username and password for the SQL server.
> 
> Also, make sure that the SQL Server driver is installed on your machine. If it's not, you can download it from the official Microsoft website.
> 
> If you're still having issues after trying these steps, please provide more details about your setup (e.g., Python version, LangChain version, operating system) so I can assist you further.
> 
> Best regards, Dosu
> 
> ## Sources
> * [libs/experimental/langchain_experimental/sql/base.py](https://github.com/langchain-ai/langchain/blob/-/libs/experimental/langchain_experimental/sql/base.py)
> * [libs/langchain/langchain/utilities/sql_database.py](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/langchain/utilities/sql_database.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

db = SQLDatabase.from_uri(
"mssql+pyodbc://user1:Aksiq@312@DESKTOP-17L7UI1\SQLEXPRESS/DociQDb?driver=SQL+Server",)

I have change the connection_string to your desire pattern 
but it show error 
sqlalchemy.exc.OperationalError: (pyodbc.OperationalError) ('08001', '[08001] [Microsoft][ODBC SQL Server Driver][DBNETLIB]SQL Server does not exist or access denied. (17) (SQLDriverConnect); [08001] [Microsoft][ODBC SQL Server Driver][DBNETLIB]ConnectionOpen (Connect()). (53)')

**Comment by AnasKhan-25** [comment]
> _🤖_
> 
> Hello,
> 
> Based on the error message you're receiving, it seems like there might be an issue with the connection string you're using to connect to your Microsoft SQL Server database. The error message `sqlalchemy.exc.DBAPIError: (pyodbc.Error) ('IM010', '[IM010] [Microsoft][ODBC Driver Manager] Data source name too long (0) (SQLDriverConnect)')` typically indicates that the Data Source Name (DSN) specified in the connection string is too long.
> 
> From the code you've shared, it appears that you're using the MySQL driver (`mysql+pyodbc`) in your connection string. However, you should be using the MS-SQL driver (`mssql+pyodbc`) instead, as you've been advised.
> 
> Here's how your connection string should look:
> 
> ```python
> db = SQLDatabase.from_uri(
> "mssql+pyodbc://username:password@DESKTOP-17L7UI1\SQLEXPRESS/DociQDb?driver=SQL+Server",)
> ```
> 
> Please replace `username` and `password` with your actual username and password for the SQL server.
> 
> If you continue to encounter issues after trying these steps, please provide more details about your setup, such as your Python version, LangChain version, and operating system. This will help us better understand your issue and provide more targeted assistance.
> 
> As for your question, yes, the LangChain framework does support connections to Microsoft SQL Server databases. This is because LangChain uses SQLAlchemy as its database toolkit, which supports a variety of SQL databases, including Microsoft SQL Server. The `SQLDatabase` class in LangChain has a method `from_uri` which accepts a database URI and constructs a SQLAlchemy engine from it. This engine can be used to connect to any SQL database that SQLAlchemy supports, including Microsoft SQL Server.
> 
> I hope this helps! Let me know if you have any other questions.
> 
> ## Sources
> * [libs/langchain/langchain/utilities/sql_database.py](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/langchain/utilities/sql_database.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

@dosu-bot
db = SQLDatabase.from_uri(
"mssql+pyodbc://user1:Aksiq@312@DESKTOP-17L7UI1\SQLEXPRESS/DociQDb?driver=SQL+Server",)

I have change the connection_string to your desire pattern
but it show error
sqlalchemy.exc.OperationalError: (pyodbc.OperationalError) ('08001', '[08001] [Microsoft][ODBC SQL Server Driver][DBNETLIB]SQL Server does not exist or access denied. (17) (SQLDriverConnect); [08001] [Microsoft][ODBC SQL Server Driver][DBNETLIB]ConnectionOpen (Connect()). (53)')

**Comment by imsunnykr** [comment]
> @dosu-bot The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "D:\OmniExtract\src\api\Cheque\chatTest.py", line 31, in db = SQLDatabase.from_uri( File "C:\Users\dell\PycharmProjects\TravelIQ-Backend-test_environment\TravelIQ_update\OmniExtract\lib\site-packages\langchain\utilities\sql_database.py", line 124, in from_uri return cls(create_engine(database_uri, **_engine_args), **kwargs) File "C:\Users\dell\PycharmProjects\TravelIQ-Backend-test_environment\TravelIQ_update\OmniExtract\lib\site-packages\langchain\utilities\sql_database.py", line 65, in **init** self._inspector.get_table_names(schema=schema) File "C:\Users\dell\PycharmProjects\TravelIQ-Backend-test_environment\TravelIQ_update\OmniExtract\lib\site-packages\sqlalchemy\engine\reflection.py", line 397, in get_table_names return self.dialect.get_table_names( File "", line 2, in get_table_names File "C:\Users\dell\PycharmProjects\TravelIQ-Backend-test_environment\TravelIQ_update\OmniExtract\lib\site-packages\sqlalchemy\engine\reflection.py", line 97, in cache ret = fn(self, con, *args, **kw) File "C:\Users\dell\PycharmProjects\TravelIQ-Backend-test_environment\TravelIQ_update\OmniExtract\lib\site-packages\sqlalchemy\dialects\mssql\base.py", line 2827, in wrap return _switch_db( File "C:\Users\dell\PycharmProjects\TravelIQ-Backend-test_environment\TravelIQ_update\OmniExtract\lib\site-packages\sqlalchemy\dialects\mssql\base.py", line 2869, in _switch_db return fn(*arg, **kw) File "C:\Users\dell\PycharmProjects\TravelIQ-Backend-test_environment\TravelIQ_update\OmniExtract\lib\site-packages\sqlalchemy\dialects\mssql\base.py", line 3306, in get_table_names table_names = [r[0] for r in connection.execute(s)] File "C:\Users\dell\PycharmProjects\TravelIQ-Backend-test_environment\TravelIQ_update\OmniExtract\lib\site-packages\sqlalchemy\engine\base.py", line 1414, in execute return meth( File "C:\Users\dell\PycharmProjects\TravelIQ-Backend-test_environment\TravelIQ_update\OmniExtract\lib\site-packages\sqlalchemy\sql\elements.py", line 486, in _execute_on_connection return connection._execute_clauseelement( File "C:\Users\dell\PycharmProjects\TravelIQ-Backend-test_environment\TravelIQ_update\OmniExtract\lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement ret = self._execute_context( File "C:\Users\dell\PycharmProjects\TravelIQ-Backend-test_environment\TravelIQ_update\OmniExtract\lib\site-packages\sqlalchemy\engine\base.py", line 1842, in _execute_context return self._exec_single_context( File "C:\Users\dell\PycharmProjects\TravelIQ-Backend-test_environment\TravelIQ_update\OmniExtract\lib\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context self._handle_dbapi_exception( File "C:\Users\dell\PycharmProjects\TravelIQ-Backend-test_environment\TravelIQ_update\OmniExtract\lib\site-packages\sqlalchemy\engine\base.py", line 2326, in _handle_dbapi_exception raise sqlalchemy_exception.with_traceback(exc_info[2]) from e File "C:\Users\dell\PycharmProjects\TravelIQ-Backend-test_environment\TravelIQ_update\OmniExtract\lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context self.dialect.do_execute( File "C:\Users\dell\PycharmProjects\TravelIQ-Backend-test_environment\TravelIQ_update\OmniExtract\lib\site-packages\sqlalchemy\engine\default.py", line 748, in do_execute cursor.execute(statement, parameters) sqlalchemy.exc.DBAPIError: (pyodbc.Error) ('HY104', '[HY104] [Microsoft][ODBC SQL Server Driver]Invalid precision value (0) (SQLBindParameter)') [SQL: SELECT [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME] FROM [INFORMATION_SCHEMA].[TABLES] WHERE [INFORMATION_SCHEMA].[TABLES].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_TYPE] = CAST(? AS NVARCHAR(max)) ORDER BY [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME]] [parameters: ('dbo', 'BASE TABLE')]



You can change the drive name with ODBC+Driver+17+for+SQL+Server in place of SQL+Server , this may solve your issue

Example below 

db = SQLDatabase.from_uri(
"mssql+pyodbc://username:password@DESKTOP-17L7UI1\SQLEXPRESS/DociQDb?driver=ODBC+Driver+17+for+SQL+Server")

**Comment by satishgoml** [comment]
> Hi, @AnasKhan-25! I'm Dosu, and I'm here to help the LangChain team manage our backlog. I wanted to let you know that we are marking this issue as stale.
> 
> Based on the information provided, it seems that you were experiencing an issue when trying to connect MS-SQL with LANG-CHAIN. Initially, you were getting an error message "Data source name too long". In response, I suggested that the issue might be with the connection string and advised you to use the MS-SQL driver instead of the MySQL driver. You mentioned that you tried the suggested solution but encountered a new error message. I then suggested that the new error might be related to the precision of decimal values being inserted or updated in the database and advised you to check your data and database schema.
> 
> Before we proceed, we would like to confirm if this issue is still relevant to the latest version of the LangChain repository. If it is, please let us know by commenting on this issue. Otherwise, feel free to close the issue yourself, or the issue will be automatically closed in 7 days.
> 
> Thank you for your understanding, and we look forward to hearing from you soon!
> 
> Best regards, [Dosu](https://dosu.dev)

db = SQLDatabase.from_uri(f'mssql+pyodbc://username:password@mis-db.crg4umutboef.ap-south-1.rds.amazonaws.com/EssTee?driver=ODBC+Driver+17+for+SQL+Server')
the code is keep on running  it is not connection

**Comment by shivamsh314** [comment]
was anyone able to resolve this issue?

**Comment by gobielum** [comment]
@AnasKhan-25, in reply to your first question. I did this to resolve the issue:

import langchain
import pyodbc
from langchain.agents import create_sql_agent
from langchain.agents.agent_toolkits import SQLDatabaseToolkit
from langchain.agents.agent_types import AgentType
from langchain.chains.sql_database.query import create_sql_query_chain
from langchain.chat_models import ChatOpenAI
from langchain.llms.openai import OpenAI
from langchain.sql_database import SQLDatabase
from langchain.utilities import SQLDatabase
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

server= 'xxxxxxx'
database='xxxxxxxx'
user='xxxxxx'
password='xxxxxxx'
my_odbc_driver = "ODBC Driver 17 for SQL Server" #check your odbc driver for the correct version

connection_url = URL.create(
    "mssql+pyodbc",
    username=user,
    password=password,
    host=server,
    database=database,
    query={"driver": my_odbc_driver},
)

connection_string= (connection_url)
engine_args = {"echo": False}  # Optional engine arguments
db = SQLDatabase.from_uri(connection_string, engine_args)

**Comment by KodumuruRaja1999** [comment]
the connection is running continuously without any output. please help me.

**Comment by abel-blue** [comment]
@gobielum you are correct, thanks for the fix.
