### ISSUE TITLE
LangChain cannot deal with new OpenLLM Version (0.2.27)

### ISSUE THREAD

**Issue by Bernsai** [langchain-ai/langchain#9923]
### System Info

LangChain: 0.0.275
OpenLLM: 0.2.27
Python: 3.11.1

on Ubuntu 22.04 / Windows 11

### Who can help?

@agola11, @hwchase17

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### On the server side:
1. `conda create --name openllm python=3.11`
2. `conda activate openllm`
3. `pip install openllm`
4. `openllm start llama --model_id meta-llama/Llama-2-13b-chat-hf`

### On the client side / my local machine:
1. `conda create --name openllm python=3.11`
2. `conda activate openllm`
3. `pip install openllm`
4. Execute the following script:

```python
from langchain.llms import OpenLLM

llm = OpenLLM(server_url='http://<server-ip>:3000')
print(llm("What is the difference between a duck and a goose?"))
```

Then, the following error comes up (similar scripts produce the same error):
```bash
File "C:\Users\<User>\.virtualenvs\<env-name>-wcEN-LyC\Lib\site-packages\langchain\load\serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Generation
text
  str type expected (type=type_error.str)
```

I could solve the error manually by adapting `langchain/llms/base.py` at line 985 to the following line:
```python
generations.append([Generation(text=text["text"], generation_info=text)])
```

### Expected behavior

I would expect, the provided example script works fine, successfully requests text generation from the deployed server, and returns that text to the user / program.

**Comment by Bernsai** [comment]
@dosu-bot My fix is rather a workaround than a real fix. I would appreciate adding this fix to `langchain/llms/ openLlm.py‘ in the correct way.

**Comment by srijitcn** [comment]
I am facing the same issue thats mentioned here. `
```
from langchain.agents import Tool, initialize_agent, AgentExecutor, create_react_agent, create_structured_chat_agent
from langchain.schema.output_parser import StrOutputParser

llm_model_agent = ChatDatabricks(endpoint="databricks-llama-2-70b-chat",max_tokens = 200, temperature=0.1, )
prompt_agent = ChatPromptTemplate.from_template("Follow the instruction: {question}")

agent_chain = LLMChain(
    llm = llm_model_agent,
    prompt = prompt_agent,
    output_parser=StrOutputParser()
)

general_tool = Tool(
    name="General Question Answer",
    func=agent_chain.run,
    description="Tool for general question answer"
)
tools = [general_tool]

from langchain_core.tools import ToolException
from langchain import hub

def _handle_error(error: ToolException) -> str:
    return (
        "The following errors occurred during tool execution:"
        + error.args[0]
        + "Please try another tool."
    )

prompt = hub.pull("hwchase17/react")

agent = create_react_agent(
    tools = tools,
    llm = agent_chain,
    prompt = prompt    
)
agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)
agent_executor.invoke({"input": "what is LangChain?"})

```

This code gives me the below error
```
ValidationError: 1 validation error for Generation
text
  str type expected (type=type_error.str)
```

Full trace ie below

```Entering new AgentExecutor chain...
ValidationError: 1 validation error for Generation
text
  str type expected (type=type_error.str)
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
File <command-815870528791451>, line 2
      1 agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True,return_intermediate_steps=True)
----> 2 agent_executor.invoke({"input": "what is LangChain?", "agent_scratchpad":[]})
File /local_disk0/.ephemeral_nfs/envs/pythonEnv-961f8f16-1015-48a0-973e-42a18f558004/lib/python3.10/site-packages/langchain/chains/base.py:162, in Chain.invoke(self, input, config, **kwargs)
    160 except BaseException as e:
    161     run_manager.on_chain_error(e)
--> 162     raise e
    163 run_manager.on_chain_end(outputs)
    164 final_outputs: Dict[str, Any] = self.prep_outputs(
    165     inputs, outputs, return_only_outputs
    166 )

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-961f8f16-1015-48a0-973e-42a18f558004/lib/python3.10/site-packages/langchain/chains/base.py:156, in Chain.invoke(self, input, config, **kwargs)
    149 run_manager = callback_manager.on_chain_start(
    150     dumpd(self),
    151     inputs,
    152     name=run_name,
    153 )
    154 try:
    155     outputs = (
--> 156         self._call(inputs, run_manager=run_manager)
    157         if new_arg_supported
    158         else self._call(inputs)
    159     )
    160 except BaseException as e:
    161     run_manager.on_chain_error(e)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-961f8f16-1015-48a0-973e-42a18f558004/lib/python3.10/site-packages/langchain/agents/agent.py:1371, in AgentExecutor._call(self, inputs, run_manager)
   1369 # We now enter the agent loop (until it returns something).
   1370 while self._should_continue(iterations, time_elapsed):
-> 1371     next_step_output = self._take_next_step(
   1372         name_to_tool_map,
   1373         color_mapping,
   1374         inputs,
   1375         intermediate_steps,
   1376         run_manager=run_manager,
   1377     )
   1378     if isinstance(next_step_output, AgentFinish):
   1379         return self._return(
   1380             next_step_output, intermediate_steps, run_manager=run_manager
   1381         )

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-961f8f16-1015-48a0-973e-42a18f558004/lib/python3.10/site-packages/langchain/agents/agent.py:1097, in AgentExecutor._take_next_step(self, name_to_tool_map, color_mapping, inputs, intermediate_steps, run_manager)
   1088 def _take_next_step(
   1089     self,
   1090     name_to_tool_map: Dict[str, BaseTool],
   (...)
   1094     run_manager: Optional[CallbackManagerForChainRun] = None,
   1095 ) -> Union[AgentFinish, List[Tuple[AgentAction, str]]]:
   1096     return self._consume_next_step(
-> 1097         [
   1098             a
   1099             for a in self._iter_next_step(
   1100                 name_to_tool_map,
   1101                 color_mapping,
   1102                 inputs,
   1103                 intermediate_steps,
   1104                 run_manager,
   1105             )
   1106         ]
   1107     )

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-961f8f16-1015-48a0-973e-42a18f558004/lib/python3.10/site-packages/langchain/agents/agent.py:1097, in <listcomp>(.0)
   1088 def _take_next_step(
   1089     self,
   1090     name_to_tool_map: Dict[str, BaseTool],
   (...)
   1094     run_manager: Optional[CallbackManagerForChainRun] = None,
   1095 ) -> Union[AgentFinish, List[Tuple[AgentAction, str]]]:
   1096     return self._consume_next_step(
-> 1097         [
   1098             a
   1099             for a in self._iter_next_step(
   1100                 name_to_tool_map,
   1101                 color_mapping,
   1102                 inputs,
   1103                 intermediate_steps,
   1104                 run_manager,
   1105             )
   1106         ]
   1107     )

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-961f8f16-1015-48a0-973e-42a18f558004/lib/python3.10/site-packages/langchain/agents/agent.py:1125, in AgentExecutor._iter_next_step(self, name_to_tool_map, color_mapping, inputs, intermediate_steps, run_manager)
   1122     intermediate_steps = self._prepare_intermediate_steps(intermediate_steps)
   1124     # Call the LLM to see what to do.
-> 1125     output = self.agent.plan(
   1126         intermediate_steps,
   1127         callbacks=run_manager.get_child() if run_manager else None,
   1128         **inputs,
   1129     )
   1130 except OutputParserException as e:
   1131     if isinstance(self.handle_parsing_errors, bool):

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-961f8f16-1015-48a0-973e-42a18f558004/lib/python3.10/site-packages/langchain/agents/agent.py:387, in RunnableAgent.plan(self, intermediate_steps, callbacks, **kwargs)
    381 # Use streaming to make sure that the underlying LLM is invoked in a streaming
    382 # fashion to make it possible to get access to the individual LLM tokens
    383 # when using stream_log with the Agent Executor.
    384 # Because the response from the plan is not a generator, we need to
    385 # accumulate the output into final output and return that.
    386 final_output: Any = None
--> 387 for chunk in self.runnable.stream(inputs, config={"callbacks": callbacks}):
    388     if final_output is None:
    389         final_output = chunk

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-961f8f16-1015-48a0-973e-42a18f558004/lib/python3.10/site-packages/langchain_core/runnables/base.py:2424, in RunnableSequence.stream(self, input, config, **kwargs)
   2418 def stream(
   2419     self,
   2420     input: Input,
   2421     config: Optional[RunnableConfig] = None,
   2422     **kwargs: Optional[Any],
   2423 ) -> Iterator[Output]:
-> 2424     yield from self.transform(iter([input]), config, **kwargs)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-961f8f16-1015-48a0-973e-42a18f558004/lib/python3.10/site-packages/langchain_core/runnables/base.py:2411, in RunnableSequence.transform(self, input, config, **kwargs)
   2405 def transform(
   2406     self,
   2407     input: Iterator[Input],
   2408     config: Optional[RunnableConfig] = None,
   2409     **kwargs: Optional[Any],
   2410 ) -> Iterator[Output]:
-> 2411     yield from self._transform_stream_with_config(
   2412         input,
   2413         self._transform,
   2414         patch_config(config, run_name=(config or {}).get("run_name") or self.name),
   2415         **kwargs,
   2416     )

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-961f8f16-1015-48a0-973e-42a18f558004/lib/python3.10/site-packages/langchain_core/runnables/base.py:1497, in Runnable._transform_stream_with_config(self, input, transformer, config, run_type, **kwargs)
   1495 try:
   1496     while True:
-> 1497         chunk: Output = context.run(next, iterator)  # type: ignore
   1498         yield chunk
   1499         if final_output_supported:

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-961f8f16-1015-48a0-973e-42a18f558004/lib/python3.10/site-packages/langchain_core/runnables/base.py:2375, in RunnableSequence._transform(self, input, run_manager, config)
   2366 for step in steps:
   2367     final_pipeline = step.transform(
   2368         final_pipeline,
   2369         patch_config(
   (...)
   2372         ),
   2373     )
-> 2375 for output in final_pipeline:
   2376     yield output

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-961f8f16-1015-48a0-973e-42a18f558004/lib/python3.10/site-packages/langchain_core/runnables/base.py:1045, in Runnable.transform(self, input, config, **kwargs)
   1042         final = final + chunk  # type: ignore[operator]
   1044 if got_first_val:
-> 1045     yield from self.stream(final, config, **kwargs)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-961f8f16-1015-48a0-973e-42a18f558004/lib/python3.10/site-packages/langchain_core/runnables/base.py:580, in Runnable.stream(self, input, config, **kwargs)
    570 def stream(
    571     self,
    572     input: Input,
    573     config: Optional[RunnableConfig] = None,
    574     **kwargs: Optional[Any],
    575 ) -> Iterator[Output]:
    576     """
    577     Default implementation of stream, which calls invoke.
    578     Subclasses should override this method if they support streaming output.
    579     """
--> 580     yield self.invoke(input, config, **kwargs)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-961f8f16-1015-48a0-973e-42a18f558004/lib/python3.10/site-packages/langchain_core/output_parsers/base.py:176, in BaseOutputParser.invoke(self, input, config)
    167     return self._call_with_config(
    168         lambda inner_input: self.parse_result(
    169             [ChatGeneration(message=inner_input)]
   (...)
    173         run_type="parser",
    174     )
    175 else:
--> 176     return self._call_with_config(
    177         lambda inner_input: self.parse_result([Generation(text=inner_input)]),
    178         input,
    179         config,
    180         run_type="parser",
    181     )

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-961f8f16-1015-48a0-973e-42a18f558004/lib/python3.10/site-packages/langchain_core/runnables/base.py:1246, in Runnable._call_with_config(self, func, input, config, run_type, **kwargs)
   1242     context = copy_context()
   1243     context.run(var_child_runnable_config.set, child_config)
   1244     output = cast(
   1245         Output,
-> 1246         context.run(
   1247             call_func_with_variable_args,
   1248             func,  # type: ignore[arg-type]
   1249             input,  # type: ignore[arg-type]
   1250             config,
   1251             run_manager,
   1252             **kwargs,
   1253         ),
   1254     )
   1255 except BaseException as e:
   1256     run_manager.on_chain_error(e)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-961f8f16-1015-48a0-973e-42a18f558004/lib/python3.10/site-packages/langchain_core/runnables/config.py:326, in call_func_with_variable_args(func, input, config, run_manager, **kwargs)
    324 if run_manager is not None and accepts_run_manager(func):
    325     kwargs["run_manager"] = run_manager
--> 326 return func(input, **kwargs)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-961f8f16-1015-48a0-973e-42a18f558004/lib/python3.10/site-packages/langchain_core/output_parsers/base.py:177, in BaseOutputParser.invoke.<locals>.<lambda>(inner_input)
    167     return self._call_with_config(
    168         lambda inner_input: self.parse_result(
    169             [ChatGeneration(message=inner_input)]
   (...)
    173         run_type="parser",
    174     )
    175 else:
    176     return self._call_with_config(
--> 177         lambda inner_input: self.parse_result([Generation(text=inner_input)]),
    178         input,
    179         config,
    180         run_type="parser",
    181     )

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-961f8f16-1015-48a0-973e-42a18f558004/lib/python3.10/site-packages/langchain_core/load/serializable.py:107, in Serializable.__init__(self, **kwargs)
    106 def __init__(self, **kwargs: Any) -> None:
--> 107     super().__init__(**kwargs)
    108     self._lc_kwargs = kwargs

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/pydantic/v1/main.py:341, in BaseModel.__init__(__pydantic_self__, **data)
    339 values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
    340 if validation_error:
--> 341     raise validation_error
    342 try:
    343     object_setattr(__pydantic_self__, '__dict__', values)

ValidationError: 1 validation error for Generation
text
  str type expected (type=type_error.str)
```

**Comment by elorberb** [comment]
> I am facing the same issue thats mentioned here. `
> 
> ```
> from langchain.agents import Tool, initialize_agent, AgentExecutor, create_react_agent, create_structured_chat_agent
> from langchain.schema.output_parser import StrOutputParser
> 
> llm_model_agent = ChatDatabricks(endpoint="databricks-llama-2-70b-chat",max_tokens = 200, temperature=0.1, )
> prompt_agent = ChatPromptTemplate.from_template("Follow the instruction: {question}")
> 
> agent_chain = LLMChain(
>     llm = llm_model_agent,
>     prompt = prompt_agent,
>     output_parser=StrOutputParser()
> )
> 
> general_tool = Tool(
>     name="General Question Answer",
>     func=agent_chain.run,
>     description="Tool for general question answer"
> )
> tools = [general_tool]
> 
> from langchain_core.tools import ToolException
> from langchain import hub
> 
> prompt = hub.pull("hwchase17/react")
> 
> agent = create_react_agent(
>     tools = tools,
>     llm = agent_chain,
>     prompt = prompt    
> )
> agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)
> agent_executor.invoke({"input": "what is LangChain?"})
> ```
> 
> This code gives me the below error
> 
> ```
> ValidationError: 1 validation error for Generation
> text
>   str type expected (type=type_error.str)
> ```
> 
> Full trace ie below
> 
> ```
> ValidationError: 1 validation error for Generation
> text
>   str type expected (type=type_error.str)
> ---------------------------------------------------------------------------
> ValidationError                           Traceback (most recent call last)
> File <command-815870528791451>, line 2
>       1 agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True,return_intermediate_steps=True)
> ----> 2 agent_executor.invoke({"input": "what is LangChain?", "agent_scratchpad":[]})
> File /local_disk0/.ephemeral_nfs/envs/pythonEnv-961f8f16-1015-48a0-973e-42a18f558004/lib/python3.10/site-packages/langchain/chains/base.py:162, in Chain.invoke(self, input, config, **kwargs)
>     160 except BaseException as e:
>     161     run_manager.on_chain_error(e)
> --> 162     raise e
>     163 run_manager.on_chain_end(outputs)
>     164 final_outputs: Dict[str, Any] = self.prep_outputs(
>     165     inputs, outputs, return_only_outputs
>     166 )
> 
> File /local_disk0/.ephemeral_nfs/envs/pythonEnv-961f8f16-1015-48a0-973e-42a18f558004/lib/python3.10/site-packages/langchain/chains/base.py:156, in Chain.invoke(self, input, config, **kwargs)
>     149 run_manager = callback_manager.on_chain_start(
>     150     dumpd(self),
>     151     inputs,
>     152     name=run_name,
>     153 )
>     154 try:
>     155     outputs = (
> --> 156         self._call(inputs, run_manager=run_manager)
>     157         if new_arg_supported
>     158         else self._call(inputs)
>     159     )
>     160 except BaseException as e:
>     161     run_manager.on_chain_error(e)
> 
> File /local_disk0/.ephemeral_nfs/envs/pythonEnv-961f8f16-1015-48a0-973e-42a18f558004/lib/python3.10/site-packages/langchain/agents/agent.py:1371, in AgentExecutor._call(self, inputs, run_manager)
>    1369 # We now enter the agent loop (until it returns something).
>    1370 while self._should_continue(iterations, time_elapsed):
> -> 1371     next_step_output = self._take_next_step(
>    1372         name_to_tool_map,
>    1373         color_mapping,
>    1374         inputs,
>    1375         intermediate_steps,
>    1376         run_manager=run_manager,
>    1377     )
>    1378     if isinstance(next_step_output, AgentFinish):
>    1379         return self._return(
>    1380             next_step_output, intermediate_steps, run_manager=run_manager
>    1381         )
> 
> File /local_disk0/.ephemeral_nfs/envs/pythonEnv-961f8f16-1015-48a0-973e-42a18f558004/lib/python3.10/site-packages/langchain/agents/agent.py:1097, in AgentExecutor._take_next_step(self, name_to_tool_map, color_mapping, inputs, intermediate_steps, run_manager)
>    1088 def _take_next_step(
>    1089     self,
>    1090     name_to_tool_map: Dict[str, BaseTool],
>    (...)
>    1094     run_manager: Optional[CallbackManagerForChainRun] = None,
>    1095 ) -> Union[AgentFinish, List[Tuple[AgentAction, str]]]:
>    1096     return self._consume_next_step(
> -> 1097         [
>    1098             a
>    1099             for a in self._iter_next_step(
>    1100                 name_to_tool_map,
>    1101                 color_mapping,
>    1102                 inputs,
>    1103                 intermediate_steps,
>    1104                 run_manager,
>    1105             )
>    1106         ]
>    1107     )
> 
> File /local_disk0/.ephemeral_nfs/envs/pythonEnv-961f8f16-1015-48a0-973e-42a18f558004/lib/python3.10/site-packages/langchain/agents/agent.py:1097, in <listcomp>(.0)
>    1088 def _take_next_step(
>    1089     self,
>    1090     name_to_tool_map: Dict[str, BaseTool],
>    (...)
>    1094     run_manager: Optional[CallbackManagerForChainRun] = None,
>    1095 ) -> Union[AgentFinish, List[Tuple[AgentAction, str]]]:
>    1096     return self._consume_next_step(
> -> 1097         [
>    1098             a
>    1099             for a in self._iter_next_step(
>    1100                 name_to_tool_map,
>    1101                 color_mapping,
>    1102                 inputs,
>    1103                 intermediate_steps,
>    1104                 run_manager,
>    1105             )
>    1106         ]
>    1107     )
> 
> File /local_disk0/.ephemeral_nfs/envs/pythonEnv-961f8f16-1015-48a0-973e-42a18f558004/lib/python3.10/site-packages/langchain/agents/agent.py:1125, in AgentExecutor._iter_next_step(self, name_to_tool_map, color_mapping, inputs, intermediate_steps, run_manager)
>    1122     intermediate_steps = self._prepare_intermediate_steps(intermediate_steps)
>    1124     # Call the LLM to see what to do.
> -> 1125     output = self.agent.plan(
>    1126         intermediate_steps,
>    1127         callbacks=run_manager.get_child() if run_manager else None,
>    1128         **inputs,
>    1129     )
>    1130 except OutputParserException as e:
>    1131     if isinstance(self.handle_parsing_errors, bool):
> 
> File /local_disk0/.ephemeral_nfs/envs/pythonEnv-961f8f16-1015-48a0-973e-42a18f558004/lib/python3.10/site-packages/langchain/agents/agent.py:387, in RunnableAgent.plan(self, intermediate_steps, callbacks, **kwargs)
>     381 # Use streaming to make sure that the underlying LLM is invoked in a streaming
>     382 # fashion to make it possible to get access to the individual LLM tokens
>     383 # when using stream_log with the Agent Executor.
>     384 # Because the response from the plan is not a generator, we need to
>     385 # accumulate the output into final output and return that.
>     386 final_output: Any = None
> --> 387 for chunk in self.runnable.stream(inputs, config={"callbacks": callbacks}):
>     388     if final_output is None:
>     389         final_output = chunk
> 
> File /local_disk0/.ephemeral_nfs/envs/pythonEnv-961f8f16-1015-48a0-973e-42a18f558004/lib/python3.10/site-packages/langchain_core/runnables/base.py:2424, in RunnableSequence.stream(self, input, config, **kwargs)
>    2418 def stream(
>    2419     self,
>    2420     input: Input,
>    2421     config: Optional[RunnableConfig] = None,
>    2422     **kwargs: Optional[Any],
>    2423 ) -> Iterator[Output]:
> -> 2424     yield from self.transform(iter([input]), config, **kwargs)
> 
> File /local_disk0/.ephemeral_nfs/envs/pythonEnv-961f8f16-1015-48a0-973e-42a18f558004/lib/python3.10/site-packages/langchain_core/runnables/base.py:2411, in RunnableSequence.transform(self, input, config, **kwargs)
>    2405 def transform(
>    2406     self,
>    2407     input: Iterator[Input],
>    2408     config: Optional[RunnableConfig] = None,
>    2409     **kwargs: Optional[Any],
>    2410 ) -> Iterator[Output]:
> -> 2411     yield from self._transform_stream_with_config(
>    2412         input,
>    2413         self._transform,
>    2414         patch_config(config, run_name=(config or {}).get("run_name") or self.name),
>    2415         **kwargs,
>    2416     )
> 
> File /local_disk0/.ephemeral_nfs/envs/pythonEnv-961f8f16-1015-48a0-973e-42a18f558004/lib/python3.10/site-packages/langchain_core/runnables/base.py:1497, in Runnable._transform_stream_with_config(self, input, transformer, config, run_type, **kwargs)
>    1495 try:
>    1496     while True:
> -> 1497         chunk: Output = context.run(next, iterator)  # type: ignore
>    1498         yield chunk
>    1499         if final_output_supported:
> 
> File /local_disk0/.ephemeral_nfs/envs/pythonEnv-961f8f16-1015-48a0-973e-42a18f558004/lib/python3.10/site-packages/langchain_core/runnables/base.py:2375, in RunnableSequence._transform(self, input, run_manager, config)
>    2366 for step in steps:
>    2367     final_pipeline = step.transform(
>    2368         final_pipeline,
>    2369         patch_config(
>    (...)
>    2372         ),
>    2373     )
> -> 2375 for output in final_pipeline:
>    2376     yield output
> 
> File /local_disk0/.ephemeral_nfs/envs/pythonEnv-961f8f16-1015-48a0-973e-42a18f558004/lib/python3.10/site-packages/langchain_core/runnables/base.py:1045, in Runnable.transform(self, input, config, **kwargs)
>    1042         final = final + chunk  # type: ignore[operator]
>    1044 if got_first_val:
> -> 1045     yield from self.stream(final, config, **kwargs)
> 
> File /local_disk0/.ephemeral_nfs/envs/pythonEnv-961f8f16-1015-48a0-973e-42a18f558004/lib/python3.10/site-packages/langchain_core/runnables/base.py:580, in Runnable.stream(self, input, config, **kwargs)
>     570 def stream(
>     571     self,
>     572     input: Input,
>     573     config: Optional[RunnableConfig] = None,
>     574     **kwargs: Optional[Any],
>     575 ) -> Iterator[Output]:
>     576     """
>     577     Default implementation of stream, which calls invoke.
>     578     Subclasses should override this method if they support streaming output.
>     579     """
> --> 580     yield self.invoke(input, config, **kwargs)
> 
> File /local_disk0/.ephemeral_nfs/envs/pythonEnv-961f8f16-1015-48a0-973e-42a18f558004/lib/python3.10/site-packages/langchain_core/output_parsers/base.py:176, in BaseOutputParser.invoke(self, input, config)
>     167     return self._call_with_config(
>     168         lambda inner_input: self.parse_result(
>     169             [ChatGeneration(message=inner_input)]
>    (...)
>     173         run_type="parser",
>     174     )
>     175 else:
> --> 176     return self._call_with_config(
>     177         lambda inner_input: self.parse_result([Generation(text=inner_input)]),
>     178         input,
>     179         config,
>     180         run_type="parser",
>     181     )
> 
> File /local_disk0/.ephemeral_nfs/envs/pythonEnv-961f8f16-1015-48a0-973e-42a18f558004/lib/python3.10/site-packages/langchain_core/runnables/base.py:1246, in Runnable._call_with_config(self, func, input, config, run_type, **kwargs)
>    1242     context = copy_context()
>    1243     context.run(var_child_runnable_config.set, child_config)
>    1244     output = cast(
>    1245         Output,
> -> 1246         context.run(
>    1247             call_func_with_variable_args,
>    1248             func,  # type: ignore[arg-type]
>    1249             input,  # type: ignore[arg-type]
>    1250             config,
>    1251             run_manager,
>    1252             **kwargs,
>    1253         ),
>    1254     )
>    1255 except BaseException as e:
>    1256     run_manager.on_chain_error(e)
> 
> File /local_disk0/.ephemeral_nfs/envs/pythonEnv-961f8f16-1015-48a0-973e-42a18f558004/lib/python3.10/site-packages/langchain_core/runnables/config.py:326, in call_func_with_variable_args(func, input, config, run_manager, **kwargs)
>     324 if run_manager is not None and accepts_run_manager(func):
>     325     kwargs["run_manager"] = run_manager
> --> 326 return func(input, **kwargs)
> 
> File /local_disk0/.ephemeral_nfs/envs/pythonEnv-961f8f16-1015-48a0-973e-42a18f558004/lib/python3.10/site-packages/langchain_core/output_parsers/base.py:177, in BaseOutputParser.invoke.<locals>.<lambda>(inner_input)
>     167     return self._call_with_config(
>     168         lambda inner_input: self.parse_result(
>     169             [ChatGeneration(message=inner_input)]
>    (...)
>     173         run_type="parser",
>     174     )
>     175 else:
>     176     return self._call_with_config(
> --> 177         lambda inner_input: self.parse_result([Generation(text=inner_input)]),
>     178         input,
>     179         config,
>     180         run_type="parser",
>     181     )
> 
> File /local_disk0/.ephemeral_nfs/envs/pythonEnv-961f8f16-1015-48a0-973e-42a18f558004/lib/python3.10/site-packages/langchain_core/load/serializable.py:107, in Serializable.__init__(self, **kwargs)
>     106 def __init__(self, **kwargs: Any) -> None:
> --> 107     super().__init__(**kwargs)
>     108     self._lc_kwargs = kwargs
> 
> File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/pydantic/v1/main.py:341, in BaseModel.__init__(__pydantic_self__, **data)
>     339 values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
>     340 if validation_error:
> --> 341     raise validation_error
>     342 try:
>     343     object_setattr(__pydantic_self__, '__dict__', values)
> 
> ValidationError: 1 validation error for Generation
> text
>   str type expected (type=type_error.str)
> ```

Same for me when using an agent as the llm for the chain. 
Did you managed to solve that issue?
